### ISSUE TITLE
ip_score produces error messages in log file

### ISSUE THREAD

**Issue by croessner** [vstakhov/rspamd#1010]
I tried to configure ip_score with the updated module documentation. Still I can not get it working. I get error messgaes in the log file:

`Oct  6 09:41:57 mx rspamd[27176]: <f1c8ce>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 09:42:03 mx rspamd[27176]: <3ddc0e>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 09:47:13 mx rspamd[27175]: <f4f12a>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 09:47:41 mx rspamd[27175]: <1694d2>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 09:51:41 mx rspamd[27175]: <a04fbc>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 09:53:48 mx rspamd[27176]: <918de7>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 09:54:41 mx rspamd[27173]: <759b51>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 09:57:50 mx rspamd[27175]: <2f18cf>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 09:59:00 mx rspamd[27175]: <01e5ba>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 10:01:29 mx rspamd[27175]: <4aa805>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 10:02:11 mx rspamd[27173]: <c75aab>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};
Oct  6 10:02:51 mx rspamd[27175]: <d76b51>; task; lua_metric_symbol_callback: call to (IPSCORE_SAVE) failed: /usr/share/rspamd/lua/ip_score.lua:200: attempt to compare userdata with number; trace: [1]:{/usr/share/rspamd/lua/ip_score.lua:200 - <unknown> [Lua]};`

My config goes like this:

/etc/rspamd/rspamd.conf.local:

`redis {
        servers = "127.0.0.1";
}

asn {
        # Provider: just "cymru" for now
        provider_type = "cymru";

        # Provider-specific configuration
        provider_info {
                ip4 = "origin.asn.cymru.com";
                ip6 = "origin6.asn.cymru.com";
        }

        # If defined, insert symbol with lookup results
        symbol = "ASN";
}

ip_score {
        # how each action is treated in scoring
        actions {
                reject = 1.0,
                "add header" = 0.25,
                "rewrite subject" = 0.25,
                "no action" = 1.0
        }

        # how each component is evaluated
        scores {
                asn = 0.5;
                country = 0.1;
                ipnet = 0.8;
                ip = 1.0;
        }

        # provider for ASN data - removed in 1.3.4 - use ASN module
        # asn_provider = "origin.asn.cymru.com";
        # asn6_provider = "origin6.asn.cymru.com";
        # prefix for asn hashes
        asn_prefix = "a:";

        # prefix for country hashes
        country_prefix = "c:";

        # hash table in redis used for storing scores
        hash = "ip_score";

        # prefix for subnet hashes
        ipnet_prefix = "n:";

        # minimum number of messages to be scored
        lower_bound = 10;

        # the metric to score (usually "default")
        metric = "default";

        # upper and lower bounds at which to cap total score
        max_score = null;
        min_score = null;

        # Amount to divide subscores by before applying tanh
        score_divisor = 10;

        # symbol to be inserted
        symbol = "IP_SCORE";
}`

Sorry for code formatting. Github does not work with iPad!

Here is my /etc/rspamd/local.d/metrics.conf:

`symbol "IP_SCORE" {
        weight = 2.0;
        description = "IP reputation";
}`

**Comment by croessner** [comment]
BTW: The backticks are not belonging to the config. I thoguht they might format the code

**Comment by fatalbanana** [comment]
`min_score` and `max_score` should not be set to `null` (rather they should be left unset if not desired).

**Comment by vstakhov** [comment]
~~~
    max_score = null;
    min_score = null;
~~~

That won't work obviously. Just remove these lines to make it working. I have fixed the docs in the meantime. Furthermore, I have changed `asn` module, so I'd recommend to read the updated docs and fix your config. This will work with the recent master (and unstable packages).

**Comment by croessner** [comment]
Thanks. Now it works :-)
