### ISSUE TITLE
adding modules.d/greylist.conf file

### ISSUE THREAD

**Issue by qk4l** [vstakhov/rspamd#1014]
Hello,

What do you think about adding _modules.d/greylist.conf_ conf file with include option as other modules have?

```
greylist {
    .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/greylist.conf"
}
```

**Comment by fatalbanana** [comment]
The problem is that this would implicitly enable greylisting if redis parameters are set & greylisting is also default-enabled in rmilter.

**Comment by fatalbanana** [comment]
It exists these days.
