### ISSUE TITLE
final score added inside header miss the BAYES_HAM score

### ISSUE THREAD

**Issue by Elodie81** [vstakhov/rspamd#1016]
Hello,

I have a serious problem with my rspamd latest version (1.4.0-0~git84~dac58fa~jessie) (but it's same for previous version too), the result score and YES/NO spam information added inside mail header with the LUA script ignore the rule "BAYES_HAM".

Example, if "probably_spam" is set to 5.0 and i receive a mail (with SASL or not) with a score of 10 and a BAYES_HAM of -9, the score inside header won't be 1 but still 10 with a result spam to YES.

A real example -->

> X-Spamd-Result: default: False [0.52 / 30.00]
>  BAYES_HAM(-5.98)[99.91%]
>  FORGED_X_PHP_SCRIPT1(4.00)[]
>  R_NO_SPACE_IN_FROM(1.00)[]
>  SUBJECT_NEEDS_ENCODING(1.00)[]
>  URIBL_BLOCKED(0.00)[xxx.multi.uribl.com]
>  FORGED_RECIPIENTS(0.00)[]
>  MIME_HTML_ONLY(0.20)[]
>  FORGED_SENDER(0.30)[]
> X-Rspamd-Server: 127.0.0.1
> X-Rspamd-Scan-Time: 5.00
> X-Rspamd-Queue-ID: CE032EA00ED
> X-Spamd-Bar: ++++++
> X-Spam-Level: ******
> X-Spam-Score: 6.50
> X-Spam-Status: Yes, score=6.50
> X-Spam-Flag: YES

rspamd know it's not a spam and the score is 0.52 during the scan, but my LUA script inside rspamd will set a score of 6,50 (0.52- (BAYES_HAM) and put YES to X-Spam-Flag. It's a serious problem for me ...

This is my LUA file -->

> rspamd_config:register_symbol({
>   name = 'RMILTER_HEADERS',
>   type = 'postfilter',
>   callback = function(task)
>     local metric_score = task:get_metric_score('default')
>     local score = metric_score[1]
>     local required_score = metric_score[2]
>     -- X-Spamd-Bar & X-Spam-Level
>     local spambar
>     local spamlevel = ''
>     if score < 0 then
>       spambar = string.rep('-', score_-1)
>     elseif score > 0 then
>       spambar = string.rep('+', score_1)
>       spamlevel = string.rep('_', score_1)
>     else
>       spambar = '/'
>     end
>     -- X-Spam-Status
>     local is_spam
>     local spamstatus
>     local action = task:get_metric_action('default')
>     if action ~= 'no action' and action ~= 'greylist' then
>       is_spam = 'YES'
>     else
>       is_spam = 'NO'
>     end
>     spamstatus = is_spam .. ', score=' .. string.format('%.2f', score)
>     -- X-Spam-Score & X-Spam-Flag
>     local spamscore = string.format('%.2f', score)
>     local spamflag = is_spam
>     -- Add headers
>     task:set_rmilter_reply({
>       add_headers = {
>         ['X-Spamd-Bar'] = spambar,
>         ['X-Spam-Level'] = spamlevel,
>         ['X-Spam-Status'] = spamstatus,
>         ['X-Spam-Score'] = spamscore,
>         ['X-Spam-Flag'] = spamflag
>       },
>       remove_headers = {
>         ['X-Spamd-Bar'] = 1,
>         ['X-Spam-Level'] = 1,
>         ['X-Spam-Status'] = 1,
>         ['X-Spam-Score'] = 1,
>         ['X-Spam-Flag'] = 1
>       }
>     })
>   end
> })

Someone could help me please ?

PS. And i'm not using an other anti-spam and spam tag are not added with an other system.

**Comment by fatalbanana** [comment]
This was resolved AFAICR.
