### ISSUE TITLE
Web UI suggestions

### ISSUE THREAD

**Issue by fenice2** [vstakhov/rspamd#1027]
I'm a new user of rspamd and I was using the Web UI History page and inadvertently hit the 'reset' button, this wiped all the data without asking for confirmation. Would it be possible to add a confirmation to this button function?

Would it also be possible to change the number of items on this page (I prefer 100 items shown) and retain the setting rather than change it on each visit to the web UI?

**Comment by moisseev** [comment]
Or maybe it worth to set 100 as default or remove `show entries` selector at all and hardcode value of 100. I don't see any point in lower entries-per-page number.

**Comment by fenice2** [comment]
Yes, a default of 100 is fine for me and I don't need the ability to change it and as we have the search function a higher fixed default would work for me. :)

**Comment by fenice2** [comment]
I can confirm those two changes work, nice job. :)

There is one minor quirk but I don't know if this really matters. When you do the "reset" and confirm it also clears the table and removes the column headers. That does sometimes reappear if you switch to another page, such as Status, then switch back to the History page. This is currently on a test server that has no mail flowing into it today so I guess if there was mail it might refresh on it's own or after hitting 'Update'. If I hit update it doesn't do that it just posts an error 'Cannot receive history'. I guess this might be working as expected but just thought I'd mention it.

Many thanks for the quick fix.

**Comment by moisseev** [comment]
I confirm the issue with history reappearance.
To reproduce:
- Clear history using `Reset` button
- Reload page using `reload` button in browser
- Switch back to the `History` page

There is a message in the log:
```
2016-10-21 13:04:42 #4852(controller) <2535aa>; csession; rspamd_controller_handle_history_reset: <10.0.2.2> reseted history
```
 but `/var/db/rspamd/rspamd.history` file was not cleared.
