### ISSUE TITLE
task->messages and lua

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#1046]
Hi. Please help me. How to add my string to "task->messages" from lua plugin?

**Comment by fatalbanana** [comment]
You want to return 'options' with symbols?

You can do: `return true, 'opt1', 'opt2'`

**Comment by fatalbanana** [comment]
In a plugin: `task:insert_result('SYMBOL_NAME', 1.0, 'opt1', 'opt2')` (sorry, I see now you asked for plugin) ;)

**Comment by AlexeySa** [comment]
I want to add line similar "(SPF:) spf allow".
Example https://github.com/vstakhov/rspamd/blob/master/src/plugins/spf.c#L468

**Comment by fatalbanana** [comment]
Right. ^^ This is how to do it. ;)

**Comment by AlexeySa** [comment]
No, `task:insert_result('TEST_SYMBOL', 1.0, 'opt1', 'opt2')`:
```
Symbol: TEST_SYMBOL (1.00)[opt1, opt2]
Message: (SPF): spf softfail
```

I need this:
```
Symbol: TEST_SYMBOL (1.00)
Message: **My string here**
```

**Comment by fatalbanana** [comment]
Oh! Right ... I see ... I don't believe there's a way to do that atm.

**Comment by AlexeySa** [comment]
Additional options for insert_result output only json :(. My local_scan for exim can not this.
