### ISSUE TITLE
Learning via webui always errors with "Unauthorized"

### ISSUE THREAD

**Issue by djc** [vstakhov/rspamd#1066]
Running 1.3.5, I'm unable to use the web UI to learn (either ham or spam).

**Comment by fenice2** [comment]
I'm no expert with rspamd but have you made any changes to the password in worker-controller.inc? Are you using the "enable_password" option as it's needed for training spam/ham and fuzzy storage.

**Comment by djc** [comment]
Hah, you're right. I changed the password for `enable_password` to be the same as the password for `password`, and now it works.

I suggest having these passwords be separate doesn't actually work for browser-based HTTP auth.

**Comment by fatalbanana** [comment]
Well, you can log in but you can't learn - that seems to be the expected behaviour. What would you suggest?

**Comment by djc** [comment]
I mean, the browser will not prompt for the second password for learning, which is surprising/bad UX.

**Comment by fenice2** [comment]
I'd agree with the above comment, it doesn't prompt for any password other than the (apparently) first one that's in the config file. 

It's also worth mentioning that when the password prompt opens the cursor does not have focus in the password box until you click in there then type the password. It's not a great problem but it should not require any additional clicks, all prompts that require input should have focus and be ready for just typing any required input.

**Comment by vstakhov** [comment]
I think it might also be caused by the fact that I've banned default passwords, namely 'q1' and 'q2' from webui for security concerns.

**Comment by djc** [comment]
It was unrelated to that for me, since I had actually customized both passwords.

**Comment by vstakhov** [comment]
Is it still actual?

**Comment by djc** [comment]
Nope.
