### ISSUE TITLE
[WebUI] Incomplete ID and Symbols columns in History

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#1110]
IDs and Symbols in `ID` and `Symbols` column in `History` are not fully displayed (the same thing in pop-up menu) e.g 
`F46294C4D02D3B4C9B0DAB13EFCA858C880D87AE@R00EXMBX01.main.russia` should be `F46294C4D02D3B4C9B0DAB13EFCA858C880D87AE@R00EXMBX01.main.russianpost.ru`  or `RBL_MAILSPIKE_WORST, ASN, DMARC_POLICY_ALLOW, RBL_SORBS_RECENT, R_DKIM_ALLOW, MIME_GOOD, BAYES_SPAM, ONCE_RECEIVED, FUZZY_DEN`

**Comment by vstakhov** [comment]
Symbols row has hint that is shown when a content of cell overflows its width (`cell-overflow` class). The same is true for message id column.

**Comment by dehnli** [comment]
I send e-mail with screenshot to you

**Comment by dehnli** [comment]
@vstakhov thanks for hint via e-mail

It fixed by increasing `HISTORY_MAX_ID 64` > `HISTORY_MAX_ID 96` and `HISTORY_MAX_SYMBOLS 128` > `HISTORY_MAX_SYMBOLS 256` in `../src/libserver/roll_history.h`
```
#define HISTORY_MAX_ID 64
#define HISTORY_MAX_SYMBOLS 128
```
and recompile at `mail/rspamd` (`FreeBSD 10.3-RELEASE-p2 amd64 GENERIC`)

ps I hope that these values will be included in future releases, because in this case the fields are displayed  completely
