### ISSUE TITLE
Feature-request - Adding AVG virus scanner

### ISSUE THREAD

**Issue by gibzer** [vstakhov/rspamd#1120]
It would be great to add AVG virus scanner in Rspamd.
It's quite well documented here http://af-download.avg.com/filedir/doc/OTHERS/AVG_Linux_daemon_communication_protocol/avg_dcp_oth_en_75_2.pdf and also amavis has support of this scanner:
 ['AVG Anti-Virus', \&ask_daemon, ["SCAN {}\n", '127.0.0.1:54322'], qr/^200/m, qr/^403/m, qr/^403[- ].*?: ([^\r\n]+)/m ]

**Comment by fatalbanana** [comment]
Do you know where/how to get hold of the actual software? I don't find mention of software for *nix on their page.

**Comment by gibzer** [comment]
Yes, they officially doesn't support Linux anymore (no new versions), so some links are hard to find. But even because of that status it still has antivirus databases updates so it's still usable. :)

Download links:
http://download.avgfree.com/filedir/inst/avg2013flx-r3118-a6926.i386.deb
http://download.avgfree.com/filedir/inst/avg2013flx-r3118-a6926.i386.rpm
http://download.avgfree.com/filedir/inst/avg2013flx-r3118-a6926.i386.sh

Documentation: http://aa-download.avg.com/filedir/doc/LINUX_GROUP/AVG_Anti-Virus_for_Linux/avg_avl_uma_en_85_2.pdf

And some useful links about installation:
https://www.rosehosting.com/blog/how-to-install-and-configure-avg-free-anti-virus-on-an-ubuntu-vps/
http://idroot.net/tutorials/how-to-install-avg-free-antivirus-on-ubuntu/
https://www.howtoforge.com/avg-antivirus-for-linux-freebsd-plus-postfix-mail-server
http://webcache.googleusercontent.com/search?q=cache:http://www.techienote.com/how-to-install-avg-free-antivirus-software-on-ubuntu-12-10-12-04/&gws_rd=cr&ei=bnslWJHrE4bUafaoiLgB

**Comment by fatalbanana** [comment]
AVG having support for scanning merely files (and not streams) isn't ideal though in theory this could be supported (and in case where rspamd is scanning a file instead of a stream could be done without cost).

**Comment by gibzer** [comment]
AVG also has milter interface, if this could help.

**Comment by msimerson** [comment]
If anyone is actually interested, I have a shell script that provisions an AVG instance in a FreeBSD jail [here](https://github.com/msimerson/Mail-Toaster-6/blob/master/provision-avg.sh). I use it with Haraka's AVG plugin and a shared filesystem between the two jails. @gibzer is right that AVG still gets  signature updates but its ability to detect virus containing emails in circulation is a rounding error away from zero.

**Comment by vstakhov** [comment]
What is the conclusion on this issue?

**Comment by gibzer** [comment]
I decided to use AVG milter interface. So Postfix first sends mail to Rspamd and after to AVG.
