### ISSUE TITLE
mailman and rate limits

### ISSUE THREAD

**Issue by ddeenniiss** [vstakhov/rspamd#1149]
Hi,

Using rspamd 1.3.5, I have a big problem with mailman lists: mails are blocking because of Rate limit exceeded

Nov 14 09:00:10 xxxxx postfix/smtpd[16436]: NOQUEUE: milter-reject: RCPT from
localhost.localdomain[127.0.0.1]: 451 4.7.1 Rate limit exceeded; from=<mailman-b
ounces@xxxx> to=<xxx> proto=ESMTP helo=<xxxx>

How to get around this problem knowing that some lists have more than 10,000 subscribers ?

**Comment by fatalbanana** [comment]
How about increasing or disabling the ratelimit? You could also disable `RATELIMIT_CHECK` and `RATELIMIT_SET` symbols with `settings` module.

**Comment by ddeenniiss** [comment]
not possible to disable it only for localhost ?

**Comment by fatalbanana** [comment]
Yes, you could do that with `settings` module.

**Comment by ddeenniiss** [comment]
I don't know how to add this.

Could you confirm that i can disable temporary  with this in local.d/rspamd.conf.local.override

ratelimit {
  # Default settings for limits, 1st member is burst, second is rate
  rates {
    # Limit for all mail per recipient
    to = [0, 0.033333333];
    # Limit for all mail per one source ip
    to_ip = [0, 0.025];
    # Limit for all mail per one source ip and from address (rate 1 per minute)
    to_ip_from = [0, 0.01666666667];

    # Limit for all bounce mail (rate 2 per hour)
    bounce_to = [0, 0.000555556];
    # Limit for bounce mail per one source ip
    bounce_to_ip = [0, 0.000277778];

    # Limit for all mail per user (authuser) (rate 1 per minute)
    user = [0, 0.01666666667];
  }
}

**Comment by fatalbanana** [comment]
rspamd.conf.override [belongs in /etc/rspamd](https://rspamd.com/doc/quickstart.html#configuring-rspamd); otherwise that configuration is fine. Another way to do the same thing would be to add ratelimit to `disabled_modules` in [redis configuration](https://rspamd.com/doc/configuration/redis.html).

**Comment by neuraload** [comment]
You could append 127.0.0.1 to limit_whitelist in rmilter.conf. Give it a try, it should work as far as I know.

**Comment by fatalbanana** [comment]
@neuraload ratelimit (and greylist, antivirus) in rspamd are distinct from rmilter.

**Comment by fatalbanana** [comment]
Actually, looking at the error message... it looks like rmilter indeed. :) ^ @ddeenniiss - take note. ;) @neuraload - thank you.

**Comment by ddeenniiss** [comment]
I confirm that append 127.0.0.1 to limit_whitelist in rmilter.conf fix the problem.
Thanks.

Maybe an option to add by default ? Also in the doc ? https://rspamd.com/doc/integration.html
