### ISSUE TITLE
Greylist - whitlisting IP

### ISSUE THREAD

**Issue by skibbipl** [vstakhov/rspamd#1160]
Hello,
I'm trying to configure greylist module in rspamd (1.4.0). Unfortunately I have no idea how to use `whitelisted_ip` setting. I tried different aproaches and everytime rspamadm configtest gives me similar warning:
```
(configtest) <srkwm6>; cfg; rspamd_map_check_proto: invalid map fetching protocol: 127.0.0.1
(configtest) <srkwm6>; cfg; lua_config_add_radix_map: invalid radix map 127.0.0.1
syntax OK
```
My current greylist config:
```
greylist {
    whitelisted_ip = "127.0.0.1";
}
```
I want to add 127.0.0.1 and 192.168.1.0/24 as whitelsted IPs.

**Comment by fatalbanana** [comment]
`whitelisted_ip` should point at a file (or URL) containing the IP addresses/subnets, separated by newline.

**Comment by skibbipl** [comment]
Stupid me! Yes it works with external file.
Thanks.
