### ISSUE TITLE
antivirus module: clamav error

### ISSUE THREAD

**Issue by gibzer** [vstakhov/rspamd#1173]
I have configuration:

antivirus {
  first {
    attachments_only = false;
    symbol = "CLAM_VIRUS";
    type = "clamav";
    servers = "/var/run/clamav/clamd.ctl";
  }
}

And I got an error:

2016-11-24 12:55:48 #28714(normal) <bc10d4>; lua; antivirus.lua:193: Got error checking cache: nil

**Comment by fatalbanana** [comment]
Thank you for report. It's fixed [here](https://github.com/vstakhov/rspamd/pull/1170).
