### ISSUE TITLE
Own fuzzy storage: redis?

### ISSUE THREAD

**Issue by piwats** [vstakhov/rspamd#1176]
Hello,

I'm going through the 'own fuzzy storage' documentation.

Is it possible to have the fuzzy storage stored in redis, too?

**Comment by fatalbanana** [comment]
Yes, unfortunately this is not properly documented. The key is to set `backend = "redis";` in fuzzy worker settings - and configure redis as [usual](https://rspamd.com/doc/configuration/redis.html).

**Comment by piwats** [comment]
Many thanks for your answer!
