### ISSUE TITLE
Duplication of functionality: rspamd <-> rmilter

### ISSUE THREAD

**Issue by piwats** [vstakhov/rspamd#1177]
Since more and more functionalities previously available to rmilter start to pop up in rspamd (dkim, greylisting, etc.), what is the right way to configure the two services?

For example greylisting:

I now have a redis db for rspamd, whith greylisting enabled, I have rmilter greylisting enabled with its data stored in another redis db.

If the greylisting of rspamd is enabled, has the one in greylisting (greylist section) to be enabled, too?

**Comment by moisseev** [comment]
These features (DKIM, greylisting, etc.) are retained in Rmilter to maintain backward compatibility with existing installations. You should not enable them in both Rmilter and Rspamd at the same time.

**Comment by piwats** [comment]
Thank you for your answer.

Antivirus, too?

**Comment by moisseev** [comment]
Yes, unless you want to scan the same message with a virus scanner twice.

**Comment by piwats** [comment]
Thank you very much for the clarifications.

**Comment by moschlar** [comment]
> You should not enable them in both Rmilter and Rspamd at the same time.

Could you maybe state this more explicitly in the docs?

**Comment by vstakhov** [comment]
Yes, this information must be clearly stated in the docs.

**Comment by vstakhov** [comment]
I've added this mention to all Rmilter docs.
