### ISSUE TITLE
whitelist module are not working

### ISSUE THREAD

**Issue by Dmitry55** [vstakhov/rspamd#118]
Hello.
Rspam  version 0.7.4
Add to /etc/rspamd/rspamd.conf.local
whitelist {
    symbol_from = "WHITELIST_SENDER"
    from_whitelist = "file:///etc/rspamd/whitelist-sender"
}
metric {
    name = "default";
    symbol { weight = -20.00; name = "WHITELIST_SENDER"; }
}

/etc/rspamd/whitelist-sender:
sender@domain.ru

But symbol "WHITELIST_SENDER" not inserting to messages and emails are still marked as spam.

**Comment by fatalbanana** [comment]
Bit of a hack but: you could do this with a zero-weight symbol that gets added to every message and the settings module (to increase the value for this symbol where appropriate).

**Comment by moisseev** [comment]
What is the best way to create global blacklist based on specific part (regexp or pattern) of the sender's MTA hostname?

**Comment by vstakhov** [comment]
Why not write a simple lua rule:

~~~lua
rspamd_config.BLACKLIST = function(task)
  local re = rspamd_regexp.create_cached('/blah/')
  local hn = task:get_hostname()
  if hn and re:match(hn) then
    return true
  end
  return false
end
~~~

**Comment by moisseev** [comment]
What regexp syntax should be used here?
Catch all regexp below does'nt work.
```
local re = rspamd_regexp.create_cached('/.*/')
```
But without regexp your rule works fine:
```
rspamd_config.BLACKLIST = function(task)
  local hn = task:get_hostname()
  if hn then
    return true
  end
  return false
end
```

**Comment by vstakhov** [comment]
They use pcre syntax. But you'd need to require regexp module before.

~~~lua
local rspamd_regexp = require "rspamd_regexp"
~~~

**Comment by moisseev** [comment]
It works now. Thanks.

**Comment by ofilin86** [comment]
кто нибудь скажет, как организовать whitelist и blacklist с базой в файле?

**Comment by mnik247** [comment]
to ofilin86 - я делал себе недавно на примерам  https://github.com/vstakhov/rspamd/issues/409

**Comment by ofilin86** [comment]
Спасибо большое, Вы очень помогли :) все сделал, разработчикам можно было в коробке RSpamd сделать аналогично, чтоб люди не мучались :)

**Comment by moisseev** [comment]
Имя файла не должно отображаться в веб интерфейсе. Отображается имя символа, который вы, предположительно, создали для своего правила. Где именно вы видите "undefined"?

**Comment by mnik247** [comment]
У меня так (whitelist=wl, blacklist=bl):
multimap {
    # ip - matches source IP of message (radix map)
    # from - matches envelope from (or header From if envelope from is absent)
    # rcpt - matches any of envelope rcpt or header To if envelope info is missing
    # header - matches any header specified (must have header = "Header-Name" configuration attribute)
    # dnsbl - matches source IP against some DNS blacklist (consider using RBL module for this)
    local_bl_ip { type = "ip"; map = "$CONFDIR/local_bl_ip.map.inc"; symbol = "LOCAL_BL_IP"; }
    local_bl_from { type = "from"; map = "$CONFDIR/local_bl_from.map.inc"; symbol = "LOCAL_BL_FROM"; }
    local_bl_rcpt { type = "rcpt"; map = "$CONFDIR/local_bl_rcpt.map.inc"; symbol = "LOCAL_BL_RCPT"; }
    local_wl_ip { type = "ip"; map = "$CONFDIR/local_wl_ip.map.inc"; symbol = "LOCAL_WL_IP"; }
    local_wl_from { type = "from"; map = "$CONFDIR/local_wl_from.map.inc"; symbol = "LOCAL_WL_FROM"; }
    local_wl_rcpt { type = "rcpt"; map = "$CONFDIR/local_wl_rcpt.map.inc"; symbol = "LOCAL_WL_RCPT"; }
}

**Comment by ofilin86** [comment]
moisseev: Web интерфейс> Configuration>Lists я этот список имел ввиду
названия созданных мной карт, отображались как "undefined", пока не добавил 
```
description = "_человекопонятное_название_карты_для_веб_интерфейса_"; 
```
у господина mnik247 судя по конфигу, наверняка в веб интерфейсе названия карт отображаются как "undefined"

**Comment by mnik247** [comment]
Да все у меня правельно отобпажается...
Вот дальше конфиг:
metric {
    name = "default";
    group {
        name = "local";
        symbol {
            weight = 3;
            description = "Sender ip listed in local ip blacklist";
            name = "LOCAL_BL_IP";
        }
        symbol {
            weight = 3;
            description = "Sender from listed in local from blacklist";
            name = "LOCAL_BL_FROM";
        }
        symbol {
            weight = 3;
            description = "Recipient listed in local rcpt blacklist";
            name = "LOCAL_BL_RCPT";
        }

        symbol {
            weight = -5;
            description = "Sender ip listed in local ip whitelist";
            name = "LOCAL_WL_IP";
        }
        symbol {
            weight = -5;
            description = "Sender from listed in local from whitelist";
            name = "LOCAL_WL_FROM";
        }
        symbol {
            weight = -5;
            description = "Recipient listed in local rcpt whitelist";
            name = "LOCAL_WL_RCPT";
        }
    }
}

**Comment by ofilin86** [comment]
вот как
![rspamd](https://cloud.githubusercontent.com/assets/4071468/11841134/22ddac16-a40c-11e5-815a-fe01a30df08c.png)

**Comment by mnik247** [comment]
Ну хоть теперь стало понятно, про какую карточку Вы пишите.
Я, честно, туда вообше не заглядывал.

**Comment by ofilin86** [comment]
:))) удобно же статистику смотреть :)
