### ISSUE TITLE
[WebUI Throughput] After reconnect `Convert to:` not reset

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#1193]
After reconnect (press `Disconnect` button and log in again) `Convert to:` not reset to `--`
![rspamd-webui-troughput-section](https://cloud.githubusercontent.com/assets/14199981/20660967/99edba74-b565-11e6-8a4d-4556250c6ecc.png)

**Comment by moisseev** [comment]
It is by design. WebUI keeps graph selectors state between reconnects/reloads. Actually it is another issue: graph was reset but it should not. I'll check it.
