### ISSUE TITLE
rspamd-1.4.1 fails with "Your assembler cannot compile macros"

### ISSUE THREAD

**Issue by djc** [vstakhov/rspamd#1210]
Compiling rspamd-1.4.1 with gcc-4.9.3 on my Gentoo Linux system, I get the following error:

```
-- Compilation of slash macro convention asm set is -NOT- supported
-- Compilation of dollar macro convention asm set is -NOT- supported
CMake Error at src/libcryptobox/CMakeLists.txt:36 (MESSAGE):
  Your assembler cannot compile macros, please check your
  CMakeFiles/CMakeError.log
```

However, looking at the [error log](https://dirkjan.ochtman.nl/files/CMakeError.log), there seem to be numerous errors which don't seem to be related to macro support. From looking at them, I'm not sure what might be wrong. 1.4.0 worked fine, so this problem must have been introduced recently.

**Comment by vstakhov** [comment]
That's gentoo issue, not Rspamd one: https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass/cmake-utils.eclass?id=5132424e609fe2df9cd7916bc8dc4db70001b77d

**Comment by djc** [comment]
That doesn't explain the difference between 1.4.0 and 1.4.1 I'm seeing... I mean, I'm open to going to talk to the Gentoo CMake eclass maintainers, but I'd like to understand the issue first.

**Comment by vstakhov** [comment]
You won't be able to compile 1.4.0 with this change: you'll pass cmake stage but will fail on make stage.

**Comment by djc** [comment]
I filed https://bugs.gentoo.org/show_bug.cgi?id=601292.

**Comment by mgorny** [comment]
I'm going to look into this but I'm leaning towards the build system doing something wrong. I would suspect Gentoo if it happened with the previous version of the code which was a huge hack. However, setting CC/CXX to a C/C++ compiler is a perfectly normal practice, and if a project doesn't build with a valid C/C++ compiler being set…

**Comment by vstakhov** [comment]
It doesn't because cmake sets assembler to something weird. And you need to set everything in cmake style using CMAKE_LANG_COMPILER⁣ variables. And Rspamd requires both c compiler and assembler to be set properly.

**Comment by mgorny** [comment]
Thanks for your reply. I investigated this deeply and it turned out that our override for CMAKE_ASM_COMPILE_OBJECT went rogue once CMAKE_C_COMPILER was no longer forced through toolchain. I will look into fixing this on our end (and possibly killing the whole override, if possible).

> And you need to set everything in cmake style using CMAKE_LANG_COMPILER⁣ variables.

This is not true, actually. CMake supports both styles of setting the compilers.

**Comment by hufon** [comment]
I've got the same problem
When compiling on my raspberry pi 
Raspian Wheezy

-- Compilation of slash macro convention asm set is -NOT- supported
-- Compilation of dollar macro convention asm set is -NOT- supported
CMake Error at src/libcryptobox/CMakeLists.txt:36 (MESSAGE):
  Your assembler cannot compile macros, please check your
  CMakeFiles/CMakeError.log

**Comment by vstakhov** [comment]
That should be fixed now.

**Comment by jirutka** [comment]
> That's gentoo issue, not Rspamd one…

No, I don’t think so, we have exactly the same issue with 1.4.1 on Alpine Linux.

**Comment by vstakhov** [comment]
Do you have this issue on arm?

**Comment by jirutka** [comment]
Yes, armhf, I’m gonna try 1.4.2 now.

**Comment by vstakhov** [comment]
I think I've forgotten to push fix to the `rspamd-1.4` branch: 0c7d5f32de56ee254c4b1abc63e7c3709afd1cb2 + 4e5fae43635e824e1b48f10af0bea7dccee0412d

**Comment by jirutka** [comment]
Now it works, thanks!

**Comment by vstakhov** [comment]
They are now backported to 1.4 branch and 1.4.3 will include these fixes.
