### ISSUE TITLE
specific rules for mailman ?

### ISSUE THREAD

**Issue by ddeenniiss** [vstakhov/rspamd#1212]
We have a classical configuration with the following parameters (actions {Reject = 12;Add_header = 4;Greylist = 4;}).

Next, Dovecot filter messages with X-Spam "Yes" in the junk folder. Everything is perfect.

But we also have a lot of message sent directly to mailman and there the filter is not applicable.
postfix/pipe[2619]: 82D6A243144: to=<site-owner@xxx>, relay=mailman, delay=0.29, delays=0.16/0/0/0.12, dsn=2.0.0, status=sent (delivered via mailman service)

What solution could solve this problem?

Here is the postfix conf:
```
mailman   unix  -       n       n       -       -       pipe
  flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
  ${nexthop} ${user}
```

**Comment by fatalbanana** [comment]
You could use [settings module](https://rspamd.com/doc/configuration/settings.html) to lower reject threshold for this address.

```
settings {
  mailman {
    priority = high;
    rcpt = "mailman@example.com";
    apply "default" {
      actions {
          reject = 6;
          add_header = 2;
          greylist = 1;
      }
    }
  }
}
```

**Comment by ddeenniiss** [comment]
Thanks, it's possible to set a file for rcpt = ?
rcpt = /etc/mailman/lists.cfg

**Comment by fatalbanana** [comment]
Not at this time AFAIK.

**Comment by ddeenniiss** [comment]
OK, thanks. And what's the right place to set this settings ?

/etc/rspamd/local.d/mailman.conf ?

**Comment by fatalbanana** [comment]
`settings` is not used in default configuration so the correct place for it is `/etc/rspamd/rspamd.conf.local` (`or rspamd.conf.override`).
