### ISSUE TITLE
Controller / rspamd_redis_stat_keys: cannot get keys to gather stat: Connection refused

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1218]
Hello!

In rpamd log I see this error: Controller / rspamd_redis_stat_keys: cannot get keys to gather stat: Connection refused
Redis is properly running on localhost:6379

In statistics.conf i have
    backend = "redis";
    servers = "localhost:6379";

Any ideas? Thanks!

**Comment by gerdesj** [comment]
Try these (straight off a working system):

$ cat /etc/rspamd/rspamd.conf.local 
```
# Use Redis
redis {
  servers = "127.0.0.1";
}

```
$ cat /etc/rspamd/override.d/statistic.conf 

```
# Statistics

# System wide Bayes
classifier "bayes" {
    tokenizer {
        name = "osb";
    }

    name = "common";
    min_tokens = 11;
    min_learns = 200;
    backend = "redis";
    servers = "127.0.0.1";
    autolearn = true;

    statfile {
        symbol = "BAYES_SPAM";
        spam = true;
    }
    statfile {
        symbol = "BAYES_HAM";
        spam = false;
    }
}
```

**Comment by madorin** [comment]
Strange, during last days this error gone.

I saw them when i setup webui, apache/forwarding, maybe they was raised during my configuration process.

About your config, thanks! I have almost the same values in local.d by merging settings, not overriding it.
