### ISSUE TITLE
task:get_from() cannot parse idiotic names

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#1220]
If the `name` part of MIME `from` contains `@` symbol (`From: @example <example@example.com>`) `task:get_from(2)` returns `nil`.

**Comment by vstakhov** [comment]
I think it is gmime issue. I plan to remove gmime completely in 1.5 since it is unsuitable for Rspamd.

**Comment by fatalbanana** [comment]
This seems to be a non-issue now AFAICT:
`{[1] = {[addr] = barf@rspamd.tk, [domain] = rspamd.tk, [name] = barf@google.com, [user] = barf}}`
