### ISSUE TITLE
DNS Flood and 100% CPU Usage

### ISSUE THREAD

**Issue by hufon** [vstakhov/rspamd#1256]
I've tried to use the last master version (because 1.4.1 doesn't compile on arm)

The controller process is eating 50% of CPU and dnsmasq 100%. It seems it's flooding the dns server with requests.
I've logs like this : 

éc. 13 12:14:45 piyubserver rspamd[2211]: (normal) rdns; rdns_parse_reply: DNS request with id 25971 is for different query, ignoring
déc. 13 12:14:47 piyubserver rspamd[2211]: (normal) rdns; rdns_parse_reply: DNS request with id 33687 is for different query, ignoring
déc. 13 12:14:51 piyubserver rspamd[2211]: (normal) rdns; rdns_parse_reply: DNS request with id 5850 is for different query, ignoring
déc. 13 12:14:55 piyubserver rspamd[2211]: (normal) rdns; rdns_parse_reply: DNS request with id 51389 is for different query, ignoring

**Comment by vstakhov** [comment]
I don't test Rspamd on arm and I don't have any arm hardware. So I doubt I can reproduce your issue.

**Comment by hufon** [comment]
Ok i downgrade to 1.3.5

**Comment by xpunkt** [comment]
if there was a donation of raspberry pi, i think rspamd would be lots better

gentoo have kernel 4.9.0 now, and it bet it works aswell on raspberry pi, any model, so why not rspamd ?

**Comment by vstakhov** [comment]
I don't need neither Raspberry pi nor gentoo, thanks. Furthermore, I don't have time to support Rspamd on non-x86 platforms. If you do, then fix it and send patches. And *PLEASE* don't assume what Rspamd needs or what it doesn't.

**Comment by hufon** [comment]
Downgrade has worked... and now DNS is ok...
I doubt that this problem is related to arm, or rapsberry pi... if the log could be me explicit...

**Comment by hufon** [comment]
I'm trying to see if the problem appear for 1.4... i've to cherry pick asm / non x86 fixes

**Comment by vstakhov** [comment]
Can you run strace on rspamd worker process (anyone that eats cpu extensively). ⁣

**Comment by hufon** [comment]
Version 1.4.1 is working perfectly. I'll send you traces from master version asap.

**Comment by vstakhov** [comment]
There was a mistake with timers during some short time. Are you testing the most recent master?
