### ISSUE TITLE
BROKEN_HEADERS set for all messages

### ISSUE THREAD

**Issue by vadz** [vstakhov/rspamd#1263]
This has been reported before in #617, but that issue was closed, while the problem seems to remain: this flag (which has a default weight of 1) seems to be set for absolutely all messages, probably due to a bug in [rspamd_mime_headers_process()](https://github.com/vstakhov/rspamd/blob/ba7924d7f331ba0523a3f5a2dd012f236d41b46e/src/libmime/mime_headers.c#L40).

**Comment by vstakhov** [comment]
Do you suggest me to start guessing what is your problem? Your report is useless now, so please add necessary information or close it. (For the god sake I really need to create a template for github issues one day...)

**Comment by vadz** [comment]
I suggest looking at the example already given in #617, which was closed for some unexplained reason, but does contain everything needed. I opened this ticket just to say that the bug is still present in the recent versions of rspamd too. Feel free to close this one and reopen the other one.

**Comment by vstakhov** [comment]
No. Paste message samples, tell me what version are you using, what OS are you using, how do you send messages to Rspamd. We do not observe this issue anywhere so it is an issue in your setup. Isn't it clear?

**Comment by vadz** [comment]
No, it isn't clear. I looked at the previous bug report and I looked at the code setting the "broken headers" flag in `rspamd_mime_headers_process()` and it seems to me it's completely independent of any setup details. I also looked for unit tests for this function, didn't find any and so concluded that there was a bug in it.

If you say you really don't see the problem with the examples from #617, then I must have missed something, sorry. I'll retest with the latest code (as it seems to have changed very recently) and will provide the details if the problem is still present in it.

**Comment by fatalbanana** [comment]
Maybe you're using Exim native content scanning and rspamd < 1.2.7?

**Comment by vadz** [comment]
No, I'm using 1.3.4 without Exim integration.

**Comment by fatalbanana** [comment]
But you scan Exim spool file? ;)

**Comment by fatalbanana** [comment]
So I suppose your issue is fixed by this commit: https://github.com/vstakhov/rspamd/commit/0b4c54e21874d6d622ab6820e36071c071e0c3e1 - which is in 1.3.5.

**Comment by vadz** [comment]
OK, thanks, I can indeed confirm that the issue is gone in 1.4.1.

Sorry for the noise.
