### ISSUE TITLE
What "cannot create lemmatizer for x language" really means?

### ISSUE THREAD

**Issue by athanp** [vstakhov/rspamd#1272]
Rapsmd log is filled with "cannot create lemmatizer for greek language" during word extraction when scanning greek email.
Anybody knows what this message really means and how can I fix it?

**Comment by fatalbanana** [comment]
There is no support for Greek in [Snowball lemmatizer](https://github.com/snowballstem/snowball) so rspamd cannot convert words to the first form. It should not be a significant problem.

**Comment by athanp** [comment]
Thanks for the info! I was afraid that something was wrong with my setup.
Any workaround to avoid those _lemmatizer_ messages filling up the log?

**Comment by fatalbanana** [comment]
You'd have to [reduce log level](https://rspamd.com/doc/configuration/logging.html) to `warning` or `error`. Perhaps level for this message could be dropped to `debug`.
