### ISSUE TITLE
Dashboard does not refresh

### ISSUE THREAD

**Issue by st3fan** [vstakhov/rspamd#1285]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

rspamd 1.4.1
rmilter 1.10

Both from `apt-stable` and up to date.

### Operation system, CPU, memory and environment:

Ubuntu 16.04 / x86_64 / 1GB / Postfix

### Description (Please provide a descriptive summary of the issue):

I have a pretty standard *rspamd* setup, with pretty much nothing changed yet. I did a basic integration with *NGINX* so that I can look at the *WebUI*. It looks like this:

```
server {
  listen 443;

  server_name mail.foo.com;

  access_log /var/web/mail.foo.com/log/access.log;
  error_log /var/web/mail.foo.com/log/error.log;

  location / {
    proxy_pass  http://127.0.0.1:11334;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
  }

  ... TLS Config omitted, can show if relevant ...
}
```

The problem that I am experiencing is that the *WebUI* is not refreshing. When I reload the page, the statistics on the *Status* page remain the same. Even though they have changed for sure. The only way for me to update the *Status* page is to hit *Disconnect* and then log in again. Then I see updated statistics.

**Comment by vstakhov** [comment]
This issue seems to be fixed in the master branch.

**Comment by michelsup** [comment]
I'm plagued with the same issue for months with the latests Git versions. I need to use privacy mode to get statistics updated, clearing cache is not enough.
