### ISSUE TITLE
debian-based package missing dependency

### ISSUE THREAD

**Issue by LynxChaus** [vstakhov/rspamd#1286]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

debian/ubuntu rspamd package must depends on ca-certificates package. Without package it can't verify certificate and fill logs with non-informative messages like this:
#9827(normal) <xa6qqy>; map; http_map_error: connection with http server terminated incorrectly: ssl connect error: error:00000001:lib(0):func(0):reason(1)

**Comment by vstakhov** [comment]
Committed, thanks!
