### ISSUE TITLE
Rspamd is unable to decode ISO-2022-JP headers

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#1293]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.0-git.d0da131

### Steps to reproduce:
[iso-2202-jp.zip](https://github.com/vstakhov/rspamd/files/679590/iso-2202-jp.zip)
```sh
# rspamc < ./iso-2202-jp.eml
...
Symbol: SUBJECT_HAS_CURRENCY (1.00)
Symbol: SUBJECT_HAS_QUESTION (0.00)
...
```
But there is no currency or question symbol in the decoded text:
```
From:
Служба Внутренн
его Контроля
<user@example.com>
Subject: Заявка № . Бла
нк доверенности
MIME-Version: 1.0 
```

### Additional information:
[ISO-2022-JP on-line decoder](https://www.k-tanaka.net/decode/decode.cgi)

**Comment by vstakhov** [comment]
It should be iconv issue.

**Comment by ScOut3R** [comment]
@vstakhov Does the same apply when prepending a string to the subject which is in ISO-2022-JP? What I see is that the original text is missing from the subject and only see it with ISO-2022-JP encoded headers. 

The OS is an up-to-date Ubuntu 16.04. I am running rspamd 1.5.5.
