### ISSUE TITLE
Wrong password hint on WebUI connect

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#1299]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
`1.5.0-git.96d30cb`
### Operation system, CPU, memory and environment:
`FreeBSD 10.3-RELEASE-p11 amd64 GENERIC`/`Mozilla Firefox 50.1.0`
### Description (Please provide a descriptive summary of the issue):
If keyboard layout differs from password layout than we have error as shown below 

![rspamd-webui-wrong-password-hint](https://cloud.githubusercontent.com/assets/14199981/21615313/694bfaa4-d1f6-11e6-8e20-b69df4ac927b.png)

### Steps to reproduce:
*Important*: password in English (in my case)
1. Change keyboard layout to `Russian` for example
2. Enter _right_ password; press `Connect`

### Expected results:
`Wrong password` hint appears

### Actual results:
Error as shown above on screenshot
Nothing happens after entering password again

**Comment by vstakhov** [comment]
In theory, that's your OS or browser issue: I cannot enter cyrillic chars in password fields in OSX and Chrome. However, I've added some sanity check of data entered.
