### ISSUE TITLE
rspamd_monitored_propagate_error

### ISSUE THREAD

**Issue by aekv** [vstakhov/rspamd#1312]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamadm 1.4.1
### Operation system, CPU, memory and environment:
Ubuntu 16.04
### Description (Please provide a descriptive summary of the issue):
Jan  5 01:50:53 cloud rspamd[3428]: (normal) <thbugu>; monitored; rspamd_monitored_propagate_error: failed to make DNS request on resolving uribl.rambler.ru, disable object
Jan  5 01:50:54 cloud rspamd[3428]: (normal) <6rsaus>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve facebook.dbl.spamhaus.org
Jan  5 01:50:56 cloud rspamd[3428]: (normal) <stx5q9>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.email-bl.rambler.ru
Jan  5 01:50:56 cloud rspamd[3428]: (normal) <stx5q9>; monitored; rspamd_monitored_propagate_error: failed to make DNS request on resolving email-bl.rambler.ru, disable object
Jan  5 01:50:58 cloud rspamd[3428]: (normal) <q5zzqk>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve facebook.public.sarbl.org
Jan  5 01:50:58 cloud rspamd[3428]: (normal) <q5zzqk>; monitored; rspamd_monitored_propagate_error: failed to make DNS request on resolving public.sarbl.org, disable object

Jan  5 02:08:32 cloud rspamd[3428]: (normal) <zp979p>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.bl.ipv6.spameatingmonkey.net
Jan  5 02:08:33 cloud rspamd[3428]: (normal) <mf4ijz>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.rep.mailspike.net
Jan  5 02:08:33 cloud rspamd[3428]: (normal) <crtj3k>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.spam.abuse.ch
Jan  5 02:08:35 cloud rspamd[3428]: (normal) <mf4ijz>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.rep.mailspike.net
Jan  5 02:08:35 cloud rspamd[3428]: (normal) <cd3m9g>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.zen.spamhaus.org
Jan  5 02:08:40 cloud rspamd[3428]: (normal) <9ownwh>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve facebook.multi.uribl.com
Jan  5 02:08:47 cloud rspamd[3428]: (normal) <9ownwh>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve facebook.multi.uribl.com
Jan  5 02:08:47 cloud rspamd[3428]: (normal) <q5zzqk>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve facebook.public.sarbl.org
Jan  5 02:08:48 cloud rspamd[3428]: (normal) <q5zzqk>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve facebook.public.sarbl.org
Jan  5 02:08:52 cloud rspamd[3428]: (normal) <thbugu>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve facebook.uribl.rambler.ru

**Comment by fatalbanana** [comment]
This issue seems to be particular to your setup: could be issues with your resolver(s) or something else. Do you have error messages from rdns in your logs? Do you see the DNS requests on the wire?

**Comment by aekv** [comment]
hi
I don't have any problems with DNS

root@cloud:/# nslookup
> gmail.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	gmail.com
Address: 173.194.44.86
Name:	gmail.com
Address: 173.194.44.85
> spamhaus.org
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	spamhaus.org
Address: 192.42.118.104

**Comment by vstakhov** [comment]
Cannot make DNS request means that Rspamd cannot read your `/etc/resolv.conf` and you have not specified nameservers explicitly (https://rspamd.com/doc/configuration/options.html#dns-options)

**Comment by aekv** [comment]
I fixed it
chattr -i /etc/resolv.conf

thanks
