### ISSUE TITLE
libstemmer.so not installed after "make install" in rspamd 0.8.1 and 0.9.0

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#132]
wget https://rspamd.com/downloads/rspamd-0.8.1.tar.xz
tar xvJf rspamd-0.8.1.tar.xz
cd rspamd-0.8.1
cmake -DCMAKE_C_FLAGS="-g -O0" -D CMAKE_INSTALL_PREFIX:PATH=/usr/local/rspamd .
make
make install
/usr/local/rspamd/bin/rspamd

/usr/local/rspamd/bin/rspamd: error while loading shared libraries: libstemmer.so: cannot open shared object file: No such file or directory

Temporary solution:
cp contrib/snowball/libstemmer.so /usr/local/rspamd/lib/rspamd/

**Comment by vaygr** [comment]
same issue here

**Comment by pixilla** [comment]
same here (OS X) with different lib suffix:
cp contrib/snowball/libstemmer.dylib ${destroot}${prefix}/lib/rspamd/

**Comment by vstakhov** [comment]
This has a temporary workaround to use `-DNO_SHARED=ON` when configuring build using cmake. Actually, I'm thinking about enabling this option by default as it is done in debian and FreeBSD ports.
