### ISSUE TITLE
[WebUI] Сonfiguration ID does not fit in column

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#1323]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
`1.5.0-git.87d53c9`

### Operation system, CPU, memory and environment:
`FreeBSD 10.3-RELEASE-p11 amd64 GENERIC/Mozilla Firefox 50.1.0`

### Description (Please provide a descriptive summary of the issue):
`Сonfiguration ID` does not fit properly in column on `Status` page

### Actual results:

![rspamd-webui-cluster-conf-id](https://cloud.githubusercontent.com/assets/14199981/21752904/531e9c0c-d5fa-11e6-891c-36c266d0d753.png)

**Comment by vstakhov** [comment]
It should be fixed now.

**Comment by dehnli** [comment]
Thanks
