### ISSUE TITLE
cannot find worker "log_helper"

### ISSUE THREAD

**Issue by aekv** [vstakhov/rspamd#1324]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.4.1
### Operation system, CPU, memory and environment:
Linux Ubuntu 16.04
### Compile errors (if any):
controller) <srkwm6>; lua; fann_redis.lua:899: cannot find worker "log_helper"
(normal) <srkwm6>; lua; fann_redis.lua:899: cannot find worker "log_helper"
(normal) <srkwm6>; lua; fann_redis.lua:899: cannot find worker "log_helper"

**Comment by dehnli** [comment]
@aekv did you setup `worker "log_helper"`  https://rspamd.com/doc/modules/fann.html#configuration ?

**Comment by aekv** [comment]
Hi
Yes, I did it. 

My configs
**/etc/rspamd/local.d/rspamd.conf.local**
worker {
         .include "$LOCAL_CONFDIR/log_helper.inc"
}

**/etc/rspamd/local.d/log_helper.inc**
type = "log_helper"
count = 1;

default
**/etc/rspamd/modules.d/fann_redis.conf**

rspamd.log
(main) rspamd_roll_history_load: stored history is smaller than the current one: 129 (file) vs 200 (history)
(normal) <srkwm6>; lua; fann_redis.lua:899: cannot find worker "log_helper"
(controller) <srkwm6>; lua; fann_redis.lua:899: cannot find worker "log_helper"
(normal) <srkwm6>; lua; fann_redis.lua:899: cannot find worker "log_helper"
(controller) <35rhob>; map; read_map_file: map file is unavailable for reading
(normal) <35rhob>; map; read_map_file: map file is unavailable for reading
(normal) <35rhob>; map; read_map_file: map file is unavailable for reading

**Comment by vstakhov** [comment]
`/etc/rspamd/local.d/rspamd.conf.local` is not read by Rspamd default configuration AFAIR.

**Comment by vstakhov** [comment]
Use `rspamadm configdump` to check your config...

**Comment by aekv** [comment]
where should i add ?

worker "log_helper" {
  count = 1;
}
https://rspamd.com/doc/modules/fann.html#configuration

**Comment by moisseev** [comment]
@aekv `/etc/rspamd/rspamd.conf.local`
