### ISSUE TITLE
Issue with get_symbols_cksum

### ISSUE THREAD

**Issue by gibzer** [vstakhov/rspamd#1325]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.4.2

### Operation system, CPU, memory and environment:
Ubuntu 14.04.5, Intel Xeon CPU E5540, 6 GB RAM

### Description (Please provide a descriptive summary of the issue):
After upgrading to 1.4.2 I got such strings in log:

2017-01-09 10:15:06 #25595(normal) lua_periodic_callback: call to periodic failed: /usr/share/rspamd/lua/fann_redis.lua:341: attempt to call method 'get_symbols_cksum' (a nil value)

or

2017-01-09 10:15:07 #25609(log_helper) rspamd_log_helper_read: error executing log handler code: /usr/share/rspamd/lua/fann_redis.lua:339: attempt to call method 'get_symbols_cksum' (a nil value)

**Comment by vstakhov** [comment]
It seems something was not ported from the master branch. FYI, @fatalbanana.

**Comment by vstakhov** [comment]
It should be backported now and will be the part of 1.4.3 release

**Comment by alexanderhaensch** [comment]
After installing the recent patches from rspamd-1.4 branch, i get:
error executing log handler code: /usr/share/rspamd/lua/fann_redis.lua:339: attempt to index a userdata value

**Comment by fatalbanana** [comment]
Thank you for the report. https://github.com/vstakhov/rspamd/pull/1342
