### ISSUE TITLE
[WebUI] Cannot receive stats data from: local, error: (NULL)

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#1334]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
`1.5.0-git.1c31d90`

### Operation system, CPU, memory and environment:
`FreeBSD 10.3-RELEASE-p11 amd64 GENERIC/Mozilla Firefox 50.1.0`

### Description (Please provide a descriptive summary of the issue):
- `Cannot receive stats data from: local, error: (NULL)` error occurs on `Status` tab after WebUI login
- `Cannot receive maps data` error occurs on `Configuration` tab some time later, after switching to the tab. `Actions`  and `Lists` are present
- The other tabs work as expected

### Steps to reproduce:
Log in WebUI interface

### Expected results:
Pie graph, uptime and so on

### Actual results:
`Status` page without data

### Additional information:
```
$ cat /var/log/rspamd/rspamd.log

2017-01-11 09:59:22 #31801(controller) <wmoerd>; controller; rspamd_check_encrypted_password: incorrect or absent password has been specified
2017-01-11 09:59:22 #31801(controller) <fa0b53>; csession; rspamd_controller_error_handler: http error occurred: Not found
2017-01-11 09:59:22 #31801(controller) rspamd_http_router_finish_handler: path: /undefined/auth not found

```

**Comment by RalfvdEnden** [comment]
I have the same issue on FreeBSD 11.0. Probably caused by commit 4441b20 ([WebUI] Rework neighbours query function)

**Comment by stweiss** [comment]
Same issue here as well.
