### ISSUE TITLE
[WebUI] Status page issues

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#1343]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.0-git.a57f46c

### Description (Please provide a descriptive summary of the issue):
1. ~~`Soft reject` is missed on the pie chart if `All SERVERS` is selected.~~
1. ~~Pie chart redraws twice on `Refresh` click, browser reload or servers selector switching.~~
1. IMO it was not a good idea to redraw the pie every 10 seconds.

**Comment by moisseev** [comment]
4. I can't authenticate anymore in WebUI on one of my Rspamd servers.
I am getting `timeout` error message in WebUI and
```
017-01-14 18:54:42 #30922(controller) <fzuzf5>; controller; rspamd_check_encrypted_password: incorrect or absent password has been specified
```
WebUI works if `secure_ip` is set.
I don't have this problem with other servers even if I am using the same password.

**Comment by moisseev** [comment]
5. Sometimes `controller` returns `500` error on HTTP requests. This never happened before cluster support was introduced.
To reproduce set `monit` connection testing:
```cxx
check process rspamd with pidfile /var/run/rspamd/rspamd.pid
    if failed host 192.168.2.10 port 11334 protocol HTTP then alert
```
Following log message appears several times a day:
```cxx
Jan 18 08:57:08 mx monit[53025]: 'rspamd' failed protocol test [HTTP] at [192.168.2.10]:11334 [TCP/IP] -- HTTP error: Server returned status 500
```

**Comment by moisseev** [comment]
6. WebUI periodically lose id of a cluster member on autorefresh. 

```
neighbours {
    localhost1 {
        host = "localhost:11334";
    }
    localhost2 {
        host = "localhost:11334";
    }
}
```

![2017-01-22 13_58_53-2017-01-22 13_58_06-start png - irfanview zoom_ 1659 x 644](https://cloud.githubusercontent.com/assets/2275981/22182048/39ead716-e0ac-11e6-9ed5-208f10abd456.png)
![2017-01-22 13_58_06-start](https://cloud.githubusercontent.com/assets/2275981/22182049/424e7b6a-e0ac-11e6-8cd9-431a775ee203.png)

**Comment by moisseev** [comment]
7. WebUI causes high CPU usage on Rspamd server. It is not very very high, but seems higher than it should be. That is why I have issue [4] (see above) just with one server. Turned out `Pentium 4` performance is not enough for `controller` to serve WebUI requests.
```
CPU: Intel(R) Pentium(R) 4 CPU 2.80GHz (2793.25-MHz 686-class CPU)
  Origin="GenuineIntel"  Id=0xf29  Family=0xf  Model=0x2  Stepping=9
  Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0x4400<CNXT-ID,xTPR>
```
I've reproduced it on VirtualBox VM (FreeBSD 11.0-RELEASE-p1). When I set guest's CPU limit to 10% (host's CPU Core i3-550 3.2GHz), WebUI cannot authenticate [4].

**Comment by moisseev** [comment]
I can't reproduce these issues anymore except [5].

**Comment by vstakhov** [comment]
What path do you request?

**Comment by moisseev** [comment]
I request "/": `http://192.168.2.10:11334/`
```
HEAD / HTTP/1.1
Accept: */*
Connection: close
Host: 192.168.2.10:11334
User-Agent: Monit/5.20.0

HTTP/1.1 500 Invalid method
Connection: close
Server: rspamd/1.5.0
Date: Fri, 17 Feb 2017 13:31:33 GMT
Content-Length: 0
Content-Type: text/plain
Access-Control-Allow-Origin: *
```

**Comment by vstakhov** [comment]
Head is not implemented.

**Comment by vstakhov** [comment]
You can test it using `OPTIONS`btw.

**Comment by moisseev** [comment]
https://mmonit.com/monit/changes/ :
> Fixed: The HTTP protocol-test now uses HEAD instead of GET if no content check is set. That is, if you only want to test the response status for a given URL and not the content of the response. This should make the test faster and save bandwidth. 

AFAIK the `OPTIONS` method is not available in `monit`. So, I should use content check like:

```cxx
if failed host 192.168.2.10 port 11334 protocol HTTP content = "Rspamd Web Interface" then alert
```
