### ISSUE TITLE
how about skip symbol check?

### ISSUE THREAD

**Issue by hxily** [vstakhov/rspamd#1370]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Additional information:

i use  write a lua script 
task:set_metric_action('default', 'no action')

it still check all symbol,how about  skip remaining check?

**Comment by fatalbanana** [comment]
[task:set_pre_result()](https://rspamd.com/doc/lua/task.html#m0426b) does this.

**Comment by hxily** [comment]
thanks
task:set_pre_result() is tests
but rejected when content XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X  ,What reason?

**Comment by fatalbanana** [comment]
GTUBE is special (it will ~always be rejected).

**Comment by hxily** [comment]
@fatalbanana  now, i see. That's why.
it haunt me for a long time
thank you vear much.
