### ISSUE TITLE
jemalloc.h incorrectly included

### ISSUE THREAD

**Issue by anarchpenguin** [vstakhov/rspamd#1377]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
master
### Operation system, CPU, memory and environment:
n/a
### Description (Please provide a descriptive summary of the issue):
You all are using #include <jemalloc.h> via `man 3 jemalloc` you will see the correct
usage is #include <jemalloc/jemalloc.h>
### Compile errors (if any):
config.h:261:22: fatal error: jemalloc.h: No such file or directory

**Comment by anarchpenguin** [comment]
You can find a patch created against master at https://bugs.gentoo.org/show_bug.cgi?id=607128

**Comment by vstakhov** [comment]
In fact, it shouldn't be included at all.
