### ISSUE TITLE
[Feature] Add SpamAssassin like X-Spam-Level header

### ISSUE THREAD

**Issue by jnhmn** [vstakhov/rspamd#1393]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Rspamd version:
1.4.3

### Description (Please provide a descriptive summary of the issue):
Please add a header field which indicates the spam score and also being interpretable with a simple REGEX parser

### Additional information:
I want to tell mailman to drop mail with an high spam score and keep mails with an low score for further verification.
In my specific setup I can not use the reject feature of rspamd to archive the same results.

Example header of SpamAssassin:
X-Spam-Flag: YES
X-Spam-Level: *************
X-Spam-Status: Yes, score=13.3

**Comment by fatalbanana** [comment]
Hi, there's support for this in the [rmilter headers](https://rspamd.com/doc/modules/rmilter_headers.html) module. This module isn't available in 1.4.x but it will work there. You could also take [DIY approach](https://rspamd.com/doc/migration.html#migrating-from-rmilter-18-to-rmilter-19) instead of using this module.

**Comment by jnhmn** [comment]
Thank you,
this seems to be exactly what I'm looking for.
How do in "install" this module on debian?

Is it enough to copy to lua file from the repository to /usr/share/rspamd/lua/ and create a suiteable config file in /etc/rspamd/modules.d?

This is what I've done so far, but I do not see any results (on ham Mails, for SPAM I have to wait)

**Comment by fatalbanana** [comment]
Configuration should go in [/etc/rspamd/rspamd.conf.local](https://rspamd.com/doc/quickstart.html#configuring-rspamd) - arbitrary files in `modules.d` won't be processed.

**Comment by jnhmn** [comment]
I close this issue since rmilter headers does the job for me.
Thanks
