### ISSUE TITLE
local.d and redis configs

### ISSUE THREAD

**Issue by AloneShadow** [vstakhov/rspamd#1400]
### Classification (Please choose *one* option):
* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):
* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Operation system, CPU, memory and environment: FreeBSD

I'm currently migrating from sqlite to redis. 
I want to use only one redis instance.
I have 2 file in local.d directory: classifier-bayes.conf and redis.conf.
If i have in classifier-bayes.conf lines:
```
  name = "common";
  backend = "redis";
  db = "2";
  servers = "master-slave:srv1,srv2,srv3";
```
all work and rspamd connects to db 2.
I want to use redis `servers` definition for all modules, so I inserted line 
`  servers = "master-slave:srv1,srv2,srv3";`
into local.d/redis.conf file and deleted it from local.d/classifier-bayes.conf.
After such manipulations rspamd connects to db 0, ignoring 
`  db = "2";` or `database="2"` definitions in local.d/classifier-bayes.conf file.
Is it a bug or i'm doing something wrong?
For now it looks like I need to use `server` definition for each module if I want to use different dbs.
P.S. Если мой английский непонятен, могу изложить все на русском.

**Comment by vstakhov** [comment]
Bayes is very special. Other modules use lua function which is easy to fix. However, statistical module is written in C and that has some implication on the logic of redefinition which is more straightforward: namely, no `servers` in some section, just ignore all other redis params from it.
