### ISSUE TITLE
Lua http module does not send specified mime type in HTTP requests

### ISSUE THREAD

**Issue by cgt** [vstakhov/rspamd#1410]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version: 1.5.0-0\~git199\~091586c\~xenial
(from rspamd.com/apt/ repo)

### Operation system, CPU, memory and environment:
Ubuntu 16.04 x86_64

### Description (Please provide a descriptive summary of the issue):
The Lua `rspamd_http.request` function does not send a `Content-Type` header with HTTP requests even if the `mime_type` table argument has been specified.

### Steps to reproduce:
I wrote a small Lua module to demonstrate the problem:

```lua
local http = require "rspamd_http"
local logger = require "rspamd_logger"

local function func(task)
    local function cb(err_message, code, body, headers)
        logger.infox("errmsg=%s, code=%s", err_message, code)
        logger.infox("headers=%s", headers)
        logger.infox("body=%s", body)
    end

    http.request({
        task=task,
        url="http://127.0.0.1:8000/",
        body=[[{"foo": "bar"}]],
        mime_type="application/json",
        callback=cb,
    })
end

rspamd_config:register_post_filter(func)
```

I listened on port 8000 with netcat to receive the HTTP request.

### Expected results:
When this module is installed, whenever an e-mail is processed, it makes an HTTP POST request to the specified URL with the specified JSON body content `{"foo": "bar"}` and the HTTP request includes the header `Content-Type: application/json`.

### Actual results:
```
POST / HTTP/1.1
Connection: close
Host: 127.0.0.1
Content-Length: 14

{"foo": "bar"}
```
No `Content-Type` header has been set.

**Comment by vstakhov** [comment]
This should be fixed in the master branch, thanks!
