### ISSUE TITLE
systemd and logrotate postrotate

### ISSUE THREAD

**Issue by urusha** [vstakhov/rspamd#1412]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.4.3-2~xenial

### Operation system, CPU, memory and environment:
ubuntu xenial, amd64

### Description (Please provide a descriptive summary of the issue):
On systemd systems `service rspamd reopenlog` doesn't work, so if logging `type` is set to `file`, 
default logrotate postrotate action does nothing, and rspamd continues to use the old log file.
This code could be used to detect init system (/etc/logrotate.d/rspamd):
```
if readlink /proc/1/exe | grep -q systemd; then
  systemctl kill --signal=SIGUSR1 --kill-who=main rspamd.service 2>/dev/null || true
else
  service rspamd reopenlog >/dev/null 2>&1 || true
fi
```

### Steps to reproduce:
/etc/rspamd/local.d/logging.inc :
```
type = "file";
filename = "/var/log/rspamd/rspamd.log";
systemd = false;
```

run rotation (move rspamd.log away)

### Expected results:
After rotation new messages go to the new file (rspamd.log) 

### Actual results:
After rotation new messages go to the old file (rspamd.log.1)

**Comment by vstakhov** [comment]
That's systemd duty to reload log file in this case. I don't like the proposed solution I'm afraid assuming that it's a sysadmin's task to setup rotating of the logs in this case.

**Comment by urusha** [comment]
Then I guess postrotate action should be removed at all from debian/rspamd.logrotate , since it doesn't work with current stable distrib releases and can only just confuse sysadmins.
