### ISSUE TITLE
rspamc password file

### ISSUE THREAD

**Issue by urusha** [vstakhov/rspamd#1415]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.4.3-2~xenial

### Operation system, CPU, memory and environment:
ubuntu xenial, amd64

### Description (Please provide a descriptive summary of the issue):
For now `ps ax` could be used to catch rspamc password passed via `-P password`
Some time it's not possible to push password to stdin, for example, when using dovecot-antispam for spam learning. 
So, that would be nice, if we could specify a password file to use with rspamc, e.g. `-P /some/secret/file`
This would hide the password from both `ps ax` and dovecot (or any other software) config.
This feature will improve rspamc-rspamd communication security for some cases, so I think it's worth implementing.

**Comment by dehnli** [comment]
@urusha you can try using `secure_ip` https://rspamd.com/doc/workers/controller.html#controller-configuration ie for spam learning

**Comment by urusha** [comment]
@dehnli the main reason for password in my case is restricting controller socket for local users, so `secure_ip` is not an option.

**Comment by dehnli** [comment]
What about that? To prevent users from seeing processes that do not belong to them:
```
# mount -o remount,rw,hidepid=2 /proc
```

**Comment by urusha** [comment]
@dehnli and `chmod 640 dovecot.conf` , yes, I know that it's possible, but is it simpler than just `-P pass/file` ? Less mistake chance -> more secure.

**Comment by vstakhov** [comment]
Added.
