### ISSUE TITLE
'allow unauthorized connection from a unix socket' message, even if a password was specified

### ISSUE THREAD

**Issue by urusha** [vstakhov/rspamd#1416]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.4.3-2~xenial

### Operation system, CPU, memory and environment:
ubuntu xenial, amd64

### Description (Please provide a descriptive summary of the issue):
When unix socket is used with worker-controller, rspamd throws `allow unauthorized connection from a unix socket` even if a password was specified with rspamc.
I think rspamd should not warn us about it if a password is used. Additionally, I guess connection should be considered authorized if the socket is not world writable (and connection is not proxied).

### Steps to reproduce:
/etc/rspamd/override.d/worker-controller.inc:
```
bind_socket = "/run/rspamd/controller.sock 
enable_password = "somepassword";
```
`rspamc -h /run/rspamd/controller.sock -P somepassword`
### Expected results:
no `allow unauthorized connection from a unix socket` in logs
### Actual results:
`allow unauthorized connection from a unix socket` in logs

**Comment by vstakhov** [comment]
Rspamd assumes that Unix sockets are always safe. If you don't like this assumption then just don't use unix sockets.

**Comment by urusha** [comment]
That's what I've tried to say. "Safe" means authorized, I guess. Then what is the purpose of this log message? I just want to get rid of these messages at least on default log level.
