### ISSUE TITLE
mail notification 

### ISSUE THREAD

**Issue by ddeenniiss** [vstakhov/rspamd#1424]
With amavis, it is possible to receive a notification by mail when a spam is detecting. This report is very practical for us because it's easy to search an error and track what happens almost in real time. It's possible to have a similar mechanism with rspamd?
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ x] Enhancemen

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

**Comment by fatalbanana** [comment]
It's readily possible though there is no existing facility that does exactly this. There was some [discussion over at the mailing list](https://groups.google.com/forum/#!topic/rspamd/crt-Rn1tIxw) about it recently.
