### ISSUE TITLE
Web UI not working with 1.5.1

### ISSUE THREAD

**Issue by djc** [vstakhov/rspamd#1477]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

Web UI does not work in Firefox Nightly. In the console, it says TypeError: data[checked_server] is undefined (from `rspamd.js`:231).

### Additional information:

Web server proxy configuration:

<VirtualHost *:80>
	ServerName rspamd.example.com
	ProxyPass / http://localhost:11334/
	<Location />
		AuthType Basic
		AuthName rspamd
		AuthUserFile /etc/apache2/passwords
		AuthGroupFile /etc/apache2/groups
		Require group me
	</Location>
</VirtualHost>

**Comment by vstakhov** [comment]
I think it is somehow related to the cluster support. Do you have more information about XHR requests for your case? E.g. what was requested and what were the results.

**Comment by djc** [comment]
I don't see any XHR going on. The only resources requested are `/` and a bunch of assets (like `.css`, `.js` and `.png` files).

**Comment by fatalbanana** [comment]
Is this still an issue? Firefox works OK for me.

**Comment by djc** [comment]
I haven't had issues in a while.
