### ISSUE TITLE
Antivirus module does not handle viruses independently for mor than 1 scanners

### ISSUE THREAD

**Issue by croessner** [vstakhov/rspamd#1482]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
master branch (currently 1.5.2)

### Operation system, CPU, memory and environment:
Gentoo Linux, HP ProLiant G6 2 x Intel Xeon L5640, 64bit

### Description (Please provide a descriptive summary of the issue):
If a mail gets scanned by more than one antivirus scanner, one of them might detect a virus and register it. If future mails of the same kind arrive, the module triggers all symbols for all scanners, as if all scanners had found that virus. So I guess storing and reading to/from redis needs to be improved.

### Compile errors (if any):
-
### Steps to reproduce:
1. Configure the antivirus module like this:

```rspamd.conf
antivirus {
	savapi {
		action = "greylist";
		attachments_only = false;
		max_size = 20971520;
		symbol = "AVIRA_VIRUS";
		type = "savapi";
		product_id = *****;
		log_clean = true;
		servers = "127.0.0.1:4444";
		patterns {
			JUST_EICAR_1 = "^Eicar-Test-Signature$";
		}
		whitelist = "/etc/rspamd/antivirus.wl";
	}
	clamav {
		action = "greylist";
		attachments_only = false;
		max_size = 20971520;
		symbol = "CLAMAV_VIRUS";
		type = "clamav";
		servers = "127.0.0.1:3310";
		patterns {
			JUST_EICAR_2 = "^Eicar-Test-Signature$";
		}
		whitelist = "/etc/rspamd/antivirus.wl";
	}
}
```

2. Send a test mail with a virus pattern (not EICAR!) to the system.
3. Send again

### Expected results:
Only having that scanner symbol being set that really triggered the virus.

### Actual results:
All symbols are set and it is not clear which scanner detected it.

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
First received mail logged:
2017-03-06 02:09:18 #8254(normal) <44fecd>; lua; antivirus.lua:43: clamav: virus found: "winnow.spam.ts.xmailer.2.UNOFFICIAL"
2017-03-06 02:09:18 #8254(normal) <44fecd>; task; lua_task_set_pre_result: <undef>: set pre-result to greylist: 'clamav: virus found: "winnow.spam.ts.xmailer.2.UNOFFICIAL"'

So the SAVAPI did not detect it. Only symbol CLAMAV_VIRUS was set (correctly)

The same sender sent a second (and third mail):
2017-03-06 02:49:15 #8254(normal) <6460c5>; lua; antivirus.lua:43: savapi: virus found: "winnow.spam.ts.xmailer.2.UNOFFICIAL"
2017-03-06 02:49:15 #8254(normal) <6460c5>; task; lua_task_set_pre_result: <undef>: set pre-result to greylist: 'savapi: viru
s found: "winnow.spam.ts.xmailer.2.UNOFFICIAL"'
2017-03-06 02:49:15 #8254(normal) <6460c5>; lua; antivirus.lua:43: clamav: virus found: "winnow.spam.ts.xmailer.2.UNOFFICIAL"
2017-03-06 02:49:15 #8254(normal) <6460c5>; task; lua_task_set_pre_result: <undef>: set pre-result to greylist: 'clamav: viru
s found: "winnow.spam.ts.xmailer.2.UNOFFICIAL"'

Error! Both scanners triggered now.

### Configuration:
See above

### Additional information:
-

**Comment by fatalbanana** [comment]
https://github.com/vstakhov/rspamd/pull/1483 should fix it.

**Comment by croessner** [comment]
Yes, it fixes this issue
