### ISSUE TITLE
DKIM signing

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1486]
Hello,

I saw in v1.5 it is possible to sign messages with rspamd instead of rmilter.
Until now I use rmilter for signing. What is the recommended method?

Thanks!

**Comment by fatalbanana** [comment]
[Use rspamd](https://rspamd.com/rmilter/#project-state).

[DKIM signing module](https://rspamd.com/doc/modules/dkim_signing.html) and [DKIM plugin's sign_condition](https://rspamd.com/doc/modules/dkim.html#dkim-signatures) are options.

**Comment by madorin** [comment]
Fatalbanana, thanks for quick reply!

OK, so what exactly do you recommend, "C internal DKIM" or "Lua Signing DKIM" ?

I find rmilter way much simpler, and probably it works faster than parsing Lua sign_condition function or using Lua DKIM signing.

Currently i have in rmilter config just:

```
dkim {
    domain {
                key = /etc/dkim;
                domain = "*";
                selector = "dkim";
        };
    header_canon = relaxed;
    body_canon = relaxed;
    sign_alg = sha256;
};

```

and it is enough to sign all messages ;) Can we have something similar in rspamd ?

Also, strange, after upgrade *lua* stuff gone. There is no "rspamd.lua" file, as I see in config a reference to it. Should I install lua package/modules separately? I use Debian official package on Debian v8.7.

Thanks!

**Comment by fatalbanana** [comment]
[DKIM signing module](https://rspamd.com/doc/modules/dkim_signing.html) is the intended replacement for rmilter's DKIM signing and can be configured similarly:

```
dkim_signing {
  path = "/etc/dkim/$domain.$selector.key";
  selector = "dkim";
}
```

`dpkg-query -L rspamd` should help to find `rspamd.lua`.

**Comment by madorin** [comment]
Great, thanks for config sample, works like a charm!
Probably this sample should be added in wiki/how-to, because an "universal" sample I didn't found in docs.

One last question, I added dkim_signing options in local.d/common.conf
It there a "better" way where to put it, like in /local.d/dkim_signing.conf ? or common is the best way?
Sorry for stupid questions, but did not found it on plugin page or in plugins overview section, where exactly  configure a plugin.

**Comment by fatalbanana** [comment]
`local.d/dkim_signing.conf` will [work in rspamd 1.5.2+](https://github.com/vstakhov/rspamd/commit/7b94f845f7732c3c8b5a70d8b29a482a91a68f32).

[DKIM signing module documentation](https://rspamd.com/doc/modules/dkim_signing.html) is the intended reference for this functionality; [pull requests welcome](https://github.com/vstakhov/rspamd.com/blob/master/doc/modules/dkim_signing.md).

**Comment by jnhmn** [comment]
How do I specify multiple domains?
My current code looks like this, but does not work:
`  # Domain specific settings
    domain {
      example.com {
        path = "/etc/mail/example.com/default.private";
        selector = "default";
      }   
      example.net {
        path = "/etc/mail/example.net/default.private";
        selector = "default";
      }   
      example.org {
        path = "/etc/mail/example.org/default.private";
        selector = "default";                                                                                                                                 
      }   
    }   
`

**Comment by fatalbanana** [comment]
@jnhmn, that looks fine.

**Comment by jnhmn** [comment]
But it does not work:
```
Mär 14 10:26:57 glados rspamd[31574]: (normal) <87c4af>; task; lua_dkim_sign_handler: cannot load dkim key /var/lib/rspamd/dkim/example.com.default.key: cannot map private key /var/lib/rspamd/dkim/example.com.default.key: File not found
```

It tries to use the default configuration, not the domain specific.
I copied the whole dkim_signing.conf from modules.d to local.d and stripped it of its header and footer.
If I change the `path` in the global section of this config file it works...

**Comment by fatalbanana** [comment]
DKIM signing domain will use domain in `From:` header (unless configured to use envelope-sender instead). It will try to use domain-specific settings and fall back to defaults if these are missing (and fallback is not disabled). I think you have opened a new issue for this so better not to junk up this one.

You can get more insight into what DKIM signing module does by setting `debug_modules = ["dkim_signing"];` in `local.d/dkim_signing.conf`- error message you show suggests there's no key at the path it's configured to use.

**Comment by LaCostaSK** [comment]
Hi, it's good idea use external file for domains list ? Like ...

**local dkim_domains = io.open("/opt/dkim/dkim_domains", "r" )
	local domains = {}
	for line in dkim_domains:lines() do
	domains[#domains + 1] = line;
    end
io.close( dkim_domains )**

instead

  **local domains = {
    'example.net'
  }**

in dkim.conf

Something like IP_WHITELIST where i can map file with ip range in single line.

Sorry for english, is not my native lang.
