### ISSUE TITLE
Antivirus plugin configuration

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1491]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5

### Operation system, CPU, memory and environment:
Debian 8.7 x64

### Description (Please provide a descriptive summary of the issue):
Trying to migrate antivirus scanning from rmilter to rspamd.

Code in rmilter configuration that works:
```
clamav {
  servers = 127.0.0.1:3310;
  connect_timeout = 1s;
  port_timeout = 4s;
  results_timeout = 20s;
  error_time = 10;
  dead_time = 300;
  maxerrors = 10;
};
```

I commented it out and added the following according to the docs in rspamd.conf.local:
```
antivirus {
  first {
    symbol = "CLAM_VIRUS";
    action = "reject";
    type = "clamav";
    servers = "127.0.0.1:3310";
  }
}
```

In rspamd.log I see no errors, plugin is loaded:
```
(main) <mif31a>; lua; global_functions.lua:105: using default redis server for module antivirus
(main) <mif31a>; cfg; rspamd_init_lua_filters: init lua module antivirus
```

But, unfortunately mail (in and out) is not scanned :( I do tests with eicar sample file.
I added even "strict_auth = false;" in rmilter conf, with no luck.
Any hints to check for? 

### Expected results:
Scan emails

### Actual results:
Email is not scanned

**Comment by fatalbanana** [comment]
You should be using rspamd 1.5.1 or better.

**Comment by madorin** [comment]
Fatalbanana, it is not yet available as "packaged". any eta?

**Comment by fatalbanana** [comment]
It [looks](https://rspamd.com/apt-stable/pool/main/r/rspamd/) like packages are published.

**Comment by madorin** [comment]
Ops, it seems I have 1.5.1 as webadmin panel show :). Just saw v1.5 on your website/blog.
Camav log is clean, it seems file even is not sent to clamav engine...
Strange that no config errors are reported in rspamd log.
When i run it unconfigured it wrote "disabling unconfigured antivirus module".

**Comment by fatalbanana** [comment]
I suppose you may need to set `attachments_only = false;` to see something happening (without this only messages with non-image attachments are checked).

**Comment by madorin** [comment]
Fatalbanana, I send test file as attachement.
Anyway, I added it, now config looks like:
```
antivirus {
  first {
    attachments_only = false;
    symbol = "CLAM_VIRUS";
    action = "reject";
    type = "clamav";
    servers = "127.0.0.1:3310";
  }
}
```
Still no scanning.
Increased logging to level debug:
```
(main) <w5y7fj>; lua; global_functions.lua:105: using default redis server for module antivirus
(main) <w5y7fj>; symcache; rspamd_symbols_cache_add_symbol: used items: 271, added symbol: CLAM_VIRUS, 270
(main) <w5y7fj>; cfg; rspamd_init_lua_filters: init lua module antivirus
```
No other record related to antivirus.

**Comment by madorin** [comment]
Some caching lookups appearing, like
```
(normal) <8340bb>; antivirus; antivirus.lua:283: saved cached result for rs_cl6dbbce7694e8a194987e6c72aef11731: OK
```
So, module seems working, but no scanning is done...

**Comment by fatalbanana** [comment]
Seems that scanning was done and a result was cached.

You can disable caching by setting `disabled_modules = ["antivirus"];` in your redis configuration.

**Comment by madorin** [comment]
disabled cache, cleared redis cache, nothing ...
maybe something related to outbound mail scanning?

**Comment by fatalbanana** [comment]
`(normal) <8340bb>; antivirus; antivirus.lua:283: saved cached result for rs_cl6dbbce7694e8a194987e6c72aef11731: OK`

suggests it actively spoke to scanner and got something that didn't look like a positive match.

**Comment by madorin** [comment]
Strange, why then it detects virus using rmilter...
I'll try to enable loging in clamav even for negative virus results..

**Comment by madorin** [comment]
OK, it seems it does not scan outbound emails. I send them authenticated. Any settings to check?

For incomming, i see in clamav.log:
Tue Mar  7 13:25:50 2017 -> instream(127.0.0.1@35753): OK

For outgoing - log is clear.

**Comment by madorin** [comment]
Upgraded to 1.5.2, moved antivirus config options in antivirus.conf
Same issue, outgoing mail is not scanned.

**Comment by fatalbanana** [comment]
That's issue of rmilter - you want `strict_auth = true` I suppose (no/false is default; "scanning outbound" page is wrong, I will fix that).

**Comment by madorin** [comment]
Fatalbanana, added "strict_auth = true/yes", outgoing emails appears in rspamd webpanel history as scanned, but antivirus module anyway is not triggered. I think it is a bug/issue in antivirus plugin.

According to new design, I think rmilter should pass to rspamd all emails because global "strict_auth" flag is not so informative/logical in this case. Later in rspamd we may control what plugins activate, based on email properties. For example we want antivirus and limits for authenticated emails but no spam scanning.

For exceptions, Rmilter should have a setting in spamd { like:
bypass or `ignore = mynetworks, authenticated;`

**Comment by fatalbanana** [comment]
> Fatalbanana, added "strict_auth = true/yes", outgoing emails appears in rspamd webpanel history > as scanned, but antivirus module anyway is not triggered. I think it is a bug/issue in antivirus 
> plugin.

I can't replicate that - mail from authenticated users is scanned and there is nothing in antivirus module that might make it otherwise; maybe you are disabling the check with [settings](https://rspamd.com/doc/configuration/settings.html). Maybe there is something interesting in logs.

Setting `strict_auth = true;` enables Rmilter to send authenticated/local mail to Rspamd, I see no problem with that.

**Comment by madorin** [comment]
OK, after playing more with "strict_auth = true" (yep, doc is wrong on the site) and removing "antivirus {}". leaving just clamav { from antivirus.conf file it finally worked :) thanks for your support!

> Setting strict_auth = true; enables Rmilter to send authenticated/local mail to Rspamd

OK, initially, when rmilter had virus scanning, limits and other features, it activates them regardless of "strict_auth" setting, right? "strict_auth" was just for _spam_ control (initial function of rspamd), pass it to rspamd or not. Antivirus worked for _any_ message, if it is defined in rmilter. Now, after its migration to rspamd, if we need "antivirus" we should to set strict_auth to "true" otherwise it will not work. 

Now when all these features are moved to rspamd and rspamd works just as a bridge, we need to control what functions/plugins should be activated, because now _all_ messages are scanned for spam that come to rspamd, even if for authenticated I need for example just antivirus scanning and limits. Is there a way to disable spam scanning for authenticated messages now?

That's why I proposed to add a setting in rmilter config, rspamd { section, what messages should be bypassed and for long therm deprecate strict_auth, because it a) is a global setting (but control just rspamd) and b) it's name does not mean explicitly "send to rspamd".

**Comment by fatalbanana** [comment]
You can use [settings](https://rspamd.com/doc/configuration/settings.html) to conditionally deactivate checks (or enable just a few select ones).

**Comment by madorin** [comment]
Greeped all /etc/rspamd and did not found current settings defined. Just in docs, by your link. OK, will give them a try.

For newcomers I think some samples in distro or default presets just to uncomment them will be a good idea. Not everyone need by default as it is now spam control for outgoing email (while having antivirus & limits active).

**Comment by mpizzoli** [comment]
Hello,

Il giorno mer 8 mar 2017 alle 15:31 Dorin Marcoci <notifications@github.com>
ha scritto:

> Greeped all /etc/rspamd and did not found current settings defined. Just
> in docs, by your link. OK, will give them a try.
>
> For newcomers I think some samples in distro or default presets just to
> uncomment them will be a good idea. Not everyone need by default as it is
> now spam control for outgoing email (while having antivirus
>
& limits active).
>
> —
>

+1

Thank you very much
Marco

**Comment by vstakhov** [comment]
@madorin could you please explain your suggestion in a more detailed way? There is https://rspamd.com/doc/tutorials/scanning_outbound.html tutorial that describes outbound scanning.

**Comment by madorin** [comment]
@vstakhov as rmilter now acts as a simple bridge between MTA and Rspamd (plus maybe other services), I think routing flag (send message to rspamd or skip it) should be inside spamd { directive, like I said: (bypass/ignore/skip/except = mynetworks, authenticated;)
At least place and name is more suggestive and offer more control than a global "strict_auth".

**Comment by vstakhov** [comment]
Yes, but this is historical settings. I cannot just break compatibility...

**Comment by madorin** [comment]
Understand and partially agree.
But as long as clamav, limits are planned to be removed from Rmilter this option can be removed too.
Initially take it into account if new setting is not defined, later in a major version get rid of it.
This approach is great that all engines like rspamd will run as plugins, and "except" flag will control message routing, pass them or not.
Anyway, not a big deal, but it will be nice ;)
