### ISSUE TITLE
Greylisting Ratelimit Deadlock

### ISSUE THREAD

**Issue by kristous** [vstakhov/rspamd#1498]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.2

### Operation system, CPU, memory and environment:
Debian Jessie, CPU 1 Intel, 4GB RAM, KVM Guest

### Description (Please provide a descriptive summary of the issue):
Ratelimit is already counting while greylisting is in progress.

### Additional information:

Today I investigated following problem.
A big telecom company was trying to send an invoice to one of our customers. Greylisting kicked in and said come back later. As it seems they send mails using some crappy java application instead of a real mailserver, they try to deliver this invoice several times per minute.
So before the greylisting timeout is over the client is already over the ratelimit.
And as this client tries very often the mails are never delivered.

For the moment I fixed this using a whitelist.

My "Feature Request" would be to do ratelimiting only if there is no greylisting active.
In this case it was a single email which could not be delivered due ratelimiting.

**Comment by vstakhov** [comment]
This should be fixed now.
