### ISSUE TITLE
Displaying receiver and subject in webui history

### ISSUE THREAD

**Issue by enskymedia** [vstakhov/rspamd#1509]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.1

### Description (Please provide a descriptive summary of the issue):
For debugging the spamfilter i want to display the receiver address and rhe subject of the scanned mails in the history of the rspamd webinterface. Is this possible and if yes how could i do that?

**Comment by vstakhov** [comment]
That is not possible without breaking backwards compatibility.

**Comment by enskymedia** [comment]
Do you habe any other idea how i can get false positives?

**Comment by fatalbanana** [comment]
Maybe [metadata exporter](https://rspamd.com/doc/modules/metadata_exporter.html) could help (or copy mail in your MTA).

**Comment by moisseev** [comment]
> That is not possible without breaking backwards compatibility.

@vstakhov , Are you talking about changing of /var/db/rspamd/rspamd.history format?
I don't think that is an issue as history has very limited lifetime.

**Comment by enskymedia** [comment]
I think it would be a good feature for the future.

**Comment by fatalbanana** [comment]
This works using [redis history](https://rspamd.com/doc/modules/history_redis.html) which is default-enabled in [1.5.4](https://rspamd.com/downloads.html) (but requires redis to be [configured](https://rspamd.com/doc/configuration/redis.html)).
