### ISSUE TITLE
rspamc puts headers in mail part

### ISSUE THREAD

**Issue by dploeger** [vstakhov/rspamd#1510]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Operation system, CPU, memory and environment:

* Ubuntu 16.04.2
* 2x vCPU
* 8GB RAM

### Description (Please provide a descriptive summary of the issue):

I have the following setup:

* postfix => procmail => spamassassin, rspamc --mime

Today a customer notified me of several emails, that are displayed weird in his Outlook. Sometimes, Spam-Status headers are displayed and one mail was completely scrambled.

I looked at the raw message and found the following:

```
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
MIME-Version: 1.0
X-Spam-Scanner: rspamc 1.5.2
X-Spam-Scan-Time: 0.180
X-Spam-Action: no action
X-Spam-Score: 1.40 / 9999.00
X-Spam-Level: **
X-Spam-Symbols: FROM_HAS_DN,PREVIOUSLY_DELIVERED,RCVD_IN_DNSWL_NONE,
	TO_DN_ALL,RCVD_COUNT_3,FROM_EQ_ENVFROM,R_SPF_NA,RCPT_COUNT_1,ASN,DMARC_NA,
	R_DKIM_NA,AUTH_NA,MIME_GOOD,SUBJECT_ENDS_SPACES

SGFsbG8gSGVyciBHYXJiZ
```

So it seems, that rspamc --mime has added the headers inside a mail part. Is this a bug or is something weird in my setup?

### Expected results:

Headers are put outside of mail parts.

### Actual results:

Under unknown conditions the headers are put inside a mail part.

### Configuration:
* postfix => procmail => spamassassin, rspamc --mime

**Comment by vstakhov** [comment]
Do you have the exact mail sample? If it contains something private you can send it to my email encrypting using my gpg key.

**Comment by dploeger** [comment]
@vstakhov I've sent it to you personally because of minor privacy issues.

**Comment by vstakhov** [comment]
This email looks completely fine to me. Why do you think it is broken? Rspamc folds headers if they are too long. The only thing I'm worried about is line endings. Rspamc assumes that they are `\r\n`. Hence, if your MTA does not normalise headers then it might be an issue...

**Comment by dploeger** [comment]
Oh, right. I originally thought, Outlook would get confused because of the header between MIME-Version, but maybe it's the line endings. I'll check my configuration for that. Thanks!

**Comment by dploeger** [comment]
@vstakhov All my other mails seem to use \n line endings. Can I change the setting for rspamd?

**Comment by dploeger** [comment]
It seems, Postfix removes CRLF (which is the SMTP standard) upon receiving mail and adds LF-endings (which is the line ending standard of my unix-server) upon transporting to procmail

**Comment by vstakhov** [comment]
Why don't you use Rmilter for Postfix?

**Comment by dploeger** [comment]
I'm using an automated setup controlled by Virtualmin and wanted to use the least-invasive method. If the line encodings can not be parametrized, I'll have to check, if I could use the rmilter-setup.

**Comment by vstakhov** [comment]
I've added the fix in the master branch.

**Comment by dploeger** [comment]
Very nice. Thank you. Is a new version coming soon to include this or should I use the head version?
