### ISSUE TITLE
Whitelist module loaded but has no effect

### ISSUE THREAD

**Issue by tleuxner** [vstakhov/rspamd#1514]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

 1.5.2

### Description (Please provide a descriptive summary of the issue):
I'm trying to Whitelist certain DKIM domains to help with their score. When I reload rspamd I don't see any *.inc files from the Whitelist module loaded. Changes to the files in the DB dir are also not picked up. Per documentation the module seems to require no further 'activation', it just doesn't act on incoming mails.

### Configuration:

$ l /var/lib/rspamd/dkim_whitelist.inc.local
-rw------- 1 _rspamd _rspamd 32 Mar 13 10:29 /var/lib/rspamd/dkim_whitelist.inc.local

Mar 13 10:17:04 nihlus rspamd[60497]: <c77rsr>; cfg; rspamd_init_lua_filters: init lua module whitelist

whitelist {
    rules {
        WHITELIST_SPF {
            valid_spf = true;
            domains [
                "/etc/rspamd/spf_whitelist.inc",
                "/var/lib/rspamd/spf_whitelist.inc.local",
            ]
            score = -1.0;
            description = "Mail comes from the whitelisted domain and has a valid SPF policy";
        }
        WHITELIST_DKIM {
            valid_dkim = true;
            domains [
                "/etc/rspamd/dkim_whitelist.inc",
                "/var/lib/rspamd/dkim_whitelist.inc.local",
            ]
            description = "Mail comes from the whitelisted domain and has a valid DKIM signature";
            score = -1.0;
        }
        WHITELIST_SPF_DKIM {
            valid_spf = true;
            valid_dkim = true;
            domains [
                "/etc/rspamd/spf_dkim_whitelist.inc",
                "/var/lib/rspamd/spf_dkim_whitelist.inc.local",
            ]
            score = -3.0;
            description = "Mail comes from the whitelisted domain and has valid SPF and DKIM policies";
        }
        WHITELIST_DMARC {
            valid_dmarc = true;
            domains [
                "/etc/rspamd/dmarc_whitelist.inc",
                "/var/lib/rspamd/dmarc_whitelist.inc.local",
            ]
            score = -7.0;
            description = "Mail comes from the whitelisted domain and has valid DMARC and DKIM policies";
        }
    }
}

**Comment by fatalbanana** [comment]
That should be fixed in the master - thank you for the report.

**Comment by tleuxner** [comment]
Patched the LUA file and looks promising (Have yet to receive mail from listed domains).

Mar 14 10:13:02 nihlus rspamd[60497]: <7md9xi>; map; rspamd_map_add: added map /var/lib/rspamd/dmarc_whitelist.inc.local

**Comment by tleuxner** [comment]
Looks good now. File modifications in DB dir get picked up :)

Mar 14 11:02:53 nihlus rspamd[2471]: <7md9xi>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/dmarc_whitelist.inc.local
Mar 14 11:02:53 nihlus rspamd[2471]: <7md9xi>; map; read_map_file: read map data from /var/lib/rspamd/dmarc_whitelist.inc.local (92 bytes)
Mar 14 11:02:53 nihlus rspamd[2471]: <7md9xi>; map; rspamd_kv_list_fin: read hash of 5 elements

Actual score gets applied: symbols: WHITELIST_SPF_DKIM(-3.00)[domain.tld]

Thanks.
