### ISSUE TITLE
Add header always

### ISSUE THREAD

**Issue by ezh** [vstakhov/rspamd#1515]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rspamd -v
Rspamd daemon version 1.5.2

### Operation system, CPU, memory and environment:
Docker version 1.13.1, build 092cba3

### Description (Please provide a descriptive summary of the issue):
Rspamd ignore  'add_header' value.
I use default rspamd configuration right out of the box. The only modification is add_header = -15; I wand to store all information within mail messages (about HAM too) while testing and configuring rspamd.

### Steps to reproduce:
Add 'add_header = -15;' to metric.conf as noted at https://rspamd.com/doc/configuration/metrics.html
And I didn't see headers with add_header = 0 too

### Expected results:
Rspamd headers within mail message

### Actual results:
No rspam headers

### Configuration:
rspamadm configdump | head
lua = "/rspamd/plugin/rules/rspamd.lua";
metric {
    name = "default";
    actions {
        reject = 15;
        add_header = -15;
        greylist = 4;
    }
### Additional information:

017-03-13 09:47:11 #17(normal) <a617e0>; task; rspamd_task_write_log: id: <vstakhov/rspamd/issues/1514@github.com>, qid: <1cnMZE-00005D-Vn>, ip: 167.89.101.198, from: <bounces@sgmail.github.com>, (default: F (no action): [-0.35/15.00] [MV_CASE(0.50){},DMARC_POLICY_ALLOW(-0.25){none;github.com;},R_DKIM_ALLOW(-0.20){github.com;},R_SPF_ALLOW(-0.20){+ip4:167.89.0.0/17;},MAILLIST(-0.10){generic;},MIME_GOOD(-0.10){multipart/alternative;text/plain;},ASN(0.00){asn:11377, ipnet:167.89.96.0/20, country:US;},FORGED_RECIPIENTS_MAILLIST(0.00){},FORGED_SENDER_MAILLIST(0.00){},FROM_HAS_DN(0.00){},FROM_NEQ_ENVFROM(0.00){bounces@sgmail.github.com;notifications@github.com;},HAS_REPLYTO(0.00){},MID_RHS_MATCH_FROM(0.00){},RCPT_COUNT_2(0.00){},RCVD_COUNT_4(0.00){},REPLYTO_DOM_NEQ_FROM_DOM(0.00){},RWL_MAILSPIKE_VERYGOOD(0.00){198.101.89.167.rep.mailspike.net : 127.0.0.19;},TO_DN_ALL(0.00){}]), len: 11541, time: 2088.238ms real, 38.348ms virtual, dns req: 22, digest: <b72e52e107e5d7f78e57d56dac4d8e6c>, rcpts: <ezh@ezh.msk.ru>, mime_rcpt: <rspamd@noreply.github.com>

**Comment by fatalbanana** [comment]
You're looking for rmilter's [extended_spam_headers](https://rspamd.com/rmilter/configuration.html) setting I suppose, guessing you use rmilter. You might also be interested in the `spamd_never_reject` setting.

Rspamd assumes that all actions in metric should have some particular ordering WRT scores: reject should be > add header > greylist > no action (0). Some plugins assumes that mail with a negative score is ham so you should probably maintain this convention too.

**Comment by ezh** [comment]
I use latest exim 4.89 https://github.com/ezh/docker-exim-sourcebased
And I want to reject spam with score more than 15.

My use case is to tune low values +-0
Then I want to use headers only for spam.
Is it out of scope?

**Comment by fatalbanana** [comment]
If you use Exim, you already directly control when headers are added/how these look and when messages are rejected. [Example configuration](https://rspamd.com/doc/integration.html) does:

```
  # add spam-score and spam-report header when told by rspamd
  warn  spam       = nobody:true
        condition  = ${if eq{$spam_action}{add header}}
        add_header = X-Spam-Score: $spam_score ($spam_bar)
        add_header = X-Spam-Report: $spam_report
```

You could remove `condition` to add it always.

**Comment by ezh** [comment]
Actually I use ELK for rspam logs, so I may create kibana dashboard for deep analyze, but it is a bit overkill from my point of view.
You may close this ticket as rejected if you wish.

IMHO Not always someone have Kibana. Also my use case is common especially for small deployment.

**Comment by ezh** [comment]
Great!

**Comment by ezh** [comment]
X-Spam-Score: -0.8 (/)
X-Spam-Report: Action: no action
 Symbol: TO_DN_ALL(0.00)
 Symbol: FROM_EQ_ENVFROM(0.00)
 Symbol: PREVIOUSLY_DELIVERED(0.00)
 Symbol: RCVD_COUNT_4(0.00)
 Symbol: R_SPF_ALLOW(-0.20)
 Symbol: RCVD_IN_DNSWL_NONE(0.00)
 Symbol: R_DKIM_ALLOW(-0.20)
 Symbol: FREEMAIL_ENVFROM(0.00)
 Symbol: ASN(0.00)
 Symbol: TO_MATCH_ENVRCPT_ALL(0.00)
 Symbol: FROM_HAS_DN(0.00)
 Symbol: RWL_MAILSPIKE_GOOD(0.00)
 Symbol: DMARC_POLICY_ALLOW(-0.25)
 Symbol: FREEMAIL_FROM(0.00)
 Symbol: MIME_GOOD(-0.10)
 Symbol: RCPT_COUNT_1(0.00)

Awesome! Thank you.

**Comment by moisseev** [comment]
@fatalbanana, would you add this to the docs?
> scores: reject should be > add header > greylist > no action (0)

Probably `rspamadm configtest` should check this as well.
