### ISSUE TITLE
DKIM_SIGNATURE Module and Mailman

### ISSUE THREAD

**Issue by jnhmn** [vstakhov/rspamd#1520]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.2
### Operation system, CPU, memory and environment:
* Debian 8.7
* Mailman 2.1.20
* Postfix  2.11.3-1
### Description (Please provide a descriptive summary of the issue):

We are using mailman on it's own subdomain with the same postfix server as the other mail traffic.
But the rspamd is not even called for outgoing mails from mailman.
Mailman is installed locally.
Mail Log excerpt for a testmail:
```
Mar 14 06:26:16 glados postfix/smtpd[20671]: 6D2E9D736F: client=localhost[::1]
Mar 14 06:26:16 glados rmilter[12501]: <d10407dca8>; mlfi_data: queue id: <6D2E9D736F>
Mar 14 06:26:16 glados postfix/cleanup[20675]: 6D2E9D736F: message-id=<c4e8a758-d183-0092-f510-256b34c75e8f@example.net>
Mar 14 06:26:16 glados rmilter[12501]: <d10407dca8>; mlfi_eom: tempfile=/tmp/msg.XX9xaSPj, size=6209
Mar 14 06:26:16 glados rmilter[12501]: <d10407dca8>; msg done: queue_id: <6D2E9D736F>; message id: <>; ip: ::1; from: <list-bounces@example.com>; rcpt: <user@example.com> (6 total); user: unauthorized; spam scan: skipped, whitelisted; virus scan: skipped, no av servers; dkim: not
 signed, ignored
Mar 14 06:26:16 
```

How do I get rspamd to sign thes messages, too?

**Comment by jnhmn** [comment]
Yes, I've set this option. It already works with authenticated users.
Current configuration is already posted here: https://github.com/vstakhov/rspamd/issues/1521

**Comment by fatalbanana** [comment]
If rmilter doesn't send mail to rspamd that's rmilter issue. I understood `strict_auth` applied to mail from local networks (and the localhost), too. In case it should not work as expected I've no ideas I'm afraid.

**Comment by vstakhov** [comment]
You might need to specify `non_smtpd_milters` in Postfix: http://www.postfix.org/MILTER_README.html

**Comment by jnhmn** [comment]
Did not work.

I wonder, why local mails are flagged as `whitelisted` by rmilter, while authenticated mails are not.
(See log excerpt above)
And this except for an authenticated user
```
rmilter[14750]: <b136a517cf>; msg done: queue_id: <5468FD738D>; message id: <36eabb24-936d-22c3-22c2-1ee28fc4314a@example.com>; ip: [disclosed]; from: <user@example.com>; rcpt: <user@example.net> (1 total); user: user; spam scan: no spam; virus scan: skipped, no av servers; dkim: not signed, ignored
```

**Comment by vstakhov** [comment]
Because Rmilter has `whitelist` and `our_networks` options that include localhost by default.

**Comment by jnhmn** [comment]
But should'nt `strict_auth` disable this whitelisting?
> `strict_auth`: strict checks for mails from authenticated senders (if it is `no` then messages originated from authenticated users and `our_networks` are **NOT** checked - that’s a **default** value)

**Comment by madorin** [comment]
That's why `strict_auth` is a good candidate for removal ;) An `except` option _inside_ spamd section offers more control and flexibility.

**Comment by fatalbanana** [comment]
Issue seems to have been resolved; and is about rmilter.
