### ISSUE TITLE
Adding gitter or slackin?

### ISSUE THREAD

**Issue by pratik60** [vstakhov/rspamd#1527]
### Classification:

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

#### Proposal
Switch primary chat medium to either [gitter](https://gitter.im/) or [slackin](https://github.com/rauchg/slackin)

#### Problem
The world is moving forward. The popularity of IRC, the work horse of chat protocols, is declining. The new developers feel more comfortable to use services which provide modern user experience. IRC is not what they are used to and what they do not want to use. Gitter/Slackin allows searchable chat history, allowing people to dig in before asking for help.

#### Solution
To stay in tune with the times and developer community I'd propose to have Gitter/Slackin  for chat to have newcomer developers to have more welcoming experience. This could both be in addition to or completely remove IRC.

#### Counter arguments

This would split the community as I feel most of the old timers would not be willing to join another chat room. 

#### Thoughts?

Do we have any strong opinions on using irc? I feel like unless we have strong reasons, we should switch.

There are some really good open source repositories which have now switched from irc to one of the above - [ember.js](https://github.com/emberjs), [mongoose](https://github.com/Automattic/mongoose), [chai](https://github.com/chaijs/chai), [rails](https://medium.freecodecamp.com/best-gitter-channels-on-ruby-87ec12ead3d3#.ukmy2ptp1), [Jumper in lua](https://github.com/Yonaba/Jumper)

**Comment by vstakhov** [comment]
I'm happy with IRC. I've tried slack and found it slow, bloated and completely brain damaged app with enormous amount of bugs. Hence, there are no plans to leave IRC.

**Comment by fatalbanana** [comment]
We have a [Telegram group](https://rspamd.com/support.html) now.
