### ISSUE TITLE
feature request: language detection

### ISSUE THREAD

**Issue by vixns** [vstakhov/rspamd#1530]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Description (Please provide a descriptive summary of the issue):

Is it possible to add language detection ?
I'd like to have symbols listing detected languages' iso codes.

**Comment by fatalbanana** [comment]
We have some form of language detection already: https://rspamd.com/doc/lua/mimepart.html#mb8f0b

**Comment by asbachb** [comment]
For the ones coming from google - as the links above are broken: https://rspamd.com/doc/lua/examples.html#languages-filter
