### ISSUE TITLE
Whitelist Module may not pick up on maps

### ISSUE THREAD

**Issue by tleuxner** [vstakhov/rspamd#1535]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.3

### Description (Please provide a descriptive summary of the issue):
I'm not entirely sure if the patch to include whitelists as maps as is effective. I did not pick up on previously whitelisted domains. I'm still monitoring but a diff shows logic changes vs. the original commit.

```lua
-      for map, mult in pairs(rule['maps']) do
+      for map, mmult in pairs(rule['maps']) do
         local val = map:get_key(dom)
         if val then
           if #val > 0 then
             mult = tonumber(val)
+          else
+            mult = mmult
           end
           table.insert(domains, dom)
           return true,mult
```

**Comment by fatalbanana** [comment]
What do you suppose doesn't work? How to replicate this?

**Comment by tleuxner** [comment]
The domains are not whitelisted, compared to the old version where the mmult variable had not been introduced.

Pre 1.5.3 with git patch applied:

Mar 17 07:33:13 nihlus rmilter[966]: <4bb581e052>; spamdscan: scan, time: 0.226, server: 127.0.0.1, metric: default: [1.950 / 15.000], symbols: **WHITELIST_SPF_DKIM(-3.00)[],** HFILTER_URL_ONLY(2.20)[], BAYES_HAM(-3.00)[], PHISHING(3.75)[], R_SUSPICIOUS_IMAGES(2.10)[], URI_COUNT_ODD(1.00)[], HTML_SHORT_LINK_IMG_2(1.00)[], WHITELIST_DKIM(-1.00)[], FROM_HAS_DN(0.00)[], ASN(0.00)[], DMARC_NA(0.00)[], RWL_MAILSPIKE_GOOD(0.00)[], ONCE_RECEIVED(0.10)[], R_SPF_ALLOW(-0.20)[], FROM_NEQ_ENVFROM(0.00)[], RCPT_COUNT_1(0.00)[], TO_MATCH_ENVRCPT_ALL(0.00)[], TO_DN_ALL(0.00)[], MIME_GOOD(-0.10)[], RCVD_COUNT_1(0.00)[], R_DKIM_ALLOW(-0.20)[], FORGED_SENDER(0.30)[], WHITELIST_SPF(-1.00)[], RCVD_IN_DNSWL_NONE(0.00)[]
Mar 17 07:33:13 nihlus rmilter[966]: <4bb581e052>; msg done: queue_id: <3vkwWr3k2fz1m>; message id: <0102015adaf84efa-1739d85e-3920-43d4-b67b-cd4f5dda8f5d-000000@eu-west-1.amazonses.com>; ip: 54.240.0.62; from: <20170317063310ecf733137ef24f21b597d522a800p0eu-c1e71vvk4kz4zs@bounces.buyvip.com>; rcpt: <tlx@leuxner.net> (1 total); user: unauthorized; spam scan: no spam; virus scan: skipped, no av servers; dkim: not signed, disabled
Mar 17 07:33:13 nihlus postfix/qmgr[1618]: 3vkwWr3k2fz1m: from=<20170317063310ecf733137ef24f21b597d522a800p0eu-C1E71VVK4KZ4ZS@bounces.buyvip.com>, size=128132, nrcpt=1 (queue active)

Post-patch:

Mar 18 07:35:45 nihlus rmilter[966]: <33067467db>; spamdscan: scan, time: 1.016, server: 127.0.0.1, metric: **default: [7.649 / 15.000],** symbols: PHISHING(3.75)[], HFILTER_URL_ONLY(2.20)[], BAYES_HAM(-3.00)[], R_SUSPICIOUS_IMAGES(2.25)[], HTML_SHORT_LINK_IMG_2(1.00)[], TO_DN_ALL(0.00)[], ASN(0.00)[], ONCE_RECEIVED(0.10)[], RCPT_COUNT_ONE(0.00)[], R_DKIM_ALLOW(-0.20)[], URI_COUNT_ODD(1.00)[], RCVD_COUNT_ONE(0.00)[], FROM_NEQ_ENVFROM(0.00)[], FROM_HAS_DN(0.00)[], RWL_MAILSPIKE_VERYGOOD(0.00)[], R_PARTS_DIFFER(0.04)[], FORGED_SENDER(0.30)[], RCVD_IN_DNSWL_NONE(0.00)[], TO_MATCH_ENVRCPT_ALL(0.00)[], R_SPF_ALLOW(-0.20)[], MIME_GOOD(-0.10)[], SUBJECT_ENDS_SPACES(0.50)[]
Mar 18 07:35:45 nihlus rmilter[966]: <33067467db>; mlfi_eom: add spam header to message according to spamd action
Mar 18 07:35:45 nihlus rmilter[966]: <33067467db>; msg done: queue_id: <3vlXXH4dWnz28>; message id: <0102015ae020fa16-9fd8f9d5-0088-484e-9f50-906afe441d12-000000@eu-west-1.amazonses.com>; ip: 54.240.0.183; from: <201703180635419ef9fe352d9240eeb246fe32d520p0eu-c202hcd188nz3u@bounces.buyvip.com>; rcpt: <tlx@leuxner.net> (1 total); user: unauthorized; spam scan: action: add header; virus scan: skipped, no av servers; dkim: not signed, disabled
Mar 18 07:35:45 nihlus postfix/qmgr[1618]: 3vlXXH4dWnz28: from=<201703180635419ef9fe352d9240eeb246fe32d520p0eu-C202HCD188NZ3U@bounces.buyvip.com>, size=120364, nrcpt=1 (queue active)

**Comment by fatalbanana** [comment]
`WHITELIST_SPF_DKIM` still seems to work AFAICT; maybe there is some issue particular to your configuration.

**Comment by tleuxner** [comment]
There was no change on my end apart from updating to 1.5.3, which updated the LUA script in regard to the diff I mentioned.

**Comment by tleuxner** [comment]
I saw our mails via GitHub came in whitelisted. Maybe this is where the problem lies:

nihlus:/var/lib/rspamd# grep github *.local
dmarc_whitelist.inc.local:github.com

nihlus:/var/lib/rspamd# grep buyvip *.local
dkim_whitelist.inc.local:buyvip.com
spf_dkim_whitelist.inc.local:buyvip.com
spf_whitelist.inc.local:buyvip.com

Judging by the GitHub score it appears as if the score did not come from the DBDIR file but the default one shipped...

grep github /etc/rspamd/spf_dkim_whitelist.inc 
github.com 2.0

Mar 18 12:29:17 nihlus rmilter[966]: <2cf1350d84>; spamdscan: scan, time: 0.436, server: 127.0.0.1, metric: default: **[-17.156 / 15.000], symbols: WHITELIST_DMARC(-7.00)[],** WHITELIST_SPF_DKIM(-6.00)[], BAYES_HAM(-3.00)[], RCVD_IN_DNSWL_HI(-1.00)[], TO_DN_ALL(0.00)[], RCPT_COUNT_THREE(0.00)[], MV_CASE(0.50)[], TO_MATCH_ENVRCPT_SOME(0.00)[], ASN(0.00)[], ONCE_RECEIVED(0.10)[], MID_RHS_MATCH_FROM(0.00)[], R_DKIM_ALLOW(-0.20)[], RCVD_COUNT_ONE(0.00)[], DMARC_POLICY_ALLOW(-0.25)[], FROM_NEQ_ENVFROM(0.00)[], MAILLIST(-0.10)[], FROM_HAS_DN(0.00)[], R_PARTS_DIFFER(0.09)[], FORGED_SENDER_MAILLIST(0.00)[], R_SPF_ALLOW(-0.20)[], MIME_GOOD(-0.10)[], HAS_REPLYTO(0.00)[], REPLYTO_DOM_NEQ_FROM_DOM(0.00)[], RWL_MAILSPIKE_POSSIBLE(0.00)[]
Mar 18 12:29:17 nihlus rmilter[966]: <2cf1350d84>; msg done: queue_id: <3vlg311fgHz28>; message id: <vstakhov/rspamd/issues/1535/287537927@github.com>; ip: 192.30.252.197; from: <noreply@github.com>; rcpt: <tlx@leuxner.net> (1 total); user: unauthorized; spam scan: no spam; virus scan: skipped, no av servers; dkim: not signed, disabled

...as if my custom files are not considered anymore:

l /var/lib/rspamd/*.local
-rw------- 1 _rspamd _rspamd 111 Mar 18 10:19 /var/lib/rspamd/dkim_whitelist.inc.local
-rw------- 1 _rspamd _rspamd  92 Mar 14 11:23 /var/lib/rspamd/dmarc_whitelist.inc.local
-rw------- 1 _rspamd _rspamd 102 Mar 15 09:09 /var/lib/rspamd/spf_dkim_whitelist.inc.local
-rw------- 1 _rspamd _rspamd 102 Mar 15 09:10 /var/lib/rspamd/spf_whitelist.inc.local

**Comment by fatalbanana** [comment]
`WHITELIST_DMARC(-7.00)[], WHITELIST_SPF_DKIM(-6.00)[]`

looks as expected AFAICT.

**Comment by tleuxner** [comment]
I can confirm it works for some mails (including *.local files), but it doesn't work for domains it used to work before. In all cases the mail successfully passes a DKIM milter before rspamd is invoked, but rspamd does not tag it WHITELIST_* using its own module.

Mar 18 15:09:59 nihlus opendkim[1248]: 3vlkcR4tX4z28: DKIM verification successful

For the ones where it doesn't work I'm puzzled how they differ from the rest...

**Comment by fatalbanana** [comment]
Maybe rspamd logs show something interesting in the problem cases?

**Comment by tleuxner** [comment]
At least I don't spot it :)

Not whitelisted:

Mar 18 13:25:10 nihlus rspamd[62985]: <8fe3d3>; task; accept_socket: accepted connection from 127.0.0.1 port 50386, task ptr: 00007F2CEC1F80F0
Mar 18 13:25:10 nihlus rspamd[62985]: <8fe3d3>; task; rspamd_message_parse: loaded message; id: <0102015ae160e41f-76d91331-222e-42e5-b7ac-89ec25f78206-000000@eu-west-1.amazonses.com>; queue-id: <3vlhHT4rYLz28>; size: 137270; checksum: <43
6a77f1a41d750bad29c69f38b9333d>
Mar 18 13:25:10 nihlus rspamd[62985]: <8fe3d3>; task; rspamd_task_write_log: id: <0102015ae160e41f-76d91331-222e-42e5-b7ac-89ec25f78206-000000@eu-west-1.amazonses.com>, qid: <3vlhHT4rYLz28>, ip: 54.240.0.27, from: <20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-c1w2jey98pw7ub@bounces.amazon.de>, (default: F (no action): [-3.10/15.00] [BAYES_HAM(-3.00){100.00%;},FORGED_SENDER(0.30){},R_DKIM_ALLOW(-0.20){amazonses.com;amazon.de;},R_SPF_ALLOW(-0.20){+ip4:54.240.0.0/18;},MIME_GOOD(-0.10){text/plain;multipart/alternative;},ONCE_RECEIVED(0.10){},ASN(0.00){asn:16509, ipnet:54.240.0.0/21, country:US;},FROM_HAS_DN(0.00){},FROM_NEQ_ENVFROM(0.00){20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-c1w2jey98pw7ub@bounces.amazon.de;store-news@amazon.de;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ONE(0.00){1;},RCVD_IN_DNSWL_NONE(0.00){27.0.240.54.list.dnswl.org : 127.0.15.0;},RWL_MAILSPIKE_GOOD(0.00){27.0.240.54.rep.mailspike.net : 127.0.0.18;},TO_DN_ALL(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 137270, time: 471.998ms real, 34.152ms virtual, dns req: 43, digest: <436a77f1a41d750bad29c69f38b9333d>, rcpts: <tlx@leuxner.net>, mime_rcpt: <tlx@leuxner.net>
Mar 18 13:25:10 nihlus rspamd[62985]: <8fe3d3>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 2 regexps matched, 272 regexps total, 94 regexps cached, 0B bytes scanned using pcre, 132.12k bytes scanned total
Mar 18 13:25:20 nihlus rspamd[62979]: <>; lua; metric_exporter.lua:186: Pushing metrics to graphite backend

Whitelisted:

Mar 18 14:44:16 nihlus rspamd[62985]: <63ae98>; task; accept_socket: accepted connection from 127.0.0.1 port 58593, task ptr: 00007F2CEC1F85F0
Mar 18 14:44:16 nihlus rspamd[62985]: <63ae98>; task; rspamd_message_parse: loaded message; id: <3vlk2G35hBzJrP6@spike.porcupine.org>; queue-id: <3vlk2l5yKxz28>; size: 5001; checksum: <12a0236c2ba3c156796812a747bd084d>
Mar 18 14:44:16 nihlus rspamd[62985]: <63ae98>; task; rspamd_task_write_log: id: <3vlk2G35hBzJrP6@spike.porcupine.org>, qid: <3vlk2l5yKxz28>, ip: 2604:8d00:0:1::4, from: <owner-postfix-users@postfix.org>, (default: F (no action): [-5.00/15.00] [BAYES_HAM(-3.00){100.00%;},WHITELIST_DKIM(-1.00){porcupine.org;},RCVD_IN_DNSWL_MED(-0.50){4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.0.0.0.0.0.0.d.8.4.0.6.2.list.dnswl.org : 127.0.5.2;},MAILLIST(-0.20){majordomo;},R_DKIM_ALLOW(-0.20){porcupine.org;},MIME_GOOD(-0.10){text/plain;},ASN(0.00){asn:3700, ipnet:2604:8d00::/32, country:US;},DMARC_NA(0.00){porcupine.org;},FORGED_RECIPIENTS_FORWARDING(0.00){},FORGED_RECIPIENTS_MAILLIST(0.00){},FORGED_SENDER_FORWARDING(0.00){},FORGED_SENDER_MAILLIST(0.00){},FROM_HAS_DN(0.00){},FROM_NEQ_ENVFROM(0.00){wietse@porcupine.org;owner-postfix-users@postfix.org;},HAS_REPLYTO(0.00){},PRECEDENCE_BULK(0.00){},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_SEVEN(0.00){9;},REPLYTO_DOM_NEQ_FROM_DOM(0.00){},R_SPF_NA(0.00){},TO_DN_ALL(0.00){}]), len: 5001, time: 60.000ms real, 12.261ms virtual, dns req: 23, digest: <12a0236c2ba3c156796812a747bd084d>, rcpts: <tlx@leuxner.net>, mime_rcpt: <postfix-users@postfix.org>
Mar 18 14:44:16 nihlus rspamd[62985]: <63ae98>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 5 regexps matched, 272 regexps total, 115 regexps cached, 0B bytes scanned using pcre, 8.24k bytes scanned total
Mar 18 14:44:20 nihlus rspamd[62979]: <>; lua; metric_exporter.lua:186: Pushing metrics to graphite backend

**Comment by fatalbanana** [comment]
What domains have you whitelisted? In default configuration, `amazon.de` is in `spf_dkim_whitelist.inc` - so it wants both of SPF and DKIM, but SPF domain was `amazonses.com`.

**Comment by tleuxner** [comment]
Here’s the original log showing the processing on the one that wasn’t whitelisted:

Mar 18 13:25:08 nihlus postfix/smtpd[21157]: connect from a0-27.smtp-out.eu-west-1.amazonses.com[54.240.0.27]
Mar 18 13:25:08 nihlus rmilter[966]: <de314a7a82>; accepted connection from spectre.leuxner.net; client: 54.240.0.27:43612 (a0-27.smtp-out.eu-west-1.amazonses.com)
Mar 18 13:25:09 nihlus postfix/smtpd[21157]: Anonymous TLS connection established from a0-27.smtp-out.eu-west-1.amazonses.com[54.240.0.27]: TLSv1 with cipher AES256-SHA (256/256 bits)
Mar 18 13:25:09 nihlus policyd-spf[21163]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=54.240.0.27; helo=a0-27.smtp-out.eu-west-1.amazonses.com; envelope-from=20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-c1w2jey98pw7ub@bounces.amazon.de; receiver=<UNKNOWN>
Mar 18 13:25:09 nihlus postfix/smtpd[21157]: 3vlhHT4rYLz28: client=a0-27.smtp-out.eu-west-1.amazonses.com[54.240.0.27]
Mar 18 13:25:09 nihlus rmilter[966]: <de314a7a82>; mlfi_data: queue id: <3vlhHT4rYLz28>
Mar 18 13:25:09 nihlus postfix/cleanup[21166]: 3vlhHT4rYLz28: message-id=<0102015ae160e41f-76d91331-222e-42e5-b7ac-89ec25f78206-000000@eu-west-1.amazonses.com>
Mar 18 13:25:10 nihlus opendkim[1248]: 3vlhHT4rYLz28: message has signatures from amazon.de, amazonses.com
Mar 18 13:25:10 nihlus opendkim[1248]: 3vlhHT4rYLz28: DKIM verification successful
Mar 18 13:25:10 nihlus opendmarc[1042]: implicit authentication service: spectre.leuxner.net
Mar 18 13:25:10 nihlus opendmarc[1042]: 3vlhHT4rYLz28: amazon.de pass
Mar 18 13:25:10 nihlus rmilter[966]: <de314a7a82>; mlfi_eom: tempfile=/tmp/msg.XXwVTota, size=137270
Mar 18 13:25:10 nihlus rmilter[966]: <de314a7a82>; spamdscan: start scanning message on 127.0.0.1
Mar 18 13:25:10 nihlus rmilter[966]: <de314a7a82>; spamdscan: finish scanning message on 127.0.0.1
Mar 18 13:25:10 nihlus rmilter[966]: <de314a7a82>; spamdscan: scan, time: 0.476, server: 127.0.0.1, metric: default: [-3.100 / 15.000], symbols: BAYES_HAM(-3.00)[100.00%], TO_DN_ALL(0.00)[], ASN(0.00)[asn:16509, ipnet:54.240.0.0/21, country:US], FROM_NEQ_ENVFROM(0.00)[20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-c1w2jey98pw7ub@bounces.amazon.de, store-news@amazon.de], ONCE_RECEIVED(0.10)[], RCPT_COUNT_ONE(0.00)[1], R_DKIM_ALLOW(-0.20)[amazonses.com, amazon.de], RCVD_COUNT_ONE(0.00)[1], RCVD_IN_DNSWL_NONE(0.00)[27.0.240.54.list.dnswl.org : 127.0.15.0], FROM_HAS_DN(0.00)[], FORGED_SENDER(0.30)[], TO_MATCH_ENVRCPT_ALL(0.00)[], R_SPF_ALLOW(-0.20)[+ip4:54.240.0.0/18], MIME_GOOD(-0.10)[text/plain, multipart/alternative], RWL_MAILSPIKE_GOOD(0.00)[27.0.240.54.rep.mailspike.net : 127.0.0.18]
Mar 18 13:25:10 nihlus rmilter[966]: <de314a7a82>; msg done: queue_id: <3vlhHT4rYLz28>; message id: <0102015ae160e41f-76d91331-222e-42e5-b7ac-89ec25f78206-000000@eu-west-1.amazonses.com>; ip: 54.240.0.27; from: <20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-c1w2jey98pw7ub@bounces.amazon.de>; rcpt: <tlx@leuxner.net> (1 total); user: unauthorized; spam scan: no spam; virus scan: skipped, no av servers; dkim: not signed, disabled
Mar 18 13:25:11 nihlus postfix/qmgr[1618]: 3vlhHT4rYLz28: from=<20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-C1W2JEY98PW7UB@bounces.amazon.de>, size=137031, nrcpt=1 (queue active)
Mar 18 13:25:11 nihlus clamsmtpd: 1006E1: accepted connection from: 127.0.0.1
Mar 18 13:25:11 nihlus postfix/smtpd[21179]: connect from localhost[127.0.0.1]
Mar 18 13:25:11 nihlus postfix/smtpd[21179]: 3vlhHW0pqYz29: client=localhost[127.0.0.1], orig_queue_id=3vlhHT4rYLz28, orig_client=a0-27.smtp-out.eu-west-1.amazonses.com[54.240.0.27]
Mar 18 13:25:11 nihlus postfix/cleanup[21166]: 3vlhHW0pqYz29: message-id=<0102015ae160e41f-76d91331-222e-42e5-b7ac-89ec25f78206-000000@eu-west-1.amazonses.com>
Mar 18 13:25:11 nihlus postfix/qmgr[1618]: 3vlhHW0pqYz29: from=<20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-C1W2JEY98PW7UB@bounces.amazon.de>, size=137613, nrcpt=1 (queue active)
Mar 18 13:25:11 nihlus clamsmtpd: 1006E1: from=20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-C1W2JEY98PW7UB@bounces.amazon.de, to=tlx@leuxner.net, status=CLEAN
Mar 18 13:25:11 nihlus postfix/smtp[21177]: 3vlhHT4rYLz28: to=<tlx@leuxner.net>, relay=127.0.0.1[127.0.0.1]:10025, delay=2.2, delays=1.9/0.02/0.06/0.23, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 3vlhHW0pqYz29)
Mar 18 13:25:11 nihlus postfix/smtpd[21179]: disconnect from localhost[127.0.0.1] ehlo=1 xforward=2 mail=1 rcpt=1 data=1 quit=1 commands=7
Mar 18 13:25:11 nihlus postfix/qmgr[1618]: 3vlhHT4rYLz28: removed

And here is what OpenDKIM came up with:

Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=54.240.0.27; helo=a0-27.smtp-out.eu-west-1.amazonses.com; envelope-from=20170318122506dd418744a26d4b55a2bc010c8ac0p0eu-c1w2jey98pw7ub@bounces.amazon.de; receiver=<UNKNOWN> 
Authentication-Results: spectre.leuxner.net; dmarc=pass (p=quarantine dis=none) header.from=amazon.de
Authentication-Results: spectre.leuxner.net;
	dkim=pass (1024-bit key) header.d=amazon.de header.i=@amazon.de header.b="d0RVeijX";
	dkim=pass (1024-bit key) header.d=amazonses.com header.i=@amazonses.com header.b="Bu1g6pBG";
	dkim-atps=neutral

And here’s one from them yesterday which used to work:

Mar 17 16:07:42 nihlus postfix/postscreen[30562]: CONNECT from [198.2.130.102]:53031 to [188.138.4.217]:25
Mar 17 16:07:42 nihlus postfix/dnsblog[30610]: addr 198.2.130.102 listed by domain list.dnswl.org as 127.0.15.0
Mar 17 16:07:42 nihlus policyd-spf[30613]: None; identity=helo; client-ip=54.240.0.174; helo=a0-174.smtp-out.eu-west-1.amazonses.com; envelope-from=201703171507402fe2b6de6506414ab2b61e005f70p0eu-c2dkzgy06yvref@bounces.amazon.de; receiver=
tlx@leuxner.net
Mar 17 16:07:42 nihlus policyd-spf[30613]: Pass; identity=mailfrom; client-ip=54.240.0.174; helo=a0-174.smtp-out.eu-west-1.amazonses.com; envelope-from=201703171507402fe2b6de6506414ab2b61e005f70p0eu-c2dkzgy06yvref@bounces.amazon.de; recei
ver=tlx@leuxner.net
Mar 17 16:07:42 nihlus postfix/smtpd[30563]: 3vl7xV3p24z1m: client=a0-174.smtp-out.eu-west-1.amazonses.com[54.240.0.174]
Mar 17 16:07:42 nihlus rmilter[966]: <fba8fbb6d4>; mlfi_data: queue id: <3vl7xV3p24z1m>
Mar 17 16:07:42 nihlus postfix/cleanup[30616]: 3vl7xV3p24z1m: message-id=<0102015adccf5905-f206feea-ec76-43c4-98fe-a72a8f97e7fb-000000@eu-west-1.amazonses.com>
Mar 17 16:07:43 nihlus opendkim[1248]: 3vl7xV3p24z1m: message has signatures from amazon.de, amazonses.com
Mar 17 16:07:43 nihlus opendkim[1248]: 3vl7xV3p24z1m: DKIM verification successful
Mar 17 16:07:43 nihlus opendmarc[1042]: implicit authentication service: spectre.leuxner.net
Mar 17 16:07:43 nihlus opendmarc[1042]: 3vl7xV3p24z1m: amazon.de pass
Mar 17 16:07:43 nihlus rmilter[966]: <fba8fbb6d4>; mlfi_eom: tempfile=/tmp/msg.XXsErJRv, size=114781
Mar 17 16:07:43 nihlus rmilter[966]: <fba8fbb6d4>; spamdscan: start scanning message on 127.0.0.1
Mar 17 16:07:44 nihlus rmilter[966]: <fba8fbb6d4>; spamdscan: finish scanning message on 127.0.0.1
Mar 17 16:07:44 nihlus rmilter[966]: <fba8fbb6d4>; spamdscan: scan, time: 0.944, server: 127.0.0.1, metric: default: [-4.850 / 15.000], symbols: BAYES_HAM(-3.00)[100.00%], WHITELIST_SPF_DKIM(-3.00)[amazon.de], FROM_HAS_DN(0.00)[], ASN(0.0
0)[asn:16509, ipnet:54.240.0.0/21, country:US], DMARC_POLICY_ALLOW(-0.25)[amazon.de, quarantine], ONCE_RECEIVED(0.10)[], R_SPF_ALLOW(-0.20)[+ip4:54.240.0.0/18], URI_COUNT_ODD(1.00)[], RWL_MAILSPIKE_POSSIBLE(0.00)[174.0.240.54.rep.mailspik
e.net : 127.0.0.17], FROM_NEQ_ENVFROM(0.00)[promotion5@amazon.de, 201703171507402fe2b6de6506414ab2b61e005f70p0eu-c2dkzgy06yvref@bounces.amazon.de], FORGED_SENDER(0.30)[], RCPT_COUNT_1(0.00)[], HTML_SHORT_LINK_IMG_3(0.50)[], TO_MATCH_ENVRC
PT_ALL(0.00)[], TO_DN_ALL(0.00)[], RCVD_IN_DNSWL_NONE(0.00)[174.0.240.54.list.dnswl.org : 127.0.15.0], MIME_GOOD(-0.10)[multipart/alternative, text/plain], RCVD_COUNT_1(0.00)[], R_DKIM_ALLOW(-0.20)[amazon.de, amazonses.com]
Mar 17 16:07:44 nihlus rmilter[966]: <fba8fbb6d4>; msg done: queue_id: <3vl7xV3p24z1m>; message id: <0102015adccf5905-f206feea-ec76-43c4-98fe-a72a8f97e7fb-000000@eu-west-1.amazonses.com>; ip: 54.240.0.174; from: <201703171507402fe2b6de650
6414ab2b61e005f70p0eu-c2dkzgy06yvref@bounces.amazon.de>; rcpt: <tlx@leuxner.net> (1 total); user: unauthorized; spam scan: no spam; virus scan: skipped, no av servers; dkim: not signed, disabled
Mar 17 16:07:44 nihlus postfix/qmgr[1618]: 3vl7xV3p24z1m: from=<201703171507402fe2b6de6506414ab2b61e005f70p0eu-C2DKZGY06YVREF@bounces.amazon.de>, size=114542, nrcpt=1 (queue active)

As to the config question I don’t have any specific mapping for them. All is coming from the default /etc/rspamd/spf_dkim_whitelist.inc.

**Comment by fatalbanana** [comment]
You have `R_DKIM_ALLOW` so there is no issue with DKIM.

SPF+DKIM whitelist (ie. `spf_dkim_whitelist.inc`) wants matching DKIM/SPF. Since DKIM/SPF doesn't seem to match in this case, maybe you'd be better off using `dkim_whitelist.inc`.

**Comment by tleuxner** [comment]
I can try. Look at the one from yesterday. It got that score: WHITELIST_SPF_DKIM(-3.00)[amazon.de],

**Comment by fatalbanana** [comment]
I need to see rspamd logs.

**Comment by fatalbanana** [comment]
I suspect your issues with whitelist module should be solved by this commit: https://github.com/vstakhov/rspamd/commit/826dfdf07987331fcac0ba9e107a63cc5d60378a

**Comment by tleuxner** [comment]
It looks good for the Amazon double-signed DKIM mails now.

I have some mails which should be whitelisted, which have valid DKIMs and should pass DMARC whitelists as well. For these neither whitelist is applied [latest git code compiled].

```Mar 27 09:04:45 nihlus rspamd[21263]: <317d18>; task; rspamd_message_parse: loaded message; id: <58d8b9896d999_1b6697e6ef44469f8@hermes-15.mail>; queue-id: <3vs4lc2p8Pz1m>; size: 122105; checksum: <b98eb2160d845d993c6aeaa5240459ae>
Mar 27 09:04:45 nihlus rspamd[21263]: <317d18>; task; make_dns_request_task_common: <58d8b9896d999_1b6697e6ef44469f8@hermes-15.mail> stop resolving on reaching 64 requests
Mar 27 09:04:46 nihlus rspamd[21263]: <317d18>; lua; url_reputation.lua:305: Not updating reputation on all TLDs
Mar 27 09:04:46 nihlus rspamd[21263]: <317d18>; task; rspamd_task_write_log: id: <58d8b9896d999_1b6697e6ef44469f8@hermes-15.mail>, qid: <3vs4lc2p8Pz1m>, ip: 109.233.158.101, from: <mailrobot@mail.xing.com>, (default: F (no action): [-2.32/15.00] [BAYES_HAM(-3.00){100.00%;},PHISHING(1.43){telecomtalk.info->xing.com;venturebeat->xing;editionf->xing;manager-magazin.de->xing.com;golem.de->xing.com;wiwo.de->xing.com;t3n.de->xing.com;welt.de->xing.com;...;},MV_CASE(0.50){},RCVD_IN_DNSWL_MED(-0.50){101.158.233.109.list.dnswl.org : 127.0.9.2;},DMARC_POLICY_ALLOW(-0.25){mail.xing.com;none;},R_DKIM_ALLOW(-0.20){mail.xing.com;},R_SPF_ALLOW(-0.20){+ip4:109.233.158.0/24;},MIME_GOOD(-0.10){multipart/alternative;text/plain;},ASN(0.00){asn:50343, ipnet:109.233.156.0/22, country:DE;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_TWO(0.00){2;},TO_DN_ALL(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 122105, time: 1167.995ms real, 43.839ms virtual, dns req: 74, digest: <b98eb2160d845d993c6aeaa5240459ae>, rcpts: <tlx@leuxner.net>, mime_rcpt: <tlx@leuxner.net>
Mar 27 09:04:46 nihlus rspamd[21263]: <317d18>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 2 regexps matched, 161 regexps total, 76 regexps cached, 0B bytes scanned using pcre, 143.58k bytes scanned total
```

rspamc -h 127.0.0.1:11333 -F mailrobot@mail.xing.com -i 109.233.158.101 /tmp/xing.msg

```
Results for file: /tmp/xing.msg (0.192 seconds)
[Metric: default]
Spam: false
Score: -2.32 / 15.00
Action: no action
Symbol: ASN (0.00)[asn:50343, ipnet:109.233.156.0/22, country:DE]
Symbol: BAYES_HAM (-3.00)[100.00%]
Symbol: DMARC_POLICY_ALLOW (-0.25)[mail.xing.com, none]
Symbol: FROM_EQ_ENVFROM (0.00)
Symbol: FROM_HAS_DN (0.00)
Symbol: MIME_GOOD (-0.10)[multipart/alternative, text/plain]
Symbol: MV_CASE (0.50)
Symbol: PHISHING (1.43)[telecomtalk.info->xing.com, venturebeat->xing, editionf->xing, manager-magazin.de->xing.com, golem.de->xing.com, wiwo.de->xing.com, t3n.de->xing.com, welt.de->xing.com, mobilegeeks.de->xing.com, portel.de->xing.com]
Symbol: PREVIOUSLY_DELIVERED (0.00)[tlx@leuxner.net]
Symbol: RCPT_COUNT_ONE (0.00)[1]
Symbol: RCVD_COUNT_FIVE (0.00)[5]
Symbol: RCVD_IN_DNSWL_MED (-0.50)[101.158.233.109.list.dnswl.org : 127.0.9.2]
Symbol: R_DKIM_ALLOW (-0.20)[mail.xing.com]
Symbol: R_SPF_ALLOW (-0.20)[+ip4:109.233.158.0/24]
Symbol: TO_DN_ALL (0.00)
Message-ID: 58d8b9896d999_1b6697e6ef44469f8@hermes-15.mail
```

**Comment by fatalbanana** [comment]
Did you whitelist `xing.com`? `mail.xing.com` won't work.

**Comment by tleuxner** [comment]
I had `mail.xing.com` in as I was under the impression it needs to match the DKIM header.

**Comment by tleuxner** [comment]
Okay that did the trick:

`Symbol: WHITELIST_DMARC (-7.00)[xing.com]`

Now this raises the question how I would be able to treat `accounts.google.com` differently to `google.com`?

The latter is used by a gazillion of users, while accounts would be relatively save to only origin from an internal system.

**Comment by fatalbanana** [comment]
`Now this raises the question how I would be able to treat accounts.google.com differently to google.com?`

Not by using whitelist module at this time, it only works on the eSLD level.

**Comment by tleuxner** [comment]
Would this be worth a feature request?

**Comment by fatalbanana** [comment]
That's for you to decide I suppose.

Currently you might use `symbol_options` in `multimap` to whitelist a long DKIM domain.
