### ISSUE TITLE
Segfault with autolearning  setup by LUA function

### ISSUE THREAD

**Issue by gp54321** [vstakhov/rspamd#1536]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Operation system, CPU, memory and environment:
Ubuntu 16 LTS  Intel Xeon 512 Mb Virtual machine

### Description (Please provide a descriptive summary of the issue):
bug when trying to use documented LUA function 

### Steps to reproduce:
configure a LUA expression to setup autolearn, returns 'ham'.

### Expected results:
autolearn is triggered as ham

### Actual results:
segfault

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

#0  0x080c0ef9 in rspamd_stat_has_classifier_symbols.isra.2 () at /rspamd-1.5.0/src/libstat/stat_process.c:941
#1  rspamd_stat_check_autolearn (task=0x9938008) at /rspamd-1.5.0/src/libstat/stat_process.c:1100

### Additional information:
well, sorry to cut short the description but the problem is pretty obvious I think.

from https://github.com/vstakhov/rspamd/blob/master/src/libstat/stat_process.c

mres is initialized to NULL at the beginning of rspamd_stat_check_autolearn 
It is set in the cases of autolearn = true and autolearn = [spam value, ham value]
but it's not in the case of a LUA function. If this LUA function return ham or spam, the rspamd_stat_has_classifier_symbols routine tries to use mres and crashes because it is still NULL.

BTW (it's an unrelated issue) in this case rspamd is called by rspamc and when this problem happens, rspamc never 'sees' a problem, do not return and consumes 100% of Cpu until it is killed. (very annoying...)

**Comment by vstakhov** [comment]
The second issue is fixed already and you are using an outdated version most likely. The second issue is more strange. Why don't you have metric result at the postfilters stage? That could happen merely if there are absolutely no symbols added to a message which is in turn quite unlikely case. Nevertheless, I've added workaround for this issue.

**Comment by gp54321** [comment]
I upgraded first to 1.5.3 and sure enough the second issue (rspamc hanging) was gone, then after waiting for the new build I upgraded again to the last version with your workaround and yes it works ! Thanks, all is well now.
