### ISSUE TITLE
wrong path to pid file in logrotate file

### ISSUE THREAD

**Issue by av1ator** [vstakhov/rspamd#1538]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.x
### Operation system, CPU, memory and environment:
centos-6
### Description (Please provide a descriptive summary of the issue):
Hello!
I installed a latest version rspamd and I found one small error - rpm for centos-6 has a  wrong path in rspam logrotate conf file (/var/run/rspamd.pid). But I checked this path in github and found this file - https://github.com/vstakhov/rspamd/blob/master/centos/sources/rspamd.logrotate and there is a correct path.
Maybe your buld system have obsolete rspamd.logrotate file?
p.s. sorry for my English

**Comment by av1ator** [comment]
rspamd-1.5.4-2.x86_64 centos-6 - the same error

**Comment by av1ator** [comment]
rspamd-1.5.5-3.x86_64 centos-6 - the same error

**Comment by av1ator** [comment]
rspamd-1.5.6-3.x86_64 centos-6 - the same error

**Comment by av1ator** [comment]
rspamd-1.5.8-4.x86_64 cetnos-6 - the same error

**Comment by fatalbanana** [comment]
Seems to have been fixed at some point (that is indeed matter of things being out of sync).
