### ISSUE TITLE
Ratelimit module action

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1539]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Rspamd version:
1.5.3

### Additional information:
Can we somehow have a "special" action for ratelimit module like for graylist? to see in console messages that was rejected due to ratelimit plugin? Now they all goes as "Reject" like as an usual spam.

**Comment by fatalbanana** [comment]
Ratelimitted mail gets `soft reject` which is distinct from `reject`. It should also be apparent from logs whether ratelimit module or something else soft-rejected the mail:

Logs:
`2017-03-20 12:07:21 #3966(normal) <17c968>; lua; ratelimit.lua:294: ratelimit "user" exceeded: 2.801322 elements with 2 limit`

Message passed to rmilter/rspamc/message sender:
`Message - smtp_message: Ratelimit \"user\" exceeded`

**Comment by madorin** [comment]
@fatalbanana, then probably better to have distinct default action for greylist module, that now is "soft reject" too. OK, got it, thanks.

**Comment by fatalbanana** [comment]
`soft reject` (temporary error) is the *action* to be taken for a message. It doesn't make sense to have a distinct action for everything that uses this. It should be clear what sets an action.

**Comment by madorin** [comment]
@fatalbanana, rmilter rejects messages with "greylist" action, now after using rspamd modules, in reports/charts I don't have a way to distinct greylisted & ratelimited messages. only "soft reject" action.

**Comment by fatalbanana** [comment]
Rmilter greylists messages with `greylist` action; rspamd uses `soft reject` when it is handling greylisting to signal to Rmilter that a message should be deferred (and `greylist` action is never seen, even if defined in metric).

Greylist module always add a `GREYLIST` symbol so it should be quite clear when it's at work. Similarly to `ratelimit` it sets `smtp_message`, which is shown to the message sender.

It is not intended that all information can be read from the pie chart.

**Comment by madorin** [comment]
@fatalbanana, then we have an inconsistency here. Greylist have action, but Ratelimit does not have.
Basically now "soft reject" in rspamd can be invoked by 2 cases: ratelimit and greylist (probably spam), any other?
So it should be useful to distinct them in UI, if not by "Action" then by another extra field.
Temporarily I changed the greylist action in my config and it works nice, just don't know how long it will.

**Comment by vstakhov** [comment]
The problem is caused by legacy compatibility. Many Rmilter + Rspamd users still use greylisting in Rmilter. To distinguish from that situation, Rspamd has to use a different action name for own greylisting. Unfortunately, it is very bad for WebUI and configuration. In theory, we can do something about WebUI.

**Comment by vstakhov** [comment]
That should be done now.

**Comment by madorin** [comment]
Thanks, Vsevolod! Waiting for release build ;)
