### ISSUE TITLE
"spam class is missing" after upgrade to 1.3

### ISSUE THREAD

**Issue by abustany** [vstakhov/rspamd#1541]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rspamd-1.5.3-2.x86_64

### Operation system, CPU, memory and environment:
CentOS 7, x86_64

### Description (Please provide a descriptive summary of the issue):
Manual learning of spam messages seems to be broken since I upgraded to 1.3. I have a shell script scanning the Spam folder of my users, and running on all old enough messages

```
rspamc learn_spam $file
```

I now get in my logs

```
mars 20 18:32:27 pizzabox rspamd[5575]: (controller) <b6fd80>; task; rspamd_message_parse: loaded message; id: <20170320115941.834EFF79E87B53@ct.co.cr>; queue-id: <undef>; size: 28
47; checksum: <e74fc4d964b3568e7a0ec8097e66a78b>
mars 20 18:32:27 pizzabox rspamd[5575]: (controller) <b6fd80>; task; rspamd_stat_classifiers_process: skip statistics as SPAM class is missing
mars 20 18:32:27 pizzabox rspamd[5575]: (controller) <b6fd80>; task; rspamd_task_process: learn error: Unknown statistics error
```

I'm using the sqlite backend, and learning used to work before, since my .sqlite files have some content in them. Is there some schema migration that I ought to have done between versions 1.2 and 1.3?

**Comment by fatalbanana** [comment]
Maybe you have some error about statistics during startup?

Restart might solve it.

**Comment by abustany** [comment]
Hmm a restart solved it yes... I'm closing this ticket for now then, and will reopen if the issue appears again. Thanks for the quick reply!
