### ISSUE TITLE
split `rspamc` into separate package or provide way to disable `rspamd`

### ISSUE THREAD

**Issue by 4nd3r** [vstakhov/rspamd#1545]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue): 

i'm running rspamd in central machine, which is separate from incoming/outgoing smtpd servers and imap servers. there's no point installing and/or running `rspamd` daemon in imap servers because i only need `rspamc` there (for learning with dovecot antispam). please provide way to disable `rspamd` (even after package upgrade, `systemctl disable` etc doesn't forbid manual start) or package `rspamc` into separate package. former is probably easier.

**Comment by fatalbanana** [comment]
Using `curl` might be an option: https://rspamd.com/doc/faq.html#can-i-check-a-message-with-rspamd-without-rspamc

**Comment by 4nd3r** [comment]
so basically something like this:

```
  antispam_mail_sendmail      = /usr/bin/curl
  antispam_mail_sendmail_args = --data-binary;@-
  antispam_mail_spam          = http://rspamd.example.com:11333/learnspam
  antispam_mail_notspam       = http://rspamd.example.com:11333/learnham
```
is 11333 correct port to send and not 11334?

**Comment by fatalbanana** [comment]
These endpoints belong to the controller which listens on 11334, so you should use that.

**Comment by 4nd3r** [comment]
looks like following works just fine:
```
  antispam_mail_sendmail      = /usr/bin/curl
  antispam_mail_sendmail_args = --data-binary;@-
  antispam_mail_spam          = http://rspamd.example.com:11334/learnspam
  antispam_mail_notspam       = http://rspamd.example.com:11334/learnham
```

so this basically solves my issue. thanks for your time!
