### ISSUE TITLE
Multiple actions

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1547]
### Classification:

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Description:
Currently we define actions like:
```
actions {
	reject = 15;
	add_header = 6;
	greylist = 4;
};
```
This means that messages with less spam probability are first greylisted and later accepted. Messages with more spam probability, scored between 6-15 are accepted immediately and marked as spam. 

I think it will be a good idea to greylist first messages scored 6-15 (as in first case) and later to add_header or rewrite_subject, if "bad" MTA trying to send them again later.

**Comment by fatalbanana** [comment]
That applies merely to rmilter. In rspamd (greylisting module) all messages are greylisted unless:

- The message met `reject` score
- The IP/hostname of the sender is whitelisted using `whitelisted_ip`/`whitelist_domains_url`
- Score is below `greylist_min_score` (if set - default unset)

**Comment by madorin** [comment]
Oki, thanks @fatalbanana. Question closed ;)
