### ISSUE TITLE
Feature request. LUA API for attachments

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rspamd#1551]
Hi!

Do you plan to add some functions to work with attachments? For example, it will be very helpfull to do some actions with attachments in rules. For example, get hash for files attached to message or get names of files (or size and other statistics).

**Comment by fatalbanana** [comment]
Have you looked at [message parts API](https://rspamd.com/doc/lua/mimepart.html)?

**Comment by vstakhov** [comment]
https://rspamd.com/doc/lua/mimepart.html#m8fa7a more specifically.

**Comment by damned-trooper** [comment]
Ooops. I searched in task module. I'm sorry.
