### ISSUE TITLE
Manual page on composites is wrong (or: composite parsing is wrong)

### ISSUE THREAD

**Issue by JKingweb** [vstakhov/rspamd#1557]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version: 
1.5.3

### Operation system, CPU, memory and environment: 
Ubuntu 16.04, x64

### Description (Please provide a descriptive summary of the issue):
The manual page on composites (https://www.rspamd.com/doc/configuration/composites.html) appears to not reflect how composites actually work.  First, it lists two different syntaxes:

``` 
composite {
 name = "DMARC_TRIFECTA";
 expression = "R_SPF_ALLOW & R_DKIM_ALLOW & (DMARC_POLICY_ALLOW | DMARC_POLICY_ALLOW_WITH_FAILURES)";
 ...
}
```

``` 
composite "DMARC_TRIFECTA" {
 expression = "R_SPF_ALLOW & R_DKIM_ALLOW & (DMARC_POLICY_ALLOW | DMARC_POLICY_ALLOW_WITH_FAILURES)";
 ...
}
```

Neither works as one would expect in Rspamd 1.5: the first yields a symbol called "composite" rather than "DMARC_TRIFECTA", and the second results in a parse error:

```
rspamd[27375]: (main) <5k1qrc>; cfg; rspamd_config_read: rcl parse error: composite must have an expression defined
```

Given that the second form worked in Rspamd 1.4 and no mention of syntax changes was made in the release notes for 1.5, this may alternatively be a regression.

**Comment by fatalbanana** [comment]
Where are you adding these? There was a change; the old syntax should still work but not if it's misplaced. See notes about metrics here: https://rspamd.com/doc/migration.html#migrating-to-rspamd-15

**Comment by fatalbanana** [comment]
The [documentation](https://rspamd.com/doc/configuration/composites.html) has been updated.
