### ISSUE TITLE
[WebUI] `No results` in History search when any characters after _ or @

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#1561]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
`1.5.4-git.56b2c0c`

### Operation system, CPU, memory and environment:
`FreeBSD 10.3-RELEASE-p11 amd64 GENERIC/Mozilla Firefox 49.0`

### Description (Please provide a descriptive summary of the issue):
WebUI history search returns `No results` if search string looks like `DATE_IN_PAST`.
Though `DATE_` gives results. The same thing with `@mail.ru` - no results. `@mail` gives results.

### Expected results:
Having results when search string contains any printable characters.

### Actual results:
Returning `No results` when any characters after _ or @ or . (dot) is used in search

**Comment by vstakhov** [comment]
I think it is footables bug. No ideas how to fix. Please report upstream.

**Comment by dehnli** [comment]
Have the answer from [upstream](https://github.com/fooplugins/FooTable/issues/633#issuecomment-290347137):

> Please try setting the filtering components [connectors](http://fooplugins.github.io/FooTable/docs/components/filtering.html#connectors) option to false.

Where should it be done exactly?
