### ISSUE TITLE
[WebUI] History is empty -> TypeError

### ISSUE THREAD

**Issue by dimejo** [vstakhov/rspamd#1564]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.4

### Operation system, CPU, memory and environment:
Windows 10 Pro 64bit, Firefox 52.0.2 64bit

### Description (Please provide a descriptive summary of the issue):
The History tab is completly empty and doesn't show any entries. The throughput graph shows that rspamd is working correctly.

### Additional information:
The developer console of Firefox shows the following error:
```
TypeError: item.score is undefined
    preprocess_item                                             /js/app/history.js:50:13
    process_history_legacy/<                                    /js/app/history.js:117:13
    .each                                                       /js/lib/jquery-3.1.1.min.js:2:2863
    process_history_legacy                                      /js/app/history.js:115:9
    process_history_data                                        /js/app/history.js:356:16
    interface.getHistory/<                                      /js/app/history.js:434:33
    interface.queryNeighbours/<.success/</req_params.success    /js/app/rspamd.js:403:41
    r.Callbacks/i                                               /js/lib/jquery-3.1.1.min.js:2:27978
    r.Callbacks/j.fireWith                                      /js/lib/jquery-3.1.1.min.js:2:28749
    A                                                           /js/lib/jquery-3.1.1.min.js:4:14201
    .send/c/<                                                   /js/lib/jquery-3.1.1.min.js:4:16491
```

**Comment by madorin** [comment]
History now show more fields and probably it use another storage. On my instance it also was reset. New entries appears in the log.

**Comment by fatalbanana** [comment]
@madorin webui is currently broken for legacy history (`history_file`).

**Comment by dimejo** [comment]
I guess the password prevented rspamd from automagically switching to the Redis server. I've now configured it and history is displayed as it should.

Is the legacy history supposed to still work, or should I close the issue?

**Comment by fatalbanana** [comment]
Legacy history is supposed to still work indeed (just webui part is broken for now)- you could leave this open.

**Comment by dimejo** [comment]
Legacy history seems to be working fine with rspamd-1.5.5. Closing the issue.
