### ISSUE TITLE
Greylisting error message

### ISSUE THREAD

**Issue by athanp** [vstakhov/rspamd#1567]
This error appeared in rspamd log since last 1.5.3 update (mostly default config)

`#34509(normal) <d282f7>; task; lua_task_set_flag: unknown flag requested: greylisted`

What this means and how can be avoided?
BTW I don't use greylist module but cannot figure how to disable it

**Comment by fatalbanana** [comment]
Hi,

That's a bug - I've pushed a patch.

You can set `enabled = false;` in `local.d/greylist.conf` to disable greylist module.
