### ISSUE TITLE
Generic symbols for RBL & SURBL

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1572]
### Classification:

* [x] Feature

### Description:

Hello,
Can we have some generic symbols for RBL & SURBL groups, like RBL_LISTED that fire if any of rbls is true?
Thanks!

**Comment by fatalbanana** [comment]
Is there some particular reason you may want that?

You could use a composite like the following:

```
RBL_LISTED {
  expression = "g:rbl";
}
```

Problems are:
Whitelist symbols are also in "rbl" group- these could be moved to a "rwl" group. 
Whitelist composites remove original symbols - they could just remove weights instead.

**Comment by madorin** [comment]
@fatalbanana , oki, found in docs composites.
i'll try to write a composite symbol like RAMBLER_URIBL | ABUSE_SURB | ... just it may be a bit longer

**Comment by fatalbanana** [comment]
You can use groups in composites- eg: "g:rbl", "g:surbl". However this will unlikely work as desired for RBLs for the reasons mentioned.

**Comment by madorin** [comment]
> Is there some particular reason you may want that?

I think this way simplify rules, for ex add an extra weight +2 if message is listed in some rbl list, rather than increase weight for each rbl list particularly.
oki, i'll try with groups excluding white&neutral symbols, thanks, question closed ;)
