### ISSUE TITLE
Authenticated symbol or outbound metrics

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1573]
### Classification:

* [x] Question

### Description:

How to track outbound mail a bit different in terms of less restrictive? Is AUTHENTICATED symbol a good idea/feature to have? or how to define a separate metric for authenticated outbound mail?

**Comment by fatalbanana** [comment]
[Settings module](https://rspamd.com/doc/configuration/settings.html) can disable/rescore rules/rescore metric/add a symbol for authenticated users.

**Comment by madorin** [comment]
@fatalbanana, where/file to put settings {} block? did not found in docs

**Comment by fatalbanana** [comment]
You could use either of rspamd.conf.local or rspamd.conf.override - see [here](https://rspamd.com/doc/quickstart.html#configuring-rspamd).

**Comment by madorin** [comment]
@fatalbanana thanks! it seems to work ;)

Just saw that it still checks for "dkim" and add `DKIM_SIGNED(0)` symbol even I added it in groups_disabled, like:

```
authenticated {
        priority = high;
        authenticated = yes;
        apply "default" {
            groups_disabled = ["rbl", "surbl", "spf", "dkim", "dmarc"];
        }
    }
```

Rbl, other checks are ignored properly. Is it an issue?

**Comment by madorin** [comment]
or this is done by "headers" group, on parsing, without any other checks

**Comment by fatalbanana** [comment]
`groups_disabled` works on metric group; I suppose you've not added `DKIM_SIGNED` to metric in `dkim` group.

**Comment by madorin** [comment]
yes, just checked, DKIM_SIGNED is added by dkim signing module, not by dkim checking, so it is needed for outgoing emails, thanks!
