### ISSUE TITLE
Stopper with custom reject message

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1579]
### Classification:

* [x] Feature

### Description:

It will be a good idea to have the ability to directly reject the message if some symbol match, with a custom reject message, something like:

```
MIME_BAD_ATTACHMENT {
    reject = true;
    reject_message = "Bad attachment found";
}
```
What do you think? At least big players return a more explicit message, rather than "Spam message".

**Comment by fatalbanana** [comment]
[Force actions module](https://rspamd.com/doc/modules/force_actions.html) supports setting `message`. There is no support for setting actions in mime types module.

**Comment by madorin** [comment]
Ouch, sorry :) much better than my idea, thanks!
