### ISSUE TITLE
There is no Xenial 64 bit package for new rspamd 1.5.5-2 version in the Ubuntu repository

### ISSUE THREAD

**Issue by albsol** [vstakhov/rspamd#1585]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.5-2
### Operation system, CPU, memory and environment:
Ubuntu 16.04 (Xenial) 64 bits

### Description (Please provide a descriptive summary of the issue):
No exactly a bug, just there is no Xenial 64 bit package for new rspamd_1.5.5-2 version in the Debian/Ubuntu repository.

### Steps to reproduce:
Simply browsing in https://rspamd.com/apt-stable/pool/main/r/rspamd/

**Comment by vstakhov** [comment]
I have created packages for xenial and Fedora distros with the recent hotfixes. Thank you for your report.
