### ISSUE TITLE
rmilter DKIM Signature failing

### ISSUE THREAD

**Issue by dsimunic** [vstakhov/rspamd#1592]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.55

### Operation system, CPU, memory and environment:

Ubunty xenial, 512MB ram

### Description (Please provide a descriptive summary of the issue):

rmilter dkim signature fails validation. Using the same private key, signature from dkimproxy passes.

```
Authentication-Results: mx.google.com;
       dkim=pass header.i=@wa-research.ch;
       dkim=fail header.i=@wa-research.ch;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=wa-research.ch
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=wa-research.ch; h=from
	:content-type:content-transfer-encoding:mime-version:subject
	:message-id:date:to; s=default.private; bh=N0cgFtt5AN8bwFM1QW7h5
	GOgR0M=; b=qfMpHOD4q+za+nHF8KPjZJtPA4JSc4aIpWq8rtNBIuGIx+cH6ImV2
	35qMyKQfY40LRRh5sE1/c9iIhApoa9syYlRabh5AnfIi5IE9PxCMakfdfVupNgmt
	i2P79bcBPpVneJO+TeGLJjGTh9d9PLFN/ZYC4mNjnE0HjkuTAk47+w=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=wa-research.ch; s=default.private; t=1492118466; bh=N0cgFtt5AN8bwFM1QW7h5GOgR0M=; h=From:Content-Type:Content-Transfer-Encoding:Mime-Version:Subject:Message-Id:Date:To; b=v97QeK8Z2THr29cd/0/pQXlb2uQT6JiWtadGWhjCsp5nOT9hQfayIVzt3+WUAa2qpXxwL2JywoGm/W0jC0AaGnMhzQ445MV4q4ESBIYKhMjo3delJUeg8Ivtjl0IwhP7YiCafA6gjqp0bj/5mv+urVkHBcZPGSmgAEzohpVxFH0=
```

Note the first signature from dkimproxy passes, and the second  one from rmilter fails.

dkimvalidator.com says:

```
Validating Signature

result = fail
Details: OpenSSL error: data too large for modulus
```

Additionally, the rmilter signature is not nicely folded (even though it's within the permissible header length, it's not aesthetically pleasing).

Both signatures are using exact same private key.

### Expected results:

Valid dkim signature, correctly formatted.

### Actual results:

Invalid dkim signature, aesthetically displeasing header.

### Configuration:

```
cat rmilter.conf.local

dkim {
    enable = yes;
    sign_alg = sha1;
    domain {
	key = /var/lib/dkim/wa-research.ch.dkim.key;
	domain = "wa-research.ch";
	selector = "default.private";
    };
    header_canon = relaxed;
    body_canon = relaxed;
}
```

**Comment by fatalbanana** [comment]
Try [dkim signing module](https://www.rspamd.com/doc/modules/dkim_signing.html) (or dkim module's [sign_condition](https://rspamd.com/doc/modules/dkim.html#dkim-signatures)) - issues with these features in [rmilter](https://github.com/vstakhov/rmilter/) are unlikely to get attention.

**Comment by dsimunic** [comment]
Tried that as well without success. Will close this one and open another for dkim_signing module.
