### ISSUE TITLE
rspamd skips DKIM signature

### ISSUE THREAD

**Issue by dsimunic** [vstakhov/rspamd#1593]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.55

### Operation system, CPU, memory and environment:

Ubuntu Xenial

### Description (Please provide a descriptive summary of the issue):

rspamd is configured to sign authenticated users' messages with DKIM but it does not. rmilter correctly passes the message for signing to rspamd, but the latter skips the signing step:

    rspamd[16403]: (normal) <04317d>; task; dkim_symbol_callback: skip DKIM checks for local networks and authorized users

### Steps to reproduce:

Follow instructions on setting up [dkim_signing_module](https://www.rspamd.com/doc/modules/dkim_signing.html).

### Expected results:

Signed message.

### Actual results:

The message is never signed.

### Debugging information:

```
rmilter[17418]: <42566baeb4>; mlfi_envfrom: client is authenticated as: ...
rmilter[17418]: <42566baeb4>; mlfi_envfrom: turn off strict checks for authenticated sender: ...
rmilter[17418]: <42566baeb4>; mlfi_eom: tempfile=/tmp/msg.XXiY4g3K, size=808
rspamd[16403]: (normal) <04317d>; task; accept_socket: accepted connection from 127.0.0.1 port 36208, task ptr: 00007FDC34B42800
rmilter[17418]: <42566baeb4>; spamdscan: start scanning message on localhost
rspamd[16403]: (normal) <04317d>; task; rspamd_message_parse: loaded message; id: <4536E953-2B0B-4CBD-95FB-4372622660AA@wa-research.ch>; queue-id: <77CB4A02D2>; size: 808; checksum: <438f1942aa24bac583b2238d2ce12202>
rspamd[16403]: (normal) <04317d>; task; dkim_symbol_callback: skip DKIM checks for local networks and authorized users
rspamd[16403]: (normal) <04317d>; task; rspamd_stat_classifiers_process: skip statistics as SPAM class is missing
rspamd[16403]: (normal) <04317d>; task; rspamd_task_write_log: id: <4536E953-2B0B-4CBD-95FB-4372622660AA@wa-research.ch>, qid: <77CB4A02D2>, ip: 2.14.228.13, user: ..., from: ..., (default: F (no action): [0.00/15.00] []), len: 808, time: 4.000ms real, 1.823ms virtual, dns req: 0, digest: <438f1942aa24bac583b2238d2ce12202>, rcpts: <5YDT4V2B9YEIRo@dkimvalidator.com,check-auth@verifier.port25.com>
rspamd[16403]: (normal) <04317d>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 161 regexps total, 0 regexps cached, 0B bytes scanned using pcre, 0B bytes scanned total
rmilter[17418]: <42566baeb4>; spamdscan: finish scanning message on localhost
rmilter[17418]: <42566baeb4>; spamdscan: scan, time: 0.007, server: localhost, metric: default: [0.000 / 15.000], symbols: no symbols
rmilter[17418]: <42566baeb4>; msg done: queue_id: <77CB4A02D2>; message id: <4536E953-2B0B-4CBD-95FB-4372622660AA@wa-research.ch>; ...; spam scan: dkim sign only, whitelisted; virus scan: skipped, no av servers; dkim: not signed, disabled
```

### Configuration:

```
cat rmilter.conf.local

dkim {
    rspamd_sign = yes;
    enable = no;
}
```
```

*** Section dkim_signing ***
allow_envfrom_empty = true;
allow_hdrfrom_mismatch = false;
allow_hdrfrom_multiple = false;
allow_username_mismatch = false;
auth_only = true;
selector = "dkim";
sign_local = true;
symbol = "DKIM_SIGNED";
try_fallback = true;
use_domain = "header";
use_esld = false;
use_redis = false;
hash_key = "DKIM_KEYS";
domain {
    wa-research.ch {
        key = "/var/lib/dkim/wa-research.ch.dkim.key";
        selector = "default.private";
    }
}

*** End of section dkim_signing ***
```

```
cat local.d/logging.inc

debug_modules = ["dkim", "dkim_signing"]
```

**Comment by fatalbanana** [comment]
Log message shown is unrelated to dkim_signing module, can you check full logs? (maybe [rspamadm grep](https://rspamd.com/doc/rspamadm.html#rspamadm-grep) helps). I see no symbols- do you use [settings](https://rspamd.com/doc/configuration/settings.html)?- full log should give this away.

**Comment by dsimunic** [comment]
Those are the only log lines produced on send. 

I've installed rmilter/rspamd on xenial as per instructions on the [quickstart page](https://rspamd.com/doc/quickstart.html) and then configured dkim signing per the [dkim_signing module page](https://rspamd.com/doc/modules/dkim_signing.html).

Neither of these pages mentioned anyting about settings. Is there a separate step needed? 

Grepped the log per your advice, the only mentions of `dkim_signing` are for incoming dkim-signed messages:

```
rspamd[16403]: (normal) <0745f1>; dkim; rspamd_dkim_signature_update: initial update hash with signature part: dkim-signature:v=1; a=rsa-sha1; c=relaxed/relaxed; s=verifier201208; d=port25.com; h=Date:From:To:Subject:Message-Id:In-Reply-To; i=auth-results@verifier.port25.com; bh=/BJOnWGZ7CNr8ZCDMr1ael85SUo=; b=
rspamd[16403]: (normal) <0745f1>; dkim_signing; dkim_signing.lua:64: ignoring unauthenticated mail
```

For outgoing messages, the only log lines generated are what's in the parent post.

**Comment by dsimunic** [comment]
D'oh. Was missing 'strict_auth = true' in rmilter.conf.

**Comment by fpoulain** [comment]
I have been facing similar issue. I share it here.

It is only after activating verbose logging via `local.d/logging.inc`
```
debug_modules = ["dkim", "dkim_signing"];
```
that I seen in logs:
```
dkim_signing; lua_dkim_tools.lua:422: couldnt find domain in username
```
The involved code is
```lua
  if auser and not settings.allow_username_mismatch then
    if not udom then
      lua_util.debugm(N, task, 'couldnt find domain in username')
      return false,{}
    end
    if settings.use_esld then
      udom = rspamd_util.get_tld(udom)
    end
    if udom ~= dkim_domain then
      lua_util.debugm(N, task, 'user domain mismatch')
      return false,{}
    end
  end
```
So the problem was finally the use of domainless users (on a small long lived mail machine), which requires `allow_username_mismatch = true` in rspamd configuration.
