### ISSUE TITLE
dkim_signing Specify Headers to Sign

### ISSUE THREAD

**Issue by jlundstrom** [vstakhov/rspamd#1595]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.5
### Operation system, CPU, memory and environment:
N/A
### Description (Please provide a descriptive summary of the issue):
Some mail relay services will rewrite portions of an email (Message-ID, Date, Return-Path, Bouces-To) before sending the message on wards. An example of this is Amazon's AWS Simple Email Service linked below.

I would like to request the option to specify the headers used to create the signatures, and possibly have different criteria for each domain.

### Compile errors (if any):
N/A
### Steps to reproduce:
N/A
### Expected results:
`DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=example.com; s=dkim; t=1492139956; h=from:subject:to:mime-version:content-type; bh=xxxxxxxxxx`

### Actual results:
`DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=example.com; s=dkim; t=1492139956; h=from:subject:date:message-id:to:mime-version:content-type; bh=xxxxxxxxxx`

### Configuration:
```
dkim_signing {
    allow_envfrom_empty = true;
    allow_hdrfrom_mismatch = false;
    allow_hdrfrom_multiple = false;
    allow_username_mismatch = false;
    auth_only = true;
    selector = "dkim";
    sign_local = true;
    symbol = "DKIM_SIGNED";
    try_fallback = true;
    use_domain = "header";
    use_esld = true;
    use_redis = false;
    hash_key = "DKIM_KEYS";
}
```

### Additional information:
[Manual DKIM for AWS SES](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/manual-dkim.html)

**Comment by vstakhov** [comment]
I have added an option to `dkim` module (NOT `dkim_signing` but it will use the same option) called `sign_headers`. This option should contain `:` separated list of headers where `from` header is mandatory as per RFC. The default headers list is the following (according to RFC recommendations): 

```
from:sender:reply-to:subject:date:message-id:
to:cc:mime-version:content-type:content-transfer-encoding:
resent-to:resent-cc:resent-from:resent-sender:resent-message-id:
in-reply-to:references:list-id:list-owner:list-unsubscribe:
list-subscribe:list-post
```

Please mention that you **cannot** include newlines to that string. Perhaps, I'll fix that soon.

**Comment by vstakhov** [comment]
Oh I was not right: actually you already can include newlines/spaces in this string.

**Comment by jlundstrom** [comment]
I just tested this with the experimental repo, and it's exactly what I needed.
