### ISSUE TITLE
Packages missing for 1.5.6?

### ISSUE THREAD

**Issue by setiseta** [vstakhov/rspamd#1603]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.6

### Operation system, CPU, memory and environment:
Ubuntu 16.04 

### Description (Please provide a descriptive summary of the issue):
There is release entry in githb for 1.5.6 but i cant find any packages.
Am I missing something?

**Comment by vstakhov** [comment]
They should be ready now.
