### ISSUE TITLE
[WebUI] history: filter for 'add_header' not working

### ISSUE THREAD

**Issue by dimejo** [vstakhov/rspamd#1604]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.5.6

### Operation system, CPU, memory and environment:
Win10 Pro 64bit with Firefox 53.0 and Chrome 58.0.3029.81

### Description (Please provide a descriptive summary of the issue):
The 'add_header' filter in the top left corner of the history site shows no results even though the unfilterd list shows messages with a 'add header' tag.

### Additional information:
Looks like the name for the filter and the tag in the message list don't match (missing underscore). If I remove the underscore from the select box (making it 'add header') in the developer console the results correctly show up.

**Comment by moisseev** [comment]
There is another filtering issue: the `reject` filter matches both `reject` and `soft reject` actions.

**Comment by dimejo** [comment]
@fatalbanana 
This fixes the original issue for me

@moisseev 
> There is another filtering issue: the reject filter matches both reject and soft reject actions.

Maybe rename those actions to something like 'temporary reject' and 'permanent reject'?

**Comment by moisseev** [comment]
It's possible to use `reject -soft` query, but it looks weird in the drop-down list.
```diff
--- history.js.orig     2017-04-23 19:30:01.239405000 +0300
+++ history.js  2017-04-23 19:30:23.355081000 +0300
@@ -368,7 +368,7 @@
         FooTable.actionFilter = FooTable.Filtering.extend({
         construct : function(instance) {
             this._super(instance);
-            this.actions = [ 'reject', 'add header', 'greylist',
+            this.actions = [ 'reject -soft', 'add header', 'greylist',
                     'no action', 'soft reject' ];
             this.def = 'Any action';
             this.$action = null;
```
