### ISSUE TITLE
Enable to configure rspamd-variables in startup command-line

### ISSUE THREAD

**Issue by mpizzoli** [vstakhov/rspamd#1609]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Rspamd version:
1.5.6

### Operation system, CPU, memory and environment:
RHEL7

### Description (Please provide a descriptive summary of the issue):
Opportunity to have more instances of rspamd active at the same time, running with different configurations. As per email answer from Andrew Lewis: https://groups.google.com/forum/#!topic/rspamd/5gbwdfqbzjw

I thought I could just run rspamd providing on the starting command line the value for all variables:
https://rspamd.com/doc/configuration/#rspamd-variables 

but it seems not a viable solution, yet. In order to alter those variable I need to rebuild from source.
My wish is to use the original RPMs for EL7.

### Compile errors (if any):
N/A

### Steps to reproduce:
With the el7 rpm build, try to make rspamd to start with a configuration DIR different than /etc/rspamd. 

### Expected results:
Getting a complete working rspamd instance working with a specified configuration dir

### Actual results:
The configuration is always read from /etc/rspamd

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
Anything

### Additional information:
My ideal scenario is one in which I could specify in the starting command line all "DIR" variables, also to specify all of the following:
- /etc/rspamd/local.d
- /etc/rspamd/override.d

So I could even reference the "original" etc dir (normally updated by the official RPM) and still keeping different "local/override" dir specific for my multi-instances. That would be really useful for my use-case.

Thanks in advance

**Comment by fatalbanana** [comment]
You can indeed just run something `rspamd -c /etc/... CONFDIR=/etc`.

It's not a recommendable way to use rspamd. [Settings module](https://rspamd.com/doc/configuration/settings.html) should obviate need for multiple instances and test instances would be better running on dedicated machines/VMs.

**Comment by mpizzoli** [comment]
@fatalbanana: Your answer indeed solves my problem. Thank you very much. Closing this ticket
