### ISSUE TITLE
EL7 RPM Build not including luajit support

### ISSUE THREAD

**Issue by mpizzoli** [vstakhov/rspamd#1616]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.7

### Operation system, CPU, memory and environment:
EL7 x86_64
https://rspamd.com/rpm-stable/centos-7/x86_64/rspamd-1.5.7-3.x86_64.rpm

### Description (Please provide a descriptive summary of the issue):
The build does not support luajit.
I see in the following spec file:
https://rspamd.com/rpm-stable/SPECS/rspamd.spec
<snippet>
%if 0%{?fedora_version} >= 22 || 0%{?suse_version} >= 1320
		-DENABLE_LUAJIT=ON \
%else
		-DENABLE_LUAJIT=OFF \
</snippet>
So, on EL7 platform it is not considered the luajit integration.

### Compile errors (if any):
N/A

### Steps to reproduce:
Just install the rspamd RPM, the luajit RPM and then try to make rspamd executing luajit

### Expected results:
Loading and executing luajit on platforms that support it

### Actual results:
Only (normal)lua is executed

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
N/A

### Additional information:
It would be useful to have a configuration parameter permitting to specify where to load the lua interpreter at startup time

**Comment by dimejo** [comment]
Guess that's because `luajit` is not part of the default RHEL/CentOS repository. It is only available via EPEL.

**Comment by fatalbanana** [comment]
CentOS packages already depend on EPEL so that's no issue. I suspect luajit was not available in EPEL when CentOS packages were initially produced.

**Comment by vstakhov** [comment]
It is indeed in epel:

Installed Packages
luajit.x86_64                                                                                          2.0.4-3.el7                                                                                        @epel

Plain Lua is in the base CentOS repo.

**Comment by vstakhov** [comment]
Now packages are built with luajit for CentOS 7.
