### ISSUE TITLE
[documentation/question] WebUI required/tooling

### ISSUE THREAD

**Issue by strarsis** [vstakhov/rspamd#1618]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

Is WebUI required for completely controlling rspamd/rmilter? 
Can all operations also performed on the command line without the Web UI?

**Comment by fatalbanana** [comment]
WebUI does nothing for Rmilter. Everything it does do can be done with configuration files & command-line utilities. OTOH, everything that can be done this way can *not* be done via WebUI, so WebUI is actually a second-class citizen. It is not required.
