### ISSUE TITLE
Required token learn error

### ISSUE THREAD

**Issue by andypl78** [vstakhov/rspamd#1621]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.5.7-3~jessie

### Operation system, CPU, memory and environment:
Debian Jessie 8

### Configuration:

statistics.conf

> classifier {
>     tokenizer {
>         name = "osb";
>     }
>     name = "bayes";
>     min_tokens = 9;
>     backend = "redis";

### Additional information:

> learn error: contains less tokens than required for bayes classifier: 5 < 9

> learn error: <877c5fef-83d3-6fe6-9c7b-90a275e76fbf@post.pl> contains less tokens than required for bayes classifier: 8 < 9

**Comment by fatalbanana** [comment]
It seems you try to learn messages which are too short for bayes.
