### ISSUE TITLE
Chartable module penalizes license plate numbers

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#1630]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.0-git.4c2c4f0

### Description (Please provide a descriptive summary of the issue):
Chartable module penalizes digits in the middle of the word. So, lists of license plate numbers written in Cyrillic are getting high spam scores.

```
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

Е887НВ
Т123ВЕ
К400ОУ64
```

```
2017-05-10 08:55:13 #94812(normal) <63e0e6>; chartable; rspamd_chartable_process_word_utf: word Е887НВ, badness: 1.00
2017-05-10 08:55:13 #94812(normal) <63e0e6>; chartable; rspamd_chartable_process_word_utf: word Т123ВЕ, badness: 1.00
2017-05-10 08:55:13 #94812(normal) <63e0e6>; chartable; rspamd_chartable_process_word_utf: word К400ОУ64, badness: 1.00
```

**Comment by vstakhov** [comment]
How would you distinguish it from l33t replacements?

**Comment by moisseev** [comment]
I don't think it's possible. What if just decrease badness for digits?

**Comment by vstakhov** [comment]
I agree, will do.
