### ISSUE TITLE
MX Check module: automatically exclude local addresses

### ISSUE THREAD

**Issue by bax-** [vstakhov/rspamd#1632]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

The MX Check module can be referred to a map of IP addresses. 
But why not automatically exclude it from `local_addrs`?

**Comment by vstakhov** [comment]
Exclude what?

**Comment by bax-** [comment]
Sorry, I wasn't clear.

Exclude the MX Check for mails from authenticated users and local networks.
Just as DMARC, Greylist, IP Score etc. are disabled for mail from authenticated users and local networks:
https://rspamd.com/doc/tutorials/scanning_outbound.html

If MX Checks already is disabled I'm sorry. The logs don't mention it though.

**Comment by fatalbanana** [comment]
Already disabled; it's just not mentioned in docs/logs.

**Comment by bax-** [comment]
great, thanks for the clarification!
