### ISSUE TITLE
Whitelist domain that has no DKIM, SPF, or DMARC properties

### ISSUE THREAD

**Issue by whitslar** [vstakhov/rspamd#1635]
Is there a way to whitelist a domain that has no dkim, spf, or dmarc properties? I have a couple of domains that I absolutely have to let through for business reasons and the whitelist module isn't working because these domains haven't implemented any of dkim, spf, or dmarc, and I have no control over that. I feel like I'm probably just overlooking something, but is there a way to do this?

**Comment by fatalbanana** [comment]
It's possible with [multimap](https://rspamd.com/doc/modules/multimap.html).
