### ISSUE TITLE
DCC error

### ISSUE THREAD

**Issue by setiseta** [vstakhov/rspamd#1641]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.7

### Operation system, CPU, memory and environment:
Linux, Ubuntu 16.04 LTS, Intel i7

### Description (Please provide a descriptive summary of the issue):
dccifd is setup und listening on tcp port 10030.
dcc.conf is set to this port.
Log: ```(normal) <4f237b>; lua; dcc.lua:64: DCC error: IO timeout```
I can run dccif-test with success on the configured port.

### Configuration:
```
/etc/rspamd/local.d# cat dcc.conf
host = "dcc"
port = 10030
```
```
cat /var/dcc/dcc_conf
...
DCCM_ENABLE=off
...
DCCM_LOG_AT=NEVER
DCCM_REJECT_AT=MANY
...
DCCIFD_ENABLE=on
...
DCCIFD_ARGS="-SHELO -Smail_host -SSender -SList-ID -b -p *,10030,10.32.1.1-192.168.255.255"
```

### Additional information:
maybe just a config error?

**Comment by vstakhov** [comment]
Dcc is slow. You could try to increase its timeout.

**Comment by setiseta** [comment]
Thank you, I think this does the trick to me.
I have not recognized this option, cause it is no in the documentation.
It is just in the dcc.conf under modules.d
It seems to be good for now ( 5s instead of the default 2s)
