### ISSUE TITLE
Redis connection timeout is being ignored

### ISSUE THREAD

**Issue by samwwwblack** [vstakhov/rspamd#1646]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.7

### Description (Please provide a descriptive summary of the issue):
Setting a redis connection timeout config option doesn't work, and the default (1.0) is always being used.

### Steps to reproduce:
1. Add `local.d/redis.conf`, set `timeout = 30`
2. Edit `global_functions.lua` to log the `timeout` value in the `result` table
3. Restart `rspamd`
4. Send a test message

### Expected results:
`lua; global_functions.lua:179: :timeout:30`

### Actual results:
`lua; global_functions.lua:179: :timeout:1`

### Additional information:

[lualib/global_functions.lua:40](https://github.com/vstakhov/rspamd/blob/master/lualib/global_functions.lua#L40) to [:45](https://github.com/vstakhov/rspamd/blob/master/lualib/global_functions.lua#45) are at fault, as the default value is being set, then the config value is only set if there isn't already a value; changing this to

```
if options['timeout'] and not result['timeout'] then
  result['timeout'] = tonumber(options['timeout'])
elseif not result['timeout'] then
  result['timeout'] = default_timeout
end
```
fixes it, and the correct timeout is used.

**Comment by fatalbanana** [comment]
Fixed in 1.5.8+.
