### ISSUE TITLE
[New Feature] ARC support

### ISSUE THREAD

**Issue by mpizzoli** [vstakhov/rspamd#1647]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Rspamd version:
1.5.x

### Operation system, CPU, memory and environment:
N/A

### Description (Please provide a descriptive summary of the issue):
There is a new email authentication mechanism called Authenticated Received Chain (ARC). It's purpose is to solve the authentication problem (SPF and/or DKIM failing) when an email is being forwarded.
It has born when "p=reject" policy within DMARC caused issues to the senders.
The main website related to this technology is http://arc-spec.org.

### Compile errors (if any):
N/A

### Steps to reproduce:
N/A

### Expected results:
ARC headers inserted in the emails being processed.

### Actual results:
N/A

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
N/A

### Additional information:
Gmail already implemented this: http://dmarc.ietf.narkive.com/yRPOYVTA/dmarc-ietf-implementation-update

**Comment by vstakhov** [comment]
Is there any available opensource implementation of this? In theory, I planned to add this support at some point, however, some points are not completely clear for me so far.

**Comment by mpizzoli** [comment]
Yes, there is. Or at least it should be...
https://github.com/mskucherawy/OpenARC

Honestly I don't have any more implementation-specific info about it.

Maybe here you can find any other useful info: http://arc-spec.org/?page_id=79

**Comment by vstakhov** [comment]
It is now implemented in the upcoming 1.6 release.
