### ISSUE TITLE
Cannot build rspamd

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rspamd#1650]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
git master

### Operation system, CPU, memory and environment:
CentOS 7

Hi, guys. I've tried to build last version from git and this error:
```
<internal>:24:3: fsm "Dot_string" previously defined
<internal>:25:3: fsm "dot_atom_text" previously defined
<internal>:27:3: fsm "FWS" previously defined
-:1:1: <input>:1:1: parse error%s:%ld:
make[2]: *** [src/smtp_received_parser.rl.c] Error 1
make[1]: *** [src/CMakeFiles/rspamd-server.dir/all] Error 2
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.0o8cXw (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.0o8cXw (%build)
```
As, i can see, first file is empty and last dir does not exist:
```
[root@repo src]# ls -la smtp_received_parser.rl.c
-rw-r--r--. 1 root root 0 May 26 12:08 smtp_received_parser.rl.c
[root@repo src]# ls -la CMakeFiles/rspamd-server.dir/ | grep all
[root@repo src]#

```

**Comment by fatalbanana** [comment]
You could try installing Ragel from source.

```
2017-05-25 12:56:23     @cebka  no more packages for centos7
2017-05-25 12:56:32     @cebka  they now have broken ragel
2017-05-25 12:56:35      *      cebka cries
2017-05-25 13:57:51     @cebka  I've fixed it so far
2017-05-25 13:57:57     @cebka  installed ragel from the sources
```

**Comment by damned-trooper** [comment]
Oh shi...
Easy motion of "make install" will transform any distro to Slackware (c)
Thank you for this workaround - i'll try to do this :)

**Comment by damned-trooper** [comment]
Yep. I've successfully built new rspamd version.
Thanks a lot!
