### ISSUE TITLE
CTYPE_MISSING_DISPOSITION matches OpenPGP/MIME encrypted messages

### ISSUE THREAD

**Issue by julienschmidt** [vstakhov/rspamd#1655]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.8

### Description (Please provide a descriptive summary of the issue):

Common OpenPGP/MIME ([RFC 3156](https://tools.ietf.org/html/rfc3156)) implementations use the following format for encrypted messages:
```
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----

<encrypted message>
-----END PGP MESSAGE-----
```

Unfortunately this also matches the CTYPE_MISSING_DISPOSITION rule and increases the spam score by 4 in the default config.

### Expected results:

The rule should handle OpenPGP/MIME messages as a special case, e.g. by also looking for `Content-Description: OpenPGP encrypted message` and/or `Content-Disposition: inline; filename="encrypted.asc"`.

### Actual results:

The rule matches and the spam score is increased by 4 in the default config, causing all OpenPGP/MIME encrypted messages of unknown senders to be greylisted.

**Comment by mxmehl** [comment]
The encrypted mails sent by my [email client](https://github.com/astroidmail/astroid) do also have rspamd hits with the same rule and score. Their layout is compliant with RFC 3156 as far as I can tell.

Is there something you can do to avoid this false-positive, or does the client have to be fixed?

```
Content-Type: multipart/encrypted; protocol="application/pgp-encrypted";
	boundary="=-Ly0fxJLJgL1N4+ng4g/W"
X-Rspamd-Bar: ++++++
X-Rspamd-Report: MIME_GOOD(-0.2) AUTH_NA(1) FORGED_RECIPIENTS(2) ENCRYPTED_PGP(-0.5) CTYPE_MISSING_DISPOSITION(4)
X-Rspamd-Score: 6.3

--=-Ly0fxJLJgL1N4+ng4g/W
Content-Type: application/pgp-encrypted
Content-Transfer-Encoding: 7bit

Version: 1

--=-Ly0fxJLJgL1N4+ng4g/W
Content-Type: application/octet-stream
Content-Transfer-Encoding: 7bit

-----BEGIN PGP MESSAGE-----

[...]
jy9CyY93clry5B6GMPSy5XsXSmQctsazLcenNZw=
=I/pM
-----END PGP MESSAGE-----

--=-Ly0fxJLJgL1N4+ng4g/W--
```
