### ISSUE TITLE
RBL monitoring when 127.0.0.1 exists in blacklist

### ISSUE THREAD

**Issue by wheldom01** [vstakhov/rspamd#1662]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.9

### Operation system, CPU, memory and environment:
Debian Jessie

### Description (Please provide a descriptive summary of the issue):
When a rbl contains the rbl monitoring address of 127.0.0.1 you get error messages in the log:

monitored; rspamd_monitored_dns_cb: DNS reply returned 'no error' for hostkarma.junkemailfilter.com while 'no records with this name' was expected

### Compile errors (if any):
n/a

### Steps to reproduce:
Add the following to local.d/rbl.conf and restart
rbls {

    hostkarma {
        symbol = "RBL_HOSTKAMA";
        rbl = "hostkarma.junkemailfilter.com";
        returncodes {
            RBL_HOSTKAMA_WHITE = "127.0.0.1";
            RBL_HOSTKAMA_BLACK = "127.0.0.2";
            RBL_HOSTKAMA_YELLOW = "127.0.0.3";
            RBL_HOSTKAMA_BROWN = "127.0.0.4";
            RBL_HOSTKAMA_NOBLACK = "127.0.0.5";
            RBL_HOSTKAMA_QUIT = "127.0.1.1";
            RBL_HOSTKAMA_NOQUIT = "127.0.1.2";
            RBL_HOSTKAMA_MIXEDQUIT = "127.0.1.3";
        }
    }
}

### Expected results:
No error message in log

### Actual results:
monitored; rspamd_monitored_dns_cb: DNS reply returned 'no error' for hostkarma.junkemailfilter.com while 'no records with this name' was expected

### Configuration:
See above

### Additional information:
Suggest that the monitoring ip for rbls be changed from 127.0.0.1 to 127.0.1.1

**Comment by vstakhov** [comment]
This is direct violation of RBL creation policy (`127.0.0.1` MUST be excluded and `127.0.0.2` MUST exists): https://tools.ietf.org/html/rfc5782#section-5. Do **NOT** use such RBL ever. Hence, RFC violating DNSBLs will not be supported. Closing issue.

**Comment by vstakhov** [comment]
Reopen to think about possible solutions.

**Comment by wheldom01** [comment]
I use pdns as my dns server which supports lua scripting so will look at fixing the responses to the rbl queries, which may be a better solution.

**Comment by vstakhov** [comment]
Actually this should be fixed in master by two options:

* `disable_monitoring` - boolean value that disables monitoring completely
* `monitored_address` - fixed address to check for absence (`1.0.0.127` by default)

**Comment by wheldom01** [comment]
Thank you

**Comment by fatalbanana** [comment]
Should be fixed in 1.6.0+. @wheldom01 - could you confirm?

**Comment by wheldom01** [comment]
I can confirm that this issue is indeed fixed. Been running in production for serveral days now thanks.
