### ISSUE TITLE
[DKIM signing] cannot load dkim key with underscore in path

### ISSUE THREAD

**Issue by dimejo** [vstakhov/rspamd#1667]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.5.8

### Operation system, CPU, memory and environment:
CentOS Linux release 7.3.1611 (Core)

### Description (Please provide a descriptive summary of the issue):
rspamd can't find the dkim key file when I use an underscore in `path` between `$domain` and `$selector` variables.
> rspamd[23534]: (normal) <7db7a8>; task; lua_dkim_sign_handler: cannot load dkim key /etc/rspamd/dkim/dkim_domain_m201706.key: cannot map private key /etc/rspamd/dkim/dkim_domain_m201706.key: No such file or directory

Judging by this log entry I' assume that `$domain` is not correctly resolved for whatever reason.

### Steps to reproduce:
Use `$domain_$selector` within the path.

### Expected results:
Correct DKIM signing.

### Actual results:
No DKIM signing.

### Configuration:
_The domain specific section is shortened_
```
*** Section dkim_signing ***
allow_envfrom_empty = true;
allow_hdrfrom_mismatch = false;
allow_hdrfrom_multiple = false;
allow_username_mismatch = false;
auth_only = true;
selector = "m201706";
sign_local = true;
symbol = "DKIM_SIGNED";
try_fallback = true;
use_domain = "header";
use_esld = true;
use_redis = false;
key_prefix = "DKIM_KEYS";
path = "/etc/rspamd/dkim/dkim_$domain_$selector.key";
domain {
    dimejo.net {
        path = "/etc/rspamd/dkim/dkim_dimejo.net_dim201607n.key";
        selector = "dim201607n";
    }
}

*** End of section dkim_signing ***
```

### Additional information:
When using `$domain.$selector` or `$domain.$selector` instead of `$domain_$selector`, the key file is found correctly.

**Comment by fatalbanana** [comment]
Braced variables will work here: `${domain}_${selector}`

**Comment by dimejo** [comment]
Thanks, working with braced variables.
