### ISSUE TITLE
"mime_encoding.c" is can't encoding of long ISO-2022-JP character string

### ISSUE THREAD

**Issue by rtakamura** [vstakhov/rspamd#1669]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd 1.5.9

### Operation system, CPU, memory and environment:
CentOS 7.3 64bit, 16GByte Mem

### Description (Please provide a descriptive summary of the issue):

The long ISO-2022-JP character string can not be converted to UTF 8.
(Subject, From, attachement filename...etc)

When the Base64 part is divided into plural parts, the "token" in "mime_headers.c" forming it is connecting with escape code.
But continuous escape code is not good for iso-2022-jp.

ex.) "abcdefg#033(B#033$Babcdefg"

If consecutive escape codes are included,  "ucnv_toUChars" in "rspamd_mime_to_utf8_byte_array" will not work properly.

There is a routine to return if "new_charset" and "old_charset" are the same charset in "rspamd_mime_header_maybe_save_token" of "mime_headers.c"
for this reason, the iso-2022-jp escape code mutually has been connecting.

I think that will be solved by skip this routine and converting it for each part.
Otherwise, if have routine that eliminates consecutive escape codes of token, i think that avoid it.

**Comment by vstakhov** [comment]
I don't quite understand the issue. RFC demands that encoded elements must NOT be split inside of a multibyte character. In case of UTF, there is a workaround that permits to work with such an RFC violation. In case of other multibyte encodings, there are no such workarounds.

**Comment by rtakamura** [comment]
I apologize for any confusion.
Not split inside of a multibyte character.
By "folding" of Long Header Fields, as described in RFC 5322, It is processing when a part is split.

The case of MIME-Header by long ISO-2022-JP character string, it split to multi part for "folding".

ex.) 
Subject: =?ISO-2022-JP?B?GyRCJDMkbCRPRnxLXDhsJE5KODt6TnMkRyQ5JCxEOSQkSjg+TyRHGyhC?=
 =?ISO-2022-JP?B?GyRCJDkbKEI=?=

If each part is multibyte, the end of the part ends with an escape code, and next part starts with the escape code.

In "rspamd_mime_to_utf 8_byte_array", when the previous part and the next part are encoded the same
Since the parts are joined as it is, consecutive escape codes are generated as a result.
In this case, "ucnv_toUChars" does not work properly.
But, if encode each part without combining part, it works properly.

However...,  this may be a problem in the ICU.

**Comment by vstakhov** [comment]
It seems to be ICU bug but I can add a workaround to skip joining of the components for iso-2022-jp encoding. It might cause other issues but it would be better than nothing I suppose.

**Comment by rtakamura** [comment]
I am trying ver1.6.0, it is works properly.

**Comment by rtakamura** [comment]
I am trying ver1.6.0, it is works properly.
Thank you for promptly dealing the matter with care.
