### ISSUE TITLE
Can't read SMFIC_BODYEOB reply packet header

### ISSUE THREAD

**Issue by hardware** [vstakhov/rspamd#1672]
### Classification :

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility :

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version: 

Rspamd daemon version 1.6.0-git.04556d30f

### Operation system, CPU, memory and environment:

3.16.0-4-amd64 Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

### Description :

When I receive an e-mail, i always got this warning from rspamd_proxy :

```
Jun 10 23:35:38 mail postfix/cleanup[32770]: warning: milter inet:localhost:11332: can't read SMFIC_BODYEOB reply packet header: Success
```

Sometimes this error just after :

```
Jun 10 23:35:38 mail rspamd[32242]: <06bd8d>; main; rspamd_cld_handler: rspamd_proxy process 32244 terminated abnormally by signal: Segmentation fault but NOT created core file
```

And rspamd_proxy hang when i send a GTUBE test, i receive e-mail after 120s milter timeout.

### Steps to reproduce:

Receive an e-mail.

### Configuration:

Default setup.
Redis ON.
Logging to syslog mail.

#### Postfix version

```
postconf mail_version
mail_version = 2.11.3
```

#### main.cf

```
milter_protocol = 6
milter_default_action = accept
smtpd_milters = inet:localhost:11332
```

**Comment by vstakhov** [comment]
I've reproduced this issue, thank you.

**Comment by vstakhov** [comment]
It should be fixed now.

**Comment by hardware** [comment]
Thank you :)

When the changes will be pushed in experimental branch for Debian ?

And I have a question : I did not find an example that describes Postfix MTA integration with rspamd_proxy. My `main.cf` example should works as expected ?

**Comment by hardware** [comment]
Fixed with 1.6.0

Thanks.

**Comment by jrampin** [comment]
@vstakhov Hi, from time to time I also get this message. Two weeks ago it happened for both servers mx1 and mx2. Today it happened only for mx2. Both servers running RSPAMD 1.6.5. Debian 8 (Jessie).

----------
/var/log/syslog
----------
warning: milter inet:localhost:11332: can't read SMFIC_OPTNEG reply packet header: Connection timed out
warning: milter inet:localhost:11332: read error in initial handshake

**Comment by jrampin** [comment]
Just for record...

I've done 2 things: 
1) Increase the memory up to 16GB of RAM
2) Added both parameters on redis.conf file

_________________________________________
/etc/redis/redis.conf
________________________________________

maxmemory 1024mb
maxmemory-policy volatile-lru

It's been a while since I don't get that error anymore. Both servers reach up to 10GB of used memory, and then it releases memory after a while.

Hopefully it can help anyone going through this issue! :)
