### ISSUE TITLE
rspamd can't parse resolv.conf when IPv6 nameservers are configured

### ISSUE THREAD

**Issue by tobiasge** [vstakhov/rspamd#1681]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.0

### Operation system, CPU, memory and environment:
Linux 4.9.16-gentoo #1 SMP Fri Apr 7 13:56:42 CEST 2017 x86_64 Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz GenuineIntel GNU/Linux

### Description (Please provide a descriptive summary of the issue):
rdns module logs error when IPv6 nameserver are configured in resolv.conf that the file can't be parsed

### Compile errors (if any):
-

### Steps to reproduce:
Configure IPv6 nameserver in resolv.conf

### Expected results:
Successful parsing of resolv.conf

### Actual results:
2017-06-14 09:47:36 #13193(normal) <4e424f>; upstreams; rspamd_check_port_priority: cannot parse priority: :4860:4860::8888, at symbol :, error: Success
2017-06-14 09:47:36 #13193(normal) rdns; rdns_resolver_parse_resolv_conf_cb: rdns_resolver_parse_resolv_conf: cannot parse line: nameserver 2001:4860:4860::8888
2017-06-14 09:47:36 #13193(normal) dns_resolver_init: cannot parse resolv.conf and no nameservers defined, so no ways to resolve addresses

### Additional information:
cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 2001:4860:4860::8888
nameserver 8.8.4.4

**Comment by fatalbanana** [comment]
Should be fixed: https://github.com/vstakhov/rspamd/commit/639c67dbd85d566d04c87a2f6ec59fd9b5ffe54a

**Comment by tobiasge** [comment]
Thanks for the quick fix. It is working now.
