### ISSUE TITLE
Invalid filename avoids antivirus scan.

### ISSUE THREAD

**Issue by rtakamura** [vstakhov/rspamd#1682]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
ver 1.6.0

### Operation system, CPU, memory and environment:
CentOS 7.3 x64, 16GB mem

### Description (Please provide a descriptive summary of the issue):

When an attachment of an invalid file name such as the following is included,
Can not get the correct file name with "task: get_filename ()",
and, antivirus checks are also avoided.

it's a many pattern in recently received SPAM.

```
...
Date: Wed, 14 Jun 2017 16:50:20 +0900
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="9ADE6FA1B2FD4553C"

--9ADE6FA1B2FD4553C
Content-Type: text/plain;
	charset="iso-2022-jp"
Content-Transfer-Encoding: quoted-printable

--9ADE6FA1B2FD4553C
Content-Type: text/html;
	charset=3D"iso-2022-jp"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<META http-equiv=3D"content-type" content=3D"text/html; charset=3Diso-202=
2-jp">
</head>
<body>
...
</body>
</html>

--9ADE6FA1B2FD4553C
Content-Type: application/msword; name=3D"24344.doc"
Content-Transfer-Encoding: base64
Content-ID: <005501d2e52e$4f10c0c0$6df0460a@K6JY8V>

0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAACAAAAVQAAAAAA
AAAAEAAAWAAAAAEAAAD+////AAAAAFQAAAB/AAAA////////////////////////////////

....

AAAYAAAATWljcm9zb2Z0IE9mZmljZSBXb3JkAAAAQAAAAABs0jcvAAAAQAAAAAAwvuIxztIB
QAAAAADiWQ3f5NIBAwAAAAEAAAADAAAABgAAAAMAAAAmAAAAAwAAAAAAAAADAAAAJgAAAAMA
AAAAAAAAAAAAAAAAAAA=3D
--9ADE6FA1B2FD4553C--
```
There is also such a pattern.
```
---Part_9960961_68736136.5220933635989
Content-Type: application/vnd.ms-excel; name=3D"=3D?iso-2022-jp?B?GyRCSkw=
7ZhsoQjNfMjAxNzA2MTIbJEI9JEA1GyhCLnhscw=3D=3D?=3D"
Content-Transfer-Encoding: base64
Content-ID: <008901d2e525$df860a60$b464a8c0@8TPX7W>

0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAACAAAAAQAAAAAA
AAAAEAAAUwAAAAIAAAD+////AAAAAAAAAAB5AAAA////////////////////////////////
...
```
Both are malicious files, so can we detect such patterns?

**Comment by fatalbanana** [comment]
You could set `attachments_only = false;` in antivirus configuration to avoid it; it seems the parts are inline.

**Comment by rtakamura** [comment]
Hi fatalbanana.
Thank you for comments.
Yes, I also thought about that.
However, it scans all the mails, so I thought that the load would be high.

Hi vstakhov.
I appreciate for fix of code.
and confirmed that the attachement file was recognized correctly and passed to clamav.
