### ISSUE TITLE
Cannot disable proxy worker

### ISSUE THREAD

**Issue by aperum** [vstakhov/rspamd#1684]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1

### Operation system, CPU, memory and environment:
FreeBSD 11.0, amd64

### Description (Please provide a descriptive summary of the issue):

Setting count = 0 in local.d/worker-proxy.inc does not disable the proxy worker:

```
# sockstat -46l | grep 11332
nobody   rspamd-1.6 23236 7  tcp4   *:11332               *:*
...
```

This may be because the proxy config is wrapped in an extra rspamd_proxy  object:

```
# rspamadm configdump | grep -A13 -B1 rspamd_proxy
worker {
    rspamd_proxy {
        bind_socket = "*:11332";
        type = "proxy";
        milter = true;
        timeout = 120.0;
        upstream {
            local {
                default = true;
                hosts = "localhost";
            }
        }
        count = 0;
    }
}
```

### Steps to reproduce:

Put count = 0 into local.d/worker-proxy.inc and start rspamd

### Expected results:

Nothing listening on :11332

### Actual results:

There are workers listing on :11332

**Comment by moisseev** [comment]
Probably proxy worker was not spawned, but another process is listening on that port.
What does `# ps -ax | grep rspamd` show?

**Comment by aperum** [comment]
You are right, it seems to be every worker and there is actually no rspamd_proxy process:

```
# sockstat -46l | grep ":11332" | awk '{ print $3 }' | paste -sd '|' - | xargs -I%p sh -c 'ps auxww | egrep "%p"'
nobody   21561  0,0  0,0 173268  14952  -  IsJ  21:37    0:00,00 rspamd: main process (rspamd-1.6.1)
nobody   21869  0,0  0,1 374560  18492  -  SJ   21:37    0:03,69 rspamd: controller process (rspamd-1.6.1)
nobody   22117  0,0  0,1 403476  21388  -  SJ   21:37    0:02,48 rspamd: normal process (rspamd-1.6.1)
nobody   22477  0,0  0,1 403476  20472  -  SJ   21:37    0:02,43 rspamd: normal process (rspamd-1.6.1)
nobody   22790  0,0  0,1 407572  23176  -  SJ   21:37    0:02,53 rspamd: normal process (rspamd-1.6.1)
nobody   23160  0,0  0,1 403476  19668  -  SJ   21:37    0:02,19 rspamd: normal process (rspamd-1.6.1)
nobody   23236  0,0  0,0 173204  15856  -  SJ   21:37    0:00,40 rspamd: log_helper process (rspamd-1.6.1)

```

But port 11332 is only defined in the rspam_proxy section, why does the rest listen there?

```
# grep -R -B2 11332 *
rspamd.conf-
rspamd.conf-worker "rspamd_proxy" {
rspamd.conf:    bind_socket = "*:11332";
```

**Comment by vstakhov** [comment]
`count = 0` means `count = <NCPU>`.

**Comment by aperum** [comment]
Ok, then i misunderstood this quote from the [migration guide](https://rspamd.com/doc/migration.html):

> Proxy worker has been added to the default configuration and listens on all interfaces on TCP port 11332. If you don’t need it you can set count = 0 in local.d/worker-proxy.inc.

I thought that would disable the proxy process and and the listening to 11332.

I'm still not clear, why the other workers listen on 11332. But with count = 0 there is actually no proxy process spawned so everything seems as it should be and i'll close this report.

Thanks for your answers.

**Comment by fatalbanana** [comment]
Setting `enabled = false` in `local.d/worker-proxy.inc` works.
