### ISSUE TITLE
greylisting doesn't seem to work in 1.6.1

### ISSUE THREAD

**Issue by oxpa** [vstakhov/rspamd#1685]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1,  https://build.opensuse.org/package/show/home:ippolitov:branches:server:mail/rspamd
### Operation system, CPU, memory and environment:
OpenSuSe Leap 42.3, postfix MTA
### Description (Please provide a descriptive summary of the issue):
With a default configuration `local.d/greylist.conf` contains 
```
servers = "127.0.0.1:6379";
```
greylist.lua produce logs like:
```
Jun 14 23:57:22 ns rspamd[28477]: (normal) <73b2cc>; lua; greylist.lua:345: greylisted until "Wed, 14 Jun 2017 21:02:22 GMT", new record
```
But when I access redis with `redis-cli` I can't see corresponding keys:
```
127.0.0.1:6379> keys *
1) "BAYES_SPAM_keys"
2) "BAYES_SPAM"
3) "learned_ids"
4) "BAYES_HAM"
5) "BAYES_HAM_keys"
```
Additionally, despite 'default: F (greylist)' action in log, the letter is delivered via dovecot LDA.

### Expected results:
Keys for greylist module are expected to be in 'redis-cli' output.
Mail should not be delivered right away if the action is 'greylist'
### Actual results:
No greylisting keys
'Instant' message delivery

### Configuration:
Corresponding section for `rspamdadm configdump` output
```
greylist {
    whitelist_domains_url [
        "/etc/rspamd/local.d/greylist-whitelist-domains.inc",
    ]
    expire = 86400.0;
    timeout = 300.0;
    key_prefix = "rg";
    max_data_len = 10000;
    message = "Try again later";
    action = "soft reject";
    ipv4_mask = 19;
    ipv6_mask = 64;
    servers = "127.0.0.1:6379";
}
```

**Comment by fatalbanana** [comment]
Do you have `qid`s in scan logs? Is `soft reject` action set? Full log for a scan should answer both these questions, or at least `rspamd_task_write_log` line will.

**Comment by oxpa** [comment]
I'm using proxy worker as milter, if this is important (no rmilter).
I'm not sure what qid is, so please, find logs below.

I think, I don't have `soft reject` configured (metrics.conf is untouched, so only `reject`, `add_header` and `greylist` are configured)

I would really appreciate if you would explain me (possibly with a link to a doc) what does `greylist` action do if the greylisting module produce `soft_reject`.
And possibly it's worth changing doc a little as the phrase `To enable the module with default settings you need to define at least redis servers to store greylisting data:` is somehow misleading.

It looks like I should configure `soft_reject` and have a look if it will work.

Some logs:
```
Jun 14 23:57:21 ns rspamd[28477]: (rspamd_proxy) <32ad6a>; milter; rspamd_milter_process_command: got connection from 195.91.155.110:36729
Jun 14 23:57:21 ns rspamd[28477]: (normal) <73b2cc>; task; accept_socket: accepted connection from 127.0.0.1 port 53986, task ptr: 0000000001AA63B0
Jun 14 23:57:21 ns rspamd[28477]: (normal) <73b2cc>; task; rspamd_message_parse: loaded message; id: <367f95c4-256d-c18e-49fa-6d4bb05fc3af@ocslab.com>; queue-id: <undef>; size: 2272; checksum: <40964f4b38fd9b8e659c4023efafdcdd>
Jun 14 23:57:21 ns rspamd[28477]: (normal) <73b2cc>; lua; asn.lua:63: error querying dns: server fail
Jun 14 23:57:21 ns rspamd[28477]: (normal) <73b2cc>; task; fuzzy_generate_commands: <367f95c4-256d-c18e-49fa-6d4bb05fc3af@ocslab.com>, part is shorter than 1000 bytes: 560 (280 * 2.00 bytes), skip fuzzy check
Jun 14 23:57:21 ns rspamd[28477]: (normal) <73b2cc>; task; fuzzy_generate_commands: <367f95c4-256d-c18e-49fa-6d4bb05fc3af@ocslab.com>, part is shorter than 1000 bytes: 600 (300 * 2.00 bytes), skip fuzzy check
Jun 14 23:57:22 ns rspamd[28477]: (normal) <73b2cc>; lua; greylist.lua:345: greylisted until "Wed, 14 Jun 2017 21:02:22 GMT", new record
Jun 14 23:57:22 ns rspamd[28477]: (normal) <73b2cc>; task; rspamd_task_write_log: id: <367f95c4-256d-c18e-49fa-6d4bb05fc3af@ocslab.com>, ip: 195.91.155.110, from: <oxpa@ocslab.com>, (default: F (greylist): [5.54/15.00] [BAYES_SPAM(3.84){99.50%;},MISSING_MIME_VERSION(2.00){},R_SPF_ALLOW(-0.20){+a;},MIME_GOOD(-0.10){multipart/alternative;text/plain;},ARC_NA(0.00){},DMARC_NA(0.00){ocslab.com;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},GREYLIST(0.00){greylisted;Wed, 14 Jun 2017 21:02:22 GMT;new record;},MID_RHS_MATCH_FROM(0.00){},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_TWO(0.00){2;},RCVD_NO_TLS_LAST(0.00){},R_DKIM_NA(0.00){},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 2272, time: 820.033ms real, 5.143ms virtual, dns req: 24, digest: <40964f4b38fd9b8e659c4023efafdcdd>, rcpts: <oxpa@crys.ras.ru>, mime_rcpt: <oxpa@crys.ras.ru>
Jun 14 23:57:22 ns rspamd[28477]: (normal) <73b2cc>; task; rspamd_protocol_http_reply: regexp statistics: 80 pcre regexps scanned, 7 regexps matched, 166 regexps total, 10 regexps cached, 9.13k bytes scanned using pcre, 9.13k bytes scanned total
```

**Comment by fatalbanana** [comment]
`greylist` action means nothing these days (ie. rmilter to perform greylisting).

You should **not** add soft reject action to metric.

>  And possibly it's worth changing doc a little as the phrase To enable the module with default settings
> you need to define at least redis servers to store greylisting data: is somehow misleading.

How so?- that seems accurate.

It seems you miss qid; that's likely an issue with milter proxy (you could fall back to rmilter in this case).

**Comment by oxpa** [comment]
Thank you for your explanations. No need to change anything in docs (this was a wrong assumption).

I will wait for a fix and upgrade.

**Comment by fedelebrero** [comment]
I have exactly the same problem (and config) described here, and I don't have any solution to make the rspamd greylist module work. All mail (scored 2.0 or higher) was marked as "greylist" in the web interface, but they were delivered instantly via lda or lmtp (I tried both).

Now, I have rmilter activated again and I do the greylist from there, but all mail (soft rejected or not) is marked as greylist, although in the log I see the soft_reject on the first delivery attempt. During the second delivery attempt, it is marked as "greylist" but the mail is delivered correctly.

I don't know if I'm doing something wrong or if greylist really does not work with rspamd 1.6.x.

I will wait for a fix too.

**Comment by vstakhov** [comment]
It should be fixed in the master branch.

**Comment by oxpa** [comment]
I confirm this issue is fixed
