### ISSUE TITLE
Huge memory usage after enabling phishtank

### ISSUE THREAD

**Issue by skibbipl** [vstakhov/rspamd#1686]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.0-1~sid

### Operation system, CPU, memory and environment:
2 servers with Debian testing/unstable, both have 4GB of RAM.

### Description (Please provide a descriptive summary of the issue):
After enabling phishtank rspamd memory usage jumps from 150MB to 2400MB!
![process12z 1day](https://user-images.githubusercontent.com/4746858/27191104-0d37025a-51f7-11e7-8094-6238458b53bf.png)

### Compile errors (if any):
N/A

### Steps to reproduce:
Set `phishtank_enabled = true;` in `local.d/phishing.conf`

### Expected results:
Less memory usage?

### Actual results:
After enabling phishing in rspamd on both servers rspamd starts to use a lot of memory.

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Additional information:
Is this a normal memory usage with this option enabled?

**Comment by remkolodder** [comment]
yes this is a known issue. Phising takes up a lot of memory.
