### ISSUE TITLE
MIME part not correctly detected

### ISSUE THREAD

**Issue by smfreegard** [vstakhov/rspamd#1687]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

Rspamd daemon version 1.6.0-git.39816ee93

### Operation system, CPU, memory and environment:

Ubuntu 16.10

### Description (Please provide a descriptive summary of the issue):

I was trying to write a rule to investigate the ratio of words to lines in a message as I wanted to add score for messages that contain lots of consecutive newlines.

I found a spam message to test the rule on, but I've found that task:get_text_parts() does not actually extract the MIME part.

Here is the rule:

`````
rspamd_config.FSL_NEWLINE_RATIO = {
  callback = function (task)
    local parts = task:get_text_parts()
    if parts then
logger.infox('here')
      local plain_text_part = nil
      local html_text_part = nil
      for _,p in ipairs(parts) do
        if p:is_html() then
          html_text_part = p
        else
          plain_text_part = p
        end
      end
    end
logger.infox('here2')
    if plain_text_part then
logger.infox('here3')
      local lines = plain_text_part:get_lines_count()
      return true, lines
    end
    return false
  end
}
`````

### Steps to reproduce:

Add the rule above, then run the following message through rspamd:

`````
Authentication-Results: mx-sfo2-01; auth=pass (login)
Received: from [192.168.0.7] ([186.249.119.148])
	by mx-sfo2-01 (Haraka/2.8.10) with ESMTPA id B1874CC5-E364-4390-8EF1-E2F9E3BDF9AE.1
	envelope-from <dougj6939@nospamyahoo.com> (authenticated bits=0);
	Thu, 15 Jun 2017 08:03:30 +0000
Subject: love for hip corresponding
From: Hot Secret <dougj6939@nospamyahoo.com>
Content-Type: text/plain;
	charset=us-ascii
X-Mailer: iPhone Mail (14D27)
Message-Id: <3E261C73-89F3-CA4B-43D1-02867CE4EB90@nospamyahoo.com>
Date: Thu, 15 Jun 2017 09:35:51 -0700
To: Lyall Adam <lyall.adam@mail.com>
Content-Transfer-Encoding: quoted-printable
Mime-Version: 1.0 (1.0)
X-Haraka-MidFormat: UUID_UC
X-Haraka-Cksum1: 3187462930
X-Haraka-Cksum2: 1900453037
X-Haraka-Cksum3: 604454170
X-Haraka-Train: smtp_auth_honeypot
X-Rspamd-Bar: +++++++++
X-Rspamd-Report: 
X-Rspamd-Score: 8.4

HGood Day:) could you do me a favor? It's Julie! I live in Australia, Sydne=
y
 and 32 y.o, I'am very honourable girl and for now trying to fin=
d ineffect Man Hope You wish to talk. write to gismatullinaya.roslava1984@g=
mail.com ! I'll send You my photos;)thank you
















































































































Zuzyme pacisiwe

`````

### Expected results:

FSL_NEWLINE_RATIO rule to fire

### Actual results:

'here' and 'here2' log lines are written, but not 'here3' indicating that the plain text part is not detected.

**Comment by vstakhov** [comment]
You have an error in your rule.

```lua
rspamd_config.FSL_NEWLINE_RATIO = {
  callback = function (task)
    local parts = task:get_text_parts()
    if parts then
      -- SCOPE FOR plain_text_part STARTS
      local plain_text_part = nil
      local html_text_part = nil
      for _,p in ipairs(parts) do
        if p:is_html() then
          html_text_part = p
        else
          plain_text_part = p
        end
      end
      -- SCOPE FOR plain_text_part ENDS
    end
    -- plain_text_part IS OUT OF THE SCOPE (and it is nil)
    if plain_text_part then
logger.infox('here3')
      local lines = plain_text_part:get_lines_count()
      return true, lines
    end
    return false
  end
}
```

**Comment by smfreegard** [comment]
Gah - sorry.  It's obvious now that I look at it.

Something still isn't right though.   I've fixed the rule so it fires now, but for the above message - I'm getting '5' returned, which is way shorter than I expected.   It looks like it only counts non-empty lines?  (if I insert a whitespace on one of the lines, it is counted).

Would we therefore be able to:

1)  Modify this function not to count lines with just whitespace
2)  Add a separate function that only counts blank lines (including just whitespace)

What I'm trying to do is score messages with excessive blank lines like the sample above.  It's expensive to do in regexp or Lua without a dedicated function to do so.  With both functions, I'd be able to calculate a ratio between blank to non-blank and add a score if the ratio of blank > non-blank.
