### ISSUE TITLE
OMOGRAPH_URL is scoring false positives

### ISSUE THREAD

**Issue by sander85** [vstakhov/rspamd#1689]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1

### Operation system, CPU, memory and environment:
CentOS 7

### Description (Please provide a descriptive summary of the issue):
Any message that contains URL gets scored like this:
OMOGRAPH_URL(2.50)[framadate.org]

Some details from the message:

MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="iso-8859-1"

The actual URL: https://framadate.org/Fsr5pE57gYKCjXsp

### Expected results:
It shouldn't be hit with such a high score.

**Comment by vstakhov** [comment]
I cannot reproduce it. If I replace some of latin `a` characters with cyrillic `а` characters I see a hit. Otherwise, this rule does not fire. Perhaps, you have outdated libicu in your case...

**Comment by sander85** [comment]
libicu-50.1.2-15.el7.x86_64 - I can't see any other updates. Any way to better debug the issue?

**Comment by vstakhov** [comment]
You could check epel for a newer one. I've tested it with libicu 57.

**Comment by sander85** [comment]
From where did You get this version of icu? EPEL doesn't seem to contain it.

**Comment by sander85** [comment]
I checked my older messages, this problem was introduced with 1.6.0. Before that version I don't see such scoring. And no other system library was updated when I updated to 1.6.0.

**Comment by fedelebrero** [comment]
It could be hard to update libicu (from source) without breaking other things in centos 7...

As a temporary workaround, you can slow down OMOGRAPH_URL score to 3.0 (default 5.0).
This works for me (for now) with almost all false positives.
