### ISSUE TITLE
DKIM / DKIM_SIGNING: Selecting headers to sign

### ISSUE THREAD

**Issue by mpizzoli** [vstakhov/rspamd#1691]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1

### Operation system, CPU, memory and environment:
RHEL7

### Description (Please provide a descriptive summary of the issue):
It seems Rspamd is not providing the selection of the SMTP-headers to DKIM-sign.
Headers signed are:   h=from:subject:date:message-id:to:mime-version:content-type;

### Compile errors (if any):
N/A

### Steps to reproduce:
Try to select the smtp-headers to sign via DKIM

### Expected results:
Opportunity to select the smtp-headers to include in the signature

### Actual results:
Fixed list of smtp-headers signed:  h=from:subject:date:message-id:to:mime-version:content-type;

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
N/A

### Additional information:
N/A

**Comment by vstakhov** [comment]
`rspamadm confighelp dkim` will show you `sign_headers` option. Default value is: 

```c
static const char default_sign_headers[] = ""
		"from:sender:reply-to:subject:date:message-id:"
		"to:cc:mime-version:content-type:content-transfer-encoding:"
		"resent-to:resent-cc:resent-from:resent-sender:resent-message-id:"
		"in-reply-to:references:list-id:list-owner:list-unsubscribe:"
		"list-subscribe:list-post";
```

**Comment by mpizzoli** [comment]
Could I ask you to get this feature in the "dkim_signing" module as well?

**Comment by fatalbanana** [comment]
`dkim_signing` will use this same setting (it uses `dkim` module internally for signing).

**Comment by mpizzoli** [comment]
I admit I didn't realize it... I will have a look at it. Thank you very much for the hint!

**Comment by xpunkt** [comment]
please try usiing this sign headers on maillists, does it work ?, then be happy
