### ISSUE TITLE
Cannot load controller stats from /var/lib/rspamd/stats.ucl

### ISSUE THREAD

**Issue by hardware** [vstakhov/rspamd#1693]
### Classification :

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility :

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

**Rspamd daemon version 1.6.1**

Build from source : https://github.com/hardware/s6-rspamd/blob/master/Dockerfile#L77-L96
Run file : https://github.com/hardware/mailserver/blob/v1.1/rootfs/etc/s6.d/rspamd/run

### Operation system, CPU, memory and environment:

Debian stretch docker container

### Description :

```
rspamd[xxx]: controller; rspamd_controller_load_saved_stats: cannot load controller stats from /var/lib/rspamd/stats.ucl: No such file or directory
```

```
ls -la /var/lib/rspamd/
total 1156
drwxr-xr-x  2 _rspamd _rspamd    292 Jun 18 08:18 .
drwxr-xr-x 16 root    root       203 Jun 18 08:18 ..
-rw-r--r--  1 _rspamd _rspamd  36864 Jun 18 08:18 bayes.ham.sqlite
-rw-r--r--  1 _rspamd _rspamd  32768 Jun 18 08:18 bayes.ham.sqlite-shm
-rw-r--r--  1 _rspamd _rspamd   4152 Jun 18 08:18 bayes.ham.sqlite-wal
-rw-r--r--  1 _rspamd _rspamd  36864 Jun 18 08:18 bayes.spam.sqlite
-rw-r--r--  1 _rspamd _rspamd  32768 Jun 18 08:18 bayes.spam.sqlite-shm
-rw-r--r--  1 _rspamd _rspamd   4152 Jun 18 08:18 bayes.spam.sqlite-wal
-rw-r--r--  1 _rspamd _rspamd  12288 Jun 18 08:18 learn_cache.sqlite
-rw-r--r--  1 _rspamd _rspamd  32768 Jun 18 08:18 learn_cache.sqlite-shm
-rw-r--r--  1 _rspamd _rspamd      0 Jun 18 08:18 learn_cache.sqlite-wal
-rw-r--r--  1 _rspamd _rspamd 797696 Jun 18 08:32 rspamd.rrd
srw-------  1 root    root         0 Jun 18 08:18 rspamd.sock
```

Configuration : https://github.com/hardware/mailserver/tree/v1.1/rootfs/etc/rspamd

### Compile errors :

No compilation error.

### Steps to reproduce:

1. Start rspamd

### Additional information:

Build dependencies installed :

```
cmake
ragel
pkg-config
liblua5.1-0-dev
libglib2.0-dev
libevent-dev
libsqlite3-dev
libicu-dev
libssl-dev
libmagic-dev
libfann-dev
```

Dependencies installed :

```
libevent-2.0-5
libglib2.0-0
libssl1.1
libmagic1
liblua5.1-0
libfann2
libsqlite3-0
sqlite3
openssl
ca-certificates
```

Build method : https://github.com/hardware/s6-rspamd/blob/master/Dockerfile

**Comment by vstakhov** [comment]
That's fine during the first start.

**Comment by hardware** [comment]
Ok thanks ;)
