### ISSUE TITLE
local dkim signing config is ignored 

### ISSUE THREAD

**Issue by bjo81** [vstakhov/rspamd#1694]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1

### Operation system, CPU, memory and environment:
Debian 
### Description (Please provide a descriptive summary of the issue):
rspamd does not include /etc/rspamd/local.d/dkim_signing.conf

### Steps to reproduce:
put a config into /etc/rspamd/local.d/dkim_signing.conf

### Expected results:
the config is loaded and the individual path is used for the keys

### Actual results:
the config is ignored and the module complains not to find the keys in /var/lib/rspamd/dkim

### Configuration:
/etc/rspamd/local.d/dkim_signing.conf contains
```
dkim_signing {
 path = "/etc/dkim/$domain.$selector.key";
  # Default selector to use
  selector = "default";
}
```
Rspamd logs:
```task; lua_dkim_sign_handler: cannot load dkim key /var/lib/rspamd/dkim/nord-west.org.dkim.key: cannot stat private key /var/lib/rspamd/dkim/nord-west.org.dkim.key: Datei oder Verzeichnis nicht gefunden```

/etc/rspamd/modules.d/dkim_siging.conf contains 
```
  .include(try=true,priority=5) "${DBDIR}/dynamic/dkim_signing.conf"
  .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/dkim_signing.conf"
  .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/dkim_signing.conf"
```
so the local config should be loaded.

**Comment by vstakhov** [comment]
You have redundant `dkim_signing` element in the file. Remove it.

**Comment by bjo81** [comment]
Thanks for the hint and sorry for the noise.
