### ISSUE TITLE
Postinstall/update error since 1.6.0 (centos)

### ISSUE THREAD

**Issue by fedelebrero** [vstakhov/rspamd#1696]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1
### Operation system, CPU, memory and environment:
CentOS 7.3.1611

### Description (Please provide a descriptive summary of the issue):
When install (or update) rspamd rpm package, I get some chown errors and the service cannot start.

### Steps to reproduce:
Update rspamd 1.6.0 to 1.6.1, or 1.6.1-1 to 1.6.1-2

### Expected results:
Update without issues

### Actual results:
```
Running transaction
  Updating   : rspamd-1.6.1-2.x86_64                                        1/4
/usr/bin/chown: cannot access ‘/build7558b18c49c3aede6aa20ecb0513b9eb2b39ce7db0c739ec006369009fdf893d91b9ec4199fa64acd80aa1de7fac87a148a6f65e98f258b455996c5f99d990d2/BUILDROOT/rspamd-1.6.1-2.x86_64/var/log/rspamd’: No such file or directory
```
Fix:
chown -R _rspamd: /var/log/rspamd/ ; systemctl restart rspamd

**Comment by Ragzid** [comment]
This happens also when running clean install `yum install rspamd`, same result:
```
/usr/bin/chown: cannot access ‘/build7558b18c49c3aede6aa20ecb0513b9eb2b39ce7db0c739ec006369009fdf893d91b9ec4199fa64acd80aa1de7fac87a148a6f65e98f258b455996c5f99d990d2/BUILDROOT/rspamd-1.6.3-1.x86_64/var/log/rspamd’: No such file or directory
```
The following line should be without `%{buildroot}` variable.
https://github.com/vstakhov/rspamd/blob/e9deede49746063c763039097716aaf13c99ab97/centos/rspamd.spec#L149
