### ISSUE TITLE
RSPAMD executes only one of metrics actions with the same weight

### ISSUE THREAD

**Issue by VolFestion** [vstakhov/rspamd#1699]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1

### Operation system, CPU, memory and environment:
CentOS 7

### Description (Please provide a descriptive summary of the issue):
If metrics actions are with the same weight "add_header = 6; rewrite_subject = 6;" then rspamd executes only one of them.
Rmilter made both actions, for example:
rmilter[644]: <daf23b50f6>; mlfi_eom: rewriting spam subject and adding spam header

### Expected results:
It should be behaviour like rmilter.

**Comment by fatalbanana** [comment]
To get the desired behaviour:

* Set threshold for `rewrite subject`; remove threshold for `add header` (ie. by setting metric actions in `override.d/metrics.conf`)
* Add headers if/when you want them using [milter headers](https://rspamd.com/doc/modules/milter_headers.html)

**Comment by VolFestion** [comment]
Thank you. I couldn't setup this solution because I something misunderstood.
My case discussed here:
https://groups.google.com/forum/#!topic/rspamd/IVfqm0_CHTc
I will try later. You may close this issue.
