### ISSUE TITLE
Enabling extended headers in self scan milter mode?

### ISSUE THREAD

**Issue by athanp** [vstakhov/rspamd#1701]
How can I enable extended headers to every mail being checked in self scan milter mode (similar to the rmilter old way)?
That was very useful for debugging and informational purposes but cannot figure how this can be done in 1.6.1 self scan mode.

**Comment by fatalbanana** [comment]
Have you tried [extended_spam_headers](https://rspamd.com/doc/modules/milter_headers.html) milter_headers option? You may also be interested in `skip_local` and `skip_authenticated` options.
