### ISSUE TITLE
"enabled = false" not disables worker normal?

### ISSUE THREAD

**Issue by athanp** [vstakhov/rspamd#1702]
Using self-scan milter mode, I'm trying to disable normal worker saving some server resources.
According to rspam docs, a simple "enabled = false;" inside local.d/worker-normal.inc would be enough. Unfortunately it is not working, not inside local.d/worker-normal.inc, not even it rspamd.conf.override worker {} context.

I had to comment out the whole worker {} block in rspamd.conf.override to disable normal worker.

A bug or did I miss something?

**Comment by fatalbanana** [comment]
It works merely in 1.6.2+ (not yet in a released version).
