### ISSUE TITLE
unexpected results of multimap module

### ISSUE THREAD

**Issue by setiseta** [vstakhov/rspamd#1703]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1
### Operation system, CPU, memory and environment:
ubuntu 16.04, xeon, 64gb ram.
### Description (Please provide a descriptive summary of the issue):
I have created a simple multimap filter, but it seems not to work as expected.
### Steps to reproduce:
local.d/multimap.conf:
```
EMAIL_BLACKLIST {
  type = "from";
  filter = "email";
  map = "/maps/emails.bl";
  prefilter = true;
  action = "reject";
}
```
- add a e-mail to the blacklist over the web ui.
- send from the entered e-mail adress the the mailbox "behind" rspamd

### Expected results:
mail gets rejected

### Actual results:
mail gets into mailbox

### Additional information:
maybe i just missunderstood something on config side.

**Comment by vstakhov** [comment]
Are you sure that this map has been reloaded? It happens around each 10 seconds for file maps or even more (depending on your `maps_watch_interval` option).

**Comment by vstakhov** [comment]
Also: `from` map is using SMTP from. If it is missing, then MIME from is used (this has been adjusted to the behaviour documented quite recently).

**Comment by setiseta** [comment]
Thank you for the feedback.
I've retestet, and it seems I was too fast.
The default map_watch_interval is set to 5min, is this correct?
Is it a performance issue if it is shorter?

What is the difference between SMTP From and MIME From?
I have seen an e-mail address in the history tab (in the gui) in the column "From".
Can I use this one, or is it a different from?

**Comment by vstakhov** [comment]
For files it is not 5 mins but much shorter. I'll recheck this.

**Comment by fatalbanana** [comment]
1.6.2 adds `map_file_watch_multiplier` setting; default config sets this at `0.1`, making refresh interval for map files effectively much shorter: 30 seconds supposing `map_watch_interval` is set to 5 minutes.

**Comment by setiseta** [comment]
Ok sounds nice. Thank you.
