### ISSUE TITLE
Greylisting never happens when action is "reject"

### ISSUE THREAD

**Issue by shapirus** [vstakhov/rspamd#1707]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Master at fd74eaf

### Operation system, CPU, memory and environment:
Ubuntu Zesty 64-bit
MTA: Exim 4.88

### Description (Please provide a descriptive summary of the issue):
When spam score is below 15, greylisting works as documented. Otherwise, rspamd responds with action "reject" and greylisting does not take place.

### Expected results:
Greylisting happens _always_ when **spam_score** is greater or equal to **greylist_min_score** 

### Additional information:
In my situation, I prefer to never reject any messages, even on the recommended action "reject" or very high **spam_score** values, but only add headers to the probable spam messages to let the end users decide for themselves how to handle them.
Above certain threshold of **spam_score**, however, _especially_ the very high values, I want the senders to be greylisted first, and only on further attempts let the messages through (of course, after executing the spam checks again and setting the respective headers). Most of spam that I receive scores well over 15 (typically 20+) which effectively makes greylisting in my case non-functional, however it could prevent most of those messages from being delivered if it did take place for them.
Current rspamd's behavior only allows to greylist messages in the "**greylist_min_score** <= **spam_score** < **reject_score**" range.

To me it looks like either, if this behavior is intended, there is a reason to add a new numeric setting "greylist_max_score" or boolean "greylist_on_action_reject", or, if this behavior is unintended, there is a bug.
Of course it is possible that I am missing some point here, please let me know if that's the case.

**Comment by fatalbanana** [comment]
That is by design. It seems removing threshold for `reject` action from metric (ie. by setting metric actions in `override.d/metrics.conf`) would work for you (it could be conditionally restored using [settings](https://rspamd.com/doc/configuration/settings.html) module).

**Comment by shapirus** [comment]
Yes true, removing the action: reject threshold from metric worked. I am fine with that: spam_score is enough for making decisions in both MTA and user settings.

I think, however, that this issue deserves updating the greylisting module documentation. This behavior is (to me) far from obvious and may take a while to investigate and find out that it's not a configuration problem but is actually supposed to work that way :)

**Comment by vstakhov** [comment]
If you think it is not obvious to you then please send an update for `rspamd.com` repo where documentation lives. Nobody would likely do that for you.
