### ISSUE TITLE
[Question] Now rspam_proxy has replaced rmilter, how do I add headers to mails?

### ISSUE THREAD

**Issue by deanishe** [vstakhov/rspamd#1709]
### Rspamd version:

1.6.1

### Operation system, CPU, memory and environment:

Postfix + rspamd + dovecot

### Description (Please provide a descriptive summary of the issue):

I have been using rspamd+rmilter with postfix and dovecot. I was using rmilter to add headers to mails, and then moving them to the users' junk folders via sieve rules.

How do I do that without rmilter?

**Comment by fatalbanana** [comment]
[milter headers module](https://rspamd.com/doc/modules/milter_headers.html)

**Comment by moisseev** [comment]
Besides, Rspamd adds`X-Spam: Yes` header to spam messages by default.

**Comment by fatalbanana** [comment]
@moisseev not so in 1.6.1.

**Comment by deanishe** [comment]
> It's mentioned in the migration notes

Thanks. I was thrown off by this bit in the docs:

> If you configured this module inside local.d/rmilter_headers.conf or in override.d/rmilter_headers.conf then you don’t need to undertake any actions: these files are still loaded by the renamed module. Otherwise, you need to change section name from rmilter_headers to milter_headers.

I went over my configuration again, and realised that rmilter was configured in /etc/rmilter.conf.

I moved the config over to the right files, and everything is working swimmingly.

Thanks very much for your super-fast help everyone.

**Comment by mpizzoli** [comment]
@fatalbanana I am working with 1.6.1 for outgoing DKIM-signing and I see
the "X-Spam: yes" header added to the email.

Did I forget to do something or is it expected behaviour?

How can I eliminate it?

Thank you very much in advance
Marco
