### ISSUE TITLE
Url tags scripts

### ISSUE THREAD

**Issue by vstakhov** [vstakhov/rspamd#1716]
2017-06-30 15:59:22 #2275(normal) <92fe3f>; lua; url_tags.lua:166: Redis error: NOSCRIPT No matching script. Please use EVAL.

**Comment by fabiodemartin** [comment]
I have the same issue with the url_reputation:

url_reputation.lua:170: couldnt increment reputation: NOSCRIPT No matching script. Please use EVAL
url_tags.lua:166: Redis error: NOSCRIPT No matching script. Please use EVAL

Is this a configuration problem or a bug?

[]s

**Comment by fatalbanana** [comment]
You may see it intermittently if Redis is restarted or loses scripts for some reason. If you see it constantly maybe something goes wrong when it tries to load the script (happens on startup & when the script is found to be missing).
