### ISSUE TITLE
No package for trusty/amd64 in stable APT repo.

### ISSUE THREAD

**Issue by donspaulding** [vstakhov/rspamd#1720]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [X ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Any

### Operation system, CPU, memory and environment:
Ubuntu 14.04 Trusty on amd64

### Description (Please provide a descriptive summary of the issue):
Simply note the empty file at: https://rspamd.com/apt-stable/dists/trusty/main/binary-amd64/Packages

**Comment by vstakhov** [comment]
I've rebuilt them for this platform.
