### ISSUE TITLE
DNS Flood, too many queries to RBLs

### ISSUE THREAD

**Issue by csmk** [vstakhov/rspamd#1721]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1

### Operation system, CPU, memory and environment:
Gentoo (guest) on KVM, vCPU (Intel Core2 Duo), 2GiB

### Description (Please provide a descriptive summary of the issue):
I was tweaking my local DNS resolver (unbound server) and decided to activate the query logs, just to find out a torrent of DNS queries to RBLs coming from rspamd. I've an email server with very low traffic, so why rspamd keep asking for so many IPs? Is this the normal behavior?

This log was captured for about 25 minutes: https://gist.github.com/csmk/7edcb1b8ab35364b6bcc80380e821d39

### Steps to reproduce:
Use a local DNS resolver, like unbound and activate the query log. On unbound I have:
```
server:
  verbosity: 2
  logfile: "/etc/unbound/unbound.log"
  num-threads: 3
  so-reuseport: yes
  interface: 127.0.0.1
```

### Expected results:
Less DNS flood?!

### Additional information:
Even if I close all inbound SMTP ports, the flow won't stop. But as soon I stop rspamd, the DNS flood also stop.

**Comment by vstakhov** [comment]
Each DNS resource has planned monitoring (approximately one per minute). From your logs, Rspamd has sent initiated around 900 queries (the exact amount of requests sent by Rspamd is MUCH lower) over 25 minutes. It is not a flood, it is an intended health check.
