### ISSUE TITLE
Drop mails instead of rejecting them

### ISSUE THREAD

**Issue by jnhmn** [vstakhov/rspamd#1723]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Description (Please provide a descriptive summary of the issue):
We are running our mail server in a complex cooperate environment and are by policy not allowed to reject spam mails since our smarthost can not handle this properly.

Is there a way to tell spamd to simply drop Spam Mails?
If not, this would be a great feature for us, since we a running several dozens of mailing lists on on our server which can not be configured automatically.

**Comment by vstakhov** [comment]
I have added an option called `discard_on_reject` to the `rspamd_proxy` worker. In Milter mode, this option switches rejection mode from `reject` to `discard`.

**Comment by jnhmn** [comment]
Thank you, finally i came to testing it. Works fine
