### ISSUE TITLE
Rspamd 1.6.x documentation: wrong sendmail milter configuration

### ISSUE THREAD

**Issue by albsol** [vstakhov/rspamd#1728]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.0

### Description (Please provide a descriptive summary of the issue):

Wrong sendmail configuration documented in
       https://rspamd.com/doc/integration.html#using-rspamd-with-sendmail-mta

It says:
       MAIL_FILTER(`rspamd', `S=inet:localhost:11332, F=T')

The correct syntax would be: 
       MAIL_FILTER(`rspamd', `S=inet:11332@localhost, F=T')

It depends if you have local o remote rspamd server, ipv4 or ipv6:

S=inet:11332@localhost                             ← port 11332 on the local machine, using IPv4
S=inet:11332@host.your.domain              ← port 11332 on another machine on your network,using IPv4
S=inet6:11332@localhost                           ← port 11332 on the local machine, using IPv6
S=inet:11332@123.45.67.89                      ← port 11332 at IPv4 number 123.45.67.89
S=inet6:11332@2002:c0a8:51d2::23f4    ← port 11332 at IPv6 number 2002:c0a8:51d2::23f4

**Comment by fatalbanana** [comment]
That was [https://github.com/vstakhov/rspamd.com/commit/91b29b185c1b24d245a5c2bad2f523e987aef084#diff-151663d7c4da120af827e5fd6ba403c6](fixed), thank you for the report.

**Comment by Matatu** [comment]
Why it's closed, the documentation is still wrong.

**Comment by albsol** [comment]
Documentation is still wrong at https://rspamd.com/doc/integration.html#using-rspamd-with-sendmail-mta

**Comment by Matatu** [comment]
> Documentation is still wrong at https://rspamd.com/doc/integration.html#using-rspamd-with-sendmail-mta

You have opened the issue, you should be able to reopen it, because the problem is not fixed.

**Comment by albsol** [comment]
I cannot reopen this issue, I haven't found any reopen button. It seems only collaborators on a personal repository can do it.

More info:
https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository

**Comment by moisseev** [comment]
@albsol FYI: There is an `Edit Page` button at the top of the web page. You could use it to open a pull request in [rspamd/rspamd.com](https://github.com/rspamd/rspamd.com) repository.
