### ISSUE TITLE
[Feature Request] "rspamadm configdump" to support multiple rspamd instances

### ISSUE THREAD

**Issue by mpizzoli** [vstakhov/rspamd#1730]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1

### Operation system, CPU, memory and environment:
EL7 x86_64

### Description (Please provide a descriptive summary of the issue):
"rspamadm configdump" produces a merged dump of the current rspamd configuration. 
Problem is, in my usa case, it is not aware of other rspamd instances running on the system.

Starting from a single rspamd rpm installation, I created separate configurations and startup systemd units.
I am starting rspamd with all variables:
DBDIR=
LOCAL_CONFDIR=
DBDIR=
RUNDIR=

It would be great if I could provide at least the same variables to "rspamadm configdump" in order to get the specific configdump.

### Compile errors (if any):
N/A

### Steps to reproduce:
rspamadm configdump

### Expected results:
The specific instance configuration dump

### Actual results:
Only the main configuration dumped

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
rspamd, single installation, multiple instances running with different configuration directories

### Additional information:
N/A

**Comment by fatalbanana** [comment]
You can use `rspamadm configdump -c /path/to/config`

**Comment by fatalbanana** [comment]
```rspamadm --var=DBDIR=/foo configdump -c /bar```

or you could define DBDIR appropriately at build time.

**Comment by mpizzoli** [comment]
You are right! :-)

I have just used the following command and it worked:
`rspamadm --var=DBDIR=/var/ib/rspamd-INST1  --var=RUNDIR=/var/run/rspamd-INST1  --var=CONFDIR=/etc/rspamd-INST1 --var=LOCAL_CONFDIR=/etc/rspamd-INST1`

Thank you very much for your help!
