### ISSUE TITLE
Can not edit "X-Rspamd-Server"

### ISSUE THREAD

**Issue by johnwmail** [vstakhov/rspamd#1736]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1
### Operation system, CPU, memory and environment:
OpenBSD, 64bit, 8G ram
### Steps to reproduce:
add /etc/rspamd/local.d/milter_headers.conf, like below

--------------------------------------------------------------------------

> 

extended_spam_headers = true;

routines {
        x-rspamd-server {
                header = "X-Rspamd-Server";
                value = "rspamd.mydomain.com";       
        }
}

> 

--------------------------------------------------------------------------

### Expected results:
X-Rspamd-Server will be "rspamd.mydomain.com"

### Actual results:
X-Rspamd-Server still is "hostname"

### Additional information:
Hi, I want to edit "X-Rspamd-Server", but not work and I look at the lua script like this,

--------------------------------------------------------------------------

> 

routines['x-rspamd-server'] = function()
    if skip_wanted('x-rspamd-server') then return end
    if settings.routines['x-rspamd-server'].remove then
      remove[settings.routines['x-rspamd-server'].header] = settings.routines['x-rspamd-server'].remove
    end
    add[settings.routines['x-rspamd-server'].header] = HOSTNAME
  end

> 

--------------------------------------------------------------------------

It look like something wrong, no matter what I set,
the last line still execute
"add[settings.routines['x-rspamd-server'].header] = HOSTNAME"

So, I can not edit X-Rspamd-Server to other than my $HOSTNAME, right (I dont know lua)?

Please help, I want edit "X-Rspamd-Server" to other than my $HOSTNAME,

Thanks.

**Comment by fatalbanana** [comment]
You could add the header with your desired value using a [custom routine](https://rspamd.com/doc/modules/milter_headers.html#custom-routines) instead of the built-in one. I've just added an `add-headers` routine to support adding arbitrary headers from config instead of Lua.

~~~
routines {
  add-headers {
    headers {
      X-Rspamd-Server = "foo";
    }
  }
}
~~~

**Comment by johnwmail** [comment]
Hi , I added this to /etc/rspamd/local.d/milter_headers.conf, but still not work

routines {
  add-headers {
    headers {
      X-Rspamd-Server = "foo";
    }
  }
}

**Comment by fatalbanana** [comment]
Did you install latest sources?- If not it's not expected to work.

However you could [use a custom routine](https://rspamd.com/doc/modules/rmilter_headers.html#custom-routines):

~~~
use = ["my-x-rspamd-server"];
  custom {
    my-x-rspamd-server = <<EOD
return function(task, common_meta)
  -- parameters are task and metadata from previous functions
  return nil, -- no error
    {['X-Rspamd-Server'] = 'MY_HOSTNAME'}, -- add header: X-Foo: Bar
    {['X-Rspamd-Server'] = 1}, -- remove foreign X-Foo headers
    {}, -- metadata to return to other functions
EOD;
  }
~~~

**Comment by johnwmail** [comment]
Hi, my rspamd is version 1.6.2
Will it work?  Or need git version?

I will tried it, when I back to home.

Thank you anyway.

**Comment by johnwmail** [comment]
Unfortunately, still not work on 1.6.2😭

**Comment by johnwmail** [comment]
I noticed, rspamd show some error message, when I run rspamadm configdump

2017-07-11 08:29:30 #14846((NULL)) <uxw6cm>; lua; milter_headers.lua:429: could not load "my_routine": [string "return function(task, common_meta)..."]:6: unexpected symbol near '<eof>'                       
2017-07-11 08:29:30 #14846((NULL)) <uxw6cm>; lua; milter_headers.lua:397: routine "my_routine" does not exist

my /etc/rspamd/local.d/milter_headers.conf like below
``
# local.d/milter_headers.conf
extended_spam_headers = true;

use = [ "my_routine" ];

custom {
    my_routine = <<EOD
return function(task, common_meta)
  -- parameters are task and metadata from previous functions
  return nil, -- no error
    {['X-Rspamd-Server'] = 'rspamd.wonghome.net'}, -- add header: X-Rspamd-Server: rspamd.wonghome.net
    {['X-Rspamd-Server'] = 1}, -- remove foreign X-Rspamd-Server headers
    {}, -- metadata to return to other functions
EOD;
  }
``

**Comment by fatalbanana** [comment]
The configuration example is bad I'm afraid - [I've fixed it](https://github.com/vstakhov/rspamd.com/commit/593e8f57ceac611cee1db1d255693b3fcd866e1e).

**Comment by johnwmail** [comment]
Hi, I imported (lastet milter_headers.lua) with 1.6.2
and my /etc/rspamd/local.d/milter_headers.conf

`extended_spam_headers = true;                       

routines {                                          
        add-headers {                               
                X-Rspamd-Server = "rspamd.wonghome.net";                                                
        }                                           
}           `

**Comment by fatalbanana** [comment]
No; `extended_spam_headers = true` implicitly enables `x-spamd-result`, `x-rspamd-server` & `x-rspamd-queue-id`.

~~~
extended_spam_headers = false;
use = ["x-spamd-result", "x-rspamd-queue-id", "add-headers"];
routines {
  add-headers {
    X-Rspamd-Server = "rspamd.wonghome.net";
  }
}
~~~

**Comment by johnwmail** [comment]
OK, changed, thank you.

By the way, why some plugin/rule (multimap) symbol is zero score?
Is not that(zero score) meaningless?

**Comment by fatalbanana** [comment]
Such symbols could be used in composites/by other rules/by FANN. In the case of multimap (Freemail stuff) - it's used by rules.

**Comment by johnwmail** [comment]
Hi, add-headers function still not work😂

extended_spam_headers = false;
use = ["x-spamd-result", "x-rspamd-queue-id", "add-headers"];
routines {
  add-headers {
    X-Rspamd-Server = "rspamd.wonghome.net";
  }
}

**Comment by johnwmail** [comment]
Now， rspamd only add "x-spamd-result", "x-rspamd-queue-id"

No "X-Rspamd-Server" header.

Thanks.

**Comment by fatalbanana** [comment]
Example config was wrong- sorry - there should be a `headers {}` block inside `add-headers`.

~~~
extended_spam_headers = false;
use = ["x-spamd-result", "x-rspamd-queue-id", "add-headers"];
routines {
  add-headers {
    headers {
      X-Rspamd-Server = "rspamd.wonghome.net";
    }
  }
}
~~~

**Comment by johnwmail** [comment]
OK, changed, let see the result later, 
Thanks.

**Comment by johnwmail** [comment]
It work as expected, thank you

**Comment by pilchita** [comment]
Hello, sorry for answering such an ancient publication.

I use exim, this service not use the milter protocol, i understand the option "extended_spam_headers" not work, any ideas to add the headers x-rspamd-server and x-rspamd-queue-id in all mails?
