### ISSUE TITLE
Whitelist module

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1745]
### Classification:
* [x] Enhancement

### Reproducibility:
* [X] Always

### Rspamd version:
1.6.2

### Description:
Currently there is no way to add spf_whitelist.inc or dkim_whitelist.inc in local.d folder for whitelist plugin.
It may be achieved only by including them explicitelly, with a new file whitelist.conf in local.d:

rules {
    "WHITELIST_DKIM" = {
        domains = [
                "${CONFDIR}/local.d/dkim_whitelist.inc"
        ];
    }
}

Can you add this possibility "built-in"? without need to add custom whitelist.conf also in local.d?

Thanks!

**Comment by fatalbanana** [comment]
The stock rules [include lists in /var/lib/rspamd](https://github.com/vstakhov/rspamd/blob/master/conf/modules.d/whitelist.conf#L22).

**Comment by madorin** [comment]
@fatalbanana, I see /var/lib/rspamd contains more like dynamic generated files and/or loaded from db.
An white-list domain list domain file is more like a config file, should be in /etc/, no?
Ok, i'll try in meantime with /var, thanks
