### ISSUE TITLE
"Inline" maps

### ISSUE THREAD

**Issue by mpizzoli** [vstakhov/rspamd#1754]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.2

### Operation system, CPU, memory and environment:
EL7 x86_64

### Description (Please provide a descriptive summary of the issue):
I see that all non-remote maps (non-http / non-redis) are external to the main configuration files.
I understand that this permits to dynamically reload the configuration.

Though, I see no reason for not enabling to still have inline maps inside the configuration files as a way to simplify the configuration for simple scenarios. It seems to me an unnecessary indirection...

My enhancement request is to have "inline:" maps as Postfix implemented in version 3.0
so in the conf file I could have:
maps = inline: { {BLABLA1} {BLABLA2} }

### Compile errors (if any):
N/A

### Steps to reproduce:
N/A

### Expected results:
N/A

### Actual results:
N/A

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
N/A

### Additional information:
N/A

**Comment by vstakhov** [comment]
It works for the vast majority of maps in Rspamd. Just type map = ["value1", "value2"...]
