### ISSUE TITLE
error: invalid connect command (bad IPv6)

### ISSUE THREAD

**Issue by jirireischig** [vstakhov/rspamd#1760]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.2

### Operation system, CPU, memory and environment:
CentOS 7.3

### Description (Please provide a descriptive summary of the issue):

Rspamd sometimes close connection and don't check incoming message.

Error from log:
Jul 18 11:15:34 rspamd[32007]: <771da4>; proxy; proxy_accept_socket: accepted milter connection from /var/run/rspamd/rspamd.sock port 0
Jul 18 11:15:34 rspamd[32007]: <771da4>; proxy; proxy_milter_error_handler: abnormally closing milter connection from: /var/run/rspamd/rspamd.sock, error: invalid connect command (bad IPv6)

### Configuration:

Rspamd used as milter with sock by sendmail MTA.

**Comment by jirireischig** [comment]
Thank you very much, 
your "[Fix] Add workaround for IPv6 in sendmail" working well on our server with rspamd 1.6.3.

**Comment by jirireischig** [comment]
Thank you for your help with sendmail.
Is it possible to use the fix in the next release? 1.6.5?

**Comment by vstakhov** [comment]
Isn't it in 1.6.4?

**Comment by jirireischig** [comment]
I'm sorry, It's look like not in 1.6.4.

**Comment by christmart** [comment]
Still the same error message with 1.6.4 on Debian:
2017-10-19 12:15:05 #2019(rspamd_proxy) <bf37ee>; proxy; proxy_milter_error_handler: abnormally closing milter connection from: 127.0.0.1, error: invalid connect command (bad IPv6)

**Comment by fatalbanana** [comment]
Fix in question **is not in 1.6.4**, it will be in the next release.
