### ISSUE TITLE
Make global option local_addrs usable with a file containing IP addresses or networks.

### ISSUE THREAD

**Issue by pclemot** [vstakhov/rspamd#1763]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

**Comment by fatalbanana** [comment]
[Docs](https://rspamd.com/doc/configuration/options.html) say: ```local_addrs or local_networks: map or list of IP networks used as local, so certain checks are skipped for them (e.g. SPF checks)``` and pointing this to a map seems to work indeed:

```
echo 'local_addrs = "/etc/rspamd/pseudolocal.nets"' >> /etc/rspamd/local.d/options.inc
cat > /etc/rspamd/pseudolocal.nets << _EOF
192.168.0.0/16
10.0.0.0/8
172.16.0.0/12
fd00::/8
169.254.0.0/16
fe80::/1
_EOF
```

**Comment by pclemot** [comment]
I've just test it with local_addrs, actyually it works like a charm. I've been testing it with, local_networks, and it made rspamd stop (or crash, I don't know)...
