### ISSUE TITLE
Email address stripped in Webui

### ISSUE THREAD

**Issue by madorin** [vstakhov/rspamd#1766]
### Classification:

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility:

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.2

### Description:
In WebUI/history TO field, strips "." symbol, ie if email address is user.name@gmail.com then it is displayed as "username@gmail.com". At least it is present for Gmail addresses. I did not saw this for local emails.

**Comment by fatalbanana** [comment]
This is normalisation applied by the `EMAIL_PLUS_ALIASES` rule. Gmail ignores dots in local parts, so `user.name == username`.

**Comment by madorin** [comment]
Ok, thanks for clarification ;) sorry. did not saw this before..
