### ISSUE TITLE
inconsistent counts when sharing data folder among scan nodes in proxy mode.

### ISSUE THREAD

**Issue by vixns** [vstakhov/rspamd#1778]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3
### Operation system, CPU, memory and environment:
docker debian based image vixns/rspamd running on mesos containerizer
### Description (Please provide a descriptive summary of the issue):
I have a setup with one proxy and for now only one "scan" node and redis, all running on mesos/marathon.

On first start, all counts are 0, I'm sending 2 tests mails, counts are now 2/2/0/0/0/0 (scanned/clean/grey/probable/reject/learned).
There is no `stats.ucl` file.

After restarting the scan node, the web UI count changes to 0/0/0/0/0/0
`stats.ucl`contains `{"scanned":2,"learned":0,"actions":{"reject":0,"soft reject":0,"rewrite subject":0,"ad
d header":0,"greylist":0,"no action":2},"connections":2,"control_connections":11}`

Restarting in this case means starting a new node using the same data folder, and when the healthcheck is green, kill the old one.

I'm sending one test email, counts are now 1/1/0/0/0/0
`stats.ucl` contents does not change

Restarting again ( scale to 2 scan nodes, then kill the old one ), the counts are now 2/2/0/0/0/0
`stats.ucl` contains `{"scanned":1,"learned":0,"actions":{"reject":0,"soft reject":0,"rewrite subject":0,"ad
d header":0,"greylist":0,"no action":1},"connections":1,"control_connections":27}`

If I change the restart mode by first killing the old node, then starting a new one, I don't have this issue, but I have a downtime each time I restart, and It means I cannot run more than one  scan node this way. 

It looks like a race condition between the reading and writing of the `stats.ucl` file.
I guess these stats are in memory only and are written back to disk only when stopping the process.
As the file has a generic name, sharing it among instances is bad.

What about using the node ip address + port as suffix to prevent conflicts ( `stats-10.10.10.3-11333.ucl` )  and/or store all nodes stats in the proxy node data folder ?

update: This may accomplished by updating stats_path from the shell before starting rspamd. Shouldn't these stats stored in redis instead ?

**Comment by vstakhov** [comment]
I don't understand what you are doing. Do not share data folder between Rspamd instances: this problem is quite innocent but it might be much worse when it comes to hyperscan for instance. Use separate data folder for each individual Rspamd instance, that's it.
