### ISSUE TITLE
BROKEN_HEADERS for valid bounce message

### ISSUE THREAD

**Issue by dupondje** [vstakhov/rspamd#1783]
### Classification:

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3

### Steps to reproduce:
The mail in attachment is a valid bounce.
But rspamd gives it a 10 score for BROKEN_HEADERS, while they are valid.

### Expected results:
# rspamc test.eml 
Results for file: test.eml (5.008 seconds)
[Metric: default]
Action: no action
Spam: false
Score: 1.00 / 15.00
Symbol: ARC_NA (0.00)
Symbol: DATE_IN_PAST (1.00)
Symbol: DMARC_NA (0.00)[mailcontrol.com]
Symbol: FROM_HAS_DN (0.00)
Symbol: FROM_NEQ_ENVFROM (0.00)[MAILER-DAEMON@rly51d.srv.mailcontrol.com, ]
Symbol: MID_RHS_MATCH_FROM (0.00)
Symbol: PREVIOUSLY_DELIVERED (0.00)[mail@example-domain.com]
Symbol: RCPT_COUNT_ONE (0.00)[1]
Symbol: RCVD_COUNT_FIVE (0.00)[5]
[bounce.txt](https://github.com/vstakhov/rspamd/files/1194576/bounce.txt)

Symbol: RCVD_NO_TLS_LAST (0.00)
Symbol: R_DKIM_NA (0.00)
Symbol: TO_DN_NONE (0.00)
Symbol: URIBL_BLOCKED (0.00)[mailcontrol.com.multi.uribl.com, myserver.be.multi.uribl.com]
Message-ID: 201708011242.v71CgSVL022065@rly51d.srv.mailcontrol.com

### Actual results:
# rspamc test.eml 
Results for file: test.eml (5.012 seconds)
[Metric: default]
Action: add header
Spam: true
Score: 11.00 / 15.00
Symbol: ARC_NA (0.00)
Symbol: BROKEN_HEADERS (10.00)
Symbol: DATE_IN_PAST (1.00)
Symbol: DMARC_NA (0.00)[mailcontrol.com]
Symbol: FROM_HAS_DN (0.00)
Symbol: FROM_NEQ_ENVFROM (0.00)[MAILER-DAEMON@rly51d.srv.mailcontrol.com, ]
Symbol: MID_RHS_MATCH_FROM (0.00)
Symbol: PREVIOUSLY_DELIVERED (0.00)[mail@example-domain.com]
Symbol: RCPT_COUNT_ONE (0.00)[1]
Symbol: RCVD_COUNT_FIVE (0.00)[5]
Symbol: RCVD_NO_TLS_LAST (0.00)
Symbol: R_DKIM_NA (0.00)
Symbol: TO_DN_NONE (0.00)
Symbol: URIBL_BLOCKED (0.00)[mailcontrol.com.multi.uribl.com, myserver.be.multi.uribl.com]
Message-ID: 201708011242.v71CgSVL022065@rly51d.srv.mailcontrol.com

**Comment by fabiodemartin** [comment]
Found the same issue with 1.6.4 (BROKEN_HEADERS).

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
