### ISSUE TITLE
lua_dkim_sign_handler error when sending mail

### ISSUE THREAD

**Issue by athanp** [vstakhov/rspamd#1784]
Whenever sending an email the following error is logged (rspamd 1.6.3 / FreeBSD 11.1 x64).

`proxy; lua_dkim_sign_handler: cannot load dkim key /var/db/rspamd/arc/domain.com.arc.key: can not stat private key /var/db/rspamd/arc/domain.com.arc.key: No such file or directory`

However DKIM signing works fine as always. I don't get why rspamd is looking for keys in that directory even though my dkim private ones are in /usr/local/etc/mail.

Does it have anything to do with arc signing though even in this case why it does not look for keys in arc module default path /var/lib/rspamd/arc?

**Comment by moisseev** [comment]
`/var/lib/rspamd/arc` is the default path for Linux. FreeBSD has different file system hierarchy.
FreeBSD defaults to `/var/db/rspamd/arc/$domain.$selector.key`.
You can change it in `/usr/local/etc/rspamd/local.d/arc.conf` as
```cfg
path = "/usr/local/etc/mail/$domain.$selector.key";
```
If you want to use dkim keys for arc signing you can set the same selector, for instance:
```
selector = "dkim";
```

**Comment by athanp** [comment]
So it's an arc module issue not the dkim as the error meant.
Thanks @moisseev
