### ISSUE TITLE
Implement TCP_NODELAY for rspamd_proxy 

### ISSUE THREAD

**Issue by mpizzoli** [vstakhov/rspamd#1790]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3

### Operation system, CPU, memory and environment:
RHEL7

### Description (Please provide a descriptive summary of the issue):
I am currently unable to reach the maximum amount of available cpu with rspamd. I am using rspamd only for dkim-signing outgoing emails and it is really fast. But still not as fast as to keep pace with my bulk sendings: 250K emails in a row.
I have the strong feeling that it is due to the latency between postfix and rspamd, via tcp-loopback.
I have found different threads discussing how the by-default-enabled Nagle algorithm plays an important role for this specific use-case.

I see that the TCP_NODELAY socket flag is activated in rspamd only for HTTP and redis connections:
https://github.com/vstakhov/rspamd/search?utf8=%E2%9C%93&q=tcp_nodelay&type=

I guess it would be useful for the proxy as well, at the very minimum when used on tcp-loopback.

I am currently facing latency issues between the (ultra-fast) rspamd and Postfix.
At least getting rspamd to set the TCP_NODELAY receiving-socket option would hopefully be of help.

### Compile errors (if any):
N/A

### Steps to reproduce:
Just heavily send emails to postfix smtpd and see that the cpu consumption does not grow over a somewhat fixed limit. Even when increasing the number of rspamd proxy workers.

### Expected results:
Being able to stress the cpu at its maximum and eventually increasing my output 

### Actual results:
Maximum 35% of a single CPU consumed by rspamd. No matter the number of proxy processes running.

### Configuration:
N/A

### Additional information:
I know I could just get rid of tcp and relying on unix socket domain, but I rather keep everything tcp based, so to ease the separation of components onto different (remote) servers in case of need, without need to alter the conceptual setup. 
In addition to that, #1740 and #1708 are still unsolved.

I can provide other info if necessary.

**Comment by vstakhov** [comment]
I have strong doubts that it is somehow related to TCP_NODELAY. How do you use Rspamd (e.g. proxy or direct modes)? What does `perf top` shows? What is Postfix  CPU consuming?

Regarding #1740 and #1708 the answer is trivial: no dumps or no ways how to reproduce it -> no fix.

**Comment by mpizzoli** [comment]
Hello @vstakhov,
Yes, mine are only supposition. The only fact is I can't maximise the cpu utilization.

I use self-scan mode. Initially I had only 1 proxy process, and I reached only 35% of cpu with it.
I moved to 3 proxy processes and I got to still 35% of cpu consumed by rspamd proxy processes, only distributed among the 3 processes.

My consideration was started, between the others, by this old thread:
http://list.postfix.users.narkive.com/kNo0GOkl/dkim-milter-signing-terribly-slow-with-postfix-but-not-with-sendmail
Starting from that I read a lot about the benefits of the TCP_NODELAY options for *these specific cases*.

This article was a big clue: 
http://www.linuxvox.com/2009/11/what-is-the-linux-kernel-parameter-tcp_low_latency/

I also found this redhat article interesting: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_MRG/1.2/html/Realtime_Tuning_Guide/sect-Realtime_Tuning_Guide-Application_Tuning_and_Deployment-TCP_NODELAY_and_Small_Buffer_Writes.html

I will use "perf top" during next bulk-sending, in September, and I will report it.

Postfix has been heavily tuned. Just to give an example, I found I needed haveged in order to lower the cpu consumption for (i.e.) ssl. The cpu is really low now and I have no disk I/O latency (almost no i/o wait in the cpu seen with "top").
I can effectively send 100K emails out in 1h, still using ssl whenever possible and of course being all of them dkim-signed.

My consideration about the 2 still-open tickets is only to say that I rather avoid the risk of getting issue with unix socket domains, should it eventually really be a bug in rspamd instead of just an external problem of the reporter's system. I hope you did not get me wrong, even if my words were not so clear about that.

**Comment by vstakhov** [comment]
Again: what is the output of `perf top`?

**Comment by mpizzoli** [comment]
As I wrote before: I will use "perf top" during my next bulk-sending, in September, and I will report it.

**Comment by vstakhov** [comment]
It is very hard to test performance issues without actually testing them. After some thinking, I suppose that TCP_NODELAY might improve the performance. But I don't understand, for instance, the current issues with the Unix sockets. And I don't want to add something that is completely not tested by anybody.

**Comment by mpizzoli** [comment]
Your point is fully understandable.

You just remind that my request was to enable TCP_NODELAY *at least* when rspamd is listening on 127.0.0.1.

What I can do is trying enabling  `echo 1 > /proc/sys/net/tcp_low_latency`, so setting the TCP_NODELAY setting system wide and comparing the behaviour.
My only "difficulty" is that the bulk-sending I am referring to happens approx once per month, so it will take a while before I can produce actual data. 

I will be back on this with meaningful data.

**Comment by vstakhov** [comment]
From your description, it is most likely that Postfix just cannot feed Rspamd with enough amount of messages by some reason. Perhaps, there are not enough of `smtpd` children? Why cannot you do this test artificially: generate some amount of messages, and send them to sign routing to `/dev/null` via smarthost.

**Comment by mpizzoli** [comment]
At the beginning I thought the same, but during the bulk-sending I see running at least 3 smptd processes. My postfix configuration says to permit until 10 smtpd processes.

The artifical test you are saying, maybe I could do it but I need you to provide me with all the technical details. It is a scenario I am really inexpert.

**Comment by vstakhov** [comment]
Both 3 and 10 smtpd processes are not enough to feed Rspamd robustly.

**Comment by mpizzoli** [comment]
Hi @vstakhov,
I had a half-bulk-sending and I can confirm that the real issue was the client not supplying enough email-per-second to the mail server. I managed to get 8 network connections from the client to the mail server and I effectively got rspamd proxy processes cumulative spending 60% of a single cpu, so twice as before.
