### ISSUE TITLE
DMARC reports Content-Type bug

### ISSUE THREAD

**Issue by gibzer** [vstakhov/rspamd#1793]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3
### Operation system, CPU, memory and environment:
Ubuntu 16.04 LTS Server x64
### Description (Please provide a descriptive summary of the issue):
Rspamd sends DMARC reports with incorrect MIME Content-Type.
### Configuration:
```
*** Section dmarc ***
reporting = true;
send_reports = true;
report_settings {
    org_name = "...";
    domain = "...";
    email = "...";
}

*** End of section dmarc ***
```
### Additional information:
Thenderbird doesn't see attachment in DMARC report mail. Apple mail does.

Rspamd uses ```Content-Type: multipart/alternative``` which is incorrect type for mails with attachments. Better to use ```Content-Type: multipart/mixed```. Also maybe would be better to add file name option, e.g. ```Content-Type: text/xml; name="example.com!aol.com!1502064000!1502150400.xml"``` instead of just ```Content-Type: text/xml```.

**Comment by vstakhov** [comment]
`name` is not needed since it is already in `Content-Disposition` header.
