### ISSUE TITLE
rspamd_http and HTTP methods

### ISSUE THREAD

**Issue by Menta2L** [vstakhov/rspamd#1801]
* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

I am not sure that may exist as an option but i cant find a way to do it.

I am traing to create a meta exporter plugin for elasticsearch. For that i need to be able to send HEAD and PUT requests via rspamd_http 
So far i noticed that if there is a body request is created via POST method and if there is no body its a GET.
Is it possible somehow to tell rspamd_http what method to use ?

**Comment by Menta2L** [comment]
I find out how to do it. Actually if you put method="head" do the job. You can close the issue.
In addition to that, I like to share that elasticsearch plugin with the community maybe it may be useful for someone.
Here is a link to the repository [rspamd-elastic](https://github.com/Menta2L/rspamd-elastic)

**Comment by vstakhov** [comment]
That looks great, thank you! By the way, I could include your plugin to the official Rspamd distribution if you change license to Apache 2. Unfortunately, I cannot include GPLv3 code so far.

**Comment by Menta2L** [comment]
I changed the license. The plugin is not 100% ready still have some work to do. But probably in 1-2 days will be ready for production use and will be glad if you include it into rspamd distribution.

**Comment by vstakhov** [comment]
Cool, thank you very much! I'll definitely review the plugin before inclusion, no worries :)

**Comment by Menta2L** [comment]
I noticed that if I use 
``` 
rspamd_config:add_on_load(function(cfg, ev_base)
...
end
```
the code inside that  add_on_load is executed for each worker. I guess that each plugin is loaded for each worker and for each child of that worker.

Are there a way to execute a script just once for entire rspamd instance.

The use case is that I like to import some settings create some indeces and templates just once. Kind of prepare the plugin for a first run.

**Comment by fatalbanana** [comment]
You can limit execution to a single worker inside such a function: 
```
rspamd_config:add_on_load(function(cfg, ev_base, worker)
  if not (worker:get_name() == 'normal' and worker:get_index() == 0) then return end
```

**Comment by fatalbanana** [comment]
This module has been included into the distribution. Thank you very much for your work on it @Menta2L
