### ISSUE TITLE
symbol RCVD_VIA_SMTP_AUTH inserted when message is not from authenticated connection

### ISSUE THREAD

**Issue by jirireischig** [vstakhov/rspamd#1825]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3

### Operation system, CPU, memory and environment:
CentOS 7 - sendmail, CentOS 6 - postfix

### Description (Please provide a descriptive summary of the issue):
Symbol RCVD_VIA_SMTP_AUTH inserted/used when message is not from authenticated smtp connection.

### Expected results:
Symbol RCVD_VIA_SMTP_AUTH inserted/used only if message is send by authenticated user.

**Comment by vstakhov** [comment]
A message sample is required for this sort of issues: we are not telepaths.

**Comment by fatalbanana** [comment]
`RCVD_VIA_SMTP_AUTH` tells that `Received:` headers suggest an authenticated hand-off having happened somewhere, not that an authenticated hand-off is taking place.

~~~lua
-- /etc/rspamd/rspamd.local.lua
rspamd_config.IS_AUTHED = {
  callback = function(task)
    return task:get_user() and true or false
  end,
  score = 0.0,
}
~~~

**Comment by jirireischig** [comment]
I'm sorry, it's look like my fault. I don't understand description (Message injected via SMTP AUTH) very well.
The lua code is look like better solution for I'm looking for. Thank you fatalbanana.
