### ISSUE TITLE
centos 7 does not start after installation, logdir ownership wrong

### ISSUE THREAD

**Issue by kristous** [vstakhov/rspamd#1826]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rspamd-1.6.3-1.x86_64

### Operation system, CPU, memory and environment:
CentOS Linux release 7.3.1611 (Core) 

### Description (Please provide a descriptive summary of the issue):
Sep  7 13:22:02 mail2 rspamd: open_log: cannot open desired log file: /var/log/rspamd/rspamd.log, Permission deniedFatal error, cannot open logfile, exiting

chown _rspamd:_rspamd /var/log/rspamd
fixes the problem

### Steps to reproduce:
Install on centos 7

**Comment by fatalbanana** [comment]
Should be fixed already but we need to roll new packages.

Related to #1696
