### ISSUE TITLE
Calling task:get_protocol_reply() breaks milter headers

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#1827]
### Classification (Please choose *one* option):

* [X] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
master

### Description (Please provide a descriptive summary of the issue):
If task:get_protocol_reply() has been called task:set_milter_reply() won't work (I suppose cached response is used without alteration).

### Steps to reproduce:
Add the following to rspamd.local.lua:

~~~
rspamd_config.BREAK_MILTER_HEADERS = {
  callback = function(task)
    task:get_protocol_reply()
  end,
  type = 'postfilter'
}
~~~

### Expected results:
no change

### Actual results:
milter block is absent in protocol response

**Comment by vstakhov** [comment]
In fact, you shouldn't call this method anywhere but in idempotent post-filters (meaning that the task is completely finished).

**Comment by fatalbanana** [comment]
Ok, it's no worry I suppose.

I thought about applying stuff from here in `milter headers` module but we don't really need it.
