### ISSUE TITLE
Is it possible to add words, in rspamd

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#1831]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3
### Operation system, CPU, memory and environment:
Ubuntu
### Additional information:
I use Zimbra
As the developer of RSPamd know, a Zimbra administrator integrated your application with Zimbra, it's great.
vstakhov, as you can know, spammers no longer pass via bad IP reputation but through neutral addresses see Good.
Somewhere in your application, is it possible to add words, example, sex, big breast, pussy, etc ....
Good to you
Mz

**Comment by mxoneil** [comment]
In the local.d/multimap.conf add:
reject_content {
  type = "content";
  filter = "full";
  map = "${LOCAL_CONFDIR}/local.d/content.map";
  symbol = "REJECT_CONTENT";
  prefilter = true;
  action = "reject";
  regexp = true;
}

In the content.map: /local.d/content.map add
#content filter
/\bBreasts\b/i
(blank line)
The blank line at the end is REQUIRED.
Restart rspamd, from then on any modifications to the content.map will automatically be read instantly!

**Comment by MisterM74** [comment]
Hello
I have a bug, attachment, PDF, it blocks
surprisingly, in the there is no word that is relative in the content.map file.
When I disable this feature, the attachment sends.

Mz

**Comment by mxoneil** [comment]
The content map only checks the header and body of the email, not any attachment. There is something else causing your issue, is my guess.

**Comment by vstakhov** [comment]
No, it checks for full mime decoded content that includes attachments.

**Comment by MisterM74** [comment]
hello

Here is an example in the logs, when I send with attachment in PDF format, the worst is that, with the same file in JPG format, it sends itself without problem ...

> E9B7E125DC4: milter-reject: END-OF-MESSAGE from localhost[127.0.0.1]: 5.7.1 Matched map: REJECT_CONTENT; from=<mail@domain.com> to=<mail@domain.be> proto=ESMTP helo=<localhost>

Mz

**Comment by MisterM74** [comment]
Hello
I found the bug, adding the word "sex", that's why my attachments in PDF format, Jpg (I was wrong last time, but blocked as synonymous), Gif, or other Graphic formats blocked at sending.

Here is

For info, I use Zimbra vstakhov

Mz

**Comment by vstakhov** [comment]
Set filter to `text` for this map.

**Comment by MisterM74** [comment]
We can close the subject because it works now .. thanks  vstakhov
Mz

**Comment by lutjebroeker** [comment]
Is there a page where the code is explaind.
Like what the "/\b" and "\b/i"mean?

And what if you want to use 2 words like "spy drones".
Is that possible?
