### ISSUE TITLE
7zip support for archives

### ISSUE THREAD

**Issue by andryyy** [vstakhov/rspamd#1833]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [X] Feature
* [ ] Enhancement

### Rspamd version:

Next 👍 

### Expected results:

Support more archives. 😃

**Comment by vstakhov** [comment]
It is implemented now.

**Comment by andryyy** [comment]
Thanks!
