### ISSUE TITLE
Mention versions covered by the documentation 

### ISSUE THREAD

**Issue by 1358** [vstakhov/rspamd#1837]
rspamd is under heavy development. Please make it easier to guess which part of the documentation is usable for the version that is currently in use.

eg: the current doc mentions rmilter (which is obviously obsolated since v1.6) at several places and describses configuration-schemes using rmilter.

Please consider mention directly on the user documentation page the version(s) covered by said documentation. That's a useful information in itself, and (especially when expressed fully written out, not abbreviated like 0.7.x-0.9) is useful for packagers to make the packaging fail if manually extracted documentation does not match version of code.

Also, please consider including the source of documentation together with the source of code. One way I can imagine that done without too much interruption of current workflow is by registering the website branch as a git submodule at the master branch - e.g. at subdir "docs" or "website", and then sync and include that submodule when finalizing releases.

**Comment by vstakhov** [comment]
For the vast majority of new features, there is a mention about the version where that specific feature has appeared. There are also expiration notices about features being removed. I will not likely distribute documentation with the source code, as it is complicated task for no good reason. Regarding other suggestions I always prefer pull requests to suggestions... Rspamd.com site lives in a dedicated github repo: https://github.com/vstakhov/rspamd.com.
