### ISSUE TITLE
Rspamd doesn't send Attachments to ClamAV.

### ISSUE THREAD

**Issue by gangsterrapper22** [vstakhov/rspamd#1840]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.4
### Operation system, CPU, memory and environment:
Debian 9 (x64)
### Description (Please provide a descriptive summary of the issue):
Rspamd doesn't sent the attachments to ClamAV. I tested it also with test mails from eicar.com but they doesn't get detected and also in the rspamd.log I see nothing from ClamAV. I have also set the Logging to debug and searched for "ClamAV" but nothing is found in the Logs.
### Steps to reproduce:
Sent E-Mails from eicar.com or other attachments to ClamAV.

### Expected results:
The attachments should be sent from Rspamd to ClamAV for Virus Check.

### Actual results:
The Files which are sent by any E-Mails doesn't get scanned by ClamAV.

### Configuration:
rspamadm configdump antivirus
*** Section antivirus ***
clamav {
    attachments_only = true;
    symbol = "CLAM_VIRUS";
    type = "clamav";
    patterns {
        JUST_EICAR = "^Eicar-Test-Signature$";
    }
    whitelist = "/etc/rspamd/antivirus.wl";
}
first {
    attachments_only = true;
    symbol = "CLAM_VIRUS";
    type = "clamav";
    servers = "127.0.0.1:3310";
    patterns {
        JUST_EICAR = "^Eicar-Test-Signature$";
    }
    whitelist = "/etc/rspamd/antivirus.wl";
}

*** End of section antivirus ***

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd

**Comment by vstakhov** [comment]
No feedback, closing.
