### ISSUE TITLE
dkim validation failures on mails with multiple signatures

### ISSUE THREAD

**Issue by sergeev917** [vstakhov/rspamd#1841]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3
### Operation system, CPU, memory and environment:
gentoo linux amd64, intel core i5-2320, 16gb memory
### Description (Please provide a descriptive summary of the issue):
R_DKIM_REJECT symbol appears on messages with multiple dkim signatures.
### Compile errors (if any):
None.
### Steps to reproduce:
Cannot reproduce with the target domain since key material is missing. So far haven't tried on a test domain. Cannot disclose the sample since it contains private information.
### Additional information:
I'm getting R_DKIM_REJECT symbols on messages from a particular domain running ms exchange 2010. It signs its mail 2 times for some reason, thus there are two DKIM-Signature headers with timestamps (t=<...>) which are apart in couple of seconds.

An interesting moment is that I'm getting only R_DKIM_ALLOW when the only one signature is kept.
```
# original, with 2 signatures
# cat dkim-failure-sample.email | rspamc --connect /run/rspamd/rspamd.sock symbols
<...>
Symbol: ARC_NA (0.00)
Symbol: DKIM_MIXED (0.00)
Symbol: DMARC_POLICY_ALLOW (0.00)[example.com, none]
Symbol: DMARC_POLICY_ALLOW_WITH_FAILURES (-0.50)
Symbol: R_DKIM_ALLOW (-0.20)[example.com]
Symbol: R_DKIM_REJECT (0.00)[example.com]
<...>
# with the first or the second signature header removed (ie only one signature is kept)
<...>
Symbol: ARC_NA (0.00)
Symbol: DMARC_POLICY_ALLOW (-0.25)[example.com, none]
Symbol: R_DKIM_ALLOW (-0.20)[example.com]
<...>
```

Thus, DKIM is successfully validated on each of signatures individually, but when two signatures are present -- the second one gets R_DKIM_REJECT. This is the second one to fail even when I swap signature headers, thus it seems the problem with number of signatures and not their content (unless headers are sorted before processing). Also, there is no problem when two signature headers are identical. 

Where should I go from here? Is this information is enough for looking into it?
Also, I can somewhat quickly test a patch on samples, but unfortunatelly cannot provide the samples themselves.

**Comment by sergeev917** [comment]
It's actually always reproducable on the captured samples.

**Comment by fatalbanana** [comment]
I can't replicate that; it seems one of the signatures are really bad - in which case this is the expected behaviour.

**Comment by sergeev917** [comment]
@fatalbanana I've just re-checked to be sure.

`rspamc` returns only R_DKIM_ALLOW on each signature separatelly (ie I removed the first one from the source and ran `rspamc`, then removed the second one from the source and ran `rspamc` again).

**Comment by sergeev917** [comment]
@fatalbanana That is, it seems that both signatures are valid. Also, `dkimpy` returns `signature ok` on all samples (both signatures present and each signature on its own).

**Comment by fatalbanana** [comment]
I can't replicate that. We probably need a message sample.

~~~
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=org.org.za;
 q=dns/txt; s=email; bh=yGIXoM91E1DiKjvCBcC8NlWyw54TdfMQ08sdtwtOO4I=;
 h=from:to:content-type;
 b=N7O6hRT79EPrXqyo8nZjlcf+/hZ1SNddrtzxpcfWC2fFm6i7vyNCsVXcvtkHZICqg0yaXb9ZKABE
 HC5HyjKjfPdhd4ob5DsIscFy3ReHtwUtlo6NcnW6EucqWrtwEWCaIOTHQEi6zrVrYavRLRd6MYtu
 lMp9s3niqVYfzE1Rs0M=
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=judo.za.org;
 q=dns/txt; s=email; bh=yGIXoM91E1DiKjvCBcC8NlWyw54TdfMQ08sdtwtOO4I=;
 h=from:to:content-type;
 b=LgxQM1xTSi1kwTlnC5+RglZJ123CMfw1m29/0Rkbuq+XRVxtZicYDAJumevCPMfz0Un6HmfzIOJa
 H5u3yjdOnvXf/zfYT+OodUI6eEuq5C3W9ZA4r2CxKSBIUC52MckrEsexaxbfPlF6K/TdQ6vGe21O
 CKYguG1l8gnxIsIDESM=
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=org.org.za;
 q=dns/txt; s=email; bh=yGIXoM91E1DiKjvCBcC8NlWyw54TdfMQ08sdtwtOO4I=;
 h=from:to:content-type;
 b=N7O6hRT79EPrXqyo8nZjlcf+/hZ1SNddrtzxpcfWC2fFm6i7vyNCsVXcvtkHZICqg0yaXb9ZKABE
 HC5HyjKjfPdhd4ob5DsIscFy3ReHtwUtlo6NcnW6EucqWrtwEWCaIOTHQEi6zrVrYavRLRd6MYtu
 lMp9s3niqVYfzE1Rs0M=
From: donkey <donkey@judo.za.org>
To: donkey <donkey@judo.za.org>
Message-ID: <dingo@dingo.dingo>
Date: Thu, 18 Jun 2015 13:42:09 +0000 (UTC)
Content-type: text/plain

Hello world
~~~

**Comment by sergeev917** [comment]
Could you try `simple/simple` canonicalization and sign headers `h=from:subject:to:date:message-id`?

**Comment by fatalbanana** [comment]
I would suggest e-mailing yourself to create a suitable message sample. If you don't want to post that here you could send it PGP-encrypted to vsevolod@highsecure.ru.

**Comment by sergeev917** [comment]
Well, the problem is that it was an incoming message from an unrelated domain which runs a different software stack (ms exchange) and I can't easily send a message from there nor can have its dkim keys.

I will try to recreate a suitable sample for now (with a fallback to the present samples in some time).

**Comment by sergeev917** [comment]
@fatalbanana the sample is sent.

**Comment by vstakhov** [comment]
I understand the issue. A fix will be shortly available.
