### ISSUE TITLE
per_user bayes and redis: LUA script not executed

### ISSUE THREAD

**Issue by cite** [vstakhov/rspamd#1843]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.4
### Operation system, CPU, memory and environment:
Debian 9.1/, Intel Xeon E312xx (Sandy Bridge), 4GiB, x86_64
### Description (Please provide a descriptive summary of the issue):
Trying to use a `per_user` LUA function in the `bayes` classificator in `local.d/statistic.conf` doesn't work, the code is never executed:

```
    per_user   = <<EOD
return function(task)
    local logger = require 'rspamd_logger'
    local rcpt = task:get_recipients(1)

    if rcpt then
        first_rcpt = rcpt[1]
        if first_rcpt['domain'] and first_rcpt['addr'] then
            if first_rcpt['domain'] == 'example.com' and not(first_rcpt['addr'] == 'exempt@example.net') then
                logger.warnx('bayes per-user: %1', first_rcpt['addr'])
                return first_rcpt['addr']
            else
                logger.warnx('bayes per-user: STATIC')
                return 'exempt@example.net'
            end
        end
    end

    logger.warnx('bayes per-user: NULL')
    return nil
end
EOD
;
```

However, putting the same code in `local.d/redis.conf` seems to work - not sure if this is inteded behaviour, since the [documentation](https://rspamd.com/doc/configuration/statistic.html) says otherwise.

**Comment by cite** [comment]
I upgraded to the rspamd 1.5 release this night, however, it seems that the classifier scripts are still not loaded. Is there anything I need to change with my configuration?

**Comment by fatalbanana** [comment]
It should work as documented but I'm afraid it does not.

**Comment by cite** [comment]
Any news on this?

**Comment by fatalbanana** [comment]
It seems to be working as expected now.
