### ISSUE TITLE
rspamd: headers being added at the very end of header block (affects MIME/PGP)

### ISSUE THREAD

**Issue by Yuubari** [vstakhov/rspamd#1844]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.4

### Operation system, CPU, memory and environment:
FreeBSD 11-STABLE, amd64, 24 GB RAM, MTA is Postfix, rspamd milter configuration is as provided in the documentation.

### Description (Please provide a descriptive summary of the issue):
rspamd adds its headers below every other header in the message.

### Steps to reproduce:
Receive an email from an SPF/DKIM enabled relay; or
Send an email from a domain with DKIM signing enabled to any recipient.

### Expected results:
`Authentication-Results` and `DKIM-Signature` (along with other related headers save for `X-Spam` stuff) are inserted *before* every other header (usually after the `Received` header) to keep the header chain in its MTA processing order.

### Actual results:
The headers are inserted *after* the presumed-last header line in the main header block, without regard for MIME and PGP.
Examples:

Sent mail:
```
To: some address at gmail
From: "someone" <someone at DKIM signed domain>
Subject: Test
Message-ID: <b87f7e5d-3678-6d6d-2e41-a1217b380ffb@DKIM signed domain>
Date: Sat, 23 Sep 2017 19:20:55 +09:00
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101
 Thunderbird/52.3.0
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="nRkmTjRiMlHfbbwfiXJQHoM0heCpkfxwV"
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; ...
```
Received mail:
```
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101
 Thunderbird/52.3.0
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Content-Language: en-GB
Authentication-Results: mail.koumakan.jp; dkim=pass header.d=gmail.com; dmarc=pass policy=none header.from=gmail.com; spf=pass smtp.helo=mail-lf0-f49.google.com
```

### Configuration:
Default, but with Authentication-Results headers and DKIM signing enabled.

### Additional information:
This behaviour does not conform to the behaviour observed for basically every other DKIM/SPF/etc. verifying/signing software. This breaks PGP verification in some cases since PGP may include headers in the verification process. This also breaks MIME in some clients (and libraries).
For example, OpenDKIM's milter inserts `DKIM-Signature` headers *before* every other header in the message (ending up after the `Received` header of the processing server).

**Comment by vstakhov** [comment]
I don't understand the problem. What are 'some cases'? How MIME is broken? So far, I have completely no intention to change the headers insertion logic. In theory, it is possible but you have not convinced me that it is anyhow useful.

**Comment by Yuubari** [comment]
In PGP/MIME-signed messages the headers added by rspamd are inserted after the main From/To/Subject header block which leads to checksum mismatches if a PGP/GnuPG-capable mailer is configured to include headers (usually done to prevent unauthorised insertion of Reply-To and CC/BCC headers).

In certain older MIME-supporting clients (including IRIX Interactive Desktop's) the MIME objects are not parsed correctly when a non-MIME-related header is added after MIME-Version and Content-Type.

However, I do understand your stance regarding this issue so I will be closing it and switching back to OpenDKIM and the likes. Thank you for the prompt response.

**Comment by Yuubari** [comment]
One last point:

https://tools.ietf.org/html/rfc4871 says:

5.7 Insert the DKIM-Signature Header Field

Finally, the signer MUST insert the DKIM-Signature header field created in the previous step prior to transmitting the email. The DKIM-Signature header field MUST be the same as used to compute the hash as described above, except that the value of the "b=" tag MUST be the appropriately signed hash computed in the previous step, signed using the algorithm specified in the "a=" tag of the DKIM-Signature header field and using the private key corresponding to the selector given in the "s=" tag of the DKIM-Signature header field, as chosen above in Section 5.2

**The DKIM-Signature header field MUST be inserted before any other DKIM-Signature fields in the header block.**

INFORMATIVE IMPLEMENTATION NOTE: **The easiest way to achieve this is to insert the DKIM-Signature header field at the beginning of the header block. In particular, it may be placed before any existing Received header fields. This is consistent with treating DKIM-Signature as a trace header field.**

But of course you are free to not follow the standard.

**Comment by Yuubari** [comment]
Regarding Authentication-Results: 

https://tools.ietf.org/html/rfc7601 states:

   As stated in Section 2.1, **this header field MUST be treated as though it were a trace header field as defined in Section 3.6.7 of [MAIL] and hence MUST NOT be reordered and MUST be prepended to the message, so that there is generally some indication upon delivery of where in the chain of handling MTAs the message authentication was done.**

**Comment by andryyy** [comment]
He asked for a reason to fix it. That was just... a drama.

I have not seen a pgp plugin/mailer that is unable to handle something so trivial. But I also don’t know IRIX interactive desktop.

**Comment by vstakhov** [comment]
RFC states about other DKIM signatures and not about PGP or any other stuff. However, for multiple DKIM signatures, Rspamd logic is broken indeed. I will fix it.

**Comment by Yuubari** [comment]
The MIME/PGP stuff is merely a consequence of these headers appearing in non-standard places. If the signature and the Authentication-Results header are moved to their rightful places at the start of the headers, the issues w/MIME will automatically be resolved.

**Comment by vstakhov** [comment]
Well, that should be fixed in master (DKIM part). Auth-Results should also be fixed in somehow same matter. However, I'm not 100% sure that it won't break something else... In theory, we need to find another header with DKIM-Signature/Authentication-Results names and prepend our header before them. That should be the safest transition...

**Comment by Yuubari** [comment]
The RFC for DKIM straight up recommends placing the signature at the very top of the message, as I quoted above under “INFORMATIVE IMPLEMENTATION NOTE”. Just sticking it at the top of all headers, before any of `Received`, is good enough.

`Authentication-Results` is, however, a tough case due to RFC requirements: if rspamd is adding it, it must remove any such headers claiming to be originating from rspamd site's zone of trust, unless from a trusted relay.

**Comment by vstakhov** [comment]
I don't care what RFC recommends. I do care what can it break if being changed. And my experiences tell me that many DKIM verification tools are just broken in multiple places.

**Comment by jeredfloyd** [comment]
This was noted fixed on Sep 23 but doesn't appear to be active in 1.6.5.  What release contains the fix for headers being inserted at the bottom of the header block?

**Comment by FingerlessGlov3s** [comment]
I'm on 2.5 and its still inserting it at the bottom, is there a variable I need to set?

@jeredfloyd did you get anywhere with it?

**Comment by strangePo** [comment]
Same here. All headers are appended at the end of the headers instead of being inserted at the appropriate place like for example spamassassin does.
Is there any fix available?

**Comment by vstakhov** [comment]
With milter interface?

**Comment by strangePo** [comment]
Yes

**Comment by vstakhov** [comment]
It cannot be, you do something wrong.

**Comment by strangePo** [comment]
I don't see how I could do something wrong.
RSpamd is configured as milter in postfix

`smtpd_milters=inet:localhost:11332`

For testing purposes i have activated extended headers and disabled the skip flags.

```
# cat override.d/milter_headers.conf
extended_spam_headers = true;
```

Here relevant local configs

```
# cat worker-proxy.inc
bind_socket = "localhost:11332";
milter = yes;
timeout = 120s;
upstream "local" {
    default = yes;
    self_scan = yes;
}
count = 4;
max_retries = 5;
discard_on_reject = false;
quarantine_on_reject = false;
spam_header = "X-Spam-Flag";
reject_message = "Spam message rejected";
```

```
milter_headers.conf
authenticated_headers = ["authentication-results"];
use = ["x-spamd-result","x-spam-level","x-spamd-bar", "x-spam-status", "authentication-results"];

skip_local = false;
skip_authenticated = false;
skip_all = false;
```

**Comment by vstakhov** [comment]
Are we talking about dkim signature or about some other stuff?

**Comment by strangePo** [comment]
I'm talking about all headers added by RSpamd.

See this test Email:

```
Return-Path: <support@example.com>
Received: from mail01.example.com (127.0.0.1:40786)
	by mail01 (kopano-dagent) with LMTP;
	Thu, 11 Feb 2021 11:32:27 +0100 (CET)
Received: from mail01.example.com (localhost [127.0.0.1])
	by mail01.example.com (Postfix) with ESMTP id EE19B14094A1
	for <support@example.com>; Thu, 11 Feb 2021 11:32:26 +0100 (CET)
Received: from localhost (localhost [127.0.0.1])
	by mail01.example.com (Postfix) with ESMTP id 834A314096D1
	for <support@example.com>; Thu, 11 Feb 2021 11:32:26 +0100 (CET)
X-Virus-Scanned: by amavisd-new-2.10.1 (20141025) (Debian) at example.com
Received: from mail01.example.com ([127.0.0.1])
	by localhost (mail01.example.com [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id 73p3X1wZbvXq for <support@example.com>;
	Thu, 11 Feb 2021 11:32:21 +0100 (CET)
Received: from mail01.example.com (localhost [127.0.0.1])
	by mail01.example.com (Postfix) with ESMTP id 3127C14094A1
	for <support@example.com>; Thu, 11 Feb 2021 11:32:21 +0100 (CET)
Received: from mx00.example.com (cipher01.example.com [10.0.5.1])
	by mail01.example.com (Postfix) with ESMTP id 0B24E14094A1
	for <support@example.com>; Thu, 11 Feb 2021 11:32:21 +0100 (CET)
Date: Thu, 11 Feb 2021 11:32:20 +0100
From: support@example.com
To: support@example.com
Subject: test example
Message-ID: <20210211103220.Lbpdd%support@example.com>
User-Agent: s-nail v14.9.11
MIME-Version: 1.0
X-Spamd-Result: default: False [1.00 / 99.00];
	 ARC_NA(0.00)[];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 MIME_GOOD(-0.10)[text/plain];
	 PREVIOUSLY_DELIVERED(0.00)[support@example.com];
	 TO_DN_NONE(0.00)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 RCVD_COUNT_THREE(0.00)[4];
	 FROM_NO_DN(0.00)[];
	 MID_CONTAINS_FROM(1.00)[];
	 RCVD_NO_TLS_LAST(0.10)[];
	 FROM_EQ_ENVFROM(0.00)[];
	 TO_EQ_FROM(0.00)[];
	 MIME_TRACE(0.00)[0:+]
Authentication-Results: mail01.example.com;
	none
X-Rspamd-Server: mail01
X-Spamd-Bar: +
X-Rspamd-Queue-Id: 834A314096D1
X-Spam-Level: *
X-Spam-Status: No, score=1.00
```

**Comment by vstakhov** [comment]
And this ticket is about DKIM signature which is placed now according to RFC. Other headers are placed at the end of the headers and this is intended behaviour (I don't care what spamassassin does tbh).

**Comment by strangePo** [comment]
Actually the Issues description is about header being placed at the end (not specifically dkim only), hence i added my observations here instead of opening a new issue with basically the same subject.

I didn't mention spamassassin because i would like rspamd to behave as spamassassin does but to give an example.
IMHO the headers should be placed at the position in the chain where the scan happens so that every one can spot at which point they were added. Does this make sense to you?

**Comment by vstakhov** [comment]
Please open a separate issue: this is mostly about dkim-signature from what I see above. The order of headers could be easily changed and made as a configurable option: but I'm very reluctant about changing the default behaviour as it can break compatibility.

**Comment by strangePo** [comment]
Done. Thanks.
