### ISSUE TITLE
rspamd_trie lua module

### ISSUE THREAD

**Issue by fan51degrees** [vstakhov/rspamd#1849]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Last

### Description (Please provide a descriptive summary of the issue):
Is it possible to build only rspamd_trie lua module and use it without others features ?
I would like to use it like here:
https://rspamd.com/doc/lua/trie.html
but I can't require this module to my lua script.
.

**Comment by fatalbanana** [comment]
APIs in Rspamd are generally tied to Rspamd. `rspamd_trie` module works in `rspamadm lua` (where `task` isn't required).

Supposing you want to use some other Lua host there are [other](https://github.com/jgrahamc/aho-corasick-lua) [options](https://github.com/cloudflare/lua-aho-corasick).
