### ISSUE TITLE
Problem with redis on Port 0

### ISSUE THREAD

**Issue by ttjaden** [vstakhov/rspamd#1856]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.4

### Operation system, CPU, memory and environment:
VM with Ubuntu Server 16.04.3, 2 CPU, 4GB RAM

### Description (Please provide a descriptive summary of the issue):
The history in rspamd doesn't work! There is a problem with redis.

### Steps to reproduce:
My server works for MAIL and NEXTCLOUD. For Nextcloud I had to install REDIS and set the following configuration in /etc/redis/redis.conf
--
port 0
unixsocket /var/run/redis/redis.sock
unixsocketperm 770
--
So now I don't know how to set up rspamd to work correctly?

### Configuration:
/etc/rspamd/local.d
--
servers = "127.0.0.1";
--

**Comment by fatalbanana** [comment]
The way to use a UNIX socket for Redis is by setting its path in the `servers` parameter.
```
servers = "/var/run/redis/redis.sock";
```
