### ISSUE TITLE
communication with 88.99.142.95

### ISSUE THREAD

**Issue by slima** [vstakhov/rspamd#1861]
### Reproducibility (Please choose *one* option):

* [X] Always

### Rspamd version:

1.6.4

### Description (Please provide a descriptive summary of the issue):

I have a question.

I saw, rspamd always comunicate with 88.99.142.95.443, what for?

**Comment by fatalbanana** [comment]
[https://github.com/vstakhov/rspamd/blob/master/conf/modules.d/multimap.conf](freemail address lists)

**Comment by slima** [comment]
Thanks you!
