### ISSUE TITLE
How do I set up the spam forwarding to the postmaster?

### ISSUE THREAD

**Issue by hxily** [vstakhov/rspamd#1862]
rspamd have this setting or rule?

**Comment by moisseev** [comment]
You can use `send_mail` backend of [metadata exporter module](https://rspamd.com/doc/modules/metadata_exporter.html#metadata-exporter).

local.d/metadata_exporter.conf:
```
rules {
    EMAIL_ALERT {
        backend = "send_mail";
        smtp = "127.0.0.1";
        mail_to = "postmaster@example.com";
        mail_from = "postmaster@example.com";
        selector = "is_spam";
        formatter = "email_alert";
    }
}
```
If you want to send full message content with metadata exporter, you can set `formatter = "default"`, but **make sure mails from metadata exporter are not scanned with Rspamd** to avoid looping.

Another option. If you don't need to forward _rejected_ spam messages you can use a sieve script like:
```
require ["mailbox", "envelope", "copy"];

if allof (header :is "X-Spam" "yes",
      not envelope "To" "postmaster@example.com") {
   redirect :copy "postmaster@example.com";
}
```

**Comment by hxily** [comment]
@moisseev thank you very much.
rspamd too strong！
