### ISSUE TITLE
headers aren't added

### ISSUE THREAD

**Issue by skytaker** [vstakhov/rspamd#1864]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

Rspamd version: 1.6.4

Centos 7.  Docker

At a certain point in time, I noticed that the headers were no longer being added to the letters, they also stopped displaying correctly in the web

**WEB-GUI**
undefined(0)
undefined(0)
undefined(0)
undefined(1)[1]
undefined(-0.2)[+a]
undefined(0)[asn:201848, ipnet:89.223.24.0/21, country:RU]
undefined(0)[1]
undefined(0)[greylisted,Mon, 16 Oct 2017 13:12:18 GMT,new record]
undefined(1)[209.25.223.89.rep.mailspike.net : 127.0.0.12]
undefined(6.5)[glass-wiper-markt.ru.dbl.spamhaus.org]
undefined(0.5)
undefined(-0.25)[olympikgame.ru,reject]
undefined(-0.2)[olympikgame.ru]
undefined(5.5)[glass-wiper-markt.ru.multi.surbl.org]
undefined(-0.1)[multipart/alternative,text/plain]
undefined(0)
undefined(0)
undefined(0)
undefined(0)[1]
undefined(0)
undefined(0)
undefined(0.1)
undefined(0)[ip: (9.90), ipnet: 89.223.24.0/21(7.92), asn: 201848(4.95), country: RU(0.87)])

**log:**
2017-10-16 18:42:00 #11(normal) <5722ee>; task; rspamd_task_write_log: id: <CD3777AF30E4C3409C99D06F0B692327@olympikgame.ru>, qid: <1e47Wh-0005oc-Mt>, ip: 89.223.25.209, from: <ifilcr@olympikgame.ru>, (default: F (soft reject): [13.35/15
.00] [DBL_SPAM(6.50){glass-wiper-markt.ru.dbl.spamhaus.org;},ABUSE_SURBL(5.50){glass-wiper-markt.ru.multi.surbl.org;},RBL_MAILSPIKE_BAD(1.00){209.25.223.89.rep.mailspike.net : 127.0.0.12;},URI_COUNT_ODD(1.00){1;},DMARC_POLICY_ALLOW(-0.25
){olympikgame.ru;reject;},R_DKIM_ALLOW(-0.20){olympikgame.ru;},R_SPF_ALLOW(-0.20){+a;},MIME_GOOD(-0.10){multipart/alternative;text/plain;},ONCE_RECEIVED(0.10){},ARC_NA(0.00){},ASN(0.00){asn:201848, ipnet:89.223.24.0/21, country:RU;},FROM
_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},GREYLIST(0.00){greylisted;Mon, 16 Oct 2017 15:47:00 GMT;new record;},IP_SCORE(0.00){ip: (9.89), ipnet: 89.223.24.0/21(7.92), asn: 201848(4.95), country: RU(0.87);},MID_RHS_MATCH_FROM(0.00){},PRECED
ENCE_BULK(0.00){},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ONE(0.00){1;},RCVD_NO_TLS_LAST(0.00){},SUBJECT_ENDS_EXCLAIM(0.00){},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 10164, time: 607.016ms real, 10.831ms virtual, dns req: 27,
 digest: <94a18f58210e91ee5709119a6b113eb3>, rcpts: <myemail@myemailaddres.ru>, mime_rcpt: <myemail@myemailaddres.ru>

**rspamd.conf**
antivirus {
    first {
    attachments_only = true;
    symbol = "CLAM_VIRUS";
        type = "clamav";
        servers = "spam_clamav:3310";
        patterns {
            JUST_EICAR = "^Eicar-Test-Signature$";
    }
    whitelist = "/etc/rspamd/antivirus.wl";
  }
}
multimap {
    local_bl_ip { type = "ip"; map = "$CONFDIR/local_lists/bl_ip.map.inc"; symbol = "LOCAL_BL_IP"; description = "LOCAL ip blacklist";}
    local_bl_from { type = "from"; map = "$CONFDIR/local_lists/bl_from.map.inc"; symbol = "LOCAL_BL_FROM"; description = "LOCAL from blacklist"; regexp = true;}
    local_wl_ip { type = "ip"; map = "$CONFDIR/local_lists/wl_ip.map.inc"; symbol = "LOCAL_WL_IP"; description = "LOCAL ip whitelist";}
    local_wl_from { type = "from"; map = "$CONFDIR/local_lists/wl_from.map.inc"; symbol = "LOCAL_WL_FROM"; description = "LOCAL from whitelist"; regexp = true;}
}

**Exim.conf**
warn  spam        = nobody:true
        condition   = ${if eq{$spam_action}{add header}}
        log_message = Possible SPAM DETECTED from $sender_host_address. $spam_score points.
        add_header  = X-Spam-Score: $spam_score
        add_header  = X-Spam-Report: $spam_report
        message     = Subject: ***SPAM*** $h_Subject:

  # use greylisting available in rspamd v1.3+
  defer message    = Please try again later
        condition  = ${if eq{$spam_action}{soft reject}}

  deny  message    = Message from $sender_host_address via $sender_address_domain discarded as high-probability spam
        condition  = ${if eq{$spam_action}{reject}}

**Comment by fatalbanana** [comment]
Supposing you defer the message, why do you care that headers are not added when action is `soft reject`? Behaviour here is governed by configuration.

If you don't intend to use greylisting disable it by adding `enabled = false` to `local.d/greylist.conf` (using `disabled_modules` in redis settings will work too).

**Comment by fatalbanana** [comment]
Rspamd cannot modify a message or directly influence its processing in your configuration - that is Exim's job which it does according to its configuration & likely the action returned by Rspamd. Supposing `$spam_action` contains something reasonable maybe something unexpected is at work in your Exim ACLs; running Exim with `-d` will give visibility into how ACLs are actually processed.

**Comment by skytaker** [comment]
I'm check exim output logs  with  exim -d-all+acl -bd, but  didn't see anything criminal. Please, can you help me to find the right direction for the solution. I am very confused by the messages about undifined maps in the web interface, although they are defined. 

![rspamd1](https://user-images.githubusercontent.com/32845561/31761585-19e9f782-b4c1-11e7-9bd5-9286187dddd0.jpg)

"Part of message"
Subject: =?utf-8?B?U1NMLdGB0LXRgNGC0LjRhNC40LrQsNGCINCyINC/0L7QtNCw0YDQvtC6IQ==?=
Date: Tue, 17 Oct 2017 09:23:35 +0300
Message-ID: <NzQwMTI5NAAC168570Y248BAMTUwODIyMTQxNTI5MzYx@newd2.ru>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_00C4_01D3472C.8B0A5680"
X-Mailer: Microsoft Outlook 14.0
Thread-Index: AQH93hkuP30b1Am3VRpHQljvXLHueQ==

This is a multipart message in MIME format.

------=_NextPart_000_00C4_01D3472C.8B0A5680
Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: base64


All parts of exim.conf including spam actions
acl_smtp_data = acl_check_content

spamd_address = rspamd 11333 variant=rspamd

acl_check_content:
  # do not scan messages submitted from our own hosts
  accept hosts = +relay_from_hosts

  # do not scan messages from submission port
  accept condition = ${if eq{$interface_port}{587}}

  # skip scanning for authenticated users
  accept authenticated = *

  # add spam-score and spam-report header when told by rspamd
  warn  spam        = nobody:true
        condition   = ${if eq{$spam_action}{add header}}
        log_message = Possible SPAM DETECTED from $sender_host_address. $spam_score points.
        add_header  = X-Spam-Score: $spam_score
        add_header  = X-Spam-Report: $spam_report
        message     = Subject: ***SPAM*** $h_Subject:

  # use greylisting available in rspamd v1.3+
  defer message    = Please try again later
        condition  = ${if eq{$spam_action}{soft reject}}

  deny  message    = Message from $sender_host_address via $sender_address_domain discarded as high-probability spam
        condition  = ${if eq{$spam_action}{reject}}

  accept


Thank you!

**Comment by fatalbanana** [comment]
That's a visual issue with WebUI that's fixed in forthcoming releases AFAIK.

**Comment by skytaker** [comment]
It's good new! But what can I do with the my main problem - no headers are added?

**Comment by fatalbanana** [comment]
I'd suggest to check what your Exim ACLs are doing in the problem cases (did it try to talk to Rspamd? did it get a result? was `$spam_action` set?- and were expected ACLs processed based on this?- why not? (something does `accept` and ends processing? something didn't match?)).

**Comment by fatalbanana** [comment]
This seems to be Exim configuration issue.
