### ISSUE TITLE
exim integration ("${if >{$spam_score}{0}}": invalid integer "3.5")

### ISSUE THREAD

**Issue by himbeere** [vstakhov/rspamd#1875]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.6.3

### Operation system, CPU, memory and environment:

Linux

### Description (Please provide a descriptive summary of the issue):

Exim integration doku suggests this setting:

```
  warn
    condition = ${if >{$spam_score}{0}}
    add_header = X-Spam-Bar: $spam_bar
```

But that leads to:

```
temporarily rejected after DATA: failed to expand ACL string "${if >{$spam_score}{0}}": invalid integer "3.5"
```

Any ideas in that?

thanks and cheers
t.

**Comment by himbeere** [comment]
Fixed for now with: condition = ${if >{$spam_score_int}{0}}

**Comment by vstakhov** [comment]
You should not use spam score when interacting with Rspamd.

**Comment by fatalbanana** [comment]
Example config is using it somehow so we should do something about that. I've pushed the suggested fix. Point of this condition is to avoid the negative spambar which may not be correctly understood.
