### ISSUE TITLE
Milter headers not removed

### ISSUE THREAD

**Issue by zeroflags** [vstakhov/rspamd#1878]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rspamd-1.6.4

### Operation system, CPU, memory and environment:
OpenBSD 6.2, more than necessary.

### Description (Please provide a descriptive summary of the issue):
E-mail headers such, as User-Agent, Received, etc. are not removed by the 'remove-header' function (or routine, or whatever you name it).

### Compile errors (if any):
Comes pre-compiled.

### Steps to reproduce:
Simply configure 'milter_filters.conf' and send an e-mail.

### Expected results:
The headers should be removed.

### Actual results:
 The headers remain untouched.

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
`# vi /etc/rspamd/local.d/milter_headers.conf`

```JSON
use = ["remove-header"];
routines {
  remove-header {
    headers {
      header = "User-Agent";
      header = "Received";
      header = "X-Originating-IP";
      header = "X-Mailer";
    }
    remove = 1;
  }
}
```

### Additional information:
Would be great to be able to specify the headers' strings in regex (the same was as postfix does),  since it's not working either.

**Comment by fatalbanana** [comment]
Hi, you want `remove-headers` (plural).

Regex won't work but you could match header names and inject actual header names to delete (using a Lua rule or Milter Headers custom routine).

**Comment by zeroflags** [comment]
Hi, thanks for your prompt reply,

but I've been there, tried that and not working. My User-Agent, Received from details (including private IPv4 address) etc. are still present in the e-mails. By the way, assuming that the syntax you suggest is correct, why does the [official documentation state otherwise](https://rspamd.com/doc/modules/milter_headers.html#remove-header)?

Anyway, I can help myself using a postfix rule. I just wanted to be somewhat useful to the Rspamd developers. Hence I pointed out that this feature is either poorly documented or not working at all. Or maybe both, no pun intended, LOL

**Comment by fatalbanana** [comment]
`remove-header` (singular) is a different routine & is configured differently; I've added `remove-headers` to docs. You can check which headers are recommended for addition/removal with `rspamc --json`.

**Comment by zeroflags** [comment]
Look mate,

1. I came up with the issue that the `remove-header` routine is not working as claimed by the [official documentation](https://rspamd.com/doc/modules/milter_headers.html#remove-header).
2. You "advised" me to use the `remove-headers` routine, which is (to the time I'm writing this comment) still [undocumented](https://rspamd.com/doc/modules/milter_headers.html#remove-headers), though you had claimed it would had been. Unfortunately, the following configuration **does not work anyway**:
```
use = ["remove-headers"];
routines {
  remove-headers {
    headers {
      header = "User-Agent";
      header = "Received";
      header = "X-Originating-IP";
      header = "X-Mailer";
    }
    remove = 1;
  }
}
```
3. In the meanwhile, I tried to configure my own routine as "advised" by the [official documentation](https://rspamd.com/doc/modules/milter_headers.html#custom-routines) as follows:
```
use = [ "my_routine"];
routines {
  custom {
    my_routine = <<EOD
return function(task, common_meta)
  -- parameters are task and metadata from previous functions
  return nil, -- no error
    {['User-Agent'] = 1}, -- remove foreign X-Foo headers
    {['Received'] = 1}, -- remove foreign X-Foo headers
    {['X-Originating-IP'] = 1}, -- remove foreign X-Foo headers
    {['X-Mailer'] = 1}, -- remove foreign X-Foo headers
    {} -- metadata to return to other functions
  end
EOD;
  }
}
```
Unfortunately, with the same result and that is, that the **headers remain untouched**.

4. As you can see, this leads to nowhere. I really tried to help the Rspamd community with my feedback, but I feel like speaking a different language, no pun intended.

**This issue is not resolved**, though I'm closing it for obvious reasons. Should anyone else struggle with this issue in the future, _Postfix_ is the best way to go in `/etc/postfix/master.cf`:
```
### For privacy reasons, remove header details provided by the MUA
submission inet n       -       y       -       -       smtpd
#...
  -o cleanup_service_name=submission-header-cleanup
#...
submission-header-cleanup unix n - n    -       0       cleanup
  -o header_checks=regexp:/etc/postfix/submission_header_cleanup
```
And the filtering options in `/etc/postfix/submission_header_cleanup` can be as follows:
```
/^Received:/            IGNORE
/^X-Originating-IP:/    IGNORE
/^X-Mailer:/            IGNORE
/^User-Agent:/          IGNORE
```
Hawk.

**Comment by fatalbanana** [comment]
> I came up with the issue that the remove-header routine is not working as claimed by the official documentation.

You were trying to use `remove-header` routine with the syntax of `remove-headers` routine.

> You "advised" me to use the remove-headers routine, which is (to the time I'm writing this comment) still undocumented, though you had claimed it would had been. Unfortunately, the following configuration does not work anyway:

You could use a [configuration example](https://github.com/vstakhov/rspamd.com/blob/master/doc/modules/milter_headers.md) I suppose.

> In the meanwhile, I tried to configure my own routine as "advised" by the official documentation as follows:

Question here is still if `rspamc` shows the headers proposed for removal or if there is issue with something else. Likely reason for headers not being manipulated is local IPs/authenticated users (there are special controls for those).

> As you can see, this leads to nowhere. I really tried to help the Rspamd community with my feedback, but I feel like speaking a different language, no pun intended.

Hmm....

**Comment by a16bitsysop** [comment]
I just had this issue and to remove headers I also needed:

skip_local = false;
skip_authenticated = false;

Or it is skipped for local and authenticated users

**Comment by OliverO2** [comment]
Can confirm @a16bitsysop's observation on rspamd 1.9.4:

Tried two different configurations of `/etc/rspamd/local.d/milter_headers.conf`:

1. This configuration succeeded in removing headers:
```
extended_spam_headers = true;
use = ["authentication-results","remove-headers"];
skip_local = false;
skip_authenticated = false;

authenticated_headers = ["authentication-results"];

routines {
    remove-headers {
        headers {
            "X-Spam-Level" = 0;
            "X-Spam-Score" = 0;
            "X-Spam-Status" = 0;
        }
    }
}
```

2. This configuration failed to remove headers:
```
extended_spam_headers = true;
use = ["authentication-results","remove-headers"];

authenticated_headers = ["authentication-results"];

routines {
    remove-headers {
        headers {
            "X-Spam-Level" = 0;
            "X-Spam-Score" = 0;
            "X-Spam-Status" = 0;
        }
    }
}
```
