### ISSUE TITLE
SA regexes are scored twice after reload/fresh start

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#1880]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5 (own build with Hyperscan & PCRE2)

### Operation system, CPU, memory and environment:
CentOS 6

### Description (Please provide a descriptive summary of the issue):
After reload or a fresh start SpamAssassin regexes get double-scoring until Hyperscan settles. Native regexp rules are unaffected.

### Steps to reproduce:
Configure some SA rule; restart/reload Rspamd & check score on scan.

### Expected results:
Symbol has assigned score

### Actual results:
Symbol has double expected score

**Comment by vstakhov** [comment]
Can you enable full task debug to check what's going on?

**Comment by fatalbanana** [comment]
```2017-10-26 11:23:30 #1986(normal) <5c98fd>; spamassassin; spamassassin.lua:1179: atom: FOO_PHARMACY_VIAGRA, result: 2```

looks relevant; that is thing that got double-scoring. I've e-mailed you full log.

**Comment by fatalbanana** [comment]
That looks to have fixed it; thank you.
