### ISSUE TITLE
[WebUI] Wrong percentage value

### ISSUE THREAD

**Issue by azurit** [vstakhov/rspamd#1886]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5 (from your Debian repositories)

### Operation system, CPU, memory and environment:
Debian Jessie, 64bit, 16 cores, 24 GB RAM

### Description (Please provide a descriptive summary of the issue):
After the login to webui, in Statistics section, there's a pie graph with correct percentage values displayed. When you move mouse cursor over parts of the graph, the WRONG percentage is displayed (like 315% instead of 35%).

**Comment by moisseev** [comment]
Would you take a screenshot?

**Comment by azurit** [comment]
I just noticed that i was wrong, data are in this formar:
number_of_messages, percentage_value

i thought it's all a percentage value in float format, closing.
