### ISSUE TITLE
LOCAL_BL_FROM weight not added

### ISSUE THREAD

**Issue by himbeere** [vstakhov/rspamd#1892]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
Linux

### Description (Please provide a descriptive summary of the issue):
I've added the blacklist/whitelist functionality from https://gist.github.com/kvaps/25507a87dc287e6a620e1eec2d60ebc1but without much success. I added an email address to local_bl_from.map.inc and configured rspamd.local.conf accordingly. But when I send an email with the blacklisted email address the regexps matched but no weight is added (LOCAL_BL_FROM(0.00)):

`2017-10-29 11:58:36 #10439(normal) <8da853>; task; rspamd_task_write_log: id: <31C882B2-5017-4373-9156-325B0626B539@lordritical.de>, qid: <1e8lIa-0002rM-KY>, ip: 88.148.83.123, from: <hoppla@lordcritical.de>, (default: F (no action): [0.00/10.00] [ARC_NA(0.00){},ASN(0.00){asn:25291, ipnet:88.148.80.0/21, country:DE;},DMARC_NA(0.00){lordritical.de;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},LOCAL_BL_FROM(0.00){lordritical.de;},MID_RHS_MATCH_FROM(0.00){},MIME_GOOD(0.00){multipart/alternative;text/plain;},PREVIOUSLY_DELIVERED(0.00){himbeere@meine-oma.de;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_TWO(0.00){2;},RCVD_NO_TLS_LAST(0.00){},RCVD_VIA_SMTP_AUTH(0.00){},R_DKIM_ALLOW(0.00){lordritical.de;},R_SPF_ALLOW(0.00){+a:smtp01.lordritical.net;},TO_DN_ALL(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 1824, time: 220.000ms real, 8.534ms virtual, dns req: 35, digest: <9c6c2ad04a45b3cc52829c86b56627b5>, rcpts: <himbeere@meine-oma.de>, mime_rcpt: <himbeere@meine-oma.de>
2017-10-29 11:58:36 #10439(normal) <8da853>; task; rspamd_protocol_http_reply: regexp statistics: 91 pcre regexps scanned, 1 regexps matched, 163 regexps total, 7 regexps cached, 9.58k bytes scanned using pcre, 9.58k bytes scanned total
2017-10-29 11:58:39 #10440(normal) <zfscr4>; map; rspamd_map_file_check_callback: old mtime is 1509272188, new mtime is 1509274678 for map file /etc/rspamd/local.d/local_bl_from.map.inc`

Any help would be really appreciated.

thanks and cheers
t.

**Comment by himbeere** [comment]
Changing wheight to score solves the problem. Is the documentation outdated maybe? Do I break something when setting: 

`
        symbol "LOCAL_BL_FROM" {
            score = 10.0;
            description = "Sender from listed in local from blacklist";
        }
`

in rspamd.local.conf?

thanks and cheers

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#rspamd-does-not-work-as-expected

**Comment by himbeere** [comment]
Hi @vstakhov 

Do you need a specific snippet or the whole thing?

thanks and cheers

**Comment by vstakhov** [comment]
That's for your information...

**Comment by himbeere** [comment]
Ah, i see. Thanks. :-) So setting "score" instead of "weight" is no problem?

**Comment by fatalbanana** [comment]
Multimap expects `score`; metric wants to see `weight` - that seems to be in keeping with documentation.
