### ISSUE TITLE
How to reset the WebUI stats

### ISSUE THREAD

**Issue by gagnegithub** [vstakhov/rspamd#1893]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [x ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
I have installed rspamd with Redis and LUA and did some stress testing on it.  How can I reset the stats shown in WebUI?  I know that there is a file (/var/lib/stats.ucl) which get overwritten with the current stats every time rspamd is stopped/restarted and I believed this summary came from data stored in Redis.  So I deleted stats.ucl, flushed everything from Redis (redis-cli FLUSHALL) and restarted rspamd, but a new stats.ucl file was created and it showed the stats that were there before.  So what is the proper way to reset the statistics?

**Comment by moisseev** [comment]
> that there is a file (/var/lib/stats.ucl) which **get overwritten** with the current stats **every time rspamd is stopped/restarted**

So you need to stop rspamd, delete `/var/lib/stats.ucl`, start rspamd.

Or just use `rspamc stat_reset` command.

**Comment by gagnegithub** [comment]
thank you!  My problem was that even though I restarted rspamd, it kept a statistic count internally while running.  Stopping rspamd, delete the file and then restarting the rspamd was the solution indeed.
