### ISSUE TITLE
R_DKIM_REJECT even though SpamAssassin says DKIM_SIGNED+DKIM_VALID

### ISSUE THREAD

**Issue by FelixSchwarz** [vstakhov/rspamd#1904]
With rspamd 1.6.5 I get R_DKIM_REJECT even though SpamAssassin says DKIM_SIGNED+DKIM_VALID (also my Python DKIM validator also marks DKIM as "valid") so I assume rspamd has a bug somewhere...

spam message as received: [spam.txt](https://github.com/vstakhov/rspamd/files/1440888/spam.txt)

**Comment by fatalbanana** [comment]
Issue appears to be something about simple canonicalization & headers with empty values (like `X-MS-Has-Attach` in this example).

**Comment by FelixSchwarz** [comment]
Thank you very much for fixing this so quickly. As I'm unable to test a current git version within the next days I guess we can just close the ticket? Or is there anything else to do which was left out in https://github.com/vstakhov/rspamd/commit/54adbd226d3d0e72078047a36021aed9cc610c90 ?

**Comment by FelixSchwarz** [comment]
just closing so this ticket does not contribute to the pile of open tickets at github. Will reopen if I experience the problem again.
