### ISSUE TITLE
Connecting Rspamd to Redis and Nginx via Unix sockets

### ISSUE THREAD

**Issue by quicktrick** [vstakhov/rspamd#1905]
This is not an issue, this is a config example (everything is working on `openSUSE Tumbleweed`, `Rspamd 1.6.5`).

### Redis

`/etc/redis/rspamd.conf`  (changes only)

    bind 127.0.0.1
    port 0
    unixsocket /var/run/redis/rspamd.sock
    unixsocketperm 770
    pidfile /var/run/redis/rspamd.pid
    logfile /var/log/redis/rspamd.log
    dir /var/lib/redis/rspamd/

You should create the directory `/var/lib/redis/rspamd` and make it writable for user `redis`.

If you need to launch a separate `Redis` instance for `Rspamd`, follow [these instructions](https://medium.com/@MauroMorales/running-multiple-redis-on-a-server-472518f3b603).

`/etc/rspamd/local.d/redis.conf`

    servers = "/var/run/redis/rspamd.sock";

`/etc/rspamd/local.d/classifier-bayes.conf`

    backend = "redis";
    autolearn = true;

Don't forget to add the user `_rspamd` to the group `redis` (run `usermod -a -G redis _rspamd`)

You can check the connection with this:

    myserver:~ # redis-cli -s /run/redis/rspamd.sock
    redis /run/redis/rspamd.sock> ping
    PONG
    redis /run/redis/rspamd.sock> monitor
    OK
    1509722016.014458 [0 unix:/var/run/redis/rspamd.sock] "SMEMBERS" "BAYES_HAM_keys"
    1509722018.522879 [0 unix:/var/run/redis/rspamd.sock] "SMEMBERS" "BAYES_SPAM_keys"
    1509722018.523305 [0 unix:/var/run/redis/rspamd.sock] "HLEN" "BAYES_SPAM"
    1509722018.523334 [0 unix:/var/run/redis/rspamd.sock] "HGET" "BAYES_SPAM" "learns"
    1509722024.892442 [0 unix:/var/run/redis/rspamd.sock] "SMEMBERS" "BAYES_SPAM_keys"
    1509722024.892870 [0 unix:/var/run/redis/rspamd.sock] "HLEN" "BAYES_SPAM"
    1509722024.892899 [0 unix:/var/run/redis/rspamd.sock] "HGET" "BAYES_SPAM" "learns"
    ...

### Nginx

`/etc/tmpfiles.d/rspamd.conf`  (create this file if needed and run `systemd-tmpfiles --create`)

    d  /var/run/rspamd  0755  _rspamd  _rspamd  -

`/etc/rspamd/local.d/worker-controller.inc`

    bind_socket = "/run/rspamd/worker-controller.socket mode=0666 owner=_rspamd";
    password = "$2$paparrytknfm8...";
    enable_password = "$2$paparrytknfm8...";

`nginx.conf`

    location /rspamd/ {
        auth_basic "Restricted Area";
        auth_basic_user_file /srv/www/.mydomain.tld.htpasswd;
    
        map $status $loggable {
            ~^[23]  0;
            default 1;
        }
        access_log /var/log/nginx/rspamd.access.log combined if=$loggable;
        error_log /var/log/nginx/rspamd.error.log warn;
        
        proxy_pass http://unix:/run/rspamd/worker-controller.socket:/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

<sub><sup>I wrote this mainly for myself to store as an example for future use.</sup></sub>

**Comment by vstakhov** [comment]
Why this issue is closed? We should add this information to the documentation I suppose (e.g. to a FAQ section).

**Comment by fatalbanana** [comment]
Because it self-identifies as not an issue I suppose. :) This could go somewhere indeed but I'm not sure where, perhaps FAQ is best.

**Comment by vstakhov** [comment]
I have slightly changed Rspamd config sample to:

    bind_socket = "/run/rspamd/worker-controller.socket mode=0660 owner=_rspamd group=www";

To avoid world readable/writable sockets. That should be a better approach if nginx uses `www` group.

**Comment by quicktrick** [comment]
@vstakhov 

Всеволод, it doesn't work in that way. Even after you add your Nginx user to the group `_rspamd`. I don't know why. I tried it before I wrote my instruction.

**Comment by fenice2** [comment]
@fatalbanana 

My 2c on this would be to add it to a new section of documentation that lists "How To" examples for rspamd configurations (and possibly 'tweaking'). While the FAQ, as such, is great for some information it's not the best place for anyone that wants to see or try a specific configuration in rspamd - not everyone that uses rspamd is an expert in this technology and yes, I'm in that bracket. :)

**Comment by Jean-Daniel** [comment]
I think that a quick change can be to simply add a line in the `Upstream configuration` doc to tell that `servers` also accept unix socket (in addition to ipv4 and ipv6). It  would be very helpful and would have saved me a lot of time (I had to browse the sources to find how to specify a unix socket in the configuration…).

That does not prevent to also include the full sample elsewhere in the doc.

**Comment by fatalbanana** [comment]
[FAQ](https://rspamd.com/doc/faq.html#how-to-run-rspamd-using-unix-sockets) was updated. Please send PRs for the website: [it lives here](https://github.com/vstakhov/rspamd.com/) - [tips for working on it are here](https://rspamd.com/doc/tutorials/site_contributing.html)
