### ISSUE TITLE
Add new symbol USERS_BAYES_HAM/SPAM

### ISSUE THREAD

**Issue by johnwmail** [vstakhov/rspamd#1909]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.4
### Operation system, CPU, memory and environment:
OpenBSD, amd64, 8G ram and postfix/dovecot/rspamd
### Description (Please provide a descriptive summary of the issue):
I want to add new symbol "USER_BAYES_HAM/SPAM" to group bayes,

--------------------------------------------------
group {
bayes {
symbol {
BAYES_SPAM ....
...
}
symbol {
USERS_BAYES_SPAM {
weight = 4.0;
description = "...."
}
....
}
----------------------------------------------------

My problem is,

If I add it to /etc/rspamd/local.d/metrics.conf 
the content will add to other group, not bayes group

If I add it to /etc/rspamd/override.d/metrics.conf
I need to add other default setting/symbol to make it work,
but it will also override all other setting/symbol,
so I dont want to do that.

if I add it to /etc/rspamd/rspamd.conf.local,
then I see (rspamadm configtest), two metrics (both name = default)

My question is,
What is the correct way to add new symbol?

Thanks.

**Comment by vstakhov** [comment]
The metrics case is old and very painful (leading to the dark ages of xml config and other bad ideas). So far, when you see double metrics in the config with the same name, it should still work fine - Rspamd will merge them together. This issue will be fixed by totally new layout of metrics configuration in 1.7. There will be no metrics - just actions and grouped scores.

**Comment by johnwmail** [comment]
Yes, it work, (double metrics with same name).

Thank you to let us know the dark ages, and the rspamd future.  :)
