### ISSUE TITLE
building 0.8.1 on debian wheezy: several CMakeLists.txt missing 

### ISSUE THREAD

**Issue by bjo81** [vstakhov/rspamd#191]
CMake Warning (dev) at CMakeLists.txt:858 (ADD_SUBDIRECTORY):
  The source directory

    /root/rspamd/contrib/snowball

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:859 (ADD_SUBDIRECTORY):
  The source directory

    /root/rspamd/contrib/siphash

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at src/CMakeLists.txt:59 (ADD_SUBDIRECTORY):
  add_subdirectory given source "ucl/cmake" which is not an existing
  directory.

CMake Warning (dev) at src/CMakeLists.txt:61 (ADD_SUBDIRECTORY):
  The source directory

    /root/rspamd/src/rdns

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCONFDIR=/etc/rspamd -DMANDIR=/usr/share/man -DRUNDIR=/run/rspamd -DDBDIR=/var/lib/rspamd -DLOGDIR=/var/log/rspamd -DPLUGINSDIR=/usr/share/rspamd -DEXAMPLESDIR=/usr/share/doc/rspamd/examples -DLIBDIR=/usr/lib -DINCLUDEDIR=/usr/include -DNO_SHARED=ON -DDEBIAN_BUILD=1 -DINSTALL_EXAMPLES=ON -DFORCE_GMIME24=ON -DENABLE_HIREDIS=ON returned exit code 1

**Comment by vstakhov** [comment]
Hello, it seems that you've forgotten to initialize submodules:

    git submodule update --init
