### ISSUE TITLE
Greylist form vanished with negative value

### ISSUE THREAD

**Issue by timscha** [vstakhov/rspamd#1910]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
When you enter a negative value (for example "-2" in the Greylist form on Configuration and save the data the form vanished. Only workaround to make it visible again is, to to change the value in var/lib/rspamd/rspamd_dynamic to a positive value.

### Steps to reproduce:
In the web interface go to Configuration. Under actions, set the greylisting to a negative value and safe it.

**Comment by vstakhov** [comment]
Don't set it to negative value.

**Comment by fatalbanana** [comment]
Thresholds for metric actions should typically not be negative, and some order for actions (if defined) is expected to be maintained: `no action <= greylist <= add header <= rewrite subject <= reject`. If you want to disable `greylist` action you can redefine actions in `override.d/metrics.conf`. Note that this won't disable greylisting. To disable greylisting, set `enabled = false` in `local.d/greylist.conf` (or don't give it redis settings).

**Comment by timscha** [comment]
Guys, I know that I don't have to use negative values. But I think the form should catch values likes this.

**Comment by vstakhov** [comment]
Yes, that's correct.
