### ISSUE TITLE
Soft reject action, repeat several times?

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#1915]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Operation system, CPU, memory and environment:
Centos
### Additional information:
Hello
Having tested Eset Mail Security on Windows (ho the naughty boy that I am), the "Greylist" is repetitive when it is sending "spam" Grossier, too lours if you have not understood the word between " "!!!
Is it increasing or not?
1, 2, 3, 4, 5 passage, to know if the IP is good or totally spam ...

Mz

**Comment by vstakhov** [comment]
Please read how greylisting works. I also don't quite understand what are you asking about.
