### ISSUE TITLE
proxy; rspamd_protocol_handle_headers: bad ip header: [IPv6]

### ISSUE THREAD

**Issue by jirireischig** [vstakhov/rspamd#1916]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Operation system, CPU, memory and environment:
CentOS 7, sendmail

### Description (Please provide a descriptive summary of the issue):
Bad IPv6 address detection in proxy.
Error in log examples:
proxy; rspamd_protocol_handle_headers: bad ip header: '2607:f8b0:400e:c05::247'
proxy; rspamd_protocol_handle_headers: bad ip header: '::1'

### Steps to reproduce:
Use Rspamd as Milter with sendmail. Incomming message from IPv6 server.

I'm sorry, it's look like as another IPv6/sendmail problem. :-(

**Comment by vstakhov** [comment]
Could you please test this potential fix?

**Comment by jirireischig** [comment]
The fix look good.
I haven't error 'bad ip header' in our logs for 6 hour.

Thank you.
