### ISSUE TITLE
CircleCI fails: Cases.150 Rspamadm

### ISSUE THREAD

**Issue by szepeviktor** [vstakhov/rspamd#1922]
```
#32950(configtest) lua; rspamd_config_transform.lua:172: group 1 has no symbols
```

I haven't found an issue for it.

Maybe a quick work-around is more valuable than a real fix.

https://circleci.com/gh/vstakhov/rspamd/2460#tests/containers/0

**Comment by fatalbanana** [comment]
That was fixed.
