### ISSUE TITLE
withelist a hash ?

### ISSUE THREAD

**Issue by ddeenniiss** [vstakhov/rspamd#1927]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Additional information:

This hash seems to be related to a classical facebook logo. It blocks quite legitimate mails.

Is it possible to whitelist this hash locally ? 

4597b7dfd94e60bbf4e92b5bd023a1cb4973de3833d8fe0f962ac60cda8842aa48a7620a882f4ef8b580814f519c5f77c3563287e47befa08407e0868c04f40d

**Comment by vstakhov** [comment]
You can use https://bl.rspamd.com to add an FP for fuzzy hashes.

**Comment by moisseev** [comment]
@vstakhov 
1. Does https://bl.rspamd.com really **whitelists** fuzzy hashes, or just removes them?
2. I tried several hashes, but nothing happened at all. The hashes weren't even removed from the storage. It seems like there is nothing behind the web front end.

**Comment by vstakhov** [comment]
They are removed and whitelisted. You just need to wait for couple of minutes.

**Comment by moisseev** [comment]
ok, I've tried to add 
01fc79e5f86d969e30bacbfb777e2ea683332dfa9fbd1f7f6764368f81edae414a2e436e7d4c312dabba7b5d0511747b5da9b34be506f0dbb7f1949de836d174
I've been waiting about half-hour. Still nothing happened.

**Comment by vstakhov** [comment]
Dunno, perhaps, some issue with cron. I've tried it automatically and it worked...

**Comment by moisseev** [comment]
Automatically?
Would you take a look at cron then?

I've scanned the message again and the hash is still there.
```
2017-11-19 17:20:28 #5310(controller) <fa6313>; csession; fuzzy_insert_result: found fuzzy hash(txt) 01fc79e5f86d969e30bacbfb777e2ea683332dfa9fbd1f7f6764368f81edae414a2e436e7d4c312dabba7b5d0511747b5da9b34be506f0dbb7f1949de836d174 with weight: 0.00, probability 0.66, in list: FUZZY_DENIED:1
```
But if I put the hash into the bl.rspamd.com form it says:
```
"01fc79e5f86d969e30bacbfb777e2ea683332dfa9fbd1f7f6764368f81edae414a2e436e7d4c312dabba7b5d0511747b5da9b34be506f0dbb7f1949de836d174"
has already been removed from the Hash blacklist
```
