### ISSUE TITLE
New install rspamd, but did not find rspamd.sysvinit.conf file

### ISSUE THREAD

**Issue by ltybenet** [vstakhov/rspamd#1930]
my system: centos6.8
rspamd version:  1.6.5

curl https://rspamd.com/rpm-stable/centos-6/rspamd.repo > /etc/yum.repos.d/rspamd.repo

rpm --import https://rspamd.com/rpm-stable/gpg.key

yum update

yum -y install rspamd

service rspamd start

2017-11-21 09:12:12 # 22945 (rspamadm) cfg; rspamd_config_read: can not stat /etc/rspamd/rspamd.sysvinit.conf: No such file or directory
syntax BAD

**Comment by fenice2** [comment]
You'll find the answer in the sixth post (by jdunphy) in this forum thread: http://forums.zimbra.com/viewtopic.php?f=15&t=62443

**Comment by fatalbanana** [comment]
Seems to be fixed in 1.6.5-4 (rspamd.sysvinit.conf should not be referenced anywhere, it's history).
