### ISSUE TITLE
worker-controller.inc is world-readable, expose password to all local users

### ISSUE THREAD

**Issue by guillaume-uH57J9** [vstakhov/rspamd#1931]
### Classification (Please choose *one* option):

* [X] Other bug

### Reproducibility (Please choose *one* option):

* [X] Always

### Rspamd version:

`rspamd_1.7.0-0~git84~9467740ff~stretch_amd64`

### Operation system, CPU, memory and environment:

Debian 9 (stretch)

### Description (Please provide a descriptive summary of the issue):

/etc/rspamd/worker-controller.inc is world-readable by default, which is bad because this file is meant to contain a password as it's default content shows: 

```
# Included from top-level .conf file

type = "controller";
count = 1;
password = "q1";
secure_ip = "127.0.0.1";
secure_ip = "::1";
static_dir = "${WWWDIR}";
```

### Steps to reproduce:

If rspamd is installed: 
```
$ ls -lah /etc/rspamd/worker-controller.inc 
-rw-r--r-- 1 root root 188 Mar  1  2017 /etc/rspamd/worker-controller.inc
```

If rspamd is not installed, run the following command on data.tar.xz contained in the deb file
```
$ tar tJvf data.tar.xz | grep worker-controller.inc
-rw-r--r-- root/root       157 2015-09-17 16:17 ./etc/rspamd/worker-controller.inc
```

### Expected results:

This file should NOT be world-readable, for instance chmod 640, or chmod 600

### Actual results:

This file is chmod 644

**Comment by fatalbanana** [comment]
The actual rather than default password is not expected to be contained in this file.

https://rspamd.com/doc/quickstart.html#setting-the-controller-password
https://rspamd.com/doc/quickstart.html#configuring-rspamd

**Comment by guillaume-uH57J9** [comment]
Okay, chmod of /etc/rspamd/worker-controller.inc is not so bad then. 

Looking at local.d, I see that directory is world-readable/world-browsable. 
```
# ls -lah /etc/rspamd/ | grep local
drwxr-xr-x   2 root root 4.0K May 25  2017 local.d
```

Consider setting chmod 750 on local.d to ensure that it's content would not be readable, even if the admin isn't careful enough and leave local.d/worker-controller.inc with the default chmod upon file creation (644)

If you're wondering if that precaution, out of curiosity, check the chmod of /etc/rspamd/local.d/worker-controller.inc on your own server(s)

**Comment by Jean-Daniel** [comment]
chmod 750 /etc/rspamd/local.d would prevent user _rspamd to access it.
If you want to go that route, you have to also chown the whole dir.

But I don't see why to bother with that as the password should be hashed anyway.

**Comment by guillaume-uH57J9** [comment]
@Jean-Daniel Even if the password is always hashed (is it always?), access to hashed passwords allows offline attacks. That mean cracking the password is much faster, because it can be done without network delay, without server throttling, can be done on the GPU for further speedup. 

For reference : [Hackers crack more than 60% of breached LinkedIn passwords](https://www.computerworld.com/article/2504078/cybercrime-hacking/hackers-crack-more-than-60--of-breached-linkedin-passwords.html). The percentage would vary a lot depending on the situation (hash algo, password randomness, CPU cycles spent), but the basic idea is you should avoid leaking hashes.
