### ISSUE TITLE
rspamd-proxy doesn't work with exim

### ISSUE THREAD

**Issue by gawoyo** [vstakhov/rspamd#1933]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
CentOS 6.9

### Description (Please provide a descriptive summary of the issue):
rspamd-proxy doesn't work with Exim v4.89. Connection works etc but exim can't parse the response.

### Steps to reproduce:
local.d/worker-proxy.inc

    milter = no; # Enable milter mode
    timeout = 120s; # Needed for Milter usually

    upstream "scan" {
      default = yes;
      hosts = "1.2.3.4:11333";
    }

exim.conf:

    spamd_address = 127.0.0.1 11332 variant=rspamd

### Expected results:
Should work via proxy.

### Actual results:
exim.log:

    spam acl condition: cannot parse spamd [127.0.0.1]:11332, output: 0

**Comment by vstakhov** [comment]
I have just fixed it in https://github.com/vstakhov/rspamd/commit/d2e806d902f1469e87070b340291d21fa04fc26a I've successfully proxied Exim requests using Rspamd proxy with this change.

**Comment by fatalbanana** [comment]
Should be fixed in 1.6.6.

**Comment by pilchita** [comment]
I see the same error in my architecture: 

Exim version 4.87_1 #2 built 09-Jan-2017 13:55:10

spamd_address = 168.181.185.235 11332 variant=rspamd

2018-06-13 10:39:56 1fT60B-0003cu-M5 spam acl condition: cannot parse spamd [168.181.185.235]:11332, output: -1
2018-06-13 10:39:56 1fT60B-0003cu-M5 spam acl condition: cannot parse spamd [168.181.185.235]:11332, output: -1
2018-06-13 10:39:56 1fT60B-0003cu-M5 spam acl condition: cannot parse spamd [168.181.185.235]:11332, output: -1
2018-06-13 10:39:56 1fT60B-0003cu-M5 spam acl condition: cannot parse spamd [168.181.185.235]:11332, output: -1

cat worker-proxy.inc
# local.d/worker-proxy.inc
milter = yes;
bind_socket = *:11332;
upstream "scan" {
        default = yes; # Self-scan upstreams are always default
        self_scan = yes; # Enable self-scan
        hosts = "168.197.48.92:11333";
}

any ideas?
