### ISSUE TITLE
ARC_REJECT in mail from Google groups?

### ISSUE THREAD

**Issue by FelixSchwarz** [vstakhov/rspamd#1942]
I just noticed that my rspamd 1.6.5 does not like Google's ARC seal.

This affects all messages I sent to rspamd's Google group, for example 
Message-ID: <280f8a99-9d14-5711-4628-12a38640e957@oss.schwarz.eu>

DKIM is fine (as testified by exim and rspamd) but rspamd applies the ARC_REJECT symbol

I did not check the actual ARC seal but I just assume that Google does it correctly and the ARC seal should be just fine.

**Comment by vstakhov** [comment]
On 02.12.2017 22:12, Felix Schwarz wrote:
> I just noticed that my rspamd 1.6.5 does not like Google's ARC seal.
> 
> This affects all messages I sent to rspamd's Google group, for example
> Message-ID: 280f8a99-9d14-5711-4628-12a38640e957@oss.schwarz.eu
> <mailto:280f8a99-9d14-5711-4628-12a38640e957@oss.schwarz.eu>
> 
> DKIM is fine (as testified by exim and rspamd) but rspamd applies the
> ARC_REJECT symbol
> 
> I did not check the actual ARC seal but I just assume that Google does
> it correctly and the ARC seal should be just fine.


Google does not do it correctly, I have investigated this issue in the past.

**Comment by FelixSchwarz** [comment]
Oh sorry. I didn't find anything with Google (Search) about this and assumed that Google does it right as gmail pushes ARC quite a bit. Does that affect also gmail or just Google groups?

Maybe rspamd should lower the weight of ARC_REJECT? (as Google is pretty much the only big provider using this AFAIK).
