### ISSUE TITLE
check_local and check_authed options ignored in lua scripts

### ISSUE THREAD

**Issue by unicode2013** [vstakhov/rspamd#1954]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

The `check_local` and `check_authed` options are ignored by:
* src/plugins/lua/dmarc.lua:597
* src/plugins/lua/hfilter.lua:579
* src/plugins/lua/ip_score.lua:353
* src/plugins/lua/once_received.lua:144

Each of the scripts has this code:

```
local opts = rspamd_config:get_all_opt('options')
if opts and type(opts) ~= 'table' then
  if type(opts['check_local']) == 'boolean' then
    check_local = opts['check_local']
  end
  if type(opts['check_authed']) == 'boolean' then
    check_authed = opts['check_authed']
  end
end
```

This means the values of `check_local`, and `check_authed` are only ever changed if `opts` is not a table, but if it contains the options then it should be a table.  So I believe that the second line should read:

`if opts and type(opts) == 'table' then
`

### Steps to reproduce:

Set check_local and check_authed to true in options.inc and send mail from a local authed user.

### Expected results:

local mail from authenticated users should be checked by dmarc, ip_score, hfilter, and once_received lua scripts.

### Actual results:

dmarc, ip_score, hfilter, and once_received lua scripts skip checks.

**Comment by fatalbanana** [comment]
Yes, that's the wrong operator indeed.

Thank you for the report.
