### ISSUE TITLE
Bayes expiration feature

### ISSUE THREAD

**Issue by kobuki** [vstakhov/rspamd#1957]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Rspamd version:
any
### Description (Please provide a descriptive summary of the issue):
It would be very useful to be able to set an expiration on Bayes tokens instead of keeping them forever. The fuzzy database has a settable expiration time, it could be similar to that. There is no point in keeping the Bayes stats forever, either.

**Comment by vstakhov** [comment]
It is implemented with the new schema.

**Comment by kobuki** [comment]
Sorry, I haven't noticed that. By new schema you mean the 1.7+ series? Could you point me to the docs on how to configure stats expiration, or just a very short explanation of the options? Thanks.

**Comment by vstakhov** [comment]
There are currently no docs neither migration path. It is work in progress for `1.7` indeed. You can try it yourself using:

```
new_schema = true;
```

in classifier setup.

**Comment by kobuki** [comment]
Thanks, I'll try that.
