### ISSUE TITLE
'from field' email is not good with gmail

### ISSUE THREAD

**Issue by stephdl** [vstakhov/rspamd#1966]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Operation system, CPU, memory and environment:
centos7
### Description (Please provide a descriptive summary of the issue):
The from header  is  incoherent between the maillog and the rspamd log
see https://gist.github.com/stephdl/d59ea6e546aa773849344bd0477d87a3
### Compile errors (if any):
no errors
### Steps to reproduce:

send an email to your server with a gmail account, see  in the rspamd log the stephanedelabrusse@gmail.com instead of stephane.delabrusse@gmail.com.
Try to reproduce with another email (in my case the professional email) and stephane.delabrusse@chubbfrance.com is well read and found

### Expected results:
rspamd find and extract stephane.delabrusse@gmail.com
### Actual results:
rspamd find stephanedelabrusse@gmail.com
### Additional information:

this is problematic to filter the good email address if I want to blacklist/whitelist an email

**Comment by vstakhov** [comment]
That's how gmail normalise its emails (https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html). Closing issue.

**Comment by stephdl** [comment]
thank a lot for your quick answer, much appreciated

**Comment by stephdl** [comment]
think if you want to blacklist a gmail email account with multimap to write like this your list

`firstname.lastname@gmail.com => firstnamelastname@gmail.com`
