### ISSUE TITLE
'rewrite subject' changes the 'reject' value in the rspamd UI

### ISSUE THREAD

**Issue by stephdl** [vstakhov/rspamd#1968]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
centos7

### Description (Please provide a descriptive summary of the issue):
When the actions values are set in local.d/metrics, values are used by rspamd, but if the 'rewrite_subject' is set in local.d/metrics.conf then the value of 'reject' is changed when you save new action setting in the web UI

### Compile errors (if any):
```
2017-12-20 19:13:38 #13313(controller) <ng5fs7>; cfg; rspamd_config_set_action_score: action reject has been already registered with priority 1, override it with new priority: 3, old score: 15.00, new score: 7.00
2017-12-20 19:13:38 #13313(controller) <7d4049>; csession; rspamd_controller_handle_saveactions: <127.0.0.1> modified 1 actions
2017-12-20 19:13:46 #13319(fuzzy) <daz6fz>; map; rspamd_map_file_check_callback: old mtime is 1513793454, new mtime is 1513793618 for map file /var/lib/rspamd/rspamd_dynamic
2017-12-20 19:13:46 #13319(fuzzy) <daz6fz>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/rspamd_dynamic
2017-12-20 19:13:46 #13319(fuzzy) <daz6fz>; map; read_map_file: /var/lib/rspamd/rspamd_dynamic: read map dat, 199 bytes
2017-12-20 19:13:47 #13313(controller) <daz6fz>; map; rspamd_map_file_check_callback: old mtime is 1513793454, new mtime is 1513793618 for map file /var/lib/rspamd/rspamd_dynamic
2017-12-20 19:13:47 #13313(controller) <daz6fz>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/rspamd_dynamic
2017-12-20 19:13:47 #13313(controller) <daz6fz>; map; read_map_file: /var/lib/rspamd/rspamd_dynamic: read map dat, 199 bytes
```

### Steps to reproduce:
put this in local.d/metrics.conf and restart rspamd
```
    actions {
      reject = 15;
      add_header = 6;
      rewrite_subject = 7;
      greylist = 4;
    }
```
### Expected results:
This values are in the web UI
![screenshot-2017-12-20 rspamd web interface](https://user-images.githubusercontent.com/3164851/34222209-144c01e6-e5bb-11e7-905e-06f1916f7ce9.png)

### Actual results:
Now simply change some settings or save the same settings in the webUI, then you have this
![screenshot-2017-12-20 rspamd web interface 1](https://user-images.githubusercontent.com/3164851/34222265-488a2fd2-e5bb-11e7-87ec-08d92d337671.png)

you can see in the dynamic.map that 'reject' has changed
![screenshot-2017-12-20 rspamd web interface 2](https://user-images.githubusercontent.com/3164851/34222282-598f788c-e5bb-11e7-85da-f13663ccf10b.png)

### Additional information:

alternatively I tried to save actions like this in local.d/metrics.conf

```
      reject = 15;
      add_header = 6;
      rewrite_subject = 7;
      greylist = 4;
```

because I read in https://rspamd.com/doc/configuration/settings.html#introduction that like this we can allow dynamical update of settings, but the 'rewrite_subject' was never used by rspamd nor visible in the web UI

let me know what I'm missing and any other informations needed.

**Comment by vstakhov** [comment]
Don't set the same thresholds for different actions.

**Comment by stephdl** [comment]
thank, will try and report

**Comment by stephdl** [comment]
I retested @vstakhov , something occur on my side fun, I verified that the same threshold is not set, but it was already the case in my first test.

this is what I put in local.d/metrics.conf

```
[root@ns7dev ~]# cat /etc/rspamd/local.d/metrics.conf
actions {
    reject = 15;
    add_header = 7;
    rewrite_subject = 8;
    greylist = 4;
}
```

I did after a reload of rspamd

`[root@ns7dev ~]# systemctl reload rspamd`

I can see in the rspamd UI the change

![screenshot-2017-12-23 rspamd web interface](https://user-images.githubusercontent.com/3164851/34322115-00140672-e81f-11e7-8e13-cf196c1d08da.png)

but if I change the threshold or I simply save, then this is what I saw

![screenshot-2017-12-23 rspamd web interface 2](https://user-images.githubusercontent.com/3164851/34322169-a8fd1728-e820-11e7-954d-48a79bd2e06f.png)

and I see also the dynamic map  modified

![screenshot-2017-12-23 rspamd web interface 1](https://user-images.githubusercontent.com/3164851/34322171-bec83d94-e820-11e7-8fb6-0276f182444b.png)

and a relevant trace log

```
2017-12-01 15:30:47 #30175(controller) <qnjkkz>; cfg; rspamd_config_set_action_score: action reject has been already registered with priority 1, override it with new priority: 3, old score: 15.00, new score: 8.00
2017-12-01 15:30:47 #30175(controller) <2da4e2>; csession; rspamd_controller_handle_saveactions: <192.168.12.25> modified 1 actions
```

My concern now is that I cannot change by the UI the reject value, it comes back always to '8'

I worry a bug...of course I can be the bug :)

**Comment by fatalbanana** [comment]
Setting thresholds for actions via WebUI only works if the defined actions are `greylist`, `add header` & `reject` (as per defaults).

**Comment by stephdl** [comment]
ok @fatalbanana it is a feature not implemented in the webUI if I understand well. Does it is possible to transform this bug request in a feature request.

My concern is that we ([netheserver team](https://community.nethserver.org/)) are willing to let drop amavisd,spammassassin solution to go rspamd (actually about 8100 servers) and this feature is implemented in the core. I'm the one who is working on this project and this is the last issues I have for getting a workable solution with rspamd :)

I have another issue but I don't think it is related to rspamd, add a disclaimer to all emails

At the end I hope that you could say to someone who don't want to bored for creating himself his email server with rspamd, try nethserver !

Maybe we could look to implement this feature and do a PR also, I can see a lot of alternatives.

**Comment by stephdl** [comment]
For now I turned around my issue, We have already another User interface in nethserver to adjust the score of spam setting, then I use this UI to rewrite the override.d/metrics.conf. With the override it is workable but of course the UI of rspamd is no more usable.

**Comment by stephdl** [comment]
seems corrected by 1.7.2 do I'm alone ?

If so this issue could be closed

**Comment by stephdl** [comment]
in fact now the UI gets precedence over static configuration file, set closed

**Comment by chkpnt** [comment]
> Don't set the same thresholds for different actions.

What's the reason for this restriction? Why shouldn't it possible to set different actions to the same threshold? If I want the header added even if the mail is "only" greylisted, what should I do?
As far as I understood the [metrics](https://rspamd.com/doc/configuration/metrics.html), it doesn't make sense to set `add_header` lower than `greylist` as the latter implies `add_header`.
