### ISSUE TITLE
Rspamd should have a module that can assign scores to ASNs and countries

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#197]
This can be done with DNSBLs which provide IP->ASN and country mappings (we should support as many as possible):

http://spameatingmonkey.com/usage.html
http://www.team-cymru.org/IP-ASN-mapping.html#dns
http://www.shadowserver.org/wiki/pmwiki.php/Services/IP-BGP#toc7

And/or this may be done using Rspamd's radix trees & GeoIP data:

http://dev.maxmind.com/geoip/geoip2/geolite2/
http://dev.maxmind.com/geoip/legacy/geolite/

**Comment by AlexeySa** [comment]
I used geoip dlfunc for exim and add country-header.
Dlfunc http://dist.epipe.com/exim/

**Comment by vstakhov** [comment]
Rspamd has very effective radix trie algorithm. I'm pretty sure it'll be faster than exim's one. Let's check that some day!

**Comment by AlexeySa** [comment]
How to use the radix and geoip?

**Comment by vstakhov** [comment]
Erm, load country codes to the radix nodes, I'd suppose

**Comment by msimerson** [comment]
Getting [ASN data via DNS](https://github.com/baudehlo/Haraka/blob/master/plugins/connect.asn.js) lookups is fine for small servers but is a non-starter for mail systems with very large volume. For that, RBLs are downloaded and looked up locally as well. You can download the ASN data that SpamAssassin uses from the routeviews FTP site or better still, uses the ASN data included in the MaxMind GeoIP data. Haraka's [connect.geoip](https://github.com/baudehlo/Haraka/blob/master/plugins/connect.geoip.js) plugin uses MaxMind's data and includes [geoip distance calculations](https://github.com/baudehlo/Haraka/blob/master/plugins/connect.geoip.js#L339-L360) as well. I've also written a [perl geoip](https://github.com/smtpd/qpsmtpd/blob/master/plugins/ident/geoip) qpsmtpd plugin as well if perl is easier to grok. Of course, if you use a solution other than DNS, you'll need to keep the DBs up-to-date. I wrote a [geolite-mirror](https://www.npmjs.com/package/maxmind-geolite-mirror) script for that.

**Comment by vstakhov** [comment]
Well, I actually see no real usage of geoip in rspamd. But obviously, one can just store that data in radix trie.

**Comment by fatalbanana** [comment]
I also fail to see a compelling use-case for geoip tbh (though would find the ability to score ASNs useful).

**Comment by msimerson** [comment]
The use case for most GeoIP data is mostly informational (and for reporting purposes, can be easily added later), but similar to the [SNARE](http://www.cc.gatech.edu/~feamster/papers/snare-usenix09.pdf) authors, I too have found a significant statistical correlation of ham/spam based on GeoIP distance and time-of-day. You may want to look into it.

**Comment by msimerson** [comment]
The ASN data, which as I'm sure you're aware, is normally of marginal utility (for "average or good quality" networks with a low ratio of poor senders) but is also *extremely* useful for identifying low quality networks that spew little other than spam. Quite often when I see a new outbreak, identifying the ASN and penalizing its reputation is sufficient to quell it.

**Comment by vstakhov** [comment]
Yes, I think this functionality would be extremely useful for rspamd. I'm observing the ridiculous increase of spam sent from some networks for about a month (URL + picture with good SPF and DKIM mainly, so they are hard to filter). So we could start from making the similar plugin in lua to query ASN via DNS and think about storing geographical data in the compressed radix trie in advance.

**Comment by msimerson** [comment]
I already have the ASN (looked up way back at SMTP CONNECT), so could I pass in the ASN to rspamd in the HTTP request?

I also have a bunch of other connection metadata that has been looked up previously, such as DNSBL and URIBL lookups, GeoIP distance, sender OS (linux, mac, windows, etc.), the port they connected on (25, 465, 587), SPF results (helo and mfrom, which are looked up during the corresponding phase of the SMTP connection), and more. I browsed the web site a bit and didn't find docs for the API that @fatalbanana is using when he wrote [this part of the Haraka rspamd](https://github.com/baudehlo/Haraka/blob/master/plugins/rspamd.js#L29-L61) plugin.

**Comment by vstakhov** [comment]
The protocol is described here briefly:

https://rspamd.com/doc/architecture/protocol.html

It doesn't describe the encrypted protocol however, but it will be merely available from the upcoming 0.9 release.

Regarding additional headers, rspamd accepts all headers but there is no API so far to extract them from LUA. Perhaps, I could add that interface and we could use the special pre-filter for Haraka that would extract all available information to avoid duplication.

On the other hand, I'm pretty unsure that it's a good idea to do such a checks from JS: rspamd can obviously do it faster and in the secure way (e.g. you could read about the security model of rdns: it randomizes source address, uses cryptoghraphic PRNG for generating DNS id, sanitizing input precisely and so on). Actually, rspamd can do all these checks very fast and completely asynchronously (same as node.js model). So maybe it would be good idea to reuse that functions from rspamd and skipping them in Haraka. But we need some sort of milter like API to perform pre-DATA checks earlier.

**Comment by msimerson** [comment]
> ridiculous increase of spam sent from some networks ... good SPF and DKIM

Yes, certainly so. The spammers with their own infrastructure (ie, not sending via bot nets) tend to be far better at getting SPF and DKIM right than the vast majority of small (orgs with an IT staff of 0.1-1.0 persons) ham senders.
