### ISSUE TITLE
Received header parsing: esmtpsa .vs. ESMTPSA is not parsed correctly.

### ISSUE THREAD

**Issue by smfreegard** [vstakhov/rspamd#1976]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

This received header:

`````
Received: from [161.132.175.36] (port=51336 helo=IDEACENTRE1)
        by server10.linuxcentro.net with esmtpsa (TLSv1:AES128-SHA:128)
        (Exim 4.89_1)
        (envelope-from <sales@peruferias2018.com>)
        id 1eWP1e-0000vu-HQ; Tue, 02 Jan 2018 09:02:52 -0700
`````

Is not correctly parsed as 'esmtpsa' is lower-case, therefore RCVD_VIA_SMTP_AUTH symbol is not correctly raised.

**Comment by fatalbanana** [comment]
What version do you test? That's a known issue in 1.6 branch; should be fixed by this commit: https://github.com/vstakhov/rspamd/commit/6e25c8c70e789b78b0d2e725695f2818c5f7f0d1

**Comment by smfreegard** [comment]
Sorry - that's my bad then: 

Rspamd daemon version 1.6.5
