### ISSUE TITLE
greylist should honour local_addrs

### ISSUE THREAD

**Issue by yennor** [vstakhov/rspamd#1977]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
 1.6.5-2~stretch

### Operation system, CPU, memory and environment:
debian linux stretch, amd64

### Description (Please provide a descriptive summary of the issue):

Greylist ignores local_addrs settings, you need to whitelist local networks explicitely with whitelisted_ip settings.
It guess the expected behaviour (at least for me) would be that local networks (local_addrs) would also be ignored by greylist by default.
Would have saved me some time to debug unreliable scripted mail sending out of my docker containers ;-).
If there is a good reason not to do so, I would be interested in learning it :-).

**Comment by fatalbanana** [comment]
It looks to me like greylisting module does in fact ignore messges from local IPs.

**Comment by yennor** [comment]
well it yesterday it definetely greylisted comming from 172.17.0.2.

First 172.17.0.0/16 was not in local_addrs, so he complained about the spf record.
I added it to local_addrs. Then first it worked, then again not, then again, then again not ;-).
Until I found out that sometimes they get greylisted.
Then I added it to whitelisted_ip and no complains anymore.
Unfortunately I can't find the log file entries anymore. I guess they've got deleted when I've deleted all the logfiles, after I was incredibly annoyed about the verbosity of rspamd ;-).

**Comment by fatalbanana** [comment]
Setting for `local_addrs` per default configuration includes `172.16.0.0/12`, so there should be no need to add `172.17.0.0/16` there.

I could not reproduce this. Perhaps it might be something configuration-specific.

**Comment by yennor** [comment]
unfortunately the default values for local_addrs were not documented (at least nowhere I could find it, the whole documentation actually left more questions than it answered...) and https://thomas-leister.de/en/mailserver-debian-stretch/ said to put that here:
local_addrs = "127.0.0.0/8, ::1"; so that's why i had to add the 172 network by hand.. ;)

If interested I could add the (huge) output from
rspamadm configdump

Otherwise, for me it works right now.

**Comment by fatalbanana** [comment]
That seems to be bad advice, this *overwrites* `local_addrs` with new settings. Though the addresses added here don't feature in default setting of `local_addrs` they are indeed recognised as local.

**Comment by yennor** [comment]
I disabled it again, eventhough I didn't understand exactly why it is bad to overwrite it (beside that as it seems, sane defaults are chosen already).
