### ISSUE TITLE
Web Server Generic XSS

### ISSUE THREAD

**Issue by nquinke** [vstakhov/rspamd#1979]
Dear Vsevolod Stakhov,

great software suite! Thank you very much for your work. 

Our Nessus reported only one issue, Web Server Generic XSS, which I would like to report:

### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

rspamd 1.6.5

### Operation system, CPU, memory and environment:

RedHat Enterprise Linux 7.4, x86_64, virtual

### Description (Please provide a descriptive summary of the issue):

Nessus Security Scan, Plugin ID 10815:

8<----

Plugin Output
x.x.x.x (tcp/11333)
------------------------------ Request #1 ------------------------------

The request string used to detect this flaw was :

/scripts/<script>cross_site_scripting.nasl</script>.asp

The output was :

HTTP/1.1 500 invalid command: scripts/<script>cross_site_scripting.nasl</script>.asp 
Connection: close 
Server: rspamd/1.6.5 
Date: Fri, 22 Dec 2017 10:26:31 GMT 
Content-Length: 115 
Content-Type: application/json 

{"error":"invalid command: scripts/<script>cross_site_scripting.nasl</sc
ript>.asp","error_domain":"protocol-error"}

Note that this XSS attack may only work against web browsers
that have "content sniffing" enabled.

--->8

### Compile errors (if any):

/-

### Steps to reproduce:

Nessus PCI internal scan with web application scanning; for further details, please see description above.

### Expected results:

1) Please prohibit this front-end error response. Instead realize this error reporting via syslog or backend application logging.

2) Please prohibit the 500 server status HTTP response. Instead use HTTP/1.1 302 and redirect to login page

### Actual results:

1) front-end error response
2) HTTP/1.1 500

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

/-

### Configuration:

Package default

### Additional information:

Best regards,
Nils.

**Comment by vstakhov** [comment]
Well, I see the issue that the path shouldn't be returned via error code or an error message. But what's wrong about `500` error code?

**Comment by attritionorg** [comment]
A 302 would prevent the web server from throwing an error that may carry user-supplied content and reflected in the error message. That said, Nessus may be throwing a FP. Best to test this manually to verify the <script> code is rendered.

**Comment by fatalbanana** [comment]
1.6.6 should be OK.
