### ISSUE TITLE
DKIM Sign message that shouldn't. Something with sign_networks

### ISSUE THREAD

**Issue by MVKozlov** [vstakhov/rspamd#1985]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Operation system, CPU, memory and environment:
Ubuntu 16.04
### Description (Please provide a descriptive summary of the issue):
RSpamd sign message that should not sign (may be?) when use common sign key
### Steps to reproduce:
#Send message outside of system to the same email
`remote PS>  Send-MailMessage -To testmail@testdomain.local -From other@example.com ...`
#Send message to test email locally
`> mail testmail@testdomain.local`
`message`
#Send message outside of system to the same email
`remote PS>  Send-MailMessage -To testmail@testdomain.local -From other@example.com ...`
### Expected results:
first message not signed,
second - signed
third - not signed
### Actual results:
first message not signed,
second - signed
third - *signed*
### Configuration:
```
#/etc/rspamd/override.d/dkim_signing.conf 
path = "/var/lib/rspamd/dkim/common.$selector.key";
selector = "dkim";
allow_username_mismatch = true;
sign_networks = 127.0.0.1/32, [::1], [FE80::]/10, [FEC0::]/10, 10.1.101.0/24
```
```
# other sign_networks variant: sign_networks = /etc/rspamd/override.d/my_networks
#and content is
127.0.0.1/32
[::1]
[FE80::]/10
[FEC0::]/10
10.1.101.0/24
```
### Additional information:
Remote messages sended from 10.1.5.5 which outside of `sign_networks`

**Comment by fatalbanana** [comment]
You'll want to set `sign_local = false;` to disable signing signing for local networks. Signing will still be enabled for authenticated users, which is not as easily solved.

**Comment by MVKozlov** [comment]
I just want to sign not only `local` messages but `local` + `my_private_network`
So I setup `sign_networks` to include my private network addresses

May be I misuse `sign_networks` but why message start get signed after local pickup ? this looks like a bug.

**Comment by fatalbanana** [comment]
Messages from local networks are selected for signing if `sign_local = true` in configuration, which is default. If `sign_networks` is set, hosts in this map are selected for signing too, it is not exclusive with other options.

https://rspamd.com/doc/modules/dkim_signing.html#principles-of-operation

**Comment by MVKozlov** [comment]
yes! I see,
But the question is: why message from @otherdomain.com and from other network that NOT listed in `sign_networks` appears **signed**.
And because it happen right after rspamd sign local message that it should sign because of `sign_local = true;` It look like rspamd cache 'I should sign' state and from that moment sign all messages!

**Comment by MVKozlov** [comment]
I enabled debug and saw at `dkim_sign_tools.lua:38: mail is from local address`

Seems I misunderstanded what meaning of `sign_local = true;`
The doc: # If false, messages from local networks are not selected for signing

I supposed that local network is the network to which the current ip address belongs.
 but seems you mean that local networks - is any [Private network](https://en.wikipedia.org/wiki/Private_network)

If it is so, that should be more clear from the docs

**Comment by Jean-Daniel** [comment]
I may be wrong, but I think local networks are networks defined as local in options.inc

```
local_addrs = "192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, fd00::/8, 169.254.0.0/16, fe80::/10";
```

**Comment by MVKozlov** [comment]
Thanks, But its really hard to find.  I think this should be mentioned somewhere in quick start.

**Comment by MVKozlov** [comment]
https://github.com/vstakhov/rspamd.com/pull/308
