### ISSUE TITLE
DKIM is sometimes producing invalid signature

### ISSUE THREAD

**Issue by azurit** [vstakhov/rspamd#1987]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
Debian 8.10

### Description (Please provide a descriptive summary of the issue):
DKIM (using dkim_signing module) signature is, sometimes, invalid. I'm able to always reproduce it, can i send an e-mail example privately?

**Comment by azurit** [comment]
Really no reaction? We are still having problems with this.

**Comment by dimejo** [comment]
You didn't provide any details. How is anyone supposed to help you without information?

**Comment by vstakhov** [comment]
You can send a message to me (encrypting with my gpg key if needed). However, I won't be able to reproduce it likely without your dkim private key. And what is 'invalid'? And have you debugged `dkim` module?

**Comment by azurit** [comment]
vstakhov i sent you e-mail with some info. Body hash is invalid  and I didn't debug DKIM module, how can i do that? Thank you very much.

**Comment by azurit** [comment]
I would like to get back to this, we are still having problems with it.

I enabled debug for dkim module (pls update the documentation, as it is saying that only dkim module can be debugged, i'm using dkim_signing), here is the result:

Mar  2 14:56:43 server00 rspamd[4247]: <718bd6>; dkim; rspamd_dkim_check: bh value mismatch: cc78979a584b5330db95a6001babb0255492d2df633bdd2d2859201050534caa versus a2e53e6df0095ec443f688d6dc4d11e166daf7c9fd3537ddc2d828080d32387f, try add CRLF

Mar  2 14:56:43 server00 rspamd[4247]: <718bd6>; dkim; rspamd_dkim_check: bh value mismatch: cc78979a584b5330db95a6001babb0255492d2df633bdd2d2859201050534caa versus 4a93170a167666776932697beb45715a387381e9f8aadcc0f40a7527601d5c3d, try add LF

Mar  2 14:56:43 server00 rspamd[4247]: <718bd6>; dkim; rspamd_dkim_check: bh value mismatch: cc78979a584b5330db95a6001babb0255492d2df633bdd2d2859201050534caa versus d14b2e13c295b64a5616b528e8e4ba4094ed0cdc91c14055fc86988c7065e2c9

**Comment by vstakhov** [comment]
I think you have an issue with newlines. Please normalize them in your MTA before signing.

**Comment by azurit** [comment]
This is happening only sometimes (as i stated before), i don't see how an i suppose to fix this on my side. I'm using standard Postfix (2.11.3 from Debian Jessie).

**Comment by azurit** [comment]
I tried to change e-mail generation function to use '\r\n' instead of '\n', i also tried to add '\n' and '\r\n' at the end of email, no luck.

**Comment by azurit** [comment]
i got it! Problem is here:
http://www.postfix.org/postconf.5.html#smtp_line_length_limit

Postfix is splitting long lines by 'CRLF<space>'. Thank you for help.
