### ISSUE TITLE
Is there any configuration option for skipping SPF check for some ip addresses?

### ISSUE THREAD

**Issue by MVKozlov** [vstakhov/rspamd#1997]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Rspamd version:
1.6.5
### Description (Please provide a descriptive summary of the issue):

Is there any configuration option for skipping SPF check for some ip addresses ?
I need to skip only SPF check for one ip address. All other checks should be in place.
May be some whitelist for SPF only...

**Comment by fatalbanana** [comment]
Yes, SPF module has an IP whitelist:
~~~
# /etc/rspamd/local.d/spf.conf
# could be a file/URL:
whitelist = "/etc/rspamd/spf_whitelist.map";
# or inline:
# whitelist = ["8.8.8.8", "8.8.4.4"];
~~~

The way to disable any check by IP address is using [settings](https://rspamd.com/doc/configuration/settings.html).

**Comment by MVKozlov** [comment]
thanks :)
