### ISSUE TITLE
can't read SMFIC_BODYEOB reply packet header (since 1.7.0-0~git104~d10ece3ba~stretch)

### ISSUE THREAD

**Issue by sbadia** [vstakhov/rspamd#2005]
### Classification

* [x] Other bug

### Reproducibility

* [x] I didn’t try

### Rspamd version:

* `1.7.0-0~git106~98170e8b0~stretch`

### Operation system, CPU, memory and environment:
* Debian stretch, amd64 with Postfix MTA

### Description (Please provide a descriptive summary of the issue):

Since rspamd `1.7.0-0~git104~d10ece3ba~stretch`, when I receive an e-mail, i always got this warning from rspamd_proxy :

```
2018-01-29 13:32:36 #14134(rspamd_proxy) <b4d057>; proxy; proxy_accept_socket: accepted milter connection from ::1 port 0
2018-01-29 13:32:36 #14134(rspamd_proxy) <b4d057>; proxy; proxy_milter_error_handler: abnormally closing milter connection from: ::1, error: invalid macro command (no name)
```

```
Jan 29 13:32:36 mail postfix/cleanup[14160]: warning: milter inet:localhost:11332: can't read SMFIC_BODYEOB reply packet header: Success
```

**Note**: With the same rspamd/postfix configuration with the package `1.7.0-0~git103~f74c2585f~stretch` everything worked fine, but the problem appear with `1.7.0-0~git104~d10ece3ba~stretch` and this problem is still present with `1.7.0-0~git106~98170e8b0~stretch`

I upgraded my package on this date
```
2018-01-27 16:09:49 upgrade rspamd:amd64 1.7.0-0~git103~f74c2585f~stretch 1.7.0-0~git104~d10ece3ba~stretch
```
![rspamd stats](https://pub.sebian.fr/rspamd.png)

### Steps to reproduce:

* Receive an email

### Configuration:

* Postfix: `mail_version = 3.1.6`
* Rspamd: `1.7.0-0~git106~98170e8b0~stretch`
 * default configuration
 * redis enabled
 * logging to syslog

### Additional information:

```
# /etc/postfix/main.cf
smtpd_milters = inet:localhost:11332
milter_protocol = 6
milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
# skip mail without checks if something goes wrong
milter_default_action = accept
```

Thanks in advance!

**Comment by sbadia** [comment]
Thanks! This issue is now fixed with package `1.7.0-0~git107~759bd5e95~stretch`.
I didnd't see, but it seems similar to https://github.com/vstakhov/rspamd/issues/1998#issuecomment-361151574

**Comment by fpiraneo** [comment]
Hi, I've the same issue.

Configuration:
- Ubuntu 18.04
- Postfix 3.3.0
- rspamd 1.7.6-0\~git165\~bd43881c9~bionic

In mail.log:
```
Jun 16 12:52:15 vps04 postfix/cleanup[13495]: warning: milter inet:127.0.0.1:11332: can't read SMFIC_BODYEOB reply packet header: Success
Jun 16 12:52:15 vps04 postfix/cleanup[13495]: EF1BB1E405D7: milter-reject: END-OF-MESSAGE from 66-220-155-140.mail-mail.facebook.com[66.220.155.140]: 4.7.1 Service unavailable - try again later; from=<notification+i_jhkwid@facebookmail.com> to=<francesco@piraneo-canepa.ch> proto=ESMTP helo=<mx-out.facebook.com>
Jun 16 12:52:20 vps04 postfix/smtpd[13491]: disconnect from 66-220-155-140.mail-mail.facebook.com[66.220.155.140] ehlo=2 starttls=1 mail=1 rcpt=1 data=0/1 rset=1 quit=1 commands=7/8
```

In syslog:
```
Jun 16 12:52:15 vps04 kernel: [52879.072938] traps: rspamd[13502] general protection ip:55b407064018 sp:7fff61543650 error:0 in rspamd[55b406e62000+a6c000]
```

Postfix configurations:
```
smtpd_milters = inet:127.0.0.1:11332
non_smtpd_milters = inet:127.0.0.1:11332
milter_protocol = 6
milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
```

Server is configured as the following tutorial:
https://workaround.org/ispmail/stretch/filtering-out-spam-with-rspamd

If you need extra info please just ask.

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
