### ISSUE TITLE
filter "reject" on history-page

### ISSUE THREAD

**Issue by linuzer** [vstakhov/rspamd#2010]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Description (Please provide a descriptive summary of the issue):
If you choose the filter "reject" on the history tab, then all rejected mails (soft and hard rejects) are displayed. I would expect to see only the hard rejected ones. The other filters work like this, so you see only what you have choosen. 

### Steps to reproduce:
- click on "history"
- choose filter "reject"
- observe the result
### Expected results:
only hard rejects
### Actual results:
all rejects - soft and hard ones

**Comment by moisseev** [comment]
https://github.com/vstakhov/rspamd/issues/1604#issuecomment-296455656
