### ISSUE TITLE
get_received_headers failing

### ISSUE THREAD

**Issue by geromueller** [vstakhov/rspamd#2011]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5-4~stretch

### Operation system, CPU, memory and environment:
Debian Stretch
Postfix 3.1.6-0+deb9u1

### Description (Please provide a descriptive summary of the issue):
call to ((NULL)) failed (2): /usr/share/rspamd/lua/rbl.lua:379: bad argument #1 to 'ipairs' (table expected, got nil); trace: [1]:{[C]:-1 - ipairs [C]}; [2]:{/usr/share/rspamd/lua/rbl.lua:379 - fun [Lua]}; [3]:{/usr/share/rspamd/lib/fun.lua:30 - call_if_not_empty [Lua]}; [4]:{/usr/share/rspamd/lib/fun.lua:174 - each [Lua]}; [5]:{/usr/share/rspamd/lua/rbl.lua:378 - [Lua]};

### Additional information:
Everything worked before, no change on my side.

**Comment by geromueller** [comment]
After removing no more needed packages libluajit-5.1-2* libluajit-5.1-common* it works again.

**Comment by geromueller** [comment]
Could you create a new release? many fixed from june 17 are not availabel yet!

**Comment by fatalbanana** [comment]
It should be fixed in 1.6.6.
