### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Tikam02** [vstakhov/rspamd#2015]
## Other bug
There is no Installation Guide

**Comment by dimejo** [comment]
The [download page](https://rspamd.com/downloads.html) has install information for different OSes and even a build guide. Are you missing something?

**Comment by Tikam02** [comment]
i though installation will be in github page.sorry for the misunderstanding.

**Comment by fatalbanana** [comment]
[the quickstart](https://rspamd.com/doc/quickstart.html) together with the [downloads page](https://rspamd.com/downloads.html) are this.
