### ISSUE TITLE
Unusual high score caused by URI_HIDDEN_PATH 

### ISSUE THREAD

**Issue by viktor-wbc** [vstakhov/rspamd#2029]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [X] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Operation system, CPU, memory and environment:
Ubuntu 16.04
### Description (Please provide a descriptive summary of the issue):

One of our customers mail got rejected because of a extrem high spamscore of 64 caused only by the check URI_HIDDEN_PATH. When I take a look at the mail headers I cannot find the reason for a high score like this. 

First I was locking for URLs because the description of the check says "URL contains a UNIX hidden file/directory". I could locate a couple of URLs and find out that one URL, which was like this "https://www.domain.tld/shop/...", cause one point in URI_HIDDEN_PATH. The expression "https://www.domain.tld/shop/..." is 4 or 5 times in this mail, but when I unterstand

reconf['URI_HIDDEN_PATH'] = {
  re = "/\\/\\..+/U",
  description = "URL contains a UNIX hidden file/directory",
  score = 1.0,
  one_shot = true,
  group = "compromised_hosts"
}

correctly, "one_shot = true" prevent multiple hits. So the other 63 points I cannot explain. I'm not familiar with lua but what exactly does the regular expression "/\\/\\..+/U" looks for? Is it possible that it hits not only URLs but even other string constellations?

If you like I can provide the header in a private message. 

KInd regards,

Viktor

**Comment by fatalbanana** [comment]
Can you reproduce it immediately after restart?- It might have been fixed in 1.6.6.

Rule is looking for something like "/." in URLs.

**Comment by viktor-wbc** [comment]
Update to 1.6.6. fixed the issue! Scaning the same mail only hits URI_HIDDEN_PATH once!
