### ISSUE TITLE
Rspamd_proxy DNS resolving not working

### ISSUE THREAD

**Issue by prilly** [vstakhov/rspamd#2032]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.6
### Operation system, CPU, memory and environment:
Debian 9, xeon x5675, DDR3 48GB ECC, Xenserver VM
### Description (Please provide a descriptive summary of the issue):
Rspamd_proxy is complaining about DNS resolving issues:  Error DNS timeout.
After increasing DNS timeout value from 1s to 10s rspamd_proxy stops complaining about DNS timeout and starts complaining: error querying dns: server fail

So the thing is that rspamd has severe DNS resolving issues at the moment, i have tried to set the DNS nameserver in options.inc to try and use a different DNS server then what is provided by resolv.conf with same results. 

Just to be very clear here, DNS server used by rspamd is a local caching recursive bind9 dns working and verified, tried with other DNS server with same error.

### Steps to reproduce:
Make rspamd_proxy utilize DNS resolving, watch rspamd fails with logentry: error querying dns: server fail
when doing NS lookups

### Expected results:
Working DNS resolving
### Actual results:
Failed DNS lookup

**Comment by vstakhov** [comment]
Can you please dump your DNS traffic generated by Rspamd?

**Comment by ashceryth** [comment]
I think asn-ns.rspamd.com is unreachable. Recognized the same behavior yesterday and started debugging my DNS config but everything looked fine on my side.

So, at the moment:

```
$ ping asn-ns.rspamd.com
PING asn-ns.rspamd.com (144.76.0.235) 56(84) bytes of data.
^C
--- asn-ns.rspamd.com ping statistics ---
20 packets transmitted, 0 received, 100% packet loss, time 19000ms
```

Dig test shows that asn-ns.rspamd.com ist authoritative for uribl.rspamd.com:

```
; <<>> DiG 9.10.3-P4-Debian <<>> uribl.rspamd.com @ns1.highsecure.ru
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6513
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 2
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;uribl.rspamd.com.              IN      A

;; AUTHORITY SECTION:
uribl.rspamd.com.       60      IN      NS      asn-ns.rspamd.com.

;; ADDITIONAL SECTION:
asn-ns.rspamd.com.      60      IN      A       144.76.0.235

;; Query time: 26 msec
;; SERVER: 88.99.142.95#53(88.99.142.95)
;; WHEN: Sat Feb 24 16:02:06 CET 2018
;; MSG SIZE  rcvd: 82

```

**Comment by ashceryth** [comment]
Both emails and asn modules are complaining:

`emails.lua:48: Error querying DNS: query timed out`

`asn.lua:63: error querying dns: server fail`

asn module is also using asn-ns.rspamd.com:

```
;; AUTHORITY SECTION:
asn.rspamd.com.         60      IN      NS      asn-ns.rspamd.com.
```

**Comment by ashceryth** [comment]
Could it be that this is also influencing dmarc module in a way? This what i see in my log since yesterday:

```
<>; lua; dmarc.lua:912: sending report for google.com <>
<>; lua; dmarc.lua:788: got error in tcp callback: IO timeout
<>; lua; dmarc.lua:788: got error in tcp callback: IO timeout
<>; lua; dmarc.lua:788: got error in tcp callback: IO timeout
<wchdow>; lua; dmarc.lua:776: Couldn't send mail for google.com: retries exceeded
```

**Comment by ashceryth** [comment]
asn-ns.rspamd.com is up again. No further DNS issues so far.

```
$ ping asn-ns.rspamd.com
PING asn-ns.rspamd.com (144.76.0.235) 56(84) bytes of data.
64 bytes from static.235.0.76.144.clients.your-server.de (144.76.0.235): icmp_seq=1 ttl=54 time=27.1 ms
64 bytes from static.235.0.76.144.clients.your-server.de (144.76.0.235): icmp_seq=2 ttl=54 time=26.8 ms
64 bytes from static.235.0.76.144.clients.your-server.de (144.76.0.235): icmp_seq=3 ttl=54 time=26.3 ms
64 bytes from static.235.0.76.144.clients.your-server.de (144.76.0.235): icmp_seq=4 ttl=54 time=26.6 ms
^C
--- asn-ns.rspamd.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 26.326/26.761/27.198/0.361 ms
```

**Comment by vstakhov** [comment]
@ashceryth This seems to be unrelated to the original issue. I'm working on resolving issues with asn-ns in the meantime...

**Comment by prilly** [comment]
I can see if i can get it done.

**Comment by prilly** [comment]
I have done some testing and my issue related to DNS resolving seems to be related with the downtime yesterday. I can not reproduce the issue after asn-ns.rspamd.com is up again.

This ticket can be closed.

**Comment by locojohn** [comment]
I am having this issue now every now and then with version 1.8.0:
`
2018-10-12 13:49:45 #2136(rspamd_proxy) <27906d>; lua; emails.lua:55: Error querying DNS(h8ro5d5tqin78zsj6f9f681ipwjdz5zh): server fail
2018-10-12 13:49:45 #2136(rspamd_proxy) <27906d>; lua; emails.lua:55: Error querying DNS(rtcs4sawf155jsna9t5zdgt81xc1uu6g): server fail
2018-10-12 13:49:45 #2136(rspamd_proxy) <27906d>; lua; emails.lua:55: Error querying DNS(ghar387izsgszzaodad7ghuamiktky4d): server fail
`

**Comment by vstakhov** [comment]
You might send too many requests to my URIBL, so it applies rate limits to you. How many messages do you process?

**Comment by locojohn** [comment]
Уважаемый Всеволод,  

I think it was due to the fact that DNSSEC was not properly configured on DNSMASQ which I am using for caching, so I fixed it earlier today and I receive no more messages of that kind.  Wish this was properly reflected in the rspamd documentation.

The mail server load is very light.  There is really not much mail being processed, so I doubt it's about rate limits.

Благодарю,
Andrejs

**Comment by locojohn** [comment]
Hi, the error got back:

`2018-10-29 15:01:42 #1351(rspamd_proxy) <bba871>; lua; asn.lua:69: error querying dns (160.36.104.179.asn.rspamd.com): server fail
2018-10-29 15:01:44 #1351(rspamd_proxy) <bba871>; lua; emails.lua:55: Error querying DNS(ojbi6kia3gmoh1xdek59zh5i3fyz34tc.email.rspamd.com): server fail
2018-10-29 15:01:53 #1351(rspamd_proxy) <b9079b>; lua; asn.lua:69: error querying dns (19.196.156.98.asn.rspamd.com): server fail`

**Comment by ZombehKillah** [comment]
Hi, I have the same problem too:

> 2018-10-29 13:19:38 #841(controller) rdns; rdns_resolver_init: cannot open socket to 8.8.4.4:53 Network is unreachable
> 2018-10-29 13:19:38 #841(controller) rdns; rdns_make_request_full: resolver is uninitialized
> 2018-10-29 13:19:38 #841(controller) rdns; rdns_make_request_full: resolver is uninitialized
> 2018-10-29 13:19:38 #841(controller) rdns; rdns_make_request_full: resolver is uninitialized
> 2018-10-29 13:19:38 #841(controller) rdns; rdns_make_request_full: resolver is uninitialized
> 2018-10-29 13:28:12 #841(controller) rdns; rdns_make_request_full: resolver is uninitialized
> 2018-10-29 13:28:12 #841(controller) rspamd_log_close_priv: Last message repeated 70 times
> 2018-10-29 13:28:32 #655(main) <47f813>; upstreams; rspamd_resolve_addrs: address resolution for fuzzy1.rspamd.com failed: Temporary failure in name resolution
> 2018-10-29 13:28:32 #655(main) <47f813>; upstreams; rspamd_resolve_addrs: address resolution for fuzzy2.rspamd.com failed: Temporary failure in name resolution
> 2018-10-29 13:28:32 #655(main) <f45zff>; cfg; fuzzy_parse_rule: cannot read servers definition
> 2018-10-29 13:28:33 #845(normal) rdns; rdns_resolver_init: cannot open socket to 8.8.4.4:53 Network is unreachable
> 2018-10-29 13:28:33 #843(rspamd_proxy) rdns; rdns_resolver_init: cannot open socket to 8.8.4.4:53 Network is unreachable
> 2018-10-29 13:28:33 #844(controller) rdns; rdns_resolver_init: cannot open socket to 8.8.4.4:53 Network is unreachable
> 2018-10-29 13:28:33 #844(controller) rdns; rdns_make_request_full: resolver is uninitialized
> 2018-10-29 13:28:33 #844(controller) rdns; rdns_make_request_full: resolver is uninitialized
> 2018-10-29 13:28:33 #844(controller) rdns; rdns_make_request_full: resolver is uninitialized
> 2018-10-29 13:28:33 #844(controller) rdns; rdns_make_request_full: resolver is uninitialized

But i can resolve the fuzzy1.rspamd.com manually: 

> ping fuzzy1.rspamd.com
PING fuzzy1.rspamd.com (88.99.142.95) 56(84) bytes of data.
64 bytes from mail.highsecure.ru (88.99.142.95): icmp_seq=1 ttl=53 time=24.7 ms
64 bytes from mail.highsecure.ru (88.99.142.95): icmp_seq=2 ttl=53 time=25.4 ms
64 bytes from mail.highsecure.ru (88.99.142.95): icmp_seq=3 ttl=53 time=24.9 ms
64 bytes from mail.highsecure.ru (88.99.142.95): icmp_seq=4 ttl=53 time=24.8 ms
64 bytes from mail.highsecure.ru (88.99.142.95): icmp_seq=5 ttl=53 time=24.9 ms

Not sure why DNS is failing but i hope this helps to fix the problem

**Comment by vstakhov** [comment]
@locojohn There was a load spike on the NS servers. It should be resolved now. @ZombehKillah your issue is unrelated to Rspamd, fix your networking and don't use public resolvers.

**Comment by dhpowrhost** [comment]
I had loads of these errors yesterday, which makes sense since the NS had load trouble:
`task; rspamd_task_timeout: processing of task timed out, forced processing
lua; asn.lua:69: error querying dns (101.203.47.37.asn.rspamd.com): query timed out`
**however** all messages giving this error did only have BAYES symbol afterwards so a lot of spam messages came through that should have been blocked. It seems that after the error above all checks where skipped. There was not even an R_SPF_DNSFAIL symbol
