### ISSUE TITLE
timezone in logs

### ISSUE THREAD

**Issue by achch** [vstakhov/rspamd#2074]
Ubuntu 14.04.5 LTS
timezone = MSK

after updating from version 1.6.6 to 1.7.0 of the timestamp in the logs (/var/log/rspamd/rspamd.log) rspamd was different by -6 hours from the specified in the system. Tell me where to fix it.

**Comment by vstakhov** [comment]
So it is `-3` instead of `+3`, right?

**Comment by achch** [comment]
Yea that's right

**Comment by ralphM78** [comment]
@vstakhov 

Ubuntu 16.04.4 LTS
Time zone: Europe/Berlin (CEST, +0200)

Timestamp inside logs is -1 hour from the system time. 
Maybe it's a problem with german daylight saving time ?

**Comment by Menta2L** [comment]
I have similar problem  clock is I hour behind . Probably is something related to daylight saving 

[root@pmx02 rspamd]# rspamd -v;timedatectl|grep "Time zone";date;tail -1 /var/log/rspamd/rspamd.log
Rspamd daemon version 1.7.2
Time zone: Europe/Sofia (EEST, +0300)
Thu Apr  5 10:10:16 EEST 2018
2018-04-05 09:10:11 #24758(rspamd_proxy) <67b41b>; proxy; proxy_milter_finish_handler: finished milter connection
