### ISSUE TITLE
100% cpu & memory usage, then restarting service if try view history in web ui

### ISSUE THREAD

**Issue by airmanjoy** [vstakhov/rspamd#2079]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5, 1.7.0
### Operation system, CPU, memory and environment:
Centos 7.4.1708 in ESXI 6.0, Intel(R) Xeon(R) CPU E5-2620, 6GB
### Description (Please provide a descriptive summary of the issue):
100% cpu & memory usage, then restarting service if try view history in web ui

Multimap module includes 5 user rules.
After adding of new (6th) rule to multimap module the specified issue occurs.
Cpu usage is 100%, memory usage increasing to 100% for few second. After some time the process is restarting and working fine while history page is not refreshed.
If new rule is removed, the work is normalized (in version 1.6.5). Update to version 1.7.0 exacerbates the problem, the history does not  shown even with working settings of version 1.6.5, on 5 user rules in multimap module.
Disabling of SELinux is not efective.
UPDATE:
Adding anything to any config file in /etc/local.d leads to the occurrence of this issue.
### Steps to reproduce:
adding of new rule to the multimap module
### Expected results:
ability of adding several rules to multimap module and viewing of history in web ui

**Comment by hardware** [comment]
Do you have enough RAM ? is your swap used a lot ? Maybe same issue as : https://github.com/hardware/mailserver/issues/193

**Comment by airmanjoy** [comment]
Virtual machine have RAM 6 Gb, used 2.2Gb.
Issue in interfacing rspamd to redis database. On test server i was removed redis database, and this issue is gone. (nrows = 2000);
If issue can be solved in this way, I'll write about it.

**Comment by stephdl** [comment]
I confirm if I erase/remove the dump.db then I restart redis, the issue goes away

**Comment by airmanjoy** [comment]
Yes, after removing of dump.rdb all works fine. Apparently, this operation should be performed after each update of rspamd with yum.

**Comment by stephdl** [comment]
With all your respect @airmanjoy I would understand why you closed the Issue, as long I understand your answer it is no more than a workaround that you propose and no a *real* solution to solve this issue.
Can this issue could stay opened until a solution (at code level) is found. If the db must be erased and I'm not sure it is the good thing to do , it can be done at the rpm level

**Comment by stephdl** [comment]
never mind, duplicate if https://github.com/vstakhov/rspamd/issues/1952
