### ISSUE TITLE
Regexp cannot be safely specified in UCL

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#2080]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
Regexp cannot be safely specified in UCL; a new way to quote strings is needed (modules which encourage regexp in configuration like multimap & antivirus are affected).

### Steps to reproduce:
Specify something like this in config:
~~~
test {
  re = "/\.*/";
}
~~~
and compare to `rspamadm configdump test`

### Expected results:
Effective configuration looks like configuration file.

### Actual results:
Effective configuration is damaged

~~~
*** Section test ***
re = "/.*/";

*** End of section test ***
~~~

**Comment by smfreegard** [comment]
Don't you have to double-escape regexp like everywhere else?

e.g. `re = "/\\.*/";`

**Comment by fatalbanana** [comment]
No, that becomes literally `\\` in this case.

In Lua I'd recommend using square quotes for regexes as they're not escaped, eg. `re = [[/\.*/]]` is fine.

**Comment by fatalbanana** [comment]
As workaround, specifying the configuration in Lua works fine.

~~~lua
config.multimap = {}
config.multimap.URL_MAP_RE = {
  ['filter'] = [[tld:regexp:/\.[^.]+$/]],
  ['map'] = '/tmp/url.map',
  ['type'] = 'url',
}
~~~

**Comment by vstakhov** [comment]
I think about adding of single quotes in UCL for that purposes.

**Comment by vstakhov** [comment]
Should be doable now by re = '/\.*/'

**Comment by fatalbanana** [comment]
That seems to work fine; thanks!
