### ISSUE TITLE
rspamd checking outgoing mail for dmarc and spf

### ISSUE THREAD

**Issue by flixman** [vstakhov/rspamd#2082]
I have a postfix installation communication via milter with rspamd. The checks for dmarc and spf are performed to outgoing mail, and then the receiver gets a header that looks like

Authentication-Results: dmarc=fail reason="No valid SPF, No valid DKIM" header.from=server.org (policy=reject); spf=softfail smtp.mailfrom=me@server.org

I have seen that in rmilter there is the option of strict_auth for this purpose, but I have not been able to find the equivalent option in milter. Am I doing something wrong?

**Comment by flixman** [comment]
Could it be that skip_authenticated is not true by default? If I explicitly add it, then the Authentication-Results for outgoing mail is not added, and no mentions to DKIM/SPF are logged, neither.

**Comment by fatalbanana** [comment]
Authentication-Results header will be added if configured irrespective of whether DKIM/SPF checks actually happened (likely they don't happen for authenticated users). `skip_authenticated` is default true indeed; perhaps something in your config influences this (what does `rspamadm configdump milter_headers` show?).

**Comment by flixman** [comment]
This is the result of the command:

skip_authenticated = true;
use [
 "authentication-results",
 "x-spamd-bar",
]
enabled = true;
March 29, 2018 12:45 PM, "Andrew Lewis" <notifications@github.com (mailto:%22Andrew%20Lewis%22%20<notifications@github.com>)> wrote:
	Authentication-Results header will be added if configured irrespective of whether DKIM/SPF checks actually happened (likely they don't happen for authenticated users). skip_authenticated is default true indeed; perhaps something in your config influences this (what does rspamadm configdump milter_headers show?).

**Comment by fatalbanana** [comment]
I can't replicate the issue you've described I'm afraid.

**Comment by flixman** [comment]
Well, as it works as expected with skip_authenticated set to "true".. I think I will close it, and done. Thank you!!

**Comment by fatalbanana** [comment]
That shouldn't make a difference as it's a default setting (in my testing it works as expected with this omitted).
