### ISSUE TITLE
statistical module ignores local.d/redis.conf db setting

### ISSUE THREAD

**Issue by WRMSRwasTaken** [vstakhov/rspamd#2083]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.0
### Description (Please provide a descriptive summary of the issue):
The statistical module ignores the setting `db = 3;` in `local.d/redis.conf`, although 
```
read_servers = "127.0.0.1:6379";
write_servers = "10.8.0.1:6379";
```
is recognized. Also, for example the ip-score module recognizes this option and stores the information in db 3.
### Expected results:
Bayes token data is stored in database defined in `db` (in my case 3).
### Actual results:
Bayes token data is stored in database 0.

**Comment by hardware** [comment]
I can confirm that, and it explain my problem with this example : https://github.com/vstakhov/rspamd.com/issues/319

This problem appears when I removed `servers`, `password`, `database` parameters in statistical module configuration.

**Comment by vstakhov** [comment]
DB should be equal to a **stiring** not a number.

**Comment by WRMSRwasTaken** [comment]
Hmm. seems a bit odd, as Redis uses numbers for working with muldiple databases, and the ip-score module recognizes using number.

**Comment by vstakhov** [comment]
Lua code that parses Redis dbname does that conversion explicitly. C code doesn't.
