### ISSUE TITLE
milter: TLS cert CN interpreted as authenticated user name

### ISSUE THREAD

**Issue by bp79** [vstakhov/rspamd#2087]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.0

### Operation system, CPU, memory and environment:
Debian 9, Postfix 3.1.8

### Description (Please provide a descriptive summary of the issue):
When Postfix receives a "Trusted TLS connection" (i.e. not just an "Anonymous TLS connection"), Rspamd interprets the common name from the certificate as user name, seemingly equivalent to a SASL-authenticated user. Going forward, Rspamd will skip various checks, like DKIM, DMARC, etc. This behavior was not present in Rspamd 1.6.6. These checks should be performed!

### Log excerpts:

Here comes the Trusted TLS connection ...

```
postfix/smtpd: connect from mail-lf0-f51.google.com[209.85.215.51]
postfix/smtpd: Trusted TLS connection established from mail-lf0-f51.google.com[209.85.215.51]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
```

Rspamd receives the milter values ...

```
(rspamd_proxy) <5165f3>; task; rspamd_protocol_handle_headers: read IP header, value: 209.85.215.51:34302
(rspamd_proxy) <5165f3>; task; rspamd_protocol_handle_headers: read user-agent header, value: Postfix 3.1.8
(rspamd_proxy) <5165f3>; task; rspamd_protocol_handle_headers: unknown header: TLS-Cipher
(rspamd_proxy) <5165f3>; task; rspamd_protocol_handle_headers: unknown header: TLS-Version
(rspamd_proxy) <5165f3>; task; rspamd_protocol_handle_headers: read user header, value: smtp.gmail.com
```

Now Rspamd thinks there is an authenticated user and it skips the checks ...

```
(rspamd_proxy) <5165f3>; proxy; dkim_symbol_callback: skip DKIM checks for local networks and authorized users
(rspamd_proxy) <5165f3>; proxy; spf_symbol_callback: skip SPF checks for local networks and authorized users
(rspamd_proxy) <5165f3>; lua; dmarc.lua:218: skip DMARC checks for local networks and authorized users
```

### Configuration excerpts:

Postfix main.cf:
```
smtpd_milters = inet:127.0.0.1:11332
milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
milter_default_action = accept
```

Rspamd local.d/worker-proxy.inc:
```
bind_socket = "127.0.0.1:11332";
milter = yes;
upstream "local" {
    default = yes;
    self_scan = yes;
}
```

**Comment by vstakhov** [comment]
Can you enable milter debug (`debug_modules = ["milter"]` in local.d/logging.inc)?

**Comment by bp79** [comment]
Here is some additional logging output, with milter debug enabled:

```
(rspamd_proxy) <89fee4>; milter; rspamd_milter_process_command: got macro command
(rspamd_proxy) <89fee4>; milter; rspamd_milter_process_command: got macro: {tls_version} -> TLSv1.2
(rspamd_proxy) <89fee4>; milter; rspamd_milter_process_command: got macro: {cipher} -> ECDHE-RSA-AES128-GCM-SHA256
(rspamd_proxy) <89fee4>; milter; rspamd_milter_process_command: got macro: {cipher_bits} -> 128
(rspamd_proxy) <89fee4>; milter; rspamd_milter_process_command: got macro: {cert_subject} -> smtp.gmail.com
(rspamd_proxy) <89fee4>; milter; rspamd_milter_process_command: got macro: {cert_issuer} -> Google Internet Authority G2
```

"cert_subject" ist later on treated as user name:

```
(rspamd_proxy) <89fee4>; proxy; rspamd_task_write_log: id: <DELETED@mail.gmail.com>, qid: <DELETED>, ip: 209.85.215.47, user: smtp.gmail.com, from: <SOME_USER@gmail.com>, (default: F (no action): [0.40/15.00]
```

**Comment by vstakhov** [comment]
Cert subject is used when you have a client certificate authentication. I've not expected that Postfix uses it for anything but client authentication. I'm not sure other MTAs (e.g. Sendmail) do the same and I don't know how to distinguish that from the case where certificates are used for authentication.

**Comment by vstakhov** [comment]
I think it is related to the Postfix configuration option: 
http://www.postfix.org/postconf.5.html#smtpd_tls_ask_ccert

Another possible culprit is DANE.

**Comment by philfry** [comment]
afaik Postfix uses client certificates only for authentication. So basically there's nothing wrong in rspamd using the client certificate subject as username, and there's no possibility for it to check whether or not the subject certificate is a valid and authenticated user.
The problem here is that you're asking for a client certificate for authentication without penalizing (rejecting) bad certificates. That's why Postfix just passes the _"trusted"_ certificate to its milters.
Usually you should have your mta configured **not** to ask for client certificates on port 25 or 465 (neither doing any client authentication at all on these ports). That's what port 587 (submission) is for. Just my 2¢.

**Comment by vstakhov** [comment]
That makes sense but I'm a bit scared of a potential impact of this issue for those who are using some guide that suggests to do that. I plan to add an explicit option `client_ca_name` to define what issuer is allowed to be treated as a trusted CA for users certificates.

**Comment by bp79** [comment]
I think that's a good way to address this issue. Thanks!
