### ISSUE TITLE
version 1.7.0 can't be built with optimisation (-flto fails build)

### ISSUE THREAD

**Issue by oxpa** [vstakhov/rspamd#2091]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.0

### Operation system, CPU, memory and environment:
linux, x86_64, gcc 4.8.5

### Description (Please provide a descriptive summary of the issue):
when building with optimization on gcc 4.8.5 (`cmake -DENABLE_OPTIMIZATION=ON` ) linker fails with messages like `function_name needs isa option -m32 -maes`
Later gcc versions work well.
### Compile errors (if any):
```
[ 95%] Linking C executable rspamadm
/usr/lib64/gcc/x86_64-suse-linux/4.8/include/wmmintrin.h: In function ‘aes_key_expand’:
/usr/lib64/gcc/x86_64-suse-linux/4.8/include/wmmintrin.h:88:3: error: ‘__builtin_ia32_aeskeygenassist128’ needs isa option -m32 -maes
   return (__m128i) __builtin_ia32_aeskeygenassist128 ((__v2di)__X, __C);
```
### Steps to reproduce:
add `-DENABLE_OPTIMIZATION=ON ` or `-DCMAKE_C_OPT_FLAGS="-flto"` to cmake command
### Expected results:
build as usual
### Actual results:
build fails

**Comment by vstakhov** [comment]
It seems that your gcc version is bugged. Please use a more recent one.

**Comment by vstakhov** [comment]
I don't know how to fix compiler bugs in Rspamd. It is likely caused by AES-NI backend for libottery PRNG. You might try to disable it in the code, it is safe enough as libottery will just use chacha20 PRF for that purposes.

**Comment by oxpa** [comment]
OK, thank you. Let's consider this 'bug' resolve
