### ISSUE TITLE
Loading dynamic map from source with http2 fails

### ISSUE THREAD

**Issue by pdreissen** [vstakhov/rspamd#2109]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.1
### Operation system, CPU, memory and environment:
Debian 9
### Description (Please provide a descriptive summary of the issue):
When loading a dynamic map from a source with http2 enabled (apache 2.4.25) it fails with the following error: 

2018-03-23 21:24:56 #3629(controller) <ymayxe>; map; http_map_error: error reading https://xxxx(xx.xx.xx.48:8080): connection with http server terminated incorrectly: HTTP parser error: success

When disabling http2 (Protocols h2 h2c http/1.1)  it loads correctly: 

2018-03-23 22:19:52 #11707(controller) <ymayxe>; map; http_map_finish: https://xxxx(xx.xx.xx.48:8080): read map data 155648 bytes, next check at Fri, 23 Mar 2018 21:24:52 GMT

### Steps to reproduce:
Enabling and disabling http2 on the source

### Expected results:
Correctly loading the dynamic map

### Actual results:
Failing when http2 is enabled

**Comment by vstakhov** [comment]
HTTP2 is not supported and there are no plans to support it in future.

**Comment by pdreissen** [comment]
Ok not the answer i was hoping for, but if that is the case i need to get a workaround in place. Thanks for your answer!
