### ISSUE TITLE
Memory leak in 1.7.2?

### ISSUE THREAD

**Issue by sschindel** [vstakhov/rspamd#2120]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.2-1~stretch

### Operation system, CPU, memory and environment:
Linux mx1 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             12
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 37
Model name:            Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz
Stepping:              1
CPU MHz:               2265.834
BogoMIPS:              4533.49
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-5
NUMA node1 CPU(s):     6-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm epb kaiser dtherm arat

### Description (Please provide a descriptive summary of the issue):

We've got 19 servers running with rspamd 1.7.0, one with 1.7.1 and one with 1.7.2. Same hardware configuration, same rspamd configuration. After 19 hours of runtime the 1.7.2 normal processes occupy around 24GiB memory, much more compared to the older versions.

**Comment by vstakhov** [comment]
Indeed, that's my fault :( I have fixed it by https://github.com/vstakhov/rspamd/commit/7494b0f7ddbcd098da6cf02b40c1db4878cc8310#diff-0e66cac3ea5040492affc93072230a16 and will provide updated mainline packages soon.

**Comment by vstakhov** [comment]
Packages are ready, please update.

**Comment by antares2001** [comment]
What is the package version with the fix? This guy?
# apt-cache policy rspamd
rspamd:
  Installed: 1.7.2-2~stretch
  Candidate: 1.7.2-2~stretch
  Version table:
 *** 1.7.2-2~stretch 500
        500 http://rspamd.com/apt-stable stretch/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by sschindel** [comment]
Yes, thanks for the quick fix. It's working now as expected.
