### ISSUE TITLE
Soft-reject messages always have score of zero in history

### ISSUE THREAD

**Issue by bjoe2k4** [vstakhov/rspamd#2132]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.3-git
### Operation system, CPU, memory and environment:
Archlinux
### Compile errors (if any):
none related
### Expected results:
show actual score
### Actual results:
score is always 0/15

**Comment by vstakhov** [comment]
Score is a property that is considered internal in Rspamd. Don't rely on it, don't use it and don't complain if it does not follow your expectations. For this particular case, soft reject means 'temporarily delay' this email. Score is meaningless in this case.
