### ISSUE TITLE
Oversigning dkim headers broken

### ISSUE THREAD

**Issue by bjoe2k4** [vstakhov/rspamd#2136]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.3 git-master
### Operation system, CPU, memory and environment:
Archlinux
### Description (Please provide a descriptive summary of the issue):
When oversigning dkim headers, it is not possible to sign a header twice (once with content, once as empty). Instead it is either signed once or threee times.
### Expected results:
```
sign_headers = "from:from:to:to:cc:cc:subject:subject";
h=from:from:to:to:cc:cc:subject:subject;
```
```
sign_headers = "from:to:cc:subject";
h=from:to:cc:subject;
```
```
sign_headers = "from:to:from:cc:subject";
h=from:to:from:cc:subject;
```
### Actual results:
```
sign_headers = "from:from:to:to:cc:cc:subject:subject";
h=from:from:from:to:to:to:cc:cc:cc:subject:subject:subject;
```
```
sign_headers = "from:to:cc:subject";
h=from:to:cc:subject;
```
```
sign_headers = "from:to:from:cc:subject";
h=from:to:from:from:cc:subject;
```
### Additional information:
Actually it shouldn't be too difficult to implement a new list `oversign_headers`, that defines headers that are signed `n+1` times, if the header is present `n` times.

Example Mail:
```
To: test@test.com
From: test2@test.com
Subject: Test
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit
Content-Language: en-US

Test
```

```
sign_headers = "from:to:cc:subject";
oversign_headers = "from:cc";
h=from:from:to:cc:subject;
```

**Comment by bjoe2k4** [comment]
I think the current default behaviour after https://github.com/vstakhov/rspamd/issues/1949 / https://github.com/vstakhov/rspamd/commit/1e929b744952674120545cbbd1643b6fd1910aab is highly unflexible and limited in the way oversigning is enforced regarding headers that are not present. It should be a high priority to stay compatible with opendkim. This is where most people are coming from and such compatibility will increase the adoption of rspamd.

The current implementation and default `sign_headers` does

- oversigning on headers that are ***not*** present (and therefore enforcing it)
- no oversigning on headers that are present

The most sane, flexible and complete solution would be imho to implement the following:
`sign_headers` should list headers that are:
- signed `n` times if they are present `n` times (currently not the case).
- for the `n = 0` case this would mean that headers are not signed if they are not present.
a new configuration option `oversign_headers` should be introduced:
- headers listed in this list should be oversigned (i.e. signed `n + 1` times)
- there should be a reasonable default of this options, i.e. `oversign_headers = "from:sender:to:cc:subject:content-type:content-transfer-encoding`

**Comment by vstakhov** [comment]
It is **not** my high priority to stay with incorrect and dangerous behaviour of OpenDKIM I'm afraid. I'll check the second issue you've mentioned as it looks like a bug indeed. The first one looks reasonable to me and I see no good reason to change it.

**Comment by ChessSpider** [comment]
@vstakhov About the automatic, enforced double-signing, I'd say it's more of a feature than a bug.  Though I agree it may be made optional; but I don't see why anyone would not want double-signing. From a safety perspective it does'nt matter if any header is signed double-signed, triple-signed or quadruple-signed.. As long as it is at least double-signed.

**Comment by bjoe2k4** [comment]
Sorry to be so persistent, but @vstakhov can you elaborate why the behaviour of opendkim (which is essentailly the one that i have described in the last paragraph) is incorrect and dangerous?

For opendkim, among several others parameters there are `SignHeaders`, which corresponds to the rspamd parameter `sign_headers` and there is `OversignHeaders`, corresponds to my proposed `oversign_headers`.

For example the Debian default is:

- `SignHeaders`  includes all headers described in RFC6376, Section 5.4
- `OversignHeaders From`

This prevents from adding another forged `From` header. For obvious reasons, this can be improved and rspamd should do this better by populating oversign_headers with a more secure default. However i cannot find any sane reason why headers like `list-id:list-owner:list-unsubscribe:list-subscribe:list-post` should be oversigned by default. If people wish to do so, they could simple set `oversign_headers = sign_headers` (if my proposal is accepted).

**Comment by ChessSpider** [comment]
Again, basically:
> By only signing headers if they're present, headers can be injected. Including important headers like CC or worse, Reply-To.

Basically, your DKIM-implementation is flawed if you do 'opportunistic signing'  as you describe. Just leave out the header as a whole, always. Or take it into account when signing, always. 

Think; What do you think should be expected behavior if a mailserver receives a mail with a ``list-id`` header present but it's missing in the DKIM-Signature. Trust it? And what if a mailserver receives a mail with a ``list-id`` header present and it's in the DKIM-Signature. Also trust it? 

So what's the effective added security benefit? None. 

Either sign the header, and do it correctly by at least double-signing it. Or don't sign the header at all.

**Comment by vstakhov** [comment]
I have tried to fix it. It is now possible to specify oversigning headers as following:

```
sign_headers = "(o)from:subject";
```

So `from` will be oversigned and `subject` won't be oversigned. Can you please check if that satisfies your expectations?

**Comment by ChessSpider** [comment]
@vstakhov please make it opt-out, make the default oversign..

**Comment by vstakhov** [comment]
```
static const gchar default_sign_headers[] = ""
		"(o)from:(o)sender:(o)reply-to:(o)subject:(o)date:(o)message-id:"
		"(o)to:(o)cc:(o)mime-version:(o)content-type:(o)content-transfer-encoding:"
		"resent-to:resent-cc:resent-from:resent-sender:resent-message-id:"
		"(o)in-reply-to:(o)references:list-id:list-owner:list-unsubscribe:"
		"list-subscribe:list-post";
```

**Comment by bjoe2k4** [comment]
The current behavior is now:
- `n=1`: `n + 1` signatures when `(o)` is prepended, `n` signatures otherwise.
- `n=2`: `n + 1` signatures when `(o)` is prepended, `n` signatures otherwise.
- `n=0`: `n + 1` signatures when `(o)` is prepended, `n + 1` signatures otherwise.

The `n = 0` case does not seem to work yet for me.

**Comment by bjoe2k4** [comment]
Thank you again, in fact it does now work as expected, also for the `n=0` case.

Finally, I think everybody should be happy now with the result, which allows flexibility in configuration and is compatible with the way opendkim works.

**Comment by andryyy** [comment]
@ChessSpider @bjoe2k4 

Hi guys, Cyren does not validate oversigned mail... they say our headers are broken. 

Can anyone point me to the correct and not obsolete RFC that says it is indeed allowed to list signed headers n+1?

**Comment by vstakhov** [comment]
https://www.valimail.com/blog/breaking-dkim-or-simply-misunderstanding-how-it-works-in-practice/ ?
