### ISSUE TITLE
UCL understands nan when saving empty/null value

### ISSUE THREAD

**Issue by stephdl** [vstakhov/rspamd#2152]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.2
### Operation system, CPU, memory and environment:
centos7
### Description (Please provide a descriptive summary of the issue):
When you want to disable an action, you set `null` in the static configuration file, but when you set an empty value or a `null` value in the rspamd UI, the value saved in rspamd_dynamic map is `nan`. Of course the action is no more workable because nan is not a score value and the dynamic map is broken, see below
### Steps to reproduce:
blank the value of rewrite_subject or add `null`

### Expected results:
from this in dynamic map

```
[
    {
        "metric": "default",
        "actions": [
            {
                "name": "reject",
                "value": 20.0
            },
            {
                "name": "rewrite subject",
                "value": 9.0
            },
            {
                "name": "add header",
                "value": 8.0
            },
            {
                "name": "greylist",
                "value": 6.0
            }
        ],
        "symbols": [

        ]
    }
]
```
you wait this

```
[
    {
        "metric": "default",
        "actions": [
            {
                "name": "reject",
                "value": 20.0
            },
            {
                "name": "rewrite subject",
                "value": null
            },
            {
                "name": "add header",
                "value": 8.0
            },
            {
                "name": "greylist",
                "value": 6.0
            }
        ],
        "symbols": [

        ]
    }
]
```
### Actual results:
but you get this

```
[
    {
        "metric": "default",
        "actions": [
            {
                "name": "rewrite subject",
                "value": nan
            }
        ],
        "symbols": [

        ]
    }
]
```
### Configuration:
```
[root@prometheus ~]# rspamadm configdump actions
CPU doesn't have SSSE3 instructions set required for hyperscan, disable it
*** Section actions ***
add_header = 7;
reject = 15;
rewrite_subject = 7;
subject = "***SPAM*** %s";
unknown_weight = 1;
greylist = 4;
```

*** End of section actions ***

### Additional information:
As you can see the whole dynamic map is broken when you add a blank or null value, it is likely a huge nasty bug :)

**Comment by vstakhov** [comment]
That's not correct. UCL understands `nan` and treats it properly. `rspamadm configdump` does not show dynamic actions/symbols at all. It is a long story but I see no simple ways to fix it I'm afraid.

**Comment by stephdl** [comment]
Probably you mistaken my Issue, or I probably badly explained it, no matter what the configdump displays, the issue is that the dynamic map is broken when you set an empty value or a `null` value, this is the key @vstakhov 

thank in advance

**Comment by stephdl** [comment]
in fact the issue I saw is not relative to something broken by the `null` value, it is another topic. I probably will open another issue.
Set closed as per the answer of @vstakhov
