### ISSUE TITLE
Avoid giving negative scoring for R_SPF_ALLOW when matched IP space is stupidly large

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#216]
We might want to avoid giving negative scoring for SPF where stupid records are being matched such as:

v=spf1 +all
v=spf1 ip4:0.0.0.0/0 -all
v=spf1 ip4:0.0.0.0/1 ip4:128.0.0.0/1 -all
etc.

Perhaps there should be an upper limit on the number of IPs that can be matched, such as 536,870,912 IPv4 or 5,316,911,983,139,663,491,615,228,241,121,378,304 IPv6 (could be safe to make this smaller too). This might be worth positive scoring. Could work on a sliding scale potentially.
##

**Comment by vstakhov** [comment]
That's true, but maybe we should just write DMARC post-filter to determine the exact policy? I'll open a separate issue for this task.

**Comment by vixns** [comment]
Just got `R_SPF_ALLOW(-1.50)[ip4:0.0.0.0/0]` in some fake canadian pharm email.
What about scoring theses stupid/edge cases to `0.00` ?
