### ISSUE TITLE
spam always are rejected

### ISSUE THREAD

**Issue by markusweb** [vstakhov/rspamd#2199]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.3

### Operation system, CPU, memory and environment:
ubuntu 16.04 lts

### Description (Please provide a descriptive summary of the issue):
i don't get rspamd to just add/rewrite subject. all the mails are rejected.

```
rspamc -v < s.txt
Results for file: stdin (0.002 seconds)
[Metric: default]
Action: reject
Spam: true
Score: 125.00 / 125.00
Symbol: GTUBE (0.00)
Message-ID: e2d80c13-4813-3f41-7ef9-55a6ee3ddac3@xxx.de
Message - smtp_message: Gtube pattern
```

i have defined the 125 in override.d/metrics.conf

```
reject = 125;
add_header = 6;
rewrite_subject = 8;
greylist = 4;
subject = "*** SPAM *** %s";
```
i wan't to have the mails delivered to the user and then filter spam via X-Spam header or via "Subject" into the spam-folder. later i wan't to adjust the metric-values so that i can decide at which level it is true spam. but at the moment it seems that the mails are directly rejected. i can't have them delivered. 

do i miss something?

i followed https://workaround.org/ispmail/stretch/filtering-out-spam-with-rspamd at there it should work with a high reject value...

markus

**Comment by moisseev** [comment]
If the message contains GTUBE pattern then Rspamd sets `reject` action. Period.
Thresholds manipulation doesn't make any sense in this case.
If you need to test `add_header` or `rewrite subject` you can use other patterns:
https://github.com/vstakhov/rspamd/blob/58daf4bbaf190164a901b9c3aaba94bf0599fe52/src/libmime/message.c#L40-L45

**Comment by markusweb** [comment]
thanxs,
you made my day!

i really was wondering why my test mails always were rejected. didn't no that this is realy hardcoded in rspamd.

markus
