### ISSUE TITLE
Output of "rspamadm configdump" contains multiple badly coded strings

### ISSUE THREAD

**Issue by uvelokk** [vstakhov/rspamd#2211]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.4-1~stretch

### Operation system, CPU, memory and environment:
Debian 9

### Description (Please provide a descriptive summary of the issue):
Output of "rspamadm configdump" contains a lot of badly coded strings. 

### Steps to reproduce:
Execute "rspamadm configdump".

### Configuration:
Rspamd: default configuration

### Additional information:
```
stretch:~# uname -a
Linux stretch 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux

stretch:~# echo -e $LANG"\n"$LANGUAGE"\n"$TERM
en_US.utf8
en_US:en
xterm-256color
```

**Comment by vstakhov** [comment]
I don't observe that behaviour.

**Comment by uvelokk** [comment]
Thank you, Vsevolod

In a meantime I put up a small test site:

### Steps to reproduce:

1. Clean minimal install of Debian 9.4 x86_64 (skipped "Select and install software")

2. Configured apt:
	a. echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/99end
	b. echo "APT::Install-Suggests \"0\";" >> /etc/apt/apt.conf.d/99end

3. apt-get update ; apt-get dist-upgrade

4. apt-get install ca-certificates

5. Installed rspamd gpg.key
	a. wget https://rspamd.com/apt-stable/gpg.key
	b. apt-key add gpg.key

6. echo "deb http://rspamd.com/apt/ stretch main" > /etc/apt/sources.list.d/rspamd.list
7. apt-get update
8. apt-get install rspamd
9. systemctl restart rspamd
10. rspamadm configdump > rspamd_174_configdump.txt

[rspamd_174_configdump.txt](https://github.com/vstakhov/rspamd/files/1967001/rspamd_174_configdump.txt)

11. Take a look at the configuration of worker "controller", or RBL mailspike or dnswl, or section "once_received" etc.

Is there any additional information I could give you regarding this issue?

Uve

**Comment by vstakhov** [comment]
I will also issue packages build with this fix.
