### ISSUE TITLE
dkim_signing/sing_networks problem

### ISSUE THREAD

**Issue by andy-igoshin** [vstakhov/rspamd#2216]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.7.3, 1.7.4

### Description (Please provide a descriptive summary of the issue):

dkim_signing/sing_networks problem. the same for arc.

### Expected results:

$ rspamadm configtest
syntax OK

### Actual results:

$ rspamadm configtest
map has static backend but no `data` field
invalid radix map static
syntax OK

$ service rspamd reload
log:
2018-05-03 21:57:29 #11788(main) <dqn3m5>; cfg; lua_config_radix_from_ucl: invalid radix map static

$ rspamadm configdump
map has static backend but no `data` field
invalid radix map static

but config dump has:
dkim_signing {
...
    sign_networks [
        "127.0.0.1",
    ]
...
}

### Configuration:

/etc/rspamd/local.d/dkim_signing.conf:
sign_networks = [127.0.0.1];

**Comment by bjoe2k4** [comment]
What does the logfile say?

**Comment by andy-igoshin** [comment]
2018-05-03 21:57:29 #11788(main) ; cfg; lua_config_radix_from_ucl: invalid radix map static

**Comment by andy-igoshin** [comment]
2018-05-03 21:57:29 #11788(main) <dqn3m5>; cfg; rspamd_map_add_from_ucl: map has static backend but no `data` field
2018-05-03 21:57:29 #11788(main) <dqn3m5>; cfg; lua_config_radix_from_ucl: invalid radix map static

**Comment by bjoe2k4** [comment]
Your configuration is incomplete. You need to define a path variable in `/etc/rspamd/local.d/dkim_signing.conf`

**Comment by andy-igoshin** [comment]
adding of the path does not resolve this problem.

/etc/rspamd/local.d/dkim_signing.conf:
path = "/var/lib/rspamd/dkim/$domain.$selector.key";
sign_networks = [127.2.4.7];

i think the problem is in dkim_signing.lua:137
  if k == 'sign_networks' then
    settings[k] = rspamd_map_add(N, k, 'radix', 'DKIM signing networks')

and arc.lua:530
for k,v in pairs(opts) do
  if k == 'sign_networks' then
    settings[k] = rspamd_map_add(N, k, 'radix', 'DKIM signing networks')

if i replace 'radix' to 'map'  the problem vanishes. but i do not clearly understand what author means here.

**Comment by bjoe2k4** [comment]
Why do you specify brackets around the ip address? Try
sign_networks = 127.2.4.7

However, since this is a local Ip anyways, you most certainly want to use sign_local.

**Comment by andy-igoshin** [comment]
if i set sign_networks = 127.2.4.7 (with or without quotes) then i get such error :

$ rspamadm configtest
invalid map fetching protocol: 127.2.4.7

talking about sign_local i should note that i have to use sign_networks as array according to the design of my construction.

**Comment by bjoe2k4** [comment]
Ufff, put the addresses in a file, one per line and set:
`sign_networks =  "/etc/rspamd/local.d/test.map";`

**Comment by vstakhov** [comment]
I think we have some bug after maps rework being done in 1.7.4.

**Comment by andy-igoshin** [comment]
the same

/etc/rspamd/local.d/dkim_signing.conf:
path = "/var/lib/rspamd/dkim/$domain.$selector.key";
sign_networks = ["127.2.4.7"];


$ rspamadm configtest
map has static backend but no `data` field
invalid radix map static
syntax OK

**Comment by vstakhov** [comment]
That should be fixed now.

**Comment by andy-igoshin** [comment]
i tried, it works. thanks!
