### ISSUE TITLE
Compiler error - "inconsistent operand constraints in an 'asm'"

### ISSUE THREAD

**Issue by awhitesong** [vstakhov/rspamd#222]
Hello, 
I just cloned the repository and while doing `make`, i am getting the following compilation error. If someone could help on this:

    /opt/rspamd/rspamd/src/libcryptobox/cryptobox.c: In function ‘rspamd_cryptobox_cpuid’:
    /opt/rspamd/rspamd/src/libcryptobox/cryptobox.c:69:2: error: inconsistent operand constraints in an ‘asm’
      __asm__ __volatile__ (
      ^

and here is the code snippet giving the error:

    static void
    rspamd_cryptobox_cpuid (gint cpu[4], gint info)
    {
    #if defined(__GNUC__) && (defined(__x86_64__) || defined(__i386__))
	    __asm__ __volatile__ (
			    "cpuid":
			    "=a" (cpu[0]),
			    "=b" (cpu[1]),
			    "=c" (cpu[2]),
			    "=d" (cpu[3]) :
			    "a" (info), "c" (0)
	    );
    #else
	    memset (cpu, 0, sizeof (cpu));
    #endif
    }

Here is some information about my system:

    ..$gcc --version
     gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1
     Copyright (C) 2014 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    ..$lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.10
    Release:	14.10
    Codename:	utopic

Looks like there is some minor problem with assembly inline coding. Thanks.

**Comment by vstakhov** [comment]
That seems to be 32bit i386 architecture issue. I've pushed the workaround for this problem.

**Comment by awhitesong** [comment]
I pulled and did the fresh installation. Almost complete but I guess its now showing some linking errors and undefined references.

    Linking C executable rspamd
    librspamd-server.a(poly1305.c.o):(.data.rel.ro+0x8): undefined reference to `poly1305_block_size_ref'
    librspamd-server.a(poly1305.c.o):(.data.rel.ro+0xc): undefined reference to `poly1305_init_ext_ref'
    librspamd-server.a(poly1305.c.o):(.data.rel.ro+0x10): undefined reference to `poly1305_blocks_ref'
    librspamd-server.a(poly1305.c.o):(.data.rel.ro+0x14): undefined reference to `poly1305_finish_ext_ref'
    librspamd-server.a(poly1305.c.o):(.data.rel.ro+0x18): undefined reference to `poly1305_auth_ref'
    collect2: error: ld returned 1 exit status
    src/CMakeFiles/rspamd.dir/build.make:403: recipe for target 'src/rspamd-0.9.0' failed

**Comment by vstakhov** [comment]
Should be fixed now (another 32bit issue)

**Comment by awhitesong** [comment]
Thanks it worked!

**Comment by HailunTan** [comment]
how to fix this error??? Please advise.
