### ISSUE TITLE
Redis password set but not used -> NOAUTH Authentication required.

### ISSUE THREAD

**Issue by LarsBel** [vstakhov/rspamd#2236]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.4
### Operation system, CPU, memory and environment:
Ubuntu 18.04
### Description (Please provide a descriptive summary of the issue):
Ive configured Redis to use a password, Ive checked Redis and the password is working

"rspamadm configdump" shows that the password is correctly set in rspamd
```
redis {
    servers = "127.0.0.1";
    password = "tgsxbrtbhhw546nmntmemmghm57em5mdtz";
}
```
rspamd.log:
```
2018-05-09 04:49:48 #2237(controller) <fusi3g>; lua; lua_redis.lua:805: cannot upload script to 127.0.0.1(000000004A926B28): NOAUTH Authentication required.
2018-05-09 04:49:54 #2237(controller) <fusi3g>; lua; bayes_expiry.lua:332: cannot perform expiry step: NOAUTH Authentication required.
```

**Comment by LarsBel** [comment]
@croessner : Thanks

I had a Redis configuration in
# /etc/rspamd/local.d/classifier-bayes.conf
servers = "127.0.0.1";
backend = "redis";

After adding the password there it works

**Comment by ibotty** [comment]
I have the same problem, but adding `password=...` to `/etc/rspamd/local.d/classifier-bayes.conf` does not solve the problem:

```
2018-06-19 09:15:00 #32(rspamd_proxy) <dhn41b>; lua; lua_redis.lua:805: cannot upload script to 172.30.32.26(000000004128F478): NOAUTH Authentication required.
```

Any ideas?

**Comment by ibotty** [comment]
I needed to set the password for any service using redis. It inherits the server config, but not the password.

**Comment by Georgeto** [comment]
> I needed to set the password for any service using redis. It inherits the server config, but not the password.

Are there any plans to fix the bug that the password specified in the common redis section is not inherited by modules using the redis server from the common redis section?
