### ISSUE TITLE
DMARC reports sent by rspamd are invalid

### ISSUE THREAD

**Issue by heraklit256** [vstakhov/rspamd#2247]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.4, applicable to 1.7.2, too.
### Operation system, CPU, memory and environment:
any
### Description (Please provide a descriptive summary of the issue):
The DMARC reports generated and sent by rspamd are syntactically incorrect and not parsed by most of the reporting software. As far as I am concerned, some XML filed information is missing, but I am unable to tell it exactly at the moment; will provide details later.

**Comment by andreasschulze** [comment]
two independent notes:
1. aggregated reports send out by rspamd where not visible at dmarcian.com. That /is fixed/ by dmarcian.com. They simply mishandled the uncompressed reports.

2. dmarcanalyzer.nl have a validator (not yet public). A report generate that error message:
"Element 'report_metadata': This element is not expected. Expected is ( version )."

**Comment by vstakhov** [comment]
Well, RFC specifies `zip` or `gz` as a valid types for reports. That should be fixed by the recent commits in the master. However, I'd like to see some reports samples to figure out what's going wrong.

**Comment by vstakhov** [comment]
Is it still an issue?

**Comment by andreasschulze** [comment]
at least I've no problem anymore...
