### ISSUE TITLE
High memory usage since upgrade to 1.7.5

### ISSUE THREAD

**Issue by ashceryth** [vstakhov/rspamd#2254]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.5
### Operation system, CPU, memory and environment:
Debian Stretch, 2GB RAM
### Description (Please provide a descriptive summary of the issue):
Since upgrading from 1.7.4 to 1.7.5 there is a significantly higher memory usage on my server. The Rspamd processes are using up almost all available memory:

```
# ps aux --sort -rss
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
_rspamd    772  0.4 28.8 833004 589332 ?       SL   10:24   0:07 rspamd: rspamd_proxy process (localhost:11332)
_rspamd    774  0.3 28.2 832868 576432 ?       S    10:24   0:07 rspamd: normal process (localhost:11333)
_rspamd    773  0.7 18.1 836124 371240 ?       SL   10:24   0:13 rspamd: controller process (localhost:11334)
...
```

The graph shows that the memory usage nearly doubled after the update:

![image](https://user-images.githubusercontent.com/18515002/40352799-21e1bca2-5db0-11e8-853c-4413194337d6.png)

Please tell me if you need further information!

**Comment by vstakhov** [comment]
Disable phishtank.

**Comment by pkalemba** [comment]
@vstakhov can you describe why phishtank module is using soo much memory? in my case ~20 GB per node

**Comment by vstakhov** [comment]
It is a very large hash table that lives in Lua. Unfortunately, that's how 
they organise that data. In theory, I could reduce memory usage 
significantly but that's definitely not among my high priority tasks. So 
I'd recommend not to use it.

**Comment by pkalemba** [comment]
@vstakhov  thank you , @ashceryth  i think you can close issue yes?

**Comment by ashceryth** [comment]
@vstakhov Thank you for the elaboration.

**Comment by ralphM78** [comment]
@vstakhov I have a similar problem with 1.7.6-3~xenial. If the server boots up, everything works fine for days/weeks until  "systemctl restart rspamd". After restarting rspamd it takes about 2 minutes, then the server starts swapping. RAM usages increases very fast until the system isn't usable anymore. Disabling phishtank solves the problem, but why this happens only during "systemctl restart rspamd" ? Strange.
