### ISSUE TITLE
c7011661 doesn't work

### ISSUE THREAD

**Issue by Hello71** [vstakhov/rspamd#2265]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

post c7011661

### Operation system, CPU, memory and environment:

any

### Description (Please provide a descriptive summary of the issue):

c7011661 makes rspamd always *connect* to IPv4, but on my system, listening on "localhost" only *listens* on ::1. therefore, rspamc emits connection refused error.

### Compile errors (if any):

N/A

### Steps to reproduce:

rspamc -h localhost:x </dev/null

### Expected results:

HTTP error: 400, Empty body is not permitted

### Actual results:

IO write error: Connection refused

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

N/A

### Configuration:

bind_socket = "localhost:x";

### Additional information:

rspamd should:

1. listen on all addresses of the bind_socket (i.e. both 127.0.0.1 and ::1)
2. use IPs in the order getaddrinfo gives. the admin should use gai.conf if their system has a bug.

**Comment by vstakhov** [comment]
What address your `localhost` resolves? What OS are you using? What is your `net.ipv6.bindv6only` sysctl variable?

**Comment by Hello71** [comment]
ah, the problem (with point 2, point 1 needs separate fix) is more subtle. rspamd_inet_socket_create expects connect to return ECONNREFUSED immediately if the destination is unreachable. however, it passes nonblocking=TRUE to rspamd_socket_create, so connect returns EINPROGRESS, and only later sendmsg returns ECONNREFUSED. but by then we already threw out the getaddrinfo results. it is possible there is no simple solution there...

**Comment by Hello71** [comment]
this is not my experience.

```
$ sysctl net.ipv6.bindv6only
0
$ strace -e trace=network socat -6 - tcp-listen:9183,bind='[::1]',so-reuseaddr
socketpair(AF_UNIX, SOCK_DGRAM, 0, [3, 4]) = 0
socket(AF_INET6, SOCK_STREAM, IPPROTO_TCP) = 5
recvfrom(3, 0x7ffcbe41a590, 519, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(3, 0x7ffcbe41a590, 519, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
setsockopt(5, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(5, {sa_family=AF_INET6, sin6_port=htons(9183), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
getsockname(5, {sa_family=AF_INET6, sin6_port=htons(9183), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [28]) = 0
listen(5, 5)                            = 0
recvfrom(3, 0x7ffcbe41a3f0, 519, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(3, 0x7ffcbe41a1c0, 519, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
```

and separately:
```
$ socat -4 -d -d - tcp-connect:localhost:9183
2018/05/24 09:55:44 socat[12630] N reading from and writing to stdio
2018/05/24 09:55:44 socat[12630] N opening connection to AF=2 127.0.0.1:9183
2018/05/24 09:55:44 socat[12630] E connect(5, AF=2 127.0.0.1:9183, 16): Connection refused
2018/05/24 09:55:44 socat[12630] N exit(1)
```

**Comment by Hello71** [comment]
perhaps it works differently on other platforms, but at least on Linux there is only the 0.0.0.0/:: alias. AIUI on BSD there is no alias at all (as if net.ipv6.bindv6only is always 1).

**Comment by vstakhov** [comment]
No, there are no aliases at all:

```
       IPV6_V6ONLY (since Linux 2.4.21 and 2.6)
              If this flag is set to true (nonzero), then the socket is restricted to sending and receiving IPv6 packets only.  In this case, an IPv4 and an IPv6 application can bind to  a  single
              port at the same time.

              If this flag is set to false (zero), then the socket can be used to send and receive packets to and from an IPv6 address or an IPv4-mapped IPv6 address.

              The argument is a pointer to a boolean value in an integer.

              The default value for this flag is defined by the contents of the file /proc/sys/net/ipv6/bindv6only.  The default value for that file is 0 (false).
```

Technically it means translation to `IPv4-mapped` address from IPv6 address. Anyway, I will not change this logic and IPv4 will always be preferred. In fact, I have the same config on linux:

```
$ host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1

$ ss -l | grep 11334
tcp    LISTEN     0      128    127.0.0.1:11334                 *:*
tcp    LISTEN     0      128       ::1:11334                :::*
```

Where `bind_socket="localhost:11334"`. So there is something wrong in your system.

**Comment by Hello71** [comment]
still, even if you want to try IPv4 first, IPv6 fallback should work properly.

**Comment by LarsBel** [comment]
On Ubuntu 18.04 with default config
´´´
bind_socket="localhost:11334"
´´´
´´´
# host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1
´´´
´´´
# ss -l | grep 11334
tcp    LISTEN   0        128                                          127.0.0.1:11334                                                0.0.0.0:*
´´´
only the v4 binds automaticly.
Fix:
´´´
/etc/rspamd/local.d/worker-controller.inc
bind_socket = "[::1]:11334";
bind_socket = "127.0.0.1:11334";
´´´

then rspamc works without -h parameter
