### ISSUE TITLE
Missing i386 build for Debian/Ubuntu

### ISSUE THREAD

**Issue by pcopfer** [vstakhov/rspamd#2272]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Ubuntu stable and experimental
### Operation system, CPU, memory and environment:
Debian/Ubuntu
### Description:
I observed that your projects repository referenced on the project [website](https://rspamd.com/downloads.html) only provides an amd64 build and no i368 build though it is mentioned on the website. So there is either a bug on your build system preventing the i368 build or the documentation is outdated. 

### Expected results:
Existing i368 build at the [repository](https://rspamd.com/apt-stable/dists/xenial/main/).

### Actual results:
Only a amd64 version.

### Workaround for amd64
Change line in rspamd.list to:
` deb [arch=amd64] http://rspamd.com/apt-stable xenial main`
prevents following apt update output:
`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://rspamd.com/apt-stable xenial InRelease' doesn't support architecture 'i386'`

**Comment by rpv-tomsk** [comment]
I found the following info about this:
https://groups.google.com/forum/#!topic/rspamd/RVHH4gbLZr0

Yes, I'm still using i386 arch and do own builds for this.

**Comment by pcopfer** [comment]
Fixed by commit https://github.com/vstakhov/rspamd.com/commit/b0aa4b9da7e9fd7290b35370602a2d3b669bda48
