### ISSUE TITLE
rspamadm confighelp throws a lua error

### ISSUE THREAD

**Issue by fenice2** [vstakhov/rspamd#2276]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.5
### Operation system, CPU, memory and environment:
CentOS7
### Description (Please provide a descriptive summary of the issue):
running rspamadm confighelp -k keypair throws an error
### Steps to reproduce:
run rspamadm confighelp -k keypair

### Expected results:
Full help for this request
### Actual results:
It throw a lua script error after a partial display 
### Additional information:

rspamadm confighelp -k keypair
Showing help for keyword keypair:
Configuration element: .actions
        Description: Actions configuration
        Type: object
        Required: false

        Configuration element: grow_factor
                Description: Multiply the subsequent symbols by this number (does not affect symbols with score less or equal to zero)
                Type: double
                Required: false
        Configuration element: subject
                Description: Rewrite subject with this value
                Type: string
                Required: false
        Configuration element: unknown_weight
                Description: Accept unknown symbols with the specified weight
                Type: double
                Required: false

Configuration element: .classifier.backend
        Description: Statfiles engine
        Type: string
        Required: false

Configuration element: .dkim.dkim_cache_size.default
call to rspamadm lua script failed (2): /usr/share/rspamd/lib/rspamadm/confighelp.lua:23: bad argument #1 to 'pairs' (table expected, got string); trace: [1]:{[C]:-1 - pairs [C]}; [2]:{/usr/share/rspamd/lib/rspamadm/confighelp.lua:23 - sort_values [Lua]}; [3]:{/usr/share/rspamd/lib/rspamadm/confighelp.lua:93 - print_help [Lua]}; [4]:{/usr/share/rspamd/lib/rspamadm/confighelp.lua:108 - <unknown> [Lua]};

**Comment by vstakhov** [comment]
Fixed
