### ISSUE TITLE
How can i know clamav works ?

### ISSUE THREAD

**Issue by LeDistordu** [vstakhov/rspamd#2280]
#Hello,

I'm a little confused about the antivirus module, no trace anywhere !

*** Section antivirus ***
clamav {
    attachments_only = true;
    patterns {
        JUST_EICAR = "^Eicar-Test-Signature$";
    }
    symbol = "CLAM_VIRUS";
    type = "clamav";
    whitelist = "/etc/rspamd/antivirus.wl";
    servers = "127.0.0.1:3310";
}

*** End of section antivirus ***

in clamav.conf

TCPSocket 3310
TCPAddr 127.0.0.1

Nothing about clamav when mail go in with attachement in : 

mail.log
clamav.log
rspamd.log

Nothing about antivirus in header mail

What does it mean : HAS_ATTACHMENT(0.00){} ?

Could someone help me :)

**Comment by vstakhov** [comment]
Could you please read the documentation before opening endless issues about the same thing? https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd

**Comment by LeDistordu** [comment]
I read documentation !

The solution is to add 
log_clean = true;

Sorry for the inconvenience and thank you for your work
