### ISSUE TITLE
Filter extension, action delete attachement and add warning ?

### ISSUE THREAD

**Issue by LeDistordu** [vstakhov/rspamd#2282]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Rspamd version:

Rspamd 1.7.5

### Operation system, CPU, memory and environment:

All

### Description (Please provide a descriptive summary of the issue):

Today we can reject mail based on extension but it would be better to add action for delete attachement and add warning message in mail.

**Comment by vstakhov** [comment]
That won't be implemented: Rspamd does not modify the message itself and there are no plans to add such a functional.
