### ISSUE TITLE
please add packages for wheezy again

### ISSUE THREAD

**Issue by rubo77** [vstakhov/rspamd#2291]
On https://rspamd.com/apt-stable/dists/ there is now section for wheezy any more.

Can you please readd the sources, so I can install rspamd on an old Debian wheezy

**Comment by vstakhov** [comment]
Debian wheezy has reached its end-of-life I'm afraid. Hence, it won't be supported any longer.

**Comment by rubo77** [comment]
But why did you delete the old packages? Expand 1.6 works fine on my wheezy system

**Comment by vstakhov** [comment]
If it works fine then you no longer need packages.

**Comment by rubo77** [comment]
I first couldn't find it anywhere. Now I have it from the other servers apt-cache: 

     rspamd_1.6.5-4~wheezy_amd64.deb

It would be nice, if you had an archive with those old packages. especially, cause here it is still noted, that it works for wheezy: https://rspamd.com/doc/quickstart.html#ubuntu-debian-wheezy

**Comment by vstakhov** [comment]
It is *not* nice as these packages are no longer supported even for the security fixes. I'm sorry but I'd not advice to use unsupported and outdated platform - there was plenty of time to migrate.

**Comment by vstakhov** [comment]
I've built experimental packages for wheezy (identical to 1.7.6-stable). You can try to use them if you absolutely need to use wheezy despite of its state. Stable packages fail without https://github.com/vstakhov/rspamd/commit/1a001969a95249b50bd92bf7ea5374159e583ec6

**Comment by rubo77** [comment]
Thx!


Where do I find it?

**Comment by vstakhov** [comment]
https://rspamd.com/downloads.html#system2

**Comment by rubo77** [comment]
Sorry, but I cannot find a wheezy link there
