### ISSUE TITLE
rspamd hangs

### ISSUE THREAD

**Issue by azurit** [vstakhov/rspamd#2293]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.6
### Operation system, CPU, memory and environment:
Debian Stretch
### Description (Please provide a descriptive summary of the issue):

After a while of running, rspamd stops working and scanning e-mails and starts to print this error into log:
Jun 18 03:06:15 server00 rspamd[1908]: <>; glib; rspamd_glib_printerr_function: **#012ERROR:/rspamd-1.7.6/src/libutil/radix.c:54:radix_find_compressed: assertion failed: (tree !=
NULL)

The problem can be resolved by restarting rspamd but it works only for a while.

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed

**Comment by vstakhov** [comment]
(assert means crash)

**Comment by azurit** [comment]
Just a quick note: I downgraded to 1.7.5 and it works fine.

**Comment by vstakhov** [comment]
Is it fixed in 1.7.6-2?

**Comment by azurit** [comment]
Didn't crash for few hours, so yes, i suppose. Thank you!
