### ISSUE TITLE
rspamd 1.7.6 segfaults from time to time

### ISSUE THREAD

**Issue by philfry** [vstakhov/rspamd#2297]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.7.6

### Operation system, CPU, memory and environment:

CentOS 7.5.1804, i7-2600, 16GiB RAM

### Description (Please provide a descriptive summary of the issue):

every 1-2 days in the morning I experience segfaults in rspamd which result in mail getting temporarily rejected.

### Compile errors (if any):

n/a

### Steps to reproduce:

1. run rspamd
2. wait for milter connections
3. have luck

### Expected results:

rspamd not crashing  and mails getting checked

### Actual results:
```
Jun 21 08:04:28 xxx kernel: traps: rspamd[5053] general protection ip:58a490 sp:7fff0fc98cd0 error:0 in rspamd[400000+271000]
Jun 21 08:04:28 xxx postfix/cleanup[5041]: warning: milter unix:/run/rspamd/milter.socket: can't read SMFIC_BODYEOB reply packet header: Success
Jun 21 08:04:28 xxx postfix/cleanup[5041]: B8A7C24D9E: milter-reject: END-OF-MESSAGE from xxx[xxx]: 4.7.1 Service unavailable - try again later; from=<xxx> to=<xxx> proto=ESMTP helo=<xxx>
```
### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

see attached file

### Configuration:

see attached file

### Additional information:

crash didn't occur before 1.7.6

[rspamd-bugreport.tar.gz](https://github.com/vstakhov/rspamd/files/2122435/rspamd-bugreport.tar.gz)

**Comment by vstakhov** [comment]
Are you using 1.7.6-3?

**Comment by philfry** [comment]
probably not, I'm using the tagged release (1.7.6, d9c84b4bd).

**Comment by vstakhov** [comment]
1a001969a95249b50bd92bf7ea5374159e583ec6
1bd9b92735543e0ad651a60f2b05c567e8139933
52a9a2eed69bed33764a2eb66715711ea660fbeb
8d393a012f52e57ab6bc7cc0c8da0c64ccd10ea9

These patches are now included over 1.7.6.

**Comment by philfry** [comment]
thanks, I'll try that.

**Comment by philfry** [comment]
The patches seem to have solved the problem. Thanks again.
