### ISSUE TITLE
Wrong numerical sorting in WEBUI

### ISSUE THREAD

**Issue by hildeb** [vstakhov/rspamd#2298]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.6

### Operation system, CPU, memory and environment:
Ubuntu 18.04

### Description (Please provide a descriptive summary of the issue):
The column "frequency" is not properly sorted. I think this might be due to the expontential / scientific notation!

### Steps to reproduce:
Sort column "frequency"  so that largest numerical values come first.

### Expected results:
Correct sorting

### Actual results:
9.00e-2 is larger than 87.00e-2 
![wrong_sort_numerical](https://user-images.githubusercontent.com/2426330/41721194-9264e900-7565-11e8-9eaa-60d365acd12c.png)

**Comment by andryyy** [comment]
I can fix this when I’m back home. 

FooTable needs a sortValue parameter (explicit integer).
