### ISSUE TITLE
rspamd does not check SPF

### ISSUE THREAD

**Issue by tiukhtinvladimir** [vstakhov/rspamd#2299]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
```
rspamd --version
Rspamd daemon version 1.7.6
```
### Operation system, CPU, memory and environment:
CentOS 7.5

### Description (Please provide a descriptive summary of the issue):
Can not force rspamd to check SPF record

### Steps to reproduce:
I am sending myself an email using php from different host which can not pass SFP by design. I am sending from master@gmail.com. Anyway this email arrives with no problem because rspamd does not try to check SPF

### Expected results:
Expecting failed SPF with +10 as defined in configuration and email rejection

### Actual results:
5.3/10
```
Jun 21 17:38:07 mail rspamd[11083]: <4e6c43>; proxy; rspamd_task_write_log: id: <201806211738.w5LHcGWA020903@www.example.com>, qid: <21960A0677>, ip: X.X.X.X, from: <root@server.example.com>, (default: F (greylist): [5.30/10.00] [HFILTER_HOSTNAME_UNKNOWN(2.50){},PHP_SCRIPT_ROOT(1.00){},RDNS_NONE(1.00){},MID_RHS_WWW(0.50){},FORGED_SENDER(0.30){master@gmail.com;root@server.example.com;},DMARC_POLICY_SOFTFAIL(0.10){gmail.com : No valid SPF, No valid DKIM;none;},MIME_GOOD(-0.10){text/plain;},ARC_NA(0.00){},ASN(0.00){asn:196750, ipnet:X.X.0.0/18, country:RU;},FREEMAIL_FROM(0.00){gmail.com;},FROM_NEQ_ENVFROM(0.00){master@gmail.com;root@server.example.com;},FROM_NO_DN(0.00){},HAS_X_POS(0.00){},PREVIOUSLY_DELIVERED(0.00){me@example.com;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_THREE(0.00){3;},RCVD_TLS_LAST(0.00){},R_DKIM_NA(0.00){},R_SPF_NA(0.00){},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 569, time: 95.730ms real, 6.312ms virtual, dns req: 19, digest: <3409590110bf11bfe5cfbbf9f7c0163b>, rcpts: <me@example.com>, mime_rcpts: <me@example.com>
```

**Comment by vstakhov** [comment]
Your envelope from is `example.server.org` and not `gmail.com`. SPF uses SMTP from, not MIME one, so it is not an Rspamd issue.
