### ISSUE TITLE
Feature: action for composites

### ISSUE THREAD

**Issue by ralphM78** [vstakhov/rspamd#2303]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ x] Feature
* [ ] Enhancement

Hello,

is it possible to implement the usage of "action" inside the composite module ?
For example something like :

OVERWRITE_ML {
        expression = "MAILLIST AND LOCAL_BLACKLIST_FROM";
        action = "reject";
                             }

Actually I have to use force_actions module for this or did I miss something ?

Ralph

**Comment by heraklit256** [comment]
+1

**Comment by vstakhov** [comment]
You have `force_actions` module for that purposes, I'd refrain from duplicating its functionality.
