### ISSUE TITLE
Ratilimit module failed when disable postmaster in whitelisted_rcpts

### ISSUE THREAD

**Issue by reztarter** [vstakhov/rspamd#2306]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rspamd-1.7.6-3
### Operation system, CPU, memory and environment:
Centos 7
### Description (Please provide a descriptive summary of the issue):
I configured Exim with Rspamd. When I try to send email from postmaster@mydomai.tk  I see in rspamd.log value R_RATELIMIT(0.00) because postmaster is exists by default in whitelisted_rcpts of ratelimit module configuration. But when I excuded postmaster from whitelisted_rcpts = "mailer-daemon"; in /etc/rspamd/local.d/ratelimit.conf I got an error message in rspamd.log
``
2018-06-22 10:55:28 #19477(normal) <4856d6>; task; lua_metric_symbol_callback: call to (R_RATELIMIT) failed (2): /usr/share/rspamd/lua//ratelimit.lua:339: attempt to index field 'whitelisted_rcpts' (a nil value); trace: [1]:{/usr/share/rspamd/lua//ratelimit.lua:339 - fun [Lua]}; [2]:{/usr/share/rspamd/lib/fun.lua:30 - call_if_not_empty [Lua]}; [3]:{/usr/share/rspamd/lib/fun.lua:654 - any [Lua]}; [4]:{/usr/share/rspamd/lua//ratelimit.lua:339 - <unknown> [Lua]};

### Steps to reproduce:
Change value of whitelisted_rcpts in ratelimit.conf to whitelisted_rcpts = "mailer-daemon";

### Expected results:
I want to enable ratelimit feature when emails are sent from postmaster@mydomain.tk

### Actual results:
(R_RATELIMIT) failed (2) message in rspamd.log occurs

### Configuration:
``
$ rspamadm configdump
ratelimit {
    whitelisted_rcpts = "mailer-daemon";
    symbol = "R_RATELIMIT";
    rates {
        to_ip = "3 / 2min";
        to = "2 / 1min";
        bounce_to = "2 / 1h";
        to_ip_from = "1 / 1min";
        user = "1 / 1min";
        bounce_to_ip = "1 / 1h";
    }
    max_rcpt = 5;
    info_symbol = "R_RATELIMIT_INFO";
    enabled = true;
}

### Additional information:
It's desirable for me that ratelimit mosule works exactly with account postmaster@mydomain.tk

**Comment by vstakhov** [comment]
use `whitelisted_rcpts = ["mailer-daemon"];`

**Comment by reztarter** [comment]
I try to use 
`whitelisted_rcpts = ["mailer-daemon"];`

but I got the same error in rspamd log:
` task; lua_metric_symbol_callback: call to (R_RATELIMIT) failed (2): /usr/share/rspamd/lua//ratelimit.lua:339: attempt to index field 'whitelisted_rcpts' (a nil value); trace: [1]:{/usr/share/rspamd/lua//ratelimit.lua:339 - fun [Lua]}; [2]:{/usr/share/rspamd/lib/fun.lua:30 - call_if_not_empty [Lua]}; [3]:{/usr/share/rspamd/lib/fun.lua:654 - any [Lua]}; [4]:{/usr/share/rspamd/lua//ratelimit.lua:339 - [Lua]};`

**Comment by vstakhov** [comment]
I cannot reproduce it.

**Comment by vstakhov** [comment]
With `whitelisted_rcpts = "mailer-daemon";` it is definitely broken, but my version works fine.

**Comment by reztarter** [comment]
Ok, I just used a default values for whitelisted_rcpts = ["postmaster, mailer-daemon"]; and try to send email from root@mydomain.tk. A mentioned above error did not occur and now I see in rspamd.log lines according to my current Ratelimit module configuration when I send some emails via my email server:

`
2018-06-28 16:23:18 #34641(normal) <c3b367>; lua; ratelimit.lua:383: set_symbol_only: ratelimit "to(27:uzer17@vivaldi.net)" exceeded, (2 / 3600): 9 (0:0 dyn)
2018-06-28 16:23:18 #34641(normal) <c3b367>; lua; ratelimit.lua:383: set_symbol_only: ratelimit "to_ip(13:uzer17@vivaldi.net:192.168.42.1)" exceeded, (3 / 7200): 9 (0:0 dyn)
2018-06-28 16:23:18 #34641(normal) <c3b367>; lua; ratelimit.lua:383: set_symbol_only: ratelimit "to_ip_from(27:uzer17@vivaldi.net:192.168.42.1:root@mydomain.tk)" exceeded, (1 / 3600): 9 (0:0 dyn)`

But limitation is not working, for example when I setup to, to_ip and to_ip_from to certain value, for example 3 per hour, I still can to send 4th, 5th emails and so on... Maybe need to exactly configure some options in options.inc for example to explicitly enable discard emails that are more than needed in Ratelimit's module configuration?

Thanks.

**Comment by vstakhov** [comment]
I don't understand what you are trying to say. `set_symbol_only` means that you have configured your module to add symbol instead of issuing soft reject message. You need to remove `symbol` from the configuration if you want to do rejections...

**Comment by reztarter** [comment]
Please clarify how possible to remove symbol from configuration? In what config file?

**Comment by vstakhov** [comment]
You have added it by yourself. I have no ideas where and what have you done. By default, `ratelimit` module has no `symbol` option defined. You've defined it for some reason.

**Comment by reztarter** [comment]
What symbol exactly do you mean? My current Ratelimit configuration is the following:
`ratelimit {
    whitelisted_rcpts = "postmaster,mailer-daemon";
    symbol = "R_RATELIMIT";
    rates {
        to_ip = "3 / 2h";
        to = "2 / 1h";
        bounce_to = "2 / 1h";
        to_ip_from = "1 / 1h";
        user = "1 / 1h";
        bounce_to_ip = "1 / 1h";
    }
    max_rcpt = 5;
    info_symbol = "R_RATELIMIT_INFO";
    enabled = true;
}
`

**Comment by reztarter** [comment]
here symbol and info_symbol have a defaults value. I didn't change it...

**Comment by vstakhov** [comment]
Again: there are no default values for these symbols. Here is the default configuration:

```
% rspamadm configdump ratelimit
*** Section ratelimit ***
max_rcpt = 5;
whitelisted_rcpts = "postmaster,mailer-daemon";

*** End of section ratelimit ***
```

**Comment by reztarter** [comment]
I.e. it's enough to cut the parameters symbol and info_symbol from ratelimit.conf file to work properly email rejection feature?

**Comment by ibakirov** [comment]
@reztarter in your configuration comment these lines:
```
symbol = "R_RATELIMIT";
info_symbol = "R_RATELIMIT_INFO";
```

**Comment by reztarter** [comment]
Thanks a lot! I have now a working email rejection feature... It's interesting for the future, for what need these 2 parameters: symbol and info_symbol?

**Comment by reztarter** [comment]
A difficult explanation on https://rspamd.com/doc/modules/ratelimit.html:

symbol - if this option is specified, then ratelimit plugin just adds the corresponding symbol instead of setting pre-result, the value is scaled as , where tanh is the hyperbolic tanhent function

info_symbol (1.7.0+) - if this option is specified the corresponding symbol is inserted in addition to setting pre-result.
