### ISSUE TITLE
Allow building rspamc only

### ISSUE THREAD

**Issue by Sp1l** [vstakhov/rspamd#2312]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.5

### Operation system, CPU, memory and environment:
FreeBSD 11.2 amd64
Version from ports

### Description (Please provide a descriptive summary of the issue):
Please add a feature to the CMake scripts to allow building the client exclusively.
#### Use case:
From the system/jail where SMTP is handled, call out using `rspamc` to the system/jail running `rspamd`. Currently this requires installing the complete rspamd package whereas only the `rspamc` utility is required.

**Comment by vstakhov** [comment]
Why not use curl in this case?

**Comment by Sp1l** [comment]
Can't seem to find a way to get a modified MIME message in return using the HTTP endpoint, only symbols?

```
rspamc -h scan --mime -e \"/usr/local/bin/lda2lmtp -s %{sender} -r %{user.username}\"
```

**Comment by vstakhov** [comment]
Mime mode is a bad hack implemented in `rspamc` indeed. There are no sane use cases of this function unless the last resort case. In this case, you can easily install rspamd as a complete package.

**Comment by Sp1l** [comment]
Noted 😃

**Comment by Sp1l** [comment]
FWIW, I like to separate things. The SMTP server and IMAP/POP server run in separate jails (and rspamd in yet another jail). The only thing that OpenSMTPd hands over to Dovecot is the MIME message via LMTP.
1. Receive mail
2. Check RBL's and ClamAV
3. Classify in spamfilter
4. Deliver via LMTP to Dovecot
Hope to be able to extend my lda2lmtp script so it does the same thing and do away with the full rspamd server install in the smtp jail.
