### ISSUE TITLE
Apply bayes autolearn for soft rejected mails

### ISSUE THREAD

**Issue by WRMSRwasTaken** [vstakhov/rspamd#2316]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
*  [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.6

Hi,

I've set `autolearn = [-2, 6];` in `/etc/rspamd/local.d/statistic.conf`, but it does not apply, if a mail has been soft-rejected.

I disabled postfix' rDNS checks and wanted rspamd to handle this, that's why I created a rule for the force actions module:

```
  RDNS_FAIL_OR_NONE_SOFTREJECT {
    expression = "RDNS_DNSFAIL | RDNS_NONE";
    action = "soft reject";
    message = "rDNS verification failed, try again later";
  }
```

hoping that soft-bounced mails having a score higher than 6 will train the bayes too, but they don't. I can't see the task `rspamd_stat_check_autolearn` getting triggered in the logs.

Also it may be related to the webui not displaying scores (alaways 0.00 / 15) for soft-rejected mails, although symbols getting triggered:
```
URIBL_BLACK(7.5)[zzoz.top.multi.uribl.com]
DBL_SPAM(6.5)[zzoz.top.dbl.spamhaus.org]
ABUSE_SURBL(5.5)[zzoz.top.multi.surbl.org]
[...]
```
It would be nice to see the scores for those aswell.

**Comment by vstakhov** [comment]
Autolearn will not work for that (aside from the fact that I constantly discourage Rspamd users from using the embedded autolearning...).

**Comment by WRMSRwasTaken** [comment]
Okay, but would it still be possible to display the scores instead of 0.0 in the history tab for soft rejected mails?

**Comment by vstakhov** [comment]
No, soft reject means no score strictly.

**Comment by WRMSRwasTaken** [comment]
Ah okay, thanks for clarification!
