### ISSUE TITLE
nested section: dmarc { dmarc { ... } }, it is likely a configuration error

### ISSUE THREAD

**Issue by Knot3n** [vstakhov/rspamd#2321]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

We are getting the error msg below and dont know what should be wrong. 

Time | Worker type | PID | Module | Internal ID | Message
-- | -- | -- | -- | -- | --
3.7.2018, 09:12:22 | main | 27326 | lua |   | nested section: dmarc { dmarc { ... } }, it is likely a configuration error

### Steps to reproduce:

We did not change anything since few versions before. 
This "Error MSG" came up with the Version 1.7.6 / 1.7.7

### Expected results:
No Error Msg about DMARC

### Actual results:

Error Msg about DMARC

### Configuration:

What do you need here?

### Additional information:

Hopefully someone of you (devs) can help us. Would be awesome.

**Comment by Knot3n** [comment]
So no one can help us with this problem? 

Need more debugin ?

**Comment by vstakhov** [comment]
The problem report is self-explanatory. Read the documentation (at least FAQ section).

**Comment by Knot3n** [comment]
I looked for "nested" in the documentation station as well as in my configuration - the problem did not occur until after the update and before that, it was not there. I am aware that you first read the documentation before you open an issue, so that I do not know further, thats why im asking.

**Comment by remkolodder** [comment]
the clue is in the part that you have the config nested. probably you have dmarc.conf with dmarc { } settings, the dmarc {} part is not needed because the section is already defined when you load dmarc.conf from local.d (See modules.d/dmarc.conf for an example):

modules.d/dmarc.conf
dmarc {
    .include(try=true,priority=5) "${DBDIR}/dynamic/dmarc.conf"
    **.include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/dmarc.conf"**
    .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/dmarc.conf"
}

The highlighted part is the local.d include, it is inside the dmarc {} brackets.

That is what is wrong. Goodluck.

**Comment by anteract** [comment]
for each of you that get stuck here:
1.  "rspamadm configdump | grep option"      This will let you know that there is in fact a nested option someplace.  rspamadm configtest would help a LOT if it would give this hint
2. "rspamadm configdump | less"                      Search for the option you found above, kill the second one.  (its in local.d probably)
   Mine was rspamd_dynamic defined twice.
3.  Win!

**Comment by fatalbanana** [comment]
>     1. "rspamadm configdump | grep option"      This will let you know that there is in fact a nested option someplace.  rspamadm configtest would help a LOT if it would give this hint

`rspamadm configtest` does in fact emit a message about this.

**Comment by anteract** [comment]
It says there is a nested option, but not a clue as to where in the 10 different files in local.d.  my way sent me straight to it.
