### ISSUE TITLE
CPU doesn't have SSSE3 instructions set required for hyperscan, disable it

### ISSUE THREAD

**Issue by shoujii** [vstakhov/rspamd#2327]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ x ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.7

### Description (Please provide a descriptive summary of the issue):
While using rspamadm pw -p password I'm always getting:
"CPU doesn't have SSSE3 instructions set required for hyperscan, disable it"
I know that the Root Server doesnt have SSE3, but how can I disable that message?

**Comment by andryyy** [comment]
Perhaps 2>/dev/null will work. Or remove the first line with “head”. You could create an alias in your shell. 

Or ignore it.

**Comment by shoujii** [comment]
I can't ignore it, since it's killing my worker-controller.inc

1. RSPAMADM_PASSWORT=$(password)
2. RSPAMADM_PASSWORT_HASH=$(rspamadm pw -p ${RSPAMADM_PASSWORT})
3. cat > /etc/rspamd/local.d/worker-controller.inc <<END
password = "${RSPAMADM_PASSWORT_HASH}";
END

Result:
password = "CPU doesn't have SSSE3 instructions set required for hyperscan, disable it
$2$jc7zrnkf9khzs3wbgj7rroky5u8k4bq3$8fnz5prj3sn3ikus6w5fgxeowy14e7873tzgnuopno1q3tnsjdub";

Deleting the first line isn't useful, but there will be a workaround, but i thought that there is a more beautiful solution :)

**Comment by Knot3n** [comment]
Maybe you can ask your hoster to actiavte SSE3 on your system.

**Comment by vstakhov** [comment]
Set `disable_hyperscan = true;` in `local.d/options.inc`.

**Comment by bartoll** [comment]
> 
> 
> Set `disable_hyperscan = true;` in `local.d/options.inc`.
Not working for me :(

**Comment by shoujii** [comment]
I‘ve bypassed that error message:
https://github.com/shoujii/NeXt-Server-Buster/blob/master/script/rspamd.sh
Line 30 to 51.

Dirty, but after that I have a clean password hash without error message inside.

But I don’t know how to disable it, since that the mentioned solution isn’t working.
