### ISSUE TITLE
Controller not authorizing local rspamc

### ISSUE THREAD

**Issue by dark-al** [vstakhov/rspamd#234]
Hi!
Rspamd from git master.
I'm trying run rspamc stat on local machine and get the following messages:

>root@ubuntu:~# rspamc stat
Results for command: stat
HTTP error: 500, invalid command

>root@ubuntu:~# rspamc stat
Results for command: stat
HTTP error: 500, invalid command

>root@ubuntu:~# rspamc stat
Results for command: stat
HTTP error: 500, invalid command

>root@ubuntu:~# rspamc stat
Results for command: stat
HTTP error: 403, Unauthorized

>root@ubuntu:~# rspamc stat
Results for command: stat
HTTP error: 403, Unauthorized

**Comment by vstakhov** [comment]
Providing `strace` and tcpdump output would be helpful as well as enabling debug logs in rspamd itself.

**Comment by fatalbanana** [comment]
Needs -P q1 perhaps?

**Comment by vstakhov** [comment]
500 still looks weird.

**Comment by dark-al** [comment]
with -P q1 work, but why password really need for local client?

**Comment by dark-al** [comment]
strace: http://ur1.ca/jxund
tcpdump: http://ur1.ca/jxunv

**Comment by fatalbanana** [comment]
strace of rspamd 'normal' process & debug logs please. :)

I guess it requires a password because only IPv4 loopback is allowed by secure_ip setting.

**Comment by dark-al** [comment]
Issue already fixed? Or strace of rspamd still need?

**Comment by vstakhov** [comment]
If you report an issue it is your duty to check whether it's already fixed and close the issue if it is (or blame if it doesn't).

**Comment by dark-al** [comment]
After updating to 8af3fbb201d248d949849aaf0046c99e3642ca76 problem fixed. Thanks!
