### ISSUE TITLE
rspamd 1.7.x does not build on OpenBSD with gcc 4.2 #2

### ISSUE THREAD

**Issue by brad0** [vstakhov/rspamd#2342]
FAILED: contrib/lua-torch/torch7/lib/TH/CMakeFiles/TH.dir/THVector.c.o ^M
/usr/bin/cc  -DHAVE_CONFIG_H -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DTH_EXPORTS -DUSE_GCC_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -I/home/brad/ports/p
obj/rspamd-1.7.8/rspamd-1.7.8/contrib/hiredis -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8 -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/src -I/home
/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/src/libutil -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/src/libserver -I/home/brad/ports/pobj/rspamd-1.7.8/r
spamd-1.7.8/src/libmime -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/src/libstat -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/src/libcryptobox -I/h
ome/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/libucl -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/linenoise -I/home/brad/ports/pobj/rspa
md-1.7.8/rspamd-1.7.8/contrib/uthash -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/http-parser -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/
contrib/libottery -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/xxhash -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/cdb -I/home/brad
/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/snowball/include -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/librdns -I/home/brad/ports/pobj/rspa
md-1.7.8/rspamd-1.7.8/contrib/aho-corasick -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lc-btrie -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7
.8/contrib/lua-lpeg -Isrc -Isrc/libcryptobox -I/usr/local/include/luajit-2.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/inc
lude -I/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/compat -Icontrib/lua-torch/torch7/lib/TH -DUSE_SSE2 -msse3 -DUSE_SSE3   -DUSE_SSE2 -O2 -pipe -O2 -pipe
    -pthread -fPIC  -W -Wall -Wpointer-arith -Wno-unused-parameter -Wno-unused-function -Wunused-variable -Wno-pointer-sign -Wstrict-prototypes -Wno-sign-com
pare -std=c99 -Werror=implicit-function-declaration -Werror=format -std=gnu99 -DHAVE_GCC_GET_CPUID -DNDEBUG -fPIC -MD -MT contrib/lua-torch/torch7/lib/TH/CMa
keFiles/TH.dir/THVector.c.o -MF contrib/lua-torch/torch7/lib/TH/CMakeFiles/TH.dir/THVector.c.o.d -o contrib/lua-torch/torch7/lib/TH/CMakeFiles/TH.dir/THVecto
r.c.o   -c /home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/THVector.c^M
In file included from /home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/THVector.c:3:^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/generic/simd/simd.h:124: warning: function declaration isn't a prototype^M
In file included from /home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/THVector.c:15:^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:2:23: error: x86intrin.h: No such file or directory^M
In file included from /home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/THVector.c:15:^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c: In function 'THDoubleVector_fill_SSE':^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:10: error: '__m128d' undeclared (first use in this function)^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:10: error: (Each undeclared identifier is reported only once^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:10: error: for each function it appears in.)^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:10: error: expected ';' before 'XMM0'^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:12: warning: implicit declaration of function '_mm_storeu_pd'^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:12: error: 'XMM0' undeclared (first use in this function)^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c: In function 'THDoubleVector_cadd_SSE':^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:25: error: '__m128d' undeclared (first use in this function)^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:25: error: expected ';' before 'XMM7'^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:26: error: expected ';' before 'XMM0'^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:28: error: 'XMM0' undeclared (first use in this function)^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:28: warning: implicit declaration of function '_mm_loadu_pd'^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:29: error: 'XMM2' undeclared (first use in this function)^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:30: warning: implicit declaration of function '_mm_mul_pd'^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:30: error: 'XMM7' undeclared (first use in this function)^M
/home/brad/ports/pobj/rspamd-1.7.8/rspamd-1.7.8/contrib/lua-torch/torch7/lib/TH/vector/SSE.c:31: warning: implicit declaration of function '_mm_add_pd'^M

**Comment by vstakhov** [comment]
I'm sorry, but I'm not going to support torch with that ancient compiler. Rspamd will not likely support it as well shortly, please use somehow a modern compiler.
