### ISSUE TITLE
version 1.7.9 memory leak?

### ISSUE THREAD

**Issue by himpierre** [vstakhov/rspamd#2397]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

After updating on both of my machines to 1.7.9 memory consumption went from 4G to 12G. Did not wait for the OOM Killer. After rspamd restart memory is at normal again and begins to raise. Downgrading to 1.7.8 fixes that issue.

**Comment by vstakhov** [comment]
Do you use vanilla configuration? If not, please provide the list of your local changes.

**Comment by himpierre** [comment]
It's not completely vanilla, no. Here my configdump.

https://nopaste.fluffycloud.de/?836dad65d22a9c9e#6VWXbSUMwp+1qKdpicxVNpqGfL6Ztzo64hiXmlsUrP0=

I can paste it here too if you prefer that.

thanks and cheers

**Comment by vstakhov** [comment]
Disable phishtank.

**Comment by himpierre** [comment]
Ok. Disabled phishtank, upgraded to 1.7.9 again, restarted rspamd. Lets see.

thanks and cheers

**Comment by himpierre** [comment]
Disabling phishtank seems to fix my issue. Thank you.

**Comment by himpierre** [comment]
Oh wait. I fogot to ask. Should i try enabling phishtank with the next release?

**Comment by heraklit256** [comment]
I have the same problem here. Of course, disabling Phishtank generally is not an option, but I will try for the moment.

**Comment by heraklit256** [comment]
Confirmed memory leak is gone after disabling Phishtank and restarting `rspamd`.
