### ISSUE TITLE
DKIM check behavior differs from other scanners 

### ISSUE THREAD

**Issue by JeroenvO** [vstakhov/rspamd#2401]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.8 and 1.7.9, older version are not tested.

### Operation system, CPU, memory and environment:
Debian GNU/Linux 9 in LXC on Debian 9 host.
4GB ram (using cgroups in lxc)

### Description (Please provide a descriptive summary of the issue):
DKIM check behavior differs from other scanners (amavis/gmail). It is not known whether it is a bug in RSPAMD or in other systems.
When the 'Received' header is signed rspamd fails with R_DKIM_REJECT and logs get "rsa verify failed"
The same DKIM header signs valid when the mail is received by for instance Gmail, amavis or http://dkimvalidator.com/.

### Compile errors (if any):
-

### Steps to reproduce:
Send an email to a rspamd server using amavis. Let amavis sign the message (not opendkim) with default options:
```
 # /etc/amavis/conf.d/50-user
 $enable_dkim_verification = 1;
 $enable_dkim_signing = 1;
 dkim_key('domain.com', 'mail', '/etc/dkim/domain.com/mail.private');

 @dkim_signature_options_bysender_maps = (
 {
        'domain.com' => { d => 'domain.com', ttl => 21*24*3600, a => 'rsa-sha256', c => 'relaxed/simple' },
 } );
 @mynetworks = qw(0.0.0.0/8 127.0.0.0/8);  # list your internal networks
```
The message is dkim signed with a signature like:
```
 DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=domain.com;
    h=content-type:date:subject:from:to:mime-version:received
    :received; s=mail; t=1533456756; x=1535271157; bh=RmoWow+8Efspkf
    q71Ubj5ERu3IeZaboqUzogQ8xsY4Q=; b=bibSXMOx36Btq...7V8MyM=
```
Note that signing the 'received' header is discouraged by the spec (http://dkim.org/specs/rfc4871-dkimbase.html#rfc.section.5.5).
But since other spamfilters see this as valid DKIM, I guess it is valid, and as such rspamd should see it as valid as well.

When not signing 'Received' with DKIM, the DKIM is seen as valid by rspamd (and other spamfilters as well).
This is tested by setting these amavis dkim signing option:
```
 # /etc/amavis/conf.d/50-user
 $signed_header_fields{'received'}=0;
```

### Expected results:
The DKIM signed message is validated as valid by for instance Gmail, amavis or http://dkimvalidator.com/.
Rspamd should give R_DKIM_ALLOW

### Actual results:
Rspamd log entry (example):
```
 dkim; rspamd_dkim_signature_update: initial update hash with signature part: dkim-signature:v=1; a=rsa-sha256; c=relaxed/simple; d=domain.com; h=content-language:content-transfer-encoding:content-type :content-type:mime-version:user-agent:date:date:message-id:subject:subject:from:from:received:received; s=mail; t= 1533139538; x=1534953939; bh=Rd2KUFQp8Nm28IGYFQnMkDO8bN268ijWWcQ Iz3fJkrY=; b=
 dkim; rspamd_dkim_check: rsa verify failed
```
and the header R_DKIM_REJECT is added to the incoming message.

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
-

### Configuration:

Removed to keep issue readable.

**Comment by vstakhov** [comment]
Does it appear when `Received` *or* `User-Agent` to a list of signed headers? Failing on `Received` is not a bug most likely.

**Comment by JeroenvO** [comment]
Yes, example:
```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=domain.com;
	 h=user-agent:message-id:date:date:from:from:subject:subject
	:mime-version:content-type:content-type; s=mail; t=1533463700;
	 x=1535278101; bh=GdZ79xxpaRw/hffjstHVe423MLaou4SzJVeX/XN8Xi0=; b=
	avJ3+LvYHumsbLMZ2b9arlHBSMlzVxAijvTmi3sEYTGLaHnKGasrin0PyTyI6jRE
	/1xPV/t3hLv2jS1E5coQdY+zyLulwQK7FV9TO351C+gd/pCh5otTkHMSCRCOLq+O
	6J61Q71wgWF9aynfbsAf6eRLL7VGi2XCi40RREezzTg=
...
X-Spamd-Result: default: False [-4.51 / 150.00];
	 ARC_NA(0.00)[];
	 R_DKIM_REJECT(0.00)[domain.com];
	 R_SPF_ALLOW(-0.20)[+ip4:193.235.147.28];
	 MIME_GOOD(-0.10)[multipart/alternative,text/plain];
	 DKIM_TRACE(0.00)[domain.com:-];
	 DMARC_POLICY_ALLOW(0.00)[domain.com,quarantine];
	 DMARC_POLICY_ALLOW_WITH_FAILURES(-0.50)[];
```
But there is not header named `user-agent` in this message...

**Comment by JeroenvO** [comment]
Sorry, postfix was removing the user-agent message. The problem does not exist with the user-agent header anymore. I'll edit the issue.
If the 'Received' header problem is not a bug indeed, the issue can be closed.

**Comment by vstakhov** [comment]
Received header is added during milter phase. Hence, it will always fail.

**Comment by JeroenvO** [comment]
Ok, then its a bug in Amavis. Thanks for the help!
