### ISSUE TITLE
X-Spam header present under spam level

### ISSUE THREAD

**Issue by VonLatvala** [vstakhov/rspamd#2409]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

Data loss in the way that users won't discover legitimate mail in their spam folder

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Rspamd version:
`rspamd --version`
Rspamd daemon version 1.7.8

### Operation system, CPU, memory and environment:
`cat /etc/issue`
Ubuntu 18.04 LTS

### Description (Please provide a descriptive summary of the issue):
Mail gets flagged as spam even tho the score is below spam limit.

### Compile errors (if any):
N/A

### Steps to reproduce:
Ansible clone my repo

### Expected results:
Mail gets headers 
`X-Spamd-Result: default: False [11.40 / 15.00];`
BUT NOT
`X-Spam: Yes`

### Actual results:
Mail gets both
`X-Spamd-Result: default: False [11.40 / 15.00];`
... parameters explaining why ...
AND
`X-Spam: Yes`

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:

Full configuration (of all components except webmail) to the mailserver is available at https://bitbucket.org/VonLatvala/mailserver/src/master/

as an Ansible role.

**Comment by vstakhov** [comment]
Please read https://rspamd.com/doc/faq.html#what-are-rspamd-actions. Scores means nothing.
