### ISSUE TITLE
secure_ip localhost issue

### ISSUE THREAD

**Issue by dottedmag** [vstakhov/rspamd#241]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780928

rspam has this concept now of secure_ip which is basically a trusted IP.
The problem is that its 127.0.0.1 and if localhost resolves to ::1 first
it doesn't work.

You will either get connection refused or a password error.  It seems
that the socket code is not quite aware of IPv6 and will bind to either
v4 only or v6 only.

The default setup does this:
$ rspamc uptime
Results for command: uptime
HTTP error: 403, Unauthorized

Putting localhost in secure_ip doesn't seem to work, but changing it to
::1 makes the command line and rmilter happy again.

**Comment by fatalbanana** [comment]
Try secure_ip = "::1 127.0.0.1"

This should be fixed already in master/rspamd-0.8 branches.

**Comment by dottedmag** [comment]
I see, it is. Thank you.
