### ISSUE TITLE
DMARC policy plugin

### ISSUE THREAD

**Issue by vstakhov** [vstakhov/rspamd#242]
It would be good to have a post-filter that could check DMARK policies and match SPF and DKIM symbols regarding those policies.

**Comment by MisterM74** [comment]
Hello
You looking at how you create or re-looking at how develloper or already exists?
Mz

**Comment by fatalbanana** [comment]
It exists & mostly works but it's incomplete & so disabled in the default configuration. It will probably surface in 1.0.
