### ISSUE TITLE
get postfix queue id (rmilter scan qid: ) in lua

### ISSUE THREAD

**Issue by Fullmetal8ender** [vstakhov/rspamd#251]
It would be nice to have a method to get postfix queue id (rmilter scan qid: ) in lua

**Comment by fatalbanana** [comment]
This was recently added (In response to someone, I imagine you, asking for it): https://github.com/vstakhov/rspamd/blob/f786fc3053c2a3bc65a8ffe9bb4859f5c904be87/src/lua/lua_task.c#L1246

**Comment by Fullmetal8ender** [comment]
Yes, it was me. Thank You =)
