### ISSUE TITLE
DKIM check plugin only checks a single signature [$25]

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#254]
Per comment in the source it is the first signature though in my testing it seems to be the last one. Preferably we should support checking multiple signatures.

**Comment by msimerson** [comment]
Checking every DKIM signature is a pre-req for DMARC, as DMARC check each valid DKIM signature searching for an aligned one.

**Comment by vstakhov** [comment]
I see this point but I have never seen a single message with multiple DKIM signatures (mailing lists prefer just to delete all signatures in an original message and add  theirs own ones than to keep multiple signatures in messages sent). Therefore, I cannot really test this feature even if I'd have implemented it.

**Comment by msimerson** [comment]
> I have never seen a single message with multiple DKIM signatures

If any of your mail systems have any significant volume of traffic, then this can only mean that you simply weren't looking for multiple signatures. Granted, this is empirical, but just for fun, I grabbed the most current message in my inbox with a DKIM signature, and it has two signatures:

````
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=ietf.org; s=ietf1;
	t=1431282844; bh=FOnMurzZolcT/gPfe0b/ExLvclmjnRomUFd93oK1yo4=;
	h=References:Mime-Version:In-Reply-To:Message-Id:From:Date:To:Cc:
	 Subject:List-Id:List-Unsubscribe:List-Archive:List-Post:List-Help:
	 List-Subscribe:Content-Type:Sender;
	b=kaMkM....Mw4AHE=
DKIM-Signature: v=1; d=isdg.net; s=tms1; a=rsa-sha1;
 c=simple/relaxed; l=10050; t=1431282831; h=Received:Received:
 Message-Id:From:Subject:Date:To:Organization:List-ID; bh=kFJJea0
 Vm1YhozYUo4rMMzm7w4s=; b=nk0ryEBg....bRI
 PVtw=
````

The mailing list software in use on this particular list `X-Mailman-Version: 2.1.15` which is not even slightly unusual.

> mailing lists prefer just to delete all signatures in an original message

That is just plain wrong. Mailing list software is not homogenous and to claim that they all operate similarly is crazy-pants. Mailman offers administrators a variety of choices for dealing with DMARC (rejection of messages, stripping previous DKIM sigs, signing anew and modifying RFC 5322.From) and most others list software is completely DKIM agnostic, meaning it does nothing at all to or with the DKIM signatures.

**Comment by vstakhov** [comment]
Well, I completely understand that my case is not the generic case. I've sent several messages to, for example, FreeBSD postmasters about DKIM, gmail and mailman. However, I was told, that they won't add another DKIM signature or remove old one. Hence, all DKIM signatures from gmail passed via FreeBSD.org mailing lists are broken (as gmail includes the header `Sender` which is obviously modified by mailman).

I'm observing the same situation with exim mailing lists and other mailing lists I'm participating in (they all have broken gmail signatures).

To implement this feature, I just need some samples of e-mails with several DKIM signatures to experiment with.

**Comment by msimerson** [comment]
>  I just need some samples of e-mails with several DKIM signatures to experiment with.

[Here is a gist with a sample message](https://gist.github.com/msimerson/736430ab7509bd07eb60)

**Comment by vstakhov** [comment]
Thank you!

**Comment by vstakhov** [comment]
Well, it seems to be functional now.

**Comment by msimerson** [comment]
Nice. :)

**Comment by msimerson** [comment]
> Well, it seems to be functional now.

Can this Issue be closed now?

**Comment by fatalbanana** [comment]
Likely so though I haven't yet tested this...

DMARC plugin needs to be updated appropriately...

**Comment by vstakhov** [comment]
Yes, let's leave it open unless we can confirm that my logic of DKIM validation is exactly the same to those described in DMARC RFC.

**Comment by fatalbanana** [comment]
This should be fixed as of 1.0.0- I've confirmed at least relaxed canonicalization to work, I've not yet tested simple.

**Comment by fatalbanana** [comment]
Ok, finally tested:

2x 'simple': OK
'simple' + 'relaxed': OK
3 domains: OK

So it looks good to me.

**Comment by msimerson** [comment]
> Did you help close this issue? Go claim the $25 bounty on Bountysource.

PSA: bounty is still unclaimed.
