### ISSUE TITLE
phishing module documentaion

### ISSUE THREAD

**Issue by jpastuszek** [vstakhov/rspamd#262]
I was trying to reverse engineer it and I have figured out that there is C part that checks for www. domain in href to match with anchor text but I cannot figure out how to add exceptions for this.
Can you document that and the use of 'strict_domains' and 'domains' options, please?

**Comment by fatalbanana** [comment]
Well- it's documented now: https://github.com/vstakhov/rspamd/blob/master/doc/markdown/modules/phishing.md

Note that comparison of domains by TLD as described here is newly added (and not applicable to 0.8.x).
