### ISSUE TITLE
fuzzy_add does not complete SQLite transactions

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#267]
It seems that fuzzy_add does not complete SQLite transactions.

After executing the command:
```
# rspamc -f 1 -w 20 fuzzy_add fuzzy.eml
Results for file: fuzzy.eml
success = true;
```
fuzzy.db-journal file appears in /var/db/rspamd directory and then disappears in about 90 seconds.
Changes not commited to fuzzy.db file.
```
# pkg info -E rspamd sqlite3
rspamd-0.8.3
sqlite3-3.8.9.0
# uname -v
FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 22:51:51 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC
```
rspamd.conf:
```
worker {
    type = "fuzzy";
    bind_socket = "*:11335";
    hash_file = "${DBDIR}/fuzzy.db"
    expire = 90d;
    allow_update = "127.0.0.1";
}
```
modules.conf:
```
fuzzy_check {
    min_bytes = 300;
        rule {
                servers = "localhost:11335";
                servers = "highsecure.ru:11335";
                symbol = "FUZZY_UNKNOWN";
                mime_types = "application/pdf";
                max_score = 20.0;
                skip_unknown = yes;
                fuzzy_map = {
                        FUZZY_DENIED {
                                max_score = 20.0;
                                flag = 1
                        }
                        FUZZY_PROB {
                                max_score = 10.0;
                                flag = 2
                        }
                        FUZZY_WHITE {
                                max_score = 2.0;
                                flag = 3
                        }
                }
        }
}
```

**Comment by fatalbanana** [comment]
I guess you need read_only = "no".

It probably makes sense to define these separately for such reason (perhaps the docs should be updated?):

fuzzy_check {
    min_bytes = 300;
        rule {
                servers = "highsecure.ru:11335";
                symbol = "FUZZY_UNKNOWN";
                mime_types = "application/pdf";
                max_score = 20.0;
                read_only = yes;
                skip_unknown = yes;
                fuzzy_map = {
                        FUZZY_DENIED {
                                max_score = 20.0;
                                flag = 1
                        }
                        FUZZY_PROB {
                                max_score = 10.0;
                                flag = 2
                        }
                        FUZZY_WHITE {
                                max_score = 2.0;
                                flag = 3
                        }
                }
        }
       rule {
                servers = "127.0.0.1:11335";
                symbol = "R_LOCAL_FUZZY";
                max_score = 20.0;
                mime_types = "application/pdf";
                read_only = no;
                skip_unknown = yes;
                fuzzy_map = {
                        R_LOCAL_FUZZY_DENIED {
                                weight = 20.0;
                                flag = 66
                        }
                        R_LOCAL_FUZZY_WHITE {
                                weight = 0.0;
                                flag = 68
                        }
                }
        }
}

**Comment by moisseev** [comment]
I think ```read_only = "no"``` is the default. I tried to add ```read_only = "no"``` to the fuzzy_check configuration anyway but nothing has changed.

Then I tried to split fuzzy_check configuration in two different rules as you suggested. It does not work too.

**Comment by fatalbanana** [comment]
Hmm yes you're right RE: the default- I actually checked this but somehow misinterpreted results, sorry. :)

**Comment by moisseev** [comment]
Documentation states "On check, rspamd selects a server in round-robin matter." What does it exactly mean? If hash is not found does rspamd try another server or give up?

Suppose we have 2 rules with 2 servers in each. The Fuzzy_check module will check only one server or one server in each rule?

**Comment by vstakhov** [comment]
For the first issue: rspamd updates transaction each minute + 0 to minute random jitter (so it's from minute to two minutes). The transaction is also committed on rspamd shutdown. During this time, the changes are *not* visible to query.

For the second issue: no, there is no retransmit of fuzzy requests at the moment, however, I think about adding this feature in the meantime.

**Comment by moisseev** [comment]
My problem is transactions not committed at all.
Immediately after adding message to fuzzy storage with rspamc (when fuzzy.db-journal file is in /var/db/rspamd directory) I can query fuzzy storage worker and get expected score. At the moment when transaction should be committed, fuzzy.db-journal file disappears, but nothing has written to the db file and queries does not return score any more.

**Comment by vstakhov** [comment]
That's very strange indeed. I need to check code in 0.8.3. That obviously works in 0.9 :)

**Comment by fatalbanana** [comment]
Working for me at 0.8.3 on Ubuntu fwiw. ;)

**Comment by vstakhov** [comment]
Maybe there is some issue with access permissions?

**Comment by moisseev** [comment]
I don't think so since rspamd is able to create both files.
```
# ll /var/db/rspamd/fuzzy*
-rw-r--r--  1 nobody  nobody  6144 21 апр 14:54 /var/db/rspamd/fuzzy.db
-rw-r--r--  1 nobody  nobody  3608 21 апр 14:56 /var/db/rspamd/fuzzy.db-journal
```
```
# ps waux | grep rspamd | grep -v grep
nobody   97988   0,0  5,4 120532 111932  -  Is   13:48        0:00,12 rspamd: main process (rspamd-0.8.3)
nobody   97989   0,0  5,5 120532 112448  -  I    13:48        0:00,07 rspamd: fuzzy process (rspamd-0.8.3)
nobody   97990   0,0  5,5 120564 112536  -  S    13:48        0:00,31 rspamd: controller process (rspamd-0.8.3)
nobody   97991   0,0  5,6 124660 116032  -  S    13:48        0:00,57 rspamd: normal process (rspamd-0.8.3)
nobody   97992   0,0  5,7 124676 116408  -  S    13:48        0:00,92 rspamd: normal process (rspamd-0.8.3)
```

**Comment by vstakhov** [comment]
What do you see inside these files using sqlite command line utility? Are they empty?

**Comment by moisseev** [comment]
```
# sqlite3 fuzzy.db
SQLite version 3.8.9 2015-04-08 12:16:33
Enter ".help" for usage hints.
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE digests(id INTEGER PRIMARY KEY,flag INTEGER NOT NULL,digest TEXT NOT NULL,value INTEGER,time INTEGER);
CREATE TABLE shingles(value INTEGER NOT NULL,number INTEGER NOT NULL,digest_id INTEGER REFERENCES digests(id) ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX t ON digests(time);
CREATE UNIQUE INDEX d ON digests(digest);
CREATE UNIQUE INDEX s ON shingles(value, number);
COMMIT;
sqlite> .quit
```
I have no idea how to see sqlite journal contents.
```
# sqlite3 fuzzy.db-journal
SQLite version 3.8.9 2015-04-08 12:16:33
Enter ".help" for usage hints.
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
/**** ERROR: (26) file is encrypted or is not a database *****/
ROLLBACK; -- due to errors
sqlite> .quit
```

**Comment by vstakhov** [comment]
Yes, it seems that no data is written to your storage.

**Comment by vstakhov** [comment]
I'd suggest to trace fuzzy process when it is being terminated normally (e.g. when main process receives terminating signal).

**Comment by moisseev** [comment]
truss output:
http://pastebin.com/SfghUukW

**Comment by vstakhov** [comment]
Well, I really don't understand what happens. In the master branch, I've added `sync` option to the fuzzy worker (e.g. `sync = 10s`). Could you please try it in your environment?

**Comment by moisseev** [comment]
I didn't try master branch for some reason. I have made changes against 0.8.3 like in that commits done: 145c4fd779a17297fea5e4a8490201644e67980f 7a334aa330a6e8dfe87bb97d186da4977b27594e

https://gist.github.com/moisseev/225dab09d9a9c99c337b

The sync timeout option works, but sqlite doesn't write anything to storage file anyway.

I have two production servers with rspamd installed. Both of them have the issue. Today I tried to reproduce the issue in test environment in several ways, but I couldn't.

**Comment by vstakhov** [comment]
Could you turn debug logging on? This should show if an sqlite3 query has failed.

**Comment by moisseev** [comment]
I overlooked one thing: in test environment fuzzy worker writes digest to storage but deletes it on terminate.

Here logs from two systems.
This one writes to sqlite file, but removes data when rspamd receives terminating signal:
http://pastebin.com/ZiwqtPse
And this one doesn't write to sqlite file at all:
http://pastebin.com/gqeCK0bK

**Comment by fatalbanana** [comment]
Do you have multiple fuzzy workers in config?

**Comment by moisseev** [comment]
I don't. Just one fuzzy worker and two rules in fuzzy_check module as you suggested.

**Comment by vstakhov** [comment]
Ah, maybe you should set expire then?

**Comment by fatalbanana** [comment]
He does appear to have it set in the example provided.

**Comment by vstakhov** [comment]
Yes, but deletion occurs merely in the case of expiration.

**Comment by moisseev** [comment]
I tried to change the expire to different values in the worker configuration below but no luck.
```
worker {
    type = "fuzzy";
    bind_socket = "*:11335";
    hash_file = "${DBDIR}/fuzzy.db"
    expire = 90d;
    allow_update = "127.0.0.1";
    sync = 10s;
}
```
Also I have installed rspamd from the master branch. It doesn't write to the storage at all.
```
2015-04-25 12:25:24 #36740(controller) process_image: detected GIF image of size 735 x 936 in message <1E1BADFEF52102815D5811ACA832053E@galerie-neuhaus.ru>
2015-04-25 12:25:24 #36740(controller) fuzzy_generate_commands: <1E1BADFEF52102815D5811ACA832053E@galerie-neuhaus.ru>, part is shorter than 300 symbols, skip fuzzy check
2015-04-25 12:25:24 #36739(fuzzy) radix_find_compressed: trying to find key
2015-04-25 12:25:24 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `SELECT value, time, flag FROM digests WHERE digest==?1;`
2015-04-25 12:25:24 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `INSERT INTO digests(flag, digest, value, time) VALUES(?1, ?2, ?3, ?4);`
2015-04-25 12:25:24 #36739(fuzzy) radix_find_compressed: trying to find key
2015-04-25 12:25:24 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `SELECT value, time, flag FROM digests WHERE digest==?1;`
2015-04-25 12:25:24 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `UPDATE digests SET value = value + ?1 WHERE digest==?2;`
2015-04-25 12:25:24 #36740(controller) fuzzy_learn_callback: processed fuzzy hash, list: FUZZY_DENIED:1 for message <1E1BADFEF52102815D5811ACA832053E@galerie-neuhaus.ru>
2015-04-25 12:25:24 #36740(controller) rspamd_task_free: free pointer 29025108
2015-04-25 12:25:24 #36740(controller) destroy_message: freeing pointer 29055900
2015-04-25 12:25:34 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `DELETE FROM digests WHERE time < ?1;`
2015-04-25 12:25:34 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `COMMIT;`
2015-04-25 12:25:34 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `BEGIN TRANSACTION;`
2015-04-25 12:25:46 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `DELETE FROM digests WHERE time < ?1;`
2015-04-25 12:25:46 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `COMMIT;`
2015-04-25 12:25:46 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `BEGIN TRANSACTION;`
2015-04-25 12:26:02 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `DELETE FROM digests WHERE time < ?1;`
2015-04-25 12:26:02 #36739(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `COMMIT;`

```

**Comment by vstakhov** [comment]
Are you using 32 bits or 64 bits platform btw?

**Comment by vstakhov** [comment]
And do you see that expired count changes over time in your case?

**Comment by vstakhov** [comment]
Oh, that's awesome! Expire is totally broken now. I'm working on a fix.

**Comment by vstakhov** [comment]
Should work now. I've backported this patch to 0.8 branch.

**Comment by moisseev** [comment]
I have tested both master and 0.8. It works now. Thanks!

Could you please clarify mime_types setting?  What are default mime types? What additional mime types make sense?
```
fuzzy_check {
	rule {
	         # List of additional mime types to be checked in this fuzzy
		mime_types = "application/pdf";
	}
}
```
Just FYI: you have mistyped my GitHub username in commit messages.

**Comment by vstakhov** [comment]
Well, from rspamd 0.9 you can specify mime types as following:

~~~nginx
mime_types = "application/*"; # All with application/*
mime_types = "*"; # All attachements
mime_types = ["application/pdf", "application/ms-word"]; # Array of two types
mime_types = "application/pdf, application/ms-word"; # Legacy format
~~~

Moreover, rspamd-0.9 would read all `mime_types` definitions and concatenate to a single list. In rspamd 0.8, the only available type was the last one (comma separated string) with no wildcards available.
