### ISSUE TITLE
Cannot start CentOS 7

### ISSUE THREAD

**Issue by frederikbosch** [vstakhov/rspamd#268]
Just installed rspamd from pre-build CentOS 7 source. Service won't start. I retrieved the following from ```/var/log/messages```

```
systemd_get_socket: cannot get systemd variable 'LISTEN_FDS'
spawn_workers: cannot listen on socket systemd:1: No such file or directory
```

**Comment by frederikbosch** [comment]
After changing rspamd.conf to the one below, it worked. Perhaps it is an idea to start with this one CentOS from the start. Now it does not work out-of-the-box, at least in our case.

```
.include "$CONFDIR/common.conf"

options {
    .include "$CONFDIR/options.inc"
}

logging {
    type = "console";
    .include "$CONFDIR/logging.inc"
}

worker {
    bind_socket = "localhost:11333";
    .include "$CONFDIR/worker-normal.inc"
}

worker {
    bind_socket = "localhost:11334";
    .include "$CONFDIR/worker-controller.inc"
}

```

**Comment by vstakhov** [comment]
It seems to be systemd mess. I have not enough testing power to cover all those cases unfortunately.

**Comment by frederikbosch** [comment]
@vstakhov Ok, I do not know systemd at all tbh. My suggestion would be to listen at network address/port by default. But this thread can be closed.

**Comment by fatalbanana** [comment]
The packaged version of Rspamd for CentOS 7 (and other platforms with systemd) is socket-activated.

To enable run on startup:
`systemctl enable rspamd.socket`

To start once:
`systemctl start rspamd.socket`

Rspamd will be started on-demand, so to simulate this you could run:
`rspamc stat`

**Comment by frederikbosch** [comment]
@fatalbanana Ok, so I used the wrong command? On CentOS I should not use ```/sbin/service rspamd start```, but ```systemctl start rspamd.socket```?

**Comment by fatalbanana** [comment]
I haven't tested such syntax so I can't say RE: `service` but I can say that in my experience the CentOS7 package works when used as suggested above. :)

**Comment by frederikbosch** [comment]
@fatalbanana You are right. It works. But I still find my point valid to change the default config to use localhost:port. ```https://rspamd.com/doc/integration.html``` shows only examples where rspamd listens on ports. So I guess that is the majority of use cases.

If you do not agree, I will create a PR for the rspamd website containing exactly your words so people using CentOS know how to get it running.

**Comment by fatalbanana** [comment]
Changing that would break socket-activation. Listening address/port can be set by editing rspamd.socket. There is some work in progress to make some simple introductory documentation, currently residing on the wiki: https://github.com/vstakhov/rspamd/wiki/ - which covers socket-activation. It might be worth putting this on the download page as well.

**Comment by frederikbosch** [comment]
@fatalbanana Thanks for your help! I created a PR that should help other people using CentOS.

**Comment by skibbipl** [comment]
Hello,
I'm having exact issue on debian. Yesterday I switched to systemd and rspamd failed to start. I tried to enable socket via
```systemctl enable rspamd.socket```
but it failed with following message:
```
The unit files have no [Install] section. They are not meant to be enabled
using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
```
I can manually start the socket service, but I prefer systemd to start it on boot. Can some systemd experts tell me what should I put in [Install] section in rspamd.socket?

**Comment by frederikbosch** [comment]
@skibbipl I can remember that I also have the same problem. The process only starts manually, not on boot at the moment. Maybe @fatalbanana is willing to help one more time.

**Comment by fatalbanana** [comment]
Try adding the following to rspamd.socket file - I'll see about fixing the package:

```
[Install]
WantedBy=sockets.target
```

**Comment by skibbipl** [comment]
Thanks!
```
# systemctl enable rspamd.socket
Created symlink from /etc/systemd/system/sockets.target.wants/rspamd.socket to /lib/systemd/system/rspamd.socket.
```

**Comment by sbrl** [comment]
For future reference, this also helped me figure out the problem with opendkim on ubuntu 15.10. The switch to systemd on my VPS went and changed this config file without my permission it seems.
