### ISSUE TITLE
Per-user bayes/fuzzy storage?

### ISSUE THREAD

**Issue by wildstray** [vstakhov/rspamd#275]
It is or it will be possibile?

**Comment by fatalbanana** [comment]
User-specific bayes storage is planned for 1.0 I'm told; dunno about fuzzy.

**Comment by wildstray** [comment]
Ok! I'll patiently wait ;) Bayes is enough to replace SA.

**Comment by vstakhov** [comment]
User specific fuzzy storage is meaningless from my point of view. User specific bayes is highly desired but unless we introduce sqlite and redis backends for statistics, this option is unrealistic. I've come close to this feature in 0.9, but it won't be in 0.9 likely. But it's definitely a milestone for 1.0.

**Comment by psy0rz** [comment]
so is it fixed in 1.x?

**Comment by fatalbanana** [comment]
Yes, per-user statistics were introduced in 1.0: https://rspamd.com/doc/configuration/statistic.html
