### ISSUE TITLE
mime_types = "*"; doesn't work in fuzzy check configuration

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#283]
rspamd-0.9.1
```mime_types = "*";``` doesn't work in fuzzy check module configuration but ```mime_types = "*/*";``` works.

P.S. Would you clarify in documentation that ```mime_types``` doesn't affect learning?

**Comment by vstakhov** [comment]
That's a good catch, thank you! Mime types are considered during learning, aren't they?

**Comment by moisseev** [comment]
I found ```mime_types``` setting don't affect learning at all actually, but I have different results for checks.

For instance (for the same message):
```mime_types = "image/gif";```
Symbol: FUZZY_DENIED (9.99)[1: 1.00 / 0.99, 1: 1.00 / 0.99]

```mime_types = "";```
Symbol: FUZZY_DENIED (9.91)[1: 1.00 / 0.99]

**Comment by vstakhov** [comment]
From the code, I can only conclude that there are no differences between the path for learning and checking with the only exception that for checking rspamd also tries legacy fuzzy format (but not for learning). Mime types are processed in the same way.
