### ISSUE TITLE
Passing in additional data as HTTP headers [$100]

### ISSUE THREAD

**Issue by msimerson** [vstakhov/rspamd#285]
This is a rabbit trail from the discussion in #197 that really belongs in its own issue. 

> On the other hand, I'm pretty unsure that it's a good idea to do such a checks from JS...
> So maybe it would be good idea to reuse that functions from rspamd and skipping them in Haraka.

I can understand why you might think that, but opinions vary. Not performing those checks in Haraka is unlikely for a very long time, and here's why I think that:
### 24 Hr. stats

(collected with [Elasticsearch plugin](https://github.com/baudehlo/Haraka/pull/906)
- connections: 11,542  (small server, a few hundred users, and a few Exchange servers)
- transactions: 7,419  (connection got to MAIL FROM)
- delivered messages: 3,016
- False Positives: 1  (sender had SPF: Fail, listed on uceprotect.com, & spammy ASN)
- False Negatives / delivered spam: 8
### Nasties Detected By

| count | tool |
| --: | --- |
| 89 | Clamd + unofficial |
| 196 | rspamd (is_spam=true) |
| 557 | rspamd (add_header) |
| 332 | spamassassin (score > 5) |
| 1618 | URIBL |
| 2126 | b.barracudacentral.org |
| 1175 | spamhaus.org |
| 4051 | [karma](https://github.com/baudehlo/Haraka/blob/master/docs/plugins/karma.md) |

URIBL is interesting, based on where it detected:

| count | location |
| --: | --- |
| 1338 | Envelope From |
| 205 | HELO hostname |
| 167 | reverse DNS |
| 62 | body |

For the purposes of measurement and data collection, I'm currently letting every connection continue until after DATA, and then rejecting bad ones.  Usually though, I refuse some connections outright, block others at HELO, and most at DATA (before message is sent). I'm blocking heuristically with karma, as soon as I have enough confidence I can safely (without risk of FP) do so.

So you see, in normal usage, rspamd (and other content scanners) will only ever see a small percentage of the mail traffic. The most efficient processing is that which is avoided.

In the messages rspamd sees, most of the connection metadata (like rDNS, GeoIP, ASN, SPF, DNSBL, URIBL) has already been processed by Haraka and that's unlikely to change. Providing a way to pass that metadata to rspamd via HTTP headers would be a lot more efficient than rspamd fetching / calculating it again.
##

**Comment by fatalbanana** [comment]
One way to do this could be to add headers to the message itself (not quite so elegant as passing these over HTTP, but it should work readily).

Modules like SPF, SURBL, RBL- could be disabled outright and local rules could be added to examine particular headers and add scoring for these.

**Comment by vstakhov** [comment]
I strongly disagree with the approach of modifying message somehow. I've added an ability to get and set HTTP headers directly from lua. So the only remaining issue is to adopt the existing plugins to use that information from HTTP headers and do not do extra work if it's already there.

**Comment by msimerson** [comment]
> the only remaining issue

Great news! :-)

**Comment by vstakhov** [comment]
Yes, but we need to agree about what information should be considered by rspamd from these headers. Then I can add this logic to rspamd plugins.

**Comment by msimerson** [comment]
I'd start with this list:

* GeoIP: { **"asn": "32748"**,  "org": "Steadfast Networks", **"continent": "NA",  "country": "US"**, "region": "CO", "city": "Boulder", "ll": [ 40.048100000000005, -105.3842 ], **"distance": "1101"** }
* p0f: { **"os_name": "Linux"**, "os_flavor": "3.1-3.10" }
* FCrDNS: { "ptrs": [ { name: "o1.emailsg.servicebridge.com", ips: [ "208.117.56.85" ] } ] }
    * basis for "iprev=pass;" in Authentication-Results header
* TLS: { version=TLSv1 cipher=AES128-GCM-SHA256 **verify=YES** }
* SPF: { scope: "(helo | mfrom)", domain: "example.com", **result: "Pass"** }
    * basis for "spf=pass smtp.mailfrom=gmail.com;" in Authentication-Results header
* DKIM-Signature: { domain => 'example.com', selector => 'apr2013', result => 'fail', human_result => 'fail (body has been altered)', }
    * one signature per header, JSON encoded, with enough info that rspamd can do DMARC evaluation (if desired)
* DMARC: { result => 'pass', disposition  => 'none', reason => [ { type => 'sampled_out', comment  => 'mailing_list', } ], dkim => 'pass', dkim_align => 'strict', spf => 'pass', spf_align => 'relaxed' }
    * DMARC format: a DMARC result (see [RFC appendix C](https://tools.ietf.org/html/rfc7489#section-6) or [Mail::DMARC::Result](https://metacpan.org/pod/Mail::DMARC::Result)
    * basis for "dmarc=pass (p=none d=gmail.com)" in Authentication-Results header
    * if SPF and DKIM are available and DMARC is not, rspamd will have enough information (based on formats above) to process DMARC itself.
* DNSBL: bl.spamcop.net
* DNSBL: b.barracudacentral.org
    * does rspamd do anything based on the result (such as, scoring differently for a 127.0.0.4 -vs- a 127.0.0.5 on certain lists?  If so, maybe include the DNS answer appended to the list name?

I bolded a few chunks of the data above, which are bits of data that **can** have very strong ham/spam correlations. For example, SPF: Pass is useless, as good spammers have more consistent SPF passes than many legit small businesses. But a SPF: Fail is almost certainly spam. A Windows server that doesn't have relay privileges and doesn't have a hostname ending in outlook.com has a high spam correlation. GeoIP distance < 4000km has very little correlation, but mail in excess of 4000km has a strong spam correlation. Etc..

**Comment by vstakhov** [comment]
That looks very cool. I think we need to create a sort of pre-filter in lua that grabs this information from the request headers and pushes the specific symbols to the task's results. Next, we need that all plugins should take these results into consideration and does not perform unnecessary checks in future.

**Comment by vstakhov** [comment]
Is it still actual? It seems to be implemented now.

**Comment by msimerson** [comment]
I haven't gotten around to validating but I'll just assume it works. Please claim the bounty and I'll approve it.

**Comment by msimerson** [comment]
I've gotten around to testing and it [works](haraka/Haraka#2050) for SPF. (I haven't tried the others.)
