### ISSUE TITLE
Multiple Servers: Shared configuration and shared statistics

### ISSUE THREAD

**Issue by adestis-mb** [vstakhov/rspamd#291]
What is the recommended way to share configuration and statistics over more than one server?
e.g. if you have a HA installation
##

**Comment by vstakhov** [comment]
Previously, I've implemented something like binary logs and replication for statistics. But since it was not demanded or tested by anyone I've just drop that feature off. Currently, I'd recommend just to learn all your servers simultaneously. In the future version of rspamd I plan to support various backends for rspamd and some of them, namely redis, has their own replication logic.

**Comment by moisseev** [comment]
I do all learning at one system and copy statfiles to another one periodically. I am overwriting bayes statfiles on the target system on-the-fly (I am using `mv`, actually). At restart rspamd reopens stat files and gets the new file descriptors. It would be better if rspamd reopen statfiles on USR1, but restart do the job.

But for doing `sqlite3 fuzzy.db ".restore somefile"` rspamd should be stopped because of it permanently locks the database.
Is it possible to configure fuzzy worker to open database in read only mode without locking it permanently?

**Comment by vstakhov** [comment]
Yes, I'll fix fuzzy to avoid blocking unless it is really needed. For 1.0, I have plans to support at least sqlite3 statistics and, probably, postgresql or redis based backends.

**Comment by vstakhov** [comment]
Well, I've turned fuzzy storage to WAL locking mode, so this should resolve your issue.

**Comment by moisseev** [comment]
rspamd_fuzzy_backend_open_db: WAL mode is not supported
```
# uname -srm
FreeBSD 10.1-RELEASE i386
```
```
# pkg info -E sqlite3
sqlite3-3.8.10.2
```
```
2015-06-30 10:40:13 #10834(fuzzy) fork_worker: starting fuzzy process 10834
2015-06-30 10:40:13 #10834(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `VACUUM;`
2015-06-30 10:40:13 #10836(normal) fork_worker: starting normal process 10836
2015-06-30 10:40:13 #10836(normal) rspamd_hosts_fin: read hash of 214 elements
2015-06-30 10:40:13 #10834(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `SELECT COUNT(*) FROM digests;`
2015-06-30 10:40:13 #10834(fuzzy) rspamd_fuzzy_backend_open_db: WAL mode is not supported, locking issues might occur
2015-06-30 10:40:13 #10834(fuzzy) rspamd_fuzzy_backend_run_stmt: executing `BEGIN TRANSACTION;`
```

**Comment by vstakhov** [comment]
Are you using your storage on NFS?

**Comment by moisseev** [comment]
No, UFS+SU on VirtualBox
```
# tunefs -p /dev/ada0p2
tunefs: POSIX.1e ACLs: (-a)                                disabled
tunefs: NFSv4 ACLs: (-N)                                   disabled
tunefs: MAC multilabel: (-l)                               disabled
tunefs: soft updates: (-n)                                 enabled
tunefs: soft update journaling: (-j)                       disabled
tunefs: gjournal: (-J)                                     disabled
tunefs: trim: (-t)                                         disabled
tunefs: maximum blocks per file in a cylinder group: (-e)  4096
tunefs: average file size: (-f)                            16384
tunefs: average number of files in a directory: (-s)       64
tunefs: minimum percentage of free space: (-m)             8%
tunefs: space to hold for metadata blocks: (-k)            6408
tunefs: optimization preference: (-o)                      time
tunefs: volume label: (-L)
```

**Comment by vstakhov** [comment]
Could you open any non-existing filename (e.g. `test.sqlite`) on that fs using `sqlite3` CLI utility and type the following command there:

    PRAGMA journal_mode=WAL;

**Comment by moisseev** [comment]
```
# sqlite3 test.sqlite
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite> PRAGMA journal_mode=WAL;
wal
sqlite>
```

**Comment by vstakhov** [comment]
Well, I've added a small diagnostic message to master and 0.9 branches. Could you test it please?

**Comment by moisseev** [comment]
`2015-06-30 16:52:37 #57446(fuzzy) rspamd_fuzzy_backend_open_db: WAL mode is not supported (1), locking issues might occur`

**Comment by moisseev** [comment]
It works in 0.9.9, thanks!
What's about reopening statfiles and databases on USR1?

**Comment by moisseev** [comment]
Backing up fuzzy.db and restoring on another server worked fine since 0.9.9, but after upgrade to 1.0.x live restore `sqlite3 fuzzy.db ".restore /var/db/rspamd/fuzzy.db"` leads to database locking until rspamd restarted.
```
2015-10-06 07:11:41 #82579(fuzzy) <b46ea8>; fuzzy_backend; rspamd_fuzzy_backend_sync: cannot execute expired statement: database is locked
2015-10-06 07:11:41 #82579(fuzzy) logger; file_log_function: Last message repeated 301 times
```
```
# fuser /var/db/rspamd/fuzzy.db
# ps -aux | grep 57116 | grep -v grep
nobody   57116   0,0  0,9 273748 18012  -  I    вт15        0:01,07 rspamd: fuzzy process (rspamd-1.0.4)
```

**Comment by vstakhov** [comment]
Maybe you could try something like `PRAGMA journal_mode=wal` before restoring data from the dump?

**Comment by moisseev** [comment]
Thanks, I've got it.

**Comment by moisseev** [comment]
It didn't help actually.
```
# sqlite3 ./fuzzy.db "PRAGMA journal_mode;"
delete
# sqlite3 ./fuzzy.db "PRAGMA journal_mode=wal;"
wal
# sqlite3 /var/db/rspamd/fuzzy.db ".restore ./fuzzy.db"
# tail -50 /var/log/rspamd/rspamd.log | grep 'rspamd_fuzzy_backend_sync'
2015-10-08 22:06:55 #30401(fuzzy) <8695d3>; fuzzy_backend; rspamd_fuzzy_backend_sync: cannot execute expired statement: database is locked
2015-10-08 22:06:55 #30401(fuzzy) <8695d3>; fuzzy_backend; rspamd_fuzzy_backend_sync: cannot execute expired statement: database is locked
2015-10-08 22:09:57 #31668(fuzzy) <8b2aca>; fuzzy_backend; rspamd_fuzzy_backend_sync: cannot execute expired statement: database is locked
```

**Comment by vstakhov** [comment]
You need to set WAL mode in the same sqlite3 session, I think.

**Comment by moisseev** [comment]
I am not familiar with sqlite, but I believe journal mode should be stored in database files.
At least retestings shows the WAL mode. If I interpret results in the right way.
```
# sqlite3 ./fuzzy.db "PRAGMA journal_mode;"
delete
# sqlite3 ./fuzzy.db "PRAGMA journal_mode=wal;"
wal
# sqlite3 ./fuzzy.db "PRAGMA journal_mode;"
wal
# sqlite3 /var/db/rspamd/fuzzy.db ".restore ./fuzzy.db"
# sqlite3 /var/db/rspamd/fuzzy.db "PRAGMA journal_mode;"
wal
```

**Comment by bpbp-boop** [comment]
Glancing at the source for the stats module - it looks like you've implemented redis support?

Is this config correct?
```
classifier {
        type = "bayes";
        tokenizer {
                name = "osb";
        }
#       cache {
#               path = "${DBDIR}/learn_cache.sqlite";
#       }
        min_tokens = 11;
        backend = "redis";

        statfile {
                symbol = "BAYES_HAM";
                servers = "127.0.0.1:6379"
                spam = false;
        }
        statfile {
                symbol = "BAYES_SPAM";
                server = "127.0.0.1:6379"
                spam = true;
        }
}
```

ie, using the same redis server for both spam and ham. Will it select different DBs?
