### ISSUE TITLE
Good documentation

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#292]
hello
Having not said the last time, but I wanted to install a package, but it lacks a documation, good documentation on installation and configuration of the package.
Surely I have not understood, just knowing what we do, it would be simpler.
thank you
Mz

**Comment by fatalbanana** [comment]
Have you seen https://rspamd.com/doc/quickstart.html ?

**Comment by MisterM74** [comment]
Ok, clear it would go through the (forum)
But is that there is not an iso image, I understand how it works?

**Comment by fatalbanana** [comment]
Hmmm, Rspamd is not an appliance (and I'm not aware of any appliances that ship it at the moment). Binary packages are available for a small variety of operating systems (see quickstart) - the easiest route to installation is using those.
