### ISSUE TITLE
rspamd: write (localhost) Broken pipe

### ISSUE THREAD

**Issue by achch** [vstakhov/rspamd#294]
FreeBSD 10.0-RELEASE-p18
I installed the binary package from the repository (pkg install rspamd) rspamd-0.9.5
in the logs was a lot of pieces to appear:

Jun 15 00:01:30 postmaster rmilter[913]: mlfi_eom: 94DEC4E669: tempfile=/tmp/msg.dSFZEQAU, size=1067341
Jun 15 00:01:30 postmaster rmilter[913]: rspamd: write (localhost), 32: Broken pipe
Jun 15 00:01:30 postmaster rmilter[913]: rspamdscan: failed to scan, retry, localhost, /tmp/msg.dSFZEQAU
Jun 15 00:01:31 postmaster rmilter[913]: rspamd: write (localhost), 32: Broken pipe
Jun 15 00:01:31 postmaster rmilter[913]: rspamdscan: failed to scan, retry, localhost, /tmp/msg.dSFZEQAU
Jun 15 00:01:32 postmaster rmilter[913]: rspamd: write (localhost), 32: Broken pipe
Jun 15 00:01:32 postmaster rmilter[913]: rspamdscan: failed to scan, retry, localhost, /tmp/msg.dSFZEQAU
Jun 15 00:01:33 postmaster rmilter[913]: rspamd: write (localhost), 32: Broken pipe
Jun 15 00:01:33 postmaster rmilter[913]: rspamdscan: failed to scan, retry, localhost, /tmp/msg.dSFZEQAU
Jun 15 00:01:34 postmaster rmilter[913]: rspamd: write (localhost), 32: Broken pipe
Jun 15 00:01:34 postmaster rmilter[913]: rspamdscan: retry limit exceeded, localhost, /tmp/msg.dSFZEQAU

**Comment by fatalbanana** [comment]
Perhaps some issue particular to the problem messages?

**Comment by achch** [comment]
the problem was newsyslog and send a signal HUP. I change to SIGUSR1 and the problem disappeared.
/var/log/rspamd/rspamd.log      nobody:nobody   644     7       *       @T00    CB      /var/run/rspamd/rspamd.pid      30
