### ISSUE TITLE
unix:/var/run/rmilter/rmilter.sock: No such file or directory

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#295]
hello
While waiting for my approval on the forum, I'm testing period with rspamd and rmilter.
I have a concern, below, you notice an error:

warning: connect to Milter service unix:/var/run/rmilter/rmilter.sock: No such file or directory

The worry is that the following file is and I do not know what I should do, and permission, chown and chmod are okay ...

thank you
Mz
##

**Comment by fatalbanana** [comment]
I'd guess rmilter should create that on startup- is rmilter running? does it throw errors on startup? how have you installed it & on what platform?

**Comment by MisterM74** [comment]
Ubuntu Trusty 14.04 yes it starts and no, I would not change operating system ...

**Comment by fatalbanana** [comment]
Does `netstat -lnp` show rmilter listening somewhere? I have not much of an idea why you may see such issue tbh (mailer is in a chroot?). I haven't actually tried rmilter.. :(

**Comment by MisterM74** [comment]
Hello

Active Internet connections (only servers)
tcp        0      0 0.0.0.0:11333           0.0.0.0:*               LISTEN      28879/rspamd: main 
tcp        0      0 127.0.0.1:11334         0.0.0.0:*               LISTEN      28879/rspamd: main
......
Active UNIX domain sockets (only servers)
.....
unix  2      [ ACC ]     STREAM     LISTENING     3075355  3549/rmilter        /run/rmilter/rmilter.sock
.....

**Comment by fatalbanana** [comment]
Right- so it is /run/rmilter/... though /var/run is a symlink so I expect this is all fine.

You may have better luck asking about this on IRC- #rspamd on Freenode.net.

**Comment by patrakov** [comment]
So, you are on Ubuntu, and I guess you are using Postfix. They are a Debian derivative, and Debian likes to chroot Postfix. You have to either move the socket into the /var/spool/postfix directory, or use an inet (TCP) socket instead of UNIX-domain.

Sorry for the spam if you are not using Postfix.

**Comment by douardda** [comment]
I've just been hit by this problem and indeed (on jessie) it's a chroot "side-effect". IMHO this issue should be closed (and the problem documented eg. in the FAQ or the "installation" manual).
