### ISSUE TITLE
Check as soon RBL lists

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#298]
Hello
According spamhaus, this IP "138.99.217.44" is considered spam
Spamd quite a transition of this "138.99.217.44", did nothing
There in there a pattern to check for it at the RBL lists for this IP is described as spam and not a positive message ...
thank you
Mz
##

**Comment by fatalbanana** [comment]
Hey,

Not apparent to me what the question is here. To whitelist: you could use local_exclude_ip_map (simplest) or a self-operated RBL & is_whitelist setting- details: https://rspamd.com/doc/modules/rbl.html

**Comment by MisterM74** [comment]
Is it possible to have an example for me to understand the operation?

Thank you very much for your help

Mz

**Comment by fatalbanana** [comment]
rbl {
        local_exclude_ip_map = 'file://$CONFDIR/local.wl';

`echo 138.99.217.44 > /etc/rspamd/local.wl`

Something like that should work (although I've had problems with this in recent testing). Alternatively you could try setting up & querying a self-operated RWL or editing `private_ips` setting.
