### ISSUE TITLE
Multimap from hash map not working or bad syntax

### ISSUE THREAD

**Issue by shogoki69** [vstakhov/rspamd#299]
hi everyone, 

I have a problem with the type "from" in the module "multimap"

I did this in the file module.conf

multimap {
        dom-wl { type = "from"; map = "/etc/rspamd/from.map"; symbol = "FROM_WL"; }
}

My problem: I don't know what syntax to use in my from.map file for mail addresses or domain.
I tried this without success : 
test@test.com
@test.com
test.com

none of the tests works. 

If i test with ip, that applies the symbol correctly.

multimap {
        dom-wl { type = "ip"; map = "/etc/rspamd/ip.map"; symbol = "FROM_WL"; }
}

and in my ip.map i have this 
22.22.22.22

Thank you for the help and I apologized for my bad english.

**Comment by vstakhov** [comment]
I've tried user@domain and it worked pretty well. Just user or just domain are not (yet) supported by multimap.

**Comment by vstakhov** [comment]
I've also added @user and domain@ syntax for individual users and domains to multimap.

**Comment by shogoki69** [comment]
It's working great. Thank you very much for your work.
