### ISSUE TITLE
How to force bayes learning?

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#304]
I have a ham message with very high positive bayes score.
`rspamc learn_ham` refuses to learn the message as ham: "has been already learned as ham, ignore it". How to force rspamd to learn the message?

**Comment by vstakhov** [comment]
Is it still an issue?

**Comment by moisseev** [comment]
After update to 0.9.8 the problem seems to have gone away. I will monitor it over the next few days.
