### ISSUE TITLE
bayes broken after upgrade 0.9.6 -> 0.9.7

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#305]
Something went wrong with bayes after upgrade 0.9.6 -> 0.9.7.

For some messages it works as expected, but for others it wrongly gives maximal or minimal scores. For some messages learning fixes that but for others learning not affect the score (message not ignored).

Moreover sometimes learning brings to opposite result:
before learning `Symbol: BAYES_HAM (-6.10)[99.99%]`
after learning message as __ham__ `Symbol: BAYES_SPAM (6.11)[100.00%]`

I found in the log a lot of messages like this:
`2015-06-24 12:09:59 #39790(normal) bayes_classify <bef42a50360f81771bf0832d9de5c18b@manzinello.it> spam and ham classes are both overflowed`

**Comment by moisseev** [comment]
Downgrade to 0.9.6 has fixed the issues.

**Comment by vstakhov** [comment]
Can you send me the sample of message and your statfiles somehow? If you want, you can encrypt them with my gpg key: http://pgp.mit.edu/pks/lookup?op=get&search=0x07647B6790081437

I really need to debug and fix this problem a.s.a.p.

**Comment by moisseev** [comment]
Encrypted stat files:
http://my-files.ru/7pbi0z
http://my-files.ru/lqzyv1

Message samples:
http://my-files.ru/fbtx3p

I had downgraded to 0.9.6 as soon as the problem was discovered. So I am not sure about that message samples. I have no chance to install 0.9.7 right now but I'll can do it this evening or tomorrow morning (MSK) and filter out some interesting messages for you if you need it.

**Comment by vstakhov** [comment]
I've found the issue I think. I'll release 0.9.8 a.s.a.p. so you could test it.

**Comment by moisseev** [comment]
Fixed in 0.9.8, but now rspamd throws error message at startup:
`2015-06-26 09:59:26 #30536(main) rspamd_init_lua_filters: init of /usr/local/share/rspamd/lua/settings
.lua failed: /usr/local/share/rspamd/lua/settings.lua:415: attempt to index local 'set_section' (a nil
 value)
`

**Comment by fatalbanana** [comment]
That is fixed in master/rspamd-0.9 branches already. It is indeed an issue @ 0.9.8 but AFAICT this should not hurt operation.
