### ISSUE TITLE
Creating a custom FreeBSD port/package from master

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#315]
What way would you suggest for creating a custom FreeBSD port/package from master branch? As far as I know the port system isn't capable to fetch submodules. On the other hand `make dist` doesn't work on FreeBSD due to --transform is not supported by bsdtar and gnutar program name is gtar.

**Comment by vstakhov** [comment]
I've fixed `dist` on FreeBSD and OSx in 0.9 and master branches.

**Comment by moisseev** [comment]
Thanks, it works now. Suddenly I faced another problem: there is no easy way to use local distfile instead of fetching.

But I found the port system capable to fetch submodules actually. It works for me.
https://gist.github.com/moisseev/7ed949f9afc1f3bbfdae

Just wondering why master uses version is 0.9.4 for binaries names?

**Comment by vstakhov** [comment]
I've switched master to `1.0.0` now :)

**Comment by msimerson** [comment]
Can this issue be closed?
