### ISSUE TITLE
rspamd segfault  after reload

### ISSUE THREAD

**Issue by Fullmetal8ender** [vstakhov/rspamd#318]
Hi. I got rspamd[20774]: segfault at 400 ip 00007ff830441aea sp 00007ffd33609de8 error 4 in libc-2.19.so[7ff8303b9000+1bb000]
to reproduce
write to rspamd.conf.local
composite {
    name = "FORGED_UNDISC_MISSING_TO";
    expression = "R_UNDISC_RCPT and (FORGED_RECIPIENTS or MISSING_TO)";
}

metric {
    symbol { weight = 2.90; name = "FORGED_UNDISC_MISSING_TO"; description = "R_UNDISC_RCPT and FORGED_RECIPIENTS or MISSING_TO"; }
}

-start rspamd
-reload rspamd
-check email via rmilter
##

**Comment by fatalbanana** [comment]
Reload is fixed these days.
