### ISSUE TITLE
Cmake options

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#323]
Hello. How to set path for hiredis and libevent2?
Rspamd 0.9.8

hiredis: /usr/local/hiredis/
libevent2: /usr/local/libevent2/

**Comment by fatalbanana** [comment]
`pkg-config` will be used for both if possible.

**Comment by AlexeySa** [comment]
I did so:
sed -i 's/SET(RSPAMD_DEFAULT_INCLUDE_PATHS "/SET(RSPAMD_DEFAULT_INCLUDE_PATHS "/usr/local/hiredis;/usr/local/libevent2;/g' CMakeLists.txt
sed -i 's/SET(RSPAMD_DEFAULT_LIBRARY_PATHS "/SET(RSPAMD_DEFAULT_LIBRARY_PATHS "/usr/local/hiredis;/usr/local/libevent2;/g' CMakeLists.txt

**Comment by AlexeySa** [comment]
How use pkg-config?
