### ISSUE TITLE
Add header ability

### ISSUE THREAD

**Issue by Fullmetal8ender** [vstakhov/rspamd#326]
I think it is good idea to have ability to add some header via rspamd.
ex: i think this mail is from promotion and add header X-MType: promo
What do you think about it?
##

**Comment by fatalbanana** [comment]
Rspamd is not really in a position to add headers... perhaps you could add a spam report header and scan this for symbols of interest.

**Comment by Fullmetal8ender** [comment]
That`s what i`m doing now, but that`s not always suitable.
Maybe when rspamd would use milter protocol I will ask this question again.

**Comment by fatalbanana** [comment]
These days this is possible via `task:set_rmilter_reply`, see example script [here](https://rspamd.com/doc/migration.html).
