### ISSUE TITLE
2 Content-Type disable some checks

### ISSUE THREAD

**Issue by Fullmetal8ender** [vstakhov/rspamd#327]
If spam message has 2 Content-Type multipart/alternative headers rspamd will not find any url and core regexp module will find nothing (ex /Test123/P will not work)

mail http://pastebin.com/Dk7E9VWg
##

**Comment by vstakhov** [comment]
Rspamd uses `gmime` mime parser. Unfortunately, I can do nothing about this issue so far.

**Comment by Fullmetal8ender** [comment]
Is it possible to determine if message was parsed successfully or not?

**Comment by vstakhov** [comment]
This should work in the master with switching from gmime
