### ISSUE TITLE
Building on Gentoo fails with lack of CMakeLists.txt in contrib/snowball

### ISSUE THREAD

**Issue by djc** [vstakhov/rspamd#335]
Trying to build a simple ebuild for easy installation on Gentoo, I get this failure:

    CMake Error at CMakeLists.txt:1069 (ADD_SUBDIRECTORY):
      The source directory

        /var/tmp/portage/mail-filter/rspamd-0.9.9/work/rspamd-0.9.9/contrib/snowball

      does not contain a CMakeLists.txt file.

Any suggestions on how to fix this? I'm building rspamd-0.9.9.

**Comment by fatalbanana** [comment]
Using the [tarball](https://rspamd.com/downloads/rspamd-0.9.9.tar.xz) should work. For `git` you will need to download submodules as well, eg `git clone --recursive`.

**Comment by djc** [comment]
I was using a GitHub release so far: https://github.com/vstakhov/rspamd/archive/0.9.9.tar.gz. Those don't work?

**Comment by fatalbanana** [comment]
Nope I guess not. :) Rather get it from [rspamd.com](https://rspamd.com/downloads.html).

**Comment by djc** [comment]
Okay, that seems to work.
