### ISSUE TITLE
idn urls raise the phishing flag

### ISSUE THREAD

**Issue by vixns** [vstakhov/rspamd#337]
Hi, 

Thank you for you hard and brillant work on this needed piece of software !

Rspamd doesn't like when the href is not the same as it's label, great, but not with idn domain names.

This is a valid html link, but phishing for rspamd 

```
<a href=3D"http://www.xn--couffin-priv-meb.com/" =
rel=3D"noreferrer" target=3D"_blank">www.couffin-priv=C3=A9.com</a>
```
##

**Comment by vstakhov** [comment]
Rspamd uses rdns to convert names to IDN format. Hence, it's quite hard to detect that the url is punycoded inside href but not encoded in the displayed URL.

**Comment by fatalbanana** [comment]
This appears to be resolved.
