### ISSUE TITLE
dkim check allowed even if rsa verify failed

### ISSUE THREAD

**Issue by wummel** [vstakhov/rspamd#338]
Hi,

my rspamd debug log includes "rspamd_dkim_check: rsa verify failed", but rspamc prints out "Symbol: R_DKIM_ALLOW (-1.10)[sourceforge.net]". I expected it to be R_DKIM_REJECT, and the same message with Spamassassin triggers the T_DKIM_INVALID rule.
##

**Comment by vstakhov** [comment]
Maybe there are some valid signatures in that message?
