### ISSUE TITLE
Bayesian classifier should also look at headers

### ISSUE THREAD

**Issue by patrakov** [vstakhov/rspamd#340]
I had a chance to directly compare dspam and rspamd, by forwarding all my email from a production server that runs dspam to a test server that runs rspamd. This is a comparison of "pure bayes" (dspam) and "bayes plus extra checks" (rspamd). One would expect that, after a period of learning, "bayes plus extra checks" should win, but the result, for me, is not so conclusive: there are errors from both, of different kinds.

One particular pattern that I consider issue-worthy is that dspam, somehow (see below for a guess), correctly identifies all "one link plus an image" spams for me. Sure, rspamd has a special rule for such spams, and in recent versions it works. However, the bayesian classifier in rspamd refuses to even learn on such messages, on the basis that there are too few words.

I think that this refusal is wrong. The real problem, if I understand correctly, is that the set of words to learn on is taken from the message body in rspamd and from the whole message in dspam. I.e. there is something in the headers, mime boundaries, or something like that, that is sufficient to identify such spam with pure bayes, and rspamd throws this information away. It could be improved to take headers into account for bayesian filtering.

One guess would be that these messages:

 * are addressed (in the To: header) to a limited set of recipients not belonging to my domain and not matching any mailing lists that I am subscribed to
 * claim to come from a fixed non-current version of Microsoft Windows Live Mail
 * have obvious spammy subjects

**Comment by vstakhov** [comment]
That's a long postponed idea. rspamd really needs this feature and it seems it's quite straightforward to implement. I would really appreciate if you'd be able to do testing and collect some statistics about false positives and false negatives numbers before the changes and after that. Please tell me if you'd be able to make such an evaluation on the next week.

**Comment by patrakov** [comment]
You are welcome to contact me privately (via email or XMPP, same address) about the evaluation.
