### ISSUE TITLE
rspamc - mail to stdout feature

### ISSUE THREAD

**Issue by 0nelight** [vstakhov/rspamd#341]
would like to have a feature in rspamc like in spamc of spamassassin:
if you call spamc with -e "MDA" f.e. in a fetchmail config:
*mda "/usr/bin/rspamc -u %T -e /usr/lib/dovecot/deliver -d %T"*
you don't need to install an MTA (Postfix...) and you can pipe an email from fetchmail-->rspamc-->dovecot without additonal software.
Would be nice if rspamc is also capable of doing this. TY

**Comment by vstakhov** [comment]
Well, I've added `--exec` option that executes the specified argument parsing options and searching the `PATH`. Also, I've added `--mime` option to process message and append some headers to it. Here is invocation example:

    rspamc --mime --exec "/usr/lib/dovecot/deliver -d user@example.com" message.eml

And here are headers inserted by rspamc:

    X-Spam-Scanner: rspamc 1.0.0
    X-Spam: yes
    X-Spam-Action: reject

This can be changed or adopted more in the future.

**Comment by johnl** [comment]
That's handy, but having rspamc be able to output to stdout is really quite useful. I'm currently using maildrop's "xfilter" command to pass mail through crm before then applying other mail rules - I cant do this with rspamc.

I even tried "rspamc --exec cat" but it seems to ditch the output of the command it execs.

**Comment by vstakhov** [comment]
That should work in conjunction with `--mime` flag.

**Comment by johnl** [comment]
The --mime flag doesn't seem to change the behaviour. Also, the help for --mime looks incorrect:

```
  -e, --exec             Execute the specified command and pass output to it
  --mime                 Execute the specified command and pass output to it
```

**Comment by vstakhov** [comment]
Could you please provide the full command line that you are using to run rspamc?

**Comment by johnl** [comment]
crap, I misread the original ticket - my request is slightly different, I will open a new ticket, sorry!
