### ISSUE TITLE
Regexp in rspamd 0.9.9

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#342]
My lua code not working in rspamd 0.9.9.
```
local all_headers = task:get_raw_headers()
local dcc_header = all_headers:match("X-DCC-.*-Metrics:(.+)")
```

it's ok for rspamd 0.8

Please help.

**Comment by vstakhov** [comment]
1. Your code is terribly inefficient, please avoid it by any costs
2. The documentation of this function is outdated: now rspamd returns `rspamd_text` in this function

You can convert `rspamd_text` to string using `tostring(text)` lua function. However, I would **NOT** recommend to do it, as it would copy the whole content of text to lua. I'd suggest to either extract the exact headers or to use `rspamd_regexp` to match the whole headers chunk (but it is much slower than getting exact headers).

**Comment by AlexeySa** [comment]
Thanks. tostring() it works.

DCC-filter adds header "X-DCC-SRVNAME-Metrics".
"SRVNAME" - random set of characters.

I have not found a good way to get the value of this header :(

**Comment by vstakhov** [comment]
But now you have chosen the **less** efficient approach of the possible ones.
