### ISSUE TITLE
Per user metrics

### ISSUE THREAD

**Issue by Menta2L** [vstakhov/rspamd#348]
In the old versions like 0.6  there was a option to define metrics per domain or per user :

user_settings = file:///path/to/file.json
domain_settings = http://test.com/data.json

Unfortunately i was not  able to find a way to make this working in the current version. Is that functionality is deprecated  in the last version ?

**Comment by Menta2L** [comment]
I found the answer for myself here https://rspamd.com/doc/configuration/settings.html

**Comment by hxily** [comment]
can you give me a example?

**Comment by fatalbanana** [comment]
@hxily - there's example config at the link cited above - let us know if something is unclear.

**Comment by hxily** [comment]
@fatalbanana thank you,i  finish off
