### ISSUE TITLE
Per user whitelist

### ISSUE THREAD

**Issue by hxily** [vstakhov/rspamd#351]
user  a@abc.com have a whitelist /var/vmail/abc.com/a/whitelist
user  b@abc.com have a whitelist /var/vmail/abc.com/b/whitelist
how about setting use /var/vmail/abc.com/a/whitelist when rcpt to a@abc.com?

**Comment by fatalbanana** [comment]
Guessing /var/vmail/abc.com/a/whitelist might contain just a list of sender addresses to whitelist- it would not be viable to use this as-is with current facilities - you'd want to mangle these into something understood by [settings](https://rspamd.com/doc/configuration/settings.html) module.

```
  settings {
	whitelist {
		priority = high;
		from = "friend@example.com";
		from = "friend2@example.net";
		rcpt = "a@abc.com";
		want_spam = yes;
	}
  }
```

**Comment by Menta2L** [comment]
Here is what i done. 
First i create a /etc/rspamd/modules.d/settings.conf with following content 
```
settings {
}
```
Reason to do that is because if settings module cant load his own configuration module is not "startup" at all
After that i created a user_setting.conf file inside  /etc/rspamd/
```
settings {
    some_users {
        priority = high;
        rcpt = "/^(postmaster|abuse|invoices|info|register|orders|support)/";
        apply "default" {
            actions {
                reject = 101.0
                greylist = 11.0
                add_header = 6
            }
        }
    }
}
```
and at the end I include that file inside rspamd.conf 
```
.include "$CONFDIR/user_settings.conf"
```

**Comment by nahuelange** [comment]
Hi,
Does it exist a way to have user-based dynamic whitelist ?

**Comment by fatalbanana** [comment]
@nahuelange - yes, you can abuse `settings` module for this purpose - see [here](https://groups.google.com/forum/message/raw?msg=rspamd/8RqmIW9b5OM/mKe5L3KwTMYJ).

**Comment by nahuelange** [comment]
But this is not "dynamic", like with the spam plugin of dovecot to learn spam or ham.

**Comment by vstakhov** [comment]
Settings stored in a map are dynamic and are thus reloaded by rspamd automatically

**Comment by xpunkt** [comment]
Menta2L what you write makes seqfaults here in 1.0.11

**Comment by fatalbanana** [comment]
@xpunkt - I don't manage to replicate that on Ubuntu 14.04 x64. The first of those steps should not be necessary FWIW though I don't manage to break it by trying.
