### ISSUE TITLE
rspamc should support writing the email back out to stdout with added headers

### ISSUE THREAD

**Issue by johnl** [vstakhov/rspamd#357]
the spamassassin spamc command's default operation is to output the original email but with added headers, such as:

```
X-Spam-Flag: YES
X-Spam-Level: *************
X-Spam-Status: Yes, score=13.9 required=4.5 tests=BAYES_50,FUZZY_CLICK_HERE,
	HTML_FONT_LOW_CONTRAST,HTML_MESSAGE,INVALID_DATE,RCVD_IN_BRBL_LASTEXT,
	RCVD_IN_SBL_CSS,RDNS_NONE,UNPARSEABLE_RELAY,URIBL_BLACK,URIBL_DBL_SPAM,
	URIBL_JP_SURBL autolearn=no autolearn_force=no version=3.4.0
```

which is perfect for integration with lots of mail filtering systems, such as maildrop's "xfilter" command: http://www.courier-mta.org/maildropfilter.html#xfilter

**Comment by vstakhov** [comment]
So does rspamd with `--mime` option. I have the following command specified as pipe:

    command = /usr/bin/rspamc --mime --ucl --exec "/usr/lib/dovecot/dovecot-lda -d cebka"

Then I have the following headers in messages scanned:

```
X-Spam-Scanner: rspamc 1.0.0
X-Spam: yes
X-Spam-Action: reject
X-Spam-Score: 19.44 / 16.00
X-Spam-Result: ZGV...<base64_encoded_ucl>==
```

**Comment by johnl** [comment]
That sounds almost perfect, but I want it back out to stdout rather than being passed onto another command.

That way I can use it with maildrop's xfilter, for example.

I use spamc like this currently: postfix delivers mail to maildrop, which passes it through spamc using it's xfilter feature, and then have a further maildrop rule that checks the headers for the spam report and deliver it to a junk folder if necessary.

**Comment by vstakhov** [comment]
It's done now. The documentation has been accordingly fixes, thank you!

**Comment by johnl** [comment]
No, thank you! I'll test this out once the daily apt package is rebuilt. Thanks again!

**Comment by vstakhov** [comment]
Packages rebuild has completed.

**Comment by johnl** [comment]
Ok, this is working, but rspamc seems to reformat the original email in a way that spamassassin is careful not to.

See https://gist.github.com/johnl/dcf50ec76f63612fe019 for a diff from my original message to the output of rspamc --mime

* The received headers are reformatted
* the full name in the from header loses it's quotes
* the to header loses it's <> characters
* the X-CRM114 headers are changed in some way (I'm presuming the EOL code changes)
* the Content headers change position
* whitespace change at end of email

I'm not quite sure to what extent this matters, but I'm not sure why it's necessary either - probably best avoided.

**Comment by FelixSchwarz** [comment]
johnl: Not sure what the project's ticket policy says about this but I guess it might be good to close this bug report and open a new one about not modifying the existing email but only adding headers on top?
