### ISSUE TITLE
FreeBSD port mail/rspamd doesn't install Lua rules in %%ETCDIR%%/lua

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#375]
FreeBSD port mail/rspamd-1.0.0 doesn't install Lua rules in %%ETCDIR%%/lua at all. Is it expected behavior?

**Comment by vstakhov** [comment]
Yes. All rules are now in `share/rspamd/rules`. I'm trying to make all configs and rules as a part of rspamd distribution encouraging users to use either `rspamd.local.conf`, `rspamd.local.lua` or `rspamd.override.conf`. See lines

~~~
 # User local settings
.include(try=true) "$CONFDIR/rspamd.conf.local"
.include(try=true,priority=10) "$CONFDIR/rspamd.conf.local.override"
~~~

**Comment by moisseev** [comment]
I guess default rspamd.local.lua location has been changed from `$CONFDIR/lua/rspamd.local.lua` to `$CONFDIR/rspamd.local.lua`. Would you mention it in the migration page?

BTW Looks like `rspamd.local.lua` undocumented at all.

**Comment by vstakhov** [comment]
You are right.

**Comment by vstakhov** [comment]
In 1.0.1, I also check for the legacy location if the recommended one has not been found.
