### ISSUE TITLE
Exim Received header bug (once received)

### ISSUE THREAD

**Issue by frederikbosch** [vstakhov/rspamd#376]
The problem is that the `Received` header should not exist or must be skipped by rspamd. In case of exim we do have our local received header. And we should parse it correctly.
##

**Comment by fatalbanana** [comment]
Is this still a valid issue?- And if so could you elaborate please?

**Comment by frederikbosch** [comment]
@fatalbanana I recall a conversation I had on IRC. @vstakhov asked me to open an issue for this. He told me that there were problems with Exim headers. The problem was that most of the e-mails were getting the tag ONCE_RECEIVED, even valid ones. A while ago I updated to 1.3.x and I think messages are less frequently tagged, but for instance all gmail messages are still tagged as ONCE_RECEIVED. But maybe that is valid.

**Comment by fatalbanana** [comment]
Hmmm, Exim Received header parsing looks good to me (this has been reworked in 1.3). Exim sends messages to content scanners in mbox format which is now dealt with- I don't expect problems. Messages I'm seeing from GMail have multiple Received headers.
