### ISSUE TITLE
2 errors, unexplained

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#377]
Hello

In recent days I have this as rspamd error in the logs.

#11770(normal) <13d72b>; task; lua_metric_symbol_callback: call to ((NULL)) failed: /usr/share/rspamd/lua/rbl.lua:77: attempt to concatenate local 'rbl' (a nil value); trace: [1]:{/usr/share/rspamd/lua/rbl.lua:77 - ip_to_rbl [Lua]}; [2]:{/usr/share/rspamd/lua/rbl.lua:287 - <unknown> [Lua]}; [3]:{/usr/share/rspamd/lua/rbl.lua:291 - <unknown> [Lua]}; [4]:{/usr/share/rspamd/lua/rbl.lua:322 - <unknown> [Lua]};

I do not know to enter the web page of my logs

#11771(normal) <6ca341>; task; rspamd_worker_error_handler: abnormally closing connection from: 127.0.0.1, error: HTTP parser error: invalid HTTP method

Thank you for your support

Mz

**Comment by fatalbanana** [comment]
Hmm, it looks like one of your RBLs doesn't have the `rbl` field defined - can you share your config?

**Comment by MisterM74** [comment]
surbl {
    .include(try=true,priority=1) "${DBDIR}/dynamic/surbl.conf"
    whitelist = "file://$CONFDIR/surbl-whitelist.inc";
    exceptions = "file://$CONFDIR/2tld.inc";

    rule {
        suffix = "multi.surbl.org";
        symbol = "SURBL_MULTI";
        bits {
            JP_SURBL_MULTI = 64;
            AB_SURBL_MULTI = 32;
            MW_SURBL_MULTI = 16;
            PH_SURBL_MULTI = 8;
            WS_SURBL_MULTI = 4;
            SC_SURBL_MULTI = 2;
        }
    }
    rule {
        suffix = "multi.uribl.com";
        symbol = "URIBL_MULTI";
        bits {
            URIBL_BLACK = 2;
            URIBL_GREY = 4;
            URIBL_RED = 8;
        }
    }
    rule {
        suffix = "uribl.rambler.ru";
        symbol = "RAMBLER_URIBL";
    }
    rule {
        suffix = "dbl.spamhaus.org";
        symbol = "DBL";
        options = "noip";
        ips = {
            # spam domain
            DBL_SPAM = "127.0.1.2";
            # phish domain
            DBL_PHISH = "127.0.1.4";
            # malware domain
            DBL_MALWARE = "127.0.1.5";
            # botnet C&C domain
            DBL_BOTNET = "127.0.1.6";
            # abused legit spam
            DBL_ABUSE = "127.0.1.102";
            # abused spammed redirector domain
            DBL_ABUSE_REDIR = "127.0.1.103";
            # abused legit phish
            DBL_ABUSE_PHISH = "127.0.1.104";
            # abused legit malware
            DBL_ABUSE_MALWARE = "127.0.1.105";
            # abused legit botnet C&C
            DBL_ABUSE_BOTNET = "127.0.1.106";
            # error - IP queries prohibited!
            DBL_PROHIBIT = "127.0.1.255";
        }
    }
    rule {
        suffix = "uribl.spameatingmonkey.net";
        symbol = "SEM_URIBL_UNKNOWN";
        bits {
            SEM_URIBL = 2;
        }
        options = "noip";
    }
    rule {
        suffix = "fresh15.spameatingmonkey.net";
        symbol = "SEM_URIBL_FRESH15_UNKNOWN";
        bits {
            SEM_URIBL_FRESH15 = 2;
        }
        options = "noip";
    }
    rule {
        suffix = "fresh10.spameatingmonkey.net";
        symbol = "SEM_URIBL_FRESH10_UNKNOWN";
        bits {
            SEM_URIBL_FRESH10 = 2;
        }
        options = "noip";
    }
}

rbl {

    default_from = true;
    default_received = false;
    default_exclude_users = true;

    private_ips = "127.0.0.0/8 10.0.0.0/8 192.168.0.0/16 169.254.0.0/16 172.16.0.0/12 100.64.0.0/10 fc00::/7 fe80::/10 fec0::/10 ::1";

    rbls {

        spamhaus {
            symbol = "RBL_SPAMHAUS";
            rbl = "zen.spamhaus.org";
            ipv6 = true;
            unknown = true;
            returncodes {
                RBL_SPAMHAUS_SBL = "127.0.0.2";
                RBL_SPAMHAUS_ZEN = "127.0.0.3";
                RBL_SPAMHAUS_XBL = "127.0.0.4";
                RBL_SPAMHAUS_XBL = "127.0.0.5";
                RBL_SPAMHAUS_XBL = "127.0.0.6";
                RBL_SPAMHAUS_XBL = "127.0.0.7";
                RBL_SPAMHAUS_PBL = "127.0.0.10";
                RBL_SPAMHAUS_PBL = "127.0.0.11";
            }
        }

        spamhaus_xbl {
            symbol = "RECEIVED_SPAMHAUS_XBL";
            rbl = "xbl.spamhaus.org";
            ipv6 = true;
            received = true;
            from = false;
            ignore_whitelists = true;
        }

        spamhaus_swl {
            symbol = "RWL_SPAMHAUS_WL";
            rbl = "swl.spamhaus.org";
            ipv6 = true;
            is_whitelist = true;
            unknown = true;
            whitelist_exception = "RWL_SPAMHAUS_WL";
            returncodes {
                RWL_SPAMHAUS_WL_IND = "127.0.2.2";
                RWL_SPAMHAUS_WL_TRANS = "127.0.2.3";
                RWL_SPAMHAUS_WL_IND_EXP = "127.0.2.102";
                RWL_SPAMHAUS_WL_TRANS_EXP = "127.0.2.103";
            }
        }

        mailspike_bl {
            symbol = "RBL_MAILSPIKE";
            unknown = true;
            rbl = "bl.mailspike.net";
            returncodes {
                RBL_MAILSPIKE_ZOMBIE = "127.0.0.2";
                RBL_MAILSPIKE_WORST = "127.0.0.10";
                RBL_MAILSPIKE_VERYBAD = "127.0.0.11";
                RBL_MAILSPIKE_BAD = "127.0.0.12";
            }
        }

        mailspike_wl {
            symbol = "RWL_MAILSPIKE";
            rbl = "wl.mailspike.net";
            is_whitelist = true;
            unknown = true;
            whitelist_exception = "RWL_MAILSPIKE";
            whitelist_exception = "RWL_MAILSPIKE_GOOD";
            whitelist_exception = "RWL_MAILSPIKE_POSSIBLE";
            returncodes {
                RWL_MAILSPIKE_POSSIBLE = "127.0.0.17";
                RWL_MAILSPIKE_GOOD = "127.0.0.18";
                RWL_MAILSPIKE_VERYGOOD = "127.0.0.19";
                RWL_MAILSPIKE_EXCELLENT = "127.0.0.20";
            }
        }

        senderscore {
            symbol = "RBL_SENDERSCORE";
            rbl = "bl.score.senderscore.com";
        }

        abusech {
            symbol = "RBL_ABUSECH";
            rbl = "spam.abuse.ch";
        }

        uceprotect1 {
            symbol = "RBL_UCEPROTECT_LEVEL1";
            rbl = "dnsbl-1.uceprotect.net";
        }

	uceprotect2 {
            symbol = "RBL_UCEPROTECT_LEVEL2";
            rbl = "dnsbl-2.uceprotect.net";
        }

	uceprotect3 {
            symbol = "RBL_UCEPROTECT_LEVEL3";
            rbl = "dnsbl-3.uceprotect.net";
        }

	workgremlin {
           symbol = "RBL_WORK_GREMLIN";
           rbl = "work.drbl.gremlin.ru";
        }

        sorbs {
            symbol = "RBL_SORBS";
            rbl = "dnsbl.sorbs.net";
            unknown = true;
            returncodes {
                # http:// www.sorbs.net/general/using.shtml
                RBL_SORBS_HTTP = "127.0.0.2";
                RBL_SORBS_SOCKS = "127.0.0.3";
                RBL_SORBS_MISC = "127.0.0.4";
                RBL_SORBS_SMTP = "127.0.0.5";
                RBL_SORBS_RECENT = "127.0.0.6";
                RBL_SORBS_WEB = "127.0.0.7";
                RBL_SORBS_DUL = "127.0.0.10";
                RBL_SORBS_BLOCK = "127.0.0.8";
                RBL_SORBS_ZOMBIE = "127.0.0.9";
            }
        }

        sem {
            symbol = "RBL_SEM";
            rbl = "bl.spameatingmonkey.net";
        }

        semIPv6 {
            symbol = "RBL_SEM_IPV6";
            rbl = "bl.ipv6.spameatingmonkey.net";
            ipv4 = false;
            ipv6 = true;
        }

        dnswl {
            symbol = "RCVD_IN_DNSWL";
            rbl = "list.dnswl.org";
            ipv6 = true;
            is_whitelist = true;
            unknown = true;
            whitelist_exception = "RCVD_IN_DNSWL";
            whitelist_exception = "RCVD_IN_DNSWL_NONE";
            whitelist_exception = "RCVD_IN_DNSWL_LOW";
            whitelist_exception = "DNSWL_BLOCKED";
            returncodes {
                RCVD_IN_DNSWL_NONE = "127.0.%d+.0";
                RCVD_IN_DNSWL_LOW = "127.0.%d+.1";
                RCVD_IN_DNSWL_MED = "127.0.%d+.2";
                RCVD_IN_DNSWL_HI = "127.0.%d+.3";
                DNSWL_BLOCKED = "127.0.0.255";
            }
        }

        rambleremails {
            symbol = RAMBLER_EMAILBL;
            rbl = "email-bl.rambler.ru";
            from = false;
            emails = true;
            exclude_users = false;
            exclude_private_ips = false;
            exclude_local = false;
            ignore_whitelists = true;
        }

	spam-rbl {
     	symbol = "RBL_SPAM-RBL";
     	rbl = "all.spam-rbl.fr";
     	unknown = true;
     	returncodes {
        	RBL_SPAM-RBL_SPAM = "127.0.0.2";
        	RBL_SPAM-RBL_DSL = "127.0.0.3";
        	RBL_SPAM-RBL_BOGON = "127.0.0.4";
        	RBL_SPAM-RBL_LOCAL = "127.0.0.5";
        	RBL_SPAM-RBL_MISCONF = "127.0.0.6";
     	   }
  	}

	dnsbl-chile {
        symbol = "RBL_DNSBL-CHILE";
        rbl = "dnsblchile.org";
        unknown = true;
        returncodes {
                RBL_DNSBL-CHILE_NACIONAL = "127.0.0.3";
                RBL_DNSBL-CHILE_EXTRA = "127.0.0.4";
                RBL_DNSBL-CHILE_ESTAFA = "127.0.0.5";
                RBL_DNSBL-CHILE_NACIONAL_NO_CONFOR_RFC = "127.0.0.10";
		RBL_DNSBL-CHILE_SNOWSHOE = "127.0.0.12";
		RBL_DNSBL-CHILE_NACIONAL_NO_CO_CON_RFC = "127.0.0.13";
		RBL_DNSBL-CHILE_EXTRA_NO_CO_CON_RFC = "127.0.0.11";
           }
        }

	junkemailfilter {
           symbol = "RBL_JUNKEMAILFILTER";
           rbl = "hostkarma.junkemailfilter.com";
           unknown = true;
           returncodes {
                RBL_HOSTKARMA_JUNKEMAILFILTER = "127.0.0.2";
		RBL_HOSTKARMA_JUNKEMAILFILTER_B = "127.0.0.3";
           }
        }

	barracudacentral {
           symbol = "RBL_BARRACUDACENTRAL";
           rbl = "b.barracudacentral.org";
	   unknown = true;
           returncodes {
                RBL_B_BARRACUDACENTRAL = "127.0.0.2";
	   } 
        }

	barracudacentral {
           symbol = "RBL_BARRACUDACENTRAL";
           rbl = "bb.barracudacentral.org";
           unknown = true;
           returncodes {
                RBL_BB_BARRACUDACENTRAL = "127.0.0.2";
           }
        }

        nosolicitado {
           symbol = "RBL_NOSOLICITADO";
           rbl = "bl.nosolicitado.org";
	   unknown = true;
           returncodes {
                RBL_BL_NOSOLICITADO = "127.0.0.2";
	   }
        }

        truncate {
           symbol = "RBL_TRUNCATEGBUDB";
           rbl = "truncate.gbudb.net";
	   unknown = true;
           returncodes {
                RBL_BL_TRUNCATEGBUDB = "127.0.0.2";
	   }
        }

        spamcop {
           symbol = "RBL_SPAMCOP";
           rbl = "bl.spamcop.net";
	   unknown = true;
           returncodes {
                RBL_BL_SPAMCOP = "127.0.0.2";
	   }
        }

        abuseat {
           symbol = "RBL_ABUSEAT";
           rbl = "cbl.abuseat.org";
	   unknown = true;
           returncodes {
                RBL_CBL_ABUSEAT = "127.0.0.2";
	   }
        }

        psbl {
           symbol = "RBL_PSBL";
           rbl = "psbl.surriel.com";
	   unknown = true;
           returncodes {
                RBL_PSBL_SURRIEL = "127.0.0.2";
	   }
        }

    }
}

**Comment by fatalbanana** [comment]
Only potential problem I see there is that `barracudacentral` is listed twice - does giving the second entry a unique name solve it by any chance?

**Comment by MisterM74** [comment]
This is solved and my worries viewing logs via the net?
Thank you
Mz

**Comment by fatalbanana** [comment]
Ok cool.

In case of the second issue- I don't have a good handle on it- you are clicking the 'History' tab in the web interface?- & when you do nothing happens(?) and logs produce that error?- Working for me here fwiw.

**Comment by MisterM74** [comment]
I do not know access, as I have this error message

Unauthorized

I do not even know enter the page history

Before the last update, I knew enter
Mz

**Comment by vstakhov** [comment]
This seems to be my fault. Investigating...

**Comment by MisterM74** [comment]
hello

I will not be "war" with you, I'm just trying to understand what is happening and why I can not get connected.

Thank you for your support

Mz

**Comment by MisterM74** [comment]
I have other errors, can you help me

2015-10-03 08:27:52 #16549(controller) <z9ijff>; controller; rspamd_controller_password_sane: your normal password is not encrypted, we strongly recommend to replace it with the encrypted one
2015-10-03 08:27:52 #16549(controller) <z9ijff>; controller; rspamd_controller_password_sane: enable password is not set, so you should filter controller availability by using of firewall or `secure_ip` option

also this

2015-10-03 08:29:33 #16551(normal) <a6156a>; task; rspamd_worker_error_handler: abnormally closing connection from: 127.0.0.1, error: HTTP parser error: invalid HTTP method

Thank you

Mz

**Comment by fatalbanana** [comment]
`2015-10-03 08:27:52 #16549(controller) ; controller; rspamd_controller_password_sane: your normal password is not encrypted, we strongly recommend to replace it with the encrypted one`

You can generate it with `rspamadm pw`

` 2015-10-03 08:27:52 #16549(controller) ; controller; rspamd_controller_password_sane: enable password is not set, so you should filter controller availability by using of firewall or secure_ip option`

`secure_ip` allows certain hosts to run any command without a password.

If `enable_password` is specified it is used for data-changing commands, if not `password` is used for these too.

`2015-10-03 08:29:33 #16551(normal) ; task; rspamd_worker_error_handler: abnormally closing connection from: 127.0.0.1, error: HTTP parser error: invalid HTTP method`

Don't know- context might be helpful.

**Comment by MisterM74** [comment]
I also like this error for 5 "Symbol"

has its score defined but there is no corresponding rule registered

SEM_URIBL_UNKNOWN
SEM_URIBL_FRESH15_UNKNOWN
RBL_WORK_DRBL_GREMLIN
DBL
RBL_SPAMHAUS_CSS

Sincerely sorry to add to this topic, but I see in my logs

Mz

**Comment by fatalbanana** [comment]
`RBL_WORK_DRBL_GREMLIN`
`RBL_SPAMHAUS_CSS`

You haven't these in `rbl { }` do you?- But they are presumably configured in `metrics.conf` or similar.

`SEM_URIBL_UNKNOWN`
`SEM_URIBL_FRESH15_UNKNOWN`
`DBL`

I suppose this is a bug.

**Comment by MisterM74** [comment]
2 CSS rules and GREMLIN is settled, it's good, my mistake

The other mistake I add, not understood, understood?


Mz
