### ISSUE TITLE
Web-GUI authentication failed after upgrade 1.0.0 -> 1.0.1

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#378]
`2015-09-23 11:11:48 #53258(controller) <587cd3>; csession; rspamd_controller_check_password: absent password has been specified`

/usr/local/etc/rspamd/worker-controller.inc.local
```
# Included from top-level .conf file

type = "controller";
count = 1;
password = "XXXXXXXXXXXXXXXXX";
secure_ip = "127.0.0.1";
secure_ip = "::1";
static_dir = "${WWWDIR}";
```

**Comment by vstakhov** [comment]
Thanks for the report, I'm working on fix.

**Comment by vstakhov** [comment]
The issue exists only if you have an unencrypted password in your config.

**Comment by vstakhov** [comment]
No, that's webui issue I'm afraid.

**Comment by moisseev** [comment]
It works in 1.0.2. Thanks!
