### ISSUE TITLE
Webui: piechart broken in 1.0.2

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#380]
Take a look at the "Clean" slice:
![2015-09-23 21_08_19-rspamd web interface - pale moon](https://cloud.githubusercontent.com/assets/2275981/10053982/9aa5af8a-6237-11e5-98f0-4c5831dc0b08.png)

**Comment by vstakhov** [comment]
Damn, I've not noticed that. Fixed in git...

**Comment by moisseev** [comment]
It works now. Thanks!
