### ISSUE TITLE
Exclude messages with `qid: <undef>` from statistics

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#382]
I'd like to count in rspamd statistics messages scanned through rmilter only, but exclude others (scanned with rspamc or webui). Is it possible? May be by excluding messages with `qid: <undef>` from statistics?

**Comment by vstakhov** [comment]
Yes, that sounds reasonable, as neither webui nor rspamc set this header when scanning.

**Comment by moisseev** [comment]
Would you consider adding a configuration directive for that?

**Comment by vstakhov** [comment]
What do you mean?

**Comment by moisseev** [comment]
Optionally exclude from internal rspamd statistics scan results for messages with qid: <undef>.

**Comment by vstakhov** [comment]
I dislike this idea as is. What I think could be done is to create a special task flag to exclude it from stats and set it from lua, e.g.

~~~lua
rspamd_config.register_post_filter(function(task)
  if task:get_queue_id() then task:set_flag('no_stat') end
end)
~~~

What do you think about it?

**Comment by moisseev** [comment]
It would be great, looks very flexible.

**Comment by vstakhov** [comment]
Should be done.

**Comment by moisseev** [comment]
I'v added code you mentioned before to `rspamd.local.lua`:
```lua
rspamd_config:register_post_filter(function(task)
  if task:get_queue_id() then task:set_flag('no_stat') end
end)
```
Is that enough? It doesn't work.

**Comment by fatalbanana** [comment]
Shouldn't it be `if not task:get_queue_id()` ? :)

**Comment by moisseev** [comment]
Of course. It works now. Thank you all.

**Comment by moisseev** [comment]
Would you add similar task flag to exclude messages from history as well?

**Comment by mnik247** [comment]
@moisseev 
How can I set flags (no_stat, no_log,...)?
Can you write more examples?

**Comment by moisseev** [comment]
to @mnik247    

rspamd.local.lua:
```lua
rspamd_config:register_post_filter(function(task)
  if not task:get_queue_id() then task:set_flag('no_stat') end
end)
```
It works. I haven't tried anything else yet.

**Comment by mnik247** [comment]
@moisseev 
It will work global for all messages?
How can skip specific messages?

**Comment by moisseev** [comment]
Conditional operator sets flag for messages with undefined queue id. You can change condition as you need.

**Comment by moisseev** [comment]
@mnik247, thanks for the hint!
Rspamd doesn't add messages to the history if `no_log` flag is set.
