### ISSUE TITLE
[feature] teach rspamc to select classifier from command line

### ISSUE THREAD

**Issue by andrejzverev** [vstakhov/rspamd#384]
It would be useful to teach rspamc client to understand which classifier (by id/name?) user want to train with spam/ham.
- Problem: classifier {} don't have any unique name to use, can be added some name key. By default name can contain value: default, this can help be backward compatibly with older work flow when use only say learn_ham/learn_spam. If user will chose -c name learn_(ham|spam) in this case we can look  classifier by name and train their statfiles.

**Comment by vstakhov** [comment]
Done.
