### ISSUE TITLE
Statistics Settings by domain

### ISSUE THREAD

**Issue by sandromello** [vstakhov/rspamd#388]
I've read that it's possible to configure [statistics settings by users](https://www.rspamd.com/doc/configuration/statistic.html).

It's possible to achieve this configuration by domain?

**Comment by vstakhov** [comment]
That's not currently supported, but it won't be hard to add.

**Comment by sandromello** [comment]
I think it's a useful feature for mail service providers. Keep up with the good work!

**Comment by vstakhov** [comment]
Well, I've added a more flexible approach - it is now possible to specify custom lua function to extract user or language data. Here is an example that does what you are expecting:

~~~
    classifier {
        tokenizer {
            name = "osb";
        }
        backend = "sqlite3";
        per_user = <<EOD
return function(task)
    local rcpt = task:get_recipients(1)

    if rcpt then
        one_rcpt = rcpt[1]
        if one_rcpt['domain'] then
            return one_rcpt['domain']
        end
    end

    return nil
end
EOD
        statfile {
            path = "/tmp/spam.sqlite";
            symbol = "BAYES_SPAM";
        }
        statfile {
            path = "/tmp/ham.sqlite";
            symbol = "BAYES_HAM";
            languages_enabled = true;
        }
        cache {
            path = "/tmp/cache.sqlite";
            name = "sqlite3";
        }
    }
~~~

**Comment by sandromello** [comment]
Awesome! I'll test this functionality soon as possible. Thanks Vstakhov !
