### ISSUE TITLE
rspamd exits on signal 11

### ISSUE THREAD

**Issue by rmx-it** [vstakhov/rspamd#394]
Hi,
after upgrading to rspamd 1.0.4 under FreeBSD 10.2 I get tons of:
...
Oct  7 11:39:59 mail kernel: pid 58410 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:41:27 mail kernel: pid 58580 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:43:07 mail kernel: pid 58673 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:43:14 mail kernel: pid 58697 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:49:32 mail kernel: pid 58683 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:50:09 mail kernel: pid 58699 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:50:30 mail kernel: pid 58784 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:53:54 mail kernel: pid 58787 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:58:12 mail kernel: pid 58773 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 11:59:22 mail kernel: pid 58813 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 12:18:37 mail kernel: pid 58873 (rspamd-1.0.4), uid 65534: exited on signal 11
Oct  7 12:59:25 mail kernel: pid 58864 (rspamd-1.0.4), uid 65534: exited on signal 11
...

I'm using postfix <-> rmilter <-> rspamd...

Timely it could relate to the followin maillog entries (slightly scrambled):
...
12:59:25
Oct  7 12:59:25 mail postfix/smtpd[59355]: ...
Oct  7 12:59:25 mail postfix/smtpd[59347]: connect from unknown[...]
Oct  7 12:59:25 mail postfix/cleanup[59401]: 013913058: message-id=<...>
Oct  7 12:59:25 mail rmilter[845]: mlfi_eom: 013913058: tempfile=/tmp/msg.vOx7CkJl, size=3356
Oct  7 12:59:25 mail rmilter[845]: clamscan: scan 0.043852, localhost, /tmp/msg.vOx7CkJl
Oct  7 12:59:25 mail rmilter[845]: rate_check: address is whitelisted, skipping checks
Oct  7 12:59:25 mail postfix/qmgr[18404]: 013913058: from=<...>, size=3530, nrcpt=1 (queue active)
Oct  7 12:59:25 mail dovecot: lmtp(59403): Connect from local
Oct  7 12:59:25 mail dovecot: lmtp(...): /...: msgid=<1...>: saved mail to INBOX
Oct  7 12:59:25 mail postfix/lmtp[59402]: 013913058: to=<...>, relay=...[/var/run/dovecot/lmtp], delay=0.45,
 delays=0.39/0.01/0.02/0.02, dsn=2.0.0, status=sent (250 2.0.0 <...> /.../g Saved)
Oct  7 12:59:25 mail dovecot: lmtp(59403): Disconnect from local: Successful quit
Oct  7 12:59:25 mail postfix/qmgr[18404]: 013913058: removed
Oct  7 12:59:25 mail postfix/smtpd[59355]: disconnect from ...[...]

13:24:22
Oct  7 13:24:22 mail rmilter[845]: mlfi_eom: C696C3062: tempfile=/tmp/msg.O54T95rP, size=4745
Oct  7 13:24:22 mail rmilter[845]: clamscan: scan 0.033476, localhost, /tmp/msg.O54T95rP
Oct  7 13:24:22 mail rmilter[845]: rate_check: address is whitelisted, skipping checks
Oct  7 13:24:22 mail postfix/qmgr[18404]: C696C3062: from=<...>, size=4926, nrcpt=1 (queue active)
Oct  7 13:24:22 mail dovecot: lmtp(59670): Connect from local
Oct  7 13:24:22 mail dovecot: lmtp(...): .../g: msgid=<...>: saved mail to INBOX
Oct  7 13:24:22 mail postfix/lmtp[59669]: C696C3062: to=<...>, relay=...[/var/run/dovecot/lmtp], delay=0.7,
delays=0.65/0.01/0.02/0.02, dsn=2.0.0, status=sent (250 2.0.0 <...> .../g Saved)
Oct  7 13:24:22 mail dovecot: lmtp(59670): Disconnect from local: Successful quit
Oct  7 13:24:22 mail postfix/qmgr[18404]: C696C3062: removed
Oct  7 13:24:22 mail postfix/smtpd[59667]: disconnect from ...[...]
...

**Comment by vstakhov** [comment]
I need rspamd logs.

**Comment by rmx-it** [comment]
Zitat von Vsevolod Stakhov <notifications@github.com>:

> I need rspamd logs.
>

Here it is :

...
2015-10-07 12:59:25 #58864(normal) <97d8ec>; task; accept_socket:  
accepted connection from 127.0.0.1 port 36992
2015-10-07 12:59:25 #58864(normal) <97d8ec>; task;  
rspamd_message_parse: loaded message; id: <...@jenkins-9.freebsd.org>;  
queue-id: <013913058>
2015-10-07 12:59:25 #58864(normal) <97d8ec>; lua; settings.lua:222:  
check for settings
2015-10-07 12:59:25 #58864(normal) <97d8ec>; task;  
fuzzy_generate_commands: <...@jenkins-9.freebsd.org>, part is shorter  
than 300 symbols, skip fuzzy check
2015-10-07 12:59:27 #59406(normal) <7a5879>; main; fork_worker:  
starting normal process 59406
2015-10-07 12:59:27 #59406(normal) <wtm7ub>; map; rspamd_kv_list_fin:  
read hash of 288 elements
2015-10-07 12:59:27 #59406(normal) <qixjwz>; map; rspamd_kv_list_fin:  
read hash of 83 elements
2015-10-07 12:59:27 #59406(normal) <a87nhk>; map; rspamd_hosts_fin:  
read hash of 219 elements
2015-10-07 12:59:27 #59406(normal) <z9ijff>; cfg; rspamd_sqlite3_init:  
enable per language statistics for BAYES_SPAM
2015-10-07 12:59:27 #59406(normal) <z9ijff>; cfg; rspamd_sqlite3_init:  
enable per language statistics for BAYES_HAM
2015-10-07 13:24:22 #59057(normal) <919556>; task; accept_socket:  
accepted connection from 127.0.0.1 port 28315
2015-10-07 13:24:22 #59057(normal) <919556>; task;  
rspamd_message_parse: loaded message; id: <..@FreeBSD.org>; queue-id:  
<C696C3062>
2015-10-07 13:24:22 #59057(normal) <919556>; lua; settings.lua:222:  
check for settings
2015-10-07 13:24:24 #59671(normal) <7a5879>; main; fork_worker:  
starting normal process 59671
2015-10-07 13:24:24 #59671(normal) <wtm7ub>; map; rspamd_kv_list_fin:  
read hash of 288 elements
2015-10-07 13:24:24 #59671(normal) <qixjwz>; map; rspamd_kv_list_fin:  
read hash of 83 elements
2015-10-07 13:24:24 #59671(normal) <a87nhk>; map; rspamd_hosts_fin:  
read hash of 219 elements
2015-10-07 13:24:24 #59671(normal) <z9ijff>; cfg; rspamd_sqlite3_init:  
enable per language statistics for BAYES_SPAM
2015-10-07 13:24:24 #59671(normal) <z9ijff>; cfg; rspamd_sqlite3_init:  
enable per language statistics for BAYES_HAM
2015-10-07 13:33:38 #59671(normal) <29591e>; task; accept_socket:  
accepted connection from 127.0.0.1 port 56749
2015-10-07 13:33:38 #59671(normal) <29591e>; task;  
rspamd_message_parse: loaded message; id: <...@...>; queue-id:  
<3FA763066>
2015-10-07 13:33:38 #59671(normal) <29591e>; lua; settings.lua:222:  
check for settings
2015-10-07 13:33:40 #59759(normal) <7a5879>; main; fork_worker:  
starting normal process 59759
2015-10-07 13:33:40 #59759(normal) <wtm7ub>; map; rspamd_kv_list_fin:  
read hash of 288 elements
2015-10-07 13:33:40 #59759(normal) <qixjwz>; map; rspamd_kv_list_fin:  
read hash of 83 elements
2015-10-07 13:33:40 #59759(normal) <a87nhk>; map; rspamd_hosts_fin:  
read hash of 219 elements
2015-10-07 13:33:40 #59759(normal) <z9ijff>; cfg; rspamd_sqlite3_init:  
enable per language statistics for BAYES_SPAM
2015-10-07 13:33:40 #59759(normal) <z9ijff>; cfg; rspamd_sqlite3_init:  
enable per language statistics for BAYES_HAM
2015-10-07 13:39:30 #59759(normal) <163520>; task; accept_socket:  
accepted connection from 127.0.0.1 port 25829
2015-10-07 13:39:31 #59759(normal) <163520>; task;  
rspamd_message_parse: loaded message; id:  
<vstakhov/rspamd/issues/394/146163942@githu
b.com>; queue-id: <689C9306A>
2015-10-07 13:39:31 #59759(normal) <163520>; lua; settings.lua:222:  
check for settings
2015-10-07 13:39:31 #59759(normal) <163520>; task;  
fuzzy_generate_commands:  
<vstakhov/rspamd/issues/394/146163942@github.com>, part is s
horter than 300 symbols, skip fuzzy check
2015-10-07 13:39:31 #59759(normal) <163520>; task;  
fuzzy_generate_commands:  
<vstakhov/rspamd/issues/394/146163942@github.com>, part is s
horter than 300 symbols, skip fuzzy check
2015-10-07 13:39:33 #64075(normal) <7a5879>; main; fork_worker:  
starting normal process 64075
2015-10-07 13:39:33 #64075(normal) <wtm7ub>; map; rspamd_kv_list_fin:  
read hash of 288 elements
2015-10-07 13:39:33 #64075(normal) <qixjwz>; map; rspamd_kv_list_fin:  
read hash of 83 elements
2015-10-07 13:39:33 #64075(normal) <a87nhk>; map; rspamd_hosts_fin:  
read hash of 219 elements
2015-10-07 13:39:33 #64075(normal) <z9ijff>; cfg; rspamd_sqlite3_init:  
enable per language statistics for BAYES_SPAM
2015-10-07 13:39:33 #64075(normal) <z9ijff>; cfg; rspamd_sqlite3_init:  
enable per language statistics for BAYES_HAM
...

> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/vstakhov/rspamd/issues/394#issuecomment-146163942



Gruß
---
Michael Reifenberger

**Comment by vstakhov** [comment]
No ideas, can you obtain at least one core file? You need to setup the following sysctl's:

~~~
kern.corefile: /tmp/%N.core
kern.coredump: 1
kern.sugid_coredump: 1
~~~

Set `ulimit -c unlimited`, restart rspamd and then check /tmp/rspamd.core: 

~~~
# gdb /usr/local/bin/rspamd -c /tmp/core
...
(gdb) bt full
~~~

And show me the results.

**Comment by rmx-it** [comment]
Hi,
after the changes above and/or a additional restart I can't reproduce the problem any longer.
Hmm. 
So we should close this issue until (hopefully not!) happens again...

Thanks for your support anyway!

Greetings
---
Michael

**Comment by rmx-it** [comment]
Hi,
since I don't know if this is a real issue or not I didn't open a  
issue ticket on github yet...

It seems that many rspamd checked emails trigger at least one of the  
following metrices:
HFILTER_FROMHOST_NORES_A_OR_MX
HFILTER_HELO_NORES_A_OR_MX
HFILTER_MID_NORES_A_OR_MX

I've attached a few headers from mails where the DNS should be OK (at  
least postfix resolved it successfully)...

1.)
Return-Path: <devin@shxd.cx>
Delivered-To: mike@reifenberger.com
Received: from mail.eeeit.de
	by mail.eeeit.de (Dovecot) with LMTP id qPkKFBq6GVbFtAAAVus8/g
	for <mike@reifenberger.com>; Sun, 11 Oct 2015 03:23:38 +0200
Received: from shxd.cx (mail.shxd.cx [64.201.244.140])
	(using TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by mail.eeeit.de (Postfix) with ESMTPS id 0058B3A54
	for <mike@reifenberger.com>; Sun, 11 Oct 2015 03:23:35 +0200 (CEST)
Received: from [64.201.244.132] (port=52403 helo=[10.0.0.100])
	by shxd.cx with esmtpsa (TLSv1:AES256-SHA:256)
	(Exim 4.77 (FreeBSD))
	(envelope-from <devin@shxd.cx>)
	id 1Zl5M8-000CLX-CF; Sat, 10 Oct 2015 18:23:20 -0700
References:  
<20150511174604.Horde.x5ya_Sp3mvjaogt9T2OmGBF@mail.eeeit.de>  
<555160DD.8040203@FreeBSD.org> <56197B79.9020005@FreeBSD.org>
Mime-Version: 1.0 (1.0)
In-Reply-To: <56197B79.9020005@FreeBSD.org>
Content-Type: multipart/alternative;
	boundary=Apple-Mail-B75FB661-A390-4ED1-BDEA-7B4A82A86AAA
Content-Transfer-Encoding: 7bit
Message-Id: <DDC2FA42-6427-4CA3-B2BC-DD46B93469FA@fraubsd.org>
Cc: Michael Reifenberger <mike@reifenberger.com>,
  Devin Teske <dteske@FreeBSD.org>
X-Mailer: iPad Mail (12F69)
From: Devin Teske <freebsdfrau@fraubsd.org>
Subject: Re: moving ficl to sys/contrib
Date: Sat, 10 Oct 2015 18:23:30 -0700
To: Pedro Giffuni <pfg@FreeBSD.org>
Sender: devin@shxd.cx
X-Spamd-Result: default: False [2.30 / 15.00]
  BAYES_HAM(-3.00)
  HFILTER_MID_NORES_A_OR_MX(0.50)
  R_PARTS_DIFFER(2.49)
  FORGED_SENDER(0.30)
  HFILTER_HELO_NORES_A_OR_MX(2.00)
X-Spamd-Server: localhost
X-Spamd-Scan-Time: 1.04
X-Spamd-Queue-ID: 0058B3A54



2.)
Return-Path: <pfg@FreeBSD.org>
Delivered-To: mike@reifenberger.com
Received: from mail.eeeit.de
	by mail.eeeit.de (Dovecot) with LMTP id /3QXE0q9GVZAtQAAVus8/g
	for <mike@reifenberger.com>; Sun, 11 Oct 2015 03:37:14 +0200
Received: from nm25-vm1.bullet.mail.bf1.yahoo.com  
(nm25-vm1.bullet.mail.bf1.yahoo.com [98.139.212.155])
	(using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by mail.eeeit.de (Postfix) with ESMTPS id 652DA3A57
	for <mike@reifenberger.com>; Sun, 11 Oct 2015 03:37:11 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yahoo.com;  
s=s2048; t=1444527430;  
bh=DK2FDcIEyuKMQzdAV2ZGHQjx4siL9p4hJ3r5JL9sIjA=;  
h=Subject:To:References:Cc:From:Date:In-Reply-To:From:Subject;  
b=s3sq+AOL98Ln/VZGcy07k9q8grlbTgctaNrufcWhC80QiuRTWj9wvdkaREm50TfTIwGjEk/NarjZrstRiMSCcfTQLH7jn6lDXrZg3zR2fheyRRaxm5KEdtn6aoNCEgAxu7RAH76QFQOWnGm+9m9hV3eEwOflptpfBv73y8rm0i7+rtowBqGSpZDV7MEAvCDnupBL7hejJwCGftb7vHI1GEhY69m3vVvh5Ai+DZ9UqCvFeqMDjj/6BtDX69LQJ0zltx/ZLCRQ4Gq0MWXUvXIzKhNDDN9iOi5Gb0kUDUwVeMfUnp1tsw76sUb0lE2FQ71PTaBfJjRCDPrpkCWAkIk/Ug==
Received: from [66.196.81.173] by nm25.bullet.mail.bf1.yahoo.com with  
NNFMP; 11 Oct 2015 01:37:10 -0000
Received: from [98.139.213.12] by tm19.bullet.mail.bf1.yahoo.com with  
NNFMP; 11 Oct 2015 01:37:10 -0000
Received: from [127.0.0.1] by smtp112.mail.bf1.yahoo.com with NNFMP;  
11 Oct 2015 01:37:10 -0000
X-Yahoo-Newman-Id: 24361.19084.bm@smtp112.mail.bf1.yahoo.com
X-Yahoo-Newman-Property: ymail-3
X-YMail-OSG: KCVhJKMVM1m0LHrdP38WbZC_hYGYP0RqjCqkppNDkvrL.Y7
  _ZuUSi9zMFqrj_0xywha0Zv7xASaOOboewyU1Ra.0y4p5stQ3Yr6Rp4bOoPm
  lHGUarI5kKrp4bjRwj7kFE4ET24mIREFsgC7EV5N21ePOGUrJVPePyMHrgzj
  nsSPu8zMzZGflYffU_Zx8p3lOttj._mhOUbrEVpfS2QflDF7qFBZmlrITwtn
  aI_juQivLuv5WYWSuX7S79uOAV5xJVw8I.IcMZpLR8MkszDHdE_nKs5iZkwx
  jkwlw9UrqZoZJ1caEc86qEgrbWayTTw1O.W6Cm012iHkzlvPUWC1HOUms9uH
  WQCYGWb39Omsfe2EU_IHZ7E4kdj8RyOd7Kg9ED8DhcuCSNzs_10348DIE05V
  EmAjfC52SJvjgx73NiUNngY1FNECOrzGHvwj5tU9fNL1f9Z5V1jeDZxrDoBv
  n2pcM0_OXlnTMRNTdQACM_icSPiN1wZawkCGX6YMnOfNeZvOJPC6wvPmqY3V
  RDu38mnTnavhEy2KHMmEZXfjdHEpMHhv.
X-Yahoo-SMTP: xcjD0guswBAZaPPIbxpWwLcp9Unf
Subject: Re: moving ficl to sys/contrib
To: Devin Teske <freebsdfrau@fraubsd.org>
References: <20150511174604.Horde.x5ya_Sp3mvjaogt9T2OmGBF@mail.eeeit.de>
  <555160DD.8040203@FreeBSD.org> <56197B79.9020005@FreeBSD.org>
  <DDC2FA42-6427-4CA3-B2BC-DD46B93469FA@fraubsd.org>
Cc: Michael Reifenberger <mike@reifenberger.com>,
  Devin Teske <dteske@FreeBSD.org>
From: Pedro Giffuni <pfg@FreeBSD.org>
Message-ID: <5619BD4E.6010805@FreeBSD.org>
Date: Sat, 10 Oct 2015 20:37:18 -0500
User-Agent: Mozilla/5.0 (X11; FreeBSD amd64; rv:38.0) Gecko/20100101
  Thunderbird/38.2.0
MIME-Version: 1.0
In-Reply-To: <DDC2FA42-6427-4CA3-B2BC-DD46B93469FA@fraubsd.org>
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit
X-Spamd-Result: default: False [-0.60 / 15.00]
  BAYES_HAM(-3.00)
  HFILTER_FROMHOST_NORES_A_OR_MX(1.50)
  R_DKIM_ALLOW(-1.10)
  HFILTER_HELO_NORES_A_OR_MX(2.00)
X-Spamd-Server: localhost
X-Spamd-Scan-Time: 1.55
X-Spamd-Queue-ID: 652DA3A57


Thanks again for providing rspamd!

Greetings
---
Michael Reifenberger


Gruß
---
Michael Reifenberger

**Comment by vstakhov** [comment]
The rule `bla_NO_A_OR_MX` matches when there is no **either** A **or** MX record for `from`/`helo` or `Message-ID`. I've not yet revisited these rules in terms of FP.
