### ISSUE TITLE
scores sometimes don't add up

### ISSUE THREAD

**Issue by ma2thieu** [vstakhov/rspamd#396]
For some emails (but not all of them) the scores don't add up : 

```
1) ([8.90/15.00] [R_MIXED_CHARSET,RWL_MAILSPIKE_POSSIBLE,R_SPF_ALLOW])
2) ([7.79/15.00] [R_DKIM_ALLOW,R_SPF_ALLOW,R_MIXED_CHARSET])
3) ([-0.20/15.00 [BAYES_HAM,R_DKIM_ALLOW,RCVD_IN_DNSWL_LOW,R_SPF_ALLOW,R_MIXED_CHARSET])
```

```
1) 5 + 0 - 1.1 = 3.9 != 8.9
2) 5 - 1.1 - 1.1 = 2.8 != 7.79
3) -3 -1.1 + 0 -1.1 + 5 = -0.2 (ok)
```

With the defaults values : 
```
R_MIXED_CHARSET : +5
RWL_MAILSPIKE_POSSIBLE  : +0
R_SPF_ALLOW: SPF : -1.1
R_DKIM_ALLOW : -1.1
BAYES_HAM : -3
RCVD_IN_DNSWL_LOW : 0
```

Also is it normal that for some emails there is neither BAYES_HAM nor BAYES_SPAM ?

**Comment by vstakhov** [comment]
Symbols can add their score multiple times (unless `one_shot` is specified either globally in `options` or for a specific symbol). `rspamc` should show the real scores for symbols in this case. Some other symbols can even add more or less scores in certain cases. For example, bayes or fuzzy can add score in interval `(0 .. weight]` depending on the check results.

Bayes symbols can be not added if there is not enough information to distinguish between spam/ham classes or the tokens in a message have never been learnt by rspamd.

**Comment by ma2thieu** [comment]
Thanks a lot for the explanations!
