### ISSUE TITLE
error build 1.0.5 on Centos 6 (x64)

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rspamd#400]
1) try to build version 1.0.5 anf get netx erros:
[root@dev rspamd-1.0.5]# make
[  1%] Built target xxhash
[  2%] Built target rspamd-cdb
[  3%] Built target rspamd-http-parser
[  5%] Built target ottery
[  8%] Built target snowball
[  9%] Built target modules
[  9%] Built target stemmer_deps
[ 37%] Built target stemmer
[ 37%] Built target stemwords
[ 37%] Built target blake2
[ 41%] Built target ucl
[ 44%] Built target rdns
[ 45%] Built target rspamd-actrie
[ 89%] Built target rspamd-server
Linking C executable rspamd
CMakeFiles/rspamd.dir/rspamd.c.o: In function `main':
/root/rpmbuild/BUILD/rspamd-1.0.5/src/rspamd.c:1018: undefined reference to `evsignal_set'
/root/rpmbuild/BUILD/rspamd-1.0.5/src/rspamd.c:1021: undefined reference to `evsignal_set'
/root/rpmbuild/BUILD/rspamd-1.0.5/src/rspamd.c:1024: undefined reference to `evsignal_set'
/root/rpmbuild/BUILD/rspamd-1.0.5/src/rspamd.c:1027: undefined reference to `evsignal_set'
/root/rpmbuild/BUILD/rspamd-1.0.5/src/rspamd.c:1030: undefined reference to `evsignal_set'
collect2: ld returned 1 exit status
make[2]: *** [src/rspamd] Error 1
make[1]: *** [src/CMakeFiles/rspamd.dir/all] Error 2
make: *** [all] Error 2

[root@dev rspamd-1.0.5]# uname -a
Linux vb.pantele.com.ua 3.10.86-1.el6.elrepo.x86_64 #1 SMP Tue Aug 11 09:16:01 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

2) versions 1.0.3 and 1.0.4 build OK.
3) rpms for version 1.0.5 not present too.

**Comment by vstakhov** [comment]
This should be fixed in the nightly repo. Stable repos will be updated tonight or tomorrow.

**Comment by mnik247** [comment]
fixed in 1.0.6
