### ISSUE TITLE
automatically rotate rspamd.log on freebsd

### ISSUE THREAD

**Issue by msimerson** [vstakhov/rspamd#403]
by doing something like this:

```sh
echo '/var/log/rspamd/rspamd.log	nobody:nobody	644  5	   100	@0101T JC /var/run/rspamd/rspamd.pid' > /usr/local/etc/newsyslog.conf.d/rspamd
```

**Comment by moisseev** [comment]
I had issues with SIGHUP.  https://github.com/vstakhov/rspamd/issues/97 So I am using SIGUSR1 (30) for log rotation.

I suppose 100K size limit is too low. With `level = "info";` I have about 1M logs per day on very small servers.

I'd like something like this:
`/var/log/rspamd/rspamd.log      nobody:nobody   644  7    *  @T00  J   /var/run/rspamd/rspamd.pid 30`
or
`/var/log/rspamd/rspamd.log      nobody:nobody   644  7    5000  $W0D0  J   /var/run/rspamd/rspamd.pid 30`

**Comment by msimerson** [comment]
> /var/log/rspamd/rspamd.log nobody:nobody 644 7 * @T00 J /var/run/rspamd/rspamd.pid 30

That's fine by me. It has the added advantage of being nice and predictable.

**Comment by msimerson** [comment]
Actually, I amend that to:

```diff
- /var/log/rspamd/rspamd.log nobody:nobody 644 7 * @T00 J /var/run/rspamd/rspamd.pid 30
+ /var/log/rspamd/rspamd.log nobody:nobody 644 7 * @T00 JC /var/run/rspamd/rspamd.pid 30
```

**Comment by moisseev** [comment]
I have no objection, I'm just wondering what benefits of using C flag here? Rspamd itself creates log file if it doesn't exist.

**Comment by msimerson** [comment]
As long as `/var/log/rspamd/` exists and is writable by nobody:nobody, so that rspamd has permission to create the new file, then there's no difference at all. On occasion, rude things can occur in /var/logs (think: disk full events, aggressive/inadvertent rm -rf, etc.) and newsyslog, running as root, has the ability to 'set things right'.  If you aren't going to use the C flags there, then it's rather pointless to specify the user:group, don'tcha think?

**Comment by moisseev** [comment]
@vstakhov could you commit [Bug 205456] for mail/rspamd-devel too?
[Bug 205456]:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205456
