### ISSUE TITLE
How to enable RRD statistics?

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#405]

**Comment by vstakhov** [comment]
It is just `rrd` in options section that would specify path to the target rrd file.

**Comment by mnik247** [comment]
Please more details...

**Comment by moisseev** [comment]
rspamd.conf.local:
```
options {
    rrd = "/var/db/rspamd/rspamd.rrd"
}
```

**Comment by vstakhov** [comment]
And is it created?

**Comment by mnik247** [comment]
to vstakhov: yes, file created, but I can't understand where it usage.

**Comment by vstakhov** [comment]
It was intended for webui usage (and there is some preliminary implementation of `/graph` path). Also, you can use the normal `rrdtool` command to build something from this rrd file.

**Comment by moisseev** [comment]
`/graph?password=q1&type=hourly`exports RRD to JSON. It intended for some graphical representation component, I guess. Is there one already?

**Comment by vstakhov** [comment]
Nope, I had not enough time to add it. But it should not be hard to do using d3.js (which is used for piechart already).

**Comment by moisseev** [comment]
Using rrdtool looks straightforward and efficient. With rrdtool graphs will be generated on server side, stored on server, cached on client and updated only when it is necessary. JS requires rebuilding of all graphs on client side on every page reload. What benefits d3.js has over rrdtool?

You are using 1s step for RRD. Does it make sense? "Once per minute for 1 day" `rra[0]` (60 PDP per row) has same values repeated 4 times. Looks like data source changed once in 4 minutes actually.

**Comment by vstakhov** [comment]
1) I'm open for suggestions in using the original rrdttol for graphs. However, I won't create graphs from the C code by obvious reasons. So I'd need scripts to call `rrdtool graph` to generate images. Or I need to use online graphs by d3.js. Whatever is better/convenient.

2) Would you suggest better values for RRD step?

Actually, I'd like to know users opinion on this topic, as I don't have a clear point of view I'm afraid.

**Comment by moisseev** [comment]
1) The simplest way - rrdtool has `rrdcgi`. Just a template needed to make it work. Working template example: https://gist.github.com/moisseev/330c705e065cd7fd59d9
Actually, script to call `rrdtool graph` isn't far more complicated. Example here: https://github.com/moisseev/BackupPC/commit/28bb59f29e31bb0571d72f99d5c3823f5ea51000

2) I think step (and update interval) about 1-5min should be reasonable. May be default 300s step would be good enough. Or may be 60s will fit better with msgs/min scale. 
I don't know how rspamd does calculations of messages per time, but it seems to me that for some reason for now it occurs every 4 minutes and RRD updates every second. So I don't see the point in step and update interval lower than 4 minutes.

May be better way is to store statistics in RRD as a GAUGE and do calculations with `rrdtool graph`.

**Comment by CaptainQwark** [comment]
I like the rrd -> json -> d3.js route much better. try not to depend on external rrdtools and scripts. Those things break too easily.

Client side rendering gives much more flexibilty e.g. zooming on interesting parts, prettier graphs, etc. Even mobile browsers are more than capable these days. You aready have the d3.js library so just reuse that.

**Comment by moisseev** [comment]
Well, further clarification of my question about RRD update interval and real data source update interval. 
I have a test rspamd installation, clean RRD, no mail traffic. I've checked a message with rspamd just one time.Why was 4 CDPs ( approximately 320 PDPs) stored in the RRD?
~~~xml
        <!-- Round Robin Archives -->
        <rra>
                <cf>AVERAGE</cf>
                <pdp_per_row>60</pdp_per_row> <!-- 60 seconds -->
...
                <database>
...
                        <!-- 2016-02-24 06:51:00 MSK / 1456285860 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-02-24 06:52:00 MSK / 1456285920 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-02-24 06:53:00 MSK / 1456285980 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>1.591661362e-02</v><v>0.000000000e+00</v></row>
                        <!-- 2016-02-24 06:54:00 MSK / 1456286040 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>1.591661362e-02</v><v>0.000000000e+00</v></row>
                        <!-- 2016-02-24 06:55:00 MSK / 1456286100 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>1.591661362e-02</v><v>0.000000000e+00</v></row>
                        <!-- 2016-02-24 06:56:00 MSK / 1456286160 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>1.591661362e-02</v><v>0.000000000e+00</v></row>
                        <!-- 2016-02-24 06:57:00 MSK / 1456286220 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-02-24 06:58:00 MSK / 1456286280 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
 ~~~

**Comment by moisseev** [comment]
~~~
# service rspamd onestop
# rm /var/db/rspamd/rspamd.rrd
# service rspamd onestart

# rspamc learn_spam message.eml

# rspamc message.eml

# rrdtool dump /var/db/rspamd/rspamd.rrd

...
                        <!-- 2016-07-19 08:23:00 MSK / 1468905780 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-19 08:24:00 MSK / 1468905840 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-19 08:25:00 MSK / 1468905900 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-19 08:26:00 MSK / 1468905960 --> <row><v>1.596359620e-02</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-19 08:27:00 MSK / 1468906020 --> <row><v>1.596359620e-02</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-19 08:28:00 MSK / 1468906080 --> <row><v>1.596359620e-02</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-19 08:29:00 MSK / 1468906140 --> <row><v>1.596359620e-02</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-19 08:30:00 MSK / 1468906200 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-19 08:31:00 MSK / 1468906260 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
...
~~~
[rspamd.log.zip](https://github.com/vstakhov/rspamd/files/370772/rspamd.log.zip)

**Comment by moisseev** [comment]
Well, data is correct now in the RRD, but not in JSON.
~~~
                        <!-- 2016-07-20 09:58:00 MSK / 1468997880 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-20 09:59:00 MSK / 1468997940 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-20 10:00:00 MSK / 1468998000 --> <row><v>1.656209296e-02</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-20 10:01:00 MSK / 1468998060 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
                        <!-- 2016-07-20 10:02:00 MSK / 1468998120 --> <row><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v><v>0.000000000e+00</v></row>
~~~
~~~
,{"x":1468997880,"y":0.0},{"x":1468997880,"y":0.0},{"x":1468997940,"y":0.008281},{"x":1468998000,"y":0.008281},{"x":1468998060,"y":0.008281},{"x":1468998060,"y":0.008281},{"x":1468998120,"y":0.0},{"x":1468998180,"y":0.0},
~~~
I think it is here:
https://github.com/vstakhov/rspamd/blob/master/src/controller.c#L1036
It repeats `rrd_result->ds_count` times. I don't understand why.
