### ISSUE TITLE
help with setting for multiple fuzzy servers

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rspamd#411]
I'd like setup 2 fuzzy servers.
1-"rspamd.com:11335" (read only)
2-own server (localhost, read/write)
And wont to learn (spam/ham) my local server and use rspamd.com:11335 only for "read".

I try add to rspamd.conf (like in https://rspamd.com/doc/workers/fuzzy_storage.html)
worker {
   type = "fuzzy";
   bind_socket = "*:11335";
   hash_file = "${DBDIR}/fuzzy.db"
   expire = 90d;
   allow_update = "127.0.0.1";
}
File fuzzy.db is success created, but in rspamd.log:
14589(main) <d606fd>; main; spawn_workers: cannot spawn more than 1 fuzzy worker, so spawn one

Can you help me with correct setting for two fuzzy servers?
rspamd (1.0.6) + postfix (rmilter)

**Comment by vstakhov** [comment]
That message is not an error. It merely means that unlike other workers, there is no support of multiple workers for a single fuzzy storage so far. This limitation will be likely removed in future. Anyway, your storage should work fine as far as I see.

**Comment by mnik247** [comment]
Thanks.
But I don't want setup of multiple workers.
I' like setup single local fuzzy storage with worker (read/write) and use one remote rspamd.com:11335 (read only) too.

In docs https://rspamd.com/doc/modules/fuzzy_check.html for multi server:
fuzzy_check {
	rule {
		# List of servers, can be an array or multi-value item
		servers = "localhost:11335";
		servers = "highsecure.ru:11335";
more setting....
}
But I need setup independent next setting for this servers:
#List of additional mime types to be checked in this fuzzy
mime_types = "application/pdf";
mime_types = ["application/*", "*/octet-stream", "*"];
#Maximum global score for all maps
max_score = 20.0;
#Ignore flags that are not listed in maps for this rule
skip_unknown = yes;
#If this value is false, then allow learning for this fuzzy rule
read_only = no;
#Key for strict digests (default: "rspamd")
fuzzy_key = "somebigrandomstring";
#Key for fuzzy siphash (default: "rspamd")
fuzzy_shingles_key = "anotherbigrandomstring";

**Comment by vstakhov** [comment]
You need to setup multiple fuzzy rules.

**Comment by mnik247** [comment]
1) Like this?
fuzzy_check {
   rule {
   servers = "localhost:11335";
   read_only = no;
  ...more setting...
  }
   rule {
   servers = "rspamd.com:11335";
   read_only = yes;
   ...more setting...
  }
}

2) Learning fuzzy_check. 
It's correct? "If server have read_only = yes it will skipped"

3) Using fuzzy_check:
From docs: "On check, rspamd selects a server in round-robin matter."
Is it possible to check ALL servers, not roud-robin?

**Comment by vstakhov** [comment]
1) Yes.
2) Yes.
3) No, but all servers will be checked if they are in different rules. Meaning that servers are selected in round-robin matter for a single rule.

**Comment by mnik247** [comment]
Thanks.
But is possible more info about 3)?

**Comment by moisseev** [comment]
Round-robin:
```
fuzzy_check {
    rule {
        servers = "localhost:11335";
        servers = "rspamd.com:11335";
        ...more...
    }
}
```
Both servers will be checked:
```
fuzzy_check {
    rule {
        servers = "localhost:11335";
        ...more...
    }
    rule {
        servers = "rspamd.com:11335";
        ...more...
    }
}
```
Also, different symbols for the local server make troubleshooting a little easier.  I've added new symbols to the same group "fuzzy" and set max_score for the group.

rspamd.conf.local:
```
metric {
    name = "default";
    group {
        name = "fuzzy";
        max_score = 10.0;
        symbol {
            weight = 5.0;
            description = "Generic fuzzy hash match";
            name = "LOCAL_FUZZY_UNKNOWN";
        }
        symbol {
            weight = 10.0;
            description = "Denied fuzzy hash";
            name = "LOCAL_FUZZY_DENIED";
        }
        symbol {
            weight = 5.0;
            description = "Probable fuzzy hash";
            name = "LOCAL_FUZZY_PROB";
        }
        symbol {
            weight = -2.1;
            description = "Whitelisted fuzzy hash";
            name = "LOCAL_FUZZY_WHITE";
        }
    }
}
```

**Comment by mnik247** [comment]
to moisseev: thanks for examples.

**Comment by mnik247** [comment]
to moisseev: can you check it for correct?

**rspamd.conf.local:**
worker {
   type = "fuzzy";
   #bind_socket = "*:11335";
   bind_socket = "127.0.0.1:11335";
   hash_file = "${DBDIR}/fuzzy.db"
   expire = 90d;
   allow_update = "127.0.0.1";
}
metric {
    name = "default";
    group {
        name = "fuzzy";
        max_score = 10.0;
        symbol {
            weight = 5.0;
            description = "Generic fuzzy hash match";
            name = "LOCAL_FUZZY_UNKNOWN";
        }
        symbol {
            weight = 10.0;
            description = "Denied fuzzy hash";
            name = "LOCAL_FUZZY_DENIED";
        }
        symbol {
            weight = 5.0;
            description = "Probable fuzzy hash";
            name = "LOCAL_FUZZY_PROB";
        }
        symbol {
            weight = -2.1;
            description = "Whitelisted fuzzy hash";
            name = "LOCAL_FUZZY_WHITE";
        }
    }
}

updated **fuzzy_check.conf:**
fuzzy_check {
    # Include dynamic conf for the rule
    .include(try=true,priority=1) "${DBDIR}/dynamic/fuzzy_check.conf"
    min_bytes = 300;
    rule {
        servers = "rspamd.com:11335";
        encryption_key = "icy63itbhhni8bq15ntp5n5symuixf73s1kpjh6skaq4e7nx5fiy";
        symbol = "FUZZY_UNKNOWN";
        mime_types = ["application/"];
        max_score = 20.0;
        read_only = yes;
        skip_unknown = yes;
        fuzzy_map = {
            FUZZY_DENIED {
                max_score = 20.0;
                flag = 1;
            }
            FUZZY_PROB {
                max_score = 10.0;
                flag = 2;
            }
            FUZZY_WHITE {
                max_score = 2.0;
                flag = 3;
            }
        }
    }
    rule {
        servers = "127.0.0.1:11335";
        #encryption_key = "icy63itbhhni8bq15ntp5n5symuixf73s1kpjh6skaq4e7nx5fiy";
        symbol = "LOCAL_FUZZY_UNKNOWN";
        mime_types = ["application/*"];
        #max_score = 20.0;
        read_only = no;
        skip_unknown = yes;
        fuzzy_map = {
            LOCAL_FUZZY_DENIED {
                max_score = 20.0;
                flag = 1;
            }
            LOCAL_FUZZY_PROB {
                max_score = 10.0;
                flag = 2;
            }
            LOCAL_FUZZY_WHITE {
                max_score = -2.0;
                flag = 3;
            }
        }
}

**And then try testing:**
`1) check before:`
#rspamc -t 30 symbols  rspam-spam-04.eml                                                                                           Results for file: rspam-spam-04.eml (0.623 seconds)
[Metric: default]
Spam: false
Score: 23.59 / 155.00
Action: add header
Symbol: RBL_COMPOSITE_RCVD_IN_DNSWL_RBL_SEM (0.00)
Symbol: SEM_URIBL (3.50)[complexsw.ru.uribl.spameatingmonkey.net]
Symbol: RAMBLER_URIBL (4.50)[complexsw.ru.uribl.rambler.ru]
Symbol: BAYES_SPAM (2.98)[99.61%]
Symbol: FUZZY_DENIED (9.60)[1: 0.93 / 0.92, 1: 0.96 / 0.96]
Symbol: RBL_COMPOSITE_RCVD_IN_DNSWL_RBL_SENDERSCORE (0.00)
Symbol: RECEIVED_SPAMHAUS_XBL (3.00)
Symbol: RBL_COMPOSITE_RCVD_IN_DNSWL_RBL_SORBS_DUL (0.00)
Symbol: RBL_COMPOSITE_RCVD_IN_DNSWL_RBL_SPAMHAUS (0.00)
Symbol: RBL_COMPOSITE_RCVD_IN_DNSWL_RBL_SORBS (0.00)
Urls: ["complexsw.ru"]
Message-ID: 01d110cc$6982af00$208cc575@ryzhenko.ru

`2) learn fuzz as spam:`
#rspamc -f 1 -w 10 fuzzy_add rspam-spam-04.eml
Results for file: rspam-spam-04.eml (0.005 seconds)
success = true;

`3) check again:`
#rspamc symbols  rspam-spam-04.eml
Results for file: /rspam-spam-04.eml (1.136 seconds)
[Metric: default]
Spam: false
Score: 18.59 / 155.00
Action: add header
Symbol: BAYES_SPAM (2.98)[99.61%]
Symbol: RBL_SORBS (0.00)
Symbol: RBL_SORBS_DUL (2.00)
Symbol: LOCAL_FUZZY_DENIED (0.00)[1: 1.00 / 0.00, 1: 1.00 / 0.00]
Symbol: RBL_SPAMHAUS_PBL (2.00)
Symbol: RBL_SENDERSCORE (2.00)
Symbol: FUZZY_DENIED (9.60)[1: 0.93 / 0.92, 1: 0.96 / 0.96]
Urls: ["complexsw.ru"]
Message-ID: 01d110cc$6982af00$208cc575@ryzhenko.ru

`4) We seen new symbol "LOCAL_FUZZY_DENIED"`
But why this weight = 0.00?

**Comment by moisseev** [comment]
I'd try to uncomment `#max_score = 20.0;` in local fuzzy_check rule.


> updated fuzzy_check.conf:

I guess, it is `rspamd.conf.local.override` actually?


I'm not sure `mime_types = ["application/"];` for rspamd.com will work. It should be `mime_types = ["application/*"];`

**Comment by moisseev** [comment]
to @vstakhov
@mnik247 uses the same flags for both local fuzzy storage and `servers = "rspamd.com:11335";`
Is it good idea or it can lead to problems?

**Comment by mnik247** [comment]
1) uncomment #max_score = 20.0 and get:
#Symbol: LOCAL_FUZZY_DENIED (9.43)[1: 1.00 / 0.94, 1: 1.00 / 0.94, 1: 1.00 / 0.94, 1: 1.00 / 0.94, 1: 1.00 / 0.94, 1: 1.00 / 0.94]
Thanks.
2) I not use rspamd.conf.local.override  yet.
3) mime_types is correct, I deleted 'start' from  ["application/"] for incorrect formatting.
4) can you write full command for fuzzy learning (ham/spam) on your system?

**Comment by moisseev** [comment]
`rspamc -w $FUZZY_WEIGHT -f $FUZZY_FLAG fuzzy_add`
It's a part of script actually.
https://gist.github.com/moisseev/a0b032842225a7d0b17a

**Comment by mnik247** [comment]
Thanks for link to rspamc_learn.sh
And why need mode "prob"?

**Comment by moisseev** [comment]
FUZZY_PROB intended mostly for "unreliable" sources (automatic learning, users and so on). I'm not using it for now, actually.

BTW Please be aware that the last line in the script __expunges folders__.

**Comment by vstakhov** [comment]
Rules within fuzzy check plugin are independent from each other. Therefore, you can use both same flags and/or same flags within different rules.
