### ISSUE TITLE
VoidLinux: Build on i686 is broken

### ISSUE THREAD

**Issue by Gottox** [vstakhov/rspamd#413]
Hello again! :smiley: 

This time i686 is broken:

* the template file: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/rspamd/template

* build log: http://build.voidlinux.eu/builders/i686_builder/builds/17817/steps/shell_3/logs/stdio

**Comment by Gottox** [comment]
Oh, and before I forget it: Thanks for the awesome software, not only rspamd but libucl too :)

**Comment by vstakhov** [comment]
Should be fixed in 1.0.8

**Comment by Gottox** [comment]
It's fixed in 1.0.[98].
