### ISSUE TITLE
rspamc timeout

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rspamd#415]
Sometimes I have next error:
#rspamc symbols  rspam-spam-02.eml
Results for file: rspam-spam-02.eml (5.005 seconds)
IO timeout

rspamd.log: 
#14653(normal) <83cba6>; task; rspamd_task_timeout: processing of task timed out, forced processing

Where can I change this timeout?

Centos 6 (x64) + postfix + rspamd 1.0.8 + rmilter

**Comment by mnik247** [comment]
-t seconds, --timeout=seconds
              Timeout for waiting for a reply (can be floating point number, e.g.  0.1)

**Comment by mnik247** [comment]
Not helped - 99% - timeout:
rspamc -t 300 symbols  rspam-spam-02.eml
Results for file: rspam-spam-02.eml (300.100 seconds)
IO timeout

But sometimes...
#rspamc -t 300 symbols  /rspam-spam-02.eml
Results for file: /rspam-spam-02.eml (0.383 seconds)
[Metric: default]
Spam: false
Score: 21.00 / 155.00
Action: add header
Symbol: HFILTER_MID_NOT_FQDN (0.50)
Symbol: BAYES_SPAM (3.00)[100.00%]
Symbol: DATE_IN_PAST (1.00)
Symbol: RAMBLER_URIBL (4.50)[maver.space.uribl.rambler.ru]
Symbol: SEM_URIBL_FRESH15 (3.00)[maver.space.fresh15.spameatingmonkey.net]
Symbol: ONCE_RECEIVED_STRICT (4.00)
Symbol: RCVD_IN_DNSWL (0.00)
Symbol: ONCE_RECEIVED (1.00)
Symbol: HFILTER_HOSTNAME_UNKNOWN (4.00)
Symbol: LOCAL_FUZZY_PROB (0.00)[2: 1.00 / 0.00, 2: 1.00 / 0.00]
Urls: ["www.maver.space"]
Message-ID: 033301d10c70$19b3a890$5565eb20@sluodpynts

This bad email - http://pastebin.com/NspaapKA

**Comment by vstakhov** [comment]
This sounds like some issue in your configuration. 300 seconds is unrealistic timeout.
