### ISSUE TITLE
How to create a rule for fake opt-out HTML links?

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#418]
I'd like to create rule for fake opt-out links like this
```
<DIV align=3Dleft><A=20
href=3D"http://goo.gl/pqKbP9?wmauu"><STRONG><FONT=20
size=3D1>=CE=F2=EF=E8=F1=E0=F2=FC=F1=FF =EE=F2=20
=F0=E0=F1=F1=FB=EB=EA=E8</FONT></STRONG></A></DIV></FONT></DIV></BODY></H=
TML>
```
I want to add a symbol if a text/html part contains tag A with certain text and certain domain part of the hyperlink, but I couldn't find a way to get html content with lua.
How to create such rule?

**Comment by vstakhov** [comment]
But how your client displays such a message? Does it tries to parse HTML or shows just a plain message? In the second case, a user won't see a malicious URL anyway...

**Comment by moisseev** [comment]
Yes, most of MUAs nowadays can display HTML messages and a lot of users are using that mode. I'm not considering that URLs as malicious and it isn't about _hiding_ the URL. I'm getting a lot of image spam messages with such URL and I haven't seen ham messages contain opt-outs like that. I want to reject the messages eventually.

Message sample: https://paste.rspamd.com/FGBE
