### ISSUE TITLE
log SPF IP address

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rspamd#422]
Is it possible add IP address for check SPF records to log file?
I have some email with failed SPF, but when I manual check SPF is good.

**Comment by crepererum** [comment]
I also have some problems with SPF failures. I've tried to check the SPF record and permission manually I was not able to figure out why it failed (all of my own tests said that they should pass).

**Comment by vstakhov** [comment]
It seems that prior to 0c43dd1, rspamd had a bug with parsing of certain SPF redirects. Logging of SPF message will be possible in 1.1 with flexible logging format (that is already implemented but not for spf).

**Comment by mnik247** [comment]
Thanks.
Will wait new version 1.0.11 or 1.1.0 for checking result.

**Comment by vstakhov** [comment]
Rolling packages are ready for 1.1.0

**Comment by mnik247** [comment]
When we wait version 1.1.0?

**Comment by fatalbanana** [comment]
Version 1.1.0 probably won't be generally available any time soon given that its just recently been branched, but you can try the nightly: https://rspamd.com/downloads.html (or try build `rspamd-1.0` branch if you're not feeling quite so adventurous)
