### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#429]
Hello
Logic that I still have this ...

#2315((NULL)) <z9ijff>; lua; ratelimit.lua:379: no servers are specified
#2315((NULL)) <z9ijff>; lua; dmarc.lua:291: no servers are specified for dmarc stats
#2315((NULL)) <z9ijff>; symcache; rspamd_symbols_cache_validate: symbol 'SEM_URIBL_UNKNOWN' has its score defined but there is no corresponding rule registered
#2315((NULL)) <z9ijff>; symcache; rspamd_symbols_cache_validate: symbol 'DBL' has its score defined but there is no corresponding rule registered
#2315((NULL)) <z9ijff>; symcache; rspamd_symbols_cache_validate: symbol 'SEM_URIBL_FRESH15_UNKNOWN' has its score defined but there is no corresponding rule registered

MZ

**Comment by fatalbanana** [comment]
> #2315((NULL)) ; lua; ratelimit.lua:379: no servers are specified
> #2315((NULL)) ; lua; dmarc.lua:291: no servers are specified for dmarc stats

Expected default behaviour. Ratelimit requires Redis to work (and in default configuration is effectively disabled) & DMARC module requires Redis only for reports (and in default configuration does not store statistics).

https://rspamd.com/doc/modules/ratelimit.html
https://rspamd.com/doc/modules/dmarc.html

> #2315((NULL)) ; symcache; rspamd_symbols_cache_validate: symbol 'SEM_URIBL_UNKNOWN' has its score defined but there is no corresponding rule registered
> #2315((NULL)) ; symcache; rspamd_symbols_cache_validate: symbol 'SEM_URIBL_FRESH15_UNKNOWN' has its score defined but there is no corresponding rule registered
> #2315((NULL)) ; symcache; rspamd_symbols_cache_validate: symbol 'DBL' has its score defined but there is no corresponding rule registered

Answered at #377 - looks like a bug - probably this will get fixed sooner or later.

**Comment by MisterM74** [comment]
Hello

Ok , and this ?

#2315((NULL)) ; symcache; rspamd_symbols_cache_validate: symbol 'SEM_URIBL_UNKNOWN' has its score defined but there is no corresponding rule registered
#2315((NULL)) ; symcache; rspamd_symbols_cache_validate: symbol 'SEM_URIBL_FRESH15_UNKNOWN' has its score defined but there is no corresponding rule registered
#2315((NULL)) ; symcache; rspamd_symbols_cache_validate: symbol 'DBL' has its score defined but there is no corresponding rule registered

MZ

**Comment by fatalbanana** [comment]
Same thing as addressed above again. ;)
