### ISSUE TITLE
Webui via mod_proxy

### ISSUE THREAD

**Issue by Twilek-de** [vstakhov/rspamd#431]
I want to pass the Webui to a virtual subdirectory through mod_proxy on apache2. When I set the Proxypas and Reverseproxypass directives the Webpage shows up. But when I enter the password I get an Error saying "NULL". The Rspamd log says 

(controller) <49dbd4>; csession; rspamd_controller_error_handler: http error occurred: Not found
(controller) rspamd_http_router_finish_handler: path: //auth not found

I then tried to Map the URL which resultet in

(controller) rspamd_http_router_finish_handler: path: /cdnjs.cloudflare.com/ajax/libs/file-uploader/3.7.0/fineuploader.min.css not found
(controller) <e3bf6e>; csession; rspamd_controller_error_handler: http error occurred: Not found
(controller) rspamd_http_router_finish_handler: path: /maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css not found
(controller) <ec532e>; csession; rspamd_controller_error_handler: http error occurred: Not found
(controller) rspamd_http_router_finish_handler: path: /code.jquery.com/jquery-2.1.4.min.js not found
(controller) <ea0815>; csession; rspamd_controller_error_handler: http error occurred: Not found
(controller) rspamd_http_router_finish_handler: path: /maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js not found
(controller) <77ec69>; csession; rspamd_controller_error_handler: http error occurred: Not found
(controller) rspamd_http_router_finish_handler: path: /cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js not found
(controller) <52005f>; csession; rspamd_controller_error_handler: http error occurred: Not found
(controller) rspamd_http_router_finish_handler: path: /cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js not found
(controller) <0213ae>; csession; rspamd_controller_error_handler: http error occurred: Not found

Is there any way to do this properly?

**Comment by fatalbanana** [comment]
Something like this should work:

```
        RewriteEngine On
        <Location /rspamd>
           Order allow,deny
           Allow from all
        </Location>
        RewriteRule ^/rspamd/(.*) http://127.0.0.1:11334/$1 [P,L]
```

**Comment by Twilek-de** [comment]
No I think it won´t, because it would rewrite the /rspamd/ directory into a localhost adress which would not work when accessing the site from outside. What I want to do is be able to access the rspam interface from the internet via www.mysite.com/spam/ or something suchlike while using https. I think the only way to do this is via the proxy module.

**Comment by fatalbanana** [comment]
It's copied from the config I actually use so I believe it does work. :) mod_rewrite's `[P]` invokes mod_proxy.

**Comment by Twilek-de** [comment]
Wow, I forgot that I had disabled the proxy module again. I have now re-enabled the proxy and proxy_http mod and what can I say, it works beautifully!

Thanks!
