### ISSUE TITLE
strip ipv6 prefix

### ISSUE THREAD

**Issue by vixns** [vstakhov/rspamd#434]
in received headers, ipv6 addresses are prefixed, "[IPv6:2001:4b98..."
This "IPv6:" prefix should be stripped before IP based validations ( dns / spf ... )

**Comment by vstakhov** [comment]
Is it fixed for you?

**Comment by vixns** [comment]
> Le 29 nov. 2015 à 00:31, Vsevolod Stakhov <notifications@github.com> a écrit :
> 
> Is it fixed for you?

Yes, seems fixed, thanks.
