### ISSUE TITLE
SUSPICIOUS_RECIPS/SORTED_RECIPS leads to false positive

### ISSUE THREAD

**Issue by falstaff84** [vstakhov/rspamd#437]
It happend several times to me that a mailing list email gets sorted as a Spam email. I looked into some of these closer, and realized that often the recipts criteria lead to a high score. As far as I understand the SUSPICIOUS_RECIPS looks for similarities (what is the criteria here?), whereas SORTED_RECIPS shows for sorted recipients. Especially the second one seems not to be the case in my email. Sample email is attached. The To list only contains a single email address and the cc list is not sorted....
[suspicous_recips_false_positive.txt](https://github.com/vstakhov/rspamd/files/49286/suspicous_recips_false_positive.txt)

**Comment by vstakhov** [comment]
Well, I've added a workaround for those rules. But I'm really tired of gmime structures and need to rework them some day...
