### ISSUE TITLE
Regexps require carriage return (`\r`) before `$` ancor

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#438]
Why regexps require carriage return (`\r`) before `$` ancor while ignore it in other places?
~~~
------=_NextPart_001_0AB2_01D12B56.F2FE02D0
Content-Type: text/plain; charset="windows-1251"
Content-Transfer-Encoding: quoted-printable

=C8=ED=F4=EE=F0=EC=E0=F6=E8=FF =E2=EE =E2=EB=EE=E6=E5=ED=ED=EE=EC =F4=E0=E9=
=EB=E5

------=_NextPart_001_0AB2_01D12B56.F2FE02D0
~~~

This rule doesn't work (except WebUI scanning):
rspamd.local.lua
~~~lua
local reconf = config['regexp']
reconf['LOCAL_MS_ATTACHMENT_ONLY'] = '/^Информация во вложенном файле$/P'
~~~

This rule works:
rspamd.local.lua
~~~lua
local reconf = config['regexp']
reconf['LOCAL_MS_ATTACHMENT_ONLY'] = '/^Информация во вложенном файле\r$/P'
~~~

P.S. Are possible regexp flags described somewhere? In particular what `P` flag does?

**Comment by vstakhov** [comment]
Could you please check if this patch resolves your issue?

**Comment by moisseev** [comment]
It fixed the issue. Thanks!
Could you point me to some regexp flags description?

**Comment by fatalbanana** [comment]
They are documented here: https://rspamd.com/doc/modules/regexp.html

**Comment by moisseev** [comment]
Thanks!

**Comment by moisseev** [comment]
@vstakhov, would you please merge 09c3e1b into the `rspamd-1.0` branch if you don't plan to release 1.1 soon?
