### ISSUE TITLE
WebUI scan results: reject, but spam message in my mailbox

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#440]
`% uname -srovp`
`FreeBSD 10.1-RELEASE-p24 FreeBSD 10.1-RELEASE-p24 #0: Mon Nov  2 12:02:13 UTC 2015     ``root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  i386`
`% pkg info | grep ^rspamd`
`rspamd-1.0.10                  Fast spam filtering system`

When scanning suspicious message in WebUI (Scan menu) I have such scan result:

`Scan results:`
`reject	11.00/10.00	`
`HFILTER_HOSTNAME_UNKNOWN: 4.00`
`BAYES_SPAM: 3.00`
`HFILTER_HELO_UNKNOWN: 4.00`

but /var/log/rspamd/rspamd.log 

`2015-12-02 11:35:41 #33408(normal) <9362f3>; task; accept_socket: accepted connection from 127.0.0.1 port 42242`
`2015-12-02 11:35:41 #33408(normal) <9362f3>; task; rspamd_message_parse: loaded message; id: <2ED49D94DE0A7516CACF863BCF19FEB8@trening2015.ru>; queue-id: <E03FB1D444B2>`
`2015-12-02 11:35:44 #33408(normal) <9362f3>; task; rspamd_protocol_http_reply: id: `<2ED49D94DE0A7516CACF863BCF19FEB8@trening2015.ru>`, qid: <E03FB1D444B2>, ip: ``109.120.189.203, from: email@trening2015.ru, (default: F (no action): [2.99/10.00] [BAYES_SPAM]), len:` `197541, time: 2900.394ms real, 10.148ms virtual, dns req: 24,`

and

`% rspamc /tmp/test.eml `
`Results for file: /tmp/test.eml (0.830 seconds)`
`[Metric: default]`
`Spam: false`
`Score: 2.99 / 10.00`
`Action: no action`
`Symbol: BAYES_SPAM (2.99)[99.99%]`
`Message-ID: 2ED49D94DE0A7516CACF863BCF19FEB8@trening2015.ru`

**Comment by vstakhov** [comment]
That happens because rspamd failed to parse received headers I suppose but in case of MTA it used MTA information about host/ip and other stuff. Could you paste the headers of that particular message somewhere please?

**Comment by dehnli** [comment]
Sure. I sent e-mail to you.

**Comment by vstakhov** [comment]
Well, it seems that your MTA added some additional received headers. Hence, rspamd was unable to get the real sender's data. That's why HFILTER rules fired (they are a bit dumb about local mail I'm afraid).

**Comment by moisseev** [comment]
@dehnli, maybe you are using wrong text encoding when scanning with WebUI?
For instance, Thunderbird displays message sources in `Western` by default. To get sane results you have to switch it to `Unicode` before copy/paste to WebUI.

**Comment by dehnli** [comment]
@moisseev, thanks for reply.
Default encoding `Cyrillic (Windows)` 
I changed it to `Unicode` then copy/paste to WebUI. The scan result is the same:

`reject	12.00/10.00`	
`BAYES_SPAM: 3.00`
`HFILTER_HELO_UNKNOWN: 4.00`
`HFILTER_HOSTNAME_UNKNOWN: 4.00`
`DATE_IN_PAST: 1.00`
