### ISSUE TITLE
spf check when authenticated

### ISSUE THREAD

**Issue by vixns** [vstakhov/rspamd#443]
When sending myself an email, the R_SPF_SOFTFAIL	 symbol is added, but it shouldn't, as i'm sending thru an authenticated smtp session.

Received: from [IPv6:xxxxxxx] (unknown [IPv6:xxxxxx])
	by xxxx.xxx.xx (Postfix) with ESMTPSA id 0792CF11

IPs in received headers containing "with ESMTPSA" should be ignored by SPF checks

**Comment by xpunkt** [comment]
ESMTPSA is the trigger, should non ssl/tls be suppoted aswell ?

**Comment by fatalbanana** [comment]
Rspamd does not look for this information in `Received` headers, it is passed in via `User` parameter: https://rspamd.com/doc/architecture/protocol.html
