### ISSUE TITLE
HTTP error: 22, process fuzzy error

### ISSUE THREAD

**Issue by dnl555** [vstakhov/rspamd#446]
Hi , 

I'm using the 1.1.0-0~git118~b779108~jessie version of RspamD and I'm having problems with the fuzzy learning . 

When I run rspamc for fuzzy learning I always have an error in the first run: 

rspamc -w 20 -f 2 fuzzy_add < message.txt -P q1 -h 127.0.0.1:11334
Results for file: stdin (0.001 seconds)
HTTP error: 22, process fuzzy error

In second run, work as expected: 
rspamc -w 20 -f 2 fuzzy_add <  message.txt -P q1 -h 127.0.0.1:11334
Results for file: stdin (0.002 seconds)
success = true;

In logs, I have the error: 

rspamd[31379]: <>; ; accept_fuzzy_socket: got error while reading from socket: 107, Transport endpoint is not connected

Confs: 

worker-fuzzy.inc

    type = "fuzzy";
    bind_socket = "*:11335";
    hash_file = "${DBDIR}/fuzzy.db"
    expire = 90d;
    allow_update = "127.0.0.1";

fuzzy_check.conf:

    fuzzy_check {
    rule {
        # List of servers, can be an array or multi-value item
        servers = "localhost:11335";

        # Default symbol
        symbol = "FUZZY_UNKNOWN";

        # List of additional mime types to be checked in this fuzzy
        mime_types = "application/pdf";
        mime_types = ["application/*", "*/octet-stream", "*"];

        # Maximum global score for all maps
        max_score = 20.0;

        # Ignore flags that are not listed in maps for this rule
        skip_unknown = yes;

        # If this value is false, then allow learning for this fuzzy rule
        read_only = no;

        # Key for strict digests (default: "rspamd")
        fuzzy_key = "somebigrandomstring";

        # Key for fuzzy siphash (default: "rspamd")
        fuzzy_shingles_key = "anotherbigrandomstring";

        # maps
        fuzzy_map = {
        FUZZY_DENIED {
            # Maximum weight for this list
            max_score = 20.0;
            # Flag value
            flag = 1
        }
        FUZZY_PROB {
            max_score = 10.0;
            flag = 2
        }
        FUZZY_WHITE {
            max_score = 2.0;
            flag = 3
            }
        }
    }
    }

Thanks !

**Comment by vstakhov** [comment]
What if you change `servers = "localhost:11335"` to `servers = "127.0.0.1:11335"`?

**Comment by dnl555** [comment]
It works! Thanks! :)
