### ISSUE TITLE
rspamc must return an error if the delivery command failed

### ISSUE THREAD

**Issue by vadz** [vstakhov/rspamd#449]
I'm migrating a system using Exim + DSPAM to rspamd and so am trying to reuse more or less the same configuration, just replacing the use of `dspam` command with `rspamc`. While doing it, I made a mistake and omitted the recipient name, i.e. used something like this:

    /usr/bin/rspamc --mime --exec "/usr/sbin/exim -oi -oMr rspamd-scanned" --deliver $local_part --from $sender_address

which was resulting in error from exim command used because normally it should have been `/usr/sbin/exim -oi -oMr rspamd-scanned $local_part` and exim just gave an error message and exited with 1 without the required argument. However `rspamc` command itself just returned 0 exit code, meaning that all email was simply discarded and lost!

If I'm reading [the code](https://github.com/vstakhov/rspamd/blob/master/src/client/rspamc.c#L1257) correctly, the `GError` variable is passed all the way down to `rspamc_client_execute_cmd()` but all that ever happens to it there is that an error message can be printed (and even this is not done when the command being executed exits with non-0 return code) and the process always exits with 0 no matter what.

This is extremely bad as it can (and did) result in data loss. Errors really need to be handled.

**Comment by vstakhov** [comment]
Should be fixed in https://github.com/vstakhov/rspamd/commit/75a0c0ea96046f84540900e7a7aee49f391d200a
