### ISSUE TITLE
Mysterious failures with dovecot antispam plugin

### ISSUE THREAD

**Issue by vadz** [vstakhov/rspamd#450]
I'm trying to allow training rspamd (1.1.0-0~git111~e3a8756~wheezy version) by moving the messages in (or out) Junk folder using Dovecot [antispam plugin](http://wiki2.dovecot.org/Plugins/Antispam) with the following configuration:

```
  antispam_spam = Junk
  antispam_backend = mailtrain
  antispam_mail_sendmail = /usr/bin/rspamc
  antispam_mail_spam = learn_spam
  antispam_mail_notspam = learn_ham
  antispam_mail_sendmail_args = -h;localhost:11334
```

For some reason this results in only the following in rspamd logs:

```
2015-12-15 02:01:18 #15560(normal) <12d1d6>; task; accept_socket: accepted connection from 127.0.0.1 port 58342
2015-12-15 02:01:18 #15560(normal) <12d1d6>; task; rspamd_worker_body_handler: cannot handle request: invalid command:
```

I've confirmed, using `strace`, that the correct command is executed:

```
[pid 27864] execve("/usr/bin/rspamc", ["/usr/bin/rspamc", "-h", "localhost:11334", "learn_spam"], [/* 13 vars */]) = 0
```

and the same command executed directly from the command line works fine.

Would you have any idea what is going wrong here and how could I fix it or at least debug it further? TIA!

**Comment by vadz** [comment]
I'm continue struggling with this, I just don't understand what's going on here. I confirmed, using wireshark, that `POST /learnspam` is done by the client, as expected, but the server still says "invalid command" without any more details. Even at the "debug" logging level I only get the following in the logs:
```
#32305(normal) <5be97b>; task; accept_socket: accepted connection from 127.0.0.1 port 38980
#32305(normal) <5be97b>; task; rspamd_worker_body_handler: cannot handle request: invalid command:
#32305(normal) <5be97b>; task; rspamd_task_process: task is processed
#32305(normal) <5be97b>; task; rspamd_protocol_write_reply: writing reply to client
#32305(normal) <5be97b>; task; rspamd_worker_finish_handler: normally closing connection from: 127.0.0.1
#32305(normal) <5be97b>; task; rspamd_task_free: free pointer 0000000000D30240
```

**Comment by vadz** [comment]
OK, sorry for flooding but I think I finally found something: it's related to `bind_socket` in some strange way. If I remove all its other occurrences, things seem to work fine, but if I use explicit `bind_socket` for the normal and controller workers to make them listen on the loopback and LAN interfaces only (but not the WAN one), things break down.

Separately, there seems to be something weird with the `bind_socket` location in the configuration too: it's my understanding that having it inside the `worker` section of `rspamd.conf` itself or the `worker-{normal,controller}.inc` file included from it should behave identically, but this doesn't seem to be the case... The behaviour also doesn't conform to [the documentation](https://rspamd.com/doc/workers/) which states that multiple `bind_socket` options should work, whereas, in fact, if I have this in the top level file:
```
worker {
    bind_socket = "127.0.0.1:11334";
    bind_socket = "192.168.1.1:11334";
    .include "$CONFDIR/worker-controller.inc"
}
```
the second one seems to be just totally ignored and `netstat` shows the listening socket on `127.0.0.1` only. But if I move the second line into `worker-controller.inc`, the main process can indeed be seen listening on both interfaces.

Can this really be the right behaviour? It seems to me all this is very buggy, but I could be missing something here, of course...

**Comment by vstakhov** [comment]
Thank you, I'll check your assumption soon.

**Comment by dpavlotzky** [comment]
@vadz I am seeing the same issue. I am not exactly ure what you mean by 

> its other occurrences

Which one did you leave intact?

**Comment by dpavlotzky** [comment]
Never mind. I had spamc talking to the wrong port...

**Comment by fatalbanana** [comment]
Multiple bind sockets seem to work correctly at normal worker & the controller at least these days: place for these is `local.d`.
