### ISSUE TITLE
Annoying 0-sized magic.mgc file creation

### ISSUE THREAD

**Issue by vadz** [vstakhov/rspamd#451]
Running almost any `rspamc` command, even something trivial such as `rspamc uptime` creates a 0-sized `magic.mgc` file in the current directory.

This is not really harmful, but is still quite annoying. Searching for this file in the sources didn't find anything, just where exactly is this coming from?

**Comment by vstakhov** [comment]
This should be fixed by https://github.com/vstakhov/rspamd/commit/d4f8010847e1a509f46bb038a80be64385687e96

**Comment by vadz** [comment]
I can confirm this is fixed with `1.1.0-0~git111~e3a8756~wheezy` package, thanks.
