### ISSUE TITLE
invalid message-id

### ISSUE THREAD

**Issue by vixns** [vstakhov/rspamd#454]
Since last nightly build, many messages IDs no longer validate, for example :  

Message-Id : `<Kdtx8zQaE6U9gDtKIHpCg.1450621271961@postal.12bbb5635878>`

X-Spamd-Result : default: False [10.49 / 15.00] HFILTER_HELO_IP_A(2.00) INVALID_MSGID(5.00) BAYES_SPAM(2.99) HFILTER_MID_NORES_A_OR_MX(0.50) R_SPF_SOFTFAIL(0.00)

**Comment by vstakhov** [comment]
Does the error persist if you add `disable_hyperscan = true;` to the `options` section?

**Comment by vixns** [comment]
no

**Comment by vstakhov** [comment]
Ok, so if I add this message id to any message it should trigger this issue, right?

**Comment by vixns** [comment]
right

**Comment by vstakhov** [comment]
I tried to reproduce it on https://paste.rspamd.com/1J1N

But got the following symbols only:

```
# rspamc -p test.eml
Results for file: test.eml (0.133 seconds)
[Metric: default]
Spam: false
Score: 10.00 / 15.00
Action: add header
Symbol: DATE_IN_PAST (1.00)
Symbol: HFILTER_MID_NORES_A_OR_MX (0.50)
Symbol: ONCE_RECEIVED (1.00)
Symbol: RAMBLER_URIBL (4.50)[movimento.com.uribl.rambler.ru]
Symbol: R_PARTS_DIFFER (3.00)[0%]
Urls: ["movimento.com"]
Message-ID: Kdtx8zQaE6U9gDtKIHpCg.1450621271961@postal.12bbb5635878
```

I'm using out-of-the box rspamd on ubuntu trusty.

**Comment by vstakhov** [comment]
Could you run this message in your system with debug logs enabled please (and without `disable_hyperscan`)

**Comment by vixns** [comment]
2015-12-20T16:38:08.56832 2015-12-20 17:38:08 #2664(hs_helper) <09386c>; main; rspamd_fork_worker: starting hs_helper process 2664
2015-12-20T16:38:08.56858 2015-12-20 17:38:08 #2664(hs_helper) <efef60>; re_cache; rspamd_re_cache_is_valid_hyperscan_file: cannot read hyperscan cache file /var/lib/rspamd//3f0fe080efff109f4f50e0ff509fe0d080afdfaf5fff6f4faf10ff80e0902fdf.hs: Bad file descriptor
2015-12-20T16:38:08.57045 2015-12-20 17:38:08 #18147(main) <09386c>; main; rspamd_cld_handler: hs_helper process 2664 terminated abnormally by signal: 4 but NOT created core file


ls -al /var/lib/rspamd/3f0fe080efff109f4f50e0ff509fe0d080afdfaf5fff6f4faf10ff80e0902fdf.hs
-rw------- 1 _rspamd _rspamd 0 déc.  20 17:42 /var/lib/rspamd/3f0fe080efff109f4f50e0ff509fe0d080afdfaf5fff6f4faf10ff80e0902fdf.hs

I was thinking about fs issue, but still have the same after rebooting, fsck + moving /var/lib/rspamd on another disk / fs

**Comment by vstakhov** [comment]
This signal means unsupported CPU instruction. Are you using i386 or amd64?

**Comment by vixns** [comment]
i386

**Comment by vstakhov** [comment]
Yes, i386 is likely broken as it assumes minimum SandyBridge architecture. I had no chance to fix it I'm afraid.

**Comment by vixns** [comment]
Ok, not a good news, you may totally discard hyperscan on i386.
For now i'm keeping `disable_hyperscan = true;` in the options.inc file and plan a kernel upgrade to amd64 soon (hopefully, it's a xen vm on amd64 hardware)

**Comment by vixns** [comment]
Switched to amd64 ( thanks to debian multiarch ), I no longer have this issue.

**Comment by vstakhov** [comment]
Great, I'll try to switch off hyperscan for all but amd64 platform to avoid confusion in future.

**Comment by denji** [comment]
@vstakhov Why you want to disable hyperscan on amd64 ?

**Comment by vstakhov** [comment]
I'm going to disable hyperscan for all platforms with the **exception** of amd64

**Comment by vstakhov** [comment]
Well, I've enabled hyperscan for only x86_64 and for `trusty`, `vivid`, `wily` and `jessie` distributions.
