### ISSUE TITLE
threshold for reject

### ISSUE THREAD

**Issue by bax-** [vstakhov/rspamd#457]
Where do I set the threshold when a message should be rejected?
I didn't find anything about this in the documentation…

**Comment by vstakhov** [comment]
https://rspamd.com/doc/configuration/metrics.html

**Comment by bax-** [comment]
Thanks.
But how should I proceed if I just want mails to be scored but not rejected?
I want to use sieve to do that.
But if I delete the `reject` action my headers don't indicate the max score anymore:
'X-Spamd-Result: default: True [23.99 / 0.00] […]'

**Comment by vstakhov** [comment]
In rmilter, you can also specify `spamd_never_reject` to disable reject action completely. Read more at https://rspamd.com/rmilter/#spamd-section

**Comment by bax-** [comment]
That's what I was looking for, thanks!
Maybe an option for setting the max score would also be nice though.

**Comment by fatalbanana** [comment]
By setting the max score you mean defining an own score at which mail should be rejected?- in which case, you could just raise reject score in rspamd metrics.

**Comment by bax-** [comment]
I was thinking about choosing the max score which is added in the header (like `X-Spamd-Result: default: False [-4.38 / 15]` without setting a reject score.
Something like a `max score` action.
Then I would have a choice to reject only by dovecot's sieve options and change that behavior quickly on the go.

**Comment by fatalbanana** [comment]
But you could just set `reject` score as desired and not honour the suggestion to actually reject? (as with rmilter's `spamd_never_reject` option).

If you want to reject spam with sieve filter: don't: you will generate backscatter (discarding the mail is fine :) but rejecting at SMTP time would be better since this is transparent to senders of filtered mail).

**Comment by bax-** [comment]
@fatalbanana 
Yes, this is what I will do now.

Of course you are right. I was thinking "discard" when I wrote "reject".

**Comment by Tetsumaki** [comment]
@vstakhov write :
> In rmilter, you can also specify spamd_never_reject to disable reject action completely. Read more at https://rspamd.com/rmilter/#spamd-section

Hello.
Similar method is possible with rspamd_proxy?
Thanks.

**Comment by fatalbanana** [comment]
@Tetsumaki not at this time AFAIK. You could however remove `reject` action from metric by redefining `actions {}` in `override.d/metrics.conf`.

**Comment by Tetsumaki** [comment]
Thanks @fatalbanana

**Comment by azurit** [comment]
@fatalbanana this doesn't work from version 1.7.0, any hints?

**Comment by azurit** [comment]
Well, it does work but in headers it is showing "[<spam_score> / 15]" instead of "[<spam_score> / 6]" (when the only enabeld action is add_header, so maximum score is 6). This was working fine before 1.7.0.

**Comment by tresh** [comment]
@azurit I think it just moved to `override.d/actions.conf`, at least that's how it works for me.
