### ISSUE TITLE
rspamc stat: Broken pipe

### ISSUE THREAD

**Issue by bax-** [vstakhov/rspamd#458]
Wie I run `rspamc stat`I get the following output:

```
Results for command: stat (0.000 seconds)
IO write error: Broken pipe

```

This is my `rspamd.conf` (I'm on FreeBSD):

```
.include "$CONFDIR/common.conf"

options {
    pidfile = "$RUNDIR/rspamd.pid";
    .include "$CONFDIR/options.inc"
}

logging {
    type = "file";
    filename = "$LOGDIR/rspamd.log";
    .include "$CONFDIR/logging.inc"
}

worker {
    #bind_socket = "*:11333";
    bind_socket = "/var/run/rspamd/rspamd.sock mode=0666 owner=nobody";
    .include "$CONFDIR/worker-normal.inc"
}

worker {
    #bind_socket = "localhost:11334";
    bind_socket = "/var/run/rspamd/rspamc.sock mode=0666 owner=nobody";
    .include "$CONFDIR/worker-controller.inc"
}

```

Anything I'm missing?

**Comment by vstakhov** [comment]
I suppose you have broken IPv6 stack, but your resolver tells that `localhost` is `::1`. Does the issue disappear when you add `-h 127.0.0.1` to `rspamc`?

**Comment by bax-** [comment]
This command works:
rspamc -h /var/run/rspamd/rspamc.sock stat
I guess I will have to change my dovecot anti spam args as well?

**Comment by vstakhov** [comment]
If you change the default configuration then you obviously need to change the `rspamc` command line invocation.

**Comment by skibbipl** [comment]
BTW, how to connect with `rspamc` on IPv6 interface on localhost. Whenever I try to connect with this command I get this error:
```
rspamc -h ::1:11334 -P <password> stat
Results for command: stat (0.000 seconds)
IO write error: Socket operation on non-socket
```
rspamd listens on IPv6:
```
netstat -an|grep 11334
tcp6       0      0 ::1:11334               :::*                    LISTEN
```
Happy New Year!

**Comment by fatalbanana** [comment]
@skibbipl : rspamc -h [::1]:11334
