### ISSUE TITLE
Status of Redis implementation

### ISSUE THREAD

**Issue by bax-** [vstakhov/rspamd#459]
What is the status of the Redis implementation?
I didn't find that much information in the documentation about it's purpose and how to enable it.
At what server size is it recommended / will there be any profit on very small servers?
I guess it doesn't yet interact with rmilter?

**Comment by vstakhov** [comment]
There won't likely be any profit comparing to sqlite. Redis support is somehow planned feature, so I might push for it before 1.1 release.

**Comment by bax-** [comment]
I see, thanks for the info!

**Comment by qk4l** [comment]
Please check this page https://rspamd.com/doc/configuration/redis.html
