### ISSUE TITLE
inconsistent headers

### ISSUE THREAD

**Issue by vixns** [vstakhov/rspamd#463]
Using latest nightly, X-Spam header is "yes" when message was first greylisted, even if X-Spamd-Result is "False".

````
X-Spamd-Result : default: False [6.37 / 15.00] BAYES_SPAM(0.87) HFILTER_MID_NORES_A_OR_MX(0.50) HFILTER_HOSTNAME_UNKNOWN(4.00) HFILTER_HELO_IP_A(1.00) R_SPF_SOFTFAIL(0.00)
X-Spamd-Scan-Time : 0.26
X-Spam : yes
X-Spamd-Server : 127.0.0.1
````

**Comment by xpunkt** [comment]
add header is default 6
reject is default 15

so if add header is the score trigger for spam accept it works as designed, i just hope it is so

**Comment by vixns** [comment]
Your right, we are in the "add header" case, the message is tagged as spam.
So, isn't "X-Spamd-Result : default: False " wrong ?

**Comment by fatalbanana** [comment]
AFAIU `true` in rmilter's `X-Spam` header indicates `add header` signal from rspamd and `X-Spamd-Result` is showing (legacy protocol equivalent of) rspamd's `is_spam` result which signifies the `reject` action (if you haven't touched `spamd_never_reject` you will never see that): https://rspamd.com/doc/architecture/protocol.html
