### ISSUE TITLE
Integrated OpenDkim?

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#475]
Hello
Embed OpenDkim with RSPamd is possible?
Thank you
Mz

**Comment by vstakhov** [comment]
No way. There is a sane implementation of DKIM spec in rspamd, why do you need OpenDKIM?

**Comment by MisterM74** [comment]
to encrypt my outgoing mail messages, as many spam message comes in, even with the proper SPF function and neutral

**Comment by vstakhov** [comment]
Rmilter can sign outgoing messages. Rspamd is not intended for this purposes as it has no functions to modify messages.

**Comment by MisterM74** [comment]
ok, rmilter all the time? does not close all the topic now because the concern is that when I send messages I see through the local server and not, by not identifying, if you understand what mean, thank you

**Comment by MisterM74** [comment]
it is in opendkim manage outbound IP with this file if:

TrustedHosts

there would be the opportunity to do the same with rmilter?

Mz

**Comment by wackerm** [comment]
yes, in rmilter.conf there is the option `sign_network` 

See in http://rspamd.com/rmilter/#dkim-section
