### ISSUE TITLE
Always got "IO read error: unexpected EOF"

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#479]
Almost all the emails I tested got this EOF error, except one, which is "sample-spam.txt".

apple.eml (got EOF error)
https://www.dropbox.com/s/yjl33kkg1rg3x9i/apple.eml?dl=0

sample-spam.txt (correct, return score)
https://www.dropbox.com/s/3f6txy1a0m0pbi2/sample-spam.txt?dl=0

Don't know why it returned EOF error. Could someone tell me why ? Thanks !!

I built from github repo, and the Head is a270611.
cmd : 
rspamd : src/rspamd --insecure
rspamc : src/client/rspamc /tmp/apple.eml

Following is my setting 
worker {                                                                                                                                                                  
    bind_socket = "*:11333";  
    .include "/usr/local/etc/rspamd/worker-normal.inc"
}

logging {
    type = "file";       
    filename = "/usr/local/etc/rspamd/rspamd.log";
    .include "/usr/local/etc/rspamd/logging.inc"
} 
worker-normal.inc
type = "normal";
mime = true;
task_timeout = 8s;

**Comment by mozzan** [comment]
It seems that I didn't set the installation of rspam correctly. 
I followed this post 
http://www.perlhipster.com/2014/05/how-to-compile-install-rspamd-webgui.html
The error doesn't appear anymore.

**Comment by fatalbanana** [comment]
That article is dated unfortunately. Contemporary instructions for enabling web interface are here: https://rspamd.com/webui

**Comment by essandess** [comment]
See https://github.com/rspamd/rspamd/issues/479. I attribute my problem with this to a build configuration issue.
