### ISSUE TITLE
Issue regarding max_score for groups

### ISSUE THREAD

**Issue by rafaelabdo** [vstakhov/rspamd#482]
It seems that this kind of configuration for groups, inside of metric scope, isn't working properly. See details below:

Config:

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
metric {
    name = "default";
...
    group {
        name = "phishing";
        max_score = 6.0;
...
        }
    }
...
}
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Result:

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[Metric: default]
...
Symbol: PHISHING (13.18)[XXXX.com.br, XXXX.com.br, XXXX.com.br, XXXX.com.br, XXXX.com.br]
...
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by vstakhov** [comment]
Ow, that was a bad error. It should be fixed now.

**Comment by rafaelabdo** [comment]
Yes, fixed. Thanks.
