### ISSUE TITLE
Issue with SPF check 

### ISSUE THREAD

**Issue by dnl555** [vstakhov/rspamd#483]
Hi , I think there is something wrong with SPF module.  I found some SPF FAIL's when the SPF is OK . 

Example with domain eu-west-1.amazonses.com: 
eu-west-1.amazonses.com descriptive text "v=spf1 include:amazonses.com -all"
eu-west-1.amazonses.com descriptive text "spf2.0/pra include:amazonses.com -all"

I configured 0 as score in R_SPF_FAIL to test . 

Return of rmilter: 
 rmilter[2877]: spamdscan: scan qid: <41E1DE0CFC>, mid: <000001524245b237-56b6cb3a-142f-4d92-86d4-73d5a96f0ffa-000000@eu-west-1.amazonses.com>, 0.513548, 127.0.0.1, metric: default: [10.760000 / 60.000000], symbols: R_DKIM_ALLOW(0.00), RWL_MAILSPIKE_POSSIBLE(0.00), R_PARTS_DIFFER(2.97), DMARC_POLICY_ALLOW(-0.50), BAYES_SPAM(2.99), R_SPF_FAIL(0.00), FUZZY_PROB(5.00), FORGED_SENDER(0.30), RCVD_IN_DNSWL_LOW(0.00)

The IP that amazon used was 54.240.6.123 with the mailfrom 000001524245b237-56b6cb3a-142f-4d92-86d4-73d5a96f0ffa-000000@eu-west-1.amazonses.com.  

Testing in http://www.kitterman.com/test5.py : 

Input accepted, querying now...

Mail sent from this IP address: 54.240.6.123 
Mail from (Sender): 000001524245b237-56b6cb3a-142f-4d92-86d4-73d5a96f0ffa-000000@eu-west-1.amazonses.com 

Results - PASS sender SPF authorized

**Comment by vstakhov** [comment]
Isn't it fixed?

**Comment by dnl555** [comment]
Hi Vstakhov , I did'nt see more false positives with SPF Fail . Thanks !

**Comment by dnl555** [comment]
Hi, I got the same problem with 1.1.0-1 stable: 

metric: default: [5.790000 / 60.000000], symbols: MIME_HTML_ONLY(1.00), SUBJ_ALL_CAPS(0.50), HFILTER_HELO_NORES_A_OR_MX(0.30), R_SPF_FAIL(4.00)

from=<sejatop@tfs.com.br>
IP of connection: 189.42.132.178

spf of tfs.com.br: 
tfs.com.br descriptive text "v=spf1 mx a -all"

http://www.kitterman.com/test5.py
Input accepted, querying now...  Mail sent from this IP address: 189.42.132.178  Mail from (Sender): sejatop@tfs.com.br   Results - PASS sender SPF authorized

**Comment by xpunkt** [comment]
From: header must not be used for spf testing, if rspamd still does this its brokken

to developpers, hov does one define envelope_senders_header in rspamd ?

in spamassassin its in local.cf

always_trust_envelope_sender 1
envelope_sender_header Return-Path

for postfix

**Comment by xpunkt** [comment]
check for Sender-ID badnees in libspf2

ask senders to remove spf2.0/pra include:amazonses.com -all in dns

in rspamd ignore it

**Comment by vstakhov** [comment]
@dnl555: I can't reproduce your issue. Rspamd gives `R_SPF_ALLOW` for this combination of IP and from. Perhaps, you have DNS issues so rspamd fails to resolve some components of SPF record?

**Comment by rafaelabdo** [comment]
@vstakhov:

As @dnl555 told us, I guess that there is some inconsistency. We've repeated the same validation many times using different servers and dns servers as well. It seems that rspamd is answering different things for the same validation, see it below:

root@debian-wheezy:~# rspamc -F mail@domain.com.br -i x.x.x.x < ~/spam.eml | grep SPF | grep Symbol
Symbol: R_SPF_ALLOW (-1.50)[mx]
root@debian-wheezy:~# rspamc -F mail@domain.com.br -i x.x.x.x < ~/spam.eml | grep SPF | grep Symbol
Symbol: R_SPF_ALLOW (-1.50)[mx]
root@debian-wheezy:~# rspamc -F mail@domain.com.br -i x.x.x.x < ~/spam.eml | grep SPF | grep Symbol
Symbol: R_SPF_FAIL (1.00)[all]
root@debian-wheezy:~# rspamc -F mail@domain.com.br -i x.x.x.x < ~/spam.eml | grep SPF | grep Symbol
Symbol: R_SPF_ALLOW (-1.50)[mx]
root@debian-wheezy:~# rspamc -F mail@domain.com.br -i x.x.x.x < ~/spam.eml | grep SPF | grep Symbol
Symbol: R_SPF_FAIL (1.00)[all]
root@debian-wheezy:~# rspamc -F mail@domain.com.br -i x.x.x.x < ~/spam.eml | grep SPF | grep Symbol
Symbol: R_SPF_ALLOW (-1.50)[mx]
root@debian-wheezy:~# rspamc -F mail@domain.com.br -i x.x.x.x < ~/spam.eml | grep SPF | grep Symbol
Symbol: R_SPF_FAIL (1.00)[all]
root@debian-wheezy:~# rspamc -F mail@domain.com.br -i x.x.x.x < ~/spam.eml | grep SPF | grep Symbol
Symbol: R_SPF_ALLOW (-1.50)[mx]

Just to be sure, I've tried to resolve dns more than once to confirm that server was answering the same thing every time like so:

root@debian-wheezy:~# host -t txt domain.com.br
domain.com.br descriptive text "v=spf1 mx a -all"
root@debian-wheezy:~# host -t txt domain.com.br
domain.com.br descriptive text "v=spf1 mx a -all"
root@debian-wheezy:~# host -t txt domain.com.br
domain.com.br descriptive text "v=spf1 mx a -all"
root@debian-wheezy:~# host -t txt domain.com.br
domain.com.br descriptive text "v=spf1 mx a -all"
root@debian-wheezy:~# host -t txt domain.com.br
domain.com.br descriptive text "v=spf1 mx a -all"
root@debian-wheezy:~# host -t txt domain.com.br
domain.com.br descriptive text "v=spf1 mx a -all"

**Comment by vstakhov** [comment]
I think I know the reason. It is related to IPv4/v6 ambiguity most likely.

**Comment by rafaelabdo** [comment]
I don't know if it's useful but I've repeated the test with no ipv6 enabled and the result was the same.

**Comment by vstakhov** [comment]
Could you please test the following patch?

**Comment by rafaelabdo** [comment]
It seems that's solved. There's no fault in 30 attempts:

Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]
Symbol: R_SPF_ALLOW (-1.50)[mx]

**Comment by dnl555** [comment]
Thanks @vstakhov and @rafaelabdo . It seems that it's solved now.
