### ISSUE TITLE
Problem with local fuzzy storage

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rspamd#485]
Hi.
I'm trying to configure local fuzzy storage, but when i'm starting rspamd i got a lot of erros like this:

> Jan 19 18:35:03 mx01 rspamd[46373]: <>; ; accept_fuzzy_socket: got error while reading from socket: 107, Transport endpoint is not connected

OS:
> [root@mx01 ~]# cat /etc/redhat-release
> CentOS Linux release 7.2.1511 (Core)

Rspamd version:
>rspamd-1.0.11-1.1.x86_64

My configs:
**/etc/systemd/system/rspamd.socket**
>[Unit]
>Description=rapid spam filtering system
>[Socket]
>ListenStream=11333
>ListenStream=[::1]:11334
>ListenStream=11335
>BindIPv6Only=both

**/etc/rspamd/rspamd.conf**
> ...
> worker {
>    bind_socket = "systemd:2";
>    .include "$CONFDIR/worker-fuzzy.inc"
>}
> ...

**/etc/rspamd/worker-fuzzy.inc**
>type = "fuzzy";
>count = 1;
>hash_file = "${DBDIR}/fuzzy.db";
>expire = 90d;
>allow_update = "127.0.0.1";
>allow_map = "127.0.0.1";

**/etc/rspamd/modules.d/fuzzy_check.conf**
> ... 
>rule {
>        servers = "127.0.0.1:11335";
>        symbol = "FUZZY_UNKNOWN";
>        mime_types = ["application/*"];
>        max_score = 20.0;
>        read_only = no;
>        skip_unknown = yes;
>        fuzzy_map = {
>            LOCAL_FUZZY_DENIED {
>                max_score = 20.0;
>                flag = 1;
>            }
>            LOCAL_FUZZY_PROB {
>                max_score = 10.0;
>                flag = 2;
>            }
>            LOCAL_FUZZY_WHITE {
>                max_score = 2.0;
>                flag = 3;
>            }
>        }
>    }

How can i determine the cause of this errors?

**Comment by vstakhov** [comment]
Fuzzy uses UDP for operations. I don't know how it plays with systemd. Perhaps, it won't work. I have no experiences with systemd, so I cannot answer to your question.

**Comment by fatalbanana** [comment]
You could use `ListenDatagram` in place of `ListenStream` for UDP.

**Comment by damned-trooper** [comment]
Thank you very much.
I did not think about UDP and ListenDatagram.
Sorry.

**Comment by damned-trooper** [comment]
Excuse me, but now i get another problem.
When i try to run rspamc fuzzy_add i got this error:
>[root@mx01 fuzzy_spam]# rspamc -h localhost -f 1 -w 10 fuzzy_add 1.eml
>Results for file: 1.eml (0.088 seconds)
>HTTP error: 22, process fuzzy error

Details in /var/log/rspamd:
>Jan 19 19:24:21 mx01 rspamd[47651]: <79419b>; task; fuzzy_cmd_from_text_part: loading shingles with key ff30ef0fcfdf3fc0f0b06f80b0ef7f40
>Jan 19 19:24:21 mx01 rspamd[47651]: <79419b>; task; fuzzy_cmd_from_text_part: loading shingles with key a0e08f7f3020b0009fef6f8f9f5060a0
>Jan 19 19:24:21 mx01 rspamd[47650]: <92a47a>; radix; radix_find_compressed: trying to find key: 00000000000000000000fffff0000010
>Jan 19 19:24:21 mx01 rspamd[47650]: <92a47a>; radix; radix_find_compressed: finding in the compressed node: 0000000000000001 at level 0
>Jan 19 19:24:21 mx01 rspamd[47651]: <79419b>; task; fuzzy_controller_io_callback: cannot process fuzzy hash for message <bbd501d15258$2532a210$b17dd667@aqlofxd>, list LOCAL_FUZZY_DENIED:1
>Jan 19 19:24:21 mx01 rspamd[47651]: <79419b>; task; fuzzy_controller_io_callback: cannot process fuzzy hash for message <bbd501d15258$2532a210$b17dd667@aqlofxd>, list FUZZY_DENIED:1
>Jan 19 19:24:21 mx01 rspamd[47651]: <79419b>; task; rspamd_task_free: free pointer 0000000000FE2240
>Jan 19 19:24:21 mx01 rspamd[47651]: <00e497>; csession; rspamd_controller_finish_handler: destroy session 0000000000FF2040

**Comment by damned-trooper** [comment]
After upgrade to 1.1 version nothing has change:
>[root@mx01 fuzzy_spam]# rspamc -h localhost -f 1 -w 10 fuzzy_add 1.eml
>Results for file: 1.eml (0.066 seconds)
>HTTP error: 22, process fuzzy error

Logs:
>Jan 19 20:02:31 mx01 rspamd[48662]: <d312db>; csession; rspamd_controller_check_password: allow unauthorized connection from a trusted IP ::1
>Jan 19 20:02:31 mx01 rspamd[48662]: <f399fc>; task; rspamd_message_parse: loaded message; id: <bbd501d15258$2532a210$b17dd667@aqlofxd>; queue-id: <undef>
>Jan 19 20:02:31 mx01 rspamd[48662]: <f399fc>; task; fuzzy_controller_io_callback: cannot process fuzzy hash for message <bbd501d15258$2532a210$b17dd667@aqlofxd>, list LOCAL_FUZZY_DENIED:1, error: 403
>Jan 19 20:02:31 mx01 rspamd[48662]: <f399fc>; task; fuzzy_controller_io_callback: cannot process fuzzy hash for message <bbd501d15258$2532a210$b17dd667@aqlofxd>, list FUZZY_DENIED:1, error: 403

**Comment by vstakhov** [comment]
This means that your fuzzy worker refuses updates from the controller. Please check the example at https://rspamd.com/doc/workers/fuzzy_storage.html and `allow_update` setting in particular.

**Comment by damned-trooper** [comment]
This option exists in my config:
**/etc/rspamd/worker-fuzzy.inc**
>type = "fuzzy";
>count = 1;
>hash_file = "${DBDIR}/fuzzy.db";
>expire = 90d;
>allow_update = "127.0.0.1";
>allow_map = "127.0.0.1";

By the way is that correct method to set parameters for fuzzy worker 'via .include "$CONFDIR/worker-fuzzy.inc"'?
I have copied skeleton from other workers.

**Comment by vstakhov** [comment]
You should also include ::1 as the possible addr. Allow map is not supported (I've fixed that in docs).

**Comment by damned-trooper** [comment]
New config:

>type = "fuzzy";
>count = 1;
>hash_file = "${DBDIR}/fuzzy.db";
>expire = 90d;
>allow_update = "127.0.0.1";
>allow_update = "::1";

Same result:

>[root@mx01 fuzzy_spam]# rspamc -h localhost -P lcAd2012 -f 1 -w 10 fuzzy_add 1.eml
>Results for file: 1.eml (0.066 seconds)
>HTTP error: 22, process fuzzy error

Log:
>Jan 19 21:32:30 mx01 rspamd[49559]: <62591c>; csession; rspamd_controller_check_password: allow unauthorized connection from a trusted IP ::1
>Jan 19 21:32:30 mx01 rspamd[49559]: <f96d6a>; task; rspamd_message_parse: loaded message; id: <bbd501d15258$2532a210$b17dd667@aqlofxd>; queue-id: <undef>
>Jan 19 21:32:30 mx01 rspamd[49559]: <f96d6a>; task; fuzzy_controller_io_callback: cannot process fuzzy hash for message <bbd501d15258$2532a210$b17dd667@aqlofxd>, list LOCAL_FUZZY_DENIED:1, error: 403
>Jan 19 21:32:30 mx01 rspamd[49559]: <f96d6a>; task; fuzzy_controller_io_callback: cannot process fuzzy hash for message <bbd501d15258$2532a210$b17dd667@aqlofxd>, list FUZZY_DENIED:1, error: 403

May be something wrong with my controller worker?
**/etc/rspamd/worker-controller.inc**
>type = "controller";
>count = 1;
>password = "$1$6t...STRING...4wb";
>enable_password = "$1$6t...STRING...4wb";
>secure_ip = "127.0.0.1";
>secure_ip = "::1";
>static_dir = "${WWWDIR}";

**Comment by vstakhov** [comment]
Do you have `read_only = no` in your `fuzzy_check` plugin configuration?

**Comment by damned-trooper** [comment]
Yes. I set it for local rule definition.
Here is my fuzzy plugin config:

**/etc/rspamd/modules.d/fuzzy_check.conf**
>    .include(try=true,priority=1) "${DBDIR}/dynamic/fuzzy_check.conf"
>    min_bytes = 300;
>    rule {
>        servers = "rspamd.com:11335";
>        encryption_key = "icy63itbhhni8bq15ntp5n5symuixf73s1kpjh6skaq4e7nx5fiy";
>        symbol = "FUZZY_UNKNOWN";
>        mime_types = ["application/*"];
>        max_score = 20.0;
>        read_only = yes;
>        skip_unknown = yes;
>        fuzzy_map = {
>            FUZZY_DENIED {
>                max_score = 20.0;
>                flag = 1;
>            }
>            FUZZY_PROB {
>                max_score = 10.0;
>                flag = 2;
>            }
>            FUZZY_WHITE {
>                max_score = 2.0;
>                flag = 3;
>            }
>        }
>    }
>    rule {
>        servers = "127.0.0.1:11335";
>        symbol = "LOCAL_FUZZY_UNKNOWN";
>        mime_types = ["application/*"];
>        max_score = 20.0;
>        **read_only = no;**
>        skip_unknown = yes;
>        fuzzy_map = {
>            LOCAL_FUZZY_DENIED {
>                max_score = 20.0;
>                flag = 1;
>            }
>            LOCAL_FUZZY_PROB {
>                max_score = 10.0;
>                flag = 2;
>            }
>            LOCAL_FUZZY_WHITE {
>                max_score = 2.0;
>                flag = 3;
>            }
>        }
>    }

**Comment by fatalbanana** [comment]
I wasn't able to replicate your exact issue (and tested on wrong OS unfortunately) but it looks to me that fuzzy+socket activation is issuey indeed - try setting fuzzy worker's bind_socket to something like `127.0.0.1:11335` (and drop the related entry from .socket file) and see if that helps?

**Comment by damned-trooper** [comment]
Yes.
It was was ipv6 only socket.
After setting to v4 all works fine.
Thank you.
