### ISSUE TITLE
How to make per-language statistics learning work?

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#496]
Does the language should be detected automatically on learning or I have to do additional actions?

~~~sql
# sqlite3 /var/db/rspamd/bayes.ham.sqlite
SQLite version 3.10.0 2016-01-06 11:01:07
Enter ".help" for usage hints.
sqlite> select * from languages;
0|default|3666
1|russian|0
2|arabic|0
sqlite> .quit

# sqlite3 /var/db/rspamd/bayes.spam.sqlite
SQLite version 3.10.0 2016-01-06 11:01:07
Enter ".help" for usage hints.
sqlite> select * from languages;
0|default|3645
1|russian|0
2|chineese|0
sqlite> .quit
~~~

rspamd 1.1.1

~~~
# rspamadm configdump
...
classifier {
    type = "bayes";
    tokenizer {
        name = "osb";
    }
    cache {
        path = "/var/db/rspamd/learn_cache.sqlite";
    }
    min_tokens = 11;
    backend = "sqlite3";
    languages_enabled = true;
    statfile {
        symbol = "BAYES_HAM";
        path = "/var/db/rspamd/bayes.ham.sqlite";
        spam = false;
    }
    statfile {
        symbol = "BAYES_SPAM";
        path = "/var/db/rspamd/bayes.spam.sqlite";
        spam = true;
    }
}
...
~~~

**Comment by fatalbanana** [comment]
Should be detected. You could check `select count(*) from tokens where language = 1` which would likely show some non-zero value.

**Comment by moisseev** [comment]
You are right. But why values in the `learns` column are 0 for languages other than `default`?
~~~sql
# sqlite3 /var/db/rspamd/bayes.ham.sqlite
SQLite version 3.10.0 2016-01-06 11:01:07
Enter ".help" for usage hints.
sqlite> select * from languages;
0|default|3703
1|russian|0
2|arabic|0
sqlite> select count(*) from tokens where language = 0;
209309
sqlite> select count(*) from tokens where language = 1;
831132
sqlite> select count(*) from tokens where language = 2;
277
sqlite> .quit

# sqlite3 /var/db/rspamd/bayes.spam.sqlite
SQLite version 3.10.0 2016-01-06 11:01:07
Enter ".help" for usage hints.
sqlite> select * from languages;
0|default|3656
1|russian|0
2|chineese|0
sqlite> select count(*) from tokens where language = 0;
197399
sqlite> select count(*) from tokens where language = 1;
867985
sqlite> select count(*) from tokens where language = 2;
227
sqlite> .quit
~~~

**Comment by fatalbanana** [comment]
I suppose these arguments are transposed:

https://github.com/vstakhov/rspamd/blob/master/src/libstat/backends/sqlite3_backend.c#L890

https://github.com/vstakhov/rspamd/blob/master/src/libstat/backends/sqlite3_backend.c#L183-L184

**Comment by moisseev** [comment]
The fix works, but there is a problem with relearning messages learned before the fix.
Learns count for all languages was stored as `default` language learns.

We should count number of learns for each language in the `tokens` table and update `languages` table once before using the fix. Or maybe check the language stored in the `tokens` table for particular token on each learn and update the counters respectively.

--
Learn a message with rspamd without the fix.
~~~
# rspamc learn_ham double_bayes.eml
~~~
Now reinstall rspamd with the fix.
~~~sql
# sqlite3 /var/db/rspamd/bayes.spam.sqlite
sqlite> select * from languages;
0|default|3483
1|russian|0
2|chineese|0

# sqlite3 /var/db/rspamd/bayes.ham.sqlite
sqlite> select * from languages;
0|default|3334
1|russian|0
2|arabic|0

# rspamc learn_spam double_bayes.eml
Results for file: double_bayes.eml (0.281 seconds)
success = true;

# sqlite3 /var/db/rspamd/bayes.spam.sqlite
sqlite> select * from languages;
0|default|3483
1|russian|1
2|chineese|0

# sqlite3 /var/db/rspamd/bayes.ham.sqlite
sqlite> select * from languages;
0|default|3334
1|russian|-1
2|arabic|0
~~~

**Comment by fatalbanana** [comment]
That's unfortunate but I think not fixable. AFAIU there is no way to infer an accurate learn count (ie from `tokens`).

**Comment by moisseev** [comment]
AFAIU for now learn count is only used to calculate `Total learns` and it is not affected. Are there any plans for other usage of that counters?

**Comment by fatalbanana** [comment]
None I'm aware of. Feels doubtful. But I cannot confirm. :)

**Comment by vstakhov** [comment]
Well, I've added a workaround for this issue to avoid negative numbers here

**Comment by moisseev** [comment]
I think it's not a good idea. This issue is not about negative numbers, it's about decrementing wrong counter. If I understand right what you've done, 70b43ec will break totals that was counted right despite negative numbers.

**Comment by fatalbanana** [comment]
It's not the wrong counter though- your data is just bad. And I see no possibility to fix that unfortunately.

**Comment by moisseev** [comment]
I understand. I meant it would be better to revert 70b43ec to make totals calculated properly in any case (even with negative numbers).

**Comment by vstakhov** [comment]
But calculations with negative numbers won't be correct by nature!

**Comment by moisseev** [comment]
There was a bug before f2d698079160e0f36c0575f012e84d60d4f68cf1. But it wasn't affect total value. After that fix we may have negative value of particular counter, but we never use it directly. We need only total value and it is not affected. So, it's good enough.

`Total learns` is a sum of all `learns` counters.

* On each learning one of the counters incremented by 1. And total incremented by 1. Particular language and sign doesn't mater.
* On each relearning one of the counter is decremented and another one is incremented. Total doesn't change. Particular language and sign doesn't mater again.

If we wouldn't allow a counter to fall below 0 and wouldn't decrement it while relearning, it's value will be not changed, but another one will be incremented by 1, then total will be increased by 1 and that is incorrect.

There is a way to avoid negative counter values and keep correct total. You should not both decrement and increment counters while relearning if one of them falls below zero.
