### ISSUE TITLE
Is there a way to disable "stat" function?

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#500]
First of all, I must thank you for creating such a powerful software, it's quite great. 

However, In my stress testing, I found that rspamd uses more and more memory, approximates to 200mb.

It seems that because the stat function, rspamd would remember the result of scan. 

Is there a way to disable this or how I could limit the memory usage ? Restart after a period of time?

Thank you all !!

**Comment by vstakhov** [comment]
The leak should be fixed now
