### ISSUE TITLE
Problem witch TheBat HTML messages + IMG

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#501]
I put a picture in html and attach it to the letter.
Mail client: TheBat
Format: text + html. 

Rspamd added HTML_SHORT_LINK_IMG_1(3.00) symbol to my simple letter.
```
<img width=272 height=128 alt="" style="padding : 1px;" src="cid:=6ED594D2.01D15813.5F8EFF3F.1367FC40_csseditor">
```

And added R_SUSPICIOUS_IMAGES(5.00) symbol. 

Very hard rules :(

My simple letter http://pastebin.com/akhHZDqC

**Comment by moisseev** [comment]
It's probably related to #406

**Comment by vstakhov** [comment]
This rule is intended to detect spam messages with just a large embedded image. And now you creates exactly the same message and ask why is it filtered. IMHO, the answer is obvious: that's because it looks like a spam.

**Comment by vstakhov** [comment]
Hum, I just checked your message. I need to investigate more about it...

**Comment by AlexeySa** [comment]
I think that this should not detected as the "short link":
```
src="cid:=6ED594D2.01D15813.5F8EFF3F.1367FC40_csseditor"
```

**Comment by AlexeySa** [comment]
I propose to exclude strings src="cid:.*"

**Comment by moisseev** [comment]
https://github.com/vstakhov/rspamd/blob/da30951c96e75560da9d1457c1cc023655bc3e42/rules/html.lua#L123

@vstakhov, why is __l=0__ for the @AlexeySa's sample and for that message sample:

https://paste.rspamd.com/QHdv

**Comment by vstakhov** [comment]
That's the question I'm asking as well, I'm afraid. I've postponed this issue some time ago but it seems that it needs further investigation. I'll try to find time for it A.S.A.P

**Comment by moisseev** [comment]
Looks like `text_part:get_length()` is affected too.

https://github.com/vstakhov/rspamd/blob/da30951c96e75560da9d1457c1cc023655bc3e42/rules/html.lua#L29

len=114

https://paste.rspamd.com/gPzf

**Comment by vstakhov** [comment]
It seems I've found a problem after all.

**Comment by AlexeySa** [comment]
Thank you!
