### ISSUE TITLE
rspamd child dies with SIGILL

### ISSUE THREAD

**Issue by CaptainQwark** [vstakhov/rspamd#502]
Hi,

Daily build "1.1.2-0~git11~df4b3f7~jessie   amd64" crashes on most incoming mails. (this probably has been going on for a while now, not just this latest build).

this is a little bit of the strace -f rspamd -f ... output:

```
[pid 27058] sendto(15, ">\263\1\0\0\1\0\0\0\0\0\1\00232\003194\003115\003212\3zen\10"..., 60, 0, NULL, 0) = 60
[pid 27058] writev(2, [{"(normal) ", 9}, {"<3017ad>; task; rspamd_session_a"..., 42}, {"added event: 00000000035676C0, p"..., 73}, {"\n", 1}], 4(normal) <3017ad>; task; rspamd_session_add_event: added event: 00000000035676C0, pending 14 events, subsystem: dns resolver
) = 125
[pid 27058] writev(2, [{"(normal) ", 9}, {"<3017ad>; task; rspamd_symbols_c"..., 51}, {"execute R_WHITE_ON_WHITE, 100", 29}, {"\n", 1}], 4(normal) <3017ad>; task; rspamd_symbols_cache_check_symbol: execute R_WHITE_ON_WHITE, 100
) = 90
[pid 27058] writev(2, [{"(normal) ", 9}, {"<d0b03f>; re_cache; rspamd_re_ca"..., 45}, {"get to the slow path for re type"..., 48}, {"\n", 1}], 4(normal) <d0b03f>; re_cache; rspamd_re_cache_exec_re: get to the slow path for re type: part: BGCOLOR=
) = 103
[pid 27058] --- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x63b103} ---
```

Seems to be from re_cache.c. maybe somthing to do with the new hyperscan stuff?

The message is a standard swaks (plaintext) test message. To make this more fun: it doesn't crash on every test message:

```
(normal) <73bdc0>; task; rspamd_session_add_event: added event: 000000000216F6C0, pending 14 events, subsystem: dns resolver
(normal) <73bdc0>; task; rspamd_symbols_cache_check_symbol: execute R_WHITE_ON_WHITE, 100
(normal) <d0b03f>; re_cache; rspamd_re_cache_exec_re: get to the slow path for re type: part: BGCOLOR=
(normal) <73bdc0>; task; rspamd_re_cache_exec_re: checking mime regexp: BGCOLOR= -> 0
(normal) <d0b03f>; re_cache; rspamd_re_cache_exec_re: get to the slow path for re type: part: font color=[\"']?\#FFFFFF[\"']?
(normal) <73bdc0>; task; rspamd_re_cache_exec_re: checking mime regexp: font color=[\"']?\#FFFFFF[\"']? -> 0
(normal) <73bdc0>; task; rspamd_symbols_cache_check_symbol: execute FORGED_OUTLOOK_HTML, 80
(normal) <d0b03f>; re_cache; rspamd_re_cache_exec_re: get to the slow path for re type: header: from \[\S+\] by \S+\.(?:groups|scd|dcn)\.yahoo\.com with NNFMP
(normal) <73bdc0>; task; rspamd_re_cache_exec_re: checking header Received regexp: from \[\S+\] by \S+\.(?:groups|scd|dcn)\.yahoo\.com with NNFMP -> 0
(normal) <d0b03f>; re_cache; rspamd_re_cache_exec_re: get to the slow path for re type: header: ^Microsoft Outlook\b
(normal) <73bdc0>; task; rspamd_re_cache_exec_re: checking header X-Mailer regexp: ^Microsoft Outlook\b -> 0
(normal) <73bdc0>; task; rspamd_symbols_cache_check_symbol: execute R_SAJDING, 83
(normal) <d0b03f>; re_cache; rspamd_re_cache_exec_re: get to the slow path for re type: header: \bsajding(?:om|a)?\b
(normal) <73bdc0>; task; rspamd_re_cache_exec_re: checking header Subject regexp: \bsajding(?:om|a)?\b -> 0
etc
```

You probably need more info, Just tell me what you need.

Alex

**Comment by vstakhov** [comment]
Could you tell your CPU model please?

**Comment by CaptainQwark** [comment]
Yes:
CPU0: Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz stepping 01

But it turned out there were some other things not working quite nice on this server, so I gave it a reboot. Rspamd (and the other stuff) seems to be much more stable now (did not get a SIGILL since that reboot).

I'm not sure what was going on there but it's probably better to give this a rest for now. (and close this issue)

Sorry for your time.
Alex.

**Comment by CaptainQwark** [comment]
Hmm seems I cheered too early: still the same issue.

```
(normal) <53830e>; task; rspamd_symbols_cache_check_symbol: execute R_WHITE_ON_WHITE, 100
(normal) <d0b03f>; re_cache; rspamd_re_cache_exec_re: get to the slow path for re type: part: BGCOLOR=
(main) <015fa1>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated worker
(main) <015fa1>; main; rspamd_cld_handler: normal process 4032 terminated abnormally by signal: 4 but NOT created core file
```

**Comment by vstakhov** [comment]
Is it a VM or a baremetal server?

**Comment by CaptainQwark** [comment]
baremetal

**Comment by vstakhov** [comment]
Could you set VALGRIND enviornment variable before running rspamd? E.g. in rspamd start script. I have one suspection...

**Comment by CaptainQwark** [comment]
What value should I set VALGRIND to? setting VALGRIND=1 does not seem to do much?

running: VALGRIND=1  rspamd -f -d -u _rspamd -g _rspamd -c /etc/rspamd/rspamd.conf on cmd line.
tried export VALGRIND=1 as well.

**Comment by vstakhov** [comment]
Ok and what if you set 'disable_hyperscan=true;' in options section of the configuration?

**Comment by CaptainQwark** [comment]
That helped. Now the SIGILLs are completely gone.
But we'd rather have that hyperscan would work without problems, right? :)

**Comment by vstakhov** [comment]
Could you please tell what are the log messages that appear just after rspamd start and describe hyperscan configuration. For example, in my case this message looks as following:

    2016-01-28 18:15:42 #93108(main) <f07f2f>; re_cache; rspamd_re_cache_init: loaded hyperscan engine witch cpu tune 'haswell' and features 'AVX2'

**Comment by CaptainQwark** [comment]
```
(main) <d0b03f>; re_cache; rspamd_re_cache_init: loaded hyperscan engine witch cpu tune 'generic' and features ''
```

**Comment by CaptainQwark** [comment]
Hi, 

Even with 'disable_hyperscan=true;' I get signal 4 errors again in recent 1.2.4 builds. 
1.2.3-stable is fine.

I did not do real debugging yet, but with 1.2.4 I see lines like this in my logfile:
re_cache; rspamd_re_cache_load_hyperscan: hyperscan database of 237 regexps has been loaded

I do not see lines like that with 1.2.3. Perhaps de disable_hyperscan=true; setting is not honored in 1.2.4?

thanks,
Alex.

**Comment by vstakhov** [comment]
Yes, hyperscan is now used for everything. What OS are you using btw?

**Comment by vstakhov** [comment]
Actually, I just need to rebuild hyperscan properly for your platform and your issue should be resolved.

**Comment by CaptainQwark** [comment]
tnx for your reply. 

I'm using your deb packages from rspamd.com on debian 8.4 (latest jessie amd64). 

uname -a
Linux liquid 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

lshw | grep cpu stuff

     *-cpu
          product: Intel(R) Pentium(R) 4 CPU 3.80GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          size: 1400MHz
          capacity: 1900MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx x86-64 constant_tsc pebs bts nopl pni dtes64 monitor ds_cpl est tm2 cid cx16 xtpr cpufreq

**Comment by vstakhov** [comment]
I've just rebuilt hyperscan for jessie, so it should work fine with the most recent rspamd package.

**Comment by CaptainQwark** [comment]
damn you're quick. will try! tnx!

**Comment by CaptainQwark** [comment]
I just upgraded to (reinstalled again) this version:
Unpacking rspamd (1.2.4-0~git75~d4c6a71~jessie) over (1.2.4-0~git75~d4c6a71~jessie) ...

stopped (verified) and started rspamd but still signal 4 errors.

did I use the right package?

**Comment by vstakhov** [comment]
Wait, do you really have Pentium 4 CPU? That doesn't look sane for me as that processor has no support of x86_64 mode.

**Comment by fatalbanana** [comment]
Looks like more recent Pentium 4 chips were x86_64 fwiw: https://en.wikipedia.org/wiki/Pentium_4

**Comment by vstakhov** [comment]
I'm sorry but I won't reduce compile level to pentium 4 for hyperscan as it would affect the vast majority of hyperscan users. The lower model of cpu supported for x86_64 architecture is `core 2`. If you'd like to have rspamd on Pentium 4 in 64 bits mode, then please build packages by yourself adding -DENABLE_HYPERSCAN=OFF to `debian/rules` where `cmake` is invoked.

**Comment by CaptainQwark** [comment]
That is understandable :). Thanks for your time!

**Comment by vstakhov** [comment]
Alternatively, you could build hyperscan on your platform and use it in rspamd - there should be no issues AFAIR.

**Comment by CaptainQwark** [comment]
Thanks. While that would be a nice exercise, but I actually have some newer hardware lying around here, so I probably just use this issue as a nice incentive to finally migrate.

**Comment by xpunkt** [comment]
sudo apt-get source rspamd -b

build local to make better performance and stabality

**Comment by vstakhov** [comment]
Should be fixed now.
