### ISSUE TITLE
rspamd on FreeBSD

### ISSUE THREAD

**Issue by ameagle** [vstakhov/rspamd#503]
Hi !
I can't install rspamd on FreeBSD from src
git clone --recursive https://github.com/vstakhov/rspamd.git
cmake ../rspamd
.......
-- Performing Test HAVE_LIBEVENT2
-- Performing Test HAVE_LIBEVENT2 - Failed
-- Looking for CLOCK_PROCESS_CPUTIME_ID
-- Looking for CLOCK_PROCESS_CPUTIME_ID - not found
-- Looking for CLOCK_VIRTUAL
-- Looking for CLOCK_VIRTUAL - found
-- Performing Test HAVE_ASM_PAUSE
-- Performing Test HAVE_ASM_PAUSE - Success
-- Performing Test HAVE_ATOMIC_BUILTINS
-- Performing Test HAVE_ATOMIC_BUILTINS - Failed
-- atomic builtins are -NOT- supported
-- Compilation of slash macro convention asm set is supported
-- Compilation of dollar macro convention asm set is -NOT- supported
-- Compilation of avx2 asm set is -NOT- supported
-- Compilation of avx asm set is -NOT- supported
-- Compilation of sse2 asm set is supported
-- Compilation of sse3 asm set is -NOT- supported
-- Compilation of ssse3 asm set is -NOT- supported
-- Compilation of sse41 asm set is -NOT- supported
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ameagle/rspamd.build

make
......
[ 78%] Building C object src/CMakeFiles/rspamd-server.dir/libmime/smtp_utils.c.o
[ 78%] Building C object src/CMakeFiles/rspamd-server.dir/libmime/smtp_proto.c.o
[ 80%] Building C object src/CMakeFiles/rspamd-server.dir/libcryptobox/cryptobox.c.o
[ 80%] Building C object src/CMakeFiles/rspamd-server.dir/libcryptobox/chacha20/chacha.c.o
[ 81%] Building C object src/CMakeFiles/rspamd-server.dir/libcryptobox/chacha20/ref.c.o
[ 81%] Building ASM object src/CMakeFiles/rspamd-server.dir/libcryptobox/chacha20/sse2.S.o
/home/ameagle/rspamd/src/libcryptobox/chacha20/sse2.S: Assembler messages:
/home/ameagle/rspamd/src/libcryptobox/chacha20/sse2.S:482: Error: suffix or operands invalid for `movq'
*** Error code 1
Stop in /usr/home/ameagle/rspamd.build.
*** Error code 1
Stop in /usr/home/ameagle/rspamd.build.
*** Error code 1
Stop in /usr/home/ameagle/rspamd.build.

**Comment by vstakhov** [comment]
What version of FreeBSD and what architecture are you using?

**Comment by ameagle** [comment]
uname -a
FreeBSD spg.xxx.ru 8.2-RELEASE FreeBSD 8.2-RELEASE  amd64.
Virtual Mashine.
I know it's old, but can't change (customer requirement).

I commented lines in rspamd/src/libcryptobox/CMakeLists.txt, before cmake.
IF(HAVE_SSE2)
        #SET(CHACHASRC ${CHACHASRC} ${CMAKE_CURRENT_SOURCE_DIR}/chacha20/sse2.S)
        #SET(POLYSRC ${POLYSRC} ${CMAKE_CURRENT_SOURCE_DIR}/poly1305/sse2.S)
ENDIF(HAVE_SSE2)

After that I could build and install it.
But catch Segmentation fault.

~/rspamd# gdb /usr/local/bin/rspamd
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) r -c /usr/local/etc/rspamd/rspamd.conf --insecure
Starting program: /usr/local/bin/rspamd -c /usr/local/etc/rspamd/rspamd.conf --insecure
[New LWP 100302]
[New Thread 8022041c0 (LWP 100302)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 8022041c0 (LWP 100302)]
0x0000000800b5507e in g_byte_array_sort () from /usr/local/lib/libglib-2.0.so.0

**Comment by vstakhov** [comment]
I'd recommend to install the recent gcc or clang and switch compiler by `-DCMAKE_C_COMPILER` `-DCMAKE_ASM_COMPILER` and so on

**Comment by ameagle** [comment]
Thanks. It helped. Besides update libglib-2.28 to libglib-2.36
