### ISSUE TITLE
Segfault in main (rspamd_cld_handler)

### ISSUE THREAD

**Issue by wackerm** [vstakhov/rspamd#507]
Since the last update the rspamd.log is full with these error messages (after allmost every incoming message!) :

    #20715(main) <0c1ff1>; main; rspamd_cld_handler: normal process 29417 terminated abnormally by signal: 11 but NOT created core file

And also a lot of segfaults in my system log (i am not sure, if these are related to the above error):
```
Jan 27 08:40:26 mail kernel: [12578227.666879] rspamd[20523]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
Jan 27 09:08:12 mail kernel: [12579892.224444] rspamd[23655]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
Jan 27 10:53:37 mail kernel: [12586213.404838] rspamd[19547]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
Jan 27 11:20:44 mail kernel: [12587839.750958] rspamd[4602]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
Jan 27 12:19:09 mail kernel: [12591342.626190] rspamd[23159]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
Jan 27 12:40:47 mail kernel: [12592640.040933] rspamd[11892]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
Jan 27 13:13:58 mail kernel: [12594630.120376] rspamd[26735]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
Jan 27 18:25:55 mail kernel: [12613336.525562] rspamd[2872]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
Jan 27 18:53:08 mail kernel: [12614968.108953] rspamd[22675]: segfault at 0 ip 00000000004374bb sp 00007ffe2b8b0c50 error 4 in rspamd[400000+13c000]
```
Since rspamd still seems to work i am not sure if i should worry about these error messages?

Usage: Debian Wheezy, Postfix + rmilter

**Comment by vstakhov** [comment]
Nope, that's bad. To be able to solve your issue I need to get some backtraces from the core files. You should read some related documentation to enable core dumps in your system (e.g. http://www.cyberciti.biz/tips/linux-core-dumps.html) and get backtraces by typing `bt full` in gdb.

**Comment by wackerm** [comment]
ok, i enabled core dumps and will provide a backtrace tomorrow...

**Comment by wackerm** [comment]
ist magic: yesterday after this report i restarted rspamd and activated the kernel core dumps and since then the errors did not reappear again... 
as soon as the error reappears i will provide a core-dump / backtrace...

**Comment by mnik247** [comment]
Yesterday I have problem with crashing rspamd too.
2016-01-27 15:55:36 #27815(main) <b226f4>; main; rspamd_cld_handler: controller process 27817 terminated normally
It was after "reload" - /etc/init.d/rspamd reload
I have about 30 core dump if need.
After "restart" - /etc/init.d/rspamd restart - no errors more...

**Comment by vstakhov** [comment]
Could you please show trace from any of those core files?

**Comment by mnik247** [comment]
first dump: 
#gdb /tmp/core-rspamd-11-497-496-13332-1453902993
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-83.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Missing separate debuginfo for the main executable file
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/50/3408958c2ffcac65e85f08d271529e051f9a88
[New Thread 13332]
Core was generated by `rspamd: normal process                                                   '.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000433d29 in ?? ()
"/tmp/core-rspamd-11-497-496-13332-1453902993" is a core file.
Please specify an executable to debug.
(gdb) bt full
#0  0x0000000000433d29 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb)

last dump:
#gdb /tmp/core-rspamd-11-497-496-30112-1453904709
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-83.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Missing separate debuginfo for the main executable file
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/50/3408958c2ffcac65e85f08d271529e051f9a88
[New Thread 30112]
Core was generated by `rspamd: normal process                                                   '.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f102d8baee8 in ?? ()
"/tmp/core-rspamd-11-497-496-30112-1453904709" is a core file.
Please specify an executable to debug.
(gdb) bt full
#0  0x00007f102d8baee8 in ?? ()
No symbol table info available.
#1  0x00007f102d8bc118 in ?? ()
No symbol table info available.
#2  0x0000000000000028 in ?? ()
No symbol table info available.
#3  0x0000000001423620 in ?? ()
No symbol table info available.
#4  0x000000000188a020 in ?? ()
No symbol table info available.
#5  0x000000000044906b in ?? ()
No symbol table info available.
#6  0x00007fff9b6e8cd0 in ?? ()
No symbol table info available.
#7  0x0000006e00000077 in ?? ()
No symbol table info available.
#8  0x000000000188a020 in ?? ()
No symbol table info available.
#9  0x0000000000000008 in ?? ()
No symbol table info available.
#10 0x000000000188a020 in ?? ()
No symbol table info available.
#11 0x0000000000003fff in ?? ()
No symbol table info available.
#12 0x0000000000000001 in ?? ()
No symbol table info available.
#13 0x000000000047243e in ?? ()
No symbol table info available.
#14 0x0000000000000090 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb)

**Comment by vstakhov** [comment]
Oh wait, that was reload... Just don't even try to use it - it was broken for ages and I should eventually remove it.

**Comment by vstakhov** [comment]
OK, I've removed them for now...

**Comment by wackerm** [comment]
oh i guess i tried "reloading" before too, so that would explain why it these errors are not appearing anymore after the restart ;-)
