### ISSUE TITLE
Fuzzy storage did not store any data

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rspamd#508]
Hi.

My issue similar to #478 but main difference is that in my case there is no data in digest table to.

My config for fuzzy check module:
> ... here is defaul config for rspamd.com servers
>
>    # My rules
>    rule {
>        servers = "127.0.0.1:11335";
>        symbol = "LOCAL_FUZZY_UNKNOWN";
>        mime_types = ["application/*"];
>        max_score = 20.0;
>        read_only = no;
>        skip_unknown = yes;
>        fuzzy_map = {
>            LOCAL_FUZZY_DENIED {
>                max_score = 20.0;
>                flag = 11;
>            }
>            LOCAL_FUZZY_PROB {
>                max_score = 10.0;
>                flag = 12;
>            }
>            LOCAL_FUZZY_WHITE {
>                max_score = 2.0;
>                flag = 13;
>            }
>        }
>    }

My command is:
>rspamc -h localhost -f 11 -w 10 fuzzy_add 1.eml

Result is:
>Results for file: 1.eml (0.008 seconds)
>success = true;

Logs:
>Jan 29 09:58:31 mx01 rspamd[44225]: <>; ; rspamd_http_router_finish_handler: requested known path: /fuzzyadd
>Jan 29 09:58:31 mx01 rspamd[44225]: <7bdadb>; task; fuzzy_cmd_from_text_part: loading shingles with key ff30ef0fcfdf3fc0f0b06f80b0ef7f40
>Jan 29 09:58:31 mx01 rspamd[44225]: <7bdadb>; task; fuzzy_controller_io_callback: processed fuzzy hash <1771552120>, list: LOCAL_FUZZY_DENIED:11 for message <bbd501d15258$2532a210$b17dd667@aqlofxd>

But when i opened fuzzy.db i saw that it is empty:
>[root@mx01 ~]# sqlite3 /var/lib/rspamd/fuzzy.db
>SQLite version 3.7.17 2013-05-20 00:56:22
>Enter ".help" for instructions
>Enter SQL statements terminated with a ";"
>sqlite> SELECT Count(*) FROM digests;
>0
>sqlite> SELECT Count(*) FROM shingles;
>0

My schema:
>sqlite> .schema
>CREATE TABLE digests(id INTEGER PRIMARY KEY,flag INTEGER NOT NULL,digest TEXT NOT NULL,value INTEGER,time INTEGER);
>CREATE TABLE shingles(value INTEGER NOT NULL,number INTEGER NOT NULL,digest_id INTEGER REFERENCES digests(id) ON DELETE CASCADE ON UPDATE CASCADE);
>CREATE UNIQUE INDEX d ON digests(digest);
>CREATE INDEX t ON digests(time);
>CREATE INDEX dgst_id ON shingles(digest_id);
>CREATE UNIQUE INDEX s ON shingles(value, number);

Versions:
CentOS Linux release 7.2.1511 (Core)
rspamd-1.1.1-2.1.x86_64

**Comment by vstakhov** [comment]
A storage is not updated immediately. Instead hashes are collected and updated approximately once per minute.

**Comment by damned-trooper** [comment]
After 2 hours nothing changed:
>[root@mx01 ~]# sqlite3 /var/lib/rspamd/fuzzy.db
>SQLite version 3.7.17 2013-05-20 00:56:22
>Enter ".help" for instructions
>Enter SQL statements terminated with a ";"
>sqlite> SELECT Count(*) FROM shingles;
>0
>sqlite> SELECT Count(*) FROM shingles;
>0
>sqlite> .quit
>[root@mx01 ~]# date
>**Fri Jan 29 12:43:43 MSK 2016**

**Comment by fatalbanana** [comment]
Can you show configuration for fuzzy worker?- You will likely have problems if you are using systemd sockets for this (rather use `bind_socket = "localhost:11335"`).

**Comment by damned-trooper** [comment]
Yes, i use systemd socket (UDP). But i saw "success = true" when i start learn command. As i can understand - worker run correct in this case.

Configs:

/etc/rspamd/rspamd.conf:
>worker {
>    bind_socket = "systemd:2";
>    .include "$CONFDIR/worker-fuzzy.inc"
>}

/etc/rspamd/worker-fuzzy.inc:
>type = "fuzzy";
>count = 1;
>hash_file = "${DBDIR}/fuzzy.db";
>expire = 90d;
>allow_update = "127.0.0.1";
>allow_update = "::1";

/etc/systemd/system/rspamd.socket:
>[Unit]
>Description=rapid spam filtering system
>
>[Socket]
>ListenStream=11333
>ListenStream=[::1]:11334
>ListenDatagram=127.0.0.1:11335
>
>BindIPv6Only=both
>
>[Install]
>WantedBy=sockets.target

Do you think that i shall try to use native socket without systemd?

**Comment by fatalbanana** [comment]
Yes I suggest you try it. Take special care to see that the service actually restarts.

**Comment by damned-trooper** [comment]
@fatalbanana it works!
So look likes systemd cause my problem with learning. But i can't understand what difference between systemd's socket and raw socket from config file.
Anyway thanks a lot.
