### ISSUE TITLE
HEADER_FORGED_MDN rule and `from=<>`

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#513]
"Fix rule when SMTP from is unavailable" 91d772ab6f6e9f030561654d9dca693518dbd3c3
The rule doesn't also distinguish `unavailable SMTP from` and `from=<>`. Is it possible to fix that?

**Comment by vstakhov** [comment]
Do you think it is worth to distinguish?

**Comment by moisseev** [comment]
Is there any legitimate reason to send mail with `MAIL FROM: <>` except DSN?
DSN shouldn't have `Disposition-Notification-To:` header.

**Comment by vstakhov** [comment]
I'm still not with you: what exactly do you suggest to change in this rule?

**Comment by moisseev** [comment]
Sorry. It works as expected, actually.
