### ISSUE TITLE
"MISSING_MIMEOLE" rule incorrectly interpreted (fixed in SpamAssassin, broken in rspamd).

### ISSUE THREAD

**Issue by ilyakruchinin** [vstakhov/rspamd#514]
IMPORTANT: see next message for details and a bugreport (this rule/rating has been fixed in SpamAssassin long ago).

Version: rspamd 1.1.1

We are using rspamd as outbound antispam.
A user has complained that some of his messages get bounced.
I checked and some (not all) of his messages get:

> Feb 01 16:59:21 antispam rspamd[497]: (normal) <e585be>; task; rspamd_task_write_log: id: <000801d15cb5$cfd5db30$6f819190$@contoso.com>, qid: <1aQ7WC-00082L-Rz>, ip: XXX.XX.XX.XX, from: <john@contoso.com>, (default: T (reject): [15.09/15.00] [**MISSING_MIMEOLE,FORGED_OUTLOOK_TAGS**,SUBJ_ALL_CAPS,HFILTER_HELO_IP_A,HFILTER_HOSTNAME_UNKNOWN]), len: 48467, time: 397.687ms real, 30.368ms virtual, dns req: 38

I've discussed it with the user and he's using Outlook, not using any other email software.
Here's a different message from the same user (for comparison), where NO scores are assigned for MISSING_MIMEOLE or FORGED_OUTLOOK_TAGS:

> Feb 02 09:31:46 antispam rspamd[497]: (normal) <31f3e2>; task; rspamd_task_write_log: id: <000601d15d40$7623e8d0$626bba70$@contoso.com>, qid: <1aQN0b-000A3a-Mx>, ip: 111.67.28.43, from: <john@contoso.com>, (default: F (no action): [2.00/15.00] [HFILTER_HELO_IP_A,URIBL_BLOCKED,BAYES_HAM,HFILTER_HOSTNAME_UNKNOWN]), len: 52298, time: 408.724ms real, 20.649ms virtual, dns req: 54

For the first example of "incorrectly detected as missing_mimeole/forged_outlook_tags - below are the headers from exim4 rejectlog:

```
2016-02-01 16:59:21 1aQ7WC-00082L-Rz H=(wp010.contoso.com) [XXX.XX.XX.XX] F=<john@contoso.com> rejected after DATA: Message discarded as high-probability spam 15.1 reject
Envelope-from: <john@contoso.com>
Envelope-to: <aaron@contoso.com>
    ...
P Received: from [XXX.XX.XX.XX] (helo=contoso.com)
        by antispam.contoso.com with esmtp (Exim 4.86)
        (envelope-from <john@contoso.com>)
        id 1aQ7WC-00082L-Rz; Mon, 01 Feb 2016 16:59:20 +1100
P Received: from Giovanni ([YYY.YY.YY>YY]) by wp010.contoso.com with MailEnable ESMTP; Mon, 1 Feb 2016 16:59:14 +1100
F From: <john@contoso.com>
T To: <prash@contoso.com>
  References:
  In-Reply-To:
  Subject: RE: 2016 DESIGN GROUP STRATEGIC CONFERENCE
  Date: Mon, 1 Feb 2016 17:00:10 +1100
I Message-ID: <000801d15cb5$cfd5db30$6f819190$@contoso.com>
  MIME-Version: 1.0
  Content-Type: multipart/related;
        boundary="----=_NextPart_000_0009_01D15D12.03484F00"
  X-Priority: 1 (Highest)
  X-MSMail-Priority: High
  X-Mailer: Microsoft Outlook 15.0
  Thread-Index: AdFMtJ4fItqFX3o2T5yHfZbyYOiEtAP/cbUw
  Content-Language: en-au
  Importance: High
  X-ME-Bayesian: 0.000000
```

**Comment by ilyakruchinin** [comment]
OK, having analyzed the full email (with headers) from the user, it seems like the MIME_OLE part is missing, although the "PRIORITY" is set.
The user, however, ensures us he's ONLY using the official Microsoft Outlook product line (2003 to Office365), and there are multiple responses in the mail thread (with all users using Microsoft Outlook only). 

I wonder if, in any Microsoft Outlook version, the behaviour has been changed, and whether now the "priority" tag can go without "mime_ole".

**Comment by ilyakruchinin** [comment]
Please see: https://bz.apache.org/SpamAssassin/show_bug.cgi?id=6346

Web (OWA) access in Office12/14 do NOT include MIMEOLE tag (which is now expected behaviour in Microsoft product). However, such messages get a devastating 5.0 score in rspamd.

**Comment by ilyakruchinin** [comment]
Could you please correct the rule (for example, using the suggested workaround for SA)? Lots of false positives.

**Comment by vstakhov** [comment]
Should be fixed in the master (I'll cherry-pick this fix to stable as well)

**Comment by ilyakruchinin** [comment]
Thank you! I'll be waiting for the next stable release then (with the cherry-picked fix you mentioned)!

**Comment by mars90226** [comment]
Hi, I think this issue should be opened again as Outlook 2016 has the same problem.
Please see: [https://bz.apache.org/SpamAssassin/show_bug.cgi?id=7463](https://bz.apache.org/SpamAssassin/show_bug.cgi?id=7463)

**Comment by vstakhov** [comment]
I have relaxed this rule.
