### ISSUE TITLE
Feature: add Ratelimit for authenticated senders (outgoing messages)

### ISSUE THREAD

**Issue by wackerm** [vstakhov/rspamd#515]
it would be very nice if it would be possible (for e.g. via expiring redis entries) to add a rate limit for messages based on the authenticated sender information (sasl-username).

this could prevent incidents, where the users pc is infected and abused to send spam or the user credentials had been leaked...

so it should be possible to rate limit an authenticated sender to send no more than for e.g. 100 messages per hour or 5 per minute or something like this, together with the leaking bucket concept this should work fairly well and could be monitored in the logs...

**Comment by vstakhov** [comment]
You could try something like this:

```nginx
ratelimit {
    rates {
        user = [20, 0.01666666667];
    }
    servers = example.com;
    symbol = "USERS_RATELIMIT";
    whitelisted_rcpts = "postmaster,mailer-daemon";
}
```

**Comment by vstakhov** [comment]
You could try something like this:

```nginx
ratelimit {
    rates {
        user = [20, 0.01666666667];
    }
    servers = example.com;
    symbol = "USERS_RATELIMIT";
    whitelisted_rcpts = "postmaster,mailer-daemon";
}
```

**Comment by wackerm** [comment]
i am not sure, if i fully understood your proposed ratelimit configuration, but as far as i understood this will work only for a specific receiver with domain "example.com" or a sender "...@example.com"?

We are hosting some hundred domains with lots of users, signing in from dynamic IPs... so how to distinguish the users?

We just had the case, that a users computer was infected and abused to send thousands of messages a minute while login in with his compromised credentials...

**Comment by vstakhov** [comment]
No, `servers` specifies redis backend to store limits data. You distinguish your users by SMTP auth.

**Comment by wackerm** [comment]
well so seems to be exactly what i am looking for... i will give it a try ;-)

**Comment by TomFuch** [comment]
Hello!
Is it possible to limit a specific user and not all?
