### ISSUE TITLE
Feature Request: more secure Redis options

### ISSUE THREAD

**Issue by bax-** [vstakhov/rspamd#518]
I'm missing some options to connect to Redis.
In my use case, I have several FreeBSD jails. One of them runs Redis. 
So I have a shared caching instance but I'm separating the different services by using different Redis databases (for PHP-sessions, webcache, etc.).

For security I think it would be important if rspamd supported choosing the number of the database and also support authentication.

**Comment by vstakhov** [comment]
Why not run dedicated redis for rspamd? Implementing authentication or db selection is not an easy task using asynchronous API, so I don't see enough reasons to implement this feature.

**Comment by bax-** [comment]
I'm trying to keep everything as minimum as possible at this moment.
I think if the redis server is a shared or a dedicated one should be open to the user's needs and capabilities.
Using different databases shouldn't be too complicated I was expecting – maybe I was wrong?
[PHP-Redis](https://github.com/phpredis/phpredis#php-session-handler) e.g. uses a simple URL scheme like `tcp://host1:6379?database=6`

**Comment by vstakhov** [comment]
It involves sending extra command to redis. That's not that easy with asynchronous IO.
