### ISSUE TITLE
How to scan mail coming from fetchmail

### ISSUE THREAD

**Issue by Twilek-de** [vstakhov/rspamd#520]
I am trying rspamd again (no connection resets until now). I use rspamd with exim. I poll multiple external IMAP accounts via fetchmail. With the default rspamd exim configuration with  "accept hosts = +relay_from_hosts" included rspamd will not scan those incoming messages at all as fetchmail is recognised as running on the local host (I guess). If I comment this out rspamd will scan those message but will put high Spam rankings on them.

Symbol: HFILTER_HOSTNAME_UNKNOWN(2.50)
Symbol: HFILTER_HELO_NORES_A_OR_MX(0.30)
Symbol: FORGED_RECIPIENTS(1.00)
Symbol: BROKEN_HEADERS(1.00)
Symbol: BAYES_SPAM(3.79) (wondering about this one as the test mail included almost no text)

I think that most of those come from the fact that the mail has the external mail as the recipient but then is pulled in to the local mailserver with the local mailadress via fetchmail which obviously doesn´t match.
Is there any way to easily configure rspamd and exim to scan the messages but not flag them for being pulled by fetchmail?

**Comment by fatalbanana** [comment]
Rspamd works best @ the MX- if at all possible you should be doing filtering there.

Supposing you have to do this...

`BROKEN_HEADERS` and `BAYES_SPAM` you would probably not see on every message. Rspamd includes certain header information in bayes tokens.

`FORGED_RECIPIENTS` you will probably want to set to zero weight in metric as you may well see this on every message.

hfilter helo/hostname checks: you could similarly set to zero in metric; or disable in `hfilter {}` section of config- they're likely of no use for your purposes.

**Comment by Twilek-de** [comment]
Well I use the server as MX as well so it would have to be selevtively disabled. Strangely enough my previous setup with Spamassassin didn´t mind the headers and adresses.

**Comment by fatalbanana** [comment]
To disable this stuff selectively you could use settings module: https://rspamd.com/doc/configuration/settings.html

Rspamd is not a clone of SpamAssassin. ;)

**Comment by Twilek-de** [comment]
Yes I know, but I would have thought such inconsistencies would trigger SA as well. So if I get you right I have to generate a settings config with multiple "rcpt =" with the the corresponding external adresses in them and then in the apply section setting FORGED_RECIPIENTS = 0 etc. ?!

**Comment by fatalbanana** [comment]
Rather you could apply the setting to `ip` address used by fetchmail.

**Comment by Twilek-de** [comment]
I have added this 

settings {
    rcpt = "xxx@gmx.de";
    rcpt = "xxx@gmx.de";
    apply "default" {
        HFILTER_HOSTNAME_UNKNOWN = 0;
        HFILTER_HELO_NORES_A_OR_MX = 0;
        FORGED_RECIPIENTS = 0;
    }
}

to the rspamd.conf and tried it. It would still give the normal scores. I guess IP based selection wouldn´t really work as the IMAP Servers of the big email providers use multiple IPs for to do loadbalancing, don´t they?!

**Comment by fatalbanana** [comment]
IP address seen by Rspamd would be whatever Exim sent it. So if fetchmail delivered mail over SMTP to 127.0.0.1 then it is 127.0.0.1.

**Comment by Twilek-de** [comment]
I think I missed the name attribute. 
My config now looks like this


```
settings {
    twilek {
        ip = "127.0.0.1";
            apply "default" {
                HFILTER_HOSTNAME_UNKNOWN = 0;
                HFILTER_HELO_NORES_A_OR_MX = 0;
                FORGED_RECIPIENTS = 0;
           }
    }
}

```

Now the spamscore dropped to 4.09 and rspamd has greylisted the message. I am not sure what fetchmail will do with a greylisting... Lets wait and see...

**Comment by fatalbanana** [comment]
Adding headers is Exim's job- in the reference configuration there is a `condition` which limits this to messages given `add header` action.

**Comment by Twilek-de** [comment]
Config seems to work now, thanks. Now let the Spam start rolling in and see how rspamd performs. I hope the connection reset problems will not reappear.

**Comment by Twilek-de** [comment]
I have changed the greylisting threshold as well to stop the useless greylisting for fetchmail


```
settings {
    twilek {
        ip = "127.0.0.1";
            apply "default" {
                HFILTER_HOSTNAME_UNKNOWN = 0;
                HFILTER_HELO_NORES_A_OR_MX = 0;
                FORGED_RECIPIENTS = 0;
                        actions {
                                greylist = 15.0;
                        }
           }
    }
}

```

**Comment by fatalbanana** [comment]
Unless you have done something to make it otherwise Exim does not actually honor the `greylist` action so it is harmless. It can be treated as equivalent to `no action` (reference config ignores these equally) or removed from metric. If you want greylisting you could adapt one of the recipes in the Exim wiki for use with Rspamd: https://github.com/Exim/exim/wiki

**Comment by fatalbanana** [comment]
... You will probably want to make quite sure you don't reject messages from fetchmail. ;) I would suggest modifying Exim ACLs to suit (ie. `accept hosts = 127.0.0.1` placed strategically).

**Comment by Twilek-de** [comment]
I don´t reject any messages, but have the subject line changed and then directly moved to the junk directory for a later review.

**Comment by devurandom** [comment]
Is it possible to apply these settings to the IP-address and port the MTA **received** the mail on? I have Postfix setup to listen on `localhost:10025` and that is where fetchmail delivers the emails. So I could easily apply the special treatment only to that recipient address/port combination.

**Comment by vstakhov** [comment]
Inject some artificial header with the actual IP address, then add a pre-filter in Lua that will get this header and set the actual IP address using method `task:set_from_ip`.

**Comment by devurandom** [comment]
[Postfix milter documentation](http://www.postfix.org/MILTER_README.html) claims that it would set `{daemon_addr}` and `{daemon_port}`, which would contain the local address the email was received on. There is no way to apply rspamd settings based on these macros?

Instead, I should use the `Received` header that fetchmail inserts and whenever any `Received` header contains "fetchmail", I would use a Lua script to rewrite the remote (instead of the local) IP to some fantasy value, to allow rspamd to apply a special configuration to this email?

**Comment by sebastianlipponer** [comment]
I use a similar setup. Postfix as MX with RSpamd and Fetchmail in addition to poll IMAP accounts. Fetchmail is configured to forward mails to Postfix. Currently, I use the following `local.d/settings.conf`
```
fetchmail {
    priority = high;
    ip = "127.0.0.1";
    ip = "::1";
    header = {
        "Received" = "\\(fetchmail-\\d{1,3}\.\\d{1,3}\.\\d{1,3}\.?\\w*\\)";
    }
    apply {
        actions {
            greylist = null;
            reject = null;
        }
    }
    symbols [
        "FORWARDED";
    ]
}
```
to ensure that a mail received by Fetchmail is not rejected and gets recognized as forwarded. The problem with this is that mails are now from a local network (Fetchmail runs on the same machine) while they are in fact not. As a consequence, rspamd skips DKIM checks
```
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; rspamd_worker_body_handler: accepted connection from 127.0.0.1 port 55308, task ptr: 00007F9A03A9D0A0
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; rspamd_message_parse: loaded message; id: <...>; queue-id: <AD6474987D>; size: 201928; checksum: <...>
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; rspamd_mime_part_detect_language: detected part language: de
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; rspamd_mime_part_detect_language: detected part language: de
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; lua; settings.lua:363: <...> apply static settings fetchmail (id = 3526492139); ip,header:Received matched; priority high
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; lua_task_set_settings: disabled action greylist due to settings
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; lua_task_set_settings: disabled action reject due to settings
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; lua; greylist.lua:204: skip greylisting for local networks and/or authorized users
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; dkim_symbol_callback: skip DKIM checks for local networks and authorized users
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; lua; spf.lua:185: skip SPF checks for local networks and authorized users
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; lua; dmarc.lua:596: skip DMARC checks as either SPF or DKIM were not checked
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; dkim_module_load_key_format: cannot load dkim key /var/lib/rspamd/dkim/domain.tld.default.key: cannot stat key file: '/var/lib/rspamd/dkim/domain.tld.default.key' No such file or directory
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; lua; once_received.lua:99: Skipping once_received for authenticated user or local network
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; lua; greylist.lua:318: Score too low - skip greylisting
2021-08-16 16:09:53 #31622(normal) <1fb9b2>; task; rspamd_task_write_log: id: <...>, qid: <AD6474987D>, ip: ::1, from: <...>, (default: F (no action): ..., settings_id: fetchmail
```
and wants to DKIM sign (domain.tld is from the envelope from address of the sender). Obviously the mails are handled as outgoing mail.

> Inject some artificial header with the actual IP address, then add a pre-filter in Lua that will get this header and set the actual IP > address using method task:set_from_ip.

@vstakhov I think this should fix the problem. Do you have some examples/references on how to implement this?

**Comment by fatalbanana** [comment]
There is the newly-added and so-far-undocumented [external_relay plugin](https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/external_relay.lua) for setups like these; if it's not directly useful you might use it as a reference for rules / consider if using [rspamd_config:add_condition()](https://rspamd.com/doc/faq.html#how-can-i-disable-some-rspamd-rules-safely) helps / if there are plugin changes that could be applicable. There is example config in [functional tests](https://github.com/rspamd/rspamd/pull/3772/files#diff-71c734728e239231ca27c0b6011bf22db14539471b8bddebcadd66149a60150a).

**Comment by sebastianlipponer** [comment]
@fatalbanana Thanks! I have implemented this [rspamd fetchmail plugin](https://gist.githubusercontent.com/sebastianlipponer/6230fd4e424074ce809ebf0dc0812a14/raw/aabcb2a2d99fa2dcd9ad047caf54173151d1f817/rspamd.lua).

**Comment by Bluehorn** [comment]
> @fatalbanana Thanks! I have implemented this [rspamd fetchmail plugin](https://gist.github.com/sebastianlipponer/6230fd4e424074ce809ebf0dc0812a14).

This looks like what I am searching for. I am trying to migrate my mail server away from dspam and rspamd looks very promising. But in my tests, rspamd just did not do anything. I use `fetchmail`, pulling my email from the old server to test spam checking - go figure.

So I copied that plugin to `/etc/rspamd/plugins.d/fetchmail.lua` and it is at least picked up:

```console
# rspamadm configdump -m|grep fetchmail
Modules disabled (unconfigured): antivirus, reputation, external_services, spamassassin, clickhouse, fetchmail, metric_exporter, ip_score, clustering, maps_stats, dynamic_conf, fuzzy_collect
```

But it is marked as disabled. According to [the FAQ](https://rspamd.com/doc/faq.html#how-can-i-disable-some-rspamd-rules-safely), a module can be disabled by setting `enabled = false;` in its `.conf` file. I tried creating a config file for the plugin, but it does not have any effect.

Any hints on how to get it enabled? I found some information about disabling and enabling symbols, but I'd assume that loading the module is something different?!

TIA for any hints, Torsten

**Comment by sebastianlipponer** [comment]
@Bluehorn I renamed the file to `rspamd.lua` and copied it to `/etc/rspamd/local.d` to make it work.
