### ISSUE TITLE
dkim_module_key_handler: cannot get key for domain

### ISSUE THREAD

**Issue by dphi** [vstakhov/rspamd#521]
Hi,
I'm running rspamd 1.1.3-1~jessie (amd64). 

I find the error  dkim_module_key_handler: cannot get key for domain XXXXX
several times in my logs, e.g. for "20120113._domainkey.gmail.com".

$ host -t txt 20120113._domainkey.gmail.com
20120113._domainkey.gmail.com descriptive text "k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1Kd87/UeJjenpabgbFwh+eBCsSTrqmwIYYvywlbhbqoo2DymndFkbjOVIPIldNs/m40KF+yzMn1skyoxcTUGCQs8g3FgD2Ap3ZB5DekAo5wMmk4wimDO+U8QzI3SD0" "7y2+07wlNWwIt8svnxgdxGkVbbhzY8i+RQ9DpSVpPbF7ykQxtKXkv/ahW3KjViiAH+ghvvIhkx4xYSIc9oSwVmAl5OctMEeWUwg8Istjqz8BZeTWbf41fbNhte7Y+YqZOwq1Sd0DbvYAD9NOZK9vlfuac0598HY+vtSBczUiKERHv1yRbcaQtZFh5wtiRrN04BLUTD21MycBX5jYchHjPY/wIDAQAB"

...works.

**Comment by fatalbanana** [comment]
Are /all/ possible resolvers in /etc/resolv.conf healthy?

Is it a persistent issue? Can you replicate the issue by re-scanning some affected mail with `rspamc`?

**Comment by vstakhov** [comment]
Well, I've added some more diagnostics for this error.

**Comment by dphi** [comment]
It seems to work fine after removing the ipv6 nameservers.

**Comment by vstakhov** [comment]
Then it might be rdns issue. Could you tell me what was the syntax of those ipv6 resolvers in your `resolv.conf`?

**Comment by dphi** [comment]
nameserver followed by the plain ipv6 address (without [])
