### ISSUE TITLE
ip_score module not sets proper score

### ISSUE THREAD

**Issue by AdUser** [vstakhov/rspamd#528]
Messages in log when processing message:

```
2016-02-17 14:18:21 #69587(normal) <66f2bf>; lua; ip_score.lua:277: total score: -2.2402319899656
2016-02-17 14:18:21 #69587(normal) <66f2bf>; task; rspamd_task_write_log: id: <1455682697.809174581@f94.i.mail.ru>, qid: <1aVtZE-000J1V-3q>, ip: 94.100.185.169, from: <sardana_eremeeva86@mail.ru>, (default: F (add header): [8.96/11.30] [BAYES_SPAM,IP_SCORE,MIME_GOOD,TO_EXCESS_BASE64,R_SPF_ALLOW,RCVD_IN_DNSWL_LOW,R_DKIM_ALLOW,MIME_UNKNOWN,BROKEN_HEADERS,R_PARTS_DIFFER]), len: 446238, time: 551.283ms real, 13.992ms virtual, dns req: 21
```

Note: "total score: " log message generated with modified `ip_score_check()` in ip_score.lua:

``` lua
local ip_score_check = function(task)
  <...>
      if total_score ~= 0 then
        rspamd_logger.infox(task, 'total score: ' .. total_score)
        task:insert_result(options['symbol'], total_score, table.concat(description_t, ', '))
      end
```

Resulting symbols in message:

```
X-Spam-Score: 9.0 (++++++++)
X-Spam-Report: Action: add header
 Symbol: BAYES_SPAM(4.41)
 Symbol: IP_SCORE(0.00)
 Symbol: MIME_GOOD(-0.10)
 Symbol: TO_EXCESS_BASE64(1.50)
 Symbol: R_SPF_ALLOW(0.00)
 Symbol: RCVD_IN_DNSWL_LOW(0.00)
 Symbol: R_DKIM_ALLOW(0.00)
 Symbol: MIME_UNKNOWN(0.10)
 Symbol: BROKEN_HEADERS(1.00)
 Symbol: R_PARTS_DIFFER(2.04)
```

rspamd 1.1.2

Best regards, Alex

**Comment by vstakhov** [comment]
Do you have `IP_SCORE` symbol defined in the metric?

**Comment by AdUser** [comment]
From ip_score.lua

```lua
  local options = {
  <...>
  symbol = 'IP_SCORE', -- symbol to be inserted

  rspamd_config:register_symbol(options['symbol'], 1.0, ip_score_check)
-- ^^ near line 369
```

Seems like symbol is registered by module itself.

**Comment by fatalbanana** [comment]
You still need to register symbol in metric to give it a non-zero weight.

**Comment by AdUser** [comment]
Hmm, this seems to be working.

Can you add some docs about this to official site? Now this module undocumented at all (not even mentioned in module list).

**Comment by fatalbanana** [comment]
This module is somewhat experimental. There is at least one issue with it I'd like to see fixed ideally before it's documented (being that scores are not considered exclusive of `IP_SCORE` itself so if scoring is too high this skews reputation). I also have some thoughts about how to improve on this module but that should be non-blocking. :)
