### ISSUE TITLE
Feature request: fuzzy storage update rspamc command

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#533]
Is it possible to add an rspamc command for forcing immediate fuzzy storage update?

**Comment by vstakhov** [comment]
That's possible for `rspamadm control` but not for rspamc according to rspamd architecture.

**Comment by moisseev** [comment]
ok, it works for me. That would be great.

**Comment by moisseev** [comment]
Thanks! This command is a real time saver for me.
