### ISSUE TITLE
different number of normal processes on 2 servers

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#534]
It is not an issue, but after searching many info on the internet, I still cannot find the reason.

That is, one of my server is using 4 rspamd normal processes while the other using 2 .

root:~# ps aux | grep rspam
root      1558  0.0  0.1  65800  5172 ?        Ss   17:06   0:00 rspamd: main process              
root      1559  0.0  0.1 157584  6908 ?        S    17:06   0:00 rspamd: controller process        
root      1560  0.0  0.1 157568  6828 ?        S    17:06   0:00 rspamd: normal process            
root      1561  0.0  0.1 157568  6832 ?        S    17:06   0:00 rspamd: normal process            
root      1563  0.0  0.1 157568  6836 ?        S    17:06   0:00 rspamd: normal process            
root      1564  0.0  0.1 157568  6840 ?        S    17:06   0:00 rspamd: normal process 

the other :
root:/tmp/install# ps aux | grep rspam
root      3648  0.0  0.0   3884   612 pts/2    RN+  17:09   0:00 grep rspam
root     30156  0.0  0.1  65804  4484 ?        SNs  12:06   0:00 rspamd: main process              
root     30158  0.0  1.6 158792 65048 ?        SN   12:06   0:00 rspamd: controller process        
root     30159  0.0  1.4 159932 57548 ?        SN   12:06   0:09 rspamd: normal process            
root     30160  0.0  0.5 159064 23856 ?        SN   12:06   0:01 rspamd: normal process

The two servers are both using 4Gb ram, but have different number of processes.

Can anyone help?  Thanks.

**Comment by fatalbanana** [comment]
Should match number of cores on the system (see `cat /proc/cpuinfo`).

**Comment by mozzan** [comment]
Is this setting can be changed by config?

**Comment by fatalbanana** [comment]
Yes, you can set `count = 2;` or similar in `worker {}` configuration for `normal` worker (possibly by editting `worker-normal.inc` depending on your existing configuration & personal preference).

**Comment by mozzan** [comment]
Problem solved. Thank you for the reply.
