### ISSUE TITLE
Redis and rspamd

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#537]
Rspamd crash if redis-server stoped. :(

Feb 23 01:50:39 isp1 rspamd[7352]: <9885f2>; main; rspamd_cld_handler: normal process 7458 terminated abnormally by signal: 6 but NOT created core file

**Comment by vstakhov** [comment]
Any chances to get a backtrace from core? Signal 6 means programmatic assertion - so it's just an unhandled path in the code.

**Comment by AlexeySa** [comment]
gdb:
(gdb) bt
#0  0x00007f27026cc625 in raise () from /lib64/libc.so.6
#1  0x00007f27026cde05 in abort () from /lib64/libc.so.6
#2  0x00007f270270a537 in __libc_message () from /lib64/libc.so.6
#3  0x00007f270270ff4e in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f2702712cf0 in _int_free () from /lib64/libc.so.6
#5  0x0000000000465af0 in lua_redis_free_args (args=0x27999c0, nargs=6)
    at /root/src/rspamd/rspamd-1.2.0/src/lua/lua_redis.c:116
#6  0x0000000000465e77 in lua_redis_dtor (ctx=0x2487220) at /root/src/rspamd/rspamd-1.2.0/src/lua/lua_redis.c:134
#7  0x00007f2702d04f0c in event_process_active_single_queue (base=0x27add80, flags=0) at event.c:1368
#8  event_process_active (base=0x27add80, flags=0) at event.c:1438
#9  event_base_loop (base=0x27add80, flags=0) at event.c:1639
#10 0x000000000042cb99 in start_worker (worker=0x2743a50) at /root/src/rspamd/rspamd-1.2.0/src/worker.c:436
#11 0x000000000048dec6 in rspamd_fork_worker (rspamd_main=0x24818e0, cf=0x25528b0, index=5, ev_base=0x27add80)
    at /root/src/rspamd/rspamd-1.2.0/src/libserver/worker_util.c:541
#12 0x0000000000429515 in spawn_worker_type (rspamd_main=0x24818e0, ev_base=0x27add80, cf=0x25528b0)
    at /root/src/rspamd/rspamd-1.2.0/src/rspamd.c:446
#13 0x000000000042985e in spawn_workers (rspamd_main=0x24818e0, ev_base=0x27add80)
    at /root/src/rspamd/rspamd-1.2.0/src/rspamd.c:524
#14 0x000000000042a448 in main (argc=1, argv=0x7ffe39a65778, env=<value optimized out>)
    at /root/src/rspamd/rspamd-1.2.0/src/rspamd.c:1219

strace:
======= Backtrace: =========
/lib64/libc.so.6(+0x75f4e)[0x7f1b4f85ff4e]
/lib64/libc.so.6(+0x78cf0)[0x7f1b4f862cf0]
rspamd: normal process[0x465af0]
rspamd: normal process[0x465e77]
/usr/local/rspamd/lib/rspamd/libevent-2.0.so.5(event_base_loop+0x53c)[0x7f1b4fe54f0c]
rspamd: normal process(start_worker+0xd9)[0x42cb99]
rspamd: normal process(rspamd_fork_worker+0x1f6)[0x48dec6]
rspamd: normal process[0x429515]
rspamd: normal process[0x42985e]
rspamd: normal process(main+0x918)[0x42a448]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f1b4f808d5d]
rspamd: normal process[0x421669]

**Comment by vstakhov** [comment]
Ow, I've found this issue.

**Comment by vstakhov** [comment]
Could you please test the recent master branch (packaged as well)?

**Comment by AlexeySa** [comment]
Thank you! Issue is solved!
