### ISSUE TITLE
RBL doesn't perform like spamassassin 

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#539]
I have a letter which contains an Ip (204.80.91.124) which is in black list of barracudacentral. (http://www.barracudacentral.org/lookups/lookup-reputation).

However, rspamd doesn't correctly point that out while spamassassin does.

My RBL module with barracudacentral is fine because it can find out the black list ip with some mails.

Header : 
Return-Path: bounce@eigroup.co.in
X-Original-To: xx@xxxxxxx.com.tw
Delivered-To: xx@xxxxxx.com.tw
Received: by xxx.xxxxxxxx.com.tw (Postfix, from userid 98)
        id DF5CC1AF0A7; Tue, 23 Feb 2016 04:00:11 +0800 (CST)
Received: from **mail3.eigroup.co.in (unknown [204.80.91.124])**
        by xxx.xxxxxx.com.tw (Postfix) with ESMTP id B4BF31A116F
        for xx@xxxxxxx.com.tw; Tue, 23 Feb 2016 03:59:57 +0800 (CST)
Received: from newsletter1.eigroup.co.in (unknown [192.168.199.102])
        (Authenticated sender: newsletter@eigroup.co.in)
        by mail3.eigroup.co.in (cnmarketpro) with ESMTPA id 7CFEE61F9A
        for sales@xxxxxx.com.tw; Mon, 22 Feb 2016 13:59:38 -0600 (CST)
DKIM-Signature: v=1; a=rsa-sha1; c=simple/simple; d=eigroup.co.in; s=mail;
        t=1456171178; bh=Nnz1hO8fSgW8MiRYVTNegEzy8Ms=;
        h=Date:To:From:Reply-to:Subject:List-Unsubscribe;
        b=WU3QfgLqvyTI4+T7vsIc9GAM+T0tuvosRrK1x/s//uJvISdZneihx//ST0uxy6bz1
         q292erBza3/QWNuPUpy3u7ZtgmCDedRjrq29GpOdYZqJ29xHeQcUY+GIP7Akd3ZSVo
         cg7eMJE6j+WMk0axQbjZrpCgKp8frTu14wj935xMG6Bu7n7RYIq5o7pK4PpZ+TyxCD
         llOtDxTcAZ17sPAMK8TquY4CXmOY18fYLvWQyxofO/4kJ6Ikipr50Bew3KQswhwHlo
         nMTIiNegCLG0Z/rlKXIYPOqnCoD98IwNrcabxi4ZVuQi+hX4FQayS4k7nSEUd0NYOK
         HiiP/a4qRhEsA==
Date: Tue, 23 Feb 2016 01:29:55 +0580

rspamd score : 
[Metric: default]
Spam: false
Score: 3.97 / 15.00
Action: no action
Symbol: BAYES_SPAM (2.77)[97.92%]
Symbol: DMARC_POLICY_SOFTFAIL (0.10)[Eigroup.Co.In]
Symbol: FORGED_SENDER (0.30)
Symbol: MIME_GOOD (-0.10)[multipart/alternative, text/plain]
Symbol: R_DKIM_ALLOW (-1.10)[eigroup.co.in]
Symbol: R_PARTS_DIFFER (2.00)[0%]
Message-ID: ec1a4273995b91b0e372629806325ab0@localhost.localdomain

spamassassin score : 6.5/5.0 
  **2.0 RCVD_IN_BRBL_LASTEXT   RBL: No description available.
                            [204.80.91.124 listed in bb.barracudacentral.org]**
 1.4 BUG6152_INVALID_DATE_TZ_ABSURD No description available.
 0.6 INVALID_DATE_TZ_ABSURD Invalid Date: header (timezone does not exist)
 0.5 L_SPAM_TOOL_13         No description available.
-0.0 SPF_PASS               SPF: sender matches SPF record
 0.0 HTML_IMAGE_RATIO_08    BODY: HTML has a low ratio of text to image area
 0.7 MPART_ALT_DIFF         BODY: HTML and text parts are different
 0.0 MIME_HTML_MOSTLY       BODY: Multipart message mostly text/html MIME
 0.0 HTML_MESSAGE           BODY: HTML included in message
 0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily valid
-0.1 DKIM_VALID             Message has at least one valid DKIM or DK signature
-0.1 DKIM_VALID_AU          Message has a valid DKIM or DK signature from author's
                            domain
 1.3 RDNS_NONE              Delivered to internal network by a host with no rDNS

bb.barracudacentral.org  wasn't in the default configuration rspamd provided. I added it manually.

Config : 
rbl {
   ....
  rbls {
  ...
    brbl {
                        symbol = RCVD_IN_BRBL_LASTEXT;
                        rbl = "bb.barracudacentral.org";
                }
  }
}

Mail :  https://www.dropbox.com/s/9r3c6s78fhl1vhp/spam6.eml?dl=0

I don't know if this is a bug or not. 
Thanks.

**Comment by fatalbanana** [comment]
Not a bug: rspamd is not intended to be a clone of SpamAssassin - so it will not do all the same checks.

You can of-course configure rspamd to check this particular RBL as you've done.

**Comment by vstakhov** [comment]
@fatalbanana: the difference here is that is SA all RBL checks are performed against all received headers. In rspamd, on the contrary, you can select between the two options: either check all received headers (by specifying `received = true` for a particular RBL element) or to check merely sender's IP address.

**Comment by fatalbanana** [comment]
It looks like the OP received mail directly from the listed system though, so if they have proper MTA integration (eg. Rmilter/Exim/Haraka) then it should find that.

Setting both of `from` and `received` on a single RBL should work though it's unlikely to make sense to do that.

**Comment by vstakhov** [comment]
Ah, that's true.

**Comment by mozzan** [comment]
Yes, I set default_received = true then it can find the IP.
But I got another letter which has multiple Received header, it seems not finding the black list IP.

Letter : 
Return-Path: <gengl@xhby.net>
X-Original-To: xx@xxxxxx.com.tw
Delivered-To: xx@xxxxxx.com.tw
Received: by xx.xxxxxx.com.tw (Postfix, from userid 98)
        id 02DF21B4149; Tue, 23 Feb 2016 20:12:45 +0800 (CST)
Received: from eyou.net (unknown [222.190.113.19])
        by xx.xxxxxxx.com.tw (Postfix) with SMTP id 40D861EAF62
        for <xxx@xxxxxx.com.tw>; Tue, 23 Feb 2016 20:12:41 +0800 (CST)
X-EYOU-SPAMVALUE:0
X-EMDG-ORIGINAL-FROM:<gengl@xhby.net>
X-EMDG-ORIGINAL-TO:<xx@xxxxxx.com.tw>
X-EMDG-ORIGINAL-IP:115.192.123.19
X-EMDG-VER:4.1.1
X-EMDG-ABROAD:no
Received: (eyou anti_spam gateway 4.1.0); Tue, 23 Feb 2016 17:49:43 +0800
X-EMDG-MID: <656220983.16675@eyou.net>
X-EMDG-SMTPAUTH: gengl@xhby.net
Received: from **115.192.123.19** by 10.200.5.141 with SMTP; Tue, 23 Feb 2016 17:49:43 +0800
Message-ID: <20160223174407387013@xhby.net>
From: "HR" <gengl@xhby.net>
To: <tomi.tuominen@f-secure.com>
Subject: =?utf-8?B?6L+d57qq6L+d6KeE6Zeu6aKY5ZGY5bel5aSE55CG77ybSFI=?=
Date: Tue, 23 Feb 2016 17:44:00 +0800
MIME-Version: 1.0
Content-Type: multipart/mixed;
        boundary="----=_NextPart_000_0839_01982475.1F8378E0"
X-mailer: Adizhzm 7
Disposition-Notification-To: 18673690388@163.com

rspamd score :
Spam: false
Score: 4.90 / 15.00
Action: greylist
Symbol: HEADER_FORGED_MDN (2.00)
Symbol: MIME_GOOD (-0.10)[multipart/mixed, multipart/alternative, text/plain]
Symbol: SUBJ_ALL_CAPS (3.00)
Message-ID: 20160223174407387013@xhby.net

spamassassin :
 pts rule name              description
---- ---------------------- --------------------------------------------------
** 1.3 RCVD_IN_BL_SPAMCOP_NET RBL: Received via a relay in bl.spamcop.net
              [Blocked - see <http://www.spamcop.net/bl.shtml?115.192.123.19>]**
 0.7 SPF_HELO_SOFTFAIL      SPF: HELO does not match SPF record (softfail)
 2.0 BAYES_80               BODY: Bayes spam probability is 80 to 95%
                            [score: 0.8858]
 0.0 HTML_MESSAGE           BODY: HTML included in message
 1.0 HTML_FONT_FACE_BAD     BODY: HTML font face is not a word
 0.8 RDNS_NONE              Delivered to internal network by a host with no rDNS
 1.0 RCVD_DOUBLE_IP_LOOSE   Received: by and from look like IP addresses


If I move the IP (115.192.123.19) to the first Received Header like :
Return-Path: <gengl@xhby.net>
X-Original-To: xx@xxxxxx.com.tw
Delivered-To: xx@xxxxxx.com.tw
Received: by xx.xxxxxx.com.tw (Postfix, from userid 98)
        id 02DF21B4149; Tue, 23 Feb 2016 20:12:45 +0800 (CST)
Received: from eyou.net (unknown [**115.192.123.19**])

I got following score :
Spam: true
Score: 44.89 / 15.00
Action: reject
Symbol: HEADER_FORGED_MDN (2.00)
Symbol: MIME_GOOD (-0.10)[multipart/mixed, multipart/alternative, text/plain]
Symbol: RBL_SPAMHAUS_PBL1 (10.00)
Symbol: RBL_SPAMHAUS_XBL_ANY (10.00)
Symbol: RCVD_IN_BL_SPAMCOP_NET (10.00)
Symbol: RCVD_IN_BRBL_LASTEXT (10.00)
Symbol: SUBJ_ALL_CAPS (3.00)
Message-ID: 20160223174407387013@xhby.net

It seems that it didn't reach the last Received Header ?
Thanks.

**Comment by fatalbanana** [comment]
Guessing you're using `rmilter` and you received mail directly from the listed system(?), you shouldn't _need_ to check `Received` headers to get a hit. Also be aware that setting `default_received` will change behaviour of /all/ configured RBLs (or those without `received = false` anyway) and may have unintended consequences.

Not sure about the second issue: maybe it stops processing when it finds something that doesn't look like a `Received:` header, have not tested this. This seems unrelated to the original issue so may warrant a different report. It would at least be nice to understand why you've encountered the original issue (not using `rmilter`?).

**Comment by mozzan** [comment]
No, I'm not using rmilter. Just with postfix.

**Comment by fatalbanana** [comment]
How have you integrated rspamd then? For best results I'd recommend to adopt rmilter or if possible fix your integration.

**Comment by fatalbanana** [comment]
In the case of the second issue, problem seems to be that the Received header in question is not understandable by rspamd (it can be expected that it won't understand every variation of these):

```Received: from 115.192.123.19 by 10.200.5.141 with SMTP; Tue, 23 Feb 2016 17:49:43 +0800```

**Comment by vstakhov** [comment]
1. If you don't use rmilter then don't be surprised by unexpected behaviour: rspamd was designed to work in some particular environment and you might want to customize rspamd for your custom environment accordingly
2. Don't expect that rspamd will parse any header that looks like received: rspamd can work with Postfix, Exim and qmail received headers. Customized received are just ignored as they are faked too frequently. And you should blame SMTP standard designers in this case. Again: received headers could be forged too easily so rspamd won't trust them ultimately.
