### ISSUE TITLE
https downloads key repo

### ISSUE THREAD

**Issue by le9i0nx** [vstakhov/rspamd#541]
https://rspamd.com/downloads.html#system2
The key is offered for downloading insecure protocol
```
wget -O- http://rspamd.com/apt-stable/gpg.key | apt-key add -
```
is changed to a secure protocol
```
wget -O- https://rspamd.com/apt-stable/gpg.key | apt-key add -
```
[https](https://rspamd.com/apt-stable/gpg.key)

**Comment by vstakhov** [comment]
Fixed (please notice that rspamd.com lives in another repo: https://github.com/vstakhov/rspamd.com)
