### ISSUE TITLE
SPF not checked

### ISSUE THREAD

**Issue by sativouf** [vstakhov/rspamd#542]
Hi,

Consequently to some emails not properly flagged as SPAM, I realised that they were not showing any R_SPF_FAIL.
Those mails were sent with a from @gmail.com, from a server that is not listed by Google's SPF records.
When I send to myself a "good" email from a genuine gmail account, a correct R_SPF_ALLOW does show up.

My test email is a simple (from an internet server not trusted by rmilter) : `(printf "ehlo bla\nmail from:<test@gmail.com>\nrcpt to:<addr@domain.tld>\ndata\ntest\n.\n") | nc mailserver 25`

FYI, the only place where gmail.com is statically setup in my config is at /etc/rspamd/modules.d/surbl.conf
I'm using the latest jessie version : 1.1.4-1~jessie

**Comment by vstakhov** [comment]
Rspamd uses SMTP from for SPF checks as far as I remember. It might be different from the real `From` header.

**Comment by sativouf** [comment]
You can see in my test with netcat that there is no `from` header within the email, only the `mail from` that is to be sent to the mail server, the `rcpt to`, and `data` with "test"
The resulting email is as follows (FYI, my spam level trigger is 6.0) : 

`Return-Path: <test@gmail.com>
Delivered-To: myemail
X-Quarantine-ID: <Ps1-KzA6abv1>
X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "Date"
Received: from bla (**** [x.x.x.x])
	by mailserver (Postfix) with ESMTP id 52EF0BB7
	for <myemail>; Mon, 29 Feb 2016 14:35:10 +0100 (CET)
X-Spamd-Result: default: False [11.80 / 100.00]
 MISSING_MID(2.50)
 MISSING_SUBJECT(2.00)
 HFILTER_HELO_5(2.00)
 MISSING_DATE(1.00)
 MIME_GOOD(-0.10)
 MISSING_TO(2.00)
 FORGED_SENDER(0.30)
 ONCE_RECEIVED(0.10)
 RBL_SPAMHAUS_PBL1(2.00)
X-Spamd-Bar: +++++++++++
X-Spam-Level: xxxxxxxxxxx
X-Spam-Status: Yes, score=11.8
X-Spamd-Server: localhost
X-Spamd-Scan-Time: 0.03
X-Spamd-Queue-ID: 52EF0BB7
X-Spam: yes
Message-Id: <20160229133511.784A9BB9@mailserver>
Date: Mon, 29 Feb 2016 14:35:11 +0100 (CET)
From: test@gmail.com

test`

**Comment by vstakhov** [comment]
Yes, it seems to be rspamd bug. I've fixed it in the `master` branch, thank you for report
