### ISSUE TITLE
Can I disable HFILTER_HOSTNAME_UNKNOWN when it's a private ip

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#545]
I have a letter which was sent from private ip.

But it was rejected. I want to disable HFILTER_HOSTNAME_UNKNOWN while the letter is from

private IP. Is it possible by changing config?

Or can I add negative scores when it's from private IP ?

Thanks.

Return-Path: 2012@xxxxxxxx.com.tw
Received: from scan.xxxxxxxx.com.tw (**unknown [192.168.195.254]**)
        by scan.xxxxxxxx.com.tw (Postfix) with ESMTP id 44A2D190345
        for sales@xxxxxxxx.com.tw; Thu,  3 Mar 2016 18:04:48 +0800 (CST)
Subject: =?UTF-8?B?55y+6IezVVRN6IiH5ZCI5Yuk5Lqk?=
 =?UTF-8?B?5o+b5Zmo5Y2U5ZCM6Ziy56am5pWZ6IKy6KiT57e0?=

**Comment by fatalbanana** [comment]
There isn't such support in hfilter itself but you could selectively (ie. for private IPs) set this symbol's weight to zero using settings module: https://rspamd.com/doc/configuration/settings.html
