### ISSUE TITLE
Why SUBJ_ALL_CAPS isn't in metrics.conf

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#548]
It might not be an issue. However, I'd like to know why SUBJ_ALL_CAPS isn't in metrics.conf?

Another question is if I want all scores in metrics.conf divided by 3 since the reject threshold with my server need to be 5. might there be some problems? I already know one because SUBJ_ALL_CAPS isn't in metrics.conf. Any other symbols are not in metrics.conf ?  Thanks.

**Comment by vstakhov** [comment]
You should not edit `metrics.conf` or any other condif file shipped with rspamd: https://rspamd.com/doc/quickstart.html#configuring-rspamd

There are couple of other symbols that are not in the `metric.conf`. I don't know any simple way to do what you want (about division by 3). You might add some custom post-filter which would change weights but that won't affect composite rules. This might be implemented in fact, but I'm not sure about the priority of such a task.
