### ISSUE TITLE
Phishing false positive?

### ISSUE THREAD

**Issue by kristous** [vstakhov/rspamd#549]
Not sure if it is a bug or misinterpretation from my side.
I do receive newsletters which get the PHISHING-flag, but when I inspect them I can't figure out what the reason is for this hit.

This newsletters seem all to be base64 encoded and do have href-lines like this:
`<br><a href="http://con.eyepinnews.com/include/unsubscribe.php?p=zc6bf001175e862241455274d9938c6e784eb75780f1986556fe36fc1d4" target="_blank">&raquo; Newsletter abbestellen</a>`

As there is no url in the text part the phishing module should leave this line alone, right?

Thanks
Christian

**Comment by fatalbanana** [comment]
That doesn't seem to trigger PHISHING on 1.1.4 or master in my testing. Are you sure there's not something else in the mail you're missing? Parameters returned for PHISHING symbol when scanned with `rspamc` should indicate the phished domain.

**Comment by kristous** [comment]
Thanks for the rspamc-returned-parameters tip and sorry for bothering. 
Found it!
`<b>Weitere Informationen</b> zu CON&#8226;ECT Eventmanagement und allen CON&#8226;ECT-Veranstaltungen erhalten Sie unter <a href="http://con.eyepinnews.com/include/lcnt.php?p=zc6bf001175e86224145e74e441fda687cdfe355ded2bb3b007d" target="_blank"><strong>www.conect.at</strong></a>!`
