### ISSUE TITLE
RBL timeout and retransmits settings

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#551]
Does RBL have timeout and retransmits just like the settings in options.inc ?

I'm wondering because I found RBL sometimes not triggered, but I'm not sure what the problem is.

would it be helpful if I change the logging level to debug?

**Comment by fatalbanana** [comment]
RBL module will use timeout & retransmit settings from `options.inc` or equivalent.

Unfortunately it does not have useful [debug] logging at this time.
