### ISSUE TITLE
resolv.conf nameserver order/priority on Linux

### ISSUE THREAD

**Issue by Freeaqingme** [vstakhov/rspamd#552]
I have a /etc/resolv.conf file that looks as follows:

```
# File Managed by Puppet
domain mail.example.net
search example.net example.com 
nameserver 127.0.0.1
nameserver 80.69.67.66
nameserver 80.69.66.67


```

It seems rspamd uses all the nameservers with equal priority:

```
netstat -lantup | grep 53 | grep rspamd | awk '{print $5}' | cut -d ':' -f1 | sort | uniq -c 
     40 127.0.0.1
     40 80.69.66.67
     40 80.69.67.66
```

Even though, at least on Linux, '''man resolv.conf''' says:

```
If  there  are  multiple  servers,  the  resolver library queries them in the order listed.
```

As such, I'd expect to see all connections to 127.0.0.1 (assuming they're successful), and no connections to the other two nameservers.

Rspamd daemon version 1.2.0
Release id: 98ac7cd
Linux mx8 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

Edits: Formatting...

**Comment by vstakhov** [comment]
Your assumption is incorrect I'm afraid: rspamd uses `round-robin` rotation for servers in the `resolv.conf`. However, it is currently not available to specify custom rotation for `nameserver` option in rspamd itself and that should be fixed indeed.

**Comment by vstakhov** [comment]
In your case, you can set the only server to rspamd in `options -> dns` section and it won't read any servers from resolv.conf

**Comment by Freeaqingme** [comment]
> In your case, you can set the only server to rspamd in options -> dns section and it won't read any servers from resolv.conf

Didn't know about that, thanks!

**Comment by Freeaqingme** [comment]
Possibly related to the above. If I put this in my override config file:
```
options {
        dns {
                nameserver = "127.0.0.1:100";
                nameserver = "127.0.0.2:1";
        }
}
```

I see an equal number of connections to 127.0.0.1 and to 127.0.0.2, even though I'd expect about 100 times more connections to the first ip than to the second.

**Comment by vstakhov** [comment]
Ok, it's now possible to do something like that:

```
    dns {
        #nameserver = "master-slave:8.8.8.8;9.9.9.1";
        nameserver = "round-robin:8.8.8.8:53:100;8.8.8.1:53:1";
    };
```

Syntax is ugly, I know and I think about something more clear (keeping compatibility of course).

**Comment by Freeaqingme** [comment]
awesome!
