### ISSUE TITLE
Idea: number of unicode scripts

### ISSUE THREAD

**Issue by crepererum** [vstakhov/rspamd#553]
## Preface
With the wide adaption of Unicode in mail clients, the following "spam filter workaround" gets more common (removed some parts that are actually spam):
```
I'm so sorry sexy bear :))
i fou̐nd your prًofiͥle via faْcebook. You are handso̤me ...
are u hrny? sen͌d me a XXXXXXXX req֒uest so we h00kup..
the pag٘e is oْver there: XXXXXXX
I knoͥw what you want and I֬'m ready for you darling.. Sms me n̾ow @ XXXXX !!
I'm ready fo͝r chat!
```

That might be caught by the bayes filter but I think there is a way easier way to detect this, obviously spam-like, behaviour.

## Solution
[Unicode® Standard Annex #24](http://www.unicode.org/reports/tr24/) describes a property called `script` for every character, so a system can check to which language class a character belongs to. It is slightly uncommon to write mails with a huge number of different scripts, but for obfuscating mails this seems to be a common choice. So counting the number of used scripts per language (data file can be found [here](http://ftp.unicode.org/Public/UNIDATA/Scripts.txt)) you get a good metric if the mail contains rubbish or actual normal text. Something similar is done for security checks of mail addresses and usernames, see [Unicode® Technical Standard #39 -- 5.2 Restriction-Level Detection](http://www.unicode.org/reports/tr39/#Restriction_Level_Detection) and [Googles blog post](https://security.googleblog.com/2014/08/protecting-gmail-in-global-world.html).

## Technical discussion
While the data file mentioned above is rather small, it does not solve a specific problem: Unicode isn't a normalized representation. So we should apply one of the methods described in [Unicode® Standard Annex #15](http://unicode.org/reports/tr15/) (I suggest NFKC) before counting the number of scripts. *(TODO: File a separate issue about the this as a general pipeline-step)*

## Changelog
1. Initial version
2. Added technical section

**Comment by vstakhov** [comment]
There is `chartable` module that does exactly what you've described.
