### ISSUE TITLE
The permissions on the file is not safe.  /etc/rspamd/worker-controller.inc

### ISSUE THREAD

**Issue by le9i0nx** [vstakhov/rspamd#555]
https://github.com/vstakhov/rspamd/blob/master/conf/worker-controller.inc

```
root@smtp:/etc/rspamd# ls -la
total 176
...
-rw-r--r--   1 root root   157 Feb  6 23:13 worker-controller.inc
...
```

I think it will be safer.
At least one hit will not be able to read the password.
```
root@smtp:/etc/rspamd# ls -la
total 176
...
-rw-r-----   1 root _rspamd   157 Feb  6 23:13 worker-controller.inc
...
```

**Comment by vstakhov** [comment]
You should define your password in `local.d/worker-controller.inc` from rspamd 1.2 and you can set any permission you'd like on that file.

**Comment by le9i0nx** [comment]
Yes, I saw in the master branch changes in the configuration files.
Only here the version 1.2 there is still no.

Yes, after my first comments.
I tried to change the password for the Web interface.
And for some reason, any suitable even an empty password and allows you to change the settings.

**Comment by fatalbanana** [comment]
If you're proxying to the localhost (eg. from Apache/Nginx) you should remove loopback addresses from `secure_ip` setting.

**Comment by le9i0nx** [comment]
@fatalbanana 
Thank you helped.
