### ISSUE TITLE
is Return-Path's domain checked by surbl module?

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#558]
I'm wondering because in a letter, the return-path's domain "itjas.com" is on SURBL lists(WS).

But no SURBL related score report appears. 

http://www.surbl.org/surbl-analysis
SURBL Lookup Result:
itjas.com is on SURBL lists: WS 

Return-Path: **nicole@itjas.com**
Received: from ns27.Host1.yourdomainname.com (unknown [120.59.56.135])
        by xxx.xxxxxx.com.tw (Postfix) with ESMTP id 8D7571FF455
        for xx@xxxxxx.com; Thu, 17 Mar 2016 02:32:44 +0800 (CST)
X-Sender: "Nicole Marks" nicole@itjas.com
X-Receiver: xx@xxxxxx.com.tw

**Comment by vstakhov** [comment]
It is not checked because SURBL is `URL` map which is intended to check `URL` in messages and not their senders.
