### ISSUE TITLE
MIME_BAD_ATTACHMENT - too many false positives

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#561]
There are too many false positives with default rule configuration.

Message sample:
https://paste.rspamd.com/hCmx/raw
`Symbol: MIME_BAD_ATTACHMENT (4.00)[png]`

**Comment by vstakhov** [comment]
Hum, it is not intended to react to `image/png`. I'll check.

**Comment by moisseev** [comment]
It reacts to almost any attachment. I've seen pdf, tiff, xls, xlsx, xml.
