### ISSUE TITLE
Quickstart guide and dovecot-postfix

### ISSUE THREAD

**Issue by chuckpeters** [vstakhov/rspamd#573]
https://rspamd.com/doc/quickstart.html says:
apt-get install dovecot-imapd dovecot-postfix dovecot-sieve

The dovecot-postfix package does not exist in Debian, and hasn't been available in Ubuntu since precise (12.04LTS).  The old package is basically a meta package that pulls in mail-stack-delivery and 
dovecot-core
dovecot-imapd
dovecot-managesieved
dovecot-pop3d
postfix

mail-stack-delivery is also a meta package, but it is not available in Debian.

You might want the following:
apt-get install dovecot-imapd dovecot-sieve dovecot-core dovecot-managesieved dovecot-pop3d postfix

**Comment by piwats** [comment]
IMHO the quickstart guide should be distribution agnostic.

Whoever came here to use rspamd has already a email server running.

**Comment by fatalbanana** [comment]
This seems to have been addressed.
