### ISSUE TITLE
Show Subject in UI History table

### ISSUE THREAD

**Issue by Friss** [vstakhov/rspamd#574]
It would be great to see the subject lines for the emails in the history table to get an idea / look at what's being rejected / accepted.

**Comment by fatalbanana** [comment]
[history_redis](https://rspamd.com/doc/modules/history_redis.html) provides this.

**Comment by supertin** [comment]
More info? Are you saying rspamd stores no subjects, but just the message ID by default? And we need a 3rd party database to get basic information like the subject?

**Comment by fatalbanana** [comment]
Yes- legacy history format has not changed. Redis history additionally stores Subject among other things; it's enabled by default but requires redis configuration.
