### ISSUE TITLE
False positive for FORGED_MUA_THEBAT_MSGID_UNKNOWN 

### ISSUE THREAD

**Issue by kristous** [vstakhov/rspamd#575]
Following my mail logs I found that my rspamd 1.2.1 gets a lot of FORGED_MUA_THEBAT_MSGID_UNKNOWN symbols.
After some investigation I found that this are (all?) false positivies.

I crafted a small testmail for testing:
`
Received: from server1.example.com (server1.example.com [1.2.3.4]) by localhost (Postfix) with ESMTP id 0000000;
Date: Tue, 29 Mar 2016 18:05:03 +0200
To: office@example.net
From: Info <info@example.com>
Reply-To: Info <info@example.com>
Subject: Newsletter 1
Message-ID: <e77e59d1aa5627d3dd88681028fb5f8c@www.example.com>
X-Mailer: PHPMailer 5.2.14 (https://github.com/PHPMailer/PHPMailer)
Precedence: bulk
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit
Return-Path: <info@example.com>
X-Rcpt-To: <office@example.net>

blablabl
`

Testing with rspamc gives:

Results for file: /tmp/test2.eml (0.125 seconds)
[Metric: default]
Spam: true
Score: 8.80 / 15.00
Action: add header
Symbol: FORGED_MUA_THEBAT_MSGID_UNKNOWN (3.00)
Symbol: HFILTER_HELO_UNKNOWN (2.00)
Symbol: INVALID_MSGID (1.70)
Symbol: MIME_HTML_ONLY (1.00)
Symbol: ONCE_RECEIVED (0.10)
Symbol: R_SPF_FAIL (1.00)[all]
Message: (SPF): spf fail
Message-ID: e77e59d1aa5627d3dd88681028fb5f8c@www.example.com

Unfortunately I was not able to find the problem in headers.lua

**Comment by vstakhov** [comment]
I can't reproduce your issue in my environment.

**Comment by kristous** [comment]
It must be some kind of race condition, same file same server 3 seconds apart:

root@mx2:/var/log# date && rspamc  /var/spool/rmilter/test3.eml 
Wed Mar 30 07:17:47 CEST 2016
Results for file: /var/spool/rmilter/test3.eml (0.160 seconds)
[Metric: default]
Spam: false
Score: 8.80 / 15.00
Action: greylist
Symbol: FORGED_MUA_THEBAT_MSGID_UNKNOWN (3.00)
Symbol: HFILTER_HELO_UNKNOWN (2.00)
Symbol: INVALID_MSGID (1.70)
Symbol: MIME_HTML_ONLY (1.00)
Symbol: ONCE_RECEIVED (0.10)
Symbol: R_SPF_FAIL (1.00)[all]
Message: (SPF): spf fail
Message-ID: e77e59d1aa5627d3dd88681028fb5f8c@www.example.com

root@mx2:/var/log# date && rspamc  /var/spool/rmilter/test3.eml 
Wed Mar 30 07:17:50 CEST 2016
Results for file: /var/spool/rmilter/test3.eml (0.012 seconds)
[Metric: default]
Spam: false
Score: 5.79 / 15.00
Action: greylist
Symbol: HFILTER_HELO_UNKNOWN (2.00)
Symbol: INVALID_MSGID (1.70)
Symbol: MIME_HTML_ONLY (1.00)
Symbol: ONCE_RECEIVED (0.10)
Symbol: R_SPF_FAIL (1.00)[all]
Message: (SPF): spf fail
Message-ID: e77e59d1aa5627d3dd88681028fb5f8c@www.example.com

My rmilter tempdir is on a tmpfs, my suspicion is that it happens more likely when I/O is fast.

**Comment by vstakhov** [comment]
Does it happen if you add `disable_hyperscan = yes` to the options section?

**Comment by kristous** [comment]
With `disable_hyperscan = yes` it does not happen.

Difference are the symbols FORGED_MUA_THEBAT_MSGID_UNKNOWN and INVALID_MSGID.

**Comment by vstakhov** [comment]
With hyperscan, does it happen at the beginning or all the time periodically?

**Comment by kristous** [comment]
With hyperscan it happens almost all the time.
I stopped postfix, restarted rspamd and tested with rspamc ~50 times with the same file.
Gives:
50 INVALID_MSGID
45 FORGED_MUA_THEBAT_MSGID_UNKNOWN

**Comment by vstakhov** [comment]
Does it happen on a single server or on both?

**Comment by vstakhov** [comment]
And are you using rspamd from git or from some stable version?

**Comment by kristous** [comment]
It happens on both servers.
rspamd installed from `deb http://rspamd.com/apt-stable/ jessie main`

On my private servers, which run on ubuntu 14.04, the problem does not exist.
On them the repo is `deb http://download.opensuse.org/repositories/home:/cebka/xUbuntu_14.04/ /`
The private servers do not have exactly the same configuration.

**Comment by vstakhov** [comment]
I've just tried debian jessie with exactly the same package and couldn't reproduce issue. Could you please enable debug logging and paste the full output of rspamd for some message that causes this problem?

**Comment by kristous** [comment]
Here is the debug log.
It includes start of rspamd, feeding with the test message and shutdown of rspamd.
It is very big but I was not sure which lines can be truncated.

[rspamd_debug.txt](https://github.com/vstakhov/rspamd/files/197027/rspamd_debug.txt)

**Comment by vstakhov** [comment]
I don't see that symbol inserted in the log you've provided. Please mention that hyperscan requires about 5-10 seconds to load. Before it's loaded all checks go via pcre.

**Comment by kristous** [comment]
next try
[rspamd_debug.txt](https://github.com/vstakhov/rspamd/files/197314/rspamd_debug.txt)

**Comment by vstakhov** [comment]
Could you please open `headers.lua` rules file and replace

```
reconf['FORGED_MUA_THEBAT_MSGID_UNKNOWN'] = string.format('(%s) & !(%s) & !(%s) & !(%s)', thebat_mua_any, thebat_msgid, thebat_msgid_common, unusable_msgid)
```

with

```
reconf['FORGED_MUA_THEBAT_MSGID_UNKNOWN'] = string.format('(%s) & !(%s) & !(%s)', thebat_mua_any, thebat_msgid, thebat_msgid_common)
```

I can't understand why it ignores the first component, I'm afraid. And I cannot reproduce it anywhere.

**Comment by kristous** [comment]
Sorry, was a little busy.
Just now I wanted to do the test and before I started I tried to reproduce it which I was not able to.
Turned out that in the meanwhile rspamd has been upgraded to 1.2.2 by our daily upgrade process and the problem disappeared without changing the line in headers.lua.
So one of the changes in 1.2.2 seems to fix the problem.
