### ISSUE TITLE
Possibilty to always set spam header

### ISSUE THREAD

**Issue by setiseta** [vstakhov/rspamd#580]
Hi,
I'm searching for a setting to always add the spam headers, to see more about the rating on each message.
maybe I'm wrong here and it should be in the rmilter repository, but I don't know aktually so I start here.

THx for feedback.
Greetings

**Comment by moisseev** [comment]
Did you mean `extended spam headers` like this?
~~~
X-Spamd-Result: default: False [-10.50 / 15.00]
 URIBL_BLOCKED(0.00)
 RWL_MAILSPIKE_GOOD(0.00)
 MIME_GOOD(-0.10)
~~~
rmilter.conf:
~~~nginx
spamd {
	extended_spam_headers = yes;
...
};
~~~

**Comment by setiseta** [comment]
oh yes, sorry haven't noticed this option.
