### ISSUE TITLE
Maillist: How do I add my own (any rfc conform) mailinglist to be recognized by rspamd?

### ISSUE THREAD

**Issue by piwats** [vstakhov/rspamd#584]
Hello,

I am running a mlmmj mailing list, where I am free to set whatever headers I wish.

Since I would like them to be RFC conform, I add all the necessary headers like List-*.

Editing the /usr/share/rspamd/lua/maillist.lua to fit cannot be a solution, since there is a /etc/rspamd/lua/rspamd.local.lua ruleset where such things, according to the documentation, do belong.

Now, if I create /etc/rspamd/lua/rspamd.local.lua with the following content

```lua
-- same as for cgp
local function check_ml_mlmmj(task)
  local header = task:get_header('X-Listserver')

  if not header or header ~= 'mlmmj' then
    return false
  end

  return check_rfc2919(task)
end


local function check_maillist(task)
  if check_ml_mlmmj(task) then
    task:insert_result(symbol, 1, 'mlmmj')
  end
end
```

emails checked against this seem not to be marked as maillist.

Indeed, if headers of a mailing list are rfc conform (i.e. RFC 2919 and/or RFC 2369), why doesn't rspamd automatically sets such email as coming from a mailing list? For example gentoo mailing lists are using mlmmj as their backend and the same thing happens to emails sent from them, too, although their headers seem to be quiet o.k..

So, how do I override some behaviour from the maillist lua module?

**Comment by vstakhov** [comment]
The only way to fix this issue so far is to update maillist plugin in the main rspamd repo I'm afraid.

**Comment by piwats** [comment]
Thank you. That is no problem at all.

I get FORGED_SENDER(0.30), FORGED_RECIPIENTS(2.00) on emails on the mailing list I run. Using the rspamd.com bayes spam/ham DBs, I get sometimes a bayes score of 3,99 on some emails, together with those forged symbols the overall score can rise over 4, which leads to emails processed by mlmmj being greylisted by rmilter. That is not so nice, as emails then get stuck or not processed furthermore (mlmmj is very lightweight, it doesn't put emails back into the postfix queue if anything goes wrong, or as here: greylisted).

As a workaround I have risen the greylisting metric to 6 to mitigate this behaviour and now I am looking to how to circumvent this behaviour by properly tuning rspamd.

At the moment I am learning what is where in rspamd, so maybe there is another way to tune the score.

**Comment by vstakhov** [comment]
I think this mailing list should be supported by maillist plugin indeed. Are there any specific headers that are added by mlmmj by default?

**Comment by piwats** [comment]
There are none headers added by default. That is good and maybe bad at the same time. (very lightweight in comparison to mailman, no deps)

I can add whatever headers I wish. I can let it pretend to be f.i. mailman or any other mailing list soft described in maillist.lua. I feel a little bit scared as I do not want to go offroad RFCs (why else do they exist?) and become non-compliant.

**Comment by piwats** [comment]
Thank you very much for the changes. A little question:

For these checks, does it matter in what specific order the headers appear in the mail?

**Comment by vstakhov** [comment]
No, order doesn't matter

**Comment by piwats** [comment]
I have rolled out this on my production servers, it does work now, mails from mailinglists are now handled properly. Therefore I think it is safe to close this one. Thank you.

**Comment by piwats** [comment]
Fixed. Thank you very much :+1:
