### ISSUE TITLE
Password of WebUI in GET

### ISSUE THREAD

**Issue by cimnine** [vstakhov/rspamd#585]
When the access to the WebUI requires a password, that password is from then on passed along some resources via GET. This is bad practice, because this way, the password might end up in an access log.

A least the following requests contain the password as ``?password=`` parameter:

* /auth?password=...
* /pie?password=...
* /history?password=...
* /maps?password=...
* /symbols?password=...
* /actions?password=...

The authentication should be performed on Cookie basis, or the password should at least get hashed on the browser side, e.g. using PBKDF2.

**Comment by vstakhov** [comment]
Rspamd does not save anything from GET paramenters in logs. 

Cookies require stateful sessions from the server's side which is complicated and I have absolutely no desire to implement that in rspamd. 

PBKDF could be a sollution indeed but it requires quite a lot of cryptography to be executed in javascript and I'm not very familiar with JS to tell the truth. 

Rspamd supports `Password` header and it was organized in this way initially. I can't remember now why that has been changed I'm afraid. The whole interface code is shit to my mind, but I have neither time nor experiences to write it properly (e.g. by using react/om/angular/whatever).

**Comment by fatalbanana** [comment]
GET parameters may likely be saved by reverse proxies like Apache/Nginx. The web interface should probably be making use of the `Password` header rather than a query string.

**Comment by cimnine** [comment]
@fatalbanana is totally right, and this is where I discovered that issue in the first place.

As a short-term solution, rspamd could switch to HTTP Basic-Auth. This is fairly trivial to implement and every browser understands it.

In the long term, rspamd could expose a clean REST API, preferably documented with something like Swagger. That would lay solid groundwork for a third-party to implement an improved UI. The API may also serve as nice integration point in the future, e.g. to learn spam/ham, monitoring, etc.

**Comment by assistcontrol** [comment]
This is a serious issue. The password to control rspamd is all over my nginx logs! Please, cut a new release with this patch!

**Comment by fatalbanana** [comment]
You could self-patch by replacing /usr/share/rspamd/www/js/rspamd.js (or equivalent file, depending on your installation) with https://raw.githubusercontent.com/vstakhov/rspamd/5c71b574aba4af3203358284a716061353c521bc/interface/js/rspamd.js

**Comment by vstakhov** [comment]
I'm polishing some last issues and will likely do a release tomorrow.
