### ISSUE TITLE
[BUG] fuzzy learn 

### ISSUE THREAD

**Issue by Dmitry55** [vstakhov/rspamd#587]
Looks like fuzzy storage remember only last learn

rspamc -w 100000000 -f 2 fuzzy_add /test/spam.eml
[Metric: default]
......
Symbol: FUZZY_PROB (5.00)[2:a97c0f752c:1.00, 2:a97c0f752c:1.00]
......

rspamc -w 1 -f 3 fuzzy_add /test/spam.eml
[Metric: default]
......
Symbol: FUZZY_WHITE (-0.55)[3:a97c0f752c:1.00, 3:a97c0f752c:1.00]
......

And fuzzy_del ignore flag
rspamc -f 1 fuzzy_del /test/spam.eml
[Metric: default]
......

**Comment by vstakhov** [comment]
It is technically impossible to have the same hash with the different flags. All further things are just consequences from this fact.
