### ISSUE TITLE
One rspamd webui for multiple instances of rspamd

### ISSUE THREAD

**Issue by piwats** [vstakhov/rspamd#590]
Hello,

I have here two instances of rspamd running, each on its own machine.

Is it possible to control the second rspamd instance from the webui of the first?
(Have one webui for both instances?)

Thank you in advance.

**Comment by moisseev** [comment]
What would it do and what functionality would it have over two browser tabs/windows?
What real problem are you trying to solve?

**Comment by piwats** [comment]
Nice centralized stats in the webui from all rspamd instances?

**Comment by piwats** [comment]
I think I'll take the ```rspamc -j stat``` output, which by the way is nice, of both instances and let it parse through icinga2. That will allow also to put the metrics/statistics into graphite... That is awesome from a monitoring design standpoint of view.

So, no need to get on with this one any further.

:)
