### ISSUE TITLE
X-Spamd-Server header: how to change the name of the host?

### ISSUE THREAD

**Issue by piwats** [vstakhov/rspamd#591]
When I tell rspamd to add headers to emails scanned, it does this as desired.

However, it would be nice to be able to rename the host in X-Spamd-Server header.

Rspamd runs on two different machines, each of them is bound to 127.0.0.1 (default configuration) which indeed resolves to localhost. 

At the moment, both rspamd instances add the headers as follows:

```
X-Spamd-Result: default: False [3.30 / 15.00]
 R_SPF_ALLOW(-1.50)
 RCVD_IN_DNSWL_HI(0.00)
 R_MISSING_CHARSET(5.00)
 MIME_HTML_ONLY(1.00)
 MIME_GOOD(-0.10)
 R_DKIM_ALLOW(-1.10)
X-Spamd-Bar: +++
X-Spam-Level: xxx
X-Spam-Status: No, score=3.3
X-Spamd-Server: localhost
```

X-Spamd-Server: localhost

For diagnostic purposes it would be great to be able to change the default hostname from localhost to something more distinctive, e.g. ```hostname/hostname -f```.

**Comment by piwats** [comment]
That is a rmilter story.

**Comment by fatalbanana** [comment]
Server name is taken from rmilter's `spamd { servers = ... }` setting. There is currently no possibility to set this to something else short of changing this setting.

**Comment by vstakhov** [comment]
It is possible to set your alias in `/etc/hosts` and use it here.

**Comment by fatalbanana** [comment]
Right. :)

**Comment by piwats** [comment]
That's a solution. Thanks everybody :)
