### ISSUE TITLE
Please clarify what "hacks" `url:is_obscured()` should detect

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#593]
It seems there is something wrong with the `url:is_obscured()` method, but it is not clear from the description what exactly it should detect.

[Method url:is_obscured()](https://rspamd.com/doc/lua/url.html#m21c54)

> Check whether URL is treated as obscured or obfusicated (e.g. **numbers in IP address** or other hacks)

The `url:is_obscured()` method treats these URIs as suspicious:

```
http://irr.ru/cars/passenger/special_offers/
http://www.alibaba.com/help/safety_security/policies_rules/others/002.html?tracelog=rowan&rowan_id1=buyerAcceptGoodsTimeoutRemindToBuyer_ru_RU_2016-04-14&rowan_msg_id=38747294980299$44ea6a88d1ed44fe9960877b03c82552&ck=in_edm_other
http://www.7dach.ru/tag/?q=%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D0%BA%D0%B8
http://feeback.hh.ru/?utm_source=3Demail&utm_medium=3Demail&utm_campaign=3Dall_app
http://hh.ru/subscribe?utm_source=3Demail&utm_medium=3Demail&utm_campaign=3Dind_webinarscert_170316
```

What's wrong with them?

**Comment by vstakhov** [comment]
Maybe there are some spaces in `href` tag if they come from HTML part?

**Comment by moisseev** [comment]
You are right, there are spaces before protocol "http":
~~~
<a href=" http://irr.ru/cars/passenger/special_offers/">
~~~
~~~
<a style=3D"color:#666666;text-decoration:none=
;font:12px/20px Arial, sans-serif;" class=3D"link footer-menu-link" href=3D=
" http://hh.ru/subscribe?utm_source=3Demail&utm_medium=3Demail&utm_campaign=
=3Dind_webinarscert_170316" target=3D"_blank">=D0=A3=D0=BF=D1=80=D0=B0=D0=
=B2=D0=BB=D0=B5=D0=BD=D0=B8=D0=B5 =D1=80=D0=B0=D1=81=D1=81=D1=8B=D0=BB=D0=
=BA=D0=BE=D0=B9</a>
~~~
~~~
<a style=3D"COLOR: #999; TEXT-DECORATION: under=
line" href=3D"http://www.alibaba.com/help/safety_security/policies_rules/ot=
hers/002.html?tracelog=3Drowan&rowan_id1=3DbuyerAcceptGoodsTimeoutRemindToB=
uyer_ru_RU_2016-04-14&rowan_msg_id=3D38747294980299$44ea6a88d1ed44fe9960877=
b03c82552&ck=3Din_edm_other" target=3D"_blank">=D0=9F=D1=80=D0=B0=D0=B2=D0=
=B8=D0=BB=D0=B0=D0=BC=D0=B8 =D0=BF=D0=BE=D0=BB=D1=8C=D0=B7=D0=BE=D0=B2=D0=
=B0=D0=BD=D0=B8=D1=8F</a>
~~~
But  in this tag there are no spaces:
~~~
<a href="http://www.7dach.ru/tag/?q=%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D0%BA%D0%B8">дорожки</a>
~~~

**Comment by vstakhov** [comment]
I cannot reproduce this issue with the text you've provided.

**Comment by moisseev** [comment]
Toss it, please. You can just paste the samples below into the WebUI to reproduce.

Space before "http":
~~~
--b1_9bbe7867a2fbda719c2a6e11c95d21f3
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 8bit

<a href=" http://irr.ru/cars/passenger/special_offers/">

--b1_9bbe7867a2fbda719c2a6e11c95d21f3--
~~~
Space before "http":
~~~
------=_Part_2211327_957449905.1460685645181
Content-Type: text/html;charset=utf-8
Content-Transfer-Encoding: quoted-printable

=B5=D1=81=D1=8C =D1=81 =D0=BD=D0=B0=D1=88=D0=B5=D0=B9 <a style=3D"COLOR: #9=
99; TEXT-DECORATION: underline" href=3D" http://www.alibaba.com/help/safety=
_security/policies_rules/others/001.html?tracelog=3Drowan&rowan_id1=3Dbuyer=
AcceptGoodsTimeoutRemindToBuyer_ru_RU_2016-04-14&rowan_msg_id=3D38747294980=
299$44ea6a88d1ed44fe9960877b03c82552&ck=3Din_edm_other" target=3D"_blank">=

------=_Part_2211327_957449905.1460685645181--
~~~
Space at the end of the reference:
~~~
--b1_9bbe7867a2fbda719c2a6e11c95d21f3
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 8bit

<a href="http://www.7dach.ru/tag/?q=%D1%81%D0%BD%D0%B8%D0%BC%D0%B0%D1%82%D1%8C+%D1%83%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5
 ">укрытия</a>.

--b1_9bbe7867a2fbda719c2a6e11c95d21f3--
~~~

**Comment by vstakhov** [comment]
It's obviously reproduced with spaces and it is the intended behaviour. Well, it is in my humble opinion, of course.

**Comment by moisseev** [comment]
Maybe the score of `6.0` is too high for this rule then? 
And what else should this rule detect besides spaces?

**Comment by vstakhov** [comment]
Initially this flag was triggered merely for urls with some obvious obfuscation, such as numeric or hex IP addresses in host. Maybe adding urls with spaces to this category was a mistake...

**Comment by moisseev** [comment]
* Spaces **at the start and end** of an URL are explicitly allowed by the w3c. I think they should be rather considered as minor imperfections than hacks. I can't imagine how such hacks could work. I think we should merely chop leading and trailing spaces from URL before doing this test.

W3C Recommendation 28 October 2014
[4.8.1 Links created by a and area elements](https://www.w3.org/TR/html5/links.html#links-created-by-a-and-area-elements)

> The href attribute on a and area elements must have a value that is **a valid URL potentially surrounded by spaces**.

* I'm not sure about using IP addresses instead of host names. Maybe score of `6.0` is too much for it. Sometimes it is not malicious, but poor design. For example, IP addresses in URLs are commonly encountered in information systems provided by government institution or their commercial contractors.

* Obfuscated links are common in some sort of bulk mail like this:
~~~
-----=_1460561271285673473
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html; charset=windows-1251

<br/><hr> Вы получили данное сообщение потому, что являетесь зарегистрированным клиентом портала Goszakaz.ru, предоставляющего информацию о тендерах и закупках. <br/><a href='http://www.zakupki.ru/unsubscribe/MREdNDc6/aW5mb0BTuyibnpuuvbnBshkkucnU=
'>Отписаться от рассылки</a>
--_----------=_1460561271285673473--
~~~
Score of `6.0` is too much for them too.

**Comment by vstakhov** [comment]
I have disabled this feature for urls with spaces. For IP urls this rule work merely when something from http://www.pc-help.org/obscure.htm this page triggers. E.g. numeric IP like http://100500/blah (and **NOT** http://192.168.0.0/blah)
