### ISSUE TITLE
New register_symbol() and once received plugin

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#602]
New style register_symbol() not working for ONCE_RECEIVED :(.

local id = rspamd_config:register_symbol({
 name = symbol,
 callback = check_quantity_received,
 type = 'callback',
})
ERROR on start rspamd: symcache; rspamd_symbols_cache_validate: symbol 'ONCE_RECEIVED' has its score defined but there is no corresponding rule registered

local id = rspamd_config:register_symbol(symbol, 1.0, check_quantity_received)
it's OK!

Last git version.

**Comment by vstakhov** [comment]
Oh yes, that shouldn't be `callback` obviously.
