### ISSUE TITLE
Pre-existing X-Spam* headers are passed through

### ISSUE THREAD

**Issue by assistcontrol** [vstakhov/rspamd#603]
An increasingly common trick for spammers is to pre-add X-Spam\* headers. This makes sieve/procmail rules tricky, because now there are two X-Spam-Score headers.

Other spam detection engines, including bogofilter and SpamAssassin, will remove previous copies of its spam headers, rather than just appending its own.

rspamd should consider doing this itself. I'd suggest either removing them entirely, or at least renaming it so that there aren't conflicting lines.

**Comment by piwats** [comment]
...without breaking DKIM...?

**Comment by vstakhov** [comment]
Rspamd does not modify any headers in a message. Moreover, it has no ways to modify a message. Rmilter calls `smfi_chgheader` which replace a header if it already exists, so there is no such issue for the recommended rspamd integration method.

**Comment by moisseev** [comment]
I don't know about `X-Spamd-Result`, but rmilter definitely doesn't replace `X-Spam` header. In the sample below `X-Spam` header was added by sender's MTA and wasn't replaced by rmilter.
~~~
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="1e9e206ac5dc10b54e5027e331a1"
X-Rambler-User: fsadf-sdfs0@rambler.ru/186.67.91.98
X-Spam: Yes
X-Spamd-Result: default: False [-4.23 / 15.00]
 RCVD_IN_DNSWL_NONE(0.00)
 R_DKIM_ALLOW(-1.10)
 DMARC_POLICY_ALLOW(-0.50)
 BAYES_HAM(-1.28)
 RBL_UCEPROTECT_LEVEL1(1.00)
 R_SPF_ALLOW(-1.50)
 RWL_MAILSPIKE_GOOD(0.00)
 DCC_BULK(2.00)
 IP_SCORE(-2.75)
 MIME_GOOD(-0.10)
X-Spamd-Bar: ----
X-Spam-Status: No, score=-4.2
X-Spamd-Server: 127.0.0.1
X-Spamd-Scan-Time: 1.59
X-Spamd-Queue-ID: 2DDCF61F8E
~~~

**Comment by vstakhov** [comment]
Rmilter doesn't replace a header if it considers a message innocent. Then no alteration is performed indeed.

**Comment by moisseev** [comment]
It make sense. Of course no one will intensionally mark its message as spam. But sometimes false positives happen on upstream servers. Considering e36bf64097a27ee6d0595b6923f9a811d49ddb09 it might be useful to rewrite existing `X-Spam: Yes` header with `X-Spam: No`.

**Comment by FelixSchwarz** [comment]
also there is the issue with "rspamc --mime". I filed a separate ticket about this (#633) - is my ticket a duplicate or should we track this separately?

**Comment by fatalbanana** [comment]
This has been addressed in rmilter through the addition of `task:set_rmilter_reply` - see example [here](https://rspamd.com/doc/migration.html).
