### ISSUE TITLE
Inconsistent identation in config files

### ISSUE THREAD

**Issue by IlyaSemenov** [vstakhov/rspamd#61]
conf/options.conf, conf/logging.conf and other config files have inconsistent identation, for instance:
```
# Logging setup

logging {
    level = "info";
    type = "file";
        filename = "$LOGDIR/rspamd.log"; <----- HERE
}
```

**Comment by fatalbanana** [comment]
Fixed in https://github.com/vstakhov/rspamd/commit/90df2efa3cffccbeac2b85623afef1b1cca91518
