### ISSUE TITLE
Some mails are recognized as spam, but after scanning with clamav some of them are delivered to my inbox - without extended headers or spam score 

### ISSUE THREAD

**Issue by tweidelt** [vstakhov/rspamd#610]
My configuration: 
Debian 8 with Postfix 2.11.3, Dovecot 2.2.13 + antispam plugin, clamav 0.99, rspamd 1.2.4, rmilter 1.61

With some of my mails everything works as expected, but others slip through. One example:

`Apr 27 16:09:29 secure postfix/smtpd[17695]: 01F128003B: client=unknown[181.174.189.181]
Apr 27 16:09:29 secure postfix/cleanup[17851]: 01F128003B: message-id=<1481301415802148111511310332270@8i28dgq.secratedating.date>
Apr 27 16:09:29 secure rmilter[31813]: mlfi_eom: 01F128003B: tempfile=/tmp/msg.XXtOS2Nz, size=27924
Apr 27 16:09:29 secure rspamd[18984]: <9773da>; task; accept_socket: accepted connection from 127.0.0.1 port 48366
Apr 27 16:09:29 secure rspamd[18984]: <9773da>; task; rspamd_message_parse: loaded message; id: <1481301415802148111511310332270@8i28dgq.secratedating.date>; queue-id: <undef>
Apr 27 16:09:29 secure rspamd[18984]: <9773da>; lua; once_received.lua:41: SMTP resolver failed to resolve: 181.189.174.181.in-addr.arpa is hosted-by.sered.net
Apr 27 16:09:29 secure rspamd[18984]: <9773da>; task; process_dns_results: <1481301415802148111511310332270@8i28dgq.secratedating.date> domain [secratedating.date.multi.uribl.com] is in surbl multi.uribl.com(1)
Apr 27 16:09:29 secure rspamd[18984]: <9773da>; task; process_dns_results: <1481301415802148111511310332270@8i28dgq.secratedating.date> domain [secratedating.date] is in surbl sbl.spamhaus.org(300007f)
Apr 27 16:09:29 secure rspamd[18984]: <9773da>; task; process_dns_results: <1481301415802148111511310332270@8i28dgq.secratedating.date> domain [secratedating.date.dbl.spamhaus.org] is in surbl dbl.spamhaus.org(201007f)
Apr 27 16:09:31 secure rspamd[18984]: <9773da>; task; fuzzy_check_timer_callback: got IO timeout with server rspamd.com, after 3 retransmits
Apr 27 16:09:31 secure rspamd[18984]: <9773da>; task; rspamd_task_write_log: id: <1481301415802148111511310332270@8i28dgq.secratedating.date>, ip: 181.174.189.181, from: <christenpress@secratedating.date>, (default: T (reject): [18.50/15.00] [RBL_SPAMHAUS_CSS,DBL_SPAM,BAYES_HAM,URIBL_BLOCKED,HFILTER_HOSTNAME_UNKNOWN,RBL_MAILSPIKE_WORST,HFILTER_HELO_UNKNOWN,MIME_GOOD,ONCE_RECEIVED,URIBL_SBL_CSS]), len: 27924, time: 2425.046ms real, 93.731ms virtual, dns req: 30
Apr 27 16:09:31 secure rmilter[31813]: clamscan: scan 0.018131, /var/run/clamav/clamd.ctl, /tmp/msg.XXtOS2Nz
Apr 27 16:09:31 secure postfix/qmgr[18278]: 01F128003B: from=<ChristenPress@secratedating.date>, size=27965, nrcpt=1 (queue active)
Apr 27 16:09:31 secure dovecot: lda(tobias@weidelt.de): sieve: msgid=<1481301415802148111511310332270@8i28dgq.secratedating.date>: stored mail into mailbox 'INBOX'`

As you can see, rspamd gave this message 18.5 of 15 needed score points - and tells that this mails should be rejected. After that a virus scan is performed - and finally the mail is deliverd to my mailbox.

In other cases it works, an example for that:

`Apr 27 10:20:05 secure postfix/smtpd[10771]: warning: hostname hosted.by.serveo.nl does not resolve to address 195.10.212.10: Name or service not known
Apr 27 10:20:05 secure postfix/smtpd[10771]: connect from unknown[195.10.212.10]
Apr 27 10:20:05 secure policyd-spf[10776]: None; identity=helo; client-ip=195.10.212.10; helo=sacristy.dominicvacate.trade; envelope-from=travelthedominicanr
epublic@dominicvacate.trade; receiver=tobias@weidelt.de
Apr 27 10:20:05 secure policyd-spf[10776]: None; identity=mailfrom; client-ip=195.10.212.10; helo=sacristy.dominicvacate.trade; envelope-from=travelthedomini
canrepublic@dominicvacate.trade; receiver=tobias@weidelt.de
Apr 27 10:20:05 secure postfix/smtpd[10771]: 434F78003B: client=unknown[195.10.212.10]
Apr 27 10:20:05 secure postfix/cleanup[10864]: 434F78003B: message-id=<0d330a11f0ee504d90faefca25cfbff8@y.dominicvacate.trade>
Apr 27 10:20:05 secure rmilter[31813]: mlfi_eom: 434F78003B: tempfile=/tmp/msg.XXdPBapK, size=8351
Apr 27 10:20:05 secure rspamd[18982]: <dbd283>; task; accept_socket: accepted connection from 127.0.0.1 port 60183
Apr 27 10:20:05 secure rspamd[18982]: <dbd283>; task; rspamd_message_parse: loaded message; id: <0d330a11f0ee504d90faefca25cfbff8@y.dominicvacate.trade>; que
ue-id: <434F78003B>
Apr 27 10:20:05 secure rspamd[18982]: <dbd283>; task; process_dns_results: <0d330a11f0ee504d90faefca25cfbff8@y.dominicvacate.trade> domain [dominicvacate.tra
de.multi.uribl.com] is in surbl multi.uribl.com(1)
Apr 27 10:20:05 secure rspamd[18982]: <dbd283>; lua; once_received.lua:41: SMTP resolver failed to resolve: 10.212.10.195.in-addr.arpa is hosted.by.serveo.nl
Apr 27 10:20:05 secure rspamd[18982]: <dbd283>; task; process_dns_results: <0d330a11f0ee504d90faefca25cfbff8@y.dominicvacate.trade> domain [dominicvacate.trade] is in surbl sbl.spamhaus.org(300007f)
Apr 27 10:20:05 secure rspamd[18982]: <dbd283>; task; process_dns_results: <0d330a11f0ee504d90faefca25cfbff8@y.dominicvacate.trade> domain [dominicvacate.trade.dbl.spamhaus.org] is in surbl dbl.spamhaus.org(201007f)
Apr 27 10:20:07 secure rspamd[18982]: <dbd283>; task; fuzzy_check_timer_callback: got IO timeout with server rspamd.com, after 3 retransmits
Apr 27 10:20:07 secure rspamd[18982]: <dbd283>; bayes; inv_chi_square: exp overflow
Apr 27 10:20:07 secure rspamd[18982]: <dbd283>; task; rspamd_task_write_log: id: <0d330a11f0ee504d90faefca25cfbff8@y.dominicvacate.trade>, qid: <434F78003B>, ip: 195.10.212.10, from: <travelthedominicanrepublic@dominicvacate.trade>, (default: T (reject): [21.50/15.00] [RBL_SPAMHAUS_CSS,DBL_SPAM,URIBL_BLOCKED,RWL_MAILSPIKE_POSSIBLE,HFILTER_HOSTNAME_UNKNOWN,BAYES_SPAM,MIME_GOOD,ONCE_RECEIVED,URIBL_SBL_CSS]), len: 8351, time: 2191.041ms real, 55.219ms virtual, dns req: 33
Apr 27 10:20:07 secure rmilter[31813]: spamdscan: scan qid: <434F78003B>, mid: <0d330a11f0ee504d90faefca25cfbff8@y.dominicvacate.trade>, 2.191018, localhost, metric: default: [21.500000 / 15.000000], symbols: URIBL_SBL_CSS(6.50), ONCE_RECEIVED(0.10), MIME_GOOD(-0.10), BAYES_SPAM(4.00), HFILTER_HOSTNAME_UNKNOWN(2.50), RWL_MAILSPIKE_POSSIBLE(0.00), URIBL_BLOCKED(0.00), DBL_SPAM(6.50), RBL_SPAMHAUS_CSS(2.00)
Apr 27 10:20:07 secure rmilter[31813]: mlfi_eom: 434F78003B: rejecting spam
Apr 27 10:20:07 secure postfix/cleanup[10864]: 434F78003B: milter-reject: END-OF-MESSAGE from unknown[195.10.212.10]: 5.7.1 Spam message rejected; If this is not spam contact abuse; from=<travelthedominicanrepublic@dominicvacate.trade> to=<tobias@weidelt.de> proto=ESMTP helo=<sacristy.dominicvacate.trade>
Apr 27 10:20:07 secure postfix/smtpd[10771]: disconnect from unknown[195.10.212.10]
`

Do you have an idea what's wrong? I can provide you with configuration files if needed.

**Comment by tweidelt** [comment]
Headers of the first (non-working) mail:

`Return-Path: <ChristenPress@secratedating.date>
Delivered-To: tobias@weidelt.de
Received-SPF: None (no SPF record) identity=mailfrom; client-ip=181.174.189.181; helo=00065e03.secratedating.date; envelope-from=christenpress@secratedating.date; receiver=tobias@weidelt.de 
Received: from 00065e03.secratedating.date (unknown [181.174.189.181])
	by secure.weidelt.de (Postfix) with ESMTP id 01F128003B
	for <tobias@weidelt.de>; Wed, 27 Apr 2016 16:09:28 +0000 (UTC)
Received: from 00065e03.8i28dgq.secratedating.date ([127.0.0.1]:7481 helo=8i28dgq.secratedating.date)
	by 8i28dgq.secratedating.date with ESMTP id 00MLNHHP065EYWUHTA03;
	for <tobias@weidelt.de>; Wed, 27 Apr 2016 18:09:28 00200
To: <tobias@weidelt.de>
Message-ID: <1481301415802148111511310332270@8i28dgq.secratedating.date>
Date: Wed, 27 Apr 2016 18:09:28 00200
From: "Christen Press" <ChristenPress@secratedating.date>
Subject: Go From Average Guy To God Of Multiple Orgasms This Weekend
Content-Language: en-us
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Content-Type: multipart/alternative;
	boundary="----=Part.667.9286.1461773368"
X-Spamd-Server: localhost
X-Spamd-Scan-Time: 2.43
X-Spamd-Queue-ID: 01F128003B

------=Part.667.9286.1461773368
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset="UTF-8"

***Go From Average Guy To God Of Multiple Orgasms This Weekend***`

**Comment by vstakhov** [comment]
That should be fixed in rmilter 1.8.3

**Comment by tweidelt** [comment]
Hello Vsevolod,

thank you for your fast help. With this fix rspamd und rmilter work 
perfectly now for me.

Kind regards

Tobias Weidelt

Am 30.04.2016 um 16:14 schrieb Vsevolod Stakhov:
>
> That should be fixed in rmilter 1.8.3
>
