### ISSUE TITLE
rspamc + dovecot-antispam: run program failed with exit code 127

### ISSUE THREAD

**Issue by posledov** [vstakhov/rspamd#620]
`cat /etc/debian_version`

> 8.4

`# dovecot --version`

> 2.2.13

`# apt-cache show dovecot-antispam | grep Version`

> Version: 2.0+20130912-2

`# rspamd --version`

> Rspamd daemon version 1.2.6

`# netstat -nltp | grep 1133`

> tcp        0      0 127.0.0.1:11332         0.0.0.0:\*               LISTEN      2176/rmilter
> tcp        0      0 0.0.0.0:11333           0.0.0.0:\*               LISTEN      1/init
> tcp        0      0 0.0.0.0:11334           0.0.0.0:\*               LISTEN      1/init

`# /usr/bin/rspamc -h 127.0.0.1:11334 stat`

> Results for command: stat (0.221 seconds)
> Messages scanned: 43
> Messages with action reject: 4, 9.30%
> Messages with action soft reject: 0, 0.00%
> Messages with action rewrite subject: 0, 0.00%
> Messages with action add header: 8, 18.60%
> Messages with action greylist: 1, 2.32%
> Messages with action no action: 30, 69.76%
> Messages treated as spam: 12, 27.90%
> Messages treated as ham: 31, 72.09%
> Messages learned: 1
> Connections count: 21
> Control connections count: 3355
> Pools allocated: 3413
> Pools freed: 3387
> Bytes allocated: 871k
> Memory chunks allocated: 91
> Shared chunks allocated: 11
> Chunks freed: 0
> Oversized chunks: 1
> Fuzzy hashes stored: 0
> Fuzzy hashes expired: 0
> Statfile: BAYES_SPAM type: sqlite3; length: 54.27k; free blocks: 0; total blocks: 646; free: 0.00%; learned: 1; users: 1; languages: 1
> Statfile: BAYES_HAM type: sqlite3; length: 9.21k; free blocks: 0; total blocks: 0; free: 0.00%; learned: 0; users: 1; languages: 1
> Total learns: 1

`egrep -v '^#' /etc/dovecot/conf.d/90-plugin.conf`

> plugin {
>         antispam_verbose_debug                                  = 1
>         antispam_debug_target                                   = syslog
>         antispam_backend                                                = pipe
>         antispam_spam                                                   = Junk
>         antispam_trash                                                  = Trash
>         antispam_pipe_program                                  = /usr/bin/rspamc
>         antispam_pipe_program_args                             = -b;127.0.0.1;-h;127.0.0.1:11334
>         antispam_pipe_program_spam_arg                 = learn_spam
>         antispam_pipe_program_notspam_arg              = learn_ham
> }

while attempting to move a letter to the Spam folder, it is appears in the log:

> May  5 17:59:55 talk imap: antispam: mailbox_is_unsure(Junk): 0 
> May  5 17:59:55 talk imap: antispam: mailbox_is_trash(INBOX): 0 
> May  5 17:59:55 talk imap: antispam: mailbox_is_trash(Junk): 0 
> May  5 17:59:55 talk imap: antispam: mail copy: from trash: 0, to trash: 0 
> May  5 17:59:55 talk imap: antispam: mailbox_is_spam(INBOX): 0 
> May  5 17:59:55 talk imap: antispam: mailbox_is_spam(Junk): 1 
> May  5 17:59:55 talk imap: antispam: mailbox_is_unsure(INBOX): 0 
> May  5 17:59:55 talk imap: antispam: mail copy: src spam: 0, dst spam: 1, src unsure: 0 
> May  5 17:59:55 talk imap: antispam: running mailtrain backend program /usr/bin/rspamc 
> May  5 17:59:55 talk imap: antispam: running mailtrain backend program /usr/bin/rspamc 
> May  5 17:59:55 talk imap: antispam: running mailtrain backend program parameter 1 -b 
> May  5 17:59:55 talk imap: antispam: running mailtrain backend program parameter 2 127.0.0.1 
> May  5 17:59:55 talk imap: antispam: running mailtrain backend program parameter 3 -h 
> May  5 17:59:55 talk imap: antispam: running mailtrain backend program parameter 4 127.0.0.1:11334 
> May  5 17:59:55 talk imap: antispam: running mailtrain backend program parameter 5 learn_spam 
> May  5 17:59:55 talk imap: antispam: **run program failed with exit code 127**

I understand that the problem is rather in the plugin, however, I ask for help in determining the details of the error on the part of rspamс

thanks

**Comment by fatalbanana** [comment]
Your command line arguments for rspamc are not valid ("-b 127.0.0.1 -h 127.0.0.1"). I suggest removing all of these (antispam_pipe_program_args) - localhost is already the default target.

**Comment by fatalbanana** [comment]
Hummm, nevermind. :) Those arguments are actually fine (I didn't know about `-b`). I still think they are redundant, but that doesn't explain why it doesn't work.

I find it strange that logs refer to `mailtrain` backend while config indicates `pipe`. But I don't really know what to expect. AFAIU `pipe` is correct backend to use on Debian stable.

**Comment by posledov** [comment]
and a little more details:

`# LANG=C rspamc stat`
> Results for command: stat (0.000 seconds)
> IO write error: Connection refused

`# LANG=C rspamc -P q1 stat`
> Results for command: stat (0.000 seconds)
> IO write error: Connection refused

`# LANG=C rspamc -h localhost:11334 -P q1 stat`
> Results for command: stat (0.000 seconds)
> IO write error: Connection refused

`LANG=C rspamc -h 127.0.0.1:11334 stat`
> Results for command: stat (0.027 seconds)
> ...

**Comment by fatalbanana** [comment]
Right - you really need to use `-h` as there are issues with systemd socket activation and IPv4 vs 6 I'm afraid. :(

**Comment by posledov** [comment]
for me still remains a mystery why rspamc works as expected from console:

`# rspamc -h 127.0.0.1:11334 learn_spam < /mnt/mail/example.net/igor/Maildir/Junk/cur/1462452148.M874216P2484.talk\,S\=652741\,W\=661911\:2\,S `
> Results for file: stdin (0.669 seconds)
> HTTP error: 404, <572B3FB1.3020504@example.com> has been already learned as spam, ignore it

but the antispam plugin can not to befriend him?..

**Comment by posledov** [comment]
using script-wrapper for rspamc (`antispam_pipe_program = /etc/dovecot/rspamc.sh`), that's what we have:

`# cat rspamc-pipe.log `
> Fri May  6 11:03:29 EEST 2016 5751-start (-h 127.0.0.1:11334 learn_spam) /tmp/rspamc-msg-5751.txt
> uid=5000 gid=5000 groups=5000
> DOVECOT_PRESERVE_ENVS=TZ CORE_OUTOFMEM CORE_ERROR LISTEN_PID LISTEN_FDS
> SSL_SOCKET_COUNT=0
> PROCESS_LIMIT=1024
> CONFIG_FILE=/var/run/dovecot/config
> DOVECOT_CHILD_PROCESS=1
> SOCKET_COUNT=1
> IDLE_KILL=60
> PWD=/mnt/mail/example.net/igor
> CLIENT_LIMIT=1
> GENERATION=8
> DOVECOT_HOSTNAME=talk
> PROCESS_MIN_AVAIL=0
> DOVECOT_VERSION=2.2.13
> SHLVL=1
> LOG_SERVICE=1
> DOVECOT_HOSTDOMAIN=talk
> SERVICE_COUNT=1
> SOCKET_NAMES=imap       
> _=/usr/bin/env
> **/usr/bin/rspamc: error while loading shared libraries: libselinux.so.1: failed to map segment from shared object: Cannot allocate memory**
> Fri May  6 11:03:29 EEST 2016 5751-end rc=0

`# egrep -v '^#' /etc/dovecot/rspamc.sh `

> pid=$$
> 
> {
> echo "$(date) ${pid}-start ($*) /tmp/rspamc-msg-$$.txt"
> id -a
> env
> cat > /tmp/rspamc-msg-${pid}.txt
> /usr/bin/rspamc "$@" < /tmp/rspamc-msg-${pid}.txt
> echo "$(date) $$-end rc=$?"
> } >/tmp/rspamc.${pid}.log 2>&1
> 
> cat /tmp/rspamc.${pid}.log >>/tmp/rspamc-pipe.log
> rm -f /tmp/rspamc.${pid}.log /tmp/rspamc-msg-${pid}.txt
> 
> exit 99

**Comment by posledov** [comment]
`# dpkg -l | grep libselinux1`
> ii  libselinux1:amd64                 2.3-2                             amd64        SELinux runtime shared libraries

**Comment by posledov** [comment]
fixed by increasing `vsz_limit` for `service imap`

**Comment by posledov** [comment]
after upgrading Debian to Stretch got same exit code, but the reason is other:

> cat /tmp/systemd-private-647660fb6afc456e94946ba818544ae4-dovecot.service-ylwPaX/tmp/rspamc-pipe.log 
> Wed Aug 16 10:19:59 EEST 2017 16714-start (-h 127.0.0.1:11334 learn_ham) /tmp/rspamc-msg-16714.txt
> uid=5000 gid=5000 groups=5000
> GENERATION=12
> SOCKET0_SETTINGS=imap
> IDLE_KILL=60
> PROCESS_LIMIT=1024
> SOCKET_COUNT=2
> SOCKET1_SETTINGS=imap-master
> PWD=/mnt/mail/cac2s.net/igor
> DOVECOT_VERSION=2.2.27
> CONFIG_FILE=/var/run/dovecot/config
> DOVECOT_HOSTNAME=talk.cac2s.lan
> LOG_SERVICE=1
> DOVECOT_PRESERVE_ENVS=TZ CORE_OUTOFMEM CORE_ERROR LISTEN_PID LISTEN_FDS
> DOVECOT_HOSTDOMAIN=talk.cac2s.lan
> DOVECOT_CHILD_PROCESS=1
> SHLVL=1
> SERVICE_COUNT=1
> CLIENT_LIMIT=1
> PROCESS_MIN_AVAIL=0
> _=/usr/bin/env
> /usr/bin/rspamc: error while loading shared libraries: libbsd.so.0: failed to map segment from shared object
> Wed Aug 16 10:19:59 EEST 2017 16714-end rc=0
