### ISSUE TITLE
[1.2.6 WebUI] Edit rules save wrong values in rspamd_dynamic file when editing more than once

### ISSUE THREAD

**Issue by frederikbosch** [vstakhov/rspamd#623]
When you edit rules using the WebUI wrong values are saved. Only the latest changed values + the initial values (on start of rspamd) are saved. That means that when you edit more than once, only the initial values + the latest changes values are saved to `/var/lib/rspamd/rspamd_dynamic`. So the earlier changes are not present in `/var/lib/rspamd/rspamd_dynamic`.

However, it seems that the correct changes are used by rspamd instance (in memory). But when you restart, the wrong values will be used because these are not in `/var/lib/rspamd/rspamd_dynamic`.

**Comment by stephdl** [comment]
same issue than mine https://github.com/vstakhov/rspamd/issues/2154
