### ISSUE TITLE
rspamc check spf

### ISSUE THREAD

**Issue by ameagle** [vstakhov/rspamd#627]
Hello!
I have 2 question:
1)When option -u presents spf check doesn't work. Why?
In log  for B:
2016-05-13 14:43:35 #23557(normal) <6ce3d1>; task; spf_symbol_callback: skip SPF checks for local networks and authorized users

2) For the same message I got different score
score R_SUSPICIOUS_IMAGES
A)
root@spg:/usr/local/etc/rspamd# rspamc -v  -i 1.1.1.1  mail.file
Results for file: 04543614121747504457 (0.043 seconds)
[Metric: default]
Spam: true
Score: 9.59 / 5.00
Action: reject
Symbol: BAYES_SPAM (1.89)[37.29%]
Symbol: DATE_IN_PAST (1.70)
Symbol: DMARC_POLICY_REJECT (2.00)[infinitys.co.ua]
Symbol: HTML_SHORT_LINK_IMG_1 (3.00)
Symbol: MIME_GOOD (0.00)[multipart/related, multipart/alternative, text/plain]
**Symbol: R_SPF_FAIL (1.00)[all]**
Message: (SPF): spf fail
Message-ID: e77901d15d33$da654440$261d295b@info

B)
root@spg:/usr/local/etc/rspamd# rspamc -v **-u q1@q1.ru**  -i 1.1.1.1  mail.file
Results for file: 04543614121747504457 (0.290 seconds)
[Metric: default]
Spam: true
Score: 10.26 / 5.00
Action: reject
Symbol: BAYES_SPAM (1.89)[37.29%]
Symbol: DATE_IN_PAST (1.70)
Symbol: DMARC_POLICY_REJECT (2.00)[infinitys.co.ua]
Symbol: HTML_SHORT_LINK_IMG_1 (3.00)
Symbol: MIME_GOOD (0.00)[multipart/related, multipart/alternative, text/plain]
Symbol: R_SUSPICIOUS_IMAGES (1.67)
Message-ID: e77901d15d33$da654440$261d295b@info

**Comment by fatalbanana** [comment]
> 1)When option -u presents spf check doesn't work. Why?

Most people probably don't want to check SPF on mail sent by their users. I'm afraid this behaviour is not currently configurable so if you do really want that for some reason(?)- it would require patching.

> 2) For the same message I got different score

Try re-run your tests with `-p`. Rspamd does not plan further checks when `reject` score is reached.

**Comment by ameagle** [comment]
Thanks. How can I patch it ? It's really important for me. I just use rspamc whith qmail-scanner instead of  SA. http://qmail-scanner.sourceforge.net/

**Comment by fatalbanana** [comment]
If you're using rspamc as LDA you can't expect SPF to work properly I'm afraid. For proper operation Rspamd requires metadata to be passed from MTA (typically this requirement is satisfied by Rmilter; Exim/Haraka offer proper integration too).

If you're able to provide stuff like:

* IP of the sender
* RDNS of the sender
* HELO used
* Envelope sender of the message
* Envelope recipients of the message

... Then you can pass this in using the related `rspamc` parameters (eg. `-i` for IP address)- refer to `man rspamc` for details on that and https://rspamd.com/doc/architecture/protocol.html for details about possible metadata (Under "HTTP Headers").

**Comment by ameagle** [comment]
Sorry but I really don't undestand  Why spf checks just for -i options?
root@spg2.g.ixi.ru:/var/qmail/spamgun/working/spam# rspamc -p -i 85.25.150.11 -u eywifwk@timareg.co.ua -F eywifwk@timareg.co.ua -d onol@rasl.nw.ru -r onol@rasl.nw.ru --helo=timareg.co.ua --hostname=mail.timareg.co.ua 04634819524282119641
Results for file: 04634819524282119641 (0.326 seconds)
[Metric: default]
Spam: true
Score: 31.60 / 15.00
Action: reject
Symbol: BAYES_SPAM (4.00)[100.00%]
Symbol: DMARC_POLICY_REJECT (2.00)[timareg.co.ua]
Symbol: FUZZY_DENIED (12.00)[1: 1.00 / 1.00, 1: 1.00 / 1.00]
Symbol: HAS_HTML_ (0.00)
Symbol: HTML_SHORT_LINK_IMG_1 (3.00)
Symbol: MIME_GOOD (0.00)[multipart/related, multipart/alternative, text/plain]
Symbol: MIME_UNKNOWN (0.10)[image/jpeg]
Symbol: URIBL_BLACK (10.50)[femura.co.ua.multi.uribl.com]
Message-ID: 77e201d1b003$f7d3fa30$af94d32d@eywifwk

root@spg2.g.ixi.ru:/var/qmail/spamgun/working/spam# rspamc -p -i 85.25.150.11 04634819524282119641                                                                                                          
Results for file: 04634819524282119641 (0.252 seconds)
[Metric: default]
Spam: true
Score: 32.60 / 15.00
Action: reject
Symbol: BAYES_SPAM (4.00)[100.00%]
Symbol: DMARC_POLICY_REJECT (2.00)[timareg.co.ua]
Symbol: FUZZY_DENIED (12.00)[1: 1.00 / 1.00, 1: 1.00 / 1.00]
Symbol: HAS_HTML_ (0.00)
Symbol: HTML_SHORT_LINK_IMG_1 (3.00)
Symbol: MIME_GOOD (0.00)[multipart/related, multipart/alternative, text/plain]
Symbol: MIME_UNKNOWN (0.10)[image/jpeg]
**Symbol: R_SPF_FAIL (1.00)[all]**
Symbol: URIBL_BLACK (10.50)[femura.co.ua.multi.uribl.com]
**Message: (SPF): spf fail**
Message-ID: 77e201d1b003$f7d3fa30$af94d32d@eywifwk

**Comment by FelixSchwarz** [comment]
> Sorry but I really don't undestand Why spf checks just for -i option?

From my understanding rspamd does not try to retrieve meta information like the sender's ip address from the actual text message because the code would have to assume quite a bit about the message structure (and some MTAs might not even record the sender ip).

Also I guess it is easier that way because most code is shared between rspamd/milter and rspamc (and the milter just gets the information very easily). If you are willing to accept some assumptions about the received header you could write your own script (some assumptions are fine for specific systems but not in the general case).

At least with Exim it is very easy to pass the required information via the command line (if using rspamc and not the "spamd" integration).

(beware: I have very little experience with rspamd so I might be entirely wrong)

**Comment by fatalbanana** [comment]
@ameagle - not sure I understand what you're actually asking. :)

RE: your most recent sample scans - in the first case you've simulated mail from an authenticated user (`-u`): so SPF is not checked.

RE: use of metadata: it's faster/simpler/less fragile this way. Rspamd does in fact have some limited support for dummying up (some of) this information where it has not been provided but it's not to be relied on.
