### ISSUE TITLE
Override metrics limits for some domains

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rspamd#628]
Hi.

Is there a way to dynamicaly override metrics limits (for example reject score) in some cases?
For example default value determined in metrics.conf (let it be 16), but if recipient's address is 'test@example.com' dynamicaly set it to 40 only for this message. In other words i want to find a way to prevent rejecting of all emails sent to some my addresses (even in case of high SCL), but i want still has spam header actions for it.

**Comment by damned-trooper** [comment]
As i can see in documentation i need use this - https://rspamd.com/doc/configuration/settings.html 
I need to create new config file like this:
```
settings {
	some_users {
		priority = high;
		rcpt = "test@example.com";
		apply "default" {
			actions {
				reject = 100.0;
				greylist = 5.0;
				"add header" = 10.0;
			}
		}
}
```
and include it, right?

And another one question - can i use "*@example.com" in "rcpt" field to set all domain?

**Comment by fatalbanana** [comment]
Yep, if you want static settings this is the way to go.

You can use "@example.com" to match a domain part (or "foo" to match a localpart, or even regex) for from/rcpt/user - this is not particularly explicit in the documentation (but example config alludes to some such syntax).

**Comment by damned-trooper** [comment]
Thank you.

**Comment by damned-trooper** [comment]
I've got a strange problem.

I created file `/etc/rspamd/limits-test.conf` with this content:
```
settings
{
        some_users
        {
                priority = high;
                rcpt = "<MY EMAIL>";
                apply "default"
                {
                        actions
                        {
                                reject = 100.0;
                                greylist = 25.0;
                                "add header" = 30.0;
                        }
                }
        }
}
```
and included it via `/etc/rspamd/rspamd.conf.local`:
`.include "$CONFDIR/limits-test.conf"`

After restart of rspamd service i got this events in logs, when new message arrive:

> May 14 12:56:21 mx01 rspamd[5142]: <2d64cc>; task; rspamd_task_timeout: processing of task timed out, forced processing
> May 14 12:56:21 mx01 rspamd[5142]: <2d64cc>; task; rspamd_task_write_log: id: <20160513212917.9EBF71A1C20@ns1bk.aragua.gob.ve>, qid: <AAB6575BB>, ip: 190.202
> .82.238, from: <MAILER-DAEMON@expoaragua.aragua.gob.ve>, (default: T (reject): [50.29/15.00] [RBL_SPAMHAUS_XBL_ANY,RBL_MAILSPIKE_WORST,RBL_SPAMHAUS_XBL,RBL_S
> EM,RBL_SORBS_WEB,RBL_SPAMHAUS_CSS,RBL_UCEPROTECT_LEVEL1,RBL_SENDERSCORE,HFILTER_HOSTNAME_UNKNOWN,RBL_SORBS_RECENT,MIME_GOOD,FUZZY_DENIED,RDNS_NONE,HFILTER_HE
> LO_IP_A]), len: 3510, time: 8006.154ms real, 29.793ms virtual, dns req: 32
> May 14 12:56:51 mx01 rspamd[5139]: <2986bf>; main; rspamd_term_handler: catch termination signal, waiting for children
> May 14 12:56:51 mx01 rspamd[5141]: <2986bf>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
> May 14 12:56:51 mx01 rspamd[5140]: <2986bf>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
> May 14 12:56:51 mx01 rspamd[5140]: <73ee12>; fuzzy_backend; rspamd_fuzzy_backend_sync: deleted 0 orphaned shingles
> May 14 12:56:51 mx01 rspamd[5142]: <2986bf>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
> May 14 12:56:51 mx01 rspamd[5143]: <2986bf>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
> May 14 12:56:51 mx01 rspamd[5139]: <2986bf>; main; wait_for_workers: fuzzy process 5140 terminated softly
> May 14 12:56:51 mx01 rspamd[5139]: <2986bf>; main; wait_for_workers: controller process 5141 terminated softly
> May 14 12:56:51 mx01 rspamd[5139]: <2986bf>; main; wait_for_workers: normal process 5142 terminated softly
> May 14 12:56:51 mx01 rspamd[5139]: <2986bf>; main; wait_for_workers: normal process 5143 terminated softly
> May 14 12:56:51 mx01 rspamd[5139]: <2986bf>; main; main: terminating...

rspamd service stoped working and message came without scanning.

**Comment by damned-trooper** [comment]
I'm sorry.
Formating error.
All works fine now.
