### ISSUE TITLE
How can i use regex in multimap?

### ISSUE THREAD

**Issue by oczkers** [vstakhov/rspamd#631]
multimap:
`blacklist {
type = "from";
        filter = "email";
        map = "file:///etc/rspamd/blacklist.map";
        symbol = "BLACKLIST_FROM";
    }`

it's working if i use plain text (_test@test.com_) but not with regex expressions - i've tested:
`/.+@test\.com/i`
`.+@test\.com`
`tes.@test.com`

**Comment by vstakhov** [comment]
You can do it when adding

```
regexp = true;
```
 to the map options.
