### ISSUE TITLE
rspamc does not clear existing "X-Spam-Flag" for ham

### ISSUE THREAD

**Issue by FelixSchwarz** [vstakhov/rspamd#633]
I just came across an email which was detected as ham by rspamc. However the email already contained the header "X-Spam-Flag: YES" so it was moved to the quarantine folder by my sieve filter. While I can adapt my filter conditions I think it might be a good idea for rspamc to remove existing headers.

(Not how this interacts with techniques like DKIM - probably it should be possible for an administrator to tell rspamc it should only add headers and never remove any.)

**Comment by moisseev** [comment]
Duplicate of #603

**Comment by FelixSchwarz** [comment]
yeah, let's assume fixing #603 will also fix `rspamc --mime` output.
