### ISSUE TITLE
Is rspamd able to check content of archived attachments?

### ISSUE THREAD

**Issue by maethor** [vstakhov/rspamd#635]
Hi,

I'm new to rspamd. Is there a way for rspamd to check the filename or mimetype of archived attachments? In Amavis this is completely transparent. When we blacklist exe for instance, Amavis knows how to open common archive formats and check if they contain an exe.

If not, what would be the best way to make this dream come true? Do I have to patch multimap.lua and mim_types.lua?

Thanks.

**Comment by fatalbanana** [comment]
Hi,

There is no support for unpacking archives at this time.

**Comment by maethor** [comment]
I may be able to implement it. What would be the best way to do it?

**Comment by AdUser** [comment]
@maethor, that's possible not antispam task, but antivirus.

You may try clamav with additional sanesecurity databases, in my practice it's very effective for checking archives (at least .scr.zip -like spam, obfuscated js, pdf's with embedded js, doc(x)+vbs, etc).

**Comment by maethor** [comment]
Thanks @AdUser, that's exactly what I need.

**Comment by slesru** [comment]
Hello!

Is this still true? 
Or , may be , rspamd now can unpack archives and check their content using antivirus?

Thank you!
