### ISSUE TITLE
rspamc returns R_BAD_CTE_7BIT for some messages when scanning messages from Exim

### ISSUE THREAD

**Issue by FelixSchwarz** [vstakhov/rspamd#637]
commit 26282f2ce4dd477ae119c15a28ca2bd7390af18a added a workaround for Exim (spamd integration) as Exim sends the message in Unix mailbox format.

Unfortunately it seems as the workaround is buggy because rspamd sometimes applies R_BAD_CTE_7BIT to sent messages. When sending the same message (without mailbox header) via rspamc this does not happen.

I attached a simple Python script to demonstrate the issue (due to github's limitations I had to add a '.txt' extension). The script opens a TCP connection to rspamd exactly like rspamc would but there is a command line parameter `--exim`. If that parameter is set, the script will add the mailbox header like Exim would do. Otherwise the header is omitted.

[fake-rspamc.py.txt](https://github.com/vstakhov/rspamd/files/283818/fake-rspamc.py.txt)

**Comment by vstakhov** [comment]
It was casued by a bug with length calculation when such an input is detected. That should be fixed now.

**Comment by FelixSchwarz** [comment]
that's what I suspected. I'll rebuild and test the fix later today. Thanks for fixing it so quickly.

**Comment by FelixSchwarz** [comment]
fix working as expected - so far I didn't spot any anomalies in our monitoring. Seems like we're ready to move our production systems to rspamd now :-)
