### ISSUE TITLE
no url_tld option has been specified

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rspamd#641]
When i run `rspamadm configdump` i've got an error:
`2016-05-30 11:12:06 #57990(rspamadm) cfg; rspamd_config_post_load: no url_tld option has been specified, URL's detection will be awfully broken`
But this option specified:

```
rspamadm configdump | grep url_tld
2016-05-30 11:12:06 #57990(rspamadm) cfg; rspamd_config_post_load: no url_tld option has been specified, URL's detection will be awfully broken
    url_tld = "/usr/share/rspamd/effective_tld_names.dat";
```

and file exists:

```
ls -la /usr/share/rspamd/effective_tld_names.dat
-rw-r--r--. 1 root root 187193 Mar 23 10:38 /usr/share/rspamd/effective_tld_names.dat
```

**Comment by vstakhov** [comment]
Ah, I see the point. It's not rspamd, it's rspamadm. I'll try to fix it soon.
