### ISSUE TITLE
WebUI path: /learnfuzzy not found

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#642]
When press Upload files button in Upload Fuzzy examples section I got such error message:

`Cannot upload data, no server found `
`$ sudo cat /var/log/rspamd/rspamd.log | grep "fuzzy\|error"`
`2016-05-31 12:46:33 #5038(controller) <62c7a3>; csession; rspamd_controller_error_handler: http error occurred: Not found
2016-05-31 12:46:33 #5038(controller) rspamd_http_router_finish_handler: path: /learnfuzzy not found`

Where should I configure /learnfuzzy path?

**Comment by fatalbanana** [comment]
This part of the web interface is currently broken I'm afraid. See #289.

**Comment by dehnli** [comment]
@fatalbanana 
Thanks, in my case it is more convenient way than to learn through the console
