### ISSUE TITLE
[Feature] rspamc -P asking password if it is omitting

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rspamd#644]
If such syntax is used then asking password
`$ rspamc -h localhost:11334 -P -f 1 -w 20 fuzzy_add /tmp/spam/1.eml`

**Comment by fatalbanana** [comment]
Seems to be feature request: to be able to give `-P` flag to rspamc _without_ parameters and be prompted for the password interactively.

**Comment by dehnli** [comment]
Yes, that's what I mean

**Comment by vstakhov** [comment]
That should work now.

**Comment by dehnli** [comment]
@vstakhov 
`$ rspamc -h localhost:11334 -P -f 1 -w 3 fuzzy_add /tmp/98.eml`
`cannot stat file 1`

`$ rspamc -h localhost:11334 -P stat`
It seemed to hang and there is no prompt for password

ps Does it matter localhost or 10.10.10.10 for example?

**Comment by moisseev** [comment]
rspamc treats any word after '-P' as a password. It can't detect that password was omitted.
@dehnli What if you move '-P' to the end of the line?

**Comment by dehnli** [comment]
@moisseev 
`$ rspamc -h localhost:11334 -f 1 -w 3 fuzzy_add /tmp/98.eml -P`
`option parsing failed: Missing argument for -P`

**Comment by fatalbanana** [comment]
This has been added in master (forthcoming 1.3 release)- not in rspamd-1.2 branch.

**Comment by dehnli** [comment]
Thanks! It works
```
# rspamc -h localhost:11334 -P -f 1 fuzzy_add /tmp/spam/spam.eml
Enter passphrase: 
Results for file: /tmp/spam/spam.eml (0.036 seconds)
success = true;
```
