### ISSUE TITLE
Rewrite subject

### ISSUE THREAD

**Issue by andypl78** [vstakhov/rspamd#650]
Normally Rspamd rejects SPAM but I have to pass through these messages, and I question whether it is possible to add to the message subject, eg. [SPAM] ?

**Comment by fatalbanana** [comment]
Yes- you could remove `reject` action from metric, and replace `add header` with `rewrite subject`: then rmilter will add `***SPAM***` tag to Subject of suspected messages & not reject. If you want to do this selectively you could use [settings module](https://rspamd.com/doc/configuration/settings.html).

**Comment by andypl78** [comment]
Ok, working THX ;)
I have another question whether it is possible to modify the subject instead *** SPAM *** for example. [SPAM] original subject

**Comment by fatalbanana** [comment]
This appears to be hardcoded unfortunately.

**Comment by andypl78** [comment]
This could be added to Wish List;)

**Comment by wociscz** [comment]
Did you try this?
https://github.com/vstakhov/rspamd/issues/98

**Comment by andypl78** [comment]
It works ;)

How do you see enough in the documentation of the features that are hidden

**Comment by vstakhov** [comment]
https://rspamd.com/doc/configuration/metrics.html

**Comment by wociscz** [comment]
Is it possible somehow to prepend defined subject, rather than replace it? Or replacing is hardcoded when rewrite_subject is in action? (i just discovered, that subject is complete replaced with metric defined subject...)

**Comment by xpunkt** [comment]
lets say recipient server see dkim fail and reject based on it ?, any solution on that ?

**Comment by vstakhov** [comment]
1. Why do you need to rewrite subject for outgoing mail?
2. You need to rewrite DKIM signature when forwarding email or you are in troubles anyway.
3. DKIM signature *may* exclude `Subject` header.

**Comment by xpunkt** [comment]
1. i dont rewrite any headers
2. no that will still be fail on dkim since you cant resign if missing primary dkim key, but you can still sign with atps, that just another problem
3 yes if subject is not signed, it will allow forwards if subject need to be changed

hope mailadmins dont miss my points here

**Comment by vstakhov** [comment]
You can and you *should* resign a message on forwarding (whatever `atps` is)  and remove/hide the existing DKIM signature. That would still fail DMARC though.

**Comment by xpunkt** [comment]
and it will in spamassassin hit on adsp testing

dont break dkim

**Comment by vstakhov** [comment]
Then spamassassin is retarded as adsp has `historical` status and superceded with DMARC. In that case, you would have DMARC failed but DKIM success which means good things if you **trust** your forwarder. Isn't it clear to you? I'm not suggesting to resign emails with incorrect DKIM - that's an important part.

**Comment by xpunkt** [comment]
adsp is depricated in opendkim, but spamassassin still test it

how to make dmarc do the same as adsp ?

well i take it up here since thread started with related forward comment, so i add that subject must not be changed if dkim signed

and resign only works if recipient mx only test last signer not all signer

not perfekt but nearly

**Comment by vstakhov** [comment]
DMARC implements all adsp features. Regarding resigns: imagine that you have trusted forwarder `F` which removes DKIM signature when it is valid and adds its own signature (altering message if needed). Then you have some domain which has `dkim=strict` policy in dmarc. Then rspamd would treat `F` signature as invalid in terms of DMARC but you can still use rspamd `whitelist` module to add negative marks to messages that come with valid signature from `F`. That's what I'm talking about.

**Comment by gotjoshua** [comment]
is it possible to also put the numeric score in the rewritten subject?

**Comment by FerminNS** [comment]
More explained information to change the Subject

edit or create /etc/rspamd/local.d/actions.conf  

# local.d/actions.conf
subject = "Free TEXT %s"

%s -> Original Subject
%d -> Spam Score

can also be edited /etc/rspamd/actions.conf but I think it is convenient to do it in this file (or in the file of each user/domain)

**Comment by FerminNS** [comment]
More explained information to change the Subject

edit or create /etc/rspamd/local.d/actions.conf

 subject = "Free TEXT %s"

%s -> Original Subject
%d -> Spam Score

can also be edited /etc/rspamd/actions.conf but I think it is convenient to do it in this file (or in the file of each user/domain)
