### ISSUE TITLE
valid DKIM signature identified as R_DKIM_REJECT

### ISSUE THREAD

**Issue by FelixSchwarz** [vstakhov/rspamd#651]
In general my rspamd (v1.2.7+) seems to be able to verify DKIM signatures just fine. However I just noticed two messages with where classified with R_DKIM_REJECT even though I believe the signature is just fine (Exim, dkimpy and perl's Mail::DKIM say that as well). Other messages with the same DKIM key are also found to be valid be rspamd. 

My main problem is currently that it might be a bit hard for me to get the client's approval to share the email publicly though sharing in private with rspamd developers should be no problem. Is there anything else I can do (e.g. activate some logging) besides trying to build a synthetic test message (which might be difficult).

**Comment by FelixSchwarz** [comment]
Ok, I managed to build a simple example with my script emulating rspamc. I always get R_DKIM_REJECT even though the message contained in script should be perfectly valid using the current DKIM key for schwarz.eu.

[fake-rspamc.dkim.py.txt](https://github.com/vstakhov/rspamd/files/299334/fake-rspamc.dkim.py.txt) (need to strip the '.txt' from the file extension because github does not allow '.py' files).

**Comment by vstakhov** [comment]
I've found the issue: it is about removing of empty lines at the end of message. However, the resolution would likely take more time. Thank you for your report!

**Comment by FelixSchwarz** [comment]
Great, that explains why it doesn't happen with most messages :-)
Just as a ball park number: Do you already have a timeframe in mind for the real fix? Weeks? Months? 1.3 release or 1.4? Or just "later this week"?

**Comment by vstakhov** [comment]
I've added the fix but it is quite complicated and requires more testing I'm afraid.

**Comment by FelixSchwarz** [comment]
ok, so is there anything I can do to help?
We're looking into a mechanism to copy all of our incoming mail through a test system and compare spam results later with our production setup. This will take some time (roughly "this month") but might be helpful to test the DKIM fix. Do you need testing for this within a specific time frame?

**Comment by vstakhov** [comment]
From 1.3 version rspamd will include testing proxy support: https://highsecure.ru/rspamd-testing.pdf

For now, it is enough to check the recent master and report any bugs/inconsitences found.

**Comment by FelixSchwarz** [comment]
as far as I can see the fix works for us (applied manually on top of 1.2.x).

**Comment by vstakhov** [comment]
Do you see other DKIM failures? Maybe something with messages with no trailing CRLF (in both relaxed and simple encodings)? Maybe with messages with messed line-endings? Maybe with empty messages?

**Comment by FelixSchwarz** [comment]
as far as I can see it works just fine. The DKIM failures so far are correct (mostly mailing lists, a few desperate spammers). However we continue to monitor the mail flow for DKIM rejections.

**Comment by FelixSchwarz** [comment]
I noticed one more DKIM failure recently - however I have to admit I'm not using the latest 1.2.x right now.
[pingdom2.msg.txt](https://github.com/vstakhov/rspamd/files/337949/pingdom2.msg.txt)

**Comment by vstakhov** [comment]
Fixed.
