### ISSUE TITLE
rspamd outgoing mapping

### ISSUE THREAD

**Issue by andypl78** [vstakhov/rspamd#655]
Is it possible to add mapping list of IP addresses that will be assigned as outbound ?
I use a centralized configuration, a rmilter for incoming and outgoing mail

```
settings {
  outbound {
    priority = high;
    id = "outbound";
    apply "default" {
      actions {
        reject = 150.0;
        "add header" = 6.0;
      }
      BAYES_SPAM = 7.0;
      groups_disabled = [
        "hfilter",
        "spf",
        "rbl"
      ]
    }
  }
}
```

**Comment by fatalbanana** [comment]
Yes, you can specify `ip` multiple times with the relevant subnets/addresses; see https://rspamd.com/doc/configuration/settings.html

**Comment by andypl78** [comment]
Not working.
Because the variable IP only client IP address instead of the SMTP server.
If I set the IP client, which send emails then I have information

lua; settings.lua:251: <013101d1c360$47486aa0$d5d93fe0$@domain.ltd> apply settings according to rule outbound

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#how-to-distinguish-inbound-and-outbound-traffic-for-rspamd-instance

**Comment by andypl78** [comment]
It works but not when milter work for SMTP servers incoming and outgoing at the same time
I would have to install rmilter for outgoing SMTP servers.

**Comment by vstakhov** [comment]
That's the easiest way I suppose.

**Comment by andypl78** [comment]
it is possible to set two instances milter on two different ports on the same server and with different configurations?
