### ISSUE TITLE
[Doc] rewrite Autolearning section

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#660]
https://github.com/vstakhov/rspamd/blame/master/doc/markdown/configuration/statistic.md#L223
This sentence is cryptic and should be rewritten. 

What does this mean? `score is less than minimum of 2 numbers (< `1` here)`

Why not just mention that `1` and `10` are score thresholds and remove everything about score length?

I think an example with negative ham score `autolearn = [-20, 20]` would be more clear.

**Comment by vstakhov** [comment]
That's done, thanks.
