### ISSUE TITLE
DNS request limitation might cause missing DMARC policy evaluation

### ISSUE THREAD

**Issue by FelixSchwarz** [vstakhov/rspamd#661]
(Disclaimer: I'm not 100% sure that my diagnosis is correct even though I tried to verify it as much as possible.)

It seems as if the DNS request limit (I think 64 by default) also applies to the DMARC check. One of my messages contained a large list of ip addresses/host names. rspamd logged `make_dns_request_task_common: <...> stop resolving on reaching 64 requests`. This in itself is fine but unfortunately rspamd did not add DMARC_POLICY_ALLOW for this email.

I suspect the DNS request to retrieve the DMARC policy got blocked which I find a bit unsatisfactory because this lead to a false positive for us as the DMARC whitelist was not applied. Ideally I think rspamd should always be able to run the SPF/DKIM/DMARC checks regardless of the number of DNS requests for the message contents.

**Comment by vstakhov** [comment]
That works for DKIM and SPF. DMARC uses the global limit unfortunately.

**Comment by vstakhov** [comment]
Ok, I've done that for DMARC, once_received and RBL plugins. Not going to port to 1.2, I'm afraid, because the change is quite big.

**Comment by FelixSchwarz** [comment]
fair enough - thanks for tackling this so quickly. Looking forward to 1.3 then :-)
