### ISSUE TITLE
autolearn with redis not working?

### ISSUE THREAD

**Issue by wociscz** [vstakhov/rspamd#663]
Hi, i just recognised that autlearn not working(?)
when i have at statistic.conf 
```
classifier "bayes" {
  tokenizer {
    name = "osb";
  }
    name = "bayes";
    min_tokens = 11;
    backend = "redis";
    servers = "127.0.0.1:6378";
#    write_servers = "127.0.0.1:6378:10, 127.0.0.1:6379:1";
    languages_enabled = true;
    min_learns = 200;

    statfile {
        symbol = "BAYES_HAM";
        spam = false;
    }
    statfile {
        symbol = "BAYES_SPAM";
        spam = true;
    }
  autolearn = true;
}
```
i see lot of redis timeouts in rspamd logfile
```
2016-06-14 15:04:11 #17239(normal) <246f35>; task; rspamd_redis_timeout: connection to redis server 127.0.0.1 timed out
2016-06-14 15:04:11 #17239(normal) <246f35>; task; rspamd_redis_learn_tokens: invalid state for function: 2
```
and 
When i use write_servers with master-slave definitions no timeouts in logfile, there are no timeouts in logfile, but i can't see any BAYES_HAM/SPAM requests in redis monitor.

And at least redis keys "BAYES_SPAM/HAM learns" not incrementing even if i see 
```autolearn spam for classifier 'bayes' as message's action is reject, score: 23.30```
in logfile.

(using 1.3.0-0~git128~fb326ef~jessie)

**Comment by vstakhov** [comment]
Oh, I think I know what's the issue. I'll try to fix it today.

**Comment by vstakhov** [comment]
Or wait, is it still relevant now?

**Comment by wociscz** [comment]
i think yes - my observation:

**case1:**
in statistic.conf: 
`write_servers = "127.0.0.1:6378, 127.0.0.1:6379";`
same situation when i have
`write_servers = "127.0.0.1:6378:10, 127.0.0.1:6379:1";`
(as for master and slave redis - master in my case is haproxy which proxying traffic always to master node)

in rspamd log:
`task; rspamd_stat_check_autolearn: someid@somemail.tld : autolearn spam for classifier 'bayes' as message's action is reject, score: 24.10`
(i can see learning messages - seems ok)

but in redis:
```
redis-cli HGET BAYES_HAM learns
"8335"
redis-cli HGET BAYES_SPAM learns
"22060"
```
(not counting - so maybe not updating counters, or maybe not learning even if "learn" message is in redis log)

**case2:**
statistic.conf:
`servers = "127.0.0.1:6378";`
(only to haproxy master redis)

rspamd.log:
```
task; rspamd_redis_connected: error getting reply from redis server 127.0.0.1: Server closed the connection
task; rspamd_redis_processed: error getting reply from redis server 127.0.0.1: Server closed the connection
```
(connection errors, seems not using 6378 port and trying connect to localhost 6379 default which is readonly slave - only guessing)

**case3:**
statistic.conf:
`servers = "real.redis.master:6379";`

rspamd.log:
there are no "learn" messages, or redis errors

redis:BAYES_SPAM learns key counting up 
BAYES_HAM learns not counting up
```
BAYES_SPAM learns key counting up 
BAYES_HAM learns not counting up
```

Looks to me that only case2 (hostname of real master on port 6379) working in some way for autolearning spams (not hams)

I have allmost default rmilter and rspamd configs - only changed hostnames/ips and some weight at some symbols. rmilter using haproxyied redis on 6378 without problems.

If you need other config values or other whatever, let me know.

Thanks!

**Comment by wociscz** [comment]
Working now. Changed setup as https://github.com/vstakhov/rspamd/issues/766
But seems that multiple servers not working (and with other port than 6379?)
