### ISSUE TITLE
rspamd 1.2.7 segfault (same with 1.2.5) from time to time

### ISSUE THREAD

**Issue by ilyakruchinin** [vstakhov/rspamd#665]
Debian 8, latest updates.
root@antispam:/home/admin# tail -f /var/log/messages

Jun 16 14:42:56 antispam kernel: [2983310.098012] rspamd[26613]: segfault at 8995cf ip 00007f7d59e4555a sp 00007ffe8d6b9080 error 7 in libc-2.19.so[7f7d59dc0000+1a2000]
Jun 16 14:52:56 antispam kernel: [2983910.295222] rspamd[19493]: segfault at 8995cf ip 00007f7d59e4555a sp 00007ffe8d6b9080 error 7 in libc-2.19.so[7f7d59dc0000+1a2000]

The above is 1.2.5
See below for 1.2.7

Jun 16 15:46:57 antispam kernel: [2987150.404776] rspamd[54732]: segfault at 89990f ip 00007f4c7c01e55a sp 00007ffc7adecef0 error 7 in libc-2.19.so[7f4c7bf99000+1a2000]
Jun 16 15:52:56 antispam kernel: [2987510.249127] rspamd[54731]: segfault at 89990f ip 00007f4c7c01e55a sp 00007ffc7adecef0 error 7 in libc-2.19.so[7f4c7bf99000+1a2000]
Jun 16 16:02:56 antispam kernel: [2988110.297584] rspamd[59049]: segfault at 89990f ip 00007f4c7c01e55a sp 00007ffc7adecf90 error 7 in libc-2.19.so[7f4c7bf99000+1a2000]

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
