### ISSUE TITLE
How can I build my rspamd modules(conf, program, db, log) to the folders I want.

### ISSUE THREAD

**Issue by mozzan** [vstakhov/rspamd#673]
I need to manually build rspamd, and I need to not to use the default setup.

How can I set my path options when I make my rspamd binary?

**Comment by vstakhov** [comment]
# Now CMAKE_INSTALL_PREFIX is a base prefix for everything
# CONFDIR - for configuration
# LOCAL_CONFDIR - for local configuration
# MANDIR - for manual pages
# RUNDIR - for runtime files
# DBDIR - for static files
# LOGDIR - for log files
# EXAMPLESDIR - for examples files

**Comment by vstakhov** [comment]
That are all cmake vars. You could take a look at CMakeLists.txt for further details.

**Comment by mozzan** [comment]
Thanks!!
But now I'm facing another problem. That is, in my deploy server, there is only 2.17 glibc, which means I need to compile my rspamd with static glibc(2.28). How can I change the CMakeLists.txt that it would use the static library. Is there any help that you can support?  Thank you again!!

**Comment by vstakhov** [comment]
-DENABLE_STATIC=ON should help.

**Comment by mozzan** [comment]
Execuse me. There is an error. 
/addpkg/lib/libpcre.a(pcre_globals.o):(.bss+0x0): multiple definition of `pcre_callout'
/usr/local/lib/libglib-2.0.a(pcre_globals.o):(.bss+0x0): first defined here
/usr/bin/ld: attempted static link of dynamic object `/usr/local/lib/libevent.so'
collect2: ld returned 1 exit status
make[2]: *** [src/rspamd-1.1.2] Error 1
make[1]: *** [src/CMakeFiles/rspamd.dir/all] Error 2
make: *** [all] Error 2

How can I solve it?  Thanks!

**Comment by fatalbanana** [comment]
You'd need a static version of libevent library.

**Comment by mozzan** [comment]
But I have /usr/local/lib/libevent.a , is that not enough ?

**Comment by fatalbanana** [comment]
I suppose it's a matter of helping the build process find the correct library then (though I've no particular idea about how you may do that).

**Comment by mozzan** [comment]
This is my build command :
cmake -DCMAKE_INSTALL_PREFIX=/PGRAM/rspamd -DCONFDIR=/PCONF/rspamd -DRUNDIR=/PGRAM/rspamd -DDBDIR=/HDD/PDATA/rspamd -DLOGDIR=/var/log -DENABLE_STATIC=ON ../rspamd-1.1.2/

But an error showed up :
CMake Error at CMakeLists.txt:930 (MESSAGE):
  Your system does not support getaddrinfo call, please consider upgrading it
  to run rspamd

could you help me ?   thanks !!

**Comment by mozzan** [comment]
I've solved above problem.
I'm facing another problem, which is I don't know how to change the position rspamd.sock from DBDIR to /tmp/rspam.sock 
Thanks !!

**Comment by quicktrick** [comment]
Hi @mozzan !

Have you solved the problem with "Your system does not support getaddrinfo call, please consider upgrading it to run rspamd" ?  Could you please share the solution?

**Comment by fatalbanana** [comment]
@quicktrick you might not have a statically-compiled libc on your system.

BTW I am currently maintaining a static build for Linux x64 (in form of Docker image but could also be repackaged in something like DEB/RPM). Build recipe & link to binaries is here: https://github.com/fatalbanana/static-rspamd

**Comment by quicktrick** [comment]
To be honest, I'm quite new to Linux yet.  I'm trying to install Rspamd on my home openSUSE Tumbleweed server.  I've got Postfix + Dovecot + Roundcube running already.  But openSUSE repos only have an Rspamd 1.6.3 package.  Now I'm trying to update it to 1.6.5.  It successfully compiles for openSUSE Leap 42.3, but failes for Tumbleweed. :(  Thanks a lot for your reply, @fatalbanana !

**Comment by fatalbanana** [comment]
Ah, I see... so static build is not intended there I suppose. I'm not sure what the issue is I'm afraid, I'd need to investigate. Seems openSUSE packaging effort could use more people.

**Comment by quicktrick** [comment]
That's for sure. :)

**Comment by quicktrick** [comment]
But do I need this check in `CMakeLists.txt` at all?

    CHECK_SYMBOL_EXISTS(getaddrinfo "sys/types.h;sys/socket.h;netdb.h" HAVE_GETADDRINFO)

According to [this](https://software.opensuse.org/package/perl-Socket-GetAddrInfo?search_term=getaddrinfo):

> As of Perl version 5.14.0, Perl already supports 'getaddrinfo' in core.

I have `perl 5.26.1-1.4` installed.  Is it acceptable to exclude this check?

**Comment by quicktrick** [comment]
I commented out the check but it didn't help. The build succeeded again for `openSUSE_Leap_42.3` and failed for `openSUSE_Tumbleweed`. 

Here are archived build logs from `Open Build Service` and `rspamd.spec` file (if anyone is interested in them).

[rspamd_build_logs.zip](https://github.com/vstakhov/rspamd/files/1418687/rspamd_build_logs.zip)

So far I'm not competent enough to solve this problem. :(
