### ISSUE TITLE
Build problems on centos

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rspamd#700]
Hi.

Last build for centos broken, because of rspamd.service.patch conflicts with rspamd.service

rspamd.service:
```
[Service]
Type=forking
NonBlocking=true
ExecStart=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f
User=_rspamd
RuntimeDirectory=rspamd
RuntimeDirectoryMode=0755
Restart=always
```

rspamd.service.patch:
```
 [Service]
-ExecStart=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f
-User=_rspamd
+ExecStart=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f -u _rspamd -g _rspamd
 RuntimeDirectory=rspamd
 RuntimeDirectoryMode=0755
 Restart=always
```

And because of this two lines:
```
Type=forking
NonBlocking=true
```
patch failed in build process.

And there is another problem with spec file - teher is no entry for fuzzy-worker.inc:
```
%config(noreplace) %{rspamd_confdir}/worker-normal.inc
+%config(noreplace) %{rspamd_confdir}/worker-fuzzy.inc
%config(noreplace) %{rspamd_confdir}/modules.d/*
```

**Comment by f-andrey** [comment]
Small offtop

https://github.com/vstakhov/rspamd/blob/master/centos/rspamd.spec#L26 need fix gmime to gmime-devel

**Comment by vstakhov** [comment]
Could you please send patches? I'm using https://github.com/vstakhov/rspamd-build-scripts to build rspamd, so I'm not aware of this issue (maybe @fatalbanana is?)

**Comment by damned-trooper** [comment]
File `rspamd/centos/sources/rspamd.service.patch` should be like this:
```
NonBlocking=true
-ExecStart=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f 
-User=_rspamd 
+ExecStart=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f -u _rspamd -g _rspamd 
RuntimeDirectory=rspamd 
RuntimeDirectoryMode=0755 
Restart=always
```
sorry, I don't know, how to create a patch to patch file.

**Comment by fatalbanana** [comment]
I have some patches ready but I expect RPM packaging needs further attention (points in this ticket are addressed anyway).

**Comment by damned-trooper** [comment]
Thanks a lot.
