### ISSUE TITLE
Systemd.service after #707 Pull request

### ISSUE THREAD

**Issue by f-andrey** [vstakhov/rspamd#709]
After #707 add `Type=forking` it is recommended to also use the `PIDFile=`?
https://www.freedesktop.org/software/systemd/man/systemd.service.html

> PIDFile= Takes an absolute file name pointing to the PID file of this daemon. Use of this option is recommended for services where Type= is set to forking. systemd will read the PID of the main process of the daemon after start-up of the service. systemd will not write to the file configured here, although it will remove the file after the service has shut down if it still exists.

systemd not create pid by default need add options `pidfile = "$RUNDIR/rspamd.pid";` for systemd config

Why would cease to use the standard mechanism?
```
 -User=_rspamd

 +ExecStart=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f -u _rspamd -g _rspamd
```
@fatalbanana

**Comment by fatalbanana** [comment]
Hmmm, I'm not sure why `Type=forking` is there actually (rspamd is run with `-f` so it does not fork). Likely something here should be changed. #707 didn't introduce this, just updated a patch. The patch exists because `User=` setting does not work on CentOS 7, or at least, it did not work in my experience.

**Comment by f-andrey** [comment]
I missed that this is not the service itself and the patch :)

My systems work fine `User=_rspamd` rspamd.x86_64 0:1.2.8-1
```
# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
uname -a
Linux 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ps aux | grep rspam
_rspamd  18972  0.2  0.3 316504 10252 ?        Ss   21:44   0:00 rspamd: main process
_rspamd  18973  0.0  0.2 316760  7552 ?        S    21:44   0:00 rspamd: controller process
_rspamd  18974  0.0  0.2 316760  7620 ?        S    21:44   0:00 rspamd: normal process
_rspamd  18975  0.0  0.2 316756  7168 ?        S    21:44   0:00 rspamd: normal process

systemd
Version     : 219
Release     : 19.el7_2.11 (and old 9)
```

Maybe this patch not actual?

`Type=forking` added after #430 in main .service this not crash him, but changes his behavior, before service is displayed as a `active (running)` now `activating (start)` although the rest of the service such as working correctly
