### ISSUE TITLE
Multimap description not working

### ISSUE THREAD

**Issue by andypl78** [vstakhov/rspamd#712]
rspamd version 1.3.0-0~git185~ae8f01a~jessie
example from multimap.conf file
`local_bl_rcpt { type = "rcpt"; map = "$DBDIR/local_bl_rcpt.map.inc"; symbol = "LOCAL_BL_RCPT"; description = "Local Black List RCPT"; }`

![rspamd-multimap](https://cloud.githubusercontent.com/assets/7813646/16685048/be2c2a7e-4508-11e6-8396-6cc19afe6b18.jpg)

**Comment by vstakhov** [comment]
Why do you think that it doesn't work?

**Comment by andypl78** [comment]
WebUI shows undefined as seen in the attached screenshot
