### ISSUE TITLE
Per-user statistics seem to be affected by 'rspamc -r', not '-d'

### ISSUE THREAD

**Issue by leoboiko** [vstakhov/rspamd#723]
The manpage and the webpage (at https://rspamd.com/doc/configuration/statistic.html ) suggest `rspamc -d`, but I can only get usernames into the sqlite database with `rspamc -r`. Otherwise the `user.name` column is empty.

For examples, see https://groups.google.com/forum/#!topic/rspamd/Sk7DNh_8Amk .

Version: `1.2.8-1~jessie` (Debian jessie).

**Comment by leoboiko** [comment]
Further points:

 - If the message includes a `Delivered-to:` header, it seems to take precedence over the command-line `-r`.
 - If one passes the same address to both `-d` and `-r`, it will behave as if with just a `-d`, i.e. empty `user.name`.

**Comment by vstakhov** [comment]
It should be fixed now, thanks for report.
