### ISSUE TITLE
Another R_MIXED_CHARSET FP

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#725]
~~~
2016-07-17 15:37:51 #30847(controller) <a425dd>; chartable; rspamd_chartable_process_word_utf: word 300кг, badness: 1.00
~~~
Message sample:
~~~
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit


300кг

~~~

**Comment by xpunkt** [comment]
8bit is not unicode encoded, doh :=)

good catch

**Comment by moisseev** [comment]
@xpunkt What `Content-Transfer-Encoding:` do you expect for utf-8?

**Comment by xpunkt** [comment]
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

seen in mail from github

**Comment by moisseev** [comment]
It's because there is no non-Latin characters in that mail from GitHub. It consists only of ASCII characters, which only use the lower 7 bits for each character. National characters in UTF-8 require at least 8 bit.

**Comment by xpunkt** [comment]
lets test it so

blåbærgrød

so what do github do now :=)
