### ISSUE TITLE
rspamc stat fails on out-of-the-box install on Debian Jessie

### ISSUE THREAD

**Issue by xeyownt** [vstakhov/rspamd#740]
I follow the quickstart guide from https://rspamd.com/doc/quickstart.html.
My system is a Debian Jessie on VPS, with systemd.

```bash
apt-get --no-install-recommends install rspamd
dpkg -l | grep rspamd
# ii  rspamd              1.2.8-1~jessie        amd64     Rapid spam filtering system
systemctl enable rspamd.socket
systemctl start rspamd.socket
rspamc stat
# Results for command: stat (0.000 seconds)
# IO write error: Connection refused
```

Note that `systemctl enable rspamd.socket` is not necessary because it was enabled already.

Now I can get it to work with

```bash
rspamc -h ::1:11334 stat
# Results for command: stat (5.980 seconds)
# Messages scanned: 0
# ...
rspamc -h ::1:11334 stat
# Results for command: stat (0.004 seconds)
# Messages scanned: 0
# ...
```
First start is very slow because service must be started.

Oddly enough it does not work on localhost ipv4:
```bash
rspamc -h 127.0.0.1:11334 stat
# Results for command: stat (0.000 seconds)
# IO write error: Connection refused
```

Is it intended behaviour? If so, maybe the quickstart guide should be updated with the new rspamc line.
 
It took me several hours to figure this out, first because I had ipv6 disabled on my kernel, and second because of trying to understand systemd stuff and obscure `rspamd.conf` file (`bind_socket = "systemd:0"`, what does this mean?).

**Comment by fatalbanana** [comment]
`systemd:0` means first systemd socket (FD 3), `systemd:1` is the second (FD 4) and so on.

There are indeed issues with IPv4 vs IPv6 under systemd and quickstart should be updated. Something like `rspamc < /dev/null` should work.

**Comment by xeyownt** [comment]
I confirm your suggestion works:

```bash
systemctl stop rspamd.service                                                                                   
# Warning: Stopping rspamd.service, but it can still be activated by:
#  rspamd.socket
systemctl status rspamd.service                                                                       
# ● rspamd.service - rapid spam filtering system
#    Loaded: loaded (/lib/systemd/system/rspamd.service; disabled)
#    Active: inactive (dead) since Thu 2016-07-21 19:16:09 CEST; 5s ago
# ...
```
We see that service is inactive. Now let's trigger it:
```bash
rspamc < /dev/null
# Results for file: stdin (0.000 seconds)
# HTTP error: 503, Invalid length
systemctl status rspamd.service
# ● rspamd.service - rapid spam filtering system
#    Loaded: loaded (/lib/systemd/system/rspamd.service; disabled)
#    Active: active (running) since Thu 2016-07-21 19:16:37 CEST; 1s ago
# ...
```
We see that service was automatically started.
