### ISSUE TITLE
rspamd: writev (127.0.0.1), Connection refused

### ISSUE THREAD

**Issue by xeyownt** [vstakhov/rspamd#748]
I'm still trying to install rmilter/rspamd on a debian Jessie/postfix/dovecot stack. So far I managed to get everything to work correctly, including rspamd webui, but unfortunately by editing some of the package files (`/lib/systemd/system/*`) to force ipv4 sockets.

I'd like to revert all my changes in these files, and only keep configuration changes in /etc as it should be.

Currently, file `/lib/systemd/system/rspamd.socket` contains this:

```
[Socket]
ListenStream=11333
ListenStream=[::1]:11334
BindIPv6Only=both
```
With this configuration, on my system, the port 11334 is only open on ipv6. This is not a problem because I can tell Apache to reverse proxy to ipv6 [::1]:11334, and this works. Note that I can't connect to 127.0.0.1:11334 (despites the BindIPv6Only option).

The problem is that I can't tell rmilter to connect to [::1]:11333. Depending on whether I use square brackets or not, I get parsing errors.

```
... rmilter[15852]: config file parse error! line: 49, text: [::1], reason: syntax error
... ober rmilter[15852]: yyparse: cannot parse config file, 1 errors
... ober rmilter[15892]: config file parse error! line: 49, text: :1:11333, reason: syntax error
... ober rmilter[15892]: yyparse: cannot parse config file, 1 errors
```
And using address 127.0.0.1:11333, I get the errors:
```
... rmilter[1832]: <7a6b3b759d>; spamdscan: start scanning message on 127.0.0.1
... rmilter[1832]: <7a6b3b759d>; rspamd: writev (127.0.0.1), Connection refused
... rmilter[1832]: <7a6b3b759d>; spamdscan: finish scanning message on 127.0.0.1
... rmilter[1832]: <7a6b3b759d>; rspamdscan: failed to scan, retry, 127.0.0.1, /tmp/msg.XX57AIw6
```
I tried all possible settings for rspamd `secure_ip` parameter (either "127.0.0.1", "::1", "::1 127.0.0.1" or even empty). It seems the problem is more in the fact that the ipv6 socket is not open for both ipv4/ipv6, despite the systemd config and that my system seems correctly configured:

```bash
sysctl -a|grep v6|grep bind
# net.ipv6.bindv6only = 0
```

**Comment by fatalbanana** [comment]
`BindIPv6Only` won't apply in case listening address is specified, so controller listens only on IPv6 under systemd socket activation.

Port 11333 has no listening address set and as such is listening on all addresses.

`secure_ip` setting affects merely privileged controller commands (via port 11334), port 11333 will accept messages for scanning from anywhere that can connect to it.

Correct way to make changes to systemd socket file is to create `/etc/systemd/system/rspamd.socket.d/override.conf` and add changed settings there (or these will be overwritten when package is upgraded). You will need to run `systemctl daemon-reload` and `systemctl restart rspamd.socket` to affect the changes.

Rmilter being unable to connect seems to suggest the socket is not running- check `systemctl status rspamd.socket`, `netstat -lnp` and try scanning a message with rspamc: eg. `rspamc /etc/passwd` - then check that the service came up: `systemctl status rspamd.service`

**Comment by xeyownt** [comment]
Thanks for the quick feedback.

First, regarding ipv6->ipv4 forwarding, I read somewhere that this might require doing `echo '1' > /proc/sys/net/ipv6/conf/all/forwarding`. I didn't test that exhaustively so I can report anything on that here. In any case, I configured everything in /etc as you suggest to force ipv4 sockets (thanks for the tip btw). 

So, in file `/etc/systemd/system/rmilter.service.d/override.conf`
```
[Service]
Restart=always
```
File `/etc/systemd/system/rmilter.socket.d/override.conf`
```
[Socket]
ListenStream=
ListenStream=127.0.0.1:9900
```
File `/etc/systemd/system/rspamd.socket.d/override.conf`
```
[Socket]
ListenStream=
ListenStream=127.0.0.1:11333
ListenStream=127.0.0.1:11334
```
Of course, I tell postfix to connect to ipv4 port, ie. in `/etc/postfix/main.cf`:
```diff
 # rmilter setup
+smtpd_milters = inet:127.0.0.1:9900
+milter_default_action = accept
+milter_protocol = 6
+milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
```

Finally, I could fix the `connection refused` message in two different ways. If ipv6 is enabled, I have to edit `/etc/rmilter.conf.common` as follows:
```diff
-    servers = r:localhost:11333;
+    servers = r:127.0.0.1:11333;
```
The second method is simply to disable ipv6 (e.g. via /etc/sysctl.d). In that case, either `localhost` or `127.0.0.1` can be used.

In general, I wonder why the rmilter/rspamd packages are configured by default to use systemd or ipv6 sockets, when it seems that using ipv4 is much less troublesome?

**Comment by xpunkt** [comment]
# /etc/hosts
::1 ipv6.localdomain ipv6
127.0.0.1 ipv4.localdomain ipv4

viola, use ipv4/ipv6 hostnames where its needed

**Comment by fatalbanana** [comment]
The way for this to work reliably under different configurations is for it to bind IPv4/IPv6 both like rspamd does by default when not using systemd socket activation. Unfortunately it does not seem that systemd provides a way to do this.

Systemd socket activation was added for (official) Debian packages & regrettably carried over to some other platforms. Getting rid of it would not be particularly simple & would create confusion.

**Comment by xeyownt** [comment]
Thanks xpunkt for the tip. I'll try that for my own understanding. Still lot to learn on ipv6.

For the rest, no problem. Maybe as a suggestion, you could add a link to this bug report (and any others that are relevant) in the quick start guide. Or simply copy-paste the config above as an example of ipv4 only config.

**Comment by xpunkt** [comment]
note how i ordered hostnames in that listnings, its always alias names last

i just posted it here to rule out that its simple
