### ISSUE TITLE
Fix systemd socket activation fiasco

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#759]
Remaining known issues with systemd socket activation are:

1) Controller listens on IPv6 only, which means that controller commands like `rspamc stat` might not work without passing `-h` depending on system configuration.
2) Socket file will fail on systems without IPv6 support

~~I believe I can fix both. Unfortunately, it seems that we will need two `.socket` files where we used to have one, which is potentially disruptive & confusing to users. But I think the change is worth it & we could try manage this as best possible in packaging.~~ Actually multiple socket files results in unpredictable behaviour, and stuff we need to deal with this is not available in versions of systemd we want to support, so just give up all hope & rip out socket activation completely?

3) Socket activation is unfamiliar & confusing to many users.

Is not really something we can fix. Could be addressed somewhat by improving documentation. If we rip out socket activation it becomes a non-issue.

**Comment by skibbipl** [comment]
Regarding issue 1) - it's enough to put following line to /ets/hosts (which is default in Debian I believe):
`::1     localhost ip6-localhost ip6-loopback`
I'm not sure however what will happen if system is not IPv6 enabled (is it possible on modern linux distros?)

**Comment by xpunkt** [comment]
except that format is incorrect

<ip> <fqdn> <alias> <more aliases>

in that order is correct

localhost must not be first

127.0.0.1 localhost.<your-domain-name> localhost.localdomain localhost
::1 localhost.<your-domain-name> localhost.localdomain localhost

::1 ipv6.localdomain
127.0.0.1 ipv4.localdomain

so reorder it, and its fine
