### ISSUE TITLE
Add "Authentication-Results" header

### ISSUE THREAD

**Issue by lifeofguenter** [vstakhov/rspamd#78]
It would be nice if rspamd could add a header "Authentication-Results" which gives a "parsable" summary of spf and dkim verification.

Basically that what Gmail is offering:

```
    Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of xxx@xxx.xxx designates 81.xxx.xxx.xxx as permitted sender) smtp.mail=xxx@xxx.xxx;
       dkim=pass header.i=@xxx.xxx
```

I only know of gmails web-app that will display a human-readable "trusted origin domain", but other mail clients might implement similar.
But even if not, for a techie its simple enough to manually verify emails if needed.

Currently I could activate debug-headers via rmilter, but they are too verbose.
##

**Comment by vstakhov** [comment]
Implemented.
