### ISSUE TITLE
FORGED_RECIPIENTS false positives in outbound filter for multiple recipients

### ISSUE THREAD

**Issue by leoboiko** [vstakhov/rspamd#807]
I run a single rspamd both inboundly and outboundly.  Our setup has separate inbound and outbound Postfixes, with a large number of aliases and forwards, and a distinct (internal) Mailman server.

The inbound processing mostly seems to handle all that pretty well; the aliases go through without a hitch, and Mailman triggers `FORGED_RECIPIENTS_MAILLIST` as intended.  However, the *outbound* processing – literally the same rspamd with the same rmilter – triggers FORGED_RECIPIENTS for the very same valid messages, when they have multiple recipients.  I'm not sure why, or how to fix it, so I configured outbound-specific settings to disable FORGED_RECIPIENTS.  If there's anything I can do to help debug this issue, I'd be glad to help.

**Comment by fatalbanana** [comment]
Maybe your users are using `Bcc`. :) Things to look at are contents of To/Cc headers vs recipients seen by the MTA.

**Comment by leoboiko** [comment]
It's not a `Bcc` issue.  Here's a message with `To:` and `Cc:` to myself:

```
From: Leonardo Boiko <leoboiko@ime.usp.br>
To: leoboiko@ime.usp.br
Cc: leoboiko@ime.usp.br
```

Here are the Spamd results when it's going out:

```
X-Spamd-Result: default: False [0.00 / 15.00]
 FROM_IME(-2.00)[]
 FORGED_RECIPIENTS(2.00)[]
 MIME_GOOD(-0.10)[text/plain]
 ONCE_RECEIVED(0.10)[]
```

And the results for the same message going in:

```
X-Spamd-Result: default: False [-3.20 / 15.00]
 R_DKIM_ALLOW(-1.10)[ime.usp.br]
 FROM_IME(-2.00)[]
 MIME_GOOD(-0.10)[text/plain]
```

I also get the same results if the recipients are different addresses, of course.  I also get the same false positive with comma-list `To`s (`To: user1@example.com, user2@example.com`).  However, it won't trigger for a simple `To: user@example.com`.

Here are the Postfix logs for the false-positive'd outbound message:

> Aug  4 10:55:48 iris postfix/smtpd[19398]: C39ED2900181: client=kitsune.ime.usp.br[143.107.45.146]
Aug  4 10:55:48 iris rmilter[32632]: <5069700f1b>; mlfi_data: queue id: <C39ED2900181>
Aug  4 10:55:48 iris postfix/cleanup[14119]: C39ED2900181: message-id=<ymm7fbw63kr.fsf@kitsune.ime.usp.br>
Aug  4 10:55:50 iris rmilter[32632]: <5069700f1b>; msg done: queue_id: <C39ED2900181>; message id: <ymm7fbw63kr.fsf@kitsune.ime.usp.br>; ip: 143.107.45.146; from: <leoboiko@ime.usp.br>; **rcpt: <leoboiko@ime.usp.br> (2 total)**; user: unauthorized; spam scan: no spam; virus scan: clean; dkim: not signed, ignored
Aug  4 10:55:54 iris postfix/qmgr[26743]: C39ED2900181: from=<leoboiko@ime.usp.br> size=718, nrcpt=1 (queue active)
Aug  4 10:55:59 iris postfix/smtp[19490]: C39ED2900181: **to=<leoboiko@ime.usp.br>**, relay=hermes.ime.usp.br[143.107.45.4]:25, delay=10, delays=5.4/0.02/3/1.8, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 315CE7804FF)
Aug  4 10:55:59 iris postfix/qmgr[26743]: C39ED2900181: removed


And the rspamd.log:

> 2016-08-04 10:55:48 #6570(normal) <2877bb>; task; rspamd_message_parse: loaded message; id: <ymm7fbw63kr.fsf@kitsune.ime.usp.br>; queue-id: <C39ED2900181>; size: 618
2016-08-04 10:55:50 #6570(normal) <2877bb>; task; rspamd_task_write_log: id: <ymm7fbw63kr.fsf@kitsune.ime.usp.br>, qid: <C39ED2900181>, ip: 143.107.45.146, from: <leoboiko@ime.usp.br>, (default: F (no action): [0.00/15.00] [FORGED_RECIPIENTS(2.00),FROM_IME(-2.00),MIME_GOOD(-0.10),ONCE_RECEIVED(0.10)]), len: 618, time: 1939.976ms real, 3.134ms virtual, dns req: 18

By contrast, here are the Postfix logs for a message with a single recipient, which won't trigger `FORGED_RECIPIENTS`:

> Aug  4 10:57:39 iris postfix/smtpd[19398]: 444AC2900181: client=kitsune.ime.usp.br[143.107.45.146]
Aug  4 10:57:39 iris rmilter[32632]: <39cc4bbfb5>; mlfi_data: queue id: <444AC2900181>
Aug  4 10:57:39 iris postfix/cleanup[14119]: 444AC2900181: message-id=<ymm1t2463ho.fsf@kitsune.ime.usp.br>
Aug  4 10:57:39 iris rmilter[32632]: <39cc4bbfb5>; msg done: queue_id: <444AC2900181>; message id: <ymm1t2463ho.fsf@kitsune.ime.usp.br>; ip: 143.107.45.146; from: <leoboiko@ime.usp.br>; **rcpt: <leoboiko@ime.usp.br>** (1 total); user: unauthorized; spam scan: no spam; virus scan: clean; dkim: not signed, ignored
Aug  4 10:57:42 iris postfix/qmgr[26743]: 444AC2900181: from=<leoboiko@ime.usp.br>, size=721, nrcpt=1 (queue active)
Aug  4 10:57:46 iris postfix/smtp[19490]: 444AC2900181: **to=<leoboiko@ime.usp.br>**, relay=hermes.ime.usp.br[192.168.45.4]:25, delay=6.9, delays=3.7/0/3/0.22, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as F0B9B7804FF)
Aug  4 10:57:46 iris postfix/qmgr[26743]: 444AC2900181: removed

**Comment by fatalbanana** [comment]
I'm guessing your problem is probably this length check: https://github.com/vstakhov/rspamd/blob/master/src/plugins/lua/forged_recipients.lua#L35 - though I'm seeing an unrelated issue which could cause this as well.

**Comment by fatalbanana** [comment]
Header processing was a bit rotten. Please try latest experimental build for your platform. The situation should be somewhat improved at least.

**Comment by leoboiko** [comment]
I'll test it live next Monday and report the results.

**Comment by leoboiko** [comment]
I confirm that 1.3.2 solved this. No more `FORGED_RECIPIENTS` false positives, while still detecting true positives.

Thank you for prompt help as always! You guys are a model open source project.
