### ISSUE TITLE
lua_dns_callback: call to dns callback failed

### ISSUE THREAD

**Issue by croessner** [vstakhov/rspamd#821]
I get this in my logs:

2016-08-08 10:07:19 #2823(normal) lua_dns_callback: call to dns callback failed: /usr/share/rspamd/lua/dmarc.lua:197: bad argument #2 to 'insert_result' (number expected, got nil)

rspamd-1.3.1 on Gentoo Linux

emerge --info rspamd
Portage 2.2.28 (python 2.7.10-final-0, hardened/linux/amd64/no-multilib, gcc-4.9.3, glibc-2.22-r4, 4.4.8-hardened-r1 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.4.8-hardened-r1-x86_64-Intel-R-_Xeon-R-_CPU_L5640_@_2.27GHz-with-gentoo-2.2
KiB Mem:     4048368 total,    619732 free
KiB Swap:    2097148 total,   2096956 free
Timestamp of repository gentoo: Sun, 07 Aug 2016 21:15:01 +0000
sh bash 4.3_p42-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
ccache version 3.2.4 [enabled]
app-shells/bash:          4.3_p42-r1::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo
dev-util/ccache:          3.2.4::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.19.1::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.69::gentoo
sys-devel/automake:       1.13.4::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.3::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r4::gentoo

**Comment by fatalbanana** [comment]
Fixed [here](https://github.com/vstakhov/rspamd/commit/30443544a321d540f7046b001caf97f3f1d5e2ef). There have been some further fixes to dmarc.lua as well- you could grab new copy [here](https://raw.githubusercontent.com/vstakhov/rspamd/master/src/plugins/lua/dmarc.lua).

**Comment by croessner** [comment]
Thank you. Seems, the messages are gone now.
