### ISSUE TITLE
Drop in replacement for spamassasin's "spamc"

### ISSUE THREAD

**Issue by vext01** [vstakhov/rspamd#824]
Hi,

This is more a query than a bug.

I use OpenSMTPd and fdm (https://github.com/nicm/fdm) to receive mail. Currently I classify spam by piping each message to spamassassin's `spamc`, which appends a header, then fdm inspects the header to decide whether to put the message into the spam box.

It looks like this in fdm:

```
action "classify_spam" rewrite "/usr/local/bin/spamc"

...
match accounts {"stdin"} {
        match all action "classify_spam" continue
        match "^X-Spam-Flag:.*[Yy][Ee][Ss]" in headers action "spam"
        ...
```

I'm looking for a drop in alternative. Can rspamd be one?

I read somewhere that the goal of rspamc is not to modify messages and that this would be the job of the MTA. Are you set on this?

I can trivially wrap rspamc with a Pyhon script to add such headers, but I think this would be a useful addition for many users. Especially users of OpenSMTPD, which (AFAICT) doesn't integrate with rspamd.

Thoughts?

Thanks

**Comment by vstakhov** [comment]
https://rspamd.com/doc/integration.html#lda-mode

**Comment by vext01** [comment]
Ah, looks like I just need `--mime`. Thanks
