### ISSUE TITLE
"task:set_rmilter_reply" not work

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rspamd#835]
Today I updated to latest version rspamd (1.3.2) and rmilter (1.9.1) on Centos 6 with postfix.
And try restore  SpamAssassin-compatible headers: namely X-Spam-Status, X-Spam-Level and X-Spamd-Bar ( from https://rspamd.com/doc/migration.html#migrating-from-rmilter-18-to-rmilter-19).
But any new headers not inserted.
Also try simle example^
    task:set_rmilter_reply({
        add_headers = {{'X-Lua', 'test'}},
        remove_headers = {'DKIM-Signature'},
    })
Result is same - no new header.

**Comment by fatalbanana** [comment]
At least rspamd part seems to work for me. If you scan with rspamc do you see `[Metric: rmilter]` (or if you scan with `rspamc --json` do you see `rmilter` block)? If not, does rspamd log an error?

**Comment by mnik247** [comment]
Following @fatalbanana advice:
1)  # rspamc msg.Admin
Results for file: msg.Admin (0.026 seconds)
[Metric: default]
Spam: true
Score: 6.24 / 19.00
Action: add header
Symbol: BAYES_HAM (-2.99)[99.99%]
Symbol: DATE_IN_PAST (1.00)
Symbol: FORGED_SENDER (0.30)
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: R_MISSING_CHARSET (2.50)
Symbol: R_MIXED_CHARSET (0.54)
Symbol: SPAM_FLAG (5.00)
**[Metric: rmilter]**

2) №rspamc --json  msg.Admin
Results for file: msg.Admin (0.045 seconds)
{
    "default": {
        "is_spam": true,
        "is_skipped": false,
        "score": 6.247703,
        "required_score": 19.0,
        "action": "add header",
        "DATE_IN_PAST": {
            "name": "DATE_IN_PAST",
            "score": 1.0,
            "description": "Message date is in past"
        },
        "FORGED_SENDER": {
            "name": "FORGED_SENDER",
            "score": 0.300000,
            "description": "Sender is forged (different From: header and smtp MAIL FROM: addresses)"
        },
        "BAYES_HAM": {
            "name": "BAYES_HAM",
            "score": -2.999999,
            "description": "Message probably ham, probability: ",
            "options": [
                "99.99%"
            ]
        },
        "MIME_GOOD": {
            "name": "MIME_GOOD",
            "score": -0.100000,
            "description": "Known content-type",
            "options": [
                "text/plain"
            ]
        },
        "SPAM_FLAG": {
            "name": "SPAM_FLAG",
            "score": 5.0,
            "description": "Message was already marked as spam"
        },
        "R_MISSING_CHARSET": {
            "name": "R_MISSING_CHARSET",
            "score": 2.500000,
            "description": "Charset is missing in a message"
        },
        "R_MIXED_CHARSET": {
            "name": "R_MIXED_CHARSET",
            "score": 0.547703,
            "description": "Mixed characters in a message"
        }
    },
    **"rmilter": {
        "remove_headers": [
            [
                "X-Spamd-Bar"
            ],
            [
                "X-Spam-Level"
            ],
            [
                "X-Spam-Status"
            ]
        ],
        "add_headers": [
            [
                "X-Spamd-Bar",
                "++++++"
            ],
            [
                "X-Spam-Level",
                "******"
            ],
            [
                "X-Spam-Status",
                "Yes, score=6.25"
            ]
        ]
    }**
}

No errors in rspamd.log and maillog

**Comment by fatalbanana** [comment]
So your issue seems to be with rmilter. Are you running a suitable version? I've not at all tested it I'm afraid.

**Comment by mnik247** [comment]
I builded rmilter rpm today from source (as usualy) on Centos 6.
Aug 10 22:29:27 rmilter[15464]: main: starting rmilter version 1.9.1, listen on inet:11332@127.0.0.1

**Comment by fatalbanana** [comment]
I've opened an issue against rmilter about this- since it seems clear that this is where it falls apart: https://github.com/vstakhov/rmilter/issues/148

**Comment by vstakhov** [comment]
```lua
task:set_rmilter_reply({
  add_headers = {['X-Lua'] = 'test'}},
  remove_headers = {['DKIM-Signature'] = 1},
})
```

That's the format expected by Rmilter. Number is the position of header in a message (since there could be more than one header with the specified name).

**Comment by mnik247** [comment]
I tried @vstakhov variant (corrected):
    task:set_rmilter_reply({
        add_headers = {['X-Lua'] = 'test'},
        remove_headers = {['DKIM-Signature'] = 1},
    })

#rspamc --json  msg.Admin
Results for file: msg.Admin (0.070 seconds)
....................... 
    "rmilter": {
        "remove_headers": {
            "DKIM-Signature": 1
        },
        "add_headers": {
            "X-Lua": "test"
        }
    }

New header  "X-Lua" not add, header "DKIM-Signature" not removed.
Any advice?

**Comment by mnik247** [comment]
@vstakhov 
example from https://rspamd.com/doc/migration.html#migrating-from-rmilter-18-to-rmilter-19 
is not correct too?

**Comment by mnik247** [comment]
@vstakhov 
Isit possible now add/remove headers with latest version rspamd (1.3.2) and rmilter (1.9.1)?
Now add/remove headers not work.

**Comment by fatalbanana** [comment]
Please try rmilter from git.

**Comment by mnik247** [comment]
thanks @fatalbanana - I wil rebuild rmilter rpm from git.

**Comment by mnik247** [comment]
thanks @fatalbanana - now add/remove headers **worked.**
Exaples  from https://rspamd.com/doc/migration.html#migrating-from-rmilter-18-to-rmilter-19 - **not work.**
Worked exaples:
_-with one argument:_
`task:set_rmilter_reply({`
`add_headers = {['X-Spam-LUA'] = 'test' },`
`remove_headers = {['X-Mailer'] = 1},`
`})`
_-with many arguments:_
`    task:set_rmilter_reply({`
 `     add_headers = {`
 `       ['X-Spamd-Bar'] = spambar,`
 `       ['X-Spam-Level'] = spamlevel,`
 `       ['X-Spam-Status'] = spamstatus,`
 `       ['X-Spam-Score'] = spamscore,`
 `     },`
 `    remove_headers = {`
 `       ['X-Spamd-Bar'] = 1,`
 `       ['X-Spam-Level'] = 1,`
 `       ['X-Spam-Status'] = 1,`
 `       ['X-Spam-Score'] = 1,`
 `       ['X-Spamd-Result'] = 1,`
 `       ['X-Rspamd-Server'] = 1,`
 `       ['X-Rspamd-Scan-Time'] = 1,`
 `       ['X-Rspamd-Queue-ID'] = 1,`
 `       ['X-Spam-Flag'] = 1,`
 `     }`
  `  })`

And now I can delete unwanted headers from other rspamd servers! Yes!
Thanks @fatalbanana and @vstakhov.
