### ISSUE TITLE
Force DKIM check for specific domains

### ISSUE THREAD

**Issue by qk4l** [vstakhov/rspamd#854]
Hi,

Currently DKIM module support `domains` map and multiply score if message _has_ dkim incorrect sign but module does not check messages without dkim sign at all.

So there are no way to force DKIM check for specific domains.

**Comment by fatalbanana** [comment]
You could do this with [whitelist](https://rspamd.com/doc/modules/whitelist.html ) or [multimap](https://rspamd.com/doc/modules/multimap.html#conditional-maps).

**Comment by qk4l** [comment]
@fatalbanana Thank you!

**Comment by qk4l** [comment]
@fatalbanana, @vstakhov Sorry guys, does _whitelist_ module deprecated https://github.com/vstakhov/rspamd/issues/118#issuecomment-64901613 ?

Seems it's not working (v. 3.3-1).

**Comment by fatalbanana** [comment]
Whitelist module has been completely rewritten since then (the old module sharing its name was deprecated). It seems to be working for me with default configuration; I've not tried to make it do anything special.
