### ISSUE TITLE
Does rspamd classifier work with Chinese language?

### ISSUE THREAD

**Issue by weishen** [vstakhov/rspamd#855]
I am a newbie to rspamd, from the document I learned I could not figure out whether the classifier could know how to tokenize Chinese language,  with utf8 encoding, Chinese characters are  2 to 4 bytes long, what will the osb do with it? and what other tokenizers are supported in rspamd?

**Comment by vstakhov** [comment]
It knows how to work with Chinese. It doesn't know how to extract the first form of words in text but that shouldn't affect the overall result significantly.

**Comment by weishen** [comment]
Could you elaborate how rspamd works with this? As far as I know, rspamd uses 5-gram bayers classifier, given a Chinese sentence,  what will rspamd do for each step? What it sees is just a steam of octets, so how to make sure each token being a meaningful or not meaningful word?

**Comment by fatalbanana** [comment]
Rspamd [converts messages to UTF-8 internally](https://rspamd.com/doc/faq.html#how-does-rspamd-support-different-characters-sets). You can test tokenization with [util.tokenize_text](util.tokenize_text):

```
$ rspamadm lua
LuaJIT 2.0.2> util = require "rspamd_util"
LuaJIT 2.0.2> util.tokenize_text("你好，世界")
{[1] = 你好, [2] = 世界}
```
