### ISSUE TITLE
Possible mistake in FORWARDING_MAILRU composite

### ISSUE THREAD

**Issue by rpv-tomsk** [vstakhov/rspamd#874]
https://github.com/vstakhov/rspamd/blob/master/conf/composites.conf#L26

```
composite "FORWARDING_MAILRU" {
    expression = "(FWD_MAILRU & (R_SPF_SOFTFAIL | R_SPF_FAIL)) | FWD_MAILRU";
}
```

Left part of expression is excessive - it can't be true unless FWD_MAILRU condition (right part) is true. 
So, we needn't check (R_SPF_SOFTFAIL | R_SPF_FAIL) condition.

**Comment by fatalbanana** [comment]
I suppose idea here is to replace symbol in combination with other symbols or by itself (though I don't see that the latter should be necessary). This composite should apply to other forwarding-related symbols too. I have made it so.

**Comment by AlexeySa** [comment]
My idea was to remove the SPF errors on forwarded mails from mail.ru

**Comment by rpv-tomsk** [comment]
It was unclear for me as newbie. 

Maybe an additional option needs to be added? I.e

``
composite "FORWARDING_MAILRU" {
    expression = "FWD_MAILRU";
    remove_weight = ["R_SPF_SOFTFAIL",  "R_SPF_FAIL"];
}
``

**Comment by AlexeySa** [comment]
banana made a universal solution.

May be add hostname check to FWD_GOOGLE?

**Comment by rpv-tomsk** [comment]
> I suppose idea here is to replace symbol in combination with other symbols or by itself (though I don't see that the latter should be necessary).

>banana made a universal solution.

I see and I understand that.

What is about some kind of `remove_weight`  option? It will be more clear to understand and more flexible. Since you have implemented this in that way, I think there is no other more correct way to disable symbols by conditions.

I'm newbie .)

**Comment by fatalbanana** [comment]
`policy = "remove_weight"` or `~SYMBOL_NAME` work for this purpose [(reference)](https://rspamd.com/doc/configuration/composites.html) - the former seems to have been applied to the rule in question.
