### ISSUE TITLE
FTBFS

### ISSUE THREAD

**Issue by cicku** [vstakhov/rspamd#88]
Lua: 5.2.2

In file included from /home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.c:25:0:
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:28: error: expected declaration specifiers or '...' before '(' token
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                            ^
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:48: error: expected declaration specifiers or '...' before '(' token
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                                                ^
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:81: error: expected declaration specifiers or '...' before numeric constant
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                                                                                 ^
src/lua/CMakeFiles/rspamd-lua.dir/build.make:57: recipe for target 'src/lua/CMakeFiles/rspamd-lua.dir/lua_common.c.o' failed
make[2]: *** [src/lua/CMakeFiles/rspamd-lua.dir/lua_common.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_message.c:26:0:
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:28: error: expected declaration specifiers or '...' before '(' token
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                            ^
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:48: error: expected declaration specifiers or '...' before '(' token
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                                                ^
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:81: error: expected declaration specifiers or '...' before numeric constant
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                                                                                 ^
src/lua/CMakeFiles/rspamd-lua.dir/build.make:103: recipe for target 'src/lua/CMakeFiles/rspamd-lua.dir/lua_message.c.o' failed
make[2]: *** [src/lua/CMakeFiles/rspamd-lua.dir/lua_message.c.o] Error 1
In file included from /home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_task.c:26:0:
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:28: error: expected declaration specifiers or '...' before '(' token
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                            ^
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:48: error: expected declaration specifiers or '...' before '(' token
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                                                ^
/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9/src/lua/lua_common.h:24:81: error: expected declaration specifiers or '...' before numeric constant
 luaL_register (lua_State *L, const gchar *name, const struct luaL_reg *methods)
                                                                                 ^
src/lua/CMakeFiles/rspamd-lua.dir/build.make:80: recipe for target 'src/lua/CMakeFiles/rspamd-lua.dir/lua_task.c.o' failed
make[2]: *** [src/lua/CMakeFiles/rspamd-lua.dir/lua_task.c.o] Error 1
make[2]: Leaving directory '/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9'
CMakeFiles/Makefile2:242: recipe for target 'src/lua/CMakeFiles/rspamd-lua.dir/all' failed
make[1]: *** [src/lua/CMakeFiles/rspamd-lua.dir/all] Error 2
make[1]: Leaving directory '/home/rpmaker/rpmbuild/BUILD/rspamd-0.6.9'
Makefile:120: recipe for target 'all' failed
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.28sXjs (%build)

**Comment by cjsthompson** [comment]
I tried again with 0.8.0 and I still have the same problem.

**Comment by fatalbanana** [comment]
Please try installing package or using fedora.patch from here: https://build.opensuse.org/package/show/home:susenerf:branches:home:cebka/rspamd

**Comment by cjsthompson** [comment]
Hey thanks for the tip @fatalbanana , worked like a charm :)
