### ISSUE TITLE
Некорректная обработка DKIM.

### ISSUE THREAD

**Issue by AloneShadow** [vstakhov/rspamd#880]
Корректные DKIM записи определяются как R_DKIM_REJECT.
Ниже вырезки DKIM из логов exim, которые определены как R_DKIM_REJECT:
```
DKIM: d=mta-bbcspool.convio.net s=selector1 c=relaxed/relaxed a=rsa-sha1 b=1024 i=@mta-bbcspool.convio.net t=1471860026 [verification succeeded]
DKIM: d=voron.ua s=default c=relaxed/simple a=rsa-sha256 b=1024 t=1471860226 [verification succeeded]
DKIM: d=forum.mt5.com s=mail c=relaxed/relaxed a=rsa-sha256 b=1024 [verification succeeded]
DKIM: d=myheritage.com s=sm c=simple/simple a=rsa-sha1 b=1024 i=@myheritage.com [verification succeeded]
DKIM: d=tez-tour.com s=all c=relaxed/simple a=rsa-sha256 b=1024 t=1471859398 [verification succeeded]
DKIM: d=bosch.com s=2015-01-21 c=relaxed/simple a=rsa-sha256 b=1024 t=1471860255 l=10 [verification succeeded]
```
Записи дополнительно проверялись на http://dkimcore.org и все имели статус "This is a valid DKIM key record".
Версия rspamd 1.3.3, ОС freebsd 11.

**Comment by vstakhov** [comment]
I cannot say anything about DKIM without full messages samples. You can encrypt them using my gpg key if there is some sensitive information.

**Comment by vstakhov** [comment]
I mean that DKIM_REJECT does not mean incorrect key as you somehow supposed: it means that signature validation failed somehow. From my previous experiences that could be caused by Exim: it sometimes alters messages in a weird way before sending them to spam scan (e.g. CRLF normalization).

**Comment by AloneShadow** [comment]
Ниже два тестовых письма.
Разница между ними в теле письма. Если тело пустое - срабатывает DKIM_REJECT, если не пустое - DKIM_ALLOW.
Вложить другие письма, кроме своих тестовых, увы, не могу.

[bad dkim.txt](https://github.com/vstakhov/rspamd/files/429977/bad.dkim.txt)
[good dkim.txt](https://github.com/vstakhov/rspamd/files/429978/good.dkim.txt)

**Comment by vstakhov** [comment]
It should be fixed in cfcd442. Could you please test?

**Comment by xpunkt** [comment]
rmilter could dissable 8BITMIME before signing

amavisd deault do this from postfix to amavisd content dissabling 8BITMIME, then dkim signing in amavids is safe on outgoing testers since its 7bit

**Comment by AloneShadow** [comment]
Заменил  src/libserver/dkim.c. Пересобрал. Результат тот же (DKIM_REJECT) на письмо с пустым телом.
Так же прилагаю пример уже не тестового письма с публичного сервиса, которое так же опеределяется DKIM_REJECT.
[MyHeritage!.txt](https://github.com/vstakhov/rspamd/files/431958/MyHeritage.txt)

**Comment by vstakhov** [comment]
This particular message (MyHeritage) has indeed bad signature:

```
% opendkim-testmsg < ~/Downloads/MyHeritage.txt
opendkim-testmsg: dkim_eom(): Bad signature
```

I've fixed the cases you've provided in your previous message: bad dkim and good dkim are now both `DKIM_ALLOW`.

**Comment by AloneShadow** [comment]
Установил версию 1.3.4. 
На пустое письмо срабатывают такие симовлы:
`R_SPF_ALLOW, RCVD_TLS_ALL, DMARC_POLICY_ALLOW_WITH_FAILURES, MIME_GOOD`
На не пустое:
`DMARC_POLICY_ALLOW, R_SPF_ALLOW, RCVD_TLS_ALL, R_DKIM_ALLOW, MIME_GOOD`
Exim в обоих случаях говорит verification succeeded.
После проверки DKIM в exim сразу же идет проверка в rspamd  и письмо принимается, т.е. если и есть модификации, то только eximом на этапе проверки DKIM.
По поводу MyHeritage озадачен еще больше. opendkim-testmsg действительно определяет неверную сигнатуру, но exim утверждает, что сигнатура правильная. Уж не знаю кому верить и куда копать.

**Comment by vstakhov** [comment]
Yes, exim definitely alters messages. I've received couple of bug reports in the past. On the other hand, I've never ever seen misdetections from opendkim. However, all that depends on end-of-lines definition which are absolutely crazy defined in the DKIM standard.

**Comment by vstakhov** [comment]
In fact, I'd recommend to turn exim DKIM checks off as they might cause messages normalization which would definitely breaks a message for Rspamd DKIM.

**Comment by AloneShadow** [comment]
Отключил в exim проверку DKIM. Ситуация не изменилась: пустое письмо не проходит проверку. Попробую еще пересобрать exim без поддержки DKIM, чтобы наверняка.

**Comment by fatalbanana** [comment]
FWIW I tested `MyHeritage!.txt` with Exim and found that it declared the signature broken.

To disable DKIM-checking in Exim add somewhere in ACL:

`warn control = dkim_disable_verify`

**Comment by vstakhov** [comment]
If you speak about `bad dkim.txt` then here are results from the manual check:
```
rspamc  bad.dkim.txt | grep DKIM
Symbol: R_DKIM_ALLOW (-1.10)[rostest.ukr.net]
```

**Comment by AloneShadow** [comment]
В exim ACL у меня следующее:
```
RCPT:
  warn control = dkim_disable_verify
  accept
DATA:
  warn spam = exim:true
           log_message = [RSpamd]: Score: $spam_score 
  accept
```
А вот вывод ручной проверки для тестовых писем:
с непустым телом:
```
rspamc good_dkim.txt 
Results for file: good_dkim.txt (0.037 seconds)
[Metric: default]
Spam: false
Score: 3.20 / 15.00
Action: no action
Symbol: HFILTER_HOSTNAME_UNKNOWN (2.50)
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: RDNS_NONE (1.00)
Symbol: R_DKIM_ALLOW (-0.20)[rostest.ukr.net]
Message-ID: 6813775d-35a9-bd4c-475f-10ee51d69c1f@rostest.ukr.net
```
с пустым телом:
```
rspamc bad_dkim.txt 
Results for file: bad_dkim.txt (0.174 seconds)
[Metric: default]
Spam: false
Score: 4.40 / 15.00
Action: greylist
Symbol: HFILTER_HOSTNAME_UNKNOWN (2.50)
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: RDNS_NONE (1.00)
Symbol: R_DKIM_REJECT (1.00)[rostest.ukr.net]
Message-ID: 13fb46d4-d098-453f-ab81-7d0fcd1c8f63@rostest.ukr.net
```
Файлы прикрепил, на всякий случай.
Изначально я думал, что это баг, потому и сообщил. Не исключено, что где-то что-то неправильно настроил. 
В любом случае дискуссия затягивается и мне становится как-то не по себе. 
Если это крайний случай с малой долей вероятности и только у меня, тогда предлагаю закрыть дискуссию.
[bad_dkim.txt](https://github.com/vstakhov/rspamd/files/439254/bad_dkim.txt)
[good_dkim.txt](https://github.com/vstakhov/rspamd/files/439255/good_dkim.txt)

**Comment by vstakhov** [comment]
Ok, your bad_dkim contains `\n` instead of `\r\n`: that's what I was talking about when I've mentioned poorly defined DKIM standard. I'll try to provide fix soon.

**Comment by vstakhov** [comment]
Ok, I've added another fix. Could you please test it with your samples?

**Comment by AloneShadow** [comment]
После фикса проверка DKIM корректна. Корректна даже после eximовской проверки.
Спасибо.
Единственное, что смутило: на пустом сообщении не срабатывает символ RCVD_TLS_ALL, срабатывает на не пустом. Но это такое...
