### ISSUE TITLE
Bypass check for specific address

### ISSUE THREAD

**Issue by ddeenniiss** [vstakhov/rspamd#881]
Is it possible ti bypass check for a specific address or domain ?

Something like @whitelist_sender_maps for amavis ?

**Comment by fatalbanana** [comment]
Yes- you could use [prefilter maps in multimap](https://rspamd.com/doc/modules/multimap.html#pre-filter-maps) or [settings](https://rspamd.com/doc/configuration/settings.html).

**Comment by ddeenniiss** [comment]
Thanks, but what's the syntax of file for map = "file:///tmp/from.map";

Only a list of address ? With a ; ?

# local.d/multimap.conf
SENDER_FROM_WHITELIST_USER {
  type = "from";
  filter = "email:user";
  map = "file:///tmp/from.map";
  action = "accept"; # Prefilter mode
}

**Comment by fatalbanana** [comment]
List of whatever is to be matched in the map, separated by newlines. If you want to match full address (and not just localpart) you should be using `email:addr` as filter.

**Comment by fatalbanana** [comment]
Note also that prefilter map requires `prefilter = true`.

**Comment by rpv-tomsk** [comment]
If you want to add negative score (like amavis does) then use following snippet to add to local.d/multimap.conf:

```
LOCAL_SENDER_FROM_WHITELIST_DOMAIN {
    type = "from";
    filter = "email:domain";
    map = "/etc/rspamd/whitelist.sender.domain.map";
    score = -6.0
  }
```

That is whitelist by sender domain which I use. You can use ``email:addr`` as filter for sender email whitelist.

**Comment by fatalbanana** [comment]
This could probably be closed.
