### ISSUE TITLE
settings: reject score cannot be negative (no action instead of reject)

### ISSUE THREAD

**Issue by andryyy** [vstakhov/rspamd#885]
Hi,

I tried some per-user settings and modified the reject score to -100 ... When I test it, this happens:

spamdscan: scan, time: 1.066, server: localhost, metric: default: [-0.750 / -100.000], symbols: DMARC_POLICY_ALLOW(-0.25)[gmail.com], R_SPF_ALLOW(-0.20)[ip6:2a00:1450:4000::/36], MIME_GOOD(-0.10)[multipart/alternative, text/plain], R_DKIM_ALLOW(-0.20)[gmail.com]

https://i.imgur.com/PYZEipf.png

I did not add a symbol but decided to set reject to a large negative number. I changed this to using a symbol now, just wanted to report it. :-)

Bye
André

**Comment by fatalbanana** [comment]
Why are you trying to do that? If you want to reject mail use [multimap](https://rspamd.com/doc/modules/multimap.html#pre-filter-maps).

**Comment by andryyy** [comment]
I have a SQL table with whitelist_from and blacklist_from entries for all mailbox users. Also users can change their score for "add header" and "reject" there (so that low-score spam is moved to junk by a global sieve script).

I found a lot of hints doing this with user settings. It is even recommended in the documentation. You even recommended it in a [mailing list entry](https://groups.google.com/forum/message/raw?msg=rspamd/8RqmIW9b5OM/mKe5L3KwTMYJ).
I just had a single day with rspamd and rmilter, excuse me when I miss some points. Maybe multimap is new?

**Comment by fatalbanana** [comment]
Prefilter maps in multimap are fairly new. If you want to effect change in `add header` and `reject` thresholds then `settings` is still the way to do that. To preserve sanity, `reject` should be greater than `add header` should be greater than `no action`.

**Comment by andryyy** [comment]
Thanks!

So there is no way/no sane way I could handle that with multimap?

I need to get more into dynamic maps tomorrow. A static (but at least auto generated) settings section is working as intended now. Thanks, again. :-)

**Comment by fatalbanana** [comment]
If your goal is to effect a whitelist/blacklist (ie. force mail to be accepted/rejected/tagged or add a score) `multimap` and `whitelist` module are of interest, though if you want to do this _per-user_ `settings` will probably be the most comfortable way to do it (there is `want_spam` parameter which is effectively a whitelist; it misses something for blacklisting currently but that could be easily added or you could work around it).

If you want to change thresholds, you want `settings`.

Advantage of `settings` is that the module configuration itself can be stored in a map, which makes it easier to update & settings can also be passed in dynamically by integration layer.

**Comment by andryyy** [comment]
Thanks! For blacklisting I added a dummy symbol now, as recommended. An option would be nice, but I will have to wait for someone to create it. :-)

**Comment by andryyy** [comment]
Everything works as intended now! I can read from a dynamic map and insert my settings per-user.

I just wonder wether or not my issue is a bug. A spam score of -0.75 of -1000 should be rejected, right? It just won't work when the score for reject is negative. It works when it is positive.

**Comment by fatalbanana** [comment]
You could try redefining scores for all metric actions (including whichever else are defined: typically `no action`, `add_header` and `greylist`) though likely negative values for `reject` don't work as desired (it's generally expected that spam scores are positive and ham scores are negative).
