### ISSUE TITLE
Switch off surbl checks for auth users

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#886]
Please help. How to off surbl checks for auth users?

**Comment by fatalbanana** [comment]
You could use [settings](https://rspamd.com/doc/configuration/settings.html) (with `groups_disabled` parameter).

**Comment by AlexeySa** [comment]
Thank you! It's works!

**Comment by AlexeySa** [comment]
Sory, this no work.
```
settings {
	authenticated {
		priority = high;
		authenticated = yes;
		apply "default" {
			disable_groups = ["surbl"];
		}
	}
}
```
 I am not find this functional in settings plugin :(

**Comment by fatalbanana** [comment]
Perhaps `authenticated` parameter indeed does not work. You could substitute `user = "/.*/";` as workaround.

**Comment by AlexeySa** [comment]
I am not found "disable_groups" or "disable" or "groups" in this module :(

**Comment by fatalbanana** [comment]
That should be `groups_disabled` actually.

**Comment by xpunkt** [comment]
rmilter does not use rspamd anyway when sasl authed, so why does other ?

**Comment by moisseev** [comment]
@xpunkt Rmilter checks mail from authenticated users with Rspamd if `strict_auth = yes;` is set.
