### ISSUE TITLE
[Bug] Authenticated users and domainkey DNS-queries

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#888]
Rspamd continues to request dkim keys for authenticated users.

Local DNS (dnsmasq) strace:
recvmsg(7, {msg_name(16)={sa_family=AF_INET, sin_port=htons(37405), sin_addr=inet_addr("127.0.0.1")}, msg_iov(1)=[{";&\1\0\0\1\0\0\0\0\0\1\10DKIMDKIM\n_domainkey\22DOMAINDOMAINDOMAIN\2ru\0\0\20\0\1\0\0)\20\0\0\0\0\0\0\0", 1280}], msg_controllen=0, msg_flags=0}, 0) = 70

User Message:
```
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=DOMAINDOMAINDOMAIN.ru; s=DKIMDKIM;
        h=Sender:Content-Transfer-Encoding:Content-Type:MIME-Version:Subject:To:Message-ID:Reply-To:From:Date; bh=H5eE6VBC99OxarBLxE2AMNWzhX5pxUTat/M0K7VGUT0=;
        b=S6Sr+04eqw5hpLqjRhLG+dv3nM2pA2pFtoj0Il5J7fkWnxk8rFUNZe3wO6lIO9Tcf8tL3lUqHL3oHWrrPq8Jz2n+dClydjODiIUbZefxhFTcTlAFj4RCNPqS3CIgnXztqRpP0VuEzqXT1EJ3WOSBg/ilrjLPGNdafvuyamSbsFo=;

test
```
| /usr/local/rspamd/bin/rspamc -h /var/run/rspamd/rspamd.sock --user authuser@example.com

**Comment by fatalbanana** [comment]
Continues to request DKIM keys after you did something that would make you expect otherwise?

In any case this module seems to be a candidate to disable by default for authenticated users / local networks.

**Comment by AlexeySa** [comment]
I thought that dkim checks disabled by default...
