### ISSUE TITLE
FUZZY_DENIED

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rspamd#891]
Hi.

I've got FUZZY_DENIED on some normal messages. For example:
`FUZZY_DENIED(9.20)[1:bce8ae39d1:0.75, 1:cf9751a94a:0.87]`
(this is correct notification from Microsoft)
Is there a way to avoid this  false positive?

**Comment by moisseev** [comment]
@damned-trooper You can negate FUZZY_DENIED using settings:
~~~lua
settings {
    subscribe_ru {
        priority = high;
        from = "gluck@mail.subscribe.ru";
        from = "/^namma[0-9]{8}@subscribe\.ru$/";
        apply "default" {
            FUZZY_DENIED = 0.0;
        }
    }
}
~~~
I hope it be resolved properly some day.

**Comment by damned-trooper** [comment]
Thanks a lot.
