### ISSUE TITLE
Howto add "spam_header" to all mails, spam or not spam with YES or NO value

### ISSUE THREAD

**Issue by Elodie81** [vstakhov/rspamd#893]
Greetings,

I'm testing rmilter 1.9.2-1jessie and rspamd 1.3.4-1jessie on Debian and I would like add the header "spam_header" to all mails, spam or not spam by saying 'YES for the spam and 'NO' when it's not a spam.

I have inside my /etc/rmilter.conf.local this :

> extended_spam_headers = yes;
> spam_header = "X-Spam-Flag";
> spam_header_value = "YES";

Secondly, i would like add the score of the current mail, spam or not spam with this header : "X-Spam-Score: 0". Is it possible ?

I can do that with my old spamassassin, how could I do with rmilter/rspamd please ?

Thank you for your responses,
Élodie

**Comment by fatalbanana** [comment]
`X-Spam-Status` added by example script contains these values. Edited version of this script:

~~~lua
rspamd_config:register_symbol({
  name = 'RMILTER_HEADERS',
  type = 'postfilter',
  callback = function(task)
    local metric_score = task:get_metric_score('default')
    local score = metric_score[1]
    local required_score = metric_score[2]
    -- X-Spamd-Bar & X-Spam-Level
    local spambar
    local spamlevel = ''
    if score < 0 then
      spambar = string.rep('-', score*-1)
    elseif score > 0 then
      spambar = string.rep('+', score*1)
      spamlevel = string.rep('*', score*1)
    else
      spambar = '/'
    end
    -- X-Spam-Status
    local is_spam
    local spamstatus
    local action = task:get_metric_action('default')
    if action ~= 'no action' and action ~= 'greylist' then
      is_spam = 'Yes'
    else
      is_spam = 'No'
    end
    spamstatus = is_spam .. ', score=' .. string.format('%.2f', score)
    -- X-Spam-Score & X-Spam-Flag
    local spamscore = string.format('%.2f', score)
    local spamflag = is_spam
    -- Add headers
    task:set_rmilter_reply({
      add_headers = {
        ['X-Spamd-Bar'] = spambar,
        ['X-Spam-Level'] = spamlevel,
        ['X-Spam-Status'] = spamstatus,
        ['X-Spam-Score'] = spamscore,
        ['X-Spam-Flag'] = spamflag
      },
      remove_headers = {
        ['X-Spamd-Bar'] = 1,
        ['X-Spam-Level'] = 1,
        ['X-Spam-Status'] = 1,
        ['X-Spam-Score'] = 1,
        ['X-Spam-Flag'] = 1
      }
    })
  end
})
~~~

**Comment by Elodie81** [comment]
Thank a lot for your response fatalbanana,

notkoos from official channel of rspamd on freenode.net give me this script too : http://pastebin.com/8Jk6tvk8

So I tested his code and your code into the file /etc/rspamd/lua/rspamd.local.lua
I checked with "rspamc --json /root/test.mail" to test it, this is the result :

>     "rmilter": {
>         "add_headers": {
>             "X-Spamd-Bar": "",
>             "X-Spam-Level": "",
>             "X-Spam-Score": "0.30",
>             "X-Spam-Status": "No, score=0.30",
>             "X-Spam-Flag": "No"
>         },
>         "remove_headers": {
>             "X-Spamd-Bar": 1,
>             "X-Spam-Level": 1,
>             "X-Spam-Score": 1,
>             "X-Spam-Status": 1,
>             "X-Spam-Flag": 1
>         }
>     }

It seem better but when i send a mail with postfix no header is added ...

I know rmilter is working because clamav is call inside it and when i send a EICAR message rmiler/clamav react and block it.

But after this clamav test still inside rmilter, i call rspamd but nothing happen ... no header is added ...

Where i should check please ?

**Comment by Elodie81** [comment]
All is working now :)

The tips : "rmilter does not scan email (with rspamd) for authorized users (SASL) by default".

My config was correct, except i need to add this into rmilter.conf : strict_auth = yes
Thanks to xpoint from IRC ;)

Just to know : strict_auth is a global directive but it's act only on rspamd behavior and not clamav which is inside the same config rmilter file.
