### ISSUE TITLE
*_EXCESS_BASE64 on `Mail.Ru Mailer 1.0` mails.

### ISSUE THREAD

**Issue by rpv-tomsk** [vstakhov/rspamd#902]
Hi!

I have an email with the following headers:

```
Return-Path: <USERNAME1@bk.ru>
Received-SPF: pass (bk.ru ... _spf.mail.ru: 94.100.181.253 is authorized to use 'USERNAME1@bk.ru' in 'mfrom' identity (mechanism 'ip4:94.100.176.0/20' matched)) receiver=debian.domain.tld; identity=mailfrom; envelope-from="USERNAME1@bk.ru"; helo=fallback5.mail.ru; client-ip=94.100.181.253
Received: from fallback5.mail.ru (fallback5.mail.ru [94.100.181.253])
    by mail.domain.tld (Postfix) with ESMTP id 67B85180066
    for <dj@domain.tld>; Sun, 28 Aug 2016 13:19:50 +0700 (+07)
Received: from f49.i.mail.ru (f49.i.mail.ru [94.100.185.3])
    by fallback5.mail.ru (mPOP.Fallback_MX) with ESMTP id EADDFBD62B22
    for <dj@domain.tld>; Sun, 28 Aug 2016 09:10:20 +0300 (MSK)
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=bk.ru; s=mail;
    h=Content-Type:Message-ID:Reply-To:Date:MIME-Version:Subject:To:From; bh=hjuqZt4uid8dfPICVE+vT7P8zFXO5oBON3sFkRZNUn0=;
    b=Cupjnx+aa5KVgp3rrOZIg5dHm5cUZzLlZJHKJO/1WttbaBlbwPOApNhJ/oCA4wQ041Ao4In/KRfzVzOUtmrmQd7gAkQnhsDPFg7YW6Zefn/EUOTeJUFco4D06b7HDtHJSImg0A1sUUMkhtZB+sKFfSnwrcjOh+yMSl/nZBk2qIw=;
Received: from [195.206.53.54] (ident=mail)
    by f49.i.mail.ru with local (envelope-from <vozvrat_goodwin@bk.ru>)
    id 1bdtI5-0005pn-WD
    for dj@domain.tld; Sun, 28 Aug 2016 09:09:58 +0300
Received: from [195.206.53.54] by e.mail.ru with HTTP;
    Sun, 28 Aug 2016 09:09:57 +0300
From: =?UTF-8?B?R29vZHdpbiBDaW5lbWE=?= <USERNAME1@bk.ru>
To: =?UTF-8?B?ZGo=?= <dj@domain.tld>
Subject: =?UTF-8?B?RndkOiA=?=
MIME-Version: 1.0
X-Mailer: Mail.Ru Mailer 1.0
X-Originating-IP: [195.206.53.54]
Date: Sun, 28 Aug 2016 09:09:57 +0300
Reply-To: =?UTF-8?B?R29vZHdpbiBDaW5lbWE=?= <USERNAME1@bk.ru>
X-Priority: 3 (Normal)
Message-ID: <1472364597.464828483@f49.i.mail.ru>
Content-Type: multipart/mixed;
    boundary="----q8cqDo4P0R2K8OND2o35hfkzXKCANlMC-quAXU0e8FkVWQitR-1472364597"
X-Mailru-Sender: 68F6BD668818CD2CEE6E9FD2A8433876B53BD1FE7A6A39AD112F1BAEC09DDF52535B054CEE07E02E660823B2EEFD31DC
X-Mras: OK
X-Spam: yes
```

That headers produces scores:

```
2016-08-28 13:20:14 #10875(normal) <62f256>; task; rspamd_task_write_log: id: <1472364597.464828483@f49.i.mail.ru>, qid: <67B85180066>, ip: 94.100.181.253, from: <vozvrat_goodwin@bk.ru>, (default: F (add header): [7.73/15.00] [RECEIVED_SPAMHAUS_XBL(3.00),FROM_EXCESS_BASE64(1.50),REPLYTO_EXCESS_BASE64(1.50),TO_EXCESS_BASE64(1.50),BAYES_SPAM(0.73),R_DKIM_ALLOW(-0.20),R_SPF_ALLOW(-0.20),MIME_GOOD(-0.10),RCVD_IN_DNSWL_LOW(0.00)]), len: 835506, time: 491.995ms real, 18.702ms virtual, dns req: 26
```

The  `FROM_EXCESS_BASE64(1.50),REPLYTO_EXCESS_BASE64(1.50),TO_EXCESS_BASE64(1.50)` 

combination looks too strong. 

What is the correct way to reduce such scores?

**Comment by rpv-tomsk** [comment]
Hi!

I have an email with the following headers:

```
From: =?UTF-8?B?R29vZHdpbiBDaW5lbWE=?= <vozvrat_goodwin@bk.ru>
To: =?UTF-8?B?ZGo=?= <dj@nikolas.ru>
Subject: =?UTF-8?B?RndkOiA=?=
MIME-Version: 1.0
X-Mailer: Mail.Ru Mailer 1.0
X-Originating-IP: [195.206.53.54]
Date: Sun, 28 Aug 2016 09:09:57 +0300
Reply-To: =?UTF-8?B?R29vZHdpbiBDaW5lbWE=?= <vozvrat_goodwin@bk.ru>
X-Priority: 3 (Normal)
Message-ID: <1472364597.464828483@f49.i.mail.ru>
Content-Type: multipart/mixed;
	boundary="----q8cqDo4P0R2K8OND2o35hfkzXKCANlMC-quAXU0e8FkVWQitR-1472364597"
X-Mailru-Sender: 68F6BD668818CD2CEE6E9FD2A8433876B53BD1FE7A6A39AD112F1BAEC09DDF52535B054CEE07E02E660823B2EEFD31DC
X-Mras: OK
X-Spam: yes
```

That headers produces scores:

```
2016-08-28 13:20:14 #10875(normal) <62f256>; task; rspamd_task_write_log: id: <1472364597.464828483@f49.i.mail.ru>, qid: <67B85180066>, ip: 94.100.181.253, from: <vozvrat_goodwin@bk.ru>, (default: F (add header): [7.73/15.00] [RECEIVED_SPAMHAUS_XBL(3.00),FROM_EXCESS_BASE64(1.50),REPLYTO_EXCESS_BASE64(1.50),TO_EXCESS_BASE64(1.50),BAYES_SPAM(0.73),R_DKIM_ALLOW(-0.20),R_SPF_ALLOW(-0.20),MIME_GOOD(-0.10),RCVD_IN_DNSWL_LOW(0.00)]), len: 835506, time: 491.995ms real, 18.702ms virtual, dns req: 26
```

The  `FROM_EXCESS_BASE64(1.50),REPLYTO_EXCESS_BASE64(1.50),TO_EXCESS_BASE64(1.50)` 

combination looks too strong.

What is the correct way to reduce such scores?

**Comment by fatalbanana** [comment]
This could be done with a [composite](https://rspamd.com/doc/configuration/composites.html).

**Comment by moisseev** [comment]
Yes, mail.ru encodes in base64 everything. I'm using `settings`.

rspamd.conf.local:
~~~nginx
settings {
    base64_mail_ru {
        priority = high;
        from = "@mail.ru";
        from = "@inbox.ru";
        from = "@list.ru";
        from = "@bk.ru";
        apply "default" {
            REPLYTO_EXCESS_BASE64  = 0.0;
            FROM_EXCESS_BASE64     = 0.0;
            TO_EXCESS_BASE64       = 0.0;
        }
    }
}
~~~
@fatalbanana could you please post a composites example for this particular case?

**Comment by vstakhov** [comment]
So mail, such ru, wow!

**Comment by rpv-tomsk** [comment]
```X-Mailer: Mail.Ru Mailer 1.0```
I think I need to check `X-Mailer` header and build some kind of MAIL_RU_MAILER symbol to use in composite.

**Comment by rpv-tomsk** [comment]
Can you please check correctness of the following config:
```
local xm_mail_ru_mailer_1_0 = 'X-Mailer=/^Mail\.Ru Mailer 1\.0$/'
local rcvd_e_mail_ru = 'Received=/^from \\[\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\] by e\.mail\.ru with HTTP;/'
reconf['MAIL_RU_MAILER'] = string.format('(%s) & (%s)', xm_mail_ru_mailer_1_0, rcvd_e_mail_ru)
```
Will this config match headers in provided example? I'm unsure which modifiers should be also applied to these regexps.

Also, can you please provide me a link to (LUA) modifiers documentation?

```
local MAIL_RU_Return_Path<----->= 'Return-path=/^\\s*<.+\\@mail\\.ru>$/iX'
local MAIL_RU_Received<><------>= 'Received=/from mail\\.ru \\(/mH'
```

I don't understand what /X and /H modifiers means here.

**Comment by vstakhov** [comment]
https://rspamd.com/doc/modules/regexp.html

**Comment by rpv-tomsk** [comment]
New syntax for `composite`, which was proposed in #874, might be good in this case too:

```
composite "MAIL_RU_MAILER_BASE64" {
    expression = "MAIL_RU_MAILER";
    remove_weight = ["FROM_EXCESS_BASE64","REPLYTO_EXCESS_BASE64","TO_EXCESS_BASE64"];
}
```

Without this we need to put three `composite` to remove each header independently.

**Comment by vstakhov** [comment]
You don't need 3 composites. 

Moreover, I don't see any advantages of your syntax and there is a big disadvantage: it introduces another layer of complexity for both users and me to distinguish between two types of composite expressions.

**Comment by rpv-tomsk** [comment]
>You don't need 3 composites. 

I have three symbols matched: `FROM_EXCESS_BASE64(1.50),REPLYTO_EXCESS_BASE64(1.50),TO_EXCESS_BASE64(1.50)`

How to disable all of them by single composite?

**Comment by rpv-tomsk** [comment]
I have just checked this Lua config:
```
local xm_mail_ru_mailer_1_0 = 'X-Mailer=/^Mail\\.Ru Mailer 1\\.0$/H'
local rcvd_e_mail_ru = 'Received=/^from \\[\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\] by e\\.mail\\.ru with HTTP;/mH'
reconf['MAIL_RU_MAILER'] = string.format('(%s) & (%s)', xm_mail_ru_mailer_1_0, rcvd_e_mail_ru)
```

And it does not work. Can you help me?

**Comment by xpunkt** [comment]
only one \ is needed to excabe, try make \\ to single \

**Comment by vstakhov** [comment]
@xpunkt: No, you are wrong.

**Comment by rpv-tomsk** [comment]
Nope, double \\ was taken from existing configs.

Added following composite and things begin to work as expected:

```
composite {
    name = "MAIL_RU_MAILER_BASE64";
    expression = "~MAIL_RU_MAILER and (FROM_EXCESS_BASE64 || REPLYTO_EXCESS_BASE64 || TO_EXCESS_BASE64)";
}
```

**Comment by moisseev** [comment]
@vstakhov What about Lua API approach? Is it faster than regexp?
~~~lua
local rspamd_logger = require "rspamd_logger"

local symbol = 'LOCAL_MAILRU_MAILER'

local function mailru_mailer_cb(task)
  local header = task:get_header('X-Mailer')
  if header and header == 'Mail.Ru Mailer 1.0' then
  local rhs = task:get_received_headers()
    if rhs and rhs[#rhs]['by_hostname'] == 'e.mail.ru' then
      task:insert_result(symbol, 1)
      return true
    end
  end

  return false
end

rspamd_config:register_symbol({
  name = symbol,
  callback = mailru_mailer_cb,
})
rspamd_config:set_metric_symbol({
    name = symbol,
    group = 'header',
    score = 0.0,
    description = 'Composed with Mail.Ru Mailer',
    one_shot = true
})
~~~

**Comment by vstakhov** [comment]
Rspamd regexps are blazingly fast due to many factors. In fact, if you use Rspamd with Hyperscan (which you should do for all modern hardware platforms with SSSE3) new regexps does not increase scan time for messages (even for body regexps). The algorithmic complexity of SA regexp is similar to `O(N*M)` where N is length of scanned data and M is number of regexps. For Rspamd and Hyperscan it is closer to `O(N + M)`. However, you should avoid backtracking and other incompatible features (e.g. lookbehind).

Lua calls are **relatively** expensive. I think I need to provide more details about it. Perhaps, I'll do it in future.

**Comment by rpv-tomsk** [comment]
It is completely unclean what conditionals are evaluated NOT lazily.
It is unclean both for newbies and for team members.The following example/commits confirm this:

```
composite "FORWARDING_MAILRU" {
    expression = "(FWD_MAILRU & (R_SPF_SOFTFAIL | R_SPF_FAIL)) | FWD_MAILRU";
}
```
https://github.com/vstakhov/rspamd/commit/7ffc7a9c64e34c638e9b2b05b8012d6d32f56cab#diff-6e1a128358c037435da8a42a17201fe1
https://github.com/vstakhov/rspamd/commit/03ceb655ecb249b295d0863ac3cdc46ac9d35b4a#diff-6e1a128358c037435da8a42a17201fe1

**Comment by fatalbanana** [comment]
Actually I'm not sure composites are useful here. Way I'd do this would probably be to do add these symbols to a common group and use `max_score` in metric.

**Comment by moisseev** [comment]
@fatalbanana The point is to negate that symbols at all for mail.ru ESP webui MUA as they always encode headers in base64.
And I don't understand https://rspamd.com/doc/configuration/composites.html
