### ISSUE TITLE
failed to build on aarch64

### ISSUE THREAD

**Issue by clandmeter** [vstakhov/rspamd#907]
I am building rspamd on aarch64 with musl libc and gcc 6

https://github.com/vstakhov/rspamd/blob/master/contrib/mumhash/mum.h#L111

will result in:

rspamd-1.3.4/src/libcryptobox/../../contrib/mumhash/mum.h:117:27: error: expected ')' before ':' token

**Comment by vstakhov** [comment]
Is there any easy way to get aarch64 build environemnt? I've used `scaleway` arm machines to test `armv6` builds and they should be fine so far. However, I've never ever seen alive aarch64.
