### ISSUE TITLE
Huge size increase in Debian package

### ISSUE THREAD

**Issue by roedie** [vstakhov/rspamd#925]
Not sure if this should be reported here, but since Debian package 1.3.5 the size of the rspamd binaries has grown significantly.

1.3.4 package:
-rwxr-xr-x 1 root root 6764104 Aug 23 14:32 rspamadm
-rwxr-xr-x 1 root root 6459528 Aug 23 14:32 rspamc
-rwxr-xr-x 1 root root 6710472 Aug 23 14:32 rspamd
-rwxr-xr-x 1 root root   12786 Aug 23 14:22 rspamd_stats

1.3.5 package:
-rwxr-xr-x 1 root root 27292232 Sep  2 08:46 rspamadm
-rwxr-xr-x 1 root root 26983560 Sep  1 14:04 rspamc
-rwxr-xr-x 1 root root 27234568 Sep  1 14:04 rspamd
-rwxr-xr-x 1 root root    12786 Sep  1 13:52 rspamd_stats

Not sure if this is by design or something went wrong with packaging.

**Comment by fatalbanana** [comment]
Addressed in 1.3.5-2.
