### ISSUE TITLE
Can't set custom subject to append on Spam

### ISSUE THREAD

**Issue by reallumpi** [vstakhov/rspamd#931]
Hi,

I try to add add a Custom Prefix to append to Spam but this seems to be broken (or i am doing something terribly wrong). I am using rspamd/rmilter with the latest Packages from your Repo on Debian Wheezy.

metrics.conf:

```
metric {
    name = "default";
    # If this param is set to non-zero
    # then a metric would accept all symbols
    # unknown_weight = 1.0

    actions {
      reject = 15;
      add_header = 7;
      greylist = 3;
      rewrite_subject = 7;
      subject = "Spam";
    }
```

I get this Error when checking the Config:

```
[~]: rspamd -u _rspamd -t
2016-09-07 11:19:18 #22921(main) <gy5zpk>; cfg; rspamd_config_read: rcl parse error: invalid action definition: 'subject'
```

Versions in use:

```
ii  rmilter                              1.9.2-2~wheezy                       amd64        Another sendmail milter for different mail checks
ii  rspamd                               1.3.5-2~wheezy                       amd64        Rapid spam filtering system
```

So, is this a bug i am hitting, an intended behaviour for some reason or did i get something wrong from the Docs ? I appreciate any help. 

Cheers.

**Comment by Zukrain** [comment]
Try to use: 

`subject = Spam %s;`

My config in /etc/rspamd/override.d/metrics.conf is work.

```
subject = *****SPAM***** %s;

actions {
    reject = 15;
    add_header = 6;
    rewrite_subject = 6;
    greylist = 13;
}
```

**Comment by reallumpi** [comment]
AH i got it, i missunderstood the Documentation an placed it within the "actions" clause. So now it seems to work, thanks a lot !
