### ISSUE TITLE
Incorrect LOCAL_CONFDIR in FreeBSD

### ISSUE THREAD

**Issue by nORKy54** [vstakhov/rspamd#933]
How to test : in common.conf, add '.include "$LOCAL_CONFDIR/metrics.conf"

result with dump : 

```
# rspamadm configdump 
2016-09-07 14:40:40 #10984(rspamadm) <bmr7it>; cfg; rspamd_config_read: ucl parser error: cannot open file /usr/local/etc/rspamd/metrics.conf: No such file or directory
```

I don't see the 'local.d' directory.
rspamd version: 1.3.5

**Comment by nORKy54** [comment]
I think it's a sample config file error. need remplace in common.inc : 
```
.include(try=true) "$LOCAL_CONFDIR/rspamd.conf.local"
.include(try=true,priority=10) "$LOCAL_CONFDIR/rspamd.conf.local.override"
.include(try=true,priority=10) "$LOCAL_CONFDIR/rspamd.conf.override"
```
by

```
.include(try=true) "$LOCAL_CONFDIR/local.d/rspamd.conf.local"
.include(try=true,priority=10) "$LOCAL_CONFDIR/local.d/rspamd.conf.local.override"
.include(try=true,priority=10) "$LOCAL_CONFDIR/local.d/rspamd.conf.override"
```

**Comment by moisseev** [comment]
1. I believe the configdump error is not related to `.include` you've added. It seems the `/usr/local/etc/rspamd/metrics.conf` is missed (it should be installed by the port).
2. @nORKy54 you should create `local.d` and `override.d` directories by yourself. @vstakhov There are a few questions about missing config directories. I think FreeBSD port and other packages should create these directories.
3. @nORKy54 `$LOCAL_CONFDIR/local.d/metrics.conf` is already included in `$CONFDIR/metrics.conf`:
~~~
    .include(try=true; priority=1; duplicate=merge) "$LOCAL_CONFDIR/local.d/metrics.conf"
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/metrics.conf"
~~~
