### ISSUE TITLE
Website hard to read for eye handicaped people

### ISSUE THREAD

**Issue by croessner** [vstakhov/rspamd#953]
Hi,

I am pretty sure, this is not the optimal place for my question, but I don't know a better place.

My eyes are bad in two ways: One is I am red/green blind, as are 11% of all men. Reading the code snippet boxes is nearly impossible.

At the other side I also have MAcula Degeneration and I need to switch colors to inverse. This makes the code boxes as well unreadable. So for people like me, the documentation for this project is in some way unreachable.

What I ask is, if it was possible to use a different collor scheme. Ideally, the code boxes would also be based on a white background.

I hope there is some chance that this could be changed :-) I really love this project and I would very much love to dive deeper into it, if I could read the docs ;-)

Best wishes

Christian

**Comment by fatalbanana** [comment]
There is [rspamd.com repo](https://github.com/vstakhov/rspamd.com/) which might be the ideal place for this ticket. Firefox and Chrome have a 'reader mode' which I'd recommend trying but colour scheme should probably be adapted appropriately indeed.

**Comment by croessner** [comment]
I opened a new ticket here: https://github.com/vstakhov/rspamd.com/issues/145

Sidenote: The reader does not work well with code boxes. I already tried this out ;-)

**Comment by fatalbanana** [comment]
Since you've opened a new ticket for this I suggest closing the old one. ;)

**Comment by croessner** [comment]
:-)
