### ISSUE TITLE
ip_score module does not accept actions block

### ISSUE THREAD

**Issue by croessner** [vstakhov/rspamd#955]
Hi,

not sure why, but the example from https://rspamd.com/doc/modules/ip_score.html does not work, if the actions block is included. I copied the example and it seems the parser runs into problems. Is there some semicolon missing or double quotes? I guess it is something trivial, but don't know what.

Thanks

**Comment by moisseev** [comment]
Yes, the example isn't working. The parser doesn't understand single quotes. Try to use double quotes instead.

**Comment by fatalbanana** [comment]
Example config has been fixed.

**Comment by croessner** [comment]
Works :-) Thank you very much
