### ISSUE TITLE
symbol scored twice

### ISSUE THREAD

**Issue by vurgun** [vstakhov/rspamd#959]
Hello,
symbols are scored twice when settings and multimap module are used together.

settings.conf
```
settings {
    country_blacklist {
        priority = high;
        rcpt = "me@example.com";
        apply "default" {
            COUNTRY_BLACKLIST = 2.0;
        }
        symbols [
             "COUNTRY_BLACKLIST"
        ]
    }
}
```

multimap.conf
```
COUNTRY_BLACKLIST {
    type = "country";
    map = "file:///country.map";
}
```

country.map
```
RU
```

Result from rspamd log
```
---cut---
COUNTRY_BLACKLIST(4.00),
---cut---
```

How to reproduce

+ Rspamd version 1.3.5-2~wheezy
+ COUNTRY_BLACKLIST symbol is not defined in metrics.conf
+ When recipient is matched against settings -> rcpt -> me@example.com, COUNTRY_BLACKLIST  is scored twice to COUNTRY_BLACKLIST(4.00).
+ When recipient is NOT matched against settings -> rcpt -> me@example.com, COUNTRY_BLACKLIST score is zero (as it should be)  - COUNTRY_BLACKLIST(0.00)
+ ASN module is configured properly and works as expected; country name is exported properly

**Comment by fatalbanana** [comment]
It seems that second COUNTRY_BLACKLIST symbol would be added by configuration of settings module:

`
        symbols [
             "COUNTRY_BLACKLIST"
        ]
`

**Comment by vurgun** [comment]
Unfortunately there is no second symbol with the same name added. That was my first assumption as well

In the logs I can see
`<e3dddf>; lua; multimap.lua:406: cannot parse`

**Comment by vurgun** [comment]
oh, I got your idea now. 
Looks like that this part is not used only for Symbol score definition, but is used to call the symbols as well
```
        apply "default" {
            COUNTRY_BLACKLIST = 2.0;
        }
```

thanks, issue is completely resolved

**Comment by moisseev** [comment]
I don't think that `cannot parse` error is related to the issue.
I have a lot of `(normal) <7f3e62>; lua; multimap.lua:406: cannot parse` in the log as well.

**Comment by vurgun** [comment]
Thanks guys, everything was sorted out.
