### ISSUE TITLE
rspamc "IO read error: unexpected EOF" error on specific header

### ISSUE THREAD

**Issue by jhejl** [vstakhov/rspamd#977]
Rspamc can't scan the EML file which contains:

Return-Path: <ExcelloRedmine@excello.cz>

on first line. There's also a rspamd segfault message in dmesg:

`rspamd[29534]: segfault at 100000000a ip 000003c2f8770f96 sp 000003ddbeb1f0f0 error 4 in libglib2.0.so.0.4600.2[3c2f86fa000+150000]`

If I delete any of these brackets, problem goes away.

Pure (default configuration) rspamd-1.3.5 compiled on Gentoo linux with hardened kernel and PAX enabled (jit USE flag disabled).

Original file attached.
[rspamd_crash.txt](https://github.com/vstakhov/rspamd/files/490034/rspamd_crash.txt)

**Comment by piwats** [comment]
This is Gentoo specific. 'emerge --info' would be nice.

Judging by the libglib2 version, you have =dev-libs/glib-2.46.2-r3 installed on your system, when 2.48.2 is the last stable version in he portage tree.

Try to upgrade your system by running

`emerge --sync && emerge -avuDN @world --with-bdeps=y`
and
`emerge @preserved-rebuild`
and
`revdep-rebuild`

then do a complete remerge of rspamd.

**Comment by jhejl** [comment]
`emerge --info`

`Portage 2.3.0 (python 3.4.3-final-0, hardened/linux/amd64, gcc-4.9.3, glibc-2.22-r4, 4.4.8-hardened-r1 x86_64)
=================================================================
System uname: Linux-4.4.8-hardened-r1-x86_64-AMD_Opteron-TM-_Processor_6274-with-gentoo-2.2
KiB Mem:     4040204 total,    622496 free
KiB Swap:    2097148 total,   2097148 free
Timestamp of repository gentoo: Thu, 06 Oct 2016 00:45:01 +0000
sh bash 4.3_p46-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p46-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.22.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo
dev-util/cmake:           3.5.2-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.21.7::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.69::gentoo
sys-devel/automake:       1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.5::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r4::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: webrsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

virusfree
    location: /var/cache/portage/virusfree
    sync-type: git
    sync-uri: git://git.excello.cz/virusfree/overlay
    masters: gentoo

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -mtune=native"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /etc/stunnel/stunnel.conf /usr/share/gnupg/qualified.txt /var/qmail/alias /var/qmail/control /var/service/gldnsd/env /var/service/gldnsd/root/etc /var/service/wbldnsd/env"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe -mtune=native"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="acl amd64 berkdb bzip2 cli cracklib crypt cxx dri gdbm hardened iconv ipv6 justify lm_sensors mmx mmxext modules multilib ncurses nls nptl openmp pam pax_kernel pcre pie qmail-spp readline seccomp session sse sse2 ssl ssp tcpd unicode urandom xattr xtpax zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx fma4 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 xop" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="pc" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" L10N="en cs sk" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="amdgpu fbdev intel nouveau radeon radeonsi vesa dummy v4l" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON`

System is up-to-date.

Any ideas?

**Comment by piwats** [comment]
Try to remerge and then restart rspamd. Let's see how this will go...

**Comment by jhejl** [comment]
Thanks, after reemerging the system && world twice it still gives the error, this time it's against about proper GLIB:
```
segfault at 1000000001 ip 0000037229a041f6 sp 000003f06924c3a0 error 4 in libglib-2.0.so.0.4800.2[3722998d000+125000]
```
Seems like there's more errors on this system (it's old and contains lots of other packages that might break it). I've gave that up for now and installed RSPAMD on clean machines:

1. Fresh Gentoo with Gentoo sources - **RSPAMD works without errors**
2. Fresh Gentoo with hardened profile and hardened kernel - **RSPAMD is killed by PAX:**

```
[  162.101706] grsec: From 127.0.0.6: denied RWX mmap of <anonymous mapping> by /usr/bin/rspamd-1.3.5[rspamd:2589] uid/euid:101/101 gid/egid:247/247, parent /usr/bin/rspamd-1.3.5[rspamd:2584] uid/euid:101/101 gid/egid:247/247
[  162.101752] grsec: From 127.0.0.6: denied RWX mmap of <anonymous mapping> by /usr/bin/rspamd-1.3.5[rspamd:2589] uid/euid:101/101 gid/egid:247/247, parent /usr/bin/rspamd-1.3.5[rspamd:2584] uid/euid:101/101 gid/egid:247/247
[  162.101783] grsec: more alerts, logging disabled for 10 seconds
[  169.204753] PAX: From 127.0.0.6: execution attempt in: <anonymous mapping>, 331becee000-331becfe000 331becee000
[  169.204759] PAX: terminating task: /usr/bin/rspamd-1.3.5(rspamd):2590, uid/euid: 101/101, PC: 00000331becfdfd2, SP: 0000039dec3795d0
[  169.204764] PAX: bytes at PC: c7 04 25 a0 a4 11 41 01 00 00 00 83 7a 14 ff 0f 85 29 00 ff 
[  169.204779] PAX: bytes at SP-8: 000000004111a378 000000000053eac9 000000004111a450 0000000000000001 00000000022cbea0 0000000000000001 4111a3784111a378 0000000000000000 00000000022cbea0 0000000000000001 0000000000000000 
[  169.211249] rspamd (2590) used greatest stack depth: 12168 bytes left
[  170.379327] PAX: From 127.0.0.6: execution attempt in: <anonymous mapping>, 331becfe000-331bed0e000 331becfe000
[  170.379332] PAX: terminating task: /usr/bin/rspamd-1.3.5(rspamd):2589, uid/euid: 101/101, PC: 00000331bed0df9b, SP: 0000039dec37a1c0
[  170.379335] PAX: bytes at PC: c7 04 25 a0 a4 11 41 01 00 00 00 8b 6a f8 8b 7d 14 8b 6f 10 
[  170.379359] PAX: bytes at SP-8: 000000004111af70 00000000401a45f0 00000331c05d64fd 0000000000000001 0000000002192cc0 0000000800000000 401a45784111a378 0000000000000000 0000000000000000 00000000407c7fd0 0000000000000000
```

After disabling the MPROTECT:
`paxctl -m /usr/bin/rspamd`
RSPAMD works, but GRSEC is still complaining:
```
[  299.327661] grsec: From 185.33.138.174: denied RWX mmap of <anonymous mapping> by /usr/bin/rspamadm-1.3.5[rspamadm:2657] uid/euid:0/0 gid/egid:0/0, parent /lib64/rc/sh/openrc-run.sh[openrc-run.sh:2641] uid/euid:0/0 gid/egid:0/0
[  299.327707] grsec: From 185.33.138.174: denied RWX mmap of <anonymous mapping> by /usr/bin/rspamadm-1.3.5[rspamadm:2657] uid/euid:0/0 gid/egid:0/0, parent /lib64/rc/sh/openrc-run.sh[openrc-run.sh:2641] uid/euid:0/0 gid/egid:0/0
[  299.327762] grsec: From 185.33.138.174: denied RWX mmap of <anonymous mapping> by /usr/bin/rspamadm-1.3.5[rspamadm:2657] uid/euid:0/0 gid/egid:0/0, parent /lib64/rc/sh/openrc-run.sh[openrc-run.sh:2641] uid/euid:0/0 gid/egid:0/0
```

I can live with that but it would be nice to have RSPAMD in compliance with GRSEC.

**Comment by vstakhov** [comment]
Rspamd is not intended to run with W^X restrictions as it uses luajit, hyperscan and pcre-jit which all are incompatible with W^X. You can replace luajit with lua, disable hyperscan and disable jit in pcre. Anyway, that's not Rspamd related issue.

**Comment by jhejl** [comment]
Thank you, i can live with that for now, disabling these features downgrades the functionality of the RSPAMD, which is unwanted.

**Comment by vstakhov** [comment]
It will reduce speed not functionality.

**Comment by jviiret** [comment]
@vstakhov Actually, I think Hyperscan should work on systems with W^X restrictions -- it doesn't use JIT techniques, etc.
